.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestBTR_RW

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestBTR_RW:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         bt      ax,0
         bc      TestBTR_RWErr
         cmp     ax,0x0000
         bne     TestBTR_RWErr
         mov     ax,0x0000
         btr     ax,0
         bc      TestBTR_RWErr
         cmp     ax,0x0000
         bne     TestBTR_RWErr
         mov     ax,0x0000
         bts     ax,0
         bc      TestBTR_RWErr
         cmp     ax,0x0001
         bne     TestBTR_RWErr
                 
         mov     bx,0x0000
         bt      bx,1
         bc      TestBTR_RWErr
         cmp     bx,0x0000
         bne     TestBTR_RWErr
         mov     bx,0x0000
         btr     bx,1
         bc      TestBTR_RWErr
         cmp     bx,0x0000
         bne     TestBTR_RWErr
         mov     bx,0x0000
         bts     bx,1
         bc      TestBTR_RWErr
         cmp     bx,0x0002
         bne     TestBTR_RWErr
                 
         mov     cx,0x0000
         bt      cx,2
         bc      TestBTR_RWErr
         cmp     cx,0x0000
         bne     TestBTR_RWErr
         mov     cx,0x0000
         btr     cx,2
         bc      TestBTR_RWErr
         cmp     cx,0x0000
         bne     TestBTR_RWErr
         mov     cx,0x0000
         bts     cx,2
         bc      TestBTR_RWErr
         cmp     cx,0x0004
         bne     TestBTR_RWErr
                 
         mov     dx,0x0000
         bt      dx,3
         bc      TestBTR_RWErr
         cmp     dx,0x0000
         bne     TestBTR_RWErr
         mov     dx,0x0000
         btr     dx,3
         bc      TestBTR_RWErr
         cmp     dx,0x0000
         bne     TestBTR_RWErr
         mov     dx,0x0000
         bts     dx,3
         bc      TestBTR_RWErr
         cmp     dx,0x0008
         bne     TestBTR_RWErr
                 
         mov     ex,0x0000
         bt      ex,4
         bc      TestBTR_RWErr
         cmp     ex,0x0000
         bne     TestBTR_RWErr
         mov     ex,0x0000
         btr     ex,4
         bc      TestBTR_RWErr
         cmp     ex,0x0000
         bne     TestBTR_RWErr
         mov     ex,0x0000
         bts     ex,4
         bc      TestBTR_RWErr
         cmp     ex,0x0010
         bne     TestBTR_RWErr
                 
         mov     fx,0x0000
         bt      fx,5
         bc      TestBTR_RWErr
         cmp     fx,0x0000
         bne     TestBTR_RWErr
         mov     fx,0x0000
         btr     fx,5
         bc      TestBTR_RWErr
         cmp     fx,0x0000
         bne     TestBTR_RWErr
         mov     fx,0x0000
         bts     fx,5
         bc      TestBTR_RWErr
         cmp     fx,0x0020
         bne     TestBTR_RWErr
                 
         mov     gx,0x0000
         bt      gx,6
         bc      TestBTR_RWErr
         cmp     gx,0x0000
         bne     TestBTR_RWErr
         mov     gx,0x0000
         btr     gx,6
         bc      TestBTR_RWErr
         cmp     gx,0x0000
         bne     TestBTR_RWErr
         mov     gx,0x0000
         bts     gx,6
         bc      TestBTR_RWErr
         cmp     gx,0x0040
         bne     TestBTR_RWErr
                 
         mov     aw,0x0000
         bt      aw,7
         bc      TestBTR_RWErr
         cmp     aw,0x0000
         bne     TestBTR_RWErr
         mov     aw,0x0000
         btr     aw,7
         bc      TestBTR_RWErr
         cmp     aw,0x0000
         bne     TestBTR_RWErr
         mov     aw,0x0000
         bts     aw,7
         bc      TestBTR_RWErr
         cmp     aw,0x0080
         bne     TestBTR_RWErr
                 
         mov     bw,0x0000
         bt      bw,8
         bc      TestBTR_RWErr
         cmp     bw,0x0000
         bne     TestBTR_RWErr
         mov     bw,0x0000
         btr     bw,8
         bc      TestBTR_RWErr
         cmp     bw,0x0000
         bne     TestBTR_RWErr
         mov     bw,0x0000
         bts     bw,8
         bc      TestBTR_RWErr
         cmp     bw,0x0100
         bne     TestBTR_RWErr
                 
         mov     cw,0x0000
         bt      cw,9
         bc      TestBTR_RWErr
         cmp     cw,0x0000
         bne     TestBTR_RWErr
         mov     cw,0x0000
         btr     cw,9
         bc      TestBTR_RWErr
         cmp     cw,0x0000
         bne     TestBTR_RWErr
         mov     cw,0x0000
         bts     cw,9
         bc      TestBTR_RWErr
         cmp     cw,0x0200
         bne     TestBTR_RWErr
                 
         mov     dw,0x0000
         bt      dw,10
         bc      TestBTR_RWErr
         cmp     dw,0x0000
         bne     TestBTR_RWErr
         mov     dw,0x0000
         btr     dw,10
         bc      TestBTR_RWErr
         cmp     dw,0x0000
         bne     TestBTR_RWErr
         mov     dw,0x0000
         bts     dw,10
         bc      TestBTR_RWErr
         cmp     dw,0x0400
         bne     TestBTR_RWErr
                 
         mov     ew,0x0000
         bt      ew,11
         bc      TestBTR_RWErr
         cmp     ew,0x0000
         bne     TestBTR_RWErr
         mov     ew,0x0000
         btr     ew,11
         bc      TestBTR_RWErr
         cmp     ew,0x0000
         bne     TestBTR_RWErr
         mov     ew,0x0000
         bts     ew,11
         bc      TestBTR_RWErr
         cmp     ew,0x0800
         bne     TestBTR_RWErr
                 
         mov     fw,0x0000
         bt      fw,12
         bc      TestBTR_RWErr
         cmp     fw,0x0000
         bne     TestBTR_RWErr
         mov     fw,0x0000
         btr     fw,12
         bc      TestBTR_RWErr
         cmp     fw,0x0000
         bne     TestBTR_RWErr
         mov     fw,0x0000
         bts     fw,12
         bc      TestBTR_RWErr
         cmp     fw,0x1000
         bne     TestBTR_RWErr
                 
         mov     gw,0x0000
         bt      gw,13
         bc      TestBTR_RWErr
         cmp     gw,0x0000
         bne     TestBTR_RWErr
         mov     gw,0x0000
         btr     gw,13
         bc      TestBTR_RWErr
         cmp     gw,0x0000
         bne     TestBTR_RWErr
         mov     gw,0x0000
         bts     gw,13
         bc      TestBTR_RWErr
         cmp     gw,0x2000
         bne     TestBTR_RWErr
                 
         mov     ax,0x0000
         bt      ax,14
         bc      TestBTR_RWErr
         cmp     ax,0x0000
         bne     TestBTR_RWErr
         mov     ax,0x0000
         btr     ax,14
         bc      TestBTR_RWErr
         cmp     ax,0x0000
         bne     TestBTR_RWErr
         mov     ax,0x0000
         bts     ax,14
         bc      TestBTR_RWErr
         cmp     ax,0x4000
         bne     TestBTR_RWErr
                 
         mov     bx,0x0000
         bt      bx,15
         bc      TestBTR_RWErr
         cmp     bx,0x0000
         bne     TestBTR_RWErr
         mov     bx,0x0000
         btr     bx,15
         bc      TestBTR_RWErr
         cmp     bx,0x0000
         bne     TestBTR_RWErr
         mov     bx,0x0000
         bts     bx,15
         bc      TestBTR_RWErr
         cmp     bx,0x8000
         bne     TestBTR_RWErr
                 
         mov     cx,0x0001
         bt      cx,0
         bnc     TestBTR_RWErr
         cmp     cx,0x0001
         bne     TestBTR_RWErr
         mov     cx,0x0001
         btr     cx,0
         bnc     TestBTR_RWErr
         cmp     cx,0x0000
         bne     TestBTR_RWErr
         mov     cx,0x0001
         bts     cx,0
         bnc     TestBTR_RWErr
         cmp     cx,0x0001
         bne     TestBTR_RWErr
                 
         mov     dx,0x0001
         bt      dx,1
         bc      TestBTR_RWErr
         cmp     dx,0x0001
         bne     TestBTR_RWErr
         mov     dx,0x0001
         btr     dx,1
         bc      TestBTR_RWErr
         cmp     dx,0x0001
         bne     TestBTR_RWErr
         mov     dx,0x0001
         bts     dx,1
         bc      TestBTR_RWErr
         cmp     dx,0x0003
         bne     TestBTR_RWErr
                 
         mov     ex,0x0001
         bt      ex,2
         bc      TestBTR_RWErr
         cmp     ex,0x0001
         bne     TestBTR_RWErr
         mov     ex,0x0001
         btr     ex,2
         bc      TestBTR_RWErr
         cmp     ex,0x0001
         bne     TestBTR_RWErr
         mov     ex,0x0001
         bts     ex,2
         bc      TestBTR_RWErr
         cmp     ex,0x0005
         bne     TestBTR_RWErr
                 
         mov     fx,0x0001
         bt      fx,3
         bc      TestBTR_RWErr
         cmp     fx,0x0001
         bne     TestBTR_RWErr
         mov     fx,0x0001
         btr     fx,3
         bc      TestBTR_RWErr
         cmp     fx,0x0001
         bne     TestBTR_RWErr
         mov     fx,0x0001
         bts     fx,3
         bc      TestBTR_RWErr
         cmp     fx,0x0009
         bne     TestBTR_RWErr
                 
         mov     gx,0x0001
         bt      gx,4
         bc      TestBTR_RWErr
         cmp     gx,0x0001
         bne     TestBTR_RWErr
         mov     gx,0x0001
         btr     gx,4
         bc      TestBTR_RWErr
         cmp     gx,0x0001
         bne     TestBTR_RWErr
         mov     gx,0x0001
         bts     gx,4
         bc      TestBTR_RWErr
         cmp     gx,0x0011
         bne     TestBTR_RWErr
                 
         mov     aw,0x0001
         bt      aw,5
         bc      TestBTR_RWErr
         cmp     aw,0x0001
         bne     TestBTR_RWErr
         mov     aw,0x0001
         btr     aw,5
         bc      TestBTR_RWErr
         cmp     aw,0x0001
         bne     TestBTR_RWErr
         mov     aw,0x0001
         bts     aw,5
         bc      TestBTR_RWErr
         cmp     aw,0x0021
         bne     TestBTR_RWErr
                 
         mov     bw,0x0001
         bt      bw,6
         bc      TestBTR_RWErr
         cmp     bw,0x0001
         bne     TestBTR_RWErr
         mov     bw,0x0001
         btr     bw,6
         bc      TestBTR_RWErr
         cmp     bw,0x0001
         bne     TestBTR_RWErr
         mov     bw,0x0001
         bts     bw,6
         bc      TestBTR_RWErr
         cmp     bw,0x0041
         bne     TestBTR_RWErr
                 
         mov     cw,0x0001
         bt      cw,7
         bc      TestBTR_RWErr
         cmp     cw,0x0001
         bne     TestBTR_RWErr
         mov     cw,0x0001
         btr     cw,7
         bc      TestBTR_RWErr
         cmp     cw,0x0001
         bne     TestBTR_RWErr
         mov     cw,0x0001
         bts     cw,7
         bc      TestBTR_RWErr
         cmp     cw,0x0081
         bne     TestBTR_RWErr
                 
         mov     dw,0x0001
         bt      dw,8
         bc      TestBTR_RWErr
         cmp     dw,0x0001
         bne     TestBTR_RWErr
         mov     dw,0x0001
         btr     dw,8
         bc      TestBTR_RWErr
         cmp     dw,0x0001
         bne     TestBTR_RWErr
         mov     dw,0x0001
         bts     dw,8
         bc      TestBTR_RWErr
         cmp     dw,0x0101
         bne     TestBTR_RWErr
                 
         mov     ew,0x0001
         bt      ew,9
         bc      TestBTR_RWErr
         cmp     ew,0x0001
         bne     TestBTR_RWErr
         mov     ew,0x0001
         btr     ew,9
         bc      TestBTR_RWErr
         cmp     ew,0x0001
         bne     TestBTR_RWErr
         mov     ew,0x0001
         bts     ew,9
         bc      TestBTR_RWErr
         cmp     ew,0x0201
         bne     TestBTR_RWErr
                 
         mov     fw,0x0001
         bt      fw,10
         bc      TestBTR_RWErr
         cmp     fw,0x0001
         bne     TestBTR_RWErr
         mov     fw,0x0001
         btr     fw,10
         bc      TestBTR_RWErr
         cmp     fw,0x0001
         bne     TestBTR_RWErr
         mov     fw,0x0001
         bts     fw,10
         bc      TestBTR_RWErr
         cmp     fw,0x0401
         bne     TestBTR_RWErr
                 
         mov     gw,0x0001
         bt      gw,11
         bc      TestBTR_RWErr
         cmp     gw,0x0001
         bne     TestBTR_RWErr
         mov     gw,0x0001
         btr     gw,11
         bc      TestBTR_RWErr
         cmp     gw,0x0001
         bne     TestBTR_RWErr
         mov     gw,0x0001
         bts     gw,11
         bc      TestBTR_RWErr
         cmp     gw,0x0801
         bne     TestBTR_RWErr
                 
         mov     ax,0x0001
         bt      ax,12
         bc      TestBTR_RWErr
         cmp     ax,0x0001
         bne     TestBTR_RWErr
         mov     ax,0x0001
         btr     ax,12
         bc      TestBTR_RWErr
         cmp     ax,0x0001
         bne     TestBTR_RWErr
         mov     ax,0x0001
         bts     ax,12
         bc      TestBTR_RWErr
         cmp     ax,0x1001
         bne     TestBTR_RWErr
                 
         mov     bx,0x0001
         bt      bx,13
         bc      TestBTR_RWErr
         cmp     bx,0x0001
         bne     TestBTR_RWErr
         mov     bx,0x0001
         btr     bx,13
         bc      TestBTR_RWErr
         cmp     bx,0x0001
         bne     TestBTR_RWErr
         mov     bx,0x0001
         bts     bx,13
         bc      TestBTR_RWErr
         cmp     bx,0x2001
         bne     TestBTR_RWErr
                 
         mov     cx,0x0001
         bt      cx,14
         bc      TestBTR_RWErr
         cmp     cx,0x0001
         bne     TestBTR_RWErr
         mov     cx,0x0001
         btr     cx,14
         bc      TestBTR_RWErr
         cmp     cx,0x0001
         bne     TestBTR_RWErr
         mov     cx,0x0001
         bts     cx,14
         bc      TestBTR_RWErr
         cmp     cx,0x4001
         bne     TestBTR_RWErr
                 
         mov     dx,0x0001
         bt      dx,15
         bc      TestBTR_RWErr
         cmp     dx,0x0001
         bne     TestBTR_RWErr
         mov     dx,0x0001
         btr     dx,15
         bc      TestBTR_RWErr
         cmp     dx,0x0001
         bne     TestBTR_RWErr
         mov     dx,0x0001
         bts     dx,15
         bc      TestBTR_RWErr
         cmp     dx,0x8001
         bne     TestBTR_RWErr
                 
         mov     ex,0x0008
         bt      ex,0
         bc      TestBTR_RWErr
         cmp     ex,0x0008
         bne     TestBTR_RWErr
         mov     ex,0x0008
         btr     ex,0
         bc      TestBTR_RWErr
         cmp     ex,0x0008
         bne     TestBTR_RWErr
         mov     ex,0x0008
         bts     ex,0
         bc      TestBTR_RWErr
         cmp     ex,0x0009
         bne     TestBTR_RWErr
                 
         mov     fx,0x0008
         bt      fx,1
         bc      TestBTR_RWErr
         cmp     fx,0x0008
         bne     TestBTR_RWErr
         mov     fx,0x0008
         btr     fx,1
         bc      TestBTR_RWErr
         cmp     fx,0x0008
         bne     TestBTR_RWErr
         mov     fx,0x0008
         bts     fx,1
         bc      TestBTR_RWErr
         cmp     fx,0x000A
         bne     TestBTR_RWErr
                 
         mov     gx,0x0008
         bt      gx,2
         bc      TestBTR_RWErr
         cmp     gx,0x0008
         bne     TestBTR_RWErr
         mov     gx,0x0008
         btr     gx,2
         bc      TestBTR_RWErr
         cmp     gx,0x0008
         bne     TestBTR_RWErr
         mov     gx,0x0008
         bts     gx,2
         bc      TestBTR_RWErr
         cmp     gx,0x000C
         bne     TestBTR_RWErr
                 
         mov     aw,0x0008
         bt      aw,3
         bnc     TestBTR_RWErr
         cmp     aw,0x0008
         bne     TestBTR_RWErr
         mov     aw,0x0008
         btr     aw,3
         bnc     TestBTR_RWErr
         cmp     aw,0x0000
         bne     TestBTR_RWErr
         mov     aw,0x0008
         bts     aw,3
         bnc     TestBTR_RWErr
         cmp     aw,0x0008
         bne     TestBTR_RWErr
                 
         mov     bw,0x0008
         bt      bw,4
         bc      TestBTR_RWErr
         cmp     bw,0x0008
         bne     TestBTR_RWErr
         mov     bw,0x0008
         btr     bw,4
         bc      TestBTR_RWErr
         cmp     bw,0x0008
         bne     TestBTR_RWErr
         mov     bw,0x0008
         bts     bw,4
         bc      TestBTR_RWErr
         cmp     bw,0x0018
         bne     TestBTR_RWErr
                 
         mov     cw,0x0008
         bt      cw,5
         bc      TestBTR_RWErr
         cmp     cw,0x0008
         bne     TestBTR_RWErr
         mov     cw,0x0008
         btr     cw,5
         bc      TestBTR_RWErr
         cmp     cw,0x0008
         bne     TestBTR_RWErr
         mov     cw,0x0008
         bts     cw,5
         bc      TestBTR_RWErr
         cmp     cw,0x0028
         bne     TestBTR_RWErr
                 
         mov     dw,0x0008
         bt      dw,6
         bc      TestBTR_RWErr
         cmp     dw,0x0008
         bne     TestBTR_RWErr
         mov     dw,0x0008
         btr     dw,6
         bc      TestBTR_RWErr
         cmp     dw,0x0008
         bne     TestBTR_RWErr
         mov     dw,0x0008
         bts     dw,6
         bc      TestBTR_RWErr
         cmp     dw,0x0048
         bne     TestBTR_RWErr
                 
         mov     ew,0x0008
         bt      ew,7
         bc      TestBTR_RWErr
         cmp     ew,0x0008
         bne     TestBTR_RWErr
         mov     ew,0x0008
         btr     ew,7
         bc      TestBTR_RWErr
         cmp     ew,0x0008
         bne     TestBTR_RWErr
         mov     ew,0x0008
         bts     ew,7
         bc      TestBTR_RWErr
         cmp     ew,0x0088
         bne     TestBTR_RWErr
                 
         mov     fw,0x0008
         bt      fw,8
         bc      TestBTR_RWErr
         cmp     fw,0x0008
         bne     TestBTR_RWErr
         mov     fw,0x0008
         btr     fw,8
         bc      TestBTR_RWErr
         cmp     fw,0x0008
         bne     TestBTR_RWErr
         mov     fw,0x0008
         bts     fw,8
         bc      TestBTR_RWErr
         cmp     fw,0x0108
         bne     TestBTR_RWErr
                 
         mov     gw,0x0008
         bt      gw,9
         bc      TestBTR_RWErr
         cmp     gw,0x0008
         bne     TestBTR_RWErr
         mov     gw,0x0008
         btr     gw,9
         bc      TestBTR_RWErr
         cmp     gw,0x0008
         bne     TestBTR_RWErr
         mov     gw,0x0008
         bts     gw,9
         bc      TestBTR_RWErr
         cmp     gw,0x0208
         bne     TestBTR_RWErr
                 
         mov     ax,0x0008
         bt      ax,10
         bc      TestBTR_RWErr
         cmp     ax,0x0008
         bne     TestBTR_RWErr
         mov     ax,0x0008
         btr     ax,10
         bc      TestBTR_RWErr
         cmp     ax,0x0008
         bne     TestBTR_RWErr
         mov     ax,0x0008
         bts     ax,10
         bc      TestBTR_RWErr
         cmp     ax,0x0408
         bne     TestBTR_RWErr
                 
         mov     bx,0x0008
         bt      bx,11
         bc      TestBTR_RWErr
         cmp     bx,0x0008
         bne     TestBTR_RWErr
         mov     bx,0x0008
         btr     bx,11
         bc      TestBTR_RWErr
         cmp     bx,0x0008
         bne     TestBTR_RWErr
         mov     bx,0x0008
         bts     bx,11
         bc      TestBTR_RWErr
         cmp     bx,0x0808
         bne     TestBTR_RWErr
                 
         mov     cx,0x0008
         bt      cx,12
         bc      TestBTR_RWErr
         cmp     cx,0x0008
         bne     TestBTR_RWErr
         mov     cx,0x0008
         btr     cx,12
         bc      TestBTR_RWErr
         cmp     cx,0x0008
         bne     TestBTR_RWErr
         mov     cx,0x0008
         bts     cx,12
         bc      TestBTR_RWErr
         cmp     cx,0x1008
         bne     TestBTR_RWErr
                 
         mov     dx,0x0008
         bt      dx,13
         bc      TestBTR_RWErr
         cmp     dx,0x0008
         bne     TestBTR_RWErr
         mov     dx,0x0008
         btr     dx,13
         bc      TestBTR_RWErr
         cmp     dx,0x0008
         bne     TestBTR_RWErr
         mov     dx,0x0008
         bts     dx,13
         bc      TestBTR_RWErr
         cmp     dx,0x2008
         bne     TestBTR_RWErr
                 
         mov     ex,0x0008
         bt      ex,14
         bc      TestBTR_RWErr
         cmp     ex,0x0008
         bne     TestBTR_RWErr
         mov     ex,0x0008
         btr     ex,14
         bc      TestBTR_RWErr
         cmp     ex,0x0008
         bne     TestBTR_RWErr
         mov     ex,0x0008
         bts     ex,14
         bc      TestBTR_RWErr
         cmp     ex,0x4008
         bne     TestBTR_RWErr
                 
         mov     fx,0x0008
         bt      fx,15
         bc      TestBTR_RWErr
         cmp     fx,0x0008
         bne     TestBTR_RWErr
         mov     fx,0x0008
         btr     fx,15
         bc      TestBTR_RWErr
         cmp     fx,0x0008
         bne     TestBTR_RWErr
         mov     fx,0x0008
         bts     fx,15
         bc      TestBTR_RWErr
         cmp     fx,0x8008
         bne     TestBTR_RWErr
                 
         mov     gx,0x0009
         bt      gx,0
         bnc     TestBTR_RWErr
         cmp     gx,0x0009
         bne     TestBTR_RWErr
         mov     gx,0x0009
         btr     gx,0
         bnc     TestBTR_RWErr
         cmp     gx,0x0008
         bne     TestBTR_RWErr
         mov     gx,0x0009
         bts     gx,0
         bnc     TestBTR_RWErr
         cmp     gx,0x0009
         bne     TestBTR_RWErr
                 
         mov     aw,0x0009
         bt      aw,1
         bc      TestBTR_RWErr
         cmp     aw,0x0009
         bne     TestBTR_RWErr
         mov     aw,0x0009
         btr     aw,1
         bc      TestBTR_RWErr
         cmp     aw,0x0009
         bne     TestBTR_RWErr
         mov     aw,0x0009
         bts     aw,1
         bc      TestBTR_RWErr
         cmp     aw,0x000B
         bne     TestBTR_RWErr
                 
         mov     bw,0x0009
         bt      bw,2
         bc      TestBTR_RWErr
         cmp     bw,0x0009
         bne     TestBTR_RWErr
         mov     bw,0x0009
         btr     bw,2
         bc      TestBTR_RWErr
         cmp     bw,0x0009
         bne     TestBTR_RWErr
         mov     bw,0x0009
         bts     bw,2
         bc      TestBTR_RWErr
         cmp     bw,0x000D
         bne     TestBTR_RWErr
                 
         mov     cw,0x0009
         bt      cw,3
         bnc     TestBTR_RWErr
         cmp     cw,0x0009
         bne     TestBTR_RWErr
         mov     cw,0x0009
         btr     cw,3
         bnc     TestBTR_RWErr
         cmp     cw,0x0001
         bne     TestBTR_RWErr
         mov     cw,0x0009
         bts     cw,3
         bnc     TestBTR_RWErr
         cmp     cw,0x0009
         bne     TestBTR_RWErr
                 
         mov     dw,0x0009
         bt      dw,4
         bc      TestBTR_RWErr
         cmp     dw,0x0009
         bne     TestBTR_RWErr
         mov     dw,0x0009
         btr     dw,4
         bc      TestBTR_RWErr
         cmp     dw,0x0009
         bne     TestBTR_RWErr
         mov     dw,0x0009
         bts     dw,4
         bc      TestBTR_RWErr
         cmp     dw,0x0019
         bne     TestBTR_RWErr
                 
         mov     ew,0x0009
         bt      ew,5
         bc      TestBTR_RWErr
         cmp     ew,0x0009
         bne     TestBTR_RWErr
         mov     ew,0x0009
         btr     ew,5
         bc      TestBTR_RWErr
         cmp     ew,0x0009
         bne     TestBTR_RWErr
         mov     ew,0x0009
         bts     ew,5
         bc      TestBTR_RWErr
         cmp     ew,0x0029
         bne     TestBTR_RWErr
                 
         mov     fw,0x0009
         bt      fw,6
         bc      TestBTR_RWErr
         cmp     fw,0x0009
         bne     TestBTR_RWErr
         mov     fw,0x0009
         btr     fw,6
         bc      TestBTR_RWErr
         cmp     fw,0x0009
         bne     TestBTR_RWErr
         mov     fw,0x0009
         bts     fw,6
         bc      TestBTR_RWErr
         cmp     fw,0x0049
         bne     TestBTR_RWErr
                 
         mov     gw,0x0009
         bt      gw,7
         bc      TestBTR_RWErr
         cmp     gw,0x0009
         bne     TestBTR_RWErr
         mov     gw,0x0009
         btr     gw,7
         bc      TestBTR_RWErr
         cmp     gw,0x0009
         bne     TestBTR_RWErr
         mov     gw,0x0009
         bts     gw,7
         bc      TestBTR_RWErr
         cmp     gw,0x0089
         bne     TestBTR_RWErr
                 
         mov     ax,0x0009
         bt      ax,8
         bc      TestBTR_RWErr
         cmp     ax,0x0009
         bne     TestBTR_RWErr
         mov     ax,0x0009
         btr     ax,8
         bc      TestBTR_RWErr
         cmp     ax,0x0009
         bne     TestBTR_RWErr
         mov     ax,0x0009
         bts     ax,8
         bc      TestBTR_RWErr
         cmp     ax,0x0109
         bne     TestBTR_RWErr
                 
         mov     bx,0x0009
         bt      bx,9
         bc      TestBTR_RWErr
         cmp     bx,0x0009
         bne     TestBTR_RWErr
         mov     bx,0x0009
         btr     bx,9
         bc      TestBTR_RWErr
         cmp     bx,0x0009
         bne     TestBTR_RWErr
         mov     bx,0x0009
         bts     bx,9
         bc      TestBTR_RWErr
         cmp     bx,0x0209
         bne     TestBTR_RWErr
                 
         mov     cx,0x0009
         bt      cx,10
         bc      TestBTR_RWErr
         cmp     cx,0x0009
         bne     TestBTR_RWErr
         mov     cx,0x0009
         btr     cx,10
         bc      TestBTR_RWErr
         cmp     cx,0x0009
         bne     TestBTR_RWErr
         mov     cx,0x0009
         bts     cx,10
         bc      TestBTR_RWErr
         cmp     cx,0x0409
         bne     TestBTR_RWErr
                 
         mov     dx,0x0009
         bt      dx,11
         bc      TestBTR_RWErr
         cmp     dx,0x0009
         bne     TestBTR_RWErr
         mov     dx,0x0009
         btr     dx,11
         bc      TestBTR_RWErr
         cmp     dx,0x0009
         bne     TestBTR_RWErr
         mov     dx,0x0009
         bts     dx,11
         bc      TestBTR_RWErr
         cmp     dx,0x0809
         bne     TestBTR_RWErr
                 
         mov     ex,0x0009
         bt      ex,12
         bc      TestBTR_RWErr
         cmp     ex,0x0009
         bne     TestBTR_RWErr
         mov     ex,0x0009
         btr     ex,12
         bc      TestBTR_RWErr
         cmp     ex,0x0009
         bne     TestBTR_RWErr
         mov     ex,0x0009
         bts     ex,12
         bc      TestBTR_RWErr
         cmp     ex,0x1009
         bne     TestBTR_RWErr
                 
         mov     fx,0x0009
         bt      fx,13
         bc      TestBTR_RWErr
         cmp     fx,0x0009
         bne     TestBTR_RWErr
         mov     fx,0x0009
         btr     fx,13
         bc      TestBTR_RWErr
         cmp     fx,0x0009
         bne     TestBTR_RWErr
         mov     fx,0x0009
         bts     fx,13
         bc      TestBTR_RWErr
         cmp     fx,0x2009
         bne     TestBTR_RWErr
                 
         mov     gx,0x0009
         bt      gx,14
         bc      TestBTR_RWErr
         cmp     gx,0x0009
         bne     TestBTR_RWErr
         mov     gx,0x0009
         btr     gx,14
         bc      TestBTR_RWErr
         cmp     gx,0x0009
         bne     TestBTR_RWErr
         mov     gx,0x0009
         bts     gx,14
         bc      TestBTR_RWErr
         cmp     gx,0x4009
         bne     TestBTR_RWErr
                 
         mov     aw,0x0009
         bt      aw,15
         bc      TestBTR_RWErr
         cmp     aw,0x0009
         bne     TestBTR_RWErr
         mov     aw,0x0009
         btr     aw,15
         bc      TestBTR_RWErr
         cmp     aw,0x0009
         bne     TestBTR_RWErr
         mov     aw,0x0009
         bts     aw,15
         bc      TestBTR_RWErr
         cmp     aw,0x8009
         bne     TestBTR_RWErr
                 
         mov     bw,0x007F
         bt      bw,0
         bnc     TestBTR_RWErr
         cmp     bw,0x007F
         bne     TestBTR_RWErr
         mov     bw,0x007F
         btr     bw,0
         bnc     TestBTR_RWErr
         cmp     bw,0x007E
         bne     TestBTR_RWErr
         mov     bw,0x007F
         bts     bw,0
         bnc     TestBTR_RWErr
         cmp     bw,0x007F
         bne     TestBTR_RWErr
                 
         mov     cw,0x007F
         bt      cw,1
         bnc     TestBTR_RWErr
         cmp     cw,0x007F
         bne     TestBTR_RWErr
         mov     cw,0x007F
         btr     cw,1
         bnc     TestBTR_RWErr
         cmp     cw,0x007D
         bne     TestBTR_RWErr
         mov     cw,0x007F
         bts     cw,1
         bnc     TestBTR_RWErr
         cmp     cw,0x007F
         bne     TestBTR_RWErr
                 
         mov     dw,0x007F
         bt      dw,2
         bnc     TestBTR_RWErr
         cmp     dw,0x007F
         bne     TestBTR_RWErr
         mov     dw,0x007F
         btr     dw,2
         bnc     TestBTR_RWErr
         cmp     dw,0x007B
         bne     TestBTR_RWErr
         mov     dw,0x007F
         bts     dw,2
         bnc     TestBTR_RWErr
         cmp     dw,0x007F
         bne     TestBTR_RWErr
                 
         mov     ew,0x007F
         bt      ew,3
         bnc     TestBTR_RWErr
         cmp     ew,0x007F
         bne     TestBTR_RWErr
         mov     ew,0x007F
         btr     ew,3
         bnc     TestBTR_RWErr
         cmp     ew,0x0077
         bne     TestBTR_RWErr
         mov     ew,0x007F
         bts     ew,3
         bnc     TestBTR_RWErr
         cmp     ew,0x007F
         bne     TestBTR_RWErr
                 
         mov     fw,0x007F
         bt      fw,4
         bnc     TestBTR_RWErr
         cmp     fw,0x007F
         bne     TestBTR_RWErr
         mov     fw,0x007F
         btr     fw,4
         bnc     TestBTR_RWErr
         cmp     fw,0x006F
         bne     TestBTR_RWErr
         mov     fw,0x007F
         bts     fw,4
         bnc     TestBTR_RWErr
         cmp     fw,0x007F
         bne     TestBTR_RWErr
                 
         mov     gw,0x007F
         bt      gw,5
         bnc     TestBTR_RWErr
         cmp     gw,0x007F
         bne     TestBTR_RWErr
         mov     gw,0x007F
         btr     gw,5
         bnc     TestBTR_RWErr
         cmp     gw,0x005F
         bne     TestBTR_RWErr
         mov     gw,0x007F
         bts     gw,5
         bnc     TestBTR_RWErr
         cmp     gw,0x007F
         bne     TestBTR_RWErr
                 
         mov     ax,0x007F
         bt      ax,6
         bnc     TestBTR_RWErr
         cmp     ax,0x007F
         bne     TestBTR_RWErr
         mov     ax,0x007F
         btr     ax,6
         bnc     TestBTR_RWErr
         cmp     ax,0x003F
         bne     TestBTR_RWErr
         mov     ax,0x007F
         bts     ax,6
         bnc     TestBTR_RWErr
         cmp     ax,0x007F
         bne     TestBTR_RWErr
                 
         mov     bx,0x007F
         bt      bx,7
         bc      TestBTR_RWErr
         cmp     bx,0x007F
         bne     TestBTR_RWErr
         mov     bx,0x007F
         btr     bx,7
         bc      TestBTR_RWErr
         cmp     bx,0x007F
         bne     TestBTR_RWErr
         mov     bx,0x007F
         bts     bx,7
         bc      TestBTR_RWErr
         cmp     bx,0x00FF
         bne     TestBTR_RWErr
                 
         mov     cx,0x007F
         bt      cx,8
         bc      TestBTR_RWErr
         cmp     cx,0x007F
         bne     TestBTR_RWErr
         mov     cx,0x007F
         btr     cx,8
         bc      TestBTR_RWErr
         cmp     cx,0x007F
         bne     TestBTR_RWErr
         mov     cx,0x007F
         bts     cx,8
         bc      TestBTR_RWErr
         cmp     cx,0x017F
         bne     TestBTR_RWErr
                 
         mov     dx,0x007F
         bt      dx,9
         bc      TestBTR_RWErr
         cmp     dx,0x007F
         bne     TestBTR_RWErr
         mov     dx,0x007F
         btr     dx,9
         bc      TestBTR_RWErr
         cmp     dx,0x007F
         bne     TestBTR_RWErr
         mov     dx,0x007F
         bts     dx,9
         bc      TestBTR_RWErr
         cmp     dx,0x027F
         bne     TestBTR_RWErr
                 
         mov     ex,0x007F
         bt      ex,10
         bc      TestBTR_RWErr
         cmp     ex,0x007F
         bne     TestBTR_RWErr
         mov     ex,0x007F
         btr     ex,10
         bc      TestBTR_RWErr
         cmp     ex,0x007F
         bne     TestBTR_RWErr
         mov     ex,0x007F
         bts     ex,10
         bc      TestBTR_RWErr
         cmp     ex,0x047F
         bne     TestBTR_RWErr
                 
         mov     fx,0x007F
         bt      fx,11
         bc      TestBTR_RWErr
         cmp     fx,0x007F
         bne     TestBTR_RWErr
         mov     fx,0x007F
         btr     fx,11
         bc      TestBTR_RWErr
         cmp     fx,0x007F
         bne     TestBTR_RWErr
         mov     fx,0x007F
         bts     fx,11
         bc      TestBTR_RWErr
         cmp     fx,0x087F
         bne     TestBTR_RWErr
                 
         mov     gx,0x007F
         bt      gx,12
         bc      TestBTR_RWErr
         cmp     gx,0x007F
         bne     TestBTR_RWErr
         mov     gx,0x007F
         btr     gx,12
         bc      TestBTR_RWErr
         cmp     gx,0x007F
         bne     TestBTR_RWErr
         mov     gx,0x007F
         bts     gx,12
         bc      TestBTR_RWErr
         cmp     gx,0x107F
         bne     TestBTR_RWErr
                 
         mov     aw,0x007F
         bt      aw,13
         bc      TestBTR_RWErr
         cmp     aw,0x007F
         bne     TestBTR_RWErr
         mov     aw,0x007F
         btr     aw,13
         bc      TestBTR_RWErr
         cmp     aw,0x007F
         bne     TestBTR_RWErr
         mov     aw,0x007F
         bts     aw,13
         bc      TestBTR_RWErr
         cmp     aw,0x207F
         bne     TestBTR_RWErr
                 
         mov     bw,0x007F
         bt      bw,14
         bc      TestBTR_RWErr
         cmp     bw,0x007F
         bne     TestBTR_RWErr
         mov     bw,0x007F
         btr     bw,14
         bc      TestBTR_RWErr
         cmp     bw,0x007F
         bne     TestBTR_RWErr
         mov     bw,0x007F
         bts     bw,14
         bc      TestBTR_RWErr
         cmp     bw,0x407F
         bne     TestBTR_RWErr
                 
         mov     cw,0x007F
         bt      cw,15
         bc      TestBTR_RWErr
         cmp     cw,0x007F
         bne     TestBTR_RWErr
         mov     cw,0x007F
         btr     cw,15
         bc      TestBTR_RWErr
         cmp     cw,0x007F
         bne     TestBTR_RWErr
         mov     cw,0x007F
         bts     cw,15
         bc      TestBTR_RWErr
         cmp     cw,0x807F
         bne     TestBTR_RWErr
                 
         mov     dw,0x0080
         bt      dw,0
         bc      TestBTR_RWErr
         cmp     dw,0x0080
         bne     TestBTR_RWErr
         mov     dw,0x0080
         btr     dw,0
         bc      TestBTR_RWErr
         cmp     dw,0x0080
         bne     TestBTR_RWErr
         mov     dw,0x0080
         bts     dw,0
         bc      TestBTR_RWErr
         cmp     dw,0x0081
         bne     TestBTR_RWErr
                 
         mov     ew,0x0080
         bt      ew,1
         bc      TestBTR_RWErr
         cmp     ew,0x0080
         bne     TestBTR_RWErr
         mov     ew,0x0080
         btr     ew,1
         bc      TestBTR_RWErr
         cmp     ew,0x0080
         bne     TestBTR_RWErr
         mov     ew,0x0080
         bts     ew,1
         bc      TestBTR_RWErr
         cmp     ew,0x0082
         bne     TestBTR_RWErr
                 
         mov     fw,0x0080
         bt      fw,2
         bc      TestBTR_RWErr
         cmp     fw,0x0080
         bne     TestBTR_RWErr
         mov     fw,0x0080
         btr     fw,2
         bc      TestBTR_RWErr
         cmp     fw,0x0080
         bne     TestBTR_RWErr
         mov     fw,0x0080
         bts     fw,2
         bc      TestBTR_RWErr
         cmp     fw,0x0084
         bne     TestBTR_RWErr
                 
         mov     gw,0x0080
         bt      gw,3
         bc      TestBTR_RWErr
         cmp     gw,0x0080
         bne     TestBTR_RWErr
         mov     gw,0x0080
         btr     gw,3
         bc      TestBTR_RWErr
         cmp     gw,0x0080
         bne     TestBTR_RWErr
         mov     gw,0x0080
         bts     gw,3
         bc      TestBTR_RWErr
         cmp     gw,0x0088
         bne     TestBTR_RWErr
                 
         mov     ax,0x0080
         bt      ax,4
         bc      TestBTR_RWErr
         cmp     ax,0x0080
         bne     TestBTR_RWErr
         mov     ax,0x0080
         btr     ax,4
         bc      TestBTR_RWErr
         cmp     ax,0x0080
         bne     TestBTR_RWErr
         mov     ax,0x0080
         bts     ax,4
         bc      TestBTR_RWErr
         cmp     ax,0x0090
         bne     TestBTR_RWErr
                 
         mov     bx,0x0080
         bt      bx,5
         bc      TestBTR_RWErr
         cmp     bx,0x0080
         bne     TestBTR_RWErr
         mov     bx,0x0080
         btr     bx,5
         bc      TestBTR_RWErr
         cmp     bx,0x0080
         bne     TestBTR_RWErr
         mov     bx,0x0080
         bts     bx,5
         bc      TestBTR_RWErr
         cmp     bx,0x00A0
         bne     TestBTR_RWErr
                 
         mov     cx,0x0080
         bt      cx,6
         bc      TestBTR_RWErr
         cmp     cx,0x0080
         bne     TestBTR_RWErr
         mov     cx,0x0080
         btr     cx,6
         bc      TestBTR_RWErr
         cmp     cx,0x0080
         bne     TestBTR_RWErr
         mov     cx,0x0080
         bts     cx,6
         bc      TestBTR_RWErr
         cmp     cx,0x00C0
         bne     TestBTR_RWErr
                 
         mov     dx,0x0080
         bt      dx,7
         bnc     TestBTR_RWErr
         cmp     dx,0x0080
         bne     TestBTR_RWErr
         mov     dx,0x0080
         btr     dx,7
         bnc     TestBTR_RWErr
         cmp     dx,0x0000
         bne     TestBTR_RWErr
         mov     dx,0x0080
         bts     dx,7
         bnc     TestBTR_RWErr
         cmp     dx,0x0080
         bne     TestBTR_RWErr
                 
         mov     ex,0x0080
         bt      ex,8
         bc      TestBTR_RWErr
         cmp     ex,0x0080
         bne     TestBTR_RWErr
         mov     ex,0x0080
         btr     ex,8
         bc      TestBTR_RWErr
         cmp     ex,0x0080
         bne     TestBTR_RWErr
         mov     ex,0x0080
         bts     ex,8
         bc      TestBTR_RWErr
         cmp     ex,0x0180
         bne     TestBTR_RWErr
                 
         mov     fx,0x0080
         bt      fx,9
         bc      TestBTR_RWErr
         cmp     fx,0x0080
         bne     TestBTR_RWErr
         mov     fx,0x0080
         btr     fx,9
         bc      TestBTR_RWErr
         cmp     fx,0x0080
         bne     TestBTR_RWErr
         mov     fx,0x0080
         bts     fx,9
         bc      TestBTR_RWErr
         cmp     fx,0x0280
         bne     TestBTR_RWErr
                 
         mov     gx,0x0080
         bt      gx,10
         bc      TestBTR_RWErr
         cmp     gx,0x0080
         bne     TestBTR_RWErr
         mov     gx,0x0080
         btr     gx,10
         bc      TestBTR_RWErr
         cmp     gx,0x0080
         bne     TestBTR_RWErr
         mov     gx,0x0080
         bts     gx,10
         bc      TestBTR_RWErr
         cmp     gx,0x0480
         bne     TestBTR_RWErr
                 
         mov     aw,0x0080
         bt      aw,11
         bc      TestBTR_RWErr
         cmp     aw,0x0080
         bne     TestBTR_RWErr
         mov     aw,0x0080
         btr     aw,11
         bc      TestBTR_RWErr
         cmp     aw,0x0080
         bne     TestBTR_RWErr
         mov     aw,0x0080
         bts     aw,11
         bc      TestBTR_RWErr
         cmp     aw,0x0880
         bne     TestBTR_RWErr
                 
         mov     bw,0x0080
         bt      bw,12
         bc      TestBTR_RWErr
         cmp     bw,0x0080
         bne     TestBTR_RWErr
         mov     bw,0x0080
         btr     bw,12
         bc      TestBTR_RWErr
         cmp     bw,0x0080
         bne     TestBTR_RWErr
         mov     bw,0x0080
         bts     bw,12
         bc      TestBTR_RWErr
         cmp     bw,0x1080
         bne     TestBTR_RWErr
                 
         mov     cw,0x0080
         bt      cw,13
         bc      TestBTR_RWErr
         cmp     cw,0x0080
         bne     TestBTR_RWErr
         mov     cw,0x0080
         btr     cw,13
         bc      TestBTR_RWErr
         cmp     cw,0x0080
         bne     TestBTR_RWErr
         mov     cw,0x0080
         bts     cw,13
         bc      TestBTR_RWErr
         cmp     cw,0x2080
         bne     TestBTR_RWErr
                 
         mov     dw,0x0080
         bt      dw,14
         bc      TestBTR_RWErr
         cmp     dw,0x0080
         bne     TestBTR_RWErr
         mov     dw,0x0080
         btr     dw,14
         bc      TestBTR_RWErr
         cmp     dw,0x0080
         bne     TestBTR_RWErr
         mov     dw,0x0080
         bts     dw,14
         bc      TestBTR_RWErr
         cmp     dw,0x4080
         bne     TestBTR_RWErr
                 
         mov     ew,0x0080
         bt      ew,15
         bc      TestBTR_RWErr
         cmp     ew,0x0080
         bne     TestBTR_RWErr
         mov     ew,0x0080
         btr     ew,15
         bc      TestBTR_RWErr
         cmp     ew,0x0080
         bne     TestBTR_RWErr
         mov     ew,0x0080
         bts     ew,15
         bc      TestBTR_RWErr
         cmp     ew,0x8080
         bne     TestBTR_RWErr
                 
         mov     fw,0x7FFF
         bt      fw,0
         bnc     TestBTR_RWErr
         cmp     fw,0x7FFF
         bne     TestBTR_RWErr
         mov     fw,0x7FFF
         btr     fw,0
         bnc     TestBTR_RWErr
         cmp     fw,0x7FFE
         bne     TestBTR_RWErr
         mov     fw,0x7FFF
         bts     fw,0
         bnc     TestBTR_RWErr
         cmp     fw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     gw,0x7FFF
         bt      gw,1
         bnc     TestBTR_RWErr
         cmp     gw,0x7FFF
         bne     TestBTR_RWErr
         mov     gw,0x7FFF
         btr     gw,1
         bnc     TestBTR_RWErr
         cmp     gw,0x7FFD
         bne     TestBTR_RWErr
         mov     gw,0x7FFF
         bts     gw,1
         bnc     TestBTR_RWErr
         cmp     gw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     ax,0x7FFF
         bt      ax,2
         bnc     TestBTR_RWErr
         cmp     ax,0x7FFF
         bne     TestBTR_RWErr
         mov     ax,0x7FFF
         btr     ax,2
         bnc     TestBTR_RWErr
         cmp     ax,0x7FFB
         bne     TestBTR_RWErr
         mov     ax,0x7FFF
         bts     ax,2
         bnc     TestBTR_RWErr
         cmp     ax,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     bx,0x7FFF
         bt      bx,3
         bnc     TestBTR_RWErr
         cmp     bx,0x7FFF
         bne     TestBTR_RWErr
         mov     bx,0x7FFF
         btr     bx,3
         bnc     TestBTR_RWErr
         cmp     bx,0x7FF7
         bne     TestBTR_RWErr
         mov     bx,0x7FFF
         bts     bx,3
         bnc     TestBTR_RWErr
         cmp     bx,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     cx,0x7FFF
         bt      cx,4
         bnc     TestBTR_RWErr
         cmp     cx,0x7FFF
         bne     TestBTR_RWErr
         mov     cx,0x7FFF
         btr     cx,4
         bnc     TestBTR_RWErr
         cmp     cx,0x7FEF
         bne     TestBTR_RWErr
         mov     cx,0x7FFF
         bts     cx,4
         bnc     TestBTR_RWErr
         cmp     cx,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     dx,0x7FFF
         bt      dx,5
         bnc     TestBTR_RWErr
         cmp     dx,0x7FFF
         bne     TestBTR_RWErr
         mov     dx,0x7FFF
         btr     dx,5
         bnc     TestBTR_RWErr
         cmp     dx,0x7FDF
         bne     TestBTR_RWErr
         mov     dx,0x7FFF
         bts     dx,5
         bnc     TestBTR_RWErr
         cmp     dx,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     ex,0x7FFF
         bt      ex,6
         bnc     TestBTR_RWErr
         cmp     ex,0x7FFF
         bne     TestBTR_RWErr
         mov     ex,0x7FFF
         btr     ex,6
         bnc     TestBTR_RWErr
         cmp     ex,0x7FBF
         bne     TestBTR_RWErr
         mov     ex,0x7FFF
         bts     ex,6
         bnc     TestBTR_RWErr
         cmp     ex,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     fx,0x7FFF
         bt      fx,7
         bnc     TestBTR_RWErr
         cmp     fx,0x7FFF
         bne     TestBTR_RWErr
         mov     fx,0x7FFF
         btr     fx,7
         bnc     TestBTR_RWErr
         cmp     fx,0x7F7F
         bne     TestBTR_RWErr
         mov     fx,0x7FFF
         bts     fx,7
         bnc     TestBTR_RWErr
         cmp     fx,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     gx,0x7FFF
         bt      gx,8
         bnc     TestBTR_RWErr
         cmp     gx,0x7FFF
         bne     TestBTR_RWErr
         mov     gx,0x7FFF
         btr     gx,8
         bnc     TestBTR_RWErr
         cmp     gx,0x7EFF
         bne     TestBTR_RWErr
         mov     gx,0x7FFF
         bts     gx,8
         bnc     TestBTR_RWErr
         cmp     gx,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     aw,0x7FFF
         bt      aw,9
         bnc     TestBTR_RWErr
         cmp     aw,0x7FFF
         bne     TestBTR_RWErr
         mov     aw,0x7FFF
         btr     aw,9
         bnc     TestBTR_RWErr
         cmp     aw,0x7DFF
         bne     TestBTR_RWErr
         mov     aw,0x7FFF
         bts     aw,9
         bnc     TestBTR_RWErr
         cmp     aw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     bw,0x7FFF
         bt      bw,10
         bnc     TestBTR_RWErr
         cmp     bw,0x7FFF
         bne     TestBTR_RWErr
         mov     bw,0x7FFF
         btr     bw,10
         bnc     TestBTR_RWErr
         cmp     bw,0x7BFF
         bne     TestBTR_RWErr
         mov     bw,0x7FFF
         bts     bw,10
         bnc     TestBTR_RWErr
         cmp     bw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     cw,0x7FFF
         bt      cw,11
         bnc     TestBTR_RWErr
         cmp     cw,0x7FFF
         bne     TestBTR_RWErr
         mov     cw,0x7FFF
         btr     cw,11
         bnc     TestBTR_RWErr
         cmp     cw,0x77FF
         bne     TestBTR_RWErr
         mov     cw,0x7FFF
         bts     cw,11
         bnc     TestBTR_RWErr
         cmp     cw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     dw,0x7FFF
         bt      dw,12
         bnc     TestBTR_RWErr
         cmp     dw,0x7FFF
         bne     TestBTR_RWErr
         mov     dw,0x7FFF
         btr     dw,12
         bnc     TestBTR_RWErr
         cmp     dw,0x6FFF
         bne     TestBTR_RWErr
         mov     dw,0x7FFF
         bts     dw,12
         bnc     TestBTR_RWErr
         cmp     dw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     ew,0x7FFF
         bt      ew,13
         bnc     TestBTR_RWErr
         cmp     ew,0x7FFF
         bne     TestBTR_RWErr
         mov     ew,0x7FFF
         btr     ew,13
         bnc     TestBTR_RWErr
         cmp     ew,0x5FFF
         bne     TestBTR_RWErr
         mov     ew,0x7FFF
         bts     ew,13
         bnc     TestBTR_RWErr
         cmp     ew,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     fw,0x7FFF
         bt      fw,14
         bnc     TestBTR_RWErr
         cmp     fw,0x7FFF
         bne     TestBTR_RWErr
         mov     fw,0x7FFF
         btr     fw,14
         bnc     TestBTR_RWErr
         cmp     fw,0x3FFF
         bne     TestBTR_RWErr
         mov     fw,0x7FFF
         bts     fw,14
         bnc     TestBTR_RWErr
         cmp     fw,0x7FFF
         bne     TestBTR_RWErr
                 
         mov     gw,0x7FFF
         bt      gw,15
         bc      TestBTR_RWErr
         cmp     gw,0x7FFF
         bne     TestBTR_RWErr
         mov     gw,0x7FFF
         btr     gw,15
         bc      TestBTR_RWErr
         cmp     gw,0x7FFF
         bne     TestBTR_RWErr
         mov     gw,0x7FFF
         bts     gw,15
         bc      TestBTR_RWErr
         cmp     gw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     ax,0x8000
         bt      ax,0
         bc      TestBTR_RWErr
         cmp     ax,0x8000
         bne     TestBTR_RWErr
         mov     ax,0x8000
         btr     ax,0
         bc      TestBTR_RWErr
         cmp     ax,0x8000
         bne     TestBTR_RWErr
         mov     ax,0x8000
         bts     ax,0
         bc      TestBTR_RWErr
         cmp     ax,0x8001
         bne     TestBTR_RWErr
                 
         mov     bx,0x8000
         bt      bx,1
         bc      TestBTR_RWErr
         cmp     bx,0x8000
         bne     TestBTR_RWErr
         mov     bx,0x8000
         btr     bx,1
         bc      TestBTR_RWErr
         cmp     bx,0x8000
         bne     TestBTR_RWErr
         mov     bx,0x8000
         bts     bx,1
         bc      TestBTR_RWErr
         cmp     bx,0x8002
         bne     TestBTR_RWErr
                 
         mov     cx,0x8000
         bt      cx,2
         bc      TestBTR_RWErr
         cmp     cx,0x8000
         bne     TestBTR_RWErr
         mov     cx,0x8000
         btr     cx,2
         bc      TestBTR_RWErr
         cmp     cx,0x8000
         bne     TestBTR_RWErr
         mov     cx,0x8000
         bts     cx,2
         bc      TestBTR_RWErr
         cmp     cx,0x8004
         bne     TestBTR_RWErr
                 
         mov     dx,0x8000
         bt      dx,3
         bc      TestBTR_RWErr
         cmp     dx,0x8000
         bne     TestBTR_RWErr
         mov     dx,0x8000
         btr     dx,3
         bc      TestBTR_RWErr
         cmp     dx,0x8000
         bne     TestBTR_RWErr
         mov     dx,0x8000
         bts     dx,3
         bc      TestBTR_RWErr
         cmp     dx,0x8008
         bne     TestBTR_RWErr
                 
         mov     ex,0x8000
         bt      ex,4
         bc      TestBTR_RWErr
         cmp     ex,0x8000
         bne     TestBTR_RWErr
         mov     ex,0x8000
         btr     ex,4
         bc      TestBTR_RWErr
         cmp     ex,0x8000
         bne     TestBTR_RWErr
         mov     ex,0x8000
         bts     ex,4
         bc      TestBTR_RWErr
         cmp     ex,0x8010
         bne     TestBTR_RWErr
                 
         mov     fx,0x8000
         bt      fx,5
         bc      TestBTR_RWErr
         cmp     fx,0x8000
         bne     TestBTR_RWErr
         mov     fx,0x8000
         btr     fx,5
         bc      TestBTR_RWErr
         cmp     fx,0x8000
         bne     TestBTR_RWErr
         mov     fx,0x8000
         bts     fx,5
         bc      TestBTR_RWErr
         cmp     fx,0x8020
         bne     TestBTR_RWErr
                 
         mov     gx,0x8000
         bt      gx,6
         bc      TestBTR_RWErr
         cmp     gx,0x8000
         bne     TestBTR_RWErr
         mov     gx,0x8000
         btr     gx,6
         bc      TestBTR_RWErr
         cmp     gx,0x8000
         bne     TestBTR_RWErr
         mov     gx,0x8000
         bts     gx,6
         bc      TestBTR_RWErr
         cmp     gx,0x8040
         bne     TestBTR_RWErr
                 
         mov     aw,0x8000
         bt      aw,7
         bc      TestBTR_RWErr
         cmp     aw,0x8000
         bne     TestBTR_RWErr
         mov     aw,0x8000
         btr     aw,7
         bc      TestBTR_RWErr
         cmp     aw,0x8000
         bne     TestBTR_RWErr
         mov     aw,0x8000
         bts     aw,7
         bc      TestBTR_RWErr
         cmp     aw,0x8080
         bne     TestBTR_RWErr
                 
         mov     bw,0x8000
         bt      bw,8
         bc      TestBTR_RWErr
         cmp     bw,0x8000
         bne     TestBTR_RWErr
         mov     bw,0x8000
         btr     bw,8
         bc      TestBTR_RWErr
         cmp     bw,0x8000
         bne     TestBTR_RWErr
         mov     bw,0x8000
         bts     bw,8
         bc      TestBTR_RWErr
         cmp     bw,0x8100
         bne     TestBTR_RWErr
                 
         mov     cw,0x8000
         bt      cw,9
         bc      TestBTR_RWErr
         cmp     cw,0x8000
         bne     TestBTR_RWErr
         mov     cw,0x8000
         btr     cw,9
         bc      TestBTR_RWErr
         cmp     cw,0x8000
         bne     TestBTR_RWErr
         mov     cw,0x8000
         bts     cw,9
         bc      TestBTR_RWErr
         cmp     cw,0x8200
         bne     TestBTR_RWErr
                 
         mov     dw,0x8000
         bt      dw,10
         bc      TestBTR_RWErr
         cmp     dw,0x8000
         bne     TestBTR_RWErr
         mov     dw,0x8000
         btr     dw,10
         bc      TestBTR_RWErr
         cmp     dw,0x8000
         bne     TestBTR_RWErr
         mov     dw,0x8000
         bts     dw,10
         bc      TestBTR_RWErr
         cmp     dw,0x8400
         bne     TestBTR_RWErr
                 
         mov     ew,0x8000
         bt      ew,11
         bc      TestBTR_RWErr
         cmp     ew,0x8000
         bne     TestBTR_RWErr
         mov     ew,0x8000
         btr     ew,11
         bc      TestBTR_RWErr
         cmp     ew,0x8000
         bne     TestBTR_RWErr
         mov     ew,0x8000
         bts     ew,11
         bc      TestBTR_RWErr
         cmp     ew,0x8800
         bne     TestBTR_RWErr
                 
         mov     fw,0x8000
         bt      fw,12
         bc      TestBTR_RWErr
         cmp     fw,0x8000
         bne     TestBTR_RWErr
         mov     fw,0x8000
         btr     fw,12
         bc      TestBTR_RWErr
         cmp     fw,0x8000
         bne     TestBTR_RWErr
         mov     fw,0x8000
         bts     fw,12
         bc      TestBTR_RWErr
         cmp     fw,0x9000
         bne     TestBTR_RWErr
                 
         mov     gw,0x8000
         bt      gw,13
         bc      TestBTR_RWErr
         cmp     gw,0x8000
         bne     TestBTR_RWErr
         mov     gw,0x8000
         btr     gw,13
         bc      TestBTR_RWErr
         cmp     gw,0x8000
         bne     TestBTR_RWErr
         mov     gw,0x8000
         bts     gw,13
         bc      TestBTR_RWErr
         cmp     gw,0xA000
         bne     TestBTR_RWErr
                 
         mov     ax,0x8000
         bt      ax,14
         bc      TestBTR_RWErr
         cmp     ax,0x8000
         bne     TestBTR_RWErr
         mov     ax,0x8000
         btr     ax,14
         bc      TestBTR_RWErr
         cmp     ax,0x8000
         bne     TestBTR_RWErr
         mov     ax,0x8000
         bts     ax,14
         bc      TestBTR_RWErr
         cmp     ax,0xC000
         bne     TestBTR_RWErr
                 
         mov     bx,0x8000
         bt      bx,15
         bnc     TestBTR_RWErr
         cmp     bx,0x8000
         bne     TestBTR_RWErr
         mov     bx,0x8000
         btr     bx,15
         bnc     TestBTR_RWErr
         cmp     bx,0x0000
         bne     TestBTR_RWErr
         mov     bx,0x8000
         bts     bx,15
         bnc     TestBTR_RWErr
         cmp     bx,0x8000
         bne     TestBTR_RWErr
                 
         mov     cx,0xFFFF
         bt      cx,0
         bnc     TestBTR_RWErr
         cmp     cx,0xFFFF
         bne     TestBTR_RWErr
         mov     cx,0xFFFF
         btr     cx,0
         bnc     TestBTR_RWErr
         cmp     cx,0xFFFE
         bne     TestBTR_RWErr
         mov     cx,0xFFFF
         bts     cx,0
         bnc     TestBTR_RWErr
         cmp     cx,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     dx,0xFFFF
         bt      dx,1
         bnc     TestBTR_RWErr
         cmp     dx,0xFFFF
         bne     TestBTR_RWErr
         mov     dx,0xFFFF
         btr     dx,1
         bnc     TestBTR_RWErr
         cmp     dx,0xFFFD
         bne     TestBTR_RWErr
         mov     dx,0xFFFF
         bts     dx,1
         bnc     TestBTR_RWErr
         cmp     dx,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     ex,0xFFFF
         bt      ex,2
         bnc     TestBTR_RWErr
         cmp     ex,0xFFFF
         bne     TestBTR_RWErr
         mov     ex,0xFFFF
         btr     ex,2
         bnc     TestBTR_RWErr
         cmp     ex,0xFFFB
         bne     TestBTR_RWErr
         mov     ex,0xFFFF
         bts     ex,2
         bnc     TestBTR_RWErr
         cmp     ex,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     fx,0xFFFF
         bt      fx,3
         bnc     TestBTR_RWErr
         cmp     fx,0xFFFF
         bne     TestBTR_RWErr
         mov     fx,0xFFFF
         btr     fx,3
         bnc     TestBTR_RWErr
         cmp     fx,0xFFF7
         bne     TestBTR_RWErr
         mov     fx,0xFFFF
         bts     fx,3
         bnc     TestBTR_RWErr
         cmp     fx,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     gx,0xFFFF
         bt      gx,4
         bnc     TestBTR_RWErr
         cmp     gx,0xFFFF
         bne     TestBTR_RWErr
         mov     gx,0xFFFF
         btr     gx,4
         bnc     TestBTR_RWErr
         cmp     gx,0xFFEF
         bne     TestBTR_RWErr
         mov     gx,0xFFFF
         bts     gx,4
         bnc     TestBTR_RWErr
         cmp     gx,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     aw,0xFFFF
         bt      aw,5
         bnc     TestBTR_RWErr
         cmp     aw,0xFFFF
         bne     TestBTR_RWErr
         mov     aw,0xFFFF
         btr     aw,5
         bnc     TestBTR_RWErr
         cmp     aw,0xFFDF
         bne     TestBTR_RWErr
         mov     aw,0xFFFF
         bts     aw,5
         bnc     TestBTR_RWErr
         cmp     aw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     bw,0xFFFF
         bt      bw,6
         bnc     TestBTR_RWErr
         cmp     bw,0xFFFF
         bne     TestBTR_RWErr
         mov     bw,0xFFFF
         btr     bw,6
         bnc     TestBTR_RWErr
         cmp     bw,0xFFBF
         bne     TestBTR_RWErr
         mov     bw,0xFFFF
         bts     bw,6
         bnc     TestBTR_RWErr
         cmp     bw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     cw,0xFFFF
         bt      cw,7
         bnc     TestBTR_RWErr
         cmp     cw,0xFFFF
         bne     TestBTR_RWErr
         mov     cw,0xFFFF
         btr     cw,7
         bnc     TestBTR_RWErr
         cmp     cw,0xFF7F
         bne     TestBTR_RWErr
         mov     cw,0xFFFF
         bts     cw,7
         bnc     TestBTR_RWErr
         cmp     cw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     dw,0xFFFF
         bt      dw,8
         bnc     TestBTR_RWErr
         cmp     dw,0xFFFF
         bne     TestBTR_RWErr
         mov     dw,0xFFFF
         btr     dw,8
         bnc     TestBTR_RWErr
         cmp     dw,0xFEFF
         bne     TestBTR_RWErr
         mov     dw,0xFFFF
         bts     dw,8
         bnc     TestBTR_RWErr
         cmp     dw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     ew,0xFFFF
         bt      ew,9
         bnc     TestBTR_RWErr
         cmp     ew,0xFFFF
         bne     TestBTR_RWErr
         mov     ew,0xFFFF
         btr     ew,9
         bnc     TestBTR_RWErr
         cmp     ew,0xFDFF
         bne     TestBTR_RWErr
         mov     ew,0xFFFF
         bts     ew,9
         bnc     TestBTR_RWErr
         cmp     ew,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     fw,0xFFFF
         bt      fw,10
         bnc     TestBTR_RWErr
         cmp     fw,0xFFFF
         bne     TestBTR_RWErr
         mov     fw,0xFFFF
         btr     fw,10
         bnc     TestBTR_RWErr
         cmp     fw,0xFBFF
         bne     TestBTR_RWErr
         mov     fw,0xFFFF
         bts     fw,10
         bnc     TestBTR_RWErr
         cmp     fw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     gw,0xFFFF
         bt      gw,11
         bnc     TestBTR_RWErr
         cmp     gw,0xFFFF
         bne     TestBTR_RWErr
         mov     gw,0xFFFF
         btr     gw,11
         bnc     TestBTR_RWErr
         cmp     gw,0xF7FF
         bne     TestBTR_RWErr
         mov     gw,0xFFFF
         bts     gw,11
         bnc     TestBTR_RWErr
         cmp     gw,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     ax,0xFFFF
         bt      ax,12
         bnc     TestBTR_RWErr
         cmp     ax,0xFFFF
         bne     TestBTR_RWErr
         mov     ax,0xFFFF
         btr     ax,12
         bnc     TestBTR_RWErr
         cmp     ax,0xEFFF
         bne     TestBTR_RWErr
         mov     ax,0xFFFF
         bts     ax,12
         bnc     TestBTR_RWErr
         cmp     ax,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     bx,0xFFFF
         bt      bx,13
         bnc     TestBTR_RWErr
         cmp     bx,0xFFFF
         bne     TestBTR_RWErr
         mov     bx,0xFFFF
         btr     bx,13
         bnc     TestBTR_RWErr
         cmp     bx,0xDFFF
         bne     TestBTR_RWErr
         mov     bx,0xFFFF
         bts     bx,13
         bnc     TestBTR_RWErr
         cmp     bx,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     cx,0xFFFF
         bt      cx,14
         bnc     TestBTR_RWErr
         cmp     cx,0xFFFF
         bne     TestBTR_RWErr
         mov     cx,0xFFFF
         btr     cx,14
         bnc     TestBTR_RWErr
         cmp     cx,0xBFFF
         bne     TestBTR_RWErr
         mov     cx,0xFFFF
         bts     cx,14
         bnc     TestBTR_RWErr
         cmp     cx,0xFFFF
         bne     TestBTR_RWErr
                 
         mov     dx,0xFFFF
         bt      dx,15
         bnc     TestBTR_RWErr
         cmp     dx,0xFFFF
         bne     TestBTR_RWErr
         mov     dx,0xFFFF
         btr     dx,15
         bnc     TestBTR_RWErr
         cmp     dx,0x7FFF
         bne     TestBTR_RWErr
         mov     dx,0xFFFF
         bts     dx,15
         bnc     TestBTR_RWErr
         cmp     dx,0xFFFF
         bne     TestBTR_RWErr
                 
         bra     TestBTR_RWRet
TestBTR_RWErr:
         nop     
         trap    
         nop     
TestBTR_RWRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
