.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BBWS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BBWS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cx,0x0000
         addsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x00
         mov     dx,0x0000
         subsx   fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0x00
         mov     ex,0x0000
         andsx   gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x00
         mov     fx,0x0000
         orsx    ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x00
         mov     gx,0x0000
         xorsx   bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x00
         mov     aw,0x0000
         mulsx   ch,fl,aw
         cmp     ch,0x00
         bne     TestArus_BBWSErr
         mov     gl,0x00
         mov     bw,0x0000
         sdivsx  dh,gl,bw
         cmp     dh,0xFF
         bne     TestArus_BBWSErr
         mov     ah,0x00
         mov     cw,0x0000
         sremsx  eh,ah,cw
         cmp     eh,0x00
         bne     TestArus_BBWSErr
         mov     bh,0x00
         mov     dw,0x0001
         addsx   fh,bh,dw
         cmp     fh,0x01
         bne     TestArus_BBWSErr
         mov     ch,0x00
         mov     ew,0x0001
         subsx   gh,ch,ew
         cmp     gh,0xFF
         bne     TestArus_BBWSErr
         mov     dh,0x00
         mov     fw,0x0001
         andsx   al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x00
         mov     gw,0x0001
         orsx    bl,eh,gw
         cmp     bl,0x01
         bne     TestArus_BBWSErr
         mov     fh,0x00
         mov     ax,0x0001
         xorsx   cl,fh,ax
         cmp     cl,0x01
         bne     TestArus_BBWSErr
         mov     gh,0x00
         mov     bx,0x0001
         mulsx   dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x00
         mov     cx,0x0001
         sdivsx  el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x00
         mov     dx,0x0001
         sremsx  fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0x00
         mov     ex,0x0008
         addsx   gl,cl,ex
         cmp     gl,0x08
         bne     TestArus_BBWSErr
         mov     dl,0x00
         mov     fx,0x0008
         subsx   ah,dl,fx
         cmp     ah,0xF8
         bne     TestArus_BBWSErr
         mov     el,0x00
         mov     gx,0x0008
         andsx   bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x00
         mov     aw,0x0008
         orsx    ch,fl,aw
         cmp     ch,0x08
         bne     TestArus_BBWSErr
         mov     gl,0x00
         mov     bw,0x0008
         xorsx   dh,gl,bw
         cmp     dh,0x08
         bne     TestArus_BBWSErr
         mov     ah,0x00
         mov     cw,0x0008
         mulsx   eh,ah,cw
         cmp     eh,0x00
         bne     TestArus_BBWSErr
         mov     bh,0x00
         mov     dw,0x0008
         sdivsx  fh,bh,dw
         cmp     fh,0x00
         bne     TestArus_BBWSErr
         mov     ch,0x00
         mov     ew,0x0008
         sremsx  gh,ch,ew
         cmp     gh,0x00
         bne     TestArus_BBWSErr
         mov     dh,0x00
         mov     fw,0x0009
         addsx   al,dh,fw
         cmp     al,0x09
         bne     TestArus_BBWSErr
         mov     eh,0x00
         mov     gw,0x0009
         subsx   bl,eh,gw
         cmp     bl,0xF7
         bne     TestArus_BBWSErr
         mov     fh,0x00
         mov     ax,0x0009
         andsx   cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x00
         mov     bx,0x0009
         orsx    dl,gh,bx
         cmp     dl,0x09
         bne     TestArus_BBWSErr
         mov     al,0x00
         mov     cx,0x0009
         xorsx   el,al,cx
         cmp     el,0x09
         bne     TestArus_BBWSErr
         mov     bl,0x00
         mov     dx,0x0009
         mulsx   fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0x00
         mov     ex,0x0009
         sdivsx  gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x00
         mov     fx,0x0009
         sremsx  ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x00
         mov     gx,0x007F
         addsx   bh,el,gx
         cmp     bh,0x7F
         bne     TestArus_BBWSErr
         mov     fl,0x00
         mov     aw,0x007F
         subsx   ch,fl,aw
         cmp     ch,0x81
         bne     TestArus_BBWSErr
         mov     gl,0x00
         mov     bw,0x007F
         andsx   dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x00
         mov     cw,0x007F
         orsx    eh,ah,cw
         cmp     eh,0x7F
         bne     TestArus_BBWSErr
         mov     bh,0x00
         mov     dw,0x007F
         xorsx   fh,bh,dw
         cmp     fh,0x7F
         bne     TestArus_BBWSErr
         mov     ch,0x00
         mov     ew,0x007F
         mulsx   gh,ch,ew
         cmp     gh,0x00
         bne     TestArus_BBWSErr
         mov     dh,0x00
         mov     fw,0x007F
         sdivsx  al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x00
         mov     gw,0x007F
         sremsx  bl,eh,gw
         cmp     bl,0x00
         bne     TestArus_BBWSErr
         mov     fh,0x00
         mov     ax,0x0080
         addsx   cl,fh,ax
         cmp     cl,0x80
         bne     TestArus_BBWSErr
         mov     gh,0x00
         mov     bx,0x0080
         subsx   dl,gh,bx
         cmp     dl,0x80
         bne     TestArus_BBWSErr
         mov     al,0x00
         mov     cx,0x0080
         andsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x00
         mov     dx,0x0080
         orsx    fl,bl,dx
         cmp     fl,0x80
         bne     TestArus_BBWSErr
         mov     cl,0x00
         mov     ex,0x0080
         xorsx   gl,cl,ex
         cmp     gl,0x80
         bne     TestArus_BBWSErr
         mov     dl,0x00
         mov     fx,0x0080
         mulsx   ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x00
         mov     gx,0x0080
         sdivsx  bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x00
         mov     aw,0x0080
         sremsx  ch,fl,aw
         cmp     ch,0x00
         bne     TestArus_BBWSErr
         mov     gl,0x00
         mov     bw,0x7FFF
         addsx   dh,gl,bw
         cmp     dh,0xFF
         bne     TestArus_BBWSErr
         mov     ah,0x00
         mov     cw,0x7FFF
         subsx   eh,ah,cw
         cmp     eh,0x01
         bne     TestArus_BBWSErr
         mov     bh,0x00
         mov     dw,0x7FFF
         andsx   fh,bh,dw
         cmp     fh,0x00
         bne     TestArus_BBWSErr
         mov     ch,0x00
         mov     ew,0x7FFF
         orsx    gh,ch,ew
         cmp     gh,0xFF
         bne     TestArus_BBWSErr
         mov     dh,0x00
         mov     fw,0x7FFF
         xorsx   al,dh,fw
         cmp     al,0xFF
         bne     TestArus_BBWSErr
         mov     eh,0x00
         mov     gw,0x7FFF
         mulsx   bl,eh,gw
         cmp     bl,0x00
         bne     TestArus_BBWSErr
         mov     fh,0x00
         mov     ax,0x7FFF
         sdivsx  cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x00
         mov     bx,0x7FFF
         sremsx  dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x00
         mov     cx,0x8000
         addsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x00
         mov     dx,0x8000
         subsx   fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0x00
         mov     ex,0x8000
         andsx   gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x00
         mov     fx,0x8000
         orsx    ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x00
         mov     gx,0x8000
         xorsx   bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x00
         mov     aw,0x8000
         mulsx   ch,fl,aw
         cmp     ch,0x00
         bne     TestArus_BBWSErr
         mov     gl,0x00
         mov     bw,0x8000
         sdivsx  dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x00
         mov     cw,0x8000
         sremsx  eh,ah,cw
         cmp     eh,0x00
         bne     TestArus_BBWSErr
         mov     bh,0x00
         mov     dw,0xFFFF
         addsx   fh,bh,dw
         cmp     fh,0xFF
         bne     TestArus_BBWSErr
         mov     ch,0x00
         mov     ew,0xFFFF
         subsx   gh,ch,ew
         cmp     gh,0x01
         bne     TestArus_BBWSErr
         mov     dh,0x00
         mov     fw,0xFFFF
         andsx   al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x00
         mov     gw,0xFFFF
         orsx    bl,eh,gw
         cmp     bl,0xFF
         bne     TestArus_BBWSErr
         mov     fh,0x00
         mov     ax,0xFFFF
         xorsx   cl,fh,ax
         cmp     cl,0xFF
         bne     TestArus_BBWSErr
         mov     gh,0x00
         mov     bx,0xFFFF
         mulsx   dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x00
         mov     cx,0xFFFF
         sdivsx  el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x00
         mov     dx,0xFFFF
         sremsx  fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0x01
         mov     ex,0x0001
         addsx   gl,cl,ex
         cmp     gl,0x02
         bne     TestArus_BBWSErr
         mov     dl,0x01
         mov     fx,0x0001
         subsx   ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x01
         mov     gx,0x0001
         andsx   bh,el,gx
         cmp     bh,0x01
         bne     TestArus_BBWSErr
         mov     fl,0x01
         mov     aw,0x0001
         orsx    ch,fl,aw
         cmp     ch,0x01
         bne     TestArus_BBWSErr
         mov     gl,0x01
         mov     bw,0x0001
         xorsx   dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x01
         mov     cw,0x0001
         mulsx   eh,ah,cw
         cmp     eh,0x01
         bne     TestArus_BBWSErr
         mov     bh,0x01
         mov     dw,0x0001
         sdivsx  fh,bh,dw
         cmp     fh,0x01
         bne     TestArus_BBWSErr
         mov     ch,0x01
         mov     ew,0x0001
         sremsx  gh,ch,ew
         cmp     gh,0x00
         bne     TestArus_BBWSErr
         mov     dh,0x01
         mov     fw,0x0008
         addsx   al,dh,fw
         cmp     al,0x09
         bne     TestArus_BBWSErr
         mov     eh,0x01
         mov     gw,0x0008
         subsx   bl,eh,gw
         cmp     bl,0xF9
         bne     TestArus_BBWSErr
         mov     fh,0x01
         mov     ax,0x0008
         andsx   cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x01
         mov     bx,0x0008
         orsx    dl,gh,bx
         cmp     dl,0x09
         bne     TestArus_BBWSErr
         mov     al,0x01
         mov     cx,0x0008
         xorsx   el,al,cx
         cmp     el,0x09
         bne     TestArus_BBWSErr
         mov     bl,0x01
         mov     dx,0x0008
         mulsx   fl,bl,dx
         cmp     fl,0x08
         bne     TestArus_BBWSErr
         mov     cl,0x01
         mov     ex,0x0008
         sdivsx  gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x01
         mov     fx,0x0008
         sremsx  ah,dl,fx
         cmp     ah,0x01
         bne     TestArus_BBWSErr
         mov     el,0x01
         mov     gx,0x0009
         addsx   bh,el,gx
         cmp     bh,0x0A
         bne     TestArus_BBWSErr
         mov     fl,0x01
         mov     aw,0x0009
         subsx   ch,fl,aw
         cmp     ch,0xF8
         bne     TestArus_BBWSErr
         mov     gl,0x01
         mov     bw,0x0009
         andsx   dh,gl,bw
         cmp     dh,0x01
         bne     TestArus_BBWSErr
         mov     ah,0x01
         mov     cw,0x0009
         orsx    eh,ah,cw
         cmp     eh,0x09
         bne     TestArus_BBWSErr
         mov     bh,0x01
         mov     dw,0x0009
         xorsx   fh,bh,dw
         cmp     fh,0x08
         bne     TestArus_BBWSErr
         mov     ch,0x01
         mov     ew,0x0009
         mulsx   gh,ch,ew
         cmp     gh,0x09
         bne     TestArus_BBWSErr
         mov     dh,0x01
         mov     fw,0x0009
         sdivsx  al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x01
         mov     gw,0x0009
         sremsx  bl,eh,gw
         cmp     bl,0x01
         bne     TestArus_BBWSErr
         mov     fh,0x01
         mov     ax,0x007F
         addsx   cl,fh,ax
         cmp     cl,0x80
         bne     TestArus_BBWSErr
         mov     gh,0x01
         mov     bx,0x007F
         subsx   dl,gh,bx
         cmp     dl,0x82
         bne     TestArus_BBWSErr
         mov     al,0x01
         mov     cx,0x007F
         andsx   el,al,cx
         cmp     el,0x01
         bne     TestArus_BBWSErr
         mov     bl,0x01
         mov     dx,0x007F
         orsx    fl,bl,dx
         cmp     fl,0x7F
         bne     TestArus_BBWSErr
         mov     cl,0x01
         mov     ex,0x007F
         xorsx   gl,cl,ex
         cmp     gl,0x7E
         bne     TestArus_BBWSErr
         mov     dl,0x01
         mov     fx,0x007F
         mulsx   ah,dl,fx
         cmp     ah,0x7F
         bne     TestArus_BBWSErr
         mov     el,0x01
         mov     gx,0x007F
         sdivsx  bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x01
         mov     aw,0x007F
         sremsx  ch,fl,aw
         cmp     ch,0x01
         bne     TestArus_BBWSErr
         mov     gl,0x01
         mov     bw,0x0080
         addsx   dh,gl,bw
         cmp     dh,0x81
         bne     TestArus_BBWSErr
         mov     ah,0x01
         mov     cw,0x0080
         subsx   eh,ah,cw
         cmp     eh,0x81
         bne     TestArus_BBWSErr
         mov     bh,0x01
         mov     dw,0x0080
         andsx   fh,bh,dw
         cmp     fh,0x00
         bne     TestArus_BBWSErr
         mov     ch,0x01
         mov     ew,0x0080
         orsx    gh,ch,ew
         cmp     gh,0x81
         bne     TestArus_BBWSErr
         mov     dh,0x01
         mov     fw,0x0080
         xorsx   al,dh,fw
         cmp     al,0x81
         bne     TestArus_BBWSErr
         mov     eh,0x01
         mov     gw,0x0080
         mulsx   bl,eh,gw
         cmp     bl,0x80
         bne     TestArus_BBWSErr
         mov     fh,0x01
         mov     ax,0x0080
         sdivsx  cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x01
         mov     bx,0x0080
         sremsx  dl,gh,bx
         cmp     dl,0x01
         bne     TestArus_BBWSErr
         mov     al,0x01
         mov     cx,0x7FFF
         addsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x01
         mov     dx,0x7FFF
         subsx   fl,bl,dx
         cmp     fl,0x02
         bne     TestArus_BBWSErr
         mov     cl,0x01
         mov     ex,0x7FFF
         andsx   gl,cl,ex
         cmp     gl,0x01
         bne     TestArus_BBWSErr
         mov     dl,0x01
         mov     fx,0x7FFF
         orsx    ah,dl,fx
         cmp     ah,0xFF
         bne     TestArus_BBWSErr
         mov     el,0x01
         mov     gx,0x7FFF
         xorsx   bh,el,gx
         cmp     bh,0xFE
         bne     TestArus_BBWSErr
         mov     fl,0x01
         mov     aw,0x7FFF
         mulsx   ch,fl,aw
         cmp     ch,0xFF
         bne     TestArus_BBWSErr
         mov     gl,0x01
         mov     bw,0x7FFF
         sdivsx  dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x01
         mov     cw,0x7FFF
         sremsx  eh,ah,cw
         cmp     eh,0x01
         bne     TestArus_BBWSErr
         mov     bh,0x01
         mov     dw,0x8000
         addsx   fh,bh,dw
         cmp     fh,0x01
         bne     TestArus_BBWSErr
         mov     ch,0x01
         mov     ew,0x8000
         subsx   gh,ch,ew
         cmp     gh,0x01
         bne     TestArus_BBWSErr
         mov     dh,0x01
         mov     fw,0x8000
         andsx   al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x01
         mov     gw,0x8000
         orsx    bl,eh,gw
         cmp     bl,0x01
         bne     TestArus_BBWSErr
         mov     fh,0x01
         mov     ax,0x8000
         xorsx   cl,fh,ax
         cmp     cl,0x01
         bne     TestArus_BBWSErr
         mov     gh,0x01
         mov     bx,0x8000
         mulsx   dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x01
         mov     cx,0x8000
         sdivsx  el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x01
         mov     dx,0x8000
         sremsx  fl,bl,dx
         cmp     fl,0x01
         bne     TestArus_BBWSErr
         mov     cl,0x01
         mov     ex,0xFFFF
         addsx   gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x01
         mov     fx,0xFFFF
         subsx   ah,dl,fx
         cmp     ah,0x02
         bne     TestArus_BBWSErr
         mov     el,0x01
         mov     gx,0xFFFF
         andsx   bh,el,gx
         cmp     bh,0x01
         bne     TestArus_BBWSErr
         mov     fl,0x01
         mov     aw,0xFFFF
         orsx    ch,fl,aw
         cmp     ch,0xFF
         bne     TestArus_BBWSErr
         mov     gl,0x01
         mov     bw,0xFFFF
         xorsx   dh,gl,bw
         cmp     dh,0xFE
         bne     TestArus_BBWSErr
         mov     ah,0x01
         mov     cw,0xFFFF
         mulsx   eh,ah,cw
         cmp     eh,0xFF
         bne     TestArus_BBWSErr
         mov     bh,0x01
         mov     dw,0xFFFF
         sdivsx  fh,bh,dw
         cmp     fh,0xFF
         bne     TestArus_BBWSErr
         mov     ch,0x01
         mov     ew,0xFFFF
         sremsx  gh,ch,ew
         cmp     gh,0x00
         bne     TestArus_BBWSErr
         mov     dh,0x07
         mov     fw,0x0008
         addsx   al,dh,fw
         cmp     al,0x0F
         bne     TestArus_BBWSErr
         mov     eh,0x07
         mov     gw,0x0008
         subsx   bl,eh,gw
         cmp     bl,0xFF
         bne     TestArus_BBWSErr
         mov     fh,0x07
         mov     ax,0x0008
         andsx   cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x07
         mov     bx,0x0008
         orsx    dl,gh,bx
         cmp     dl,0x0F
         bne     TestArus_BBWSErr
         mov     al,0x07
         mov     cx,0x0008
         xorsx   el,al,cx
         cmp     el,0x0F
         bne     TestArus_BBWSErr
         mov     bl,0x07
         mov     dx,0x0008
         mulsx   fl,bl,dx
         cmp     fl,0x38
         bne     TestArus_BBWSErr
         mov     cl,0x07
         mov     ex,0x0008
         sdivsx  gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x07
         mov     fx,0x0008
         sremsx  ah,dl,fx
         cmp     ah,0x07
         bne     TestArus_BBWSErr
         mov     el,0x07
         mov     gx,0x0009
         addsx   bh,el,gx
         cmp     bh,0x10
         bne     TestArus_BBWSErr
         mov     fl,0x07
         mov     aw,0x0009
         subsx   ch,fl,aw
         cmp     ch,0xFE
         bne     TestArus_BBWSErr
         mov     gl,0x07
         mov     bw,0x0009
         andsx   dh,gl,bw
         cmp     dh,0x01
         bne     TestArus_BBWSErr
         mov     ah,0x07
         mov     cw,0x0009
         orsx    eh,ah,cw
         cmp     eh,0x0F
         bne     TestArus_BBWSErr
         mov     bh,0x07
         mov     dw,0x0009
         xorsx   fh,bh,dw
         cmp     fh,0x0E
         bne     TestArus_BBWSErr
         mov     ch,0x07
         mov     ew,0x0009
         mulsx   gh,ch,ew
         cmp     gh,0x3F
         bne     TestArus_BBWSErr
         mov     dh,0x07
         mov     fw,0x0009
         sdivsx  al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x07
         mov     gw,0x0009
         sremsx  bl,eh,gw
         cmp     bl,0x07
         bne     TestArus_BBWSErr
         mov     fh,0x07
         mov     ax,0x007F
         addsx   cl,fh,ax
         cmp     cl,0x86
         bne     TestArus_BBWSErr
         mov     gh,0x07
         mov     bx,0x007F
         subsx   dl,gh,bx
         cmp     dl,0x88
         bne     TestArus_BBWSErr
         mov     al,0x07
         mov     cx,0x007F
         andsx   el,al,cx
         cmp     el,0x07
         bne     TestArus_BBWSErr
         mov     bl,0x07
         mov     dx,0x007F
         orsx    fl,bl,dx
         cmp     fl,0x7F
         bne     TestArus_BBWSErr
         mov     cl,0x07
         mov     ex,0x007F
         xorsx   gl,cl,ex
         cmp     gl,0x78
         bne     TestArus_BBWSErr
         mov     dl,0x07
         mov     fx,0x007F
         mulsx   ah,dl,fx
         cmp     ah,0x79
         bne     TestArus_BBWSErr
         mov     el,0x07
         mov     gx,0x007F
         sdivsx  bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x07
         mov     aw,0x007F
         sremsx  ch,fl,aw
         cmp     ch,0x07
         bne     TestArus_BBWSErr
         mov     gl,0x07
         mov     bw,0x0080
         addsx   dh,gl,bw
         cmp     dh,0x87
         bne     TestArus_BBWSErr
         mov     ah,0x07
         mov     cw,0x0080
         subsx   eh,ah,cw
         cmp     eh,0x87
         bne     TestArus_BBWSErr
         mov     bh,0x07
         mov     dw,0x0080
         andsx   fh,bh,dw
         cmp     fh,0x00
         bne     TestArus_BBWSErr
         mov     ch,0x07
         mov     ew,0x0080
         orsx    gh,ch,ew
         cmp     gh,0x87
         bne     TestArus_BBWSErr
         mov     dh,0x07
         mov     fw,0x0080
         xorsx   al,dh,fw
         cmp     al,0x87
         bne     TestArus_BBWSErr
         mov     eh,0x07
         mov     gw,0x0080
         mulsx   bl,eh,gw
         cmp     bl,0x80
         bne     TestArus_BBWSErr
         mov     fh,0x07
         mov     ax,0x0080
         sdivsx  cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x07
         mov     bx,0x0080
         sremsx  dl,gh,bx
         cmp     dl,0x07
         bne     TestArus_BBWSErr
         mov     al,0x07
         mov     cx,0x7FFF
         addsx   el,al,cx
         cmp     el,0x06
         bne     TestArus_BBWSErr
         mov     bl,0x07
         mov     dx,0x7FFF
         subsx   fl,bl,dx
         cmp     fl,0x08
         bne     TestArus_BBWSErr
         mov     cl,0x07
         mov     ex,0x7FFF
         andsx   gl,cl,ex
         cmp     gl,0x07
         bne     TestArus_BBWSErr
         mov     dl,0x07
         mov     fx,0x7FFF
         orsx    ah,dl,fx
         cmp     ah,0xFF
         bne     TestArus_BBWSErr
         mov     el,0x07
         mov     gx,0x7FFF
         xorsx   bh,el,gx
         cmp     bh,0xF8
         bne     TestArus_BBWSErr
         mov     fl,0x07
         mov     aw,0x7FFF
         mulsx   ch,fl,aw
         cmp     ch,0xF9
         bne     TestArus_BBWSErr
         mov     gl,0x07
         mov     bw,0x7FFF
         sdivsx  dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x07
         mov     cw,0x7FFF
         sremsx  eh,ah,cw
         cmp     eh,0x07
         bne     TestArus_BBWSErr
         mov     bh,0x07
         mov     dw,0x8000
         addsx   fh,bh,dw
         cmp     fh,0x07
         bne     TestArus_BBWSErr
         mov     ch,0x07
         mov     ew,0x8000
         subsx   gh,ch,ew
         cmp     gh,0x07
         bne     TestArus_BBWSErr
         mov     dh,0x07
         mov     fw,0x8000
         andsx   al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x07
         mov     gw,0x8000
         orsx    bl,eh,gw
         cmp     bl,0x07
         bne     TestArus_BBWSErr
         mov     fh,0x07
         mov     ax,0x8000
         xorsx   cl,fh,ax
         cmp     cl,0x07
         bne     TestArus_BBWSErr
         mov     gh,0x07
         mov     bx,0x8000
         mulsx   dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x07
         mov     cx,0x8000
         sdivsx  el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x07
         mov     dx,0x8000
         sremsx  fl,bl,dx
         cmp     fl,0x07
         bne     TestArus_BBWSErr
         mov     cl,0x07
         mov     ex,0xFFFF
         addsx   gl,cl,ex
         cmp     gl,0x06
         bne     TestArus_BBWSErr
         mov     dl,0x07
         mov     fx,0xFFFF
         subsx   ah,dl,fx
         cmp     ah,0x08
         bne     TestArus_BBWSErr
         mov     el,0x07
         mov     gx,0xFFFF
         andsx   bh,el,gx
         cmp     bh,0x07
         bne     TestArus_BBWSErr
         mov     fl,0x07
         mov     aw,0xFFFF
         orsx    ch,fl,aw
         cmp     ch,0xFF
         bne     TestArus_BBWSErr
         mov     gl,0x07
         mov     bw,0xFFFF
         xorsx   dh,gl,bw
         cmp     dh,0xF8
         bne     TestArus_BBWSErr
         mov     ah,0x07
         mov     cw,0xFFFF
         mulsx   eh,ah,cw
         cmp     eh,0xF9
         bne     TestArus_BBWSErr
         mov     bh,0x07
         mov     dw,0xFFFF
         sdivsx  fh,bh,dw
         cmp     fh,0xF9
         bne     TestArus_BBWSErr
         mov     ch,0x07
         mov     ew,0xFFFF
         sremsx  gh,ch,ew
         cmp     gh,0x00
         bne     TestArus_BBWSErr
         mov     dh,0x08
         mov     fw,0x0009
         addsx   al,dh,fw
         cmp     al,0x11
         bne     TestArus_BBWSErr
         mov     eh,0x08
         mov     gw,0x0009
         subsx   bl,eh,gw
         cmp     bl,0xFF
         bne     TestArus_BBWSErr
         mov     fh,0x08
         mov     ax,0x0009
         andsx   cl,fh,ax
         cmp     cl,0x08
         bne     TestArus_BBWSErr
         mov     gh,0x08
         mov     bx,0x0009
         orsx    dl,gh,bx
         cmp     dl,0x09
         bne     TestArus_BBWSErr
         mov     al,0x08
         mov     cx,0x0009
         xorsx   el,al,cx
         cmp     el,0x01
         bne     TestArus_BBWSErr
         mov     bl,0x08
         mov     dx,0x0009
         mulsx   fl,bl,dx
         cmp     fl,0x48
         bne     TestArus_BBWSErr
         mov     cl,0x08
         mov     ex,0x0009
         sdivsx  gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x08
         mov     fx,0x0009
         sremsx  ah,dl,fx
         cmp     ah,0x08
         bne     TestArus_BBWSErr
         mov     el,0x08
         mov     gx,0x007F
         addsx   bh,el,gx
         cmp     bh,0x87
         bne     TestArus_BBWSErr
         mov     fl,0x08
         mov     aw,0x007F
         subsx   ch,fl,aw
         cmp     ch,0x89
         bne     TestArus_BBWSErr
         mov     gl,0x08
         mov     bw,0x007F
         andsx   dh,gl,bw
         cmp     dh,0x08
         bne     TestArus_BBWSErr
         mov     ah,0x08
         mov     cw,0x007F
         orsx    eh,ah,cw
         cmp     eh,0x7F
         bne     TestArus_BBWSErr
         mov     bh,0x08
         mov     dw,0x007F
         xorsx   fh,bh,dw
         cmp     fh,0x77
         bne     TestArus_BBWSErr
         mov     ch,0x08
         mov     ew,0x007F
         mulsx   gh,ch,ew
         cmp     gh,0xF8
         bne     TestArus_BBWSErr
         mov     dh,0x08
         mov     fw,0x007F
         sdivsx  al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x08
         mov     gw,0x007F
         sremsx  bl,eh,gw
         cmp     bl,0x08
         bne     TestArus_BBWSErr
         mov     fh,0x08
         mov     ax,0x0080
         addsx   cl,fh,ax
         cmp     cl,0x88
         bne     TestArus_BBWSErr
         mov     gh,0x08
         mov     bx,0x0080
         subsx   dl,gh,bx
         cmp     dl,0x88
         bne     TestArus_BBWSErr
         mov     al,0x08
         mov     cx,0x0080
         andsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x08
         mov     dx,0x0080
         orsx    fl,bl,dx
         cmp     fl,0x88
         bne     TestArus_BBWSErr
         mov     cl,0x08
         mov     ex,0x0080
         xorsx   gl,cl,ex
         cmp     gl,0x88
         bne     TestArus_BBWSErr
         mov     dl,0x08
         mov     fx,0x0080
         mulsx   ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x08
         mov     gx,0x0080
         sdivsx  bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x08
         mov     aw,0x0080
         sremsx  ch,fl,aw
         cmp     ch,0x08
         bne     TestArus_BBWSErr
         mov     gl,0x08
         mov     bw,0x7FFF
         addsx   dh,gl,bw
         cmp     dh,0x07
         bne     TestArus_BBWSErr
         mov     ah,0x08
         mov     cw,0x7FFF
         subsx   eh,ah,cw
         cmp     eh,0x09
         bne     TestArus_BBWSErr
         mov     bh,0x08
         mov     dw,0x7FFF
         andsx   fh,bh,dw
         cmp     fh,0x08
         bne     TestArus_BBWSErr
         mov     ch,0x08
         mov     ew,0x7FFF
         orsx    gh,ch,ew
         cmp     gh,0xFF
         bne     TestArus_BBWSErr
         mov     dh,0x08
         mov     fw,0x7FFF
         xorsx   al,dh,fw
         cmp     al,0xF7
         bne     TestArus_BBWSErr
         mov     eh,0x08
         mov     gw,0x7FFF
         mulsx   bl,eh,gw
         cmp     bl,0xF8
         bne     TestArus_BBWSErr
         mov     fh,0x08
         mov     ax,0x7FFF
         sdivsx  cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x08
         mov     bx,0x7FFF
         sremsx  dl,gh,bx
         cmp     dl,0x08
         bne     TestArus_BBWSErr
         mov     al,0x08
         mov     cx,0x8000
         addsx   el,al,cx
         cmp     el,0x08
         bne     TestArus_BBWSErr
         mov     bl,0x08
         mov     dx,0x8000
         subsx   fl,bl,dx
         cmp     fl,0x08
         bne     TestArus_BBWSErr
         mov     cl,0x08
         mov     ex,0x8000
         andsx   gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x08
         mov     fx,0x8000
         orsx    ah,dl,fx
         cmp     ah,0x08
         bne     TestArus_BBWSErr
         mov     el,0x08
         mov     gx,0x8000
         xorsx   bh,el,gx
         cmp     bh,0x08
         bne     TestArus_BBWSErr
         mov     fl,0x08
         mov     aw,0x8000
         mulsx   ch,fl,aw
         cmp     ch,0x00
         bne     TestArus_BBWSErr
         mov     gl,0x08
         mov     bw,0x8000
         sdivsx  dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x08
         mov     cw,0x8000
         sremsx  eh,ah,cw
         cmp     eh,0x08
         bne     TestArus_BBWSErr
         mov     bh,0x08
         mov     dw,0xFFFF
         addsx   fh,bh,dw
         cmp     fh,0x07
         bne     TestArus_BBWSErr
         mov     ch,0x08
         mov     ew,0xFFFF
         subsx   gh,ch,ew
         cmp     gh,0x09
         bne     TestArus_BBWSErr
         mov     dh,0x08
         mov     fw,0xFFFF
         andsx   al,dh,fw
         cmp     al,0x08
         bne     TestArus_BBWSErr
         mov     eh,0x08
         mov     gw,0xFFFF
         orsx    bl,eh,gw
         cmp     bl,0xFF
         bne     TestArus_BBWSErr
         mov     fh,0x08
         mov     ax,0xFFFF
         xorsx   cl,fh,ax
         cmp     cl,0xF7
         bne     TestArus_BBWSErr
         mov     gh,0x08
         mov     bx,0xFFFF
         mulsx   dl,gh,bx
         cmp     dl,0xF8
         bne     TestArus_BBWSErr
         mov     al,0x08
         mov     cx,0xFFFF
         sdivsx  el,al,cx
         cmp     el,0xF8
         bne     TestArus_BBWSErr
         mov     bl,0x08
         mov     dx,0xFFFF
         sremsx  fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0x09
         mov     ex,0x007F
         addsx   gl,cl,ex
         cmp     gl,0x88
         bne     TestArus_BBWSErr
         mov     dl,0x09
         mov     fx,0x007F
         subsx   ah,dl,fx
         cmp     ah,0x8A
         bne     TestArus_BBWSErr
         mov     el,0x09
         mov     gx,0x007F
         andsx   bh,el,gx
         cmp     bh,0x09
         bne     TestArus_BBWSErr
         mov     fl,0x09
         mov     aw,0x007F
         orsx    ch,fl,aw
         cmp     ch,0x7F
         bne     TestArus_BBWSErr
         mov     gl,0x09
         mov     bw,0x007F
         xorsx   dh,gl,bw
         cmp     dh,0x76
         bne     TestArus_BBWSErr
         mov     ah,0x09
         mov     cw,0x007F
         mulsx   eh,ah,cw
         cmp     eh,0x77
         bne     TestArus_BBWSErr
         mov     bh,0x09
         mov     dw,0x007F
         sdivsx  fh,bh,dw
         cmp     fh,0x00
         bne     TestArus_BBWSErr
         mov     ch,0x09
         mov     ew,0x007F
         sremsx  gh,ch,ew
         cmp     gh,0x09
         bne     TestArus_BBWSErr
         mov     dh,0x09
         mov     fw,0x0080
         addsx   al,dh,fw
         cmp     al,0x89
         bne     TestArus_BBWSErr
         mov     eh,0x09
         mov     gw,0x0080
         subsx   bl,eh,gw
         cmp     bl,0x89
         bne     TestArus_BBWSErr
         mov     fh,0x09
         mov     ax,0x0080
         andsx   cl,fh,ax
         cmp     cl,0x00
         bne     TestArus_BBWSErr
         mov     gh,0x09
         mov     bx,0x0080
         orsx    dl,gh,bx
         cmp     dl,0x89
         bne     TestArus_BBWSErr
         mov     al,0x09
         mov     cx,0x0080
         xorsx   el,al,cx
         cmp     el,0x89
         bne     TestArus_BBWSErr
         mov     bl,0x09
         mov     dx,0x0080
         mulsx   fl,bl,dx
         cmp     fl,0x80
         bne     TestArus_BBWSErr
         mov     cl,0x09
         mov     ex,0x0080
         sdivsx  gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x09
         mov     fx,0x0080
         sremsx  ah,dl,fx
         cmp     ah,0x09
         bne     TestArus_BBWSErr
         mov     el,0x09
         mov     gx,0x7FFF
         addsx   bh,el,gx
         cmp     bh,0x08
         bne     TestArus_BBWSErr
         mov     fl,0x09
         mov     aw,0x7FFF
         subsx   ch,fl,aw
         cmp     ch,0x0A
         bne     TestArus_BBWSErr
         mov     gl,0x09
         mov     bw,0x7FFF
         andsx   dh,gl,bw
         cmp     dh,0x09
         bne     TestArus_BBWSErr
         mov     ah,0x09
         mov     cw,0x7FFF
         orsx    eh,ah,cw
         cmp     eh,0xFF
         bne     TestArus_BBWSErr
         mov     bh,0x09
         mov     dw,0x7FFF
         xorsx   fh,bh,dw
         cmp     fh,0xF6
         bne     TestArus_BBWSErr
         mov     ch,0x09
         mov     ew,0x7FFF
         mulsx   gh,ch,ew
         cmp     gh,0xF7
         bne     TestArus_BBWSErr
         mov     dh,0x09
         mov     fw,0x7FFF
         sdivsx  al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x09
         mov     gw,0x7FFF
         sremsx  bl,eh,gw
         cmp     bl,0x09
         bne     TestArus_BBWSErr
         mov     fh,0x09
         mov     ax,0x8000
         addsx   cl,fh,ax
         cmp     cl,0x09
         bne     TestArus_BBWSErr
         mov     gh,0x09
         mov     bx,0x8000
         subsx   dl,gh,bx
         cmp     dl,0x09
         bne     TestArus_BBWSErr
         mov     al,0x09
         mov     cx,0x8000
         andsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x09
         mov     dx,0x8000
         orsx    fl,bl,dx
         cmp     fl,0x09
         bne     TestArus_BBWSErr
         mov     cl,0x09
         mov     ex,0x8000
         xorsx   gl,cl,ex
         cmp     gl,0x09
         bne     TestArus_BBWSErr
         mov     dl,0x09
         mov     fx,0x8000
         mulsx   ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x09
         mov     gx,0x8000
         sdivsx  bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x09
         mov     aw,0x8000
         sremsx  ch,fl,aw
         cmp     ch,0x09
         bne     TestArus_BBWSErr
         mov     gl,0x09
         mov     bw,0xFFFF
         addsx   dh,gl,bw
         cmp     dh,0x08
         bne     TestArus_BBWSErr
         mov     ah,0x09
         mov     cw,0xFFFF
         subsx   eh,ah,cw
         cmp     eh,0x0A
         bne     TestArus_BBWSErr
         mov     bh,0x09
         mov     dw,0xFFFF
         andsx   fh,bh,dw
         cmp     fh,0x09
         bne     TestArus_BBWSErr
         mov     ch,0x09
         mov     ew,0xFFFF
         orsx    gh,ch,ew
         cmp     gh,0xFF
         bne     TestArus_BBWSErr
         mov     dh,0x09
         mov     fw,0xFFFF
         xorsx   al,dh,fw
         cmp     al,0xF6
         bne     TestArus_BBWSErr
         mov     eh,0x09
         mov     gw,0xFFFF
         mulsx   bl,eh,gw
         cmp     bl,0xF7
         bne     TestArus_BBWSErr
         mov     fh,0x09
         mov     ax,0xFFFF
         sdivsx  cl,fh,ax
         cmp     cl,0xF7
         bne     TestArus_BBWSErr
         mov     gh,0x09
         mov     bx,0xFFFF
         sremsx  dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x0F
         mov     cx,0x0080
         addsx   el,al,cx
         cmp     el,0x8F
         bne     TestArus_BBWSErr
         mov     bl,0x0F
         mov     dx,0x0080
         subsx   fl,bl,dx
         cmp     fl,0x8F
         bne     TestArus_BBWSErr
         mov     cl,0x0F
         mov     ex,0x0080
         andsx   gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x0F
         mov     fx,0x0080
         orsx    ah,dl,fx
         cmp     ah,0x8F
         bne     TestArus_BBWSErr
         mov     el,0x0F
         mov     gx,0x0080
         xorsx   bh,el,gx
         cmp     bh,0x8F
         bne     TestArus_BBWSErr
         mov     fl,0x0F
         mov     aw,0x0080
         mulsx   ch,fl,aw
         cmp     ch,0x80
         bne     TestArus_BBWSErr
         mov     gl,0x0F
         mov     bw,0x0080
         sdivsx  dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x0F
         mov     cw,0x0080
         sremsx  eh,ah,cw
         cmp     eh,0x0F
         bne     TestArus_BBWSErr
         mov     bh,0x0F
         mov     dw,0x7FFF
         addsx   fh,bh,dw
         cmp     fh,0x0E
         bne     TestArus_BBWSErr
         mov     ch,0x0F
         mov     ew,0x7FFF
         subsx   gh,ch,ew
         cmp     gh,0x10
         bne     TestArus_BBWSErr
         mov     dh,0x0F
         mov     fw,0x7FFF
         andsx   al,dh,fw
         cmp     al,0x0F
         bne     TestArus_BBWSErr
         mov     eh,0x0F
         mov     gw,0x7FFF
         orsx    bl,eh,gw
         cmp     bl,0xFF
         bne     TestArus_BBWSErr
         mov     fh,0x0F
         mov     ax,0x7FFF
         xorsx   cl,fh,ax
         cmp     cl,0xF0
         bne     TestArus_BBWSErr
         mov     gh,0x0F
         mov     bx,0x7FFF
         mulsx   dl,gh,bx
         cmp     dl,0xF1
         bne     TestArus_BBWSErr
         mov     al,0x0F
         mov     cx,0x7FFF
         sdivsx  el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x0F
         mov     dx,0x7FFF
         sremsx  fl,bl,dx
         cmp     fl,0x0F
         bne     TestArus_BBWSErr
         mov     cl,0x0F
         mov     ex,0x8000
         addsx   gl,cl,ex
         cmp     gl,0x0F
         bne     TestArus_BBWSErr
         mov     dl,0x0F
         mov     fx,0x8000
         subsx   ah,dl,fx
         cmp     ah,0x0F
         bne     TestArus_BBWSErr
         mov     el,0x0F
         mov     gx,0x8000
         andsx   bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x0F
         mov     aw,0x8000
         orsx    ch,fl,aw
         cmp     ch,0x0F
         bne     TestArus_BBWSErr
         mov     gl,0x0F
         mov     bw,0x8000
         xorsx   dh,gl,bw
         cmp     dh,0x0F
         bne     TestArus_BBWSErr
         mov     ah,0x0F
         mov     cw,0x8000
         mulsx   eh,ah,cw
         cmp     eh,0x00
         bne     TestArus_BBWSErr
         mov     bh,0x0F
         mov     dw,0x8000
         sdivsx  fh,bh,dw
         cmp     fh,0x00
         bne     TestArus_BBWSErr
         mov     ch,0x0F
         mov     ew,0x8000
         sremsx  gh,ch,ew
         cmp     gh,0x0F
         bne     TestArus_BBWSErr
         mov     dh,0x0F
         mov     fw,0xFFFF
         addsx   al,dh,fw
         cmp     al,0x0E
         bne     TestArus_BBWSErr
         mov     eh,0x0F
         mov     gw,0xFFFF
         subsx   bl,eh,gw
         cmp     bl,0x10
         bne     TestArus_BBWSErr
         mov     fh,0x0F
         mov     ax,0xFFFF
         andsx   cl,fh,ax
         cmp     cl,0x0F
         bne     TestArus_BBWSErr
         mov     gh,0x0F
         mov     bx,0xFFFF
         orsx    dl,gh,bx
         cmp     dl,0xFF
         bne     TestArus_BBWSErr
         mov     al,0x0F
         mov     cx,0xFFFF
         xorsx   el,al,cx
         cmp     el,0xF0
         bne     TestArus_BBWSErr
         mov     bl,0x0F
         mov     dx,0xFFFF
         mulsx   fl,bl,dx
         cmp     fl,0xF1
         bne     TestArus_BBWSErr
         mov     cl,0x0F
         mov     ex,0xFFFF
         sdivsx  gl,cl,ex
         cmp     gl,0xF1
         bne     TestArus_BBWSErr
         mov     dl,0x0F
         mov     fx,0xFFFF
         sremsx  ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x7F
         mov     gx,0x7FFF
         addsx   bh,el,gx
         cmp     bh,0x7E
         bne     TestArus_BBWSErr
         mov     fl,0x7F
         mov     aw,0x7FFF
         subsx   ch,fl,aw
         cmp     ch,0x80
         bne     TestArus_BBWSErr
         mov     gl,0x7F
         mov     bw,0x7FFF
         andsx   dh,gl,bw
         cmp     dh,0x7F
         bne     TestArus_BBWSErr
         mov     ah,0x7F
         mov     cw,0x7FFF
         orsx    eh,ah,cw
         cmp     eh,0xFF
         bne     TestArus_BBWSErr
         mov     bh,0x7F
         mov     dw,0x7FFF
         xorsx   fh,bh,dw
         cmp     fh,0x80
         bne     TestArus_BBWSErr
         mov     ch,0x7F
         mov     ew,0x7FFF
         mulsx   gh,ch,ew
         cmp     gh,0x81
         bne     TestArus_BBWSErr
         mov     dh,0x7F
         mov     fw,0x7FFF
         sdivsx  al,dh,fw
         cmp     al,0x00
         bne     TestArus_BBWSErr
         mov     eh,0x7F
         mov     gw,0x7FFF
         sremsx  bl,eh,gw
         cmp     bl,0x7F
         bne     TestArus_BBWSErr
         mov     fh,0x7F
         mov     ax,0x8000
         addsx   cl,fh,ax
         cmp     cl,0x7F
         bne     TestArus_BBWSErr
         mov     gh,0x7F
         mov     bx,0x8000
         subsx   dl,gh,bx
         cmp     dl,0x7F
         bne     TestArus_BBWSErr
         mov     al,0x7F
         mov     cx,0x8000
         andsx   el,al,cx
         cmp     el,0x00
         bne     TestArus_BBWSErr
         mov     bl,0x7F
         mov     dx,0x8000
         orsx    fl,bl,dx
         cmp     fl,0x7F
         bne     TestArus_BBWSErr
         mov     cl,0x7F
         mov     ex,0x8000
         xorsx   gl,cl,ex
         cmp     gl,0x7F
         bne     TestArus_BBWSErr
         mov     dl,0x7F
         mov     fx,0x8000
         mulsx   ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0x7F
         mov     gx,0x8000
         sdivsx  bh,el,gx
         cmp     bh,0x00
         bne     TestArus_BBWSErr
         mov     fl,0x7F
         mov     aw,0x8000
         sremsx  ch,fl,aw
         cmp     ch,0x7F
         bne     TestArus_BBWSErr
         mov     gl,0x7F
         mov     bw,0xFFFF
         addsx   dh,gl,bw
         cmp     dh,0x7E
         bne     TestArus_BBWSErr
         mov     ah,0x7F
         mov     cw,0xFFFF
         subsx   eh,ah,cw
         cmp     eh,0x80
         bne     TestArus_BBWSErr
         mov     bh,0x7F
         mov     dw,0xFFFF
         andsx   fh,bh,dw
         cmp     fh,0x7F
         bne     TestArus_BBWSErr
         mov     ch,0x7F
         mov     ew,0xFFFF
         orsx    gh,ch,ew
         cmp     gh,0xFF
         bne     TestArus_BBWSErr
         mov     dh,0x7F
         mov     fw,0xFFFF
         xorsx   al,dh,fw
         cmp     al,0x80
         bne     TestArus_BBWSErr
         mov     eh,0x7F
         mov     gw,0xFFFF
         mulsx   bl,eh,gw
         cmp     bl,0x81
         bne     TestArus_BBWSErr
         mov     fh,0x7F
         mov     ax,0xFFFF
         sdivsx  cl,fh,ax
         cmp     cl,0x81
         bne     TestArus_BBWSErr
         mov     gh,0x7F
         mov     bx,0xFFFF
         sremsx  dl,gh,bx
         cmp     dl,0x00
         bne     TestArus_BBWSErr
         mov     al,0x80
         mov     cx,0x8000
         addsx   el,al,cx
         cmp     el,0x80
         bne     TestArus_BBWSErr
         mov     bl,0x80
         mov     dx,0x8000
         subsx   fl,bl,dx
         cmp     fl,0x80
         bne     TestArus_BBWSErr
         mov     cl,0x80
         mov     ex,0x8000
         andsx   gl,cl,ex
         cmp     gl,0x00
         bne     TestArus_BBWSErr
         mov     dl,0x80
         mov     fx,0x8000
         orsx    ah,dl,fx
         cmp     ah,0x80
         bne     TestArus_BBWSErr
         mov     el,0x80
         mov     gx,0x8000
         xorsx   bh,el,gx
         cmp     bh,0x80
         bne     TestArus_BBWSErr
         mov     fl,0x80
         mov     aw,0x8000
         mulsx   ch,fl,aw
         cmp     ch,0x00
         bne     TestArus_BBWSErr
         mov     gl,0x80
         mov     bw,0x8000
         sdivsx  dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0x80
         mov     cw,0x8000
         sremsx  eh,ah,cw
         cmp     eh,0x80
         bne     TestArus_BBWSErr
         mov     bh,0x80
         mov     dw,0xFFFF
         addsx   fh,bh,dw
         cmp     fh,0x7F
         bne     TestArus_BBWSErr
         mov     ch,0x80
         mov     ew,0xFFFF
         subsx   gh,ch,ew
         cmp     gh,0x81
         bne     TestArus_BBWSErr
         mov     dh,0x80
         mov     fw,0xFFFF
         andsx   al,dh,fw
         cmp     al,0x80
         bne     TestArus_BBWSErr
         mov     eh,0x80
         mov     gw,0xFFFF
         orsx    bl,eh,gw
         cmp     bl,0xFF
         bne     TestArus_BBWSErr
         mov     fh,0x80
         mov     ax,0xFFFF
         xorsx   cl,fh,ax
         cmp     cl,0x7F
         bne     TestArus_BBWSErr
         mov     gh,0x80
         mov     bx,0xFFFF
         mulsx   dl,gh,bx
         cmp     dl,0x80
         bne     TestArus_BBWSErr
         mov     al,0x80
         mov     cx,0xFFFF
         sdivsx  el,al,cx
         cmp     el,0x80
         bne     TestArus_BBWSErr
         mov     bl,0x80
         mov     dx,0xFFFF
         sremsx  fl,bl,dx
         cmp     fl,0x00
         bne     TestArus_BBWSErr
         mov     cl,0xFF
         mov     ex,0xFFFF
         addsx   gl,cl,ex
         cmp     gl,0xFE
         bne     TestArus_BBWSErr
         mov     dl,0xFF
         mov     fx,0xFFFF
         subsx   ah,dl,fx
         cmp     ah,0x00
         bne     TestArus_BBWSErr
         mov     el,0xFF
         mov     gx,0xFFFF
         andsx   bh,el,gx
         cmp     bh,0xFF
         bne     TestArus_BBWSErr
         mov     fl,0xFF
         mov     aw,0xFFFF
         orsx    ch,fl,aw
         cmp     ch,0xFF
         bne     TestArus_BBWSErr
         mov     gl,0xFF
         mov     bw,0xFFFF
         xorsx   dh,gl,bw
         cmp     dh,0x00
         bne     TestArus_BBWSErr
         mov     ah,0xFF
         mov     cw,0xFFFF
         mulsx   eh,ah,cw
         cmp     eh,0x01
         bne     TestArus_BBWSErr
         mov     bh,0xFF
         mov     dw,0xFFFF
         sdivsx  fh,bh,dw
         cmp     fh,0x01
         bne     TestArus_BBWSErr
         mov     ch,0xFF
         mov     ew,0xFFFF
         sremsx  gh,ch,ew
         cmp     gh,0x00
         bne     TestArus_BBWSErr
         bra     TestArus_BBWSRet
TestArus_BBWSErr:
         nop     
         trap    
         nop     
TestArus_BBWSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
