.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BWWZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BWWZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         mov     cx,0x0000
         addzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x0000
         subzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x0000
         andzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x0000
         orzx    ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x0000
         xorzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x0000
         mulzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x0000
         udivzx  dh,gx,bw
         cmp     dh,0xFF
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x0000
         uremzx  eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0000
         shlzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0000
         shrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0000
         rolzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x0000
         asrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0x0001
         addzx   cl,fw,ax
         cmp     cl,0x01
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0x0001
         subzx   dl,gw,bx
         cmp     dl,0xFF
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0x0001
         andzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x0001
         orzx    fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x0001
         xorzx   gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x0001
         mulzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x0001
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x0001
         uremzx  ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x0001
         shlzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x0001
         shrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0001
         rolzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0001
         asrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0008
         addzx   al,dw,fw
         cmp     al,0x08
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x0008
         subzx   bl,ew,gw
         cmp     bl,0xF8
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0x0008
         andzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0x0008
         orzx    dl,gw,bx
         cmp     dl,0x08
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0x0008
         xorzx   el,ax,cx
         cmp     el,0x08
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x0008
         mulzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x0008
         udivzx  gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x0008
         uremzx  ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x0000
         shlzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x0000
         shrzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x0000
         rolzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x0000
         asrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0009
         addzx   fh,bw,dw
         cmp     fh,0x09
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0009
         subzx   gh,cw,ew
         cmp     gh,0xF7
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0009
         andzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x0009
         orzx    bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0x0009
         xorzx   cl,fw,ax
         cmp     cl,0x09
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0x0009
         mulzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0x0009
         udivzx  el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x0009
         uremzx  fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x0001
         shlzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x0001
         shrzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x0001
         rolzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x0001
         asrzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x007F
         addzx   dh,gx,bw
         cmp     dh,0x7F
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x007F
         subzx   eh,aw,cw
         cmp     eh,0x81
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x007F
         andzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x007F
         orzx    gh,cw,ew
         cmp     gh,0x7F
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x007F
         xorzx   al,dw,fw
         cmp     al,0x7F
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x007F
         mulzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0x007F
         udivzx  cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0x007F
         uremzx  dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0x0007
         shlzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x0007
         shrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x0007
         rolzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x0007
         asrzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x0080
         addzx   bh,ex,gx
         cmp     bh,0x80
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x0080
         subzx   ch,fx,aw
         cmp     ch,0x80
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x0080
         andzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x0080
         orzx    eh,aw,cw
         cmp     eh,0x80
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0080
         xorzx   fh,bw,dw
         cmp     fh,0x80
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0080
         mulzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0080
         udivzx  al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x0080
         uremzx  bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0x0000
         shlzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0x0000
         shrzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0x0000
         rolzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x0000
         asrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x7FFF
         addzx   gl,cx,ex
         cmp     gl,0xFF
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x7FFF
         subzx   ah,dx,fx
         cmp     ah,0x01
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x7FFF
         andzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x7FFF
         orzx    ch,fx,aw
         cmp     ch,0xFF
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x7FFF
         xorzx   dh,gx,bw
         cmp     dh,0xFF
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x7FFF
         mulzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x7FFF
         udivzx  fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x7FFF
         uremzx  gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0007
         shlzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x0007
         shrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0x0007
         rolzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0x0007
         asrzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0x8000
         addzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0x8000
         subzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0x8000
         andzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0x8000
         orzx    ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0x8000
         xorzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0x8000
         mulzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x8000
         udivzx  dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x8000
         uremzx  eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0000
         shlzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0000
         shrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0000
         rolzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0000
         mov     gw,0x0000
         asrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0000
         mov     ax,0xFFFF
         addzx   cl,fw,ax
         cmp     cl,0xFF
         bne     TestArus_BWWZErr
         mov     gw,0x0000
         mov     bx,0xFFFF
         subzx   dl,gw,bx
         cmp     dl,0x01
         bne     TestArus_BWWZErr
         mov     ax,0x0000
         mov     cx,0xFFFF
         andzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0000
         mov     dx,0xFFFF
         orzx    fl,bx,dx
         cmp     fl,0xFF
         bne     TestArus_BWWZErr
         mov     cx,0x0000
         mov     ex,0xFFFF
         xorzx   gl,cx,ex
         cmp     gl,0xFF
         bne     TestArus_BWWZErr
         mov     dx,0x0000
         mov     fx,0xFFFF
         mulzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0000
         mov     gx,0xFFFF
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0000
         mov     aw,0xFFFF
         uremzx  ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x0007
         shlzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x0007
         shrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0007
         rolzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0007
         asrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0x0001
         addzx   al,dw,fw
         cmp     al,0x02
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0x0001
         subzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0x0001
         andzx   cl,fw,ax
         cmp     cl,0x01
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0x0001
         orzx    dl,gw,bx
         cmp     dl,0x01
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0x0001
         xorzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0x0001
         mulzx   fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0x0001
         udivzx  gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0x0001
         uremzx  ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x0001
         shlzx   bh,ex,gx
         cmp     bh,0x02
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x0001
         shrzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x0001
         rolzx   dh,gx,bw
         cmp     dh,0x02
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x0001
         asrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0001
         mov     dw,0x0008
         addzx   fh,bw,dw
         cmp     fh,0x09
         bne     TestArus_BWWZErr
         mov     cw,0x0001
         mov     ew,0x0008
         subzx   gh,cw,ew
         cmp     gh,0xF9
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0x0008
         andzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0x0008
         orzx    bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0x0008
         xorzx   cl,fw,ax
         cmp     cl,0x09
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0x0008
         mulzx   dl,gw,bx
         cmp     dl,0x08
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0x0008
         udivzx  el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0x0008
         uremzx  fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0x0000
         shlzx   gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0x0000
         shrzx   ah,dx,fx
         cmp     ah,0x01
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x0000
         rolzx   bh,ex,gx
         cmp     bh,0x01
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x0000
         asrzx   ch,fx,aw
         cmp     ch,0x01
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x0009
         addzx   dh,gx,bw
         cmp     dh,0x0A
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x0009
         subzx   eh,aw,cw
         cmp     eh,0xF8
         bne     TestArus_BWWZErr
         mov     bw,0x0001
         mov     dw,0x0009
         andzx   fh,bw,dw
         cmp     fh,0x01
         bne     TestArus_BWWZErr
         mov     cw,0x0001
         mov     ew,0x0009
         orzx    gh,cw,ew
         cmp     gh,0x09
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0x0009
         xorzx   al,dw,fw
         cmp     al,0x08
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0x0009
         mulzx   bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0x0009
         udivzx  cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0x0009
         uremzx  dl,gw,bx
         cmp     dl,0x01
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0x0001
         shlzx   el,ax,cx
         cmp     el,0x02
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0x0001
         shrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0x0001
         rolzx   gl,cx,ex
         cmp     gl,0x02
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0x0001
         asrzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x007F
         addzx   bh,ex,gx
         cmp     bh,0x80
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x007F
         subzx   ch,fx,aw
         cmp     ch,0x82
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x007F
         andzx   dh,gx,bw
         cmp     dh,0x01
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x007F
         orzx    eh,aw,cw
         cmp     eh,0x7F
         bne     TestArus_BWWZErr
         mov     bw,0x0001
         mov     dw,0x007F
         xorzx   fh,bw,dw
         cmp     fh,0x7E
         bne     TestArus_BWWZErr
         mov     cw,0x0001
         mov     ew,0x007F
         mulzx   gh,cw,ew
         cmp     gh,0x7F
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0x007F
         udivzx  al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0x007F
         uremzx  bl,ew,gw
         cmp     bl,0x01
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0x0007
         shlzx   cl,fw,ax
         cmp     cl,0x80
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0x0007
         shrzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0x0007
         rolzx   el,ax,cx
         cmp     el,0x80
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0x0007
         asrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0x0080
         addzx   gl,cx,ex
         cmp     gl,0x81
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0x0080
         subzx   ah,dx,fx
         cmp     ah,0x81
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x0080
         andzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x0080
         orzx    ch,fx,aw
         cmp     ch,0x81
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x0080
         xorzx   dh,gx,bw
         cmp     dh,0x81
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x0080
         mulzx   eh,aw,cw
         cmp     eh,0x80
         bne     TestArus_BWWZErr
         mov     bw,0x0001
         mov     dw,0x0080
         udivzx  fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0001
         mov     ew,0x0080
         uremzx  gh,cw,ew
         cmp     gh,0x01
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0x0000
         shlzx   al,dw,fw
         cmp     al,0x01
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0x0000
         shrzx   bl,ew,gw
         cmp     bl,0x01
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0x0000
         rolzx   cl,fw,ax
         cmp     cl,0x01
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0x0000
         asrzx   dl,gw,bx
         cmp     dl,0x01
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0x7FFF
         addzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0x7FFF
         subzx   fl,bx,dx
         cmp     fl,0x02
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0x7FFF
         andzx   gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0x7FFF
         orzx    ah,dx,fx
         cmp     ah,0xFF
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x7FFF
         xorzx   bh,ex,gx
         cmp     bh,0xFE
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x7FFF
         mulzx   ch,fx,aw
         cmp     ch,0xFF
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x7FFF
         udivzx  dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x7FFF
         uremzx  eh,aw,cw
         cmp     eh,0x01
         bne     TestArus_BWWZErr
         mov     bw,0x0001
         mov     dw,0x0007
         shlzx   fh,bw,dw
         cmp     fh,0x80
         bne     TestArus_BWWZErr
         mov     cw,0x0001
         mov     ew,0x0007
         shrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0x0007
         rolzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0x0007
         asrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0x8000
         addzx   cl,fw,ax
         cmp     cl,0x01
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0x8000
         subzx   dl,gw,bx
         cmp     dl,0x01
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0x8000
         andzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0x8000
         orzx    fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0x8000
         xorzx   gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0x8000
         mulzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x8000
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x8000
         uremzx  ch,fx,aw
         cmp     ch,0x01
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x0000
         shlzx   dh,gx,bw
         cmp     dh,0x01
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x0000
         shrzx   eh,aw,cw
         cmp     eh,0x01
         bne     TestArus_BWWZErr
         mov     bw,0x0001
         mov     dw,0x0000
         rolzx   fh,bw,dw
         cmp     fh,0x01
         bne     TestArus_BWWZErr
         mov     cw,0x0001
         mov     ew,0x0000
         asrzx   gh,cw,ew
         cmp     gh,0x01
         bne     TestArus_BWWZErr
         mov     dw,0x0001
         mov     fw,0xFFFF
         addzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0001
         mov     gw,0xFFFF
         subzx   bl,ew,gw
         cmp     bl,0x02
         bne     TestArus_BWWZErr
         mov     fw,0x0001
         mov     ax,0xFFFF
         andzx   cl,fw,ax
         cmp     cl,0x01
         bne     TestArus_BWWZErr
         mov     gw,0x0001
         mov     bx,0xFFFF
         orzx    dl,gw,bx
         cmp     dl,0xFF
         bne     TestArus_BWWZErr
         mov     ax,0x0001
         mov     cx,0xFFFF
         xorzx   el,ax,cx
         cmp     el,0xFE
         bne     TestArus_BWWZErr
         mov     bx,0x0001
         mov     dx,0xFFFF
         mulzx   fl,bx,dx
         cmp     fl,0xFF
         bne     TestArus_BWWZErr
         mov     cx,0x0001
         mov     ex,0xFFFF
         udivzx  gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0001
         mov     fx,0xFFFF
         uremzx  ah,dx,fx
         cmp     ah,0x01
         bne     TestArus_BWWZErr
         mov     ex,0x0001
         mov     gx,0x0007
         shlzx   bh,ex,gx
         cmp     bh,0x80
         bne     TestArus_BWWZErr
         mov     fx,0x0001
         mov     aw,0x0007
         shrzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0001
         mov     bw,0x0007
         rolzx   dh,gx,bw
         cmp     dh,0x80
         bne     TestArus_BWWZErr
         mov     aw,0x0001
         mov     cw,0x0007
         asrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0008
         mov     dw,0x0008
         addzx   fh,bw,dw
         cmp     fh,0x10
         bne     TestArus_BWWZErr
         mov     cw,0x0008
         mov     ew,0x0008
         subzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0008
         mov     fw,0x0008
         andzx   al,dw,fw
         cmp     al,0x08
         bne     TestArus_BWWZErr
         mov     ew,0x0008
         mov     gw,0x0008
         orzx    bl,ew,gw
         cmp     bl,0x08
         bne     TestArus_BWWZErr
         mov     fw,0x0008
         mov     ax,0x0008
         xorzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0008
         mov     bx,0x0008
         mulzx   dl,gw,bx
         cmp     dl,0x40
         bne     TestArus_BWWZErr
         mov     ax,0x0008
         mov     cx,0x0008
         udivzx  el,ax,cx
         cmp     el,0x01
         bne     TestArus_BWWZErr
         mov     bx,0x0008
         mov     dx,0x0008
         uremzx  fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0008
         mov     ex,0x0000
         shlzx   gl,cx,ex
         cmp     gl,0x08
         bne     TestArus_BWWZErr
         mov     dx,0x0008
         mov     fx,0x0000
         shrzx   ah,dx,fx
         cmp     ah,0x08
         bne     TestArus_BWWZErr
         mov     ex,0x0008
         mov     gx,0x0000
         rolzx   bh,ex,gx
         cmp     bh,0x08
         bne     TestArus_BWWZErr
         mov     fx,0x0008
         mov     aw,0x0000
         asrzx   ch,fx,aw
         cmp     ch,0x08
         bne     TestArus_BWWZErr
         mov     gx,0x0008
         mov     bw,0x0009
         addzx   dh,gx,bw
         cmp     dh,0x11
         bne     TestArus_BWWZErr
         mov     aw,0x0008
         mov     cw,0x0009
         subzx   eh,aw,cw
         cmp     eh,0xFF
         bne     TestArus_BWWZErr
         mov     bw,0x0008
         mov     dw,0x0009
         andzx   fh,bw,dw
         cmp     fh,0x08
         bne     TestArus_BWWZErr
         mov     cw,0x0008
         mov     ew,0x0009
         orzx    gh,cw,ew
         cmp     gh,0x09
         bne     TestArus_BWWZErr
         mov     dw,0x0008
         mov     fw,0x0009
         xorzx   al,dw,fw
         cmp     al,0x01
         bne     TestArus_BWWZErr
         mov     ew,0x0008
         mov     gw,0x0009
         mulzx   bl,ew,gw
         cmp     bl,0x48
         bne     TestArus_BWWZErr
         mov     fw,0x0008
         mov     ax,0x0009
         udivzx  cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0008
         mov     bx,0x0009
         uremzx  dl,gw,bx
         cmp     dl,0x08
         bne     TestArus_BWWZErr
         mov     ax,0x0008
         mov     cx,0x0001
         shlzx   el,ax,cx
         cmp     el,0x10
         bne     TestArus_BWWZErr
         mov     bx,0x0008
         mov     dx,0x0001
         shrzx   fl,bx,dx
         cmp     fl,0x04
         bne     TestArus_BWWZErr
         mov     cx,0x0008
         mov     ex,0x0001
         rolzx   gl,cx,ex
         cmp     gl,0x10
         bne     TestArus_BWWZErr
         mov     dx,0x0008
         mov     fx,0x0001
         asrzx   ah,dx,fx
         cmp     ah,0x04
         bne     TestArus_BWWZErr
         mov     ex,0x0008
         mov     gx,0x007F
         addzx   bh,ex,gx
         cmp     bh,0x87
         bne     TestArus_BWWZErr
         mov     fx,0x0008
         mov     aw,0x007F
         subzx   ch,fx,aw
         cmp     ch,0x89
         bne     TestArus_BWWZErr
         mov     gx,0x0008
         mov     bw,0x007F
         andzx   dh,gx,bw
         cmp     dh,0x08
         bne     TestArus_BWWZErr
         mov     aw,0x0008
         mov     cw,0x007F
         orzx    eh,aw,cw
         cmp     eh,0x7F
         bne     TestArus_BWWZErr
         mov     bw,0x0008
         mov     dw,0x007F
         xorzx   fh,bw,dw
         cmp     fh,0x77
         bne     TestArus_BWWZErr
         mov     cw,0x0008
         mov     ew,0x007F
         mulzx   gh,cw,ew
         cmp     gh,0xF8
         bne     TestArus_BWWZErr
         mov     dw,0x0008
         mov     fw,0x007F
         udivzx  al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0008
         mov     gw,0x007F
         uremzx  bl,ew,gw
         cmp     bl,0x08
         bne     TestArus_BWWZErr
         mov     fw,0x0008
         mov     ax,0x0007
         shlzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0008
         mov     bx,0x0007
         shrzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0008
         mov     cx,0x0007
         rolzx   el,ax,cx
         cmp     el,0x04
         bne     TestArus_BWWZErr
         mov     bx,0x0008
         mov     dx,0x0007
         asrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0008
         mov     ex,0x0080
         addzx   gl,cx,ex
         cmp     gl,0x88
         bne     TestArus_BWWZErr
         mov     dx,0x0008
         mov     fx,0x0080
         subzx   ah,dx,fx
         cmp     ah,0x88
         bne     TestArus_BWWZErr
         mov     ex,0x0008
         mov     gx,0x0080
         andzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0008
         mov     aw,0x0080
         orzx    ch,fx,aw
         cmp     ch,0x88
         bne     TestArus_BWWZErr
         mov     gx,0x0008
         mov     bw,0x0080
         xorzx   dh,gx,bw
         cmp     dh,0x88
         bne     TestArus_BWWZErr
         mov     aw,0x0008
         mov     cw,0x0080
         mulzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0008
         mov     dw,0x0080
         udivzx  fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0008
         mov     ew,0x0080
         uremzx  gh,cw,ew
         cmp     gh,0x08
         bne     TestArus_BWWZErr
         mov     dw,0x0008
         mov     fw,0x0000
         shlzx   al,dw,fw
         cmp     al,0x08
         bne     TestArus_BWWZErr
         mov     ew,0x0008
         mov     gw,0x0000
         shrzx   bl,ew,gw
         cmp     bl,0x08
         bne     TestArus_BWWZErr
         mov     fw,0x0008
         mov     ax,0x0000
         rolzx   cl,fw,ax
         cmp     cl,0x08
         bne     TestArus_BWWZErr
         mov     gw,0x0008
         mov     bx,0x0000
         asrzx   dl,gw,bx
         cmp     dl,0x08
         bne     TestArus_BWWZErr
         mov     ax,0x0008
         mov     cx,0x7FFF
         addzx   el,ax,cx
         cmp     el,0x07
         bne     TestArus_BWWZErr
         mov     bx,0x0008
         mov     dx,0x7FFF
         subzx   fl,bx,dx
         cmp     fl,0x09
         bne     TestArus_BWWZErr
         mov     cx,0x0008
         mov     ex,0x7FFF
         andzx   gl,cx,ex
         cmp     gl,0x08
         bne     TestArus_BWWZErr
         mov     dx,0x0008
         mov     fx,0x7FFF
         orzx    ah,dx,fx
         cmp     ah,0xFF
         bne     TestArus_BWWZErr
         mov     ex,0x0008
         mov     gx,0x7FFF
         xorzx   bh,ex,gx
         cmp     bh,0xF7
         bne     TestArus_BWWZErr
         mov     fx,0x0008
         mov     aw,0x7FFF
         mulzx   ch,fx,aw
         cmp     ch,0xF8
         bne     TestArus_BWWZErr
         mov     gx,0x0008
         mov     bw,0x7FFF
         udivzx  dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0008
         mov     cw,0x7FFF
         uremzx  eh,aw,cw
         cmp     eh,0x08
         bne     TestArus_BWWZErr
         mov     bw,0x0008
         mov     dw,0x0007
         shlzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0008
         mov     ew,0x0007
         shrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0008
         mov     fw,0x0007
         rolzx   al,dw,fw
         cmp     al,0x04
         bne     TestArus_BWWZErr
         mov     ew,0x0008
         mov     gw,0x0007
         asrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0008
         mov     ax,0x8000
         addzx   cl,fw,ax
         cmp     cl,0x08
         bne     TestArus_BWWZErr
         mov     gw,0x0008
         mov     bx,0x8000
         subzx   dl,gw,bx
         cmp     dl,0x08
         bne     TestArus_BWWZErr
         mov     ax,0x0008
         mov     cx,0x8000
         andzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0008
         mov     dx,0x8000
         orzx    fl,bx,dx
         cmp     fl,0x08
         bne     TestArus_BWWZErr
         mov     cx,0x0008
         mov     ex,0x8000
         xorzx   gl,cx,ex
         cmp     gl,0x08
         bne     TestArus_BWWZErr
         mov     dx,0x0008
         mov     fx,0x8000
         mulzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0008
         mov     gx,0x8000
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0008
         mov     aw,0x8000
         uremzx  ch,fx,aw
         cmp     ch,0x08
         bne     TestArus_BWWZErr
         mov     gx,0x0008
         mov     bw,0x0000
         shlzx   dh,gx,bw
         cmp     dh,0x08
         bne     TestArus_BWWZErr
         mov     aw,0x0008
         mov     cw,0x0000
         shrzx   eh,aw,cw
         cmp     eh,0x08
         bne     TestArus_BWWZErr
         mov     bw,0x0008
         mov     dw,0x0000
         rolzx   fh,bw,dw
         cmp     fh,0x08
         bne     TestArus_BWWZErr
         mov     cw,0x0008
         mov     ew,0x0000
         asrzx   gh,cw,ew
         cmp     gh,0x08
         bne     TestArus_BWWZErr
         mov     dw,0x0008
         mov     fw,0xFFFF
         addzx   al,dw,fw
         cmp     al,0x07
         bne     TestArus_BWWZErr
         mov     ew,0x0008
         mov     gw,0xFFFF
         subzx   bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0008
         mov     ax,0xFFFF
         andzx   cl,fw,ax
         cmp     cl,0x08
         bne     TestArus_BWWZErr
         mov     gw,0x0008
         mov     bx,0xFFFF
         orzx    dl,gw,bx
         cmp     dl,0xFF
         bne     TestArus_BWWZErr
         mov     ax,0x0008
         mov     cx,0xFFFF
         xorzx   el,ax,cx
         cmp     el,0xF7
         bne     TestArus_BWWZErr
         mov     bx,0x0008
         mov     dx,0xFFFF
         mulzx   fl,bx,dx
         cmp     fl,0xF8
         bne     TestArus_BWWZErr
         mov     cx,0x0008
         mov     ex,0xFFFF
         udivzx  gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0008
         mov     fx,0xFFFF
         uremzx  ah,dx,fx
         cmp     ah,0x08
         bne     TestArus_BWWZErr
         mov     ex,0x0008
         mov     gx,0x0007
         shlzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0008
         mov     aw,0x0007
         shrzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0008
         mov     bw,0x0007
         rolzx   dh,gx,bw
         cmp     dh,0x04
         bne     TestArus_BWWZErr
         mov     aw,0x0008
         mov     cw,0x0007
         asrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0009
         mov     dw,0x0009
         addzx   fh,bw,dw
         cmp     fh,0x12
         bne     TestArus_BWWZErr
         mov     cw,0x0009
         mov     ew,0x0009
         subzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0009
         mov     fw,0x0009
         andzx   al,dw,fw
         cmp     al,0x09
         bne     TestArus_BWWZErr
         mov     ew,0x0009
         mov     gw,0x0009
         orzx    bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0009
         mov     ax,0x0009
         xorzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0009
         mov     bx,0x0009
         mulzx   dl,gw,bx
         cmp     dl,0x51
         bne     TestArus_BWWZErr
         mov     ax,0x0009
         mov     cx,0x0009
         udivzx  el,ax,cx
         cmp     el,0x01
         bne     TestArus_BWWZErr
         mov     bx,0x0009
         mov     dx,0x0009
         uremzx  fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0009
         mov     ex,0x0001
         shlzx   gl,cx,ex
         cmp     gl,0x12
         bne     TestArus_BWWZErr
         mov     dx,0x0009
         mov     fx,0x0001
         shrzx   ah,dx,fx
         cmp     ah,0x04
         bne     TestArus_BWWZErr
         mov     ex,0x0009
         mov     gx,0x0001
         rolzx   bh,ex,gx
         cmp     bh,0x12
         bne     TestArus_BWWZErr
         mov     fx,0x0009
         mov     aw,0x0001
         asrzx   ch,fx,aw
         cmp     ch,0x04
         bne     TestArus_BWWZErr
         mov     gx,0x0009
         mov     bw,0x007F
         addzx   dh,gx,bw
         cmp     dh,0x88
         bne     TestArus_BWWZErr
         mov     aw,0x0009
         mov     cw,0x007F
         subzx   eh,aw,cw
         cmp     eh,0x8A
         bne     TestArus_BWWZErr
         mov     bw,0x0009
         mov     dw,0x007F
         andzx   fh,bw,dw
         cmp     fh,0x09
         bne     TestArus_BWWZErr
         mov     cw,0x0009
         mov     ew,0x007F
         orzx    gh,cw,ew
         cmp     gh,0x7F
         bne     TestArus_BWWZErr
         mov     dw,0x0009
         mov     fw,0x007F
         xorzx   al,dw,fw
         cmp     al,0x76
         bne     TestArus_BWWZErr
         mov     ew,0x0009
         mov     gw,0x007F
         mulzx   bl,ew,gw
         cmp     bl,0x77
         bne     TestArus_BWWZErr
         mov     fw,0x0009
         mov     ax,0x007F
         udivzx  cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0009
         mov     bx,0x007F
         uremzx  dl,gw,bx
         cmp     dl,0x09
         bne     TestArus_BWWZErr
         mov     ax,0x0009
         mov     cx,0x0007
         shlzx   el,ax,cx
         cmp     el,0x80
         bne     TestArus_BWWZErr
         mov     bx,0x0009
         mov     dx,0x0007
         shrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0009
         mov     ex,0x0007
         rolzx   gl,cx,ex
         cmp     gl,0x84
         bne     TestArus_BWWZErr
         mov     dx,0x0009
         mov     fx,0x0007
         asrzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x0009
         mov     gx,0x0080
         addzx   bh,ex,gx
         cmp     bh,0x89
         bne     TestArus_BWWZErr
         mov     fx,0x0009
         mov     aw,0x0080
         subzx   ch,fx,aw
         cmp     ch,0x89
         bne     TestArus_BWWZErr
         mov     gx,0x0009
         mov     bw,0x0080
         andzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0009
         mov     cw,0x0080
         orzx    eh,aw,cw
         cmp     eh,0x89
         bne     TestArus_BWWZErr
         mov     bw,0x0009
         mov     dw,0x0080
         xorzx   fh,bw,dw
         cmp     fh,0x89
         bne     TestArus_BWWZErr
         mov     cw,0x0009
         mov     ew,0x0080
         mulzx   gh,cw,ew
         cmp     gh,0x80
         bne     TestArus_BWWZErr
         mov     dw,0x0009
         mov     fw,0x0080
         udivzx  al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x0009
         mov     gw,0x0080
         uremzx  bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0009
         mov     ax,0x0000
         shlzx   cl,fw,ax
         cmp     cl,0x09
         bne     TestArus_BWWZErr
         mov     gw,0x0009
         mov     bx,0x0000
         shrzx   dl,gw,bx
         cmp     dl,0x09
         bne     TestArus_BWWZErr
         mov     ax,0x0009
         mov     cx,0x0000
         rolzx   el,ax,cx
         cmp     el,0x09
         bne     TestArus_BWWZErr
         mov     bx,0x0009
         mov     dx,0x0000
         asrzx   fl,bx,dx
         cmp     fl,0x09
         bne     TestArus_BWWZErr
         mov     cx,0x0009
         mov     ex,0x7FFF
         addzx   gl,cx,ex
         cmp     gl,0x08
         bne     TestArus_BWWZErr
         mov     dx,0x0009
         mov     fx,0x7FFF
         subzx   ah,dx,fx
         cmp     ah,0x0A
         bne     TestArus_BWWZErr
         mov     ex,0x0009
         mov     gx,0x7FFF
         andzx   bh,ex,gx
         cmp     bh,0x09
         bne     TestArus_BWWZErr
         mov     fx,0x0009
         mov     aw,0x7FFF
         orzx    ch,fx,aw
         cmp     ch,0xFF
         bne     TestArus_BWWZErr
         mov     gx,0x0009
         mov     bw,0x7FFF
         xorzx   dh,gx,bw
         cmp     dh,0xF6
         bne     TestArus_BWWZErr
         mov     aw,0x0009
         mov     cw,0x7FFF
         mulzx   eh,aw,cw
         cmp     eh,0xF7
         bne     TestArus_BWWZErr
         mov     bw,0x0009
         mov     dw,0x7FFF
         udivzx  fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0009
         mov     ew,0x7FFF
         uremzx  gh,cw,ew
         cmp     gh,0x09
         bne     TestArus_BWWZErr
         mov     dw,0x0009
         mov     fw,0x0007
         shlzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x0009
         mov     gw,0x0007
         shrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x0009
         mov     ax,0x0007
         rolzx   cl,fw,ax
         cmp     cl,0x84
         bne     TestArus_BWWZErr
         mov     gw,0x0009
         mov     bx,0x0007
         asrzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0009
         mov     cx,0x8000
         addzx   el,ax,cx
         cmp     el,0x09
         bne     TestArus_BWWZErr
         mov     bx,0x0009
         mov     dx,0x8000
         subzx   fl,bx,dx
         cmp     fl,0x09
         bne     TestArus_BWWZErr
         mov     cx,0x0009
         mov     ex,0x8000
         andzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0009
         mov     fx,0x8000
         orzx    ah,dx,fx
         cmp     ah,0x09
         bne     TestArus_BWWZErr
         mov     ex,0x0009
         mov     gx,0x8000
         xorzx   bh,ex,gx
         cmp     bh,0x09
         bne     TestArus_BWWZErr
         mov     fx,0x0009
         mov     aw,0x8000
         mulzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0009
         mov     bw,0x8000
         udivzx  dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0009
         mov     cw,0x8000
         uremzx  eh,aw,cw
         cmp     eh,0x09
         bne     TestArus_BWWZErr
         mov     bw,0x0009
         mov     dw,0x0000
         shlzx   fh,bw,dw
         cmp     fh,0x09
         bne     TestArus_BWWZErr
         mov     cw,0x0009
         mov     ew,0x0000
         shrzx   gh,cw,ew
         cmp     gh,0x09
         bne     TestArus_BWWZErr
         mov     dw,0x0009
         mov     fw,0x0000
         rolzx   al,dw,fw
         cmp     al,0x09
         bne     TestArus_BWWZErr
         mov     ew,0x0009
         mov     gw,0x0000
         asrzx   bl,ew,gw
         cmp     bl,0x09
         bne     TestArus_BWWZErr
         mov     fw,0x0009
         mov     ax,0xFFFF
         addzx   cl,fw,ax
         cmp     cl,0x08
         bne     TestArus_BWWZErr
         mov     gw,0x0009
         mov     bx,0xFFFF
         subzx   dl,gw,bx
         cmp     dl,0x0A
         bne     TestArus_BWWZErr
         mov     ax,0x0009
         mov     cx,0xFFFF
         andzx   el,ax,cx
         cmp     el,0x09
         bne     TestArus_BWWZErr
         mov     bx,0x0009
         mov     dx,0xFFFF
         orzx    fl,bx,dx
         cmp     fl,0xFF
         bne     TestArus_BWWZErr
         mov     cx,0x0009
         mov     ex,0xFFFF
         xorzx   gl,cx,ex
         cmp     gl,0xF6
         bne     TestArus_BWWZErr
         mov     dx,0x0009
         mov     fx,0xFFFF
         mulzx   ah,dx,fx
         cmp     ah,0xF7
         bne     TestArus_BWWZErr
         mov     ex,0x0009
         mov     gx,0xFFFF
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0009
         mov     aw,0xFFFF
         uremzx  ch,fx,aw
         cmp     ch,0x09
         bne     TestArus_BWWZErr
         mov     gx,0x0009
         mov     bw,0x0007
         shlzx   dh,gx,bw
         cmp     dh,0x80
         bne     TestArus_BWWZErr
         mov     aw,0x0009
         mov     cw,0x0007
         shrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0009
         mov     dw,0x0007
         rolzx   fh,bw,dw
         cmp     fh,0x84
         bne     TestArus_BWWZErr
         mov     cw,0x0009
         mov     ew,0x0007
         asrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x007F
         mov     fw,0x007F
         addzx   al,dw,fw
         cmp     al,0xFE
         bne     TestArus_BWWZErr
         mov     ew,0x007F
         mov     gw,0x007F
         subzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x007F
         mov     ax,0x007F
         andzx   cl,fw,ax
         cmp     cl,0x7F
         bne     TestArus_BWWZErr
         mov     gw,0x007F
         mov     bx,0x007F
         orzx    dl,gw,bx
         cmp     dl,0x7F
         bne     TestArus_BWWZErr
         mov     ax,0x007F
         mov     cx,0x007F
         xorzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x007F
         mov     dx,0x007F
         mulzx   fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0x007F
         mov     ex,0x007F
         udivzx  gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0x007F
         mov     fx,0x007F
         uremzx  ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x007F
         mov     gx,0x0007
         shlzx   bh,ex,gx
         cmp     bh,0x80
         bne     TestArus_BWWZErr
         mov     fx,0x007F
         mov     aw,0x0007
         shrzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x007F
         mov     bw,0x0007
         rolzx   dh,gx,bw
         cmp     dh,0xBF
         bne     TestArus_BWWZErr
         mov     aw,0x007F
         mov     cw,0x0007
         asrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x007F
         mov     dw,0x0080
         addzx   fh,bw,dw
         cmp     fh,0xFF
         bne     TestArus_BWWZErr
         mov     cw,0x007F
         mov     ew,0x0080
         subzx   gh,cw,ew
         cmp     gh,0xFF
         bne     TestArus_BWWZErr
         mov     dw,0x007F
         mov     fw,0x0080
         andzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x007F
         mov     gw,0x0080
         orzx    bl,ew,gw
         cmp     bl,0xFF
         bne     TestArus_BWWZErr
         mov     fw,0x007F
         mov     ax,0x0080
         xorzx   cl,fw,ax
         cmp     cl,0xFF
         bne     TestArus_BWWZErr
         mov     gw,0x007F
         mov     bx,0x0080
         mulzx   dl,gw,bx
         cmp     dl,0x80
         bne     TestArus_BWWZErr
         mov     ax,0x007F
         mov     cx,0x0080
         udivzx  el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x007F
         mov     dx,0x0080
         uremzx  fl,bx,dx
         cmp     fl,0x7F
         bne     TestArus_BWWZErr
         mov     cx,0x007F
         mov     ex,0x0000
         shlzx   gl,cx,ex
         cmp     gl,0x7F
         bne     TestArus_BWWZErr
         mov     dx,0x007F
         mov     fx,0x0000
         shrzx   ah,dx,fx
         cmp     ah,0x7F
         bne     TestArus_BWWZErr
         mov     ex,0x007F
         mov     gx,0x0000
         rolzx   bh,ex,gx
         cmp     bh,0x7F
         bne     TestArus_BWWZErr
         mov     fx,0x007F
         mov     aw,0x0000
         asrzx   ch,fx,aw
         cmp     ch,0x7F
         bne     TestArus_BWWZErr
         mov     gx,0x007F
         mov     bw,0x7FFF
         addzx   dh,gx,bw
         cmp     dh,0x7E
         bne     TestArus_BWWZErr
         mov     aw,0x007F
         mov     cw,0x7FFF
         subzx   eh,aw,cw
         cmp     eh,0x80
         bne     TestArus_BWWZErr
         mov     bw,0x007F
         mov     dw,0x7FFF
         andzx   fh,bw,dw
         cmp     fh,0x7F
         bne     TestArus_BWWZErr
         mov     cw,0x007F
         mov     ew,0x7FFF
         orzx    gh,cw,ew
         cmp     gh,0xFF
         bne     TestArus_BWWZErr
         mov     dw,0x007F
         mov     fw,0x7FFF
         xorzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x007F
         mov     gw,0x7FFF
         mulzx   bl,ew,gw
         cmp     bl,0x81
         bne     TestArus_BWWZErr
         mov     fw,0x007F
         mov     ax,0x7FFF
         udivzx  cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x007F
         mov     bx,0x7FFF
         uremzx  dl,gw,bx
         cmp     dl,0x7F
         bne     TestArus_BWWZErr
         mov     ax,0x007F
         mov     cx,0x0007
         shlzx   el,ax,cx
         cmp     el,0x80
         bne     TestArus_BWWZErr
         mov     bx,0x007F
         mov     dx,0x0007
         shrzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x007F
         mov     ex,0x0007
         rolzx   gl,cx,ex
         cmp     gl,0xBF
         bne     TestArus_BWWZErr
         mov     dx,0x007F
         mov     fx,0x0007
         asrzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x007F
         mov     gx,0x8000
         addzx   bh,ex,gx
         cmp     bh,0x7F
         bne     TestArus_BWWZErr
         mov     fx,0x007F
         mov     aw,0x8000
         subzx   ch,fx,aw
         cmp     ch,0x7F
         bne     TestArus_BWWZErr
         mov     gx,0x007F
         mov     bw,0x8000
         andzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x007F
         mov     cw,0x8000
         orzx    eh,aw,cw
         cmp     eh,0x7F
         bne     TestArus_BWWZErr
         mov     bw,0x007F
         mov     dw,0x8000
         xorzx   fh,bw,dw
         cmp     fh,0x7F
         bne     TestArus_BWWZErr
         mov     cw,0x007F
         mov     ew,0x8000
         mulzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x007F
         mov     fw,0x8000
         udivzx  al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x007F
         mov     gw,0x8000
         uremzx  bl,ew,gw
         cmp     bl,0x7F
         bne     TestArus_BWWZErr
         mov     fw,0x007F
         mov     ax,0x0000
         shlzx   cl,fw,ax
         cmp     cl,0x7F
         bne     TestArus_BWWZErr
         mov     gw,0x007F
         mov     bx,0x0000
         shrzx   dl,gw,bx
         cmp     dl,0x7F
         bne     TestArus_BWWZErr
         mov     ax,0x007F
         mov     cx,0x0000
         rolzx   el,ax,cx
         cmp     el,0x7F
         bne     TestArus_BWWZErr
         mov     bx,0x007F
         mov     dx,0x0000
         asrzx   fl,bx,dx
         cmp     fl,0x7F
         bne     TestArus_BWWZErr
         mov     cx,0x007F
         mov     ex,0xFFFF
         addzx   gl,cx,ex
         cmp     gl,0x7E
         bne     TestArus_BWWZErr
         mov     dx,0x007F
         mov     fx,0xFFFF
         subzx   ah,dx,fx
         cmp     ah,0x80
         bne     TestArus_BWWZErr
         mov     ex,0x007F
         mov     gx,0xFFFF
         andzx   bh,ex,gx
         cmp     bh,0x7F
         bne     TestArus_BWWZErr
         mov     fx,0x007F
         mov     aw,0xFFFF
         orzx    ch,fx,aw
         cmp     ch,0xFF
         bne     TestArus_BWWZErr
         mov     gx,0x007F
         mov     bw,0xFFFF
         xorzx   dh,gx,bw
         cmp     dh,0x80
         bne     TestArus_BWWZErr
         mov     aw,0x007F
         mov     cw,0xFFFF
         mulzx   eh,aw,cw
         cmp     eh,0x81
         bne     TestArus_BWWZErr
         mov     bw,0x007F
         mov     dw,0xFFFF
         udivzx  fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x007F
         mov     ew,0xFFFF
         uremzx  gh,cw,ew
         cmp     gh,0x7F
         bne     TestArus_BWWZErr
         mov     dw,0x007F
         mov     fw,0x0007
         shlzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x007F
         mov     gw,0x0007
         shrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x007F
         mov     ax,0x0007
         rolzx   cl,fw,ax
         cmp     cl,0xBF
         bne     TestArus_BWWZErr
         mov     gw,0x007F
         mov     bx,0x0007
         asrzx   dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x0080
         mov     cx,0x0080
         addzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0080
         mov     dx,0x0080
         subzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0080
         mov     ex,0x0080
         andzx   gl,cx,ex
         cmp     gl,0x80
         bne     TestArus_BWWZErr
         mov     dx,0x0080
         mov     fx,0x0080
         orzx    ah,dx,fx
         cmp     ah,0x80
         bne     TestArus_BWWZErr
         mov     ex,0x0080
         mov     gx,0x0080
         xorzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0080
         mov     aw,0x0080
         mulzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0080
         mov     bw,0x0080
         udivzx  dh,gx,bw
         cmp     dh,0x01
         bne     TestArus_BWWZErr
         mov     aw,0x0080
         mov     cw,0x0080
         uremzx  eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0080
         mov     dw,0x0000
         shlzx   fh,bw,dw
         cmp     fh,0x80
         bne     TestArus_BWWZErr
         mov     cw,0x0080
         mov     ew,0x0000
         shrzx   gh,cw,ew
         cmp     gh,0x80
         bne     TestArus_BWWZErr
         mov     dw,0x0080
         mov     fw,0x0000
         rolzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x0080
         mov     gw,0x0000
         asrzx   bl,ew,gw
         cmp     bl,0x80
         bne     TestArus_BWWZErr
         mov     fw,0x0080
         mov     ax,0x7FFF
         addzx   cl,fw,ax
         cmp     cl,0x7F
         bne     TestArus_BWWZErr
         mov     gw,0x0080
         mov     bx,0x7FFF
         subzx   dl,gw,bx
         cmp     dl,0x81
         bne     TestArus_BWWZErr
         mov     ax,0x0080
         mov     cx,0x7FFF
         andzx   el,ax,cx
         cmp     el,0x80
         bne     TestArus_BWWZErr
         mov     bx,0x0080
         mov     dx,0x7FFF
         orzx    fl,bx,dx
         cmp     fl,0xFF
         bne     TestArus_BWWZErr
         mov     cx,0x0080
         mov     ex,0x7FFF
         xorzx   gl,cx,ex
         cmp     gl,0x7F
         bne     TestArus_BWWZErr
         mov     dx,0x0080
         mov     fx,0x7FFF
         mulzx   ah,dx,fx
         cmp     ah,0x80
         bne     TestArus_BWWZErr
         mov     ex,0x0080
         mov     gx,0x7FFF
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x0080
         mov     aw,0x7FFF
         uremzx  ch,fx,aw
         cmp     ch,0x80
         bne     TestArus_BWWZErr
         mov     gx,0x0080
         mov     bw,0x0007
         shlzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0080
         mov     cw,0x0007
         shrzx   eh,aw,cw
         cmp     eh,0x01
         bne     TestArus_BWWZErr
         mov     bw,0x0080
         mov     dw,0x0007
         rolzx   fh,bw,dw
         cmp     fh,0x40
         bne     TestArus_BWWZErr
         mov     cw,0x0080
         mov     ew,0x0007
         asrzx   gh,cw,ew
         cmp     gh,0x01
         bne     TestArus_BWWZErr
         mov     dw,0x0080
         mov     fw,0x8000
         addzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x0080
         mov     gw,0x8000
         subzx   bl,ew,gw
         cmp     bl,0x80
         bne     TestArus_BWWZErr
         mov     fw,0x0080
         mov     ax,0x8000
         andzx   cl,fw,ax
         cmp     cl,0x00
         bne     TestArus_BWWZErr
         mov     gw,0x0080
         mov     bx,0x8000
         orzx    dl,gw,bx
         cmp     dl,0x80
         bne     TestArus_BWWZErr
         mov     ax,0x0080
         mov     cx,0x8000
         xorzx   el,ax,cx
         cmp     el,0x80
         bne     TestArus_BWWZErr
         mov     bx,0x0080
         mov     dx,0x8000
         mulzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x0080
         mov     ex,0x8000
         udivzx  gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0080
         mov     fx,0x8000
         uremzx  ah,dx,fx
         cmp     ah,0x80
         bne     TestArus_BWWZErr
         mov     ex,0x0080
         mov     gx,0x0000
         shlzx   bh,ex,gx
         cmp     bh,0x80
         bne     TestArus_BWWZErr
         mov     fx,0x0080
         mov     aw,0x0000
         shrzx   ch,fx,aw
         cmp     ch,0x80
         bne     TestArus_BWWZErr
         mov     gx,0x0080
         mov     bw,0x0000
         rolzx   dh,gx,bw
         cmp     dh,0x80
         bne     TestArus_BWWZErr
         mov     aw,0x0080
         mov     cw,0x0000
         asrzx   eh,aw,cw
         cmp     eh,0x80
         bne     TestArus_BWWZErr
         mov     bw,0x0080
         mov     dw,0xFFFF
         addzx   fh,bw,dw
         cmp     fh,0x7F
         bne     TestArus_BWWZErr
         mov     cw,0x0080
         mov     ew,0xFFFF
         subzx   gh,cw,ew
         cmp     gh,0x81
         bne     TestArus_BWWZErr
         mov     dw,0x0080
         mov     fw,0xFFFF
         andzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x0080
         mov     gw,0xFFFF
         orzx    bl,ew,gw
         cmp     bl,0xFF
         bne     TestArus_BWWZErr
         mov     fw,0x0080
         mov     ax,0xFFFF
         xorzx   cl,fw,ax
         cmp     cl,0x7F
         bne     TestArus_BWWZErr
         mov     gw,0x0080
         mov     bx,0xFFFF
         mulzx   dl,gw,bx
         cmp     dl,0x80
         bne     TestArus_BWWZErr
         mov     ax,0x0080
         mov     cx,0xFFFF
         udivzx  el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x0080
         mov     dx,0xFFFF
         uremzx  fl,bx,dx
         cmp     fl,0x80
         bne     TestArus_BWWZErr
         mov     cx,0x0080
         mov     ex,0x0007
         shlzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x0080
         mov     fx,0x0007
         shrzx   ah,dx,fx
         cmp     ah,0x01
         bne     TestArus_BWWZErr
         mov     ex,0x0080
         mov     gx,0x0007
         rolzx   bh,ex,gx
         cmp     bh,0x40
         bne     TestArus_BWWZErr
         mov     fx,0x0080
         mov     aw,0x0007
         asrzx   ch,fx,aw
         cmp     ch,0x01
         bne     TestArus_BWWZErr
         mov     gx,0x7FFF
         mov     bw,0x7FFF
         addzx   dh,gx,bw
         cmp     dh,0xFE
         bne     TestArus_BWWZErr
         mov     aw,0x7FFF
         mov     cw,0x7FFF
         subzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x7FFF
         mov     dw,0x7FFF
         andzx   fh,bw,dw
         cmp     fh,0xFF
         bne     TestArus_BWWZErr
         mov     cw,0x7FFF
         mov     ew,0x7FFF
         orzx    gh,cw,ew
         cmp     gh,0xFF
         bne     TestArus_BWWZErr
         mov     dw,0x7FFF
         mov     fw,0x7FFF
         xorzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x7FFF
         mov     gw,0x7FFF
         mulzx   bl,ew,gw
         cmp     bl,0x01
         bne     TestArus_BWWZErr
         mov     fw,0x7FFF
         mov     ax,0x7FFF
         udivzx  cl,fw,ax
         cmp     cl,0x01
         bne     TestArus_BWWZErr
         mov     gw,0x7FFF
         mov     bx,0x7FFF
         uremzx  dl,gw,bx
         cmp     dl,0x00
         bne     TestArus_BWWZErr
         mov     ax,0x00FF
         mov     cx,0x0007
         shlzx   el,ax,cx
         cmp     el,0x80
         bne     TestArus_BWWZErr
         mov     bx,0x00FF
         mov     dx,0x0007
         shrzx   fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0x00FF
         mov     ex,0x0007
         rolzx   gl,cx,ex
         cmp     gl,0xFF
         bne     TestArus_BWWZErr
         mov     dx,0x7FFF
         mov     fx,0x0007
         asrzx   ah,dx,fx
         cmp     ah,0xFF
         bne     TestArus_BWWZErr
         mov     ex,0x7FFF
         mov     gx,0x8000
         addzx   bh,ex,gx
         cmp     bh,0xFF
         bne     TestArus_BWWZErr
         mov     fx,0x7FFF
         mov     aw,0x8000
         subzx   ch,fx,aw
         cmp     ch,0xFF
         bne     TestArus_BWWZErr
         mov     gx,0x7FFF
         mov     bw,0x8000
         andzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x7FFF
         mov     cw,0x8000
         orzx    eh,aw,cw
         cmp     eh,0xFF
         bne     TestArus_BWWZErr
         mov     bw,0x7FFF
         mov     dw,0x8000
         xorzx   fh,bw,dw
         cmp     fh,0xFF
         bne     TestArus_BWWZErr
         mov     cw,0x7FFF
         mov     ew,0x8000
         mulzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x7FFF
         mov     fw,0x8000
         udivzx  al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x7FFF
         mov     gw,0x8000
         uremzx  bl,ew,gw
         cmp     bl,0xFF
         bne     TestArus_BWWZErr
         mov     fw,0x00FF
         mov     ax,0x0000
         shlzx   cl,fw,ax
         cmp     cl,0xFF
         bne     TestArus_BWWZErr
         mov     gw,0x00FF
         mov     bx,0x0000
         shrzx   dl,gw,bx
         cmp     dl,0xFF
         bne     TestArus_BWWZErr
         mov     ax,0x00FF
         mov     cx,0x0000
         rolzx   el,ax,cx
         cmp     el,0xFF
         bne     TestArus_BWWZErr
         mov     bx,0x7FFF
         mov     dx,0x0000
         asrzx   fl,bx,dx
         cmp     fl,0xFF
         bne     TestArus_BWWZErr
         mov     cx,0x7FFF
         mov     ex,0xFFFF
         addzx   gl,cx,ex
         cmp     gl,0xFE
         bne     TestArus_BWWZErr
         mov     dx,0x7FFF
         mov     fx,0xFFFF
         subzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x7FFF
         mov     gx,0xFFFF
         andzx   bh,ex,gx
         cmp     bh,0xFF
         bne     TestArus_BWWZErr
         mov     fx,0x7FFF
         mov     aw,0xFFFF
         orzx    ch,fx,aw
         cmp     ch,0xFF
         bne     TestArus_BWWZErr
         mov     gx,0x7FFF
         mov     bw,0xFFFF
         xorzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x7FFF
         mov     cw,0xFFFF
         mulzx   eh,aw,cw
         cmp     eh,0x01
         bne     TestArus_BWWZErr
         mov     bw,0x7FFF
         mov     dw,0xFFFF
         udivzx  fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x7FFF
         mov     ew,0xFFFF
         uremzx  gh,cw,ew
         cmp     gh,0xFF
         bne     TestArus_BWWZErr
         mov     dw,0x00FF
         mov     fw,0x0007
         shlzx   al,dw,fw
         cmp     al,0x80
         bne     TestArus_BWWZErr
         mov     ew,0x00FF
         mov     gw,0x0007
         shrzx   bl,ew,gw
         cmp     bl,0x01
         bne     TestArus_BWWZErr
         mov     fw,0x00FF
         mov     ax,0x0007
         rolzx   cl,fw,ax
         cmp     cl,0xFF
         bne     TestArus_BWWZErr
         mov     gw,0x7FFF
         mov     bx,0x0007
         asrzx   dl,gw,bx
         cmp     dl,0xFF
         bne     TestArus_BWWZErr
         mov     ax,0x8000
         mov     cx,0x8000
         addzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x8000
         mov     dx,0x8000
         subzx   fl,bx,dx
         cmp     fl,0x00
         bne     TestArus_BWWZErr
         mov     cx,0x8000
         mov     ex,0x8000
         andzx   gl,cx,ex
         cmp     gl,0x00
         bne     TestArus_BWWZErr
         mov     dx,0x8000
         mov     fx,0x8000
         orzx    ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x8000
         mov     gx,0x8000
         xorzx   bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x8000
         mov     aw,0x8000
         mulzx   ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x8000
         mov     bw,0x8000
         udivzx  dh,gx,bw
         cmp     dh,0x01
         bne     TestArus_BWWZErr
         mov     aw,0x8000
         mov     cw,0x8000
         uremzx  eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0000
         shlzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x0000
         mov     ew,0x0000
         shrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0x0000
         mov     fw,0x0000
         rolzx   al,dw,fw
         cmp     al,0x00
         bne     TestArus_BWWZErr
         mov     ew,0x8000
         mov     gw,0x0000
         asrzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0x8000
         mov     ax,0xFFFF
         addzx   cl,fw,ax
         cmp     cl,0xFF
         bne     TestArus_BWWZErr
         mov     gw,0x8000
         mov     bx,0xFFFF
         subzx   dl,gw,bx
         cmp     dl,0x01
         bne     TestArus_BWWZErr
         mov     ax,0x8000
         mov     cx,0xFFFF
         andzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0x8000
         mov     dx,0xFFFF
         orzx    fl,bx,dx
         cmp     fl,0xFF
         bne     TestArus_BWWZErr
         mov     cx,0x8000
         mov     ex,0xFFFF
         xorzx   gl,cx,ex
         cmp     gl,0xFF
         bne     TestArus_BWWZErr
         mov     dx,0x8000
         mov     fx,0xFFFF
         mulzx   ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x8000
         mov     gx,0xFFFF
         udivzx  bh,ex,gx
         cmp     bh,0x00
         bne     TestArus_BWWZErr
         mov     fx,0x8000
         mov     aw,0xFFFF
         uremzx  ch,fx,aw
         cmp     ch,0x00
         bne     TestArus_BWWZErr
         mov     gx,0x0000
         mov     bw,0x0007
         shlzx   dh,gx,bw
         cmp     dh,0x00
         bne     TestArus_BWWZErr
         mov     aw,0x0000
         mov     cw,0x0007
         shrzx   eh,aw,cw
         cmp     eh,0x00
         bne     TestArus_BWWZErr
         mov     bw,0x0000
         mov     dw,0x0007
         rolzx   fh,bw,dw
         cmp     fh,0x00
         bne     TestArus_BWWZErr
         mov     cw,0x8000
         mov     ew,0x0007
         asrzx   gh,cw,ew
         cmp     gh,0x00
         bne     TestArus_BWWZErr
         mov     dw,0xFFFF
         mov     fw,0xFFFF
         addzx   al,dw,fw
         cmp     al,0xFE
         bne     TestArus_BWWZErr
         mov     ew,0xFFFF
         mov     gw,0xFFFF
         subzx   bl,ew,gw
         cmp     bl,0x00
         bne     TestArus_BWWZErr
         mov     fw,0xFFFF
         mov     ax,0xFFFF
         andzx   cl,fw,ax
         cmp     cl,0xFF
         bne     TestArus_BWWZErr
         mov     gw,0xFFFF
         mov     bx,0xFFFF
         orzx    dl,gw,bx
         cmp     dl,0xFF
         bne     TestArus_BWWZErr
         mov     ax,0xFFFF
         mov     cx,0xFFFF
         xorzx   el,ax,cx
         cmp     el,0x00
         bne     TestArus_BWWZErr
         mov     bx,0xFFFF
         mov     dx,0xFFFF
         mulzx   fl,bx,dx
         cmp     fl,0x01
         bne     TestArus_BWWZErr
         mov     cx,0xFFFF
         mov     ex,0xFFFF
         udivzx  gl,cx,ex
         cmp     gl,0x01
         bne     TestArus_BWWZErr
         mov     dx,0xFFFF
         mov     fx,0xFFFF
         uremzx  ah,dx,fx
         cmp     ah,0x00
         bne     TestArus_BWWZErr
         mov     ex,0x00FF
         mov     gx,0x0007
         shlzx   bh,ex,gx
         cmp     bh,0x80
         bne     TestArus_BWWZErr
         mov     fx,0x00FF
         mov     aw,0x0007
         shrzx   ch,fx,aw
         cmp     ch,0x01
         bne     TestArus_BWWZErr
         mov     gx,0x00FF
         mov     bw,0x0007
         rolzx   dh,gx,bw
         cmp     dh,0xFF
         bne     TestArus_BWWZErr
         mov     aw,0xFFFF
         mov     cw,0x0007
         asrzx   eh,aw,cw
         cmp     eh,0xFF
         bne     TestArus_BWWZErr
         bra     TestArus_BWWZRet
TestArus_BWWZErr:
         nop     
         trap    
         nop     
TestArus_BWWZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
