.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BBBS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BBBS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cl,0x00
         addsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x00
         mov     dl,0x00
         subsx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x00
         mov     el,0x00
         andsx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x00
         mov     fl,0x00
         orsx    ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x00
         mov     gl,0x00
         xorsx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x00
         mov     ah,0x00
         mulsx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBSErr
         mov     gl,0x00
         mov     bh,0x00
         sdivsx  dh,gl,bh
         cmp     dh,0xFF
         bne     TestArus_BBBSErr
         mov     ah,0x00
         mov     ch,0x00
         sremsx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBSErr
         mov     bh,0x00
         mov     dh,0x01
         addsx   fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBSErr
         mov     ch,0x00
         mov     eh,0x01
         subsx   gh,ch,eh
         cmp     gh,0xFF
         bne     TestArus_BBBSErr
         mov     dh,0x00
         mov     fh,0x01
         andsx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x00
         mov     gh,0x01
         orsx    bl,eh,gh
         cmp     bl,0x01
         bne     TestArus_BBBSErr
         mov     fh,0x00
         mov     al,0x01
         xorsx   cl,fh,al
         cmp     cl,0x01
         bne     TestArus_BBBSErr
         mov     gh,0x00
         mov     bl,0x01
         mulsx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBSErr
         mov     al,0x00
         mov     cl,0x01
         sdivsx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x00
         mov     dl,0x01
         sremsx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x00
         mov     el,0x07
         addsx   gl,cl,el
         cmp     gl,0x07
         bne     TestArus_BBBSErr
         mov     dl,0x00
         mov     fl,0x07
         subsx   ah,dl,fl
         cmp     ah,0xF9
         bne     TestArus_BBBSErr
         mov     el,0x00
         mov     gl,0x07
         andsx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x00
         mov     ah,0x07
         orsx    ch,fl,ah
         cmp     ch,0x07
         bne     TestArus_BBBSErr
         mov     gl,0x00
         mov     bh,0x07
         xorsx   dh,gl,bh
         cmp     dh,0x07
         bne     TestArus_BBBSErr
         mov     ah,0x00
         mov     ch,0x07
         mulsx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBSErr
         mov     bh,0x00
         mov     dh,0x07
         sdivsx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBSErr
         mov     ch,0x00
         mov     eh,0x07
         sremsx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         mov     dh,0x00
         mov     fh,0x08
         addsx   al,dh,fh
         cmp     al,0x08
         bne     TestArus_BBBSErr
         mov     eh,0x00
         mov     gh,0x08
         subsx   bl,eh,gh
         cmp     bl,0xF8
         bne     TestArus_BBBSErr
         mov     fh,0x00
         mov     al,0x08
         andsx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBSErr
         mov     gh,0x00
         mov     bl,0x08
         orsx    dl,gh,bl
         cmp     dl,0x08
         bne     TestArus_BBBSErr
         mov     al,0x00
         mov     cl,0x08
         xorsx   el,al,cl
         cmp     el,0x08
         bne     TestArus_BBBSErr
         mov     bl,0x00
         mov     dl,0x08
         mulsx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x00
         mov     el,0x08
         sdivsx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x00
         mov     fl,0x08
         sremsx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x00
         mov     gl,0x09
         addsx   bh,el,gl
         cmp     bh,0x09
         bne     TestArus_BBBSErr
         mov     fl,0x00
         mov     ah,0x09
         subsx   ch,fl,ah
         cmp     ch,0xF7
         bne     TestArus_BBBSErr
         mov     gl,0x00
         mov     bh,0x09
         andsx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x00
         mov     ch,0x09
         orsx    eh,ah,ch
         cmp     eh,0x09
         bne     TestArus_BBBSErr
         mov     bh,0x00
         mov     dh,0x09
         xorsx   fh,bh,dh
         cmp     fh,0x09
         bne     TestArus_BBBSErr
         mov     ch,0x00
         mov     eh,0x09
         mulsx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         mov     dh,0x00
         mov     fh,0x09
         sdivsx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x00
         mov     gh,0x09
         sremsx  bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBSErr
         mov     fh,0x00
         mov     al,0x0F
         addsx   cl,fh,al
         cmp     cl,0x0F
         bne     TestArus_BBBSErr
         mov     gh,0x00
         mov     bl,0x0F
         subsx   dl,gh,bl
         cmp     dl,0xF1
         bne     TestArus_BBBSErr
         mov     al,0x00
         mov     cl,0x0F
         andsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x00
         mov     dl,0x0F
         orsx    fl,bl,dl
         cmp     fl,0x0F
         bne     TestArus_BBBSErr
         mov     cl,0x00
         mov     el,0x0F
         xorsx   gl,cl,el
         cmp     gl,0x0F
         bne     TestArus_BBBSErr
         mov     dl,0x00
         mov     fl,0x0F
         mulsx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x00
         mov     gl,0x0F
         sdivsx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x00
         mov     ah,0x0F
         sremsx  ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBSErr
         mov     gl,0x00
         mov     bh,0x7F
         addsx   dh,gl,bh
         cmp     dh,0x7F
         bne     TestArus_BBBSErr
         mov     ah,0x00
         mov     ch,0x7F
         subsx   eh,ah,ch
         cmp     eh,0x81
         bne     TestArus_BBBSErr
         mov     bh,0x00
         mov     dh,0x7F
         andsx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBSErr
         mov     ch,0x00
         mov     eh,0x7F
         orsx    gh,ch,eh
         cmp     gh,0x7F
         bne     TestArus_BBBSErr
         mov     dh,0x00
         mov     fh,0x7F
         xorsx   al,dh,fh
         cmp     al,0x7F
         bne     TestArus_BBBSErr
         mov     eh,0x00
         mov     gh,0x7F
         mulsx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBSErr
         mov     fh,0x00
         mov     al,0x7F
         sdivsx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBSErr
         mov     gh,0x00
         mov     bl,0x7F
         sremsx  dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBSErr
         mov     al,0x00
         mov     cl,0x80
         addsx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBSErr
         mov     bl,0x00
         mov     dl,0x80
         subsx   fl,bl,dl
         cmp     fl,0x80
         bne     TestArus_BBBSErr
         mov     cl,0x00
         mov     el,0x80
         andsx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x00
         mov     fl,0x80
         orsx    ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBSErr
         mov     el,0x00
         mov     gl,0x80
         xorsx   bh,el,gl
         cmp     bh,0x80
         bne     TestArus_BBBSErr
         mov     fl,0x00
         mov     ah,0x80
         mulsx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBSErr
         mov     gl,0x00
         mov     bh,0x80
         sdivsx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x00
         mov     ch,0x80
         sremsx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBSErr
         mov     bh,0x00
         mov     dh,0xFF
         addsx   fh,bh,dh
         cmp     fh,0xFF
         bne     TestArus_BBBSErr
         mov     ch,0x00
         mov     eh,0xFF
         subsx   gh,ch,eh
         cmp     gh,0x01
         bne     TestArus_BBBSErr
         mov     dh,0x00
         mov     fh,0xFF
         andsx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x00
         mov     gh,0xFF
         orsx    bl,eh,gh
         cmp     bl,0xFF
         bne     TestArus_BBBSErr
         mov     fh,0x00
         mov     al,0xFF
         xorsx   cl,fh,al
         cmp     cl,0xFF
         bne     TestArus_BBBSErr
         mov     gh,0x00
         mov     bl,0xFF
         mulsx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBSErr
         mov     al,0x00
         mov     cl,0xFF
         sdivsx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x00
         mov     dl,0xFF
         sremsx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x01
         mov     el,0x01
         addsx   gl,cl,el
         cmp     gl,0x02
         bne     TestArus_BBBSErr
         mov     dl,0x01
         mov     fl,0x01
         subsx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x01
         mov     gl,0x01
         andsx   bh,el,gl
         cmp     bh,0x01
         bne     TestArus_BBBSErr
         mov     fl,0x01
         mov     ah,0x01
         orsx    ch,fl,ah
         cmp     ch,0x01
         bne     TestArus_BBBSErr
         mov     gl,0x01
         mov     bh,0x01
         xorsx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x01
         mov     ch,0x01
         mulsx   eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBSErr
         mov     bh,0x01
         mov     dh,0x01
         sdivsx  fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBSErr
         mov     ch,0x01
         mov     eh,0x01
         sremsx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         mov     dh,0x01
         mov     fh,0x07
         addsx   al,dh,fh
         cmp     al,0x08
         bne     TestArus_BBBSErr
         mov     eh,0x01
         mov     gh,0x07
         subsx   bl,eh,gh
         cmp     bl,0xFA
         bne     TestArus_BBBSErr
         mov     fh,0x01
         mov     al,0x07
         andsx   cl,fh,al
         cmp     cl,0x01
         bne     TestArus_BBBSErr
         mov     gh,0x01
         mov     bl,0x07
         orsx    dl,gh,bl
         cmp     dl,0x07
         bne     TestArus_BBBSErr
         mov     al,0x01
         mov     cl,0x07
         xorsx   el,al,cl
         cmp     el,0x06
         bne     TestArus_BBBSErr
         mov     bl,0x01
         mov     dl,0x07
         mulsx   fl,bl,dl
         cmp     fl,0x07
         bne     TestArus_BBBSErr
         mov     cl,0x01
         mov     el,0x07
         sdivsx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x01
         mov     fl,0x07
         sremsx  ah,dl,fl
         cmp     ah,0x01
         bne     TestArus_BBBSErr
         mov     el,0x01
         mov     gl,0x08
         addsx   bh,el,gl
         cmp     bh,0x09
         bne     TestArus_BBBSErr
         mov     fl,0x01
         mov     ah,0x08
         subsx   ch,fl,ah
         cmp     ch,0xF9
         bne     TestArus_BBBSErr
         mov     gl,0x01
         mov     bh,0x08
         andsx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x01
         mov     ch,0x08
         orsx    eh,ah,ch
         cmp     eh,0x09
         bne     TestArus_BBBSErr
         mov     bh,0x01
         mov     dh,0x08
         xorsx   fh,bh,dh
         cmp     fh,0x09
         bne     TestArus_BBBSErr
         mov     ch,0x01
         mov     eh,0x08
         mulsx   gh,ch,eh
         cmp     gh,0x08
         bne     TestArus_BBBSErr
         mov     dh,0x01
         mov     fh,0x08
         sdivsx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x01
         mov     gh,0x08
         sremsx  bl,eh,gh
         cmp     bl,0x01
         bne     TestArus_BBBSErr
         mov     fh,0x01
         mov     al,0x09
         addsx   cl,fh,al
         cmp     cl,0x0A
         bne     TestArus_BBBSErr
         mov     gh,0x01
         mov     bl,0x09
         subsx   dl,gh,bl
         cmp     dl,0xF8
         bne     TestArus_BBBSErr
         mov     al,0x01
         mov     cl,0x09
         andsx   el,al,cl
         cmp     el,0x01
         bne     TestArus_BBBSErr
         mov     bl,0x01
         mov     dl,0x09
         orsx    fl,bl,dl
         cmp     fl,0x09
         bne     TestArus_BBBSErr
         mov     cl,0x01
         mov     el,0x09
         xorsx   gl,cl,el
         cmp     gl,0x08
         bne     TestArus_BBBSErr
         mov     dl,0x01
         mov     fl,0x09
         mulsx   ah,dl,fl
         cmp     ah,0x09
         bne     TestArus_BBBSErr
         mov     el,0x01
         mov     gl,0x09
         sdivsx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x01
         mov     ah,0x09
         sremsx  ch,fl,ah
         cmp     ch,0x01
         bne     TestArus_BBBSErr
         mov     gl,0x01
         mov     bh,0x0F
         addsx   dh,gl,bh
         cmp     dh,0x10
         bne     TestArus_BBBSErr
         mov     ah,0x01
         mov     ch,0x0F
         subsx   eh,ah,ch
         cmp     eh,0xF2
         bne     TestArus_BBBSErr
         mov     bh,0x01
         mov     dh,0x0F
         andsx   fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBSErr
         mov     ch,0x01
         mov     eh,0x0F
         orsx    gh,ch,eh
         cmp     gh,0x0F
         bne     TestArus_BBBSErr
         mov     dh,0x01
         mov     fh,0x0F
         xorsx   al,dh,fh
         cmp     al,0x0E
         bne     TestArus_BBBSErr
         mov     eh,0x01
         mov     gh,0x0F
         mulsx   bl,eh,gh
         cmp     bl,0x0F
         bne     TestArus_BBBSErr
         mov     fh,0x01
         mov     al,0x0F
         sdivsx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBSErr
         mov     gh,0x01
         mov     bl,0x0F
         sremsx  dl,gh,bl
         cmp     dl,0x01
         bne     TestArus_BBBSErr
         mov     al,0x01
         mov     cl,0x7F
         addsx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBSErr
         mov     bl,0x01
         mov     dl,0x7F
         subsx   fl,bl,dl
         cmp     fl,0x82
         bne     TestArus_BBBSErr
         mov     cl,0x01
         mov     el,0x7F
         andsx   gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBSErr
         mov     dl,0x01
         mov     fl,0x7F
         orsx    ah,dl,fl
         cmp     ah,0x7F
         bne     TestArus_BBBSErr
         mov     el,0x01
         mov     gl,0x7F
         xorsx   bh,el,gl
         cmp     bh,0x7E
         bne     TestArus_BBBSErr
         mov     fl,0x01
         mov     ah,0x7F
         mulsx   ch,fl,ah
         cmp     ch,0x7F
         bne     TestArus_BBBSErr
         mov     gl,0x01
         mov     bh,0x7F
         sdivsx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x01
         mov     ch,0x7F
         sremsx  eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBSErr
         mov     bh,0x01
         mov     dh,0x80
         addsx   fh,bh,dh
         cmp     fh,0x81
         bne     TestArus_BBBSErr
         mov     ch,0x01
         mov     eh,0x80
         subsx   gh,ch,eh
         cmp     gh,0x81
         bne     TestArus_BBBSErr
         mov     dh,0x01
         mov     fh,0x80
         andsx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x01
         mov     gh,0x80
         orsx    bl,eh,gh
         cmp     bl,0x81
         bne     TestArus_BBBSErr
         mov     fh,0x01
         mov     al,0x80
         xorsx   cl,fh,al
         cmp     cl,0x81
         bne     TestArus_BBBSErr
         mov     gh,0x01
         mov     bl,0x80
         mulsx   dl,gh,bl
         cmp     dl,0x80
         bne     TestArus_BBBSErr
         mov     al,0x01
         mov     cl,0x80
         sdivsx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x01
         mov     dl,0x80
         sremsx  fl,bl,dl
         cmp     fl,0x01
         bne     TestArus_BBBSErr
         mov     cl,0x01
         mov     el,0xFF
         addsx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x01
         mov     fl,0xFF
         subsx   ah,dl,fl
         cmp     ah,0x02
         bne     TestArus_BBBSErr
         mov     el,0x01
         mov     gl,0xFF
         andsx   bh,el,gl
         cmp     bh,0x01
         bne     TestArus_BBBSErr
         mov     fl,0x01
         mov     ah,0xFF
         orsx    ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBSErr
         mov     gl,0x01
         mov     bh,0xFF
         xorsx   dh,gl,bh
         cmp     dh,0xFE
         bne     TestArus_BBBSErr
         mov     ah,0x01
         mov     ch,0xFF
         mulsx   eh,ah,ch
         cmp     eh,0xFF
         bne     TestArus_BBBSErr
         mov     bh,0x01
         mov     dh,0xFF
         sdivsx  fh,bh,dh
         cmp     fh,0xFF
         bne     TestArus_BBBSErr
         mov     ch,0x01
         mov     eh,0xFF
         sremsx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         mov     dh,0x07
         mov     fh,0x07
         addsx   al,dh,fh
         cmp     al,0x0E
         bne     TestArus_BBBSErr
         mov     eh,0x07
         mov     gh,0x07
         subsx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBSErr
         mov     fh,0x07
         mov     al,0x07
         andsx   cl,fh,al
         cmp     cl,0x07
         bne     TestArus_BBBSErr
         mov     gh,0x07
         mov     bl,0x07
         orsx    dl,gh,bl
         cmp     dl,0x07
         bne     TestArus_BBBSErr
         mov     al,0x07
         mov     cl,0x07
         xorsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x07
         mov     dl,0x07
         mulsx   fl,bl,dl
         cmp     fl,0x31
         bne     TestArus_BBBSErr
         mov     cl,0x07
         mov     el,0x07
         sdivsx  gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBSErr
         mov     dl,0x07
         mov     fl,0x07
         sremsx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x07
         mov     gl,0x08
         addsx   bh,el,gl
         cmp     bh,0x0F
         bne     TestArus_BBBSErr
         mov     fl,0x07
         mov     ah,0x08
         subsx   ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBSErr
         mov     gl,0x07
         mov     bh,0x08
         andsx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x07
         mov     ch,0x08
         orsx    eh,ah,ch
         cmp     eh,0x0F
         bne     TestArus_BBBSErr
         mov     bh,0x07
         mov     dh,0x08
         xorsx   fh,bh,dh
         cmp     fh,0x0F
         bne     TestArus_BBBSErr
         mov     ch,0x07
         mov     eh,0x08
         mulsx   gh,ch,eh
         cmp     gh,0x38
         bne     TestArus_BBBSErr
         mov     dh,0x07
         mov     fh,0x08
         sdivsx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x07
         mov     gh,0x08
         sremsx  bl,eh,gh
         cmp     bl,0x07
         bne     TestArus_BBBSErr
         mov     fh,0x07
         mov     al,0x09
         addsx   cl,fh,al
         cmp     cl,0x10
         bne     TestArus_BBBSErr
         mov     gh,0x07
         mov     bl,0x09
         subsx   dl,gh,bl
         cmp     dl,0xFE
         bne     TestArus_BBBSErr
         mov     al,0x07
         mov     cl,0x09
         andsx   el,al,cl
         cmp     el,0x01
         bne     TestArus_BBBSErr
         mov     bl,0x07
         mov     dl,0x09
         orsx    fl,bl,dl
         cmp     fl,0x0F
         bne     TestArus_BBBSErr
         mov     cl,0x07
         mov     el,0x09
         xorsx   gl,cl,el
         cmp     gl,0x0E
         bne     TestArus_BBBSErr
         mov     dl,0x07
         mov     fl,0x09
         mulsx   ah,dl,fl
         cmp     ah,0x3F
         bne     TestArus_BBBSErr
         mov     el,0x07
         mov     gl,0x09
         sdivsx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x07
         mov     ah,0x09
         sremsx  ch,fl,ah
         cmp     ch,0x07
         bne     TestArus_BBBSErr
         mov     gl,0x07
         mov     bh,0x0F
         addsx   dh,gl,bh
         cmp     dh,0x16
         bne     TestArus_BBBSErr
         mov     ah,0x07
         mov     ch,0x0F
         subsx   eh,ah,ch
         cmp     eh,0xF8
         bne     TestArus_BBBSErr
         mov     bh,0x07
         mov     dh,0x0F
         andsx   fh,bh,dh
         cmp     fh,0x07
         bne     TestArus_BBBSErr
         mov     ch,0x07
         mov     eh,0x0F
         orsx    gh,ch,eh
         cmp     gh,0x0F
         bne     TestArus_BBBSErr
         mov     dh,0x07
         mov     fh,0x0F
         xorsx   al,dh,fh
         cmp     al,0x08
         bne     TestArus_BBBSErr
         mov     eh,0x07
         mov     gh,0x0F
         mulsx   bl,eh,gh
         cmp     bl,0x69
         bne     TestArus_BBBSErr
         mov     fh,0x07
         mov     al,0x0F
         sdivsx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBSErr
         mov     gh,0x07
         mov     bl,0x0F
         sremsx  dl,gh,bl
         cmp     dl,0x07
         bne     TestArus_BBBSErr
         mov     al,0x07
         mov     cl,0x7F
         addsx   el,al,cl
         cmp     el,0x86
         bne     TestArus_BBBSErr
         mov     bl,0x07
         mov     dl,0x7F
         subsx   fl,bl,dl
         cmp     fl,0x88
         bne     TestArus_BBBSErr
         mov     cl,0x07
         mov     el,0x7F
         andsx   gl,cl,el
         cmp     gl,0x07
         bne     TestArus_BBBSErr
         mov     dl,0x07
         mov     fl,0x7F
         orsx    ah,dl,fl
         cmp     ah,0x7F
         bne     TestArus_BBBSErr
         mov     el,0x07
         mov     gl,0x7F
         xorsx   bh,el,gl
         cmp     bh,0x78
         bne     TestArus_BBBSErr
         mov     fl,0x07
         mov     ah,0x7F
         mulsx   ch,fl,ah
         cmp     ch,0x79
         bne     TestArus_BBBSErr
         mov     gl,0x07
         mov     bh,0x7F
         sdivsx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x07
         mov     ch,0x7F
         sremsx  eh,ah,ch
         cmp     eh,0x07
         bne     TestArus_BBBSErr
         mov     bh,0x07
         mov     dh,0x80
         addsx   fh,bh,dh
         cmp     fh,0x87
         bne     TestArus_BBBSErr
         mov     ch,0x07
         mov     eh,0x80
         subsx   gh,ch,eh
         cmp     gh,0x87
         bne     TestArus_BBBSErr
         mov     dh,0x07
         mov     fh,0x80
         andsx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x07
         mov     gh,0x80
         orsx    bl,eh,gh
         cmp     bl,0x87
         bne     TestArus_BBBSErr
         mov     fh,0x07
         mov     al,0x80
         xorsx   cl,fh,al
         cmp     cl,0x87
         bne     TestArus_BBBSErr
         mov     gh,0x07
         mov     bl,0x80
         mulsx   dl,gh,bl
         cmp     dl,0x80
         bne     TestArus_BBBSErr
         mov     al,0x07
         mov     cl,0x80
         sdivsx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x07
         mov     dl,0x80
         sremsx  fl,bl,dl
         cmp     fl,0x07
         bne     TestArus_BBBSErr
         mov     cl,0x07
         mov     el,0xFF
         addsx   gl,cl,el
         cmp     gl,0x06
         bne     TestArus_BBBSErr
         mov     dl,0x07
         mov     fl,0xFF
         subsx   ah,dl,fl
         cmp     ah,0x08
         bne     TestArus_BBBSErr
         mov     el,0x07
         mov     gl,0xFF
         andsx   bh,el,gl
         cmp     bh,0x07
         bne     TestArus_BBBSErr
         mov     fl,0x07
         mov     ah,0xFF
         orsx    ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBSErr
         mov     gl,0x07
         mov     bh,0xFF
         xorsx   dh,gl,bh
         cmp     dh,0xF8
         bne     TestArus_BBBSErr
         mov     ah,0x07
         mov     ch,0xFF
         mulsx   eh,ah,ch
         cmp     eh,0xF9
         bne     TestArus_BBBSErr
         mov     bh,0x07
         mov     dh,0xFF
         sdivsx  fh,bh,dh
         cmp     fh,0xF9
         bne     TestArus_BBBSErr
         mov     ch,0x07
         mov     eh,0xFF
         sremsx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         mov     dh,0x08
         mov     fh,0x08
         addsx   al,dh,fh
         cmp     al,0x10
         bne     TestArus_BBBSErr
         mov     eh,0x08
         mov     gh,0x08
         subsx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBSErr
         mov     fh,0x08
         mov     al,0x08
         andsx   cl,fh,al
         cmp     cl,0x08
         bne     TestArus_BBBSErr
         mov     gh,0x08
         mov     bl,0x08
         orsx    dl,gh,bl
         cmp     dl,0x08
         bne     TestArus_BBBSErr
         mov     al,0x08
         mov     cl,0x08
         xorsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x08
         mov     dl,0x08
         mulsx   fl,bl,dl
         cmp     fl,0x40
         bne     TestArus_BBBSErr
         mov     cl,0x08
         mov     el,0x08
         sdivsx  gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBSErr
         mov     dl,0x08
         mov     fl,0x08
         sremsx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x08
         mov     gl,0x09
         addsx   bh,el,gl
         cmp     bh,0x11
         bne     TestArus_BBBSErr
         mov     fl,0x08
         mov     ah,0x09
         subsx   ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBSErr
         mov     gl,0x08
         mov     bh,0x09
         andsx   dh,gl,bh
         cmp     dh,0x08
         bne     TestArus_BBBSErr
         mov     ah,0x08
         mov     ch,0x09
         orsx    eh,ah,ch
         cmp     eh,0x09
         bne     TestArus_BBBSErr
         mov     bh,0x08
         mov     dh,0x09
         xorsx   fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBSErr
         mov     ch,0x08
         mov     eh,0x09
         mulsx   gh,ch,eh
         cmp     gh,0x48
         bne     TestArus_BBBSErr
         mov     dh,0x08
         mov     fh,0x09
         sdivsx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x08
         mov     gh,0x09
         sremsx  bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBSErr
         mov     fh,0x08
         mov     al,0x0F
         addsx   cl,fh,al
         cmp     cl,0x17
         bne     TestArus_BBBSErr
         mov     gh,0x08
         mov     bl,0x0F
         subsx   dl,gh,bl
         cmp     dl,0xF9
         bne     TestArus_BBBSErr
         mov     al,0x08
         mov     cl,0x0F
         andsx   el,al,cl
         cmp     el,0x08
         bne     TestArus_BBBSErr
         mov     bl,0x08
         mov     dl,0x0F
         orsx    fl,bl,dl
         cmp     fl,0x0F
         bne     TestArus_BBBSErr
         mov     cl,0x08
         mov     el,0x0F
         xorsx   gl,cl,el
         cmp     gl,0x07
         bne     TestArus_BBBSErr
         mov     dl,0x08
         mov     fl,0x0F
         mulsx   ah,dl,fl
         cmp     ah,0x78
         bne     TestArus_BBBSErr
         mov     el,0x08
         mov     gl,0x0F
         sdivsx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x08
         mov     ah,0x0F
         sremsx  ch,fl,ah
         cmp     ch,0x08
         bne     TestArus_BBBSErr
         mov     gl,0x08
         mov     bh,0x7F
         addsx   dh,gl,bh
         cmp     dh,0x87
         bne     TestArus_BBBSErr
         mov     ah,0x08
         mov     ch,0x7F
         subsx   eh,ah,ch
         cmp     eh,0x89
         bne     TestArus_BBBSErr
         mov     bh,0x08
         mov     dh,0x7F
         andsx   fh,bh,dh
         cmp     fh,0x08
         bne     TestArus_BBBSErr
         mov     ch,0x08
         mov     eh,0x7F
         orsx    gh,ch,eh
         cmp     gh,0x7F
         bne     TestArus_BBBSErr
         mov     dh,0x08
         mov     fh,0x7F
         xorsx   al,dh,fh
         cmp     al,0x77
         bne     TestArus_BBBSErr
         mov     eh,0x08
         mov     gh,0x7F
         mulsx   bl,eh,gh
         cmp     bl,0xF8
         bne     TestArus_BBBSErr
         mov     fh,0x08
         mov     al,0x7F
         sdivsx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBSErr
         mov     gh,0x08
         mov     bl,0x7F
         sremsx  dl,gh,bl
         cmp     dl,0x08
         bne     TestArus_BBBSErr
         mov     al,0x08
         mov     cl,0x80
         addsx   el,al,cl
         cmp     el,0x88
         bne     TestArus_BBBSErr
         mov     bl,0x08
         mov     dl,0x80
         subsx   fl,bl,dl
         cmp     fl,0x88
         bne     TestArus_BBBSErr
         mov     cl,0x08
         mov     el,0x80
         andsx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x08
         mov     fl,0x80
         orsx    ah,dl,fl
         cmp     ah,0x88
         bne     TestArus_BBBSErr
         mov     el,0x08
         mov     gl,0x80
         xorsx   bh,el,gl
         cmp     bh,0x88
         bne     TestArus_BBBSErr
         mov     fl,0x08
         mov     ah,0x80
         mulsx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBSErr
         mov     gl,0x08
         mov     bh,0x80
         sdivsx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x08
         mov     ch,0x80
         sremsx  eh,ah,ch
         cmp     eh,0x08
         bne     TestArus_BBBSErr
         mov     bh,0x08
         mov     dh,0xFF
         addsx   fh,bh,dh
         cmp     fh,0x07
         bne     TestArus_BBBSErr
         mov     ch,0x08
         mov     eh,0xFF
         subsx   gh,ch,eh
         cmp     gh,0x09
         bne     TestArus_BBBSErr
         mov     dh,0x08
         mov     fh,0xFF
         andsx   al,dh,fh
         cmp     al,0x08
         bne     TestArus_BBBSErr
         mov     eh,0x08
         mov     gh,0xFF
         orsx    bl,eh,gh
         cmp     bl,0xFF
         bne     TestArus_BBBSErr
         mov     fh,0x08
         mov     al,0xFF
         xorsx   cl,fh,al
         cmp     cl,0xF7
         bne     TestArus_BBBSErr
         mov     gh,0x08
         mov     bl,0xFF
         mulsx   dl,gh,bl
         cmp     dl,0xF8
         bne     TestArus_BBBSErr
         mov     al,0x08
         mov     cl,0xFF
         sdivsx  el,al,cl
         cmp     el,0xF8
         bne     TestArus_BBBSErr
         mov     bl,0x08
         mov     dl,0xFF
         sremsx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x09
         mov     el,0x09
         addsx   gl,cl,el
         cmp     gl,0x12
         bne     TestArus_BBBSErr
         mov     dl,0x09
         mov     fl,0x09
         subsx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x09
         mov     gl,0x09
         andsx   bh,el,gl
         cmp     bh,0x09
         bne     TestArus_BBBSErr
         mov     fl,0x09
         mov     ah,0x09
         orsx    ch,fl,ah
         cmp     ch,0x09
         bne     TestArus_BBBSErr
         mov     gl,0x09
         mov     bh,0x09
         xorsx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0x09
         mov     ch,0x09
         mulsx   eh,ah,ch
         cmp     eh,0x51
         bne     TestArus_BBBSErr
         mov     bh,0x09
         mov     dh,0x09
         sdivsx  fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBSErr
         mov     ch,0x09
         mov     eh,0x09
         sremsx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         mov     dh,0x09
         mov     fh,0x0F
         addsx   al,dh,fh
         cmp     al,0x18
         bne     TestArus_BBBSErr
         mov     eh,0x09
         mov     gh,0x0F
         subsx   bl,eh,gh
         cmp     bl,0xFA
         bne     TestArus_BBBSErr
         mov     fh,0x09
         mov     al,0x0F
         andsx   cl,fh,al
         cmp     cl,0x09
         bne     TestArus_BBBSErr
         mov     gh,0x09
         mov     bl,0x0F
         orsx    dl,gh,bl
         cmp     dl,0x0F
         bne     TestArus_BBBSErr
         mov     al,0x09
         mov     cl,0x0F
         xorsx   el,al,cl
         cmp     el,0x06
         bne     TestArus_BBBSErr
         mov     bl,0x09
         mov     dl,0x0F
         mulsx   fl,bl,dl
         cmp     fl,0x87
         bne     TestArus_BBBSErr
         mov     cl,0x09
         mov     el,0x0F
         sdivsx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBSErr
         mov     dl,0x09
         mov     fl,0x0F
         sremsx  ah,dl,fl
         cmp     ah,0x09
         bne     TestArus_BBBSErr
         mov     el,0x09
         mov     gl,0x7F
         addsx   bh,el,gl
         cmp     bh,0x88
         bne     TestArus_BBBSErr
         mov     fl,0x09
         mov     ah,0x7F
         subsx   ch,fl,ah
         cmp     ch,0x8A
         bne     TestArus_BBBSErr
         mov     gl,0x09
         mov     bh,0x7F
         andsx   dh,gl,bh
         cmp     dh,0x09
         bne     TestArus_BBBSErr
         mov     ah,0x09
         mov     ch,0x7F
         orsx    eh,ah,ch
         cmp     eh,0x7F
         bne     TestArus_BBBSErr
         mov     bh,0x09
         mov     dh,0x7F
         xorsx   fh,bh,dh
         cmp     fh,0x76
         bne     TestArus_BBBSErr
         mov     ch,0x09
         mov     eh,0x7F
         mulsx   gh,ch,eh
         cmp     gh,0x77
         bne     TestArus_BBBSErr
         mov     dh,0x09
         mov     fh,0x7F
         sdivsx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBSErr
         mov     eh,0x09
         mov     gh,0x7F
         sremsx  bl,eh,gh
         cmp     bl,0x09
         bne     TestArus_BBBSErr
         mov     fh,0x09
         mov     al,0x80
         addsx   cl,fh,al
         cmp     cl,0x89
         bne     TestArus_BBBSErr
         mov     gh,0x09
         mov     bl,0x80
         subsx   dl,gh,bl
         cmp     dl,0x89
         bne     TestArus_BBBSErr
         mov     al,0x09
         mov     cl,0x80
         andsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x09
         mov     dl,0x80
         orsx    fl,bl,dl
         cmp     fl,0x89
         bne     TestArus_BBBSErr
         mov     cl,0x09
         mov     el,0x80
         xorsx   gl,cl,el
         cmp     gl,0x89
         bne     TestArus_BBBSErr
         mov     dl,0x09
         mov     fl,0x80
         mulsx   ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBSErr
         mov     el,0x09
         mov     gl,0x80
         sdivsx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x09
         mov     ah,0x80
         sremsx  ch,fl,ah
         cmp     ch,0x09
         bne     TestArus_BBBSErr
         mov     gl,0x09
         mov     bh,0xFF
         addsx   dh,gl,bh
         cmp     dh,0x08
         bne     TestArus_BBBSErr
         mov     ah,0x09
         mov     ch,0xFF
         subsx   eh,ah,ch
         cmp     eh,0x0A
         bne     TestArus_BBBSErr
         mov     bh,0x09
         mov     dh,0xFF
         andsx   fh,bh,dh
         cmp     fh,0x09
         bne     TestArus_BBBSErr
         mov     ch,0x09
         mov     eh,0xFF
         orsx    gh,ch,eh
         cmp     gh,0xFF
         bne     TestArus_BBBSErr
         mov     dh,0x09
         mov     fh,0xFF
         xorsx   al,dh,fh
         cmp     al,0xF6
         bne     TestArus_BBBSErr
         mov     eh,0x09
         mov     gh,0xFF
         mulsx   bl,eh,gh
         cmp     bl,0xF7
         bne     TestArus_BBBSErr
         mov     fh,0x09
         mov     al,0xFF
         sdivsx  cl,fh,al
         cmp     cl,0xF7
         bne     TestArus_BBBSErr
         mov     gh,0x09
         mov     bl,0xFF
         sremsx  dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBSErr
         mov     al,0x0F
         mov     cl,0x0F
         addsx   el,al,cl
         cmp     el,0x1E
         bne     TestArus_BBBSErr
         mov     bl,0x0F
         mov     dl,0x0F
         subsx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x0F
         mov     el,0x0F
         andsx   gl,cl,el
         cmp     gl,0x0F
         bne     TestArus_BBBSErr
         mov     dl,0x0F
         mov     fl,0x0F
         orsx    ah,dl,fl
         cmp     ah,0x0F
         bne     TestArus_BBBSErr
         mov     el,0x0F
         mov     gl,0x0F
         xorsx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x0F
         mov     ah,0x0F
         mulsx   ch,fl,ah
         cmp     ch,0xE1
         bne     TestArus_BBBSErr
         mov     gl,0x0F
         mov     bh,0x0F
         sdivsx  dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBSErr
         mov     ah,0x0F
         mov     ch,0x0F
         sremsx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBSErr
         mov     bh,0x0F
         mov     dh,0x7F
         addsx   fh,bh,dh
         cmp     fh,0x8E
         bne     TestArus_BBBSErr
         mov     ch,0x0F
         mov     eh,0x7F
         subsx   gh,ch,eh
         cmp     gh,0x90
         bne     TestArus_BBBSErr
         mov     dh,0x0F
         mov     fh,0x7F
         andsx   al,dh,fh
         cmp     al,0x0F
         bne     TestArus_BBBSErr
         mov     eh,0x0F
         mov     gh,0x7F
         orsx    bl,eh,gh
         cmp     bl,0x7F
         bne     TestArus_BBBSErr
         mov     fh,0x0F
         mov     al,0x7F
         xorsx   cl,fh,al
         cmp     cl,0x70
         bne     TestArus_BBBSErr
         mov     gh,0x0F
         mov     bl,0x7F
         mulsx   dl,gh,bl
         cmp     dl,0x71
         bne     TestArus_BBBSErr
         mov     al,0x0F
         mov     cl,0x7F
         sdivsx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x0F
         mov     dl,0x7F
         sremsx  fl,bl,dl
         cmp     fl,0x0F
         bne     TestArus_BBBSErr
         mov     cl,0x0F
         mov     el,0x80
         addsx   gl,cl,el
         cmp     gl,0x8F
         bne     TestArus_BBBSErr
         mov     dl,0x0F
         mov     fl,0x80
         subsx   ah,dl,fl
         cmp     ah,0x8F
         bne     TestArus_BBBSErr
         mov     el,0x0F
         mov     gl,0x80
         andsx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x0F
         mov     ah,0x80
         orsx    ch,fl,ah
         cmp     ch,0x8F
         bne     TestArus_BBBSErr
         mov     gl,0x0F
         mov     bh,0x80
         xorsx   dh,gl,bh
         cmp     dh,0x8F
         bne     TestArus_BBBSErr
         mov     ah,0x0F
         mov     ch,0x80
         mulsx   eh,ah,ch
         cmp     eh,0x80
         bne     TestArus_BBBSErr
         mov     bh,0x0F
         mov     dh,0x80
         sdivsx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBSErr
         mov     ch,0x0F
         mov     eh,0x80
         sremsx  gh,ch,eh
         cmp     gh,0x0F
         bne     TestArus_BBBSErr
         mov     dh,0x0F
         mov     fh,0xFF
         addsx   al,dh,fh
         cmp     al,0x0E
         bne     TestArus_BBBSErr
         mov     eh,0x0F
         mov     gh,0xFF
         subsx   bl,eh,gh
         cmp     bl,0x10
         bne     TestArus_BBBSErr
         mov     fh,0x0F
         mov     al,0xFF
         andsx   cl,fh,al
         cmp     cl,0x0F
         bne     TestArus_BBBSErr
         mov     gh,0x0F
         mov     bl,0xFF
         orsx    dl,gh,bl
         cmp     dl,0xFF
         bne     TestArus_BBBSErr
         mov     al,0x0F
         mov     cl,0xFF
         xorsx   el,al,cl
         cmp     el,0xF0
         bne     TestArus_BBBSErr
         mov     bl,0x0F
         mov     dl,0xFF
         mulsx   fl,bl,dl
         cmp     fl,0xF1
         bne     TestArus_BBBSErr
         mov     cl,0x0F
         mov     el,0xFF
         sdivsx  gl,cl,el
         cmp     gl,0xF1
         bne     TestArus_BBBSErr
         mov     dl,0x0F
         mov     fl,0xFF
         sremsx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0x7F
         mov     gl,0x7F
         addsx   bh,el,gl
         cmp     bh,0xFE
         bne     TestArus_BBBSErr
         mov     fl,0x7F
         mov     ah,0x7F
         subsx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBSErr
         mov     gl,0x7F
         mov     bh,0x7F
         andsx   dh,gl,bh
         cmp     dh,0x7F
         bne     TestArus_BBBSErr
         mov     ah,0x7F
         mov     ch,0x7F
         orsx    eh,ah,ch
         cmp     eh,0x7F
         bne     TestArus_BBBSErr
         mov     bh,0x7F
         mov     dh,0x7F
         xorsx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBSErr
         mov     ch,0x7F
         mov     eh,0x7F
         mulsx   gh,ch,eh
         cmp     gh,0x01
         bne     TestArus_BBBSErr
         mov     dh,0x7F
         mov     fh,0x7F
         sdivsx  al,dh,fh
         cmp     al,0x01
         bne     TestArus_BBBSErr
         mov     eh,0x7F
         mov     gh,0x7F
         sremsx  bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBSErr
         mov     fh,0x7F
         mov     al,0x80
         addsx   cl,fh,al
         cmp     cl,0xFF
         bne     TestArus_BBBSErr
         mov     gh,0x7F
         mov     bl,0x80
         subsx   dl,gh,bl
         cmp     dl,0xFF
         bne     TestArus_BBBSErr
         mov     al,0x7F
         mov     cl,0x80
         andsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x7F
         mov     dl,0x80
         orsx    fl,bl,dl
         cmp     fl,0xFF
         bne     TestArus_BBBSErr
         mov     cl,0x7F
         mov     el,0x80
         xorsx   gl,cl,el
         cmp     gl,0xFF
         bne     TestArus_BBBSErr
         mov     dl,0x7F
         mov     fl,0x80
         mulsx   ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBSErr
         mov     el,0x7F
         mov     gl,0x80
         sdivsx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x7F
         mov     ah,0x80
         sremsx  ch,fl,ah
         cmp     ch,0x7F
         bne     TestArus_BBBSErr
         mov     gl,0x7F
         mov     bh,0xFF
         addsx   dh,gl,bh
         cmp     dh,0x7E
         bne     TestArus_BBBSErr
         mov     ah,0x7F
         mov     ch,0xFF
         subsx   eh,ah,ch
         cmp     eh,0x80
         bne     TestArus_BBBSErr
         mov     bh,0x7F
         mov     dh,0xFF
         andsx   fh,bh,dh
         cmp     fh,0x7F
         bne     TestArus_BBBSErr
         mov     ch,0x7F
         mov     eh,0xFF
         orsx    gh,ch,eh
         cmp     gh,0xFF
         bne     TestArus_BBBSErr
         mov     dh,0x7F
         mov     fh,0xFF
         xorsx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBSErr
         mov     eh,0x7F
         mov     gh,0xFF
         mulsx   bl,eh,gh
         cmp     bl,0x81
         bne     TestArus_BBBSErr
         mov     fh,0x7F
         mov     al,0xFF
         sdivsx  cl,fh,al
         cmp     cl,0x81
         bne     TestArus_BBBSErr
         mov     gh,0x7F
         mov     bl,0xFF
         sremsx  dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBSErr
         mov     al,0x80
         mov     cl,0x80
         addsx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBSErr
         mov     bl,0x80
         mov     dl,0x80
         subsx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0x80
         mov     el,0x80
         andsx   gl,cl,el
         cmp     gl,0x80
         bne     TestArus_BBBSErr
         mov     dl,0x80
         mov     fl,0x80
         orsx    ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBSErr
         mov     el,0x80
         mov     gl,0x80
         xorsx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBSErr
         mov     fl,0x80
         mov     ah,0x80
         mulsx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBSErr
         mov     gl,0x80
         mov     bh,0x80
         sdivsx  dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBSErr
         mov     ah,0x80
         mov     ch,0x80
         sremsx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBSErr
         mov     bh,0x80
         mov     dh,0xFF
         addsx   fh,bh,dh
         cmp     fh,0x7F
         bne     TestArus_BBBSErr
         mov     ch,0x80
         mov     eh,0xFF
         subsx   gh,ch,eh
         cmp     gh,0x81
         bne     TestArus_BBBSErr
         mov     dh,0x80
         mov     fh,0xFF
         andsx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBSErr
         mov     eh,0x80
         mov     gh,0xFF
         orsx    bl,eh,gh
         cmp     bl,0xFF
         bne     TestArus_BBBSErr
         mov     fh,0x80
         mov     al,0xFF
         xorsx   cl,fh,al
         cmp     cl,0x7F
         bne     TestArus_BBBSErr
         mov     gh,0x80
         mov     bl,0xFF
         mulsx   dl,gh,bl
         cmp     dl,0x80
         bne     TestArus_BBBSErr
         mov     al,0x80
         mov     cl,0xFF
         sdivsx  el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBSErr
         mov     bl,0x80
         mov     dl,0xFF
         sremsx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBSErr
         mov     cl,0xFF
         mov     el,0xFF
         addsx   gl,cl,el
         cmp     gl,0xFE
         bne     TestArus_BBBSErr
         mov     dl,0xFF
         mov     fl,0xFF
         subsx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBSErr
         mov     el,0xFF
         mov     gl,0xFF
         andsx   bh,el,gl
         cmp     bh,0xFF
         bne     TestArus_BBBSErr
         mov     fl,0xFF
         mov     ah,0xFF
         orsx    ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBSErr
         mov     gl,0xFF
         mov     bh,0xFF
         xorsx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBSErr
         mov     ah,0xFF
         mov     ch,0xFF
         mulsx   eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBSErr
         mov     bh,0xFF
         mov     dh,0xFF
         sdivsx  fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBSErr
         mov     ch,0xFF
         mov     eh,0xFF
         sremsx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBSErr
         bra     TestArus_BBBSRet
TestArus_BBBSErr:
         nop     
         trap    
         nop     
TestArus_BBBSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
