.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WWBZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WWBZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         mov     cl,0x00
         addzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x00
         subzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x00
         andzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x00
         orzx    aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x00
         xorzx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x00
         mulzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x00
         udivzx  dw,gx,bh
         cmp     dw,0xFFFF
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x00
         uremzx  ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x00
         shlzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x00
         shrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x00
         rolzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x00
         asrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0x01
         addzx   cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0x01
         subzx   dx,gw,bl
         cmp     dx,0xFFFF
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0x01
         andzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x01
         orzx    fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x01
         xorzx   gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x01
         mulzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x01
         udivzx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x01
         uremzx  cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x01
         shlzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x01
         shrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x01
         rolzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x01
         asrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x07
         addzx   ax,dw,fh
         cmp     ax,0x0007
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x07
         subzx   bx,ew,gh
         cmp     bx,0xFFF9
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0x07
         andzx   cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0x07
         orzx    dx,gw,bl
         cmp     dx,0x0007
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0x07
         xorzx   ex,ax,cl
         cmp     ex,0x0007
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x07
         mulzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x07
         udivzx  gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x07
         uremzx  aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x07
         shlzx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x07
         shrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x07
         rolzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x07
         asrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x08
         addzx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x08
         subzx   gw,cw,eh
         cmp     gw,0xFFF8
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x08
         andzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x08
         orzx    bx,ew,gh
         cmp     bx,0x0008
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0x08
         xorzx   cx,fw,al
         cmp     cx,0x0008
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0x08
         mulzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0x08
         udivzx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x08
         uremzx  fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x08
         shlzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x08
         shrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x08
         rolzx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x08
         asrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x09
         addzx   dw,gx,bh
         cmp     dw,0x0009
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x09
         subzx   ew,aw,ch
         cmp     ew,0xFFF7
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x09
         andzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x09
         orzx    gw,cw,eh
         cmp     gw,0x0009
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x09
         xorzx   ax,dw,fh
         cmp     ax,0x0009
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x09
         mulzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0x09
         udivzx  cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0x09
         uremzx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0x09
         shlzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x09
         shrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x09
         rolzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x09
         asrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x0F
         addzx   bw,ex,gl
         cmp     bw,0x000F
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x0F
         subzx   cw,fx,ah
         cmp     cw,0xFFF1
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x0F
         andzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x0F
         orzx    ew,aw,ch
         cmp     ew,0x000F
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x0F
         xorzx   fw,bw,dh
         cmp     fw,0x000F
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x0F
         mulzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x0F
         udivzx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x0F
         uremzx  bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0x0F
         shlzx   cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0x0F
         shrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0x0F
         rolzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x0F
         asrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x7F
         addzx   gx,cx,el
         cmp     gx,0x007F
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x7F
         subzx   aw,dx,fl
         cmp     aw,0xFF81
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x7F
         andzx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x7F
         orzx    cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x7F
         xorzx   dw,gx,bh
         cmp     dw,0x007F
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x7F
         mulzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x7F
         udivzx  fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x7F
         uremzx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x0F
         shlzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x0F
         shrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0x0F
         rolzx   cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0x0F
         asrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0x80
         addzx   ex,ax,cl
         cmp     ex,0x0080
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0x80
         subzx   fx,bx,dl
         cmp     fx,0xFF80
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0x80
         andzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0x80
         orzx    aw,dx,fl
         cmp     aw,0x0080
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0x80
         xorzx   bw,ex,gl
         cmp     bw,0x0080
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0x80
         mulzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x80
         udivzx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x80
         uremzx  ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x00
         shlzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x00
         shrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0000
         mov     fh,0x00
         rolzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0000
         mov     gh,0x00
         asrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0000
         mov     al,0xFF
         addzx   cx,fw,al
         cmp     cx,0x00FF
         bne     TestArus_WWBZErr
         mov     gw,0x0000
         mov     bl,0xFF
         subzx   dx,gw,bl
         cmp     dx,0xFF01
         bne     TestArus_WWBZErr
         mov     ax,0x0000
         mov     cl,0xFF
         andzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0000
         mov     dl,0xFF
         orzx    fx,bx,dl
         cmp     fx,0x00FF
         bne     TestArus_WWBZErr
         mov     cx,0x0000
         mov     el,0xFF
         xorzx   gx,cx,el
         cmp     gx,0x00FF
         bne     TestArus_WWBZErr
         mov     dx,0x0000
         mov     fl,0xFF
         mulzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0000
         mov     gl,0xFF
         udivzx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0000
         mov     ah,0xFF
         uremzx  cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0000
         mov     bh,0x0F
         shlzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0000
         mov     ch,0x0F
         shrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0000
         mov     dh,0x0F
         rolzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0000
         mov     eh,0x0F
         asrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0x01
         addzx   ax,dw,fh
         cmp     ax,0x0002
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0x01
         subzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0x01
         andzx   cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0x01
         orzx    dx,gw,bl
         cmp     dx,0x0001
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0x01
         xorzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0x01
         mulzx   fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0x01
         udivzx  gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0x01
         uremzx  aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x01
         shlzx   bw,ex,gl
         cmp     bw,0x0002
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x01
         shrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x01
         rolzx   dw,gx,bh
         cmp     dw,0x0002
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x01
         asrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0001
         mov     dh,0x07
         addzx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBZErr
         mov     cw,0x0001
         mov     eh,0x07
         subzx   gw,cw,eh
         cmp     gw,0xFFFA
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0x07
         andzx   ax,dw,fh
         cmp     ax,0x0001
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0x07
         orzx    bx,ew,gh
         cmp     bx,0x0007
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0x07
         xorzx   cx,fw,al
         cmp     cx,0x0006
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0x07
         mulzx   dx,gw,bl
         cmp     dx,0x0007
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0x07
         udivzx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0x07
         uremzx  fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0x07
         shlzx   gx,cx,el
         cmp     gx,0x0080
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0x07
         shrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x07
         rolzx   bw,ex,gl
         cmp     bw,0x0080
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x07
         asrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x08
         addzx   dw,gx,bh
         cmp     dw,0x0009
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x08
         subzx   ew,aw,ch
         cmp     ew,0xFFF9
         bne     TestArus_WWBZErr
         mov     bw,0x0001
         mov     dh,0x08
         andzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0001
         mov     eh,0x08
         orzx    gw,cw,eh
         cmp     gw,0x0009
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0x08
         xorzx   ax,dw,fh
         cmp     ax,0x0009
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0x08
         mulzx   bx,ew,gh
         cmp     bx,0x0008
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0x08
         udivzx  cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0x08
         uremzx  dx,gw,bl
         cmp     dx,0x0001
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0x08
         shlzx   ex,ax,cl
         cmp     ex,0x0100
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0x08
         shrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0x08
         rolzx   gx,cx,el
         cmp     gx,0x0100
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0x08
         asrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x09
         addzx   bw,ex,gl
         cmp     bw,0x000A
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x09
         subzx   cw,fx,ah
         cmp     cw,0xFFF8
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x09
         andzx   dw,gx,bh
         cmp     dw,0x0001
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x09
         orzx    ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBZErr
         mov     bw,0x0001
         mov     dh,0x09
         xorzx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBZErr
         mov     cw,0x0001
         mov     eh,0x09
         mulzx   gw,cw,eh
         cmp     gw,0x0009
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0x09
         udivzx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0x09
         uremzx  bx,ew,gh
         cmp     bx,0x0001
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0x09
         shlzx   cx,fw,al
         cmp     cx,0x0200
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0x09
         shrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0x09
         rolzx   ex,ax,cl
         cmp     ex,0x0200
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0x09
         asrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0x0F
         addzx   gx,cx,el
         cmp     gx,0x0010
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0x0F
         subzx   aw,dx,fl
         cmp     aw,0xFFF2
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x0F
         andzx   bw,ex,gl
         cmp     bw,0x0001
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x0F
         orzx    cw,fx,ah
         cmp     cw,0x000F
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x0F
         xorzx   dw,gx,bh
         cmp     dw,0x000E
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x0F
         mulzx   ew,aw,ch
         cmp     ew,0x000F
         bne     TestArus_WWBZErr
         mov     bw,0x0001
         mov     dh,0x0F
         udivzx  fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0001
         mov     eh,0x0F
         uremzx  gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0x0F
         shlzx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0x0F
         shrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0x0F
         rolzx   cx,fw,al
         cmp     cx,0x8000
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0x0F
         asrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0x7F
         addzx   ex,ax,cl
         cmp     ex,0x0080
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0x7F
         subzx   fx,bx,dl
         cmp     fx,0xFF82
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0x7F
         andzx   gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0x7F
         orzx    aw,dx,fl
         cmp     aw,0x007F
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x7F
         xorzx   bw,ex,gl
         cmp     bw,0x007E
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x7F
         mulzx   cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x7F
         udivzx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x7F
         uremzx  ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBZErr
         mov     bw,0x0001
         mov     dh,0x0F
         shlzx   fw,bw,dh
         cmp     fw,0x8000
         bne     TestArus_WWBZErr
         mov     cw,0x0001
         mov     eh,0x0F
         shrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0x0F
         rolzx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0x0F
         asrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0x80
         addzx   cx,fw,al
         cmp     cx,0x0081
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0x80
         subzx   dx,gw,bl
         cmp     dx,0xFF81
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0x80
         andzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0x80
         orzx    fx,bx,dl
         cmp     fx,0x0081
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0x80
         xorzx   gx,cx,el
         cmp     gx,0x0081
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0x80
         mulzx   aw,dx,fl
         cmp     aw,0x0080
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x80
         udivzx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x80
         uremzx  cw,fx,ah
         cmp     cw,0x0001
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x00
         shlzx   dw,gx,bh
         cmp     dw,0x0001
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x00
         shrzx   ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBZErr
         mov     bw,0x0001
         mov     dh,0x00
         rolzx   fw,bw,dh
         cmp     fw,0x0001
         bne     TestArus_WWBZErr
         mov     cw,0x0001
         mov     eh,0x00
         asrzx   gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBZErr
         mov     dw,0x0001
         mov     fh,0xFF
         addzx   ax,dw,fh
         cmp     ax,0x0100
         bne     TestArus_WWBZErr
         mov     ew,0x0001
         mov     gh,0xFF
         subzx   bx,ew,gh
         cmp     bx,0xFF02
         bne     TestArus_WWBZErr
         mov     fw,0x0001
         mov     al,0xFF
         andzx   cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x0001
         mov     bl,0xFF
         orzx    dx,gw,bl
         cmp     dx,0x00FF
         bne     TestArus_WWBZErr
         mov     ax,0x0001
         mov     cl,0xFF
         xorzx   ex,ax,cl
         cmp     ex,0x00FE
         bne     TestArus_WWBZErr
         mov     bx,0x0001
         mov     dl,0xFF
         mulzx   fx,bx,dl
         cmp     fx,0x00FF
         bne     TestArus_WWBZErr
         mov     cx,0x0001
         mov     el,0xFF
         udivzx  gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0001
         mov     fl,0xFF
         uremzx  aw,dx,fl
         cmp     aw,0x0001
         bne     TestArus_WWBZErr
         mov     ex,0x0001
         mov     gl,0x0F
         shlzx   bw,ex,gl
         cmp     bw,0x8000
         bne     TestArus_WWBZErr
         mov     fx,0x0001
         mov     ah,0x0F
         shrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0001
         mov     bh,0x0F
         rolzx   dw,gx,bh
         cmp     dw,0x8000
         bne     TestArus_WWBZErr
         mov     aw,0x0001
         mov     ch,0x0F
         asrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0008
         mov     dh,0x07
         addzx   fw,bw,dh
         cmp     fw,0x000F
         bne     TestArus_WWBZErr
         mov     cw,0x0008
         mov     eh,0x07
         subzx   gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBZErr
         mov     dw,0x0008
         mov     fh,0x07
         andzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0008
         mov     gh,0x07
         orzx    bx,ew,gh
         cmp     bx,0x000F
         bne     TestArus_WWBZErr
         mov     fw,0x0008
         mov     al,0x07
         xorzx   cx,fw,al
         cmp     cx,0x000F
         bne     TestArus_WWBZErr
         mov     gw,0x0008
         mov     bl,0x07
         mulzx   dx,gw,bl
         cmp     dx,0x0038
         bne     TestArus_WWBZErr
         mov     ax,0x0008
         mov     cl,0x07
         udivzx  ex,ax,cl
         cmp     ex,0x0001
         bne     TestArus_WWBZErr
         mov     bx,0x0008
         mov     dl,0x07
         uremzx  fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBZErr
         mov     cx,0x0008
         mov     el,0x07
         shlzx   gx,cx,el
         cmp     gx,0x0400
         bne     TestArus_WWBZErr
         mov     dx,0x0008
         mov     fl,0x07
         shrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0008
         mov     gl,0x07
         rolzx   bw,ex,gl
         cmp     bw,0x0400
         bne     TestArus_WWBZErr
         mov     fx,0x0008
         mov     ah,0x07
         asrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0008
         mov     bh,0x08
         addzx   dw,gx,bh
         cmp     dw,0x0010
         bne     TestArus_WWBZErr
         mov     aw,0x0008
         mov     ch,0x08
         subzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0008
         mov     dh,0x08
         andzx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBZErr
         mov     cw,0x0008
         mov     eh,0x08
         orzx    gw,cw,eh
         cmp     gw,0x0008
         bne     TestArus_WWBZErr
         mov     dw,0x0008
         mov     fh,0x08
         xorzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0008
         mov     gh,0x08
         mulzx   bx,ew,gh
         cmp     bx,0x0040
         bne     TestArus_WWBZErr
         mov     fw,0x0008
         mov     al,0x08
         udivzx  cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x0008
         mov     bl,0x08
         uremzx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0008
         mov     cl,0x08
         shlzx   ex,ax,cl
         cmp     ex,0x0800
         bne     TestArus_WWBZErr
         mov     bx,0x0008
         mov     dl,0x08
         shrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0008
         mov     el,0x08
         rolzx   gx,cx,el
         cmp     gx,0x0800
         bne     TestArus_WWBZErr
         mov     dx,0x0008
         mov     fl,0x08
         asrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0008
         mov     gl,0x09
         addzx   bw,ex,gl
         cmp     bw,0x0011
         bne     TestArus_WWBZErr
         mov     fx,0x0008
         mov     ah,0x09
         subzx   cw,fx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WWBZErr
         mov     gx,0x0008
         mov     bh,0x09
         andzx   dw,gx,bh
         cmp     dw,0x0008
         bne     TestArus_WWBZErr
         mov     aw,0x0008
         mov     ch,0x09
         orzx    ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBZErr
         mov     bw,0x0008
         mov     dh,0x09
         xorzx   fw,bw,dh
         cmp     fw,0x0001
         bne     TestArus_WWBZErr
         mov     cw,0x0008
         mov     eh,0x09
         mulzx   gw,cw,eh
         cmp     gw,0x0048
         bne     TestArus_WWBZErr
         mov     dw,0x0008
         mov     fh,0x09
         udivzx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0008
         mov     gh,0x09
         uremzx  bx,ew,gh
         cmp     bx,0x0008
         bne     TestArus_WWBZErr
         mov     fw,0x0008
         mov     al,0x09
         shlzx   cx,fw,al
         cmp     cx,0x1000
         bne     TestArus_WWBZErr
         mov     gw,0x0008
         mov     bl,0x09
         shrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0008
         mov     cl,0x09
         rolzx   ex,ax,cl
         cmp     ex,0x1000
         bne     TestArus_WWBZErr
         mov     bx,0x0008
         mov     dl,0x09
         asrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0008
         mov     el,0x0F
         addzx   gx,cx,el
         cmp     gx,0x0017
         bne     TestArus_WWBZErr
         mov     dx,0x0008
         mov     fl,0x0F
         subzx   aw,dx,fl
         cmp     aw,0xFFF9
         bne     TestArus_WWBZErr
         mov     ex,0x0008
         mov     gl,0x0F
         andzx   bw,ex,gl
         cmp     bw,0x0008
         bne     TestArus_WWBZErr
         mov     fx,0x0008
         mov     ah,0x0F
         orzx    cw,fx,ah
         cmp     cw,0x000F
         bne     TestArus_WWBZErr
         mov     gx,0x0008
         mov     bh,0x0F
         xorzx   dw,gx,bh
         cmp     dw,0x0007
         bne     TestArus_WWBZErr
         mov     aw,0x0008
         mov     ch,0x0F
         mulzx   ew,aw,ch
         cmp     ew,0x0078
         bne     TestArus_WWBZErr
         mov     bw,0x0008
         mov     dh,0x0F
         udivzx  fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0008
         mov     eh,0x0F
         uremzx  gw,cw,eh
         cmp     gw,0x0008
         bne     TestArus_WWBZErr
         mov     dw,0x0008
         mov     fh,0x0F
         shlzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0008
         mov     gh,0x0F
         shrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0008
         mov     al,0x0F
         rolzx   cx,fw,al
         cmp     cx,0x0004
         bne     TestArus_WWBZErr
         mov     gw,0x0008
         mov     bl,0x0F
         asrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0008
         mov     cl,0x7F
         addzx   ex,ax,cl
         cmp     ex,0x0087
         bne     TestArus_WWBZErr
         mov     bx,0x0008
         mov     dl,0x7F
         subzx   fx,bx,dl
         cmp     fx,0xFF89
         bne     TestArus_WWBZErr
         mov     cx,0x0008
         mov     el,0x7F
         andzx   gx,cx,el
         cmp     gx,0x0008
         bne     TestArus_WWBZErr
         mov     dx,0x0008
         mov     fl,0x7F
         orzx    aw,dx,fl
         cmp     aw,0x007F
         bne     TestArus_WWBZErr
         mov     ex,0x0008
         mov     gl,0x7F
         xorzx   bw,ex,gl
         cmp     bw,0x0077
         bne     TestArus_WWBZErr
         mov     fx,0x0008
         mov     ah,0x7F
         mulzx   cw,fx,ah
         cmp     cw,0x03F8
         bne     TestArus_WWBZErr
         mov     gx,0x0008
         mov     bh,0x7F
         udivzx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0008
         mov     ch,0x7F
         uremzx  ew,aw,ch
         cmp     ew,0x0008
         bne     TestArus_WWBZErr
         mov     bw,0x0008
         mov     dh,0x0F
         shlzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0008
         mov     eh,0x0F
         shrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0008
         mov     fh,0x0F
         rolzx   ax,dw,fh
         cmp     ax,0x0004
         bne     TestArus_WWBZErr
         mov     ew,0x0008
         mov     gh,0x0F
         asrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0008
         mov     al,0x80
         addzx   cx,fw,al
         cmp     cx,0x0088
         bne     TestArus_WWBZErr
         mov     gw,0x0008
         mov     bl,0x80
         subzx   dx,gw,bl
         cmp     dx,0xFF88
         bne     TestArus_WWBZErr
         mov     ax,0x0008
         mov     cl,0x80
         andzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0008
         mov     dl,0x80
         orzx    fx,bx,dl
         cmp     fx,0x0088
         bne     TestArus_WWBZErr
         mov     cx,0x0008
         mov     el,0x80
         xorzx   gx,cx,el
         cmp     gx,0x0088
         bne     TestArus_WWBZErr
         mov     dx,0x0008
         mov     fl,0x80
         mulzx   aw,dx,fl
         cmp     aw,0x0400
         bne     TestArus_WWBZErr
         mov     ex,0x0008
         mov     gl,0x80
         udivzx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0008
         mov     ah,0x80
         uremzx  cw,fx,ah
         cmp     cw,0x0008
         bne     TestArus_WWBZErr
         mov     gx,0x0008
         mov     bh,0x00
         shlzx   dw,gx,bh
         cmp     dw,0x0008
         bne     TestArus_WWBZErr
         mov     aw,0x0008
         mov     ch,0x00
         shrzx   ew,aw,ch
         cmp     ew,0x0008
         bne     TestArus_WWBZErr
         mov     bw,0x0008
         mov     dh,0x00
         rolzx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBZErr
         mov     cw,0x0008
         mov     eh,0x00
         asrzx   gw,cw,eh
         cmp     gw,0x0008
         bne     TestArus_WWBZErr
         mov     dw,0x0008
         mov     fh,0xFF
         addzx   ax,dw,fh
         cmp     ax,0x0107
         bne     TestArus_WWBZErr
         mov     ew,0x0008
         mov     gh,0xFF
         subzx   bx,ew,gh
         cmp     bx,0xFF09
         bne     TestArus_WWBZErr
         mov     fw,0x0008
         mov     al,0xFF
         andzx   cx,fw,al
         cmp     cx,0x0008
         bne     TestArus_WWBZErr
         mov     gw,0x0008
         mov     bl,0xFF
         orzx    dx,gw,bl
         cmp     dx,0x00FF
         bne     TestArus_WWBZErr
         mov     ax,0x0008
         mov     cl,0xFF
         xorzx   ex,ax,cl
         cmp     ex,0x00F7
         bne     TestArus_WWBZErr
         mov     bx,0x0008
         mov     dl,0xFF
         mulzx   fx,bx,dl
         cmp     fx,0x07F8
         bne     TestArus_WWBZErr
         mov     cx,0x0008
         mov     el,0xFF
         udivzx  gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0008
         mov     fl,0xFF
         uremzx  aw,dx,fl
         cmp     aw,0x0008
         bne     TestArus_WWBZErr
         mov     ex,0x0008
         mov     gl,0x0F
         shlzx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0008
         mov     ah,0x0F
         shrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0008
         mov     bh,0x0F
         rolzx   dw,gx,bh
         cmp     dw,0x0004
         bne     TestArus_WWBZErr
         mov     aw,0x0008
         mov     ch,0x0F
         asrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0009
         mov     dh,0x08
         addzx   fw,bw,dh
         cmp     fw,0x0011
         bne     TestArus_WWBZErr
         mov     cw,0x0009
         mov     eh,0x08
         subzx   gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBZErr
         mov     dw,0x0009
         mov     fh,0x08
         andzx   ax,dw,fh
         cmp     ax,0x0008
         bne     TestArus_WWBZErr
         mov     ew,0x0009
         mov     gh,0x08
         orzx    bx,ew,gh
         cmp     bx,0x0009
         bne     TestArus_WWBZErr
         mov     fw,0x0009
         mov     al,0x08
         xorzx   cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x0009
         mov     bl,0x08
         mulzx   dx,gw,bl
         cmp     dx,0x0048
         bne     TestArus_WWBZErr
         mov     ax,0x0009
         mov     cl,0x08
         udivzx  ex,ax,cl
         cmp     ex,0x0001
         bne     TestArus_WWBZErr
         mov     bx,0x0009
         mov     dl,0x08
         uremzx  fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBZErr
         mov     cx,0x0009
         mov     el,0x08
         shlzx   gx,cx,el
         cmp     gx,0x0900
         bne     TestArus_WWBZErr
         mov     dx,0x0009
         mov     fl,0x08
         shrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0009
         mov     gl,0x08
         rolzx   bw,ex,gl
         cmp     bw,0x0900
         bne     TestArus_WWBZErr
         mov     fx,0x0009
         mov     ah,0x08
         asrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x0009
         mov     bh,0x09
         addzx   dw,gx,bh
         cmp     dw,0x0012
         bne     TestArus_WWBZErr
         mov     aw,0x0009
         mov     ch,0x09
         subzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0009
         mov     dh,0x09
         andzx   fw,bw,dh
         cmp     fw,0x0009
         bne     TestArus_WWBZErr
         mov     cw,0x0009
         mov     eh,0x09
         orzx    gw,cw,eh
         cmp     gw,0x0009
         bne     TestArus_WWBZErr
         mov     dw,0x0009
         mov     fh,0x09
         xorzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0009
         mov     gh,0x09
         mulzx   bx,ew,gh
         cmp     bx,0x0051
         bne     TestArus_WWBZErr
         mov     fw,0x0009
         mov     al,0x09
         udivzx  cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x0009
         mov     bl,0x09
         uremzx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0009
         mov     cl,0x09
         shlzx   ex,ax,cl
         cmp     ex,0x1200
         bne     TestArus_WWBZErr
         mov     bx,0x0009
         mov     dl,0x09
         shrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0009
         mov     el,0x09
         rolzx   gx,cx,el
         cmp     gx,0x1200
         bne     TestArus_WWBZErr
         mov     dx,0x0009
         mov     fl,0x09
         asrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0009
         mov     gl,0x0F
         addzx   bw,ex,gl
         cmp     bw,0x0018
         bne     TestArus_WWBZErr
         mov     fx,0x0009
         mov     ah,0x0F
         subzx   cw,fx,ah
         cmp     cw,0xFFFA
         bne     TestArus_WWBZErr
         mov     gx,0x0009
         mov     bh,0x0F
         andzx   dw,gx,bh
         cmp     dw,0x0009
         bne     TestArus_WWBZErr
         mov     aw,0x0009
         mov     ch,0x0F
         orzx    ew,aw,ch
         cmp     ew,0x000F
         bne     TestArus_WWBZErr
         mov     bw,0x0009
         mov     dh,0x0F
         xorzx   fw,bw,dh
         cmp     fw,0x0006
         bne     TestArus_WWBZErr
         mov     cw,0x0009
         mov     eh,0x0F
         mulzx   gw,cw,eh
         cmp     gw,0x0087
         bne     TestArus_WWBZErr
         mov     dw,0x0009
         mov     fh,0x0F
         udivzx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x0009
         mov     gh,0x0F
         uremzx  bx,ew,gh
         cmp     bx,0x0009
         bne     TestArus_WWBZErr
         mov     fw,0x0009
         mov     al,0x0F
         shlzx   cx,fw,al
         cmp     cx,0x8000
         bne     TestArus_WWBZErr
         mov     gw,0x0009
         mov     bl,0x0F
         shrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0009
         mov     cl,0x0F
         rolzx   ex,ax,cl
         cmp     ex,0x8004
         bne     TestArus_WWBZErr
         mov     bx,0x0009
         mov     dl,0x0F
         asrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x0009
         mov     el,0x7F
         addzx   gx,cx,el
         cmp     gx,0x0088
         bne     TestArus_WWBZErr
         mov     dx,0x0009
         mov     fl,0x7F
         subzx   aw,dx,fl
         cmp     aw,0xFF8A
         bne     TestArus_WWBZErr
         mov     ex,0x0009
         mov     gl,0x7F
         andzx   bw,ex,gl
         cmp     bw,0x0009
         bne     TestArus_WWBZErr
         mov     fx,0x0009
         mov     ah,0x7F
         orzx    cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBZErr
         mov     gx,0x0009
         mov     bh,0x7F
         xorzx   dw,gx,bh
         cmp     dw,0x0076
         bne     TestArus_WWBZErr
         mov     aw,0x0009
         mov     ch,0x7F
         mulzx   ew,aw,ch
         cmp     ew,0x0477
         bne     TestArus_WWBZErr
         mov     bw,0x0009
         mov     dh,0x7F
         udivzx  fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0009
         mov     eh,0x7F
         uremzx  gw,cw,eh
         cmp     gw,0x0009
         bne     TestArus_WWBZErr
         mov     dw,0x0009
         mov     fh,0x0F
         shlzx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBZErr
         mov     ew,0x0009
         mov     gh,0x0F
         shrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0009
         mov     al,0x0F
         rolzx   cx,fw,al
         cmp     cx,0x8004
         bne     TestArus_WWBZErr
         mov     gw,0x0009
         mov     bl,0x0F
         asrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0009
         mov     cl,0x80
         addzx   ex,ax,cl
         cmp     ex,0x0089
         bne     TestArus_WWBZErr
         mov     bx,0x0009
         mov     dl,0x80
         subzx   fx,bx,dl
         cmp     fx,0xFF89
         bne     TestArus_WWBZErr
         mov     cx,0x0009
         mov     el,0x80
         andzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0009
         mov     fl,0x80
         orzx    aw,dx,fl
         cmp     aw,0x0089
         bne     TestArus_WWBZErr
         mov     ex,0x0009
         mov     gl,0x80
         xorzx   bw,ex,gl
         cmp     bw,0x0089
         bne     TestArus_WWBZErr
         mov     fx,0x0009
         mov     ah,0x80
         mulzx   cw,fx,ah
         cmp     cw,0x0480
         bne     TestArus_WWBZErr
         mov     gx,0x0009
         mov     bh,0x80
         udivzx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0009
         mov     ch,0x80
         uremzx  ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBZErr
         mov     bw,0x0009
         mov     dh,0x00
         shlzx   fw,bw,dh
         cmp     fw,0x0009
         bne     TestArus_WWBZErr
         mov     cw,0x0009
         mov     eh,0x00
         shrzx   gw,cw,eh
         cmp     gw,0x0009
         bne     TestArus_WWBZErr
         mov     dw,0x0009
         mov     fh,0x00
         rolzx   ax,dw,fh
         cmp     ax,0x0009
         bne     TestArus_WWBZErr
         mov     ew,0x0009
         mov     gh,0x00
         asrzx   bx,ew,gh
         cmp     bx,0x0009
         bne     TestArus_WWBZErr
         mov     fw,0x0009
         mov     al,0xFF
         addzx   cx,fw,al
         cmp     cx,0x0108
         bne     TestArus_WWBZErr
         mov     gw,0x0009
         mov     bl,0xFF
         subzx   dx,gw,bl
         cmp     dx,0xFF0A
         bne     TestArus_WWBZErr
         mov     ax,0x0009
         mov     cl,0xFF
         andzx   ex,ax,cl
         cmp     ex,0x0009
         bne     TestArus_WWBZErr
         mov     bx,0x0009
         mov     dl,0xFF
         orzx    fx,bx,dl
         cmp     fx,0x00FF
         bne     TestArus_WWBZErr
         mov     cx,0x0009
         mov     el,0xFF
         xorzx   gx,cx,el
         cmp     gx,0x00F6
         bne     TestArus_WWBZErr
         mov     dx,0x0009
         mov     fl,0xFF
         mulzx   aw,dx,fl
         cmp     aw,0x08F7
         bne     TestArus_WWBZErr
         mov     ex,0x0009
         mov     gl,0xFF
         udivzx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBZErr
         mov     fx,0x0009
         mov     ah,0xFF
         uremzx  cw,fx,ah
         cmp     cw,0x0009
         bne     TestArus_WWBZErr
         mov     gx,0x0009
         mov     bh,0x0F
         shlzx   dw,gx,bh
         cmp     dw,0x8000
         bne     TestArus_WWBZErr
         mov     aw,0x0009
         mov     ch,0x0F
         shrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0009
         mov     dh,0x0F
         rolzx   fw,bw,dh
         cmp     fw,0x8004
         bne     TestArus_WWBZErr
         mov     cw,0x0009
         mov     eh,0x0F
         asrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x007F
         mov     fh,0x09
         addzx   ax,dw,fh
         cmp     ax,0x0088
         bne     TestArus_WWBZErr
         mov     ew,0x007F
         mov     gh,0x09
         subzx   bx,ew,gh
         cmp     bx,0x0076
         bne     TestArus_WWBZErr
         mov     fw,0x007F
         mov     al,0x09
         andzx   cx,fw,al
         cmp     cx,0x0009
         bne     TestArus_WWBZErr
         mov     gw,0x007F
         mov     bl,0x09
         orzx    dx,gw,bl
         cmp     dx,0x007F
         bne     TestArus_WWBZErr
         mov     ax,0x007F
         mov     cl,0x09
         xorzx   ex,ax,cl
         cmp     ex,0x0076
         bne     TestArus_WWBZErr
         mov     bx,0x007F
         mov     dl,0x09
         mulzx   fx,bx,dl
         cmp     fx,0x0477
         bne     TestArus_WWBZErr
         mov     cx,0x007F
         mov     el,0x09
         udivzx  gx,cx,el
         cmp     gx,0x000E
         bne     TestArus_WWBZErr
         mov     dx,0x007F
         mov     fl,0x09
         uremzx  aw,dx,fl
         cmp     aw,0x0001
         bne     TestArus_WWBZErr
         mov     ex,0x007F
         mov     gl,0x09
         shlzx   bw,ex,gl
         cmp     bw,0xFE00
         bne     TestArus_WWBZErr
         mov     fx,0x007F
         mov     ah,0x09
         shrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x007F
         mov     bh,0x09
         rolzx   dw,gx,bh
         cmp     dw,0xFE00
         bne     TestArus_WWBZErr
         mov     aw,0x007F
         mov     ch,0x09
         asrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x007F
         mov     dh,0x0F
         addzx   fw,bw,dh
         cmp     fw,0x008E
         bne     TestArus_WWBZErr
         mov     cw,0x007F
         mov     eh,0x0F
         subzx   gw,cw,eh
         cmp     gw,0x0070
         bne     TestArus_WWBZErr
         mov     dw,0x007F
         mov     fh,0x0F
         andzx   ax,dw,fh
         cmp     ax,0x000F
         bne     TestArus_WWBZErr
         mov     ew,0x007F
         mov     gh,0x0F
         orzx    bx,ew,gh
         cmp     bx,0x007F
         bne     TestArus_WWBZErr
         mov     fw,0x007F
         mov     al,0x0F
         xorzx   cx,fw,al
         cmp     cx,0x0070
         bne     TestArus_WWBZErr
         mov     gw,0x007F
         mov     bl,0x0F
         mulzx   dx,gw,bl
         cmp     dx,0x0771
         bne     TestArus_WWBZErr
         mov     ax,0x007F
         mov     cl,0x0F
         udivzx  ex,ax,cl
         cmp     ex,0x0008
         bne     TestArus_WWBZErr
         mov     bx,0x007F
         mov     dl,0x0F
         uremzx  fx,bx,dl
         cmp     fx,0x0007
         bne     TestArus_WWBZErr
         mov     cx,0x007F
         mov     el,0x0F
         shlzx   gx,cx,el
         cmp     gx,0x8000
         bne     TestArus_WWBZErr
         mov     dx,0x007F
         mov     fl,0x0F
         shrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x007F
         mov     gl,0x0F
         rolzx   bw,ex,gl
         cmp     bw,0x803F
         bne     TestArus_WWBZErr
         mov     fx,0x007F
         mov     ah,0x0F
         asrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x007F
         mov     bh,0x7F
         addzx   dw,gx,bh
         cmp     dw,0x00FE
         bne     TestArus_WWBZErr
         mov     aw,0x007F
         mov     ch,0x7F
         subzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x007F
         mov     dh,0x7F
         andzx   fw,bw,dh
         cmp     fw,0x007F
         bne     TestArus_WWBZErr
         mov     cw,0x007F
         mov     eh,0x7F
         orzx    gw,cw,eh
         cmp     gw,0x007F
         bne     TestArus_WWBZErr
         mov     dw,0x007F
         mov     fh,0x7F
         xorzx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x007F
         mov     gh,0x7F
         mulzx   bx,ew,gh
         cmp     bx,0x3F01
         bne     TestArus_WWBZErr
         mov     fw,0x007F
         mov     al,0x7F
         udivzx  cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBZErr
         mov     gw,0x007F
         mov     bl,0x7F
         uremzx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x007F
         mov     cl,0x0F
         shlzx   ex,ax,cl
         cmp     ex,0x8000
         bne     TestArus_WWBZErr
         mov     bx,0x007F
         mov     dl,0x0F
         shrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x007F
         mov     el,0x0F
         rolzx   gx,cx,el
         cmp     gx,0x803F
         bne     TestArus_WWBZErr
         mov     dx,0x007F
         mov     fl,0x0F
         asrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x007F
         mov     gl,0x80
         addzx   bw,ex,gl
         cmp     bw,0x00FF
         bne     TestArus_WWBZErr
         mov     fx,0x007F
         mov     ah,0x80
         subzx   cw,fx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WWBZErr
         mov     gx,0x007F
         mov     bh,0x80
         andzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x007F
         mov     ch,0x80
         orzx    ew,aw,ch
         cmp     ew,0x00FF
         bne     TestArus_WWBZErr
         mov     bw,0x007F
         mov     dh,0x80
         xorzx   fw,bw,dh
         cmp     fw,0x00FF
         bne     TestArus_WWBZErr
         mov     cw,0x007F
         mov     eh,0x80
         mulzx   gw,cw,eh
         cmp     gw,0x3F80
         bne     TestArus_WWBZErr
         mov     dw,0x007F
         mov     fh,0x80
         udivzx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBZErr
         mov     ew,0x007F
         mov     gh,0x80
         uremzx  bx,ew,gh
         cmp     bx,0x007F
         bne     TestArus_WWBZErr
         mov     fw,0x007F
         mov     al,0x00
         shlzx   cx,fw,al
         cmp     cx,0x007F
         bne     TestArus_WWBZErr
         mov     gw,0x007F
         mov     bl,0x00
         shrzx   dx,gw,bl
         cmp     dx,0x007F
         bne     TestArus_WWBZErr
         mov     ax,0x007F
         mov     cl,0x00
         rolzx   ex,ax,cl
         cmp     ex,0x007F
         bne     TestArus_WWBZErr
         mov     bx,0x007F
         mov     dl,0x00
         asrzx   fx,bx,dl
         cmp     fx,0x007F
         bne     TestArus_WWBZErr
         mov     cx,0x007F
         mov     el,0xFF
         addzx   gx,cx,el
         cmp     gx,0x017E
         bne     TestArus_WWBZErr
         mov     dx,0x007F
         mov     fl,0xFF
         subzx   aw,dx,fl
         cmp     aw,0xFF80
         bne     TestArus_WWBZErr
         mov     ex,0x007F
         mov     gl,0xFF
         andzx   bw,ex,gl
         cmp     bw,0x007F
         bne     TestArus_WWBZErr
         mov     fx,0x007F
         mov     ah,0xFF
         orzx    cw,fx,ah
         cmp     cw,0x00FF
         bne     TestArus_WWBZErr
         mov     gx,0x007F
         mov     bh,0xFF
         xorzx   dw,gx,bh
         cmp     dw,0x0080
         bne     TestArus_WWBZErr
         mov     aw,0x007F
         mov     ch,0xFF
         mulzx   ew,aw,ch
         cmp     ew,0x7E81
         bne     TestArus_WWBZErr
         mov     bw,0x007F
         mov     dh,0xFF
         udivzx  fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x007F
         mov     eh,0xFF
         uremzx  gw,cw,eh
         cmp     gw,0x007F
         bne     TestArus_WWBZErr
         mov     dw,0x007F
         mov     fh,0x0F
         shlzx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBZErr
         mov     ew,0x007F
         mov     gh,0x0F
         shrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x007F
         mov     al,0x0F
         rolzx   cx,fw,al
         cmp     cx,0x803F
         bne     TestArus_WWBZErr
         mov     gw,0x007F
         mov     bl,0x0F
         asrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x0080
         mov     cl,0x0F
         addzx   ex,ax,cl
         cmp     ex,0x008F
         bne     TestArus_WWBZErr
         mov     bx,0x0080
         mov     dl,0x0F
         subzx   fx,bx,dl
         cmp     fx,0x0071
         bne     TestArus_WWBZErr
         mov     cx,0x0080
         mov     el,0x0F
         andzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0080
         mov     fl,0x0F
         orzx    aw,dx,fl
         cmp     aw,0x008F
         bne     TestArus_WWBZErr
         mov     ex,0x0080
         mov     gl,0x0F
         xorzx   bw,ex,gl
         cmp     bw,0x008F
         bne     TestArus_WWBZErr
         mov     fx,0x0080
         mov     ah,0x0F
         mulzx   cw,fx,ah
         cmp     cw,0x0780
         bne     TestArus_WWBZErr
         mov     gx,0x0080
         mov     bh,0x0F
         udivzx  dw,gx,bh
         cmp     dw,0x0008
         bne     TestArus_WWBZErr
         mov     aw,0x0080
         mov     ch,0x0F
         uremzx  ew,aw,ch
         cmp     ew,0x0008
         bne     TestArus_WWBZErr
         mov     bw,0x0080
         mov     dh,0x0F
         shlzx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBZErr
         mov     cw,0x0080
         mov     eh,0x0F
         shrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0080
         mov     fh,0x0F
         rolzx   ax,dw,fh
         cmp     ax,0x0040
         bne     TestArus_WWBZErr
         mov     ew,0x0080
         mov     gh,0x0F
         asrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0080
         mov     al,0x7F
         addzx   cx,fw,al
         cmp     cx,0x00FF
         bne     TestArus_WWBZErr
         mov     gw,0x0080
         mov     bl,0x7F
         subzx   dx,gw,bl
         cmp     dx,0x0001
         bne     TestArus_WWBZErr
         mov     ax,0x0080
         mov     cl,0x7F
         andzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0080
         mov     dl,0x7F
         orzx    fx,bx,dl
         cmp     fx,0x00FF
         bne     TestArus_WWBZErr
         mov     cx,0x0080
         mov     el,0x7F
         xorzx   gx,cx,el
         cmp     gx,0x00FF
         bne     TestArus_WWBZErr
         mov     dx,0x0080
         mov     fl,0x7F
         mulzx   aw,dx,fl
         cmp     aw,0x3F80
         bne     TestArus_WWBZErr
         mov     ex,0x0080
         mov     gl,0x7F
         udivzx  bw,ex,gl
         cmp     bw,0x0001
         bne     TestArus_WWBZErr
         mov     fx,0x0080
         mov     ah,0x7F
         uremzx  cw,fx,ah
         cmp     cw,0x0001
         bne     TestArus_WWBZErr
         mov     gx,0x0080
         mov     bh,0x0F
         shlzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x0080
         mov     ch,0x0F
         shrzx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x0080
         mov     dh,0x0F
         rolzx   fw,bw,dh
         cmp     fw,0x0040
         bne     TestArus_WWBZErr
         mov     cw,0x0080
         mov     eh,0x0F
         asrzx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBZErr
         mov     dw,0x0080
         mov     fh,0x80
         addzx   ax,dw,fh
         cmp     ax,0x0100
         bne     TestArus_WWBZErr
         mov     ew,0x0080
         mov     gh,0x80
         subzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x0080
         mov     al,0x80
         andzx   cx,fw,al
         cmp     cx,0x0080
         bne     TestArus_WWBZErr
         mov     gw,0x0080
         mov     bl,0x80
         orzx    dx,gw,bl
         cmp     dx,0x0080
         bne     TestArus_WWBZErr
         mov     ax,0x0080
         mov     cl,0x80
         xorzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0080
         mov     dl,0x80
         mulzx   fx,bx,dl
         cmp     fx,0x4000
         bne     TestArus_WWBZErr
         mov     cx,0x0080
         mov     el,0x80
         udivzx  gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBZErr
         mov     dx,0x0080
         mov     fl,0x80
         uremzx  aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0080
         mov     gl,0x00
         shlzx   bw,ex,gl
         cmp     bw,0x0080
         bne     TestArus_WWBZErr
         mov     fx,0x0080
         mov     ah,0x00
         shrzx   cw,fx,ah
         cmp     cw,0x0080
         bne     TestArus_WWBZErr
         mov     gx,0x0080
         mov     bh,0x00
         rolzx   dw,gx,bh
         cmp     dw,0x0080
         bne     TestArus_WWBZErr
         mov     aw,0x0080
         mov     ch,0x00
         asrzx   ew,aw,ch
         cmp     ew,0x0080
         bne     TestArus_WWBZErr
         mov     bw,0x0080
         mov     dh,0xFF
         addzx   fw,bw,dh
         cmp     fw,0x017F
         bne     TestArus_WWBZErr
         mov     cw,0x0080
         mov     eh,0xFF
         subzx   gw,cw,eh
         cmp     gw,0xFF81
         bne     TestArus_WWBZErr
         mov     dw,0x0080
         mov     fh,0xFF
         andzx   ax,dw,fh
         cmp     ax,0x0080
         bne     TestArus_WWBZErr
         mov     ew,0x0080
         mov     gh,0xFF
         orzx    bx,ew,gh
         cmp     bx,0x00FF
         bne     TestArus_WWBZErr
         mov     fw,0x0080
         mov     al,0xFF
         xorzx   cx,fw,al
         cmp     cx,0x007F
         bne     TestArus_WWBZErr
         mov     gw,0x0080
         mov     bl,0xFF
         mulzx   dx,gw,bl
         cmp     dx,0x7F80
         bne     TestArus_WWBZErr
         mov     ax,0x0080
         mov     cl,0xFF
         udivzx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x0080
         mov     dl,0xFF
         uremzx  fx,bx,dl
         cmp     fx,0x0080
         bne     TestArus_WWBZErr
         mov     cx,0x0080
         mov     el,0x0F
         shlzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x0080
         mov     fl,0x0F
         shrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x0080
         mov     gl,0x0F
         rolzx   bw,ex,gl
         cmp     bw,0x0040
         bne     TestArus_WWBZErr
         mov     fx,0x0080
         mov     ah,0x0F
         asrzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x7FFF
         mov     bh,0x7F
         addzx   dw,gx,bh
         cmp     dw,0x807E
         bne     TestArus_WWBZErr
         mov     aw,0x7FFF
         mov     ch,0x7F
         subzx   ew,aw,ch
         cmp     ew,0x7F80
         bne     TestArus_WWBZErr
         mov     bw,0x7FFF
         mov     dh,0x7F
         andzx   fw,bw,dh
         cmp     fw,0x007F
         bne     TestArus_WWBZErr
         mov     cw,0x7FFF
         mov     eh,0x7F
         orzx    gw,cw,eh
         cmp     gw,0x7FFF
         bne     TestArus_WWBZErr
         mov     dw,0x7FFF
         mov     fh,0x7F
         xorzx   ax,dw,fh
         cmp     ax,0x7F80
         bne     TestArus_WWBZErr
         mov     ew,0x7FFF
         mov     gh,0x7F
         mulzx   bx,ew,gh
         cmp     bx,0x7F81
         bne     TestArus_WWBZErr
         mov     fw,0x7FFF
         mov     al,0x7F
         udivzx  cx,fw,al
         cmp     cx,0x0102
         bne     TestArus_WWBZErr
         mov     gw,0x7FFF
         mov     bl,0x7F
         uremzx  dx,gw,bl
         cmp     dx,0x0001
         bne     TestArus_WWBZErr
         mov     ax,0x7FFF
         mov     cl,0x0F
         shlzx   ex,ax,cl
         cmp     ex,0x8000
         bne     TestArus_WWBZErr
         mov     bx,0x7FFF
         mov     dl,0x0F
         shrzx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBZErr
         mov     cx,0x7FFF
         mov     el,0x0F
         rolzx   gx,cx,el
         cmp     gx,0xBFFF
         bne     TestArus_WWBZErr
         mov     dx,0x7FFF
         mov     fl,0x0F
         asrzx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0x7FFF
         mov     gl,0x80
         addzx   bw,ex,gl
         cmp     bw,0x807F
         bne     TestArus_WWBZErr
         mov     fx,0x7FFF
         mov     ah,0x80
         subzx   cw,fx,ah
         cmp     cw,0x7F7F
         bne     TestArus_WWBZErr
         mov     gx,0x7FFF
         mov     bh,0x80
         andzx   dw,gx,bh
         cmp     dw,0x0080
         bne     TestArus_WWBZErr
         mov     aw,0x7FFF
         mov     ch,0x80
         orzx    ew,aw,ch
         cmp     ew,0x7FFF
         bne     TestArus_WWBZErr
         mov     bw,0x7FFF
         mov     dh,0x80
         xorzx   fw,bw,dh
         cmp     fw,0x7F7F
         bne     TestArus_WWBZErr
         mov     cw,0x7FFF
         mov     eh,0x80
         mulzx   gw,cw,eh
         cmp     gw,0xFF80
         bne     TestArus_WWBZErr
         mov     dw,0x7FFF
         mov     fh,0x80
         udivzx  ax,dw,fh
         cmp     ax,0x00FF
         bne     TestArus_WWBZErr
         mov     ew,0x7FFF
         mov     gh,0x80
         uremzx  bx,ew,gh
         cmp     bx,0x007F
         bne     TestArus_WWBZErr
         mov     fw,0x7FFF
         mov     al,0x00
         shlzx   cx,fw,al
         cmp     cx,0x7FFF
         bne     TestArus_WWBZErr
         mov     gw,0x7FFF
         mov     bl,0x00
         shrzx   dx,gw,bl
         cmp     dx,0x7FFF
         bne     TestArus_WWBZErr
         mov     ax,0x7FFF
         mov     cl,0x00
         rolzx   ex,ax,cl
         cmp     ex,0x7FFF
         bne     TestArus_WWBZErr
         mov     bx,0x7FFF
         mov     dl,0x00
         asrzx   fx,bx,dl
         cmp     fx,0x7FFF
         bne     TestArus_WWBZErr
         mov     cx,0x7FFF
         mov     el,0xFF
         addzx   gx,cx,el
         cmp     gx,0x80FE
         bne     TestArus_WWBZErr
         mov     dx,0x7FFF
         mov     fl,0xFF
         subzx   aw,dx,fl
         cmp     aw,0x7F00
         bne     TestArus_WWBZErr
         mov     ex,0x7FFF
         mov     gl,0xFF
         andzx   bw,ex,gl
         cmp     bw,0x00FF
         bne     TestArus_WWBZErr
         mov     fx,0x7FFF
         mov     ah,0xFF
         orzx    cw,fx,ah
         cmp     cw,0x7FFF
         bne     TestArus_WWBZErr
         mov     gx,0x7FFF
         mov     bh,0xFF
         xorzx   dw,gx,bh
         cmp     dw,0x7F00
         bne     TestArus_WWBZErr
         mov     aw,0x7FFF
         mov     ch,0xFF
         mulzx   ew,aw,ch
         cmp     ew,0x7F01
         bne     TestArus_WWBZErr
         mov     bw,0x7FFF
         mov     dh,0xFF
         udivzx  fw,bw,dh
         cmp     fw,0x0080
         bne     TestArus_WWBZErr
         mov     cw,0x7FFF
         mov     eh,0xFF
         uremzx  gw,cw,eh
         cmp     gw,0x007F
         bne     TestArus_WWBZErr
         mov     dw,0x7FFF
         mov     fh,0x0F
         shlzx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBZErr
         mov     ew,0x7FFF
         mov     gh,0x0F
         shrzx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBZErr
         mov     fw,0x7FFF
         mov     al,0x0F
         rolzx   cx,fw,al
         cmp     cx,0xBFFF
         bne     TestArus_WWBZErr
         mov     gw,0x7FFF
         mov     bl,0x0F
         asrzx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBZErr
         mov     ax,0x8000
         mov     cl,0x80
         addzx   ex,ax,cl
         cmp     ex,0x8080
         bne     TestArus_WWBZErr
         mov     bx,0x8000
         mov     dl,0x80
         subzx   fx,bx,dl
         cmp     fx,0x7F80
         bne     TestArus_WWBZErr
         mov     cx,0x8000
         mov     el,0x80
         andzx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBZErr
         mov     dx,0x8000
         mov     fl,0x80
         orzx    aw,dx,fl
         cmp     aw,0x8080
         bne     TestArus_WWBZErr
         mov     ex,0x8000
         mov     gl,0x80
         xorzx   bw,ex,gl
         cmp     bw,0x8080
         bne     TestArus_WWBZErr
         mov     fx,0x8000
         mov     ah,0x80
         mulzx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBZErr
         mov     gx,0x8000
         mov     bh,0x80
         udivzx  dw,gx,bh
         cmp     dw,0x0100
         bne     TestArus_WWBZErr
         mov     aw,0x8000
         mov     ch,0x80
         uremzx  ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBZErr
         mov     bw,0x8000
         mov     dh,0x00
         shlzx   fw,bw,dh
         cmp     fw,0x8000
         bne     TestArus_WWBZErr
         mov     cw,0x8000
         mov     eh,0x00
         shrzx   gw,cw,eh
         cmp     gw,0x8000
         bne     TestArus_WWBZErr
         mov     dw,0x8000
         mov     fh,0x00
         rolzx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBZErr
         mov     ew,0x8000
         mov     gh,0x00
         asrzx   bx,ew,gh
         cmp     bx,0x8000
         bne     TestArus_WWBZErr
         mov     fw,0x8000
         mov     al,0xFF
         addzx   cx,fw,al
         cmp     cx,0x80FF
         bne     TestArus_WWBZErr
         mov     gw,0x8000
         mov     bl,0xFF
         subzx   dx,gw,bl
         cmp     dx,0x7F01
         bne     TestArus_WWBZErr
         mov     ax,0x8000
         mov     cl,0xFF
         andzx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBZErr
         mov     bx,0x8000
         mov     dl,0xFF
         orzx    fx,bx,dl
         cmp     fx,0x80FF
         bne     TestArus_WWBZErr
         mov     cx,0x8000
         mov     el,0xFF
         xorzx   gx,cx,el
         cmp     gx,0x80FF
         bne     TestArus_WWBZErr
         mov     dx,0x8000
         mov     fl,0xFF
         mulzx   aw,dx,fl
         cmp     aw,0x8000
         bne     TestArus_WWBZErr
         mov     ex,0x8000
         mov     gl,0xFF
         udivzx  bw,ex,gl
         cmp     bw,0x0080
         bne     TestArus_WWBZErr
         mov     fx,0x8000
         mov     ah,0xFF
         uremzx  cw,fx,ah
         cmp     cw,0x0080
         bne     TestArus_WWBZErr
         mov     gx,0x8000
         mov     bh,0x0F
         shlzx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBZErr
         mov     aw,0x8000
         mov     ch,0x0F
         shrzx   ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBZErr
         mov     bw,0x8000
         mov     dh,0x0F
         rolzx   fw,bw,dh
         cmp     fw,0x4000
         bne     TestArus_WWBZErr
         mov     cw,0x8000
         mov     eh,0x0F
         asrzx   gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBZErr
         mov     dw,0xFFFF
         mov     fh,0xFF
         addzx   ax,dw,fh
         cmp     ax,0x00FE
         bne     TestArus_WWBZErr
         mov     ew,0xFFFF
         mov     gh,0xFF
         subzx   bx,ew,gh
         cmp     bx,0xFF00
         bne     TestArus_WWBZErr
         mov     fw,0xFFFF
         mov     al,0xFF
         andzx   cx,fw,al
         cmp     cx,0x00FF
         bne     TestArus_WWBZErr
         mov     gw,0xFFFF
         mov     bl,0xFF
         orzx    dx,gw,bl
         cmp     dx,0xFFFF
         bne     TestArus_WWBZErr
         mov     ax,0xFFFF
         mov     cl,0xFF
         xorzx   ex,ax,cl
         cmp     ex,0xFF00
         bne     TestArus_WWBZErr
         mov     bx,0xFFFF
         mov     dl,0xFF
         mulzx   fx,bx,dl
         cmp     fx,0xFF01
         bne     TestArus_WWBZErr
         mov     cx,0xFFFF
         mov     el,0xFF
         udivzx  gx,cx,el
         cmp     gx,0x0101
         bne     TestArus_WWBZErr
         mov     dx,0xFFFF
         mov     fl,0xFF
         uremzx  aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBZErr
         mov     ex,0xFFFF
         mov     gl,0x0F
         shlzx   bw,ex,gl
         cmp     bw,0x8000
         bne     TestArus_WWBZErr
         mov     fx,0xFFFF
         mov     ah,0x0F
         shrzx   cw,fx,ah
         cmp     cw,0x0001
         bne     TestArus_WWBZErr
         mov     gx,0xFFFF
         mov     bh,0x0F
         rolzx   dw,gx,bh
         cmp     dw,0xFFFF
         bne     TestArus_WWBZErr
         mov     aw,0xFFFF
         mov     ch,0x0F
         asrzx   ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBZErr
         bra     TestArus_WWBZRet
TestArus_WWBZErr:
         nop     
         trap    
         nop     
TestArus_WWBZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
