.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BBDS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BBDS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cwx,0x00000000
         addsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x00
         mov     dwx,0x00000000
         subsx   fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x00
         mov     ewx,0x00000000
         andsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x00
         mov     fwx,0x00000000
         orsx    ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x00
         mov     gwx,0x00000000
         xorsx   bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x00
         mov     ar,0x00000000
         mulsx   ch,fl,ar
         cmp     ch,0x00
         bne     TestArus_BBDSErr
         mov     gl,0x00
         mov     br,0x00000000
         sdivsx  dh,gl,br
         cmp     dh,0xFF
         bne     TestArus_BBDSErr
         mov     ah,0x00
         mov     cr,0x00000000
         sremsx  eh,ah,cr
         cmp     eh,0x00
         bne     TestArus_BBDSErr
         mov     bh,0x00
         mov     dr,0x00000001
         addsx   fh,bh,dr
         cmp     fh,0x01
         bne     TestArus_BBDSErr
         mov     ch,0x00
         mov     er,0x00000001
         subsx   gh,ch,er
         cmp     gh,0xFF
         bne     TestArus_BBDSErr
         mov     dh,0x00
         mov     fr,0x00000001
         andsx   al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x00
         mov     gr,0x00000001
         orsx    bl,eh,gr
         cmp     bl,0x01
         bne     TestArus_BBDSErr
         mov     fh,0x00
         mov     awx,0x00000001
         xorsx   cl,fh,awx
         cmp     cl,0x01
         bne     TestArus_BBDSErr
         mov     gh,0x00
         mov     bwx,0x00000001
         mulsx   dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x00
         mov     cwx,0x00000001
         sdivsx  el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x00
         mov     dwx,0x00000001
         sremsx  fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x00
         mov     ewx,0x00000008
         addsx   gl,cl,ewx
         cmp     gl,0x08
         bne     TestArus_BBDSErr
         mov     dl,0x00
         mov     fwx,0x00000008
         subsx   ah,dl,fwx
         cmp     ah,0xF8
         bne     TestArus_BBDSErr
         mov     el,0x00
         mov     gwx,0x00000008
         andsx   bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x00
         mov     ar,0x00000008
         orsx    ch,fl,ar
         cmp     ch,0x08
         bne     TestArus_BBDSErr
         mov     gl,0x00
         mov     br,0x00000008
         xorsx   dh,gl,br
         cmp     dh,0x08
         bne     TestArus_BBDSErr
         mov     ah,0x00
         mov     cr,0x00000008
         mulsx   eh,ah,cr
         cmp     eh,0x00
         bne     TestArus_BBDSErr
         mov     bh,0x00
         mov     dr,0x00000008
         sdivsx  fh,bh,dr
         cmp     fh,0x00
         bne     TestArus_BBDSErr
         mov     ch,0x00
         mov     er,0x00000008
         sremsx  gh,ch,er
         cmp     gh,0x00
         bne     TestArus_BBDSErr
         mov     dh,0x00
         mov     fr,0x00000009
         addsx   al,dh,fr
         cmp     al,0x09
         bne     TestArus_BBDSErr
         mov     eh,0x00
         mov     gr,0x00000009
         subsx   bl,eh,gr
         cmp     bl,0xF7
         bne     TestArus_BBDSErr
         mov     fh,0x00
         mov     awx,0x00000009
         andsx   cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x00
         mov     bwx,0x00000009
         orsx    dl,gh,bwx
         cmp     dl,0x09
         bne     TestArus_BBDSErr
         mov     al,0x00
         mov     cwx,0x00000009
         xorsx   el,al,cwx
         cmp     el,0x09
         bne     TestArus_BBDSErr
         mov     bl,0x00
         mov     dwx,0x00000009
         mulsx   fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x00
         mov     ewx,0x00000009
         sdivsx  gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x00
         mov     fwx,0x00000009
         sremsx  ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x00
         mov     gwx,0x00007FFF
         addsx   bh,el,gwx
         cmp     bh,0xFF
         bne     TestArus_BBDSErr
         mov     fl,0x00
         mov     ar,0x00007FFF
         subsx   ch,fl,ar
         cmp     ch,0x01
         bne     TestArus_BBDSErr
         mov     gl,0x00
         mov     br,0x00007FFF
         andsx   dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x00
         mov     cr,0x00007FFF
         orsx    eh,ah,cr
         cmp     eh,0xFF
         bne     TestArus_BBDSErr
         mov     bh,0x00
         mov     dr,0x00007FFF
         xorsx   fh,bh,dr
         cmp     fh,0xFF
         bne     TestArus_BBDSErr
         mov     ch,0x00
         mov     er,0x00007FFF
         mulsx   gh,ch,er
         cmp     gh,0x00
         bne     TestArus_BBDSErr
         mov     dh,0x00
         mov     fr,0x00007FFF
         sdivsx  al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x00
         mov     gr,0x00007FFF
         sremsx  bl,eh,gr
         cmp     bl,0x00
         bne     TestArus_BBDSErr
         mov     fh,0x00
         mov     awx,0x00008000
         addsx   cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x00
         mov     bwx,0x00008000
         subsx   dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x00
         mov     cwx,0x00008000
         andsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x00
         mov     dwx,0x00008000
         orsx    fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x00
         mov     ewx,0x00008000
         xorsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x00
         mov     fwx,0x00008000
         mulsx   ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x00
         mov     gwx,0x00008000
         sdivsx  bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x00
         mov     ar,0x00008000
         sremsx  ch,fl,ar
         cmp     ch,0x00
         bne     TestArus_BBDSErr
         mov     gl,0x00
         mov     br,0x7FFFFFFF
         addsx   dh,gl,br
         cmp     dh,0xFF
         bne     TestArus_BBDSErr
         mov     ah,0x00
         mov     cr,0x7FFFFFFF
         subsx   eh,ah,cr
         cmp     eh,0x01
         bne     TestArus_BBDSErr
         mov     bh,0x00
         mov     dr,0x7FFFFFFF
         andsx   fh,bh,dr
         cmp     fh,0x00
         bne     TestArus_BBDSErr
         mov     ch,0x00
         mov     er,0x7FFFFFFF
         orsx    gh,ch,er
         cmp     gh,0xFF
         bne     TestArus_BBDSErr
         mov     dh,0x00
         mov     fr,0x7FFFFFFF
         xorsx   al,dh,fr
         cmp     al,0xFF
         bne     TestArus_BBDSErr
         mov     eh,0x00
         mov     gr,0x7FFFFFFF
         mulsx   bl,eh,gr
         cmp     bl,0x00
         bne     TestArus_BBDSErr
         mov     fh,0x00
         mov     awx,0x7FFFFFFF
         sdivsx  cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x00
         mov     bwx,0x7FFFFFFF
         sremsx  dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x00
         mov     cwx,0x80000000
         addsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x00
         mov     dwx,0x80000000
         subsx   fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x00
         mov     ewx,0x80000000
         andsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x00
         mov     fwx,0x80000000
         orsx    ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x00
         mov     gwx,0x80000000
         xorsx   bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x00
         mov     ar,0x80000000
         mulsx   ch,fl,ar
         cmp     ch,0x00
         bne     TestArus_BBDSErr
         mov     gl,0x00
         mov     br,0x80000000
         sdivsx  dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x00
         mov     cr,0x80000000
         sremsx  eh,ah,cr
         cmp     eh,0x00
         bne     TestArus_BBDSErr
         mov     bh,0x00
         mov     dr,0xFFFFFFFF
         addsx   fh,bh,dr
         cmp     fh,0xFF
         bne     TestArus_BBDSErr
         mov     ch,0x00
         mov     er,0xFFFFFFFF
         subsx   gh,ch,er
         cmp     gh,0x01
         bne     TestArus_BBDSErr
         mov     dh,0x00
         mov     fr,0xFFFFFFFF
         andsx   al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x00
         mov     gr,0xFFFFFFFF
         orsx    bl,eh,gr
         cmp     bl,0xFF
         bne     TestArus_BBDSErr
         mov     fh,0x00
         mov     awx,0xFFFFFFFF
         xorsx   cl,fh,awx
         cmp     cl,0xFF
         bne     TestArus_BBDSErr
         mov     gh,0x00
         mov     bwx,0xFFFFFFFF
         mulsx   dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x00
         mov     cwx,0xFFFFFFFF
         sdivsx  el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x00
         mov     dwx,0xFFFFFFFF
         sremsx  fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x01
         mov     ewx,0x00000001
         addsx   gl,cl,ewx
         cmp     gl,0x02
         bne     TestArus_BBDSErr
         mov     dl,0x01
         mov     fwx,0x00000001
         subsx   ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x01
         mov     gwx,0x00000001
         andsx   bh,el,gwx
         cmp     bh,0x01
         bne     TestArus_BBDSErr
         mov     fl,0x01
         mov     ar,0x00000001
         orsx    ch,fl,ar
         cmp     ch,0x01
         bne     TestArus_BBDSErr
         mov     gl,0x01
         mov     br,0x00000001
         xorsx   dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x01
         mov     cr,0x00000001
         mulsx   eh,ah,cr
         cmp     eh,0x01
         bne     TestArus_BBDSErr
         mov     bh,0x01
         mov     dr,0x00000001
         sdivsx  fh,bh,dr
         cmp     fh,0x01
         bne     TestArus_BBDSErr
         mov     ch,0x01
         mov     er,0x00000001
         sremsx  gh,ch,er
         cmp     gh,0x00
         bne     TestArus_BBDSErr
         mov     dh,0x01
         mov     fr,0x00000008
         addsx   al,dh,fr
         cmp     al,0x09
         bne     TestArus_BBDSErr
         mov     eh,0x01
         mov     gr,0x00000008
         subsx   bl,eh,gr
         cmp     bl,0xF9
         bne     TestArus_BBDSErr
         mov     fh,0x01
         mov     awx,0x00000008
         andsx   cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x01
         mov     bwx,0x00000008
         orsx    dl,gh,bwx
         cmp     dl,0x09
         bne     TestArus_BBDSErr
         mov     al,0x01
         mov     cwx,0x00000008
         xorsx   el,al,cwx
         cmp     el,0x09
         bne     TestArus_BBDSErr
         mov     bl,0x01
         mov     dwx,0x00000008
         mulsx   fl,bl,dwx
         cmp     fl,0x08
         bne     TestArus_BBDSErr
         mov     cl,0x01
         mov     ewx,0x00000008
         sdivsx  gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x01
         mov     fwx,0x00000008
         sremsx  ah,dl,fwx
         cmp     ah,0x01
         bne     TestArus_BBDSErr
         mov     el,0x01
         mov     gwx,0x00000009
         addsx   bh,el,gwx
         cmp     bh,0x0A
         bne     TestArus_BBDSErr
         mov     fl,0x01
         mov     ar,0x00000009
         subsx   ch,fl,ar
         cmp     ch,0xF8
         bne     TestArus_BBDSErr
         mov     gl,0x01
         mov     br,0x00000009
         andsx   dh,gl,br
         cmp     dh,0x01
         bne     TestArus_BBDSErr
         mov     ah,0x01
         mov     cr,0x00000009
         orsx    eh,ah,cr
         cmp     eh,0x09
         bne     TestArus_BBDSErr
         mov     bh,0x01
         mov     dr,0x00000009
         xorsx   fh,bh,dr
         cmp     fh,0x08
         bne     TestArus_BBDSErr
         mov     ch,0x01
         mov     er,0x00000009
         mulsx   gh,ch,er
         cmp     gh,0x09
         bne     TestArus_BBDSErr
         mov     dh,0x01
         mov     fr,0x00000009
         sdivsx  al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x01
         mov     gr,0x00000009
         sremsx  bl,eh,gr
         cmp     bl,0x01
         bne     TestArus_BBDSErr
         mov     fh,0x01
         mov     awx,0x00007FFF
         addsx   cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x01
         mov     bwx,0x00007FFF
         subsx   dl,gh,bwx
         cmp     dl,0x02
         bne     TestArus_BBDSErr
         mov     al,0x01
         mov     cwx,0x00007FFF
         andsx   el,al,cwx
         cmp     el,0x01
         bne     TestArus_BBDSErr
         mov     bl,0x01
         mov     dwx,0x00007FFF
         orsx    fl,bl,dwx
         cmp     fl,0xFF
         bne     TestArus_BBDSErr
         mov     cl,0x01
         mov     ewx,0x00007FFF
         xorsx   gl,cl,ewx
         cmp     gl,0xFE
         bne     TestArus_BBDSErr
         mov     dl,0x01
         mov     fwx,0x00007FFF
         mulsx   ah,dl,fwx
         cmp     ah,0xFF
         bne     TestArus_BBDSErr
         mov     el,0x01
         mov     gwx,0x00007FFF
         sdivsx  bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x01
         mov     ar,0x00007FFF
         sremsx  ch,fl,ar
         cmp     ch,0x01
         bne     TestArus_BBDSErr
         mov     gl,0x01
         mov     br,0x00008000
         addsx   dh,gl,br
         cmp     dh,0x01
         bne     TestArus_BBDSErr
         mov     ah,0x01
         mov     cr,0x00008000
         subsx   eh,ah,cr
         cmp     eh,0x01
         bne     TestArus_BBDSErr
         mov     bh,0x01
         mov     dr,0x00008000
         andsx   fh,bh,dr
         cmp     fh,0x00
         bne     TestArus_BBDSErr
         mov     ch,0x01
         mov     er,0x00008000
         orsx    gh,ch,er
         cmp     gh,0x01
         bne     TestArus_BBDSErr
         mov     dh,0x01
         mov     fr,0x00008000
         xorsx   al,dh,fr
         cmp     al,0x01
         bne     TestArus_BBDSErr
         mov     eh,0x01
         mov     gr,0x00008000
         mulsx   bl,eh,gr
         cmp     bl,0x00
         bne     TestArus_BBDSErr
         mov     fh,0x01
         mov     awx,0x00008000
         sdivsx  cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x01
         mov     bwx,0x00008000
         sremsx  dl,gh,bwx
         cmp     dl,0x01
         bne     TestArus_BBDSErr
         mov     al,0x01
         mov     cwx,0x7FFFFFFF
         addsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x01
         mov     dwx,0x7FFFFFFF
         subsx   fl,bl,dwx
         cmp     fl,0x02
         bne     TestArus_BBDSErr
         mov     cl,0x01
         mov     ewx,0x7FFFFFFF
         andsx   gl,cl,ewx
         cmp     gl,0x01
         bne     TestArus_BBDSErr
         mov     dl,0x01
         mov     fwx,0x7FFFFFFF
         orsx    ah,dl,fwx
         cmp     ah,0xFF
         bne     TestArus_BBDSErr
         mov     el,0x01
         mov     gwx,0x7FFFFFFF
         xorsx   bh,el,gwx
         cmp     bh,0xFE
         bne     TestArus_BBDSErr
         mov     fl,0x01
         mov     ar,0x7FFFFFFF
         mulsx   ch,fl,ar
         cmp     ch,0xFF
         bne     TestArus_BBDSErr
         mov     gl,0x01
         mov     br,0x7FFFFFFF
         sdivsx  dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x01
         mov     cr,0x7FFFFFFF
         sremsx  eh,ah,cr
         cmp     eh,0x01
         bne     TestArus_BBDSErr
         mov     bh,0x01
         mov     dr,0x80000000
         addsx   fh,bh,dr
         cmp     fh,0x01
         bne     TestArus_BBDSErr
         mov     ch,0x01
         mov     er,0x80000000
         subsx   gh,ch,er
         cmp     gh,0x01
         bne     TestArus_BBDSErr
         mov     dh,0x01
         mov     fr,0x80000000
         andsx   al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x01
         mov     gr,0x80000000
         orsx    bl,eh,gr
         cmp     bl,0x01
         bne     TestArus_BBDSErr
         mov     fh,0x01
         mov     awx,0x80000000
         xorsx   cl,fh,awx
         cmp     cl,0x01
         bne     TestArus_BBDSErr
         mov     gh,0x01
         mov     bwx,0x80000000
         mulsx   dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x01
         mov     cwx,0x80000000
         sdivsx  el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x01
         mov     dwx,0x80000000
         sremsx  fl,bl,dwx
         cmp     fl,0x01
         bne     TestArus_BBDSErr
         mov     cl,0x01
         mov     ewx,0xFFFFFFFF
         addsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x01
         mov     fwx,0xFFFFFFFF
         subsx   ah,dl,fwx
         cmp     ah,0x02
         bne     TestArus_BBDSErr
         mov     el,0x01
         mov     gwx,0xFFFFFFFF
         andsx   bh,el,gwx
         cmp     bh,0x01
         bne     TestArus_BBDSErr
         mov     fl,0x01
         mov     ar,0xFFFFFFFF
         orsx    ch,fl,ar
         cmp     ch,0xFF
         bne     TestArus_BBDSErr
         mov     gl,0x01
         mov     br,0xFFFFFFFF
         xorsx   dh,gl,br
         cmp     dh,0xFE
         bne     TestArus_BBDSErr
         mov     ah,0x01
         mov     cr,0xFFFFFFFF
         mulsx   eh,ah,cr
         cmp     eh,0xFF
         bne     TestArus_BBDSErr
         mov     bh,0x01
         mov     dr,0xFFFFFFFF
         sdivsx  fh,bh,dr
         cmp     fh,0xFF
         bne     TestArus_BBDSErr
         mov     ch,0x01
         mov     er,0xFFFFFFFF
         sremsx  gh,ch,er
         cmp     gh,0x00
         bne     TestArus_BBDSErr
         mov     dh,0x07
         mov     fr,0x00000008
         addsx   al,dh,fr
         cmp     al,0x0F
         bne     TestArus_BBDSErr
         mov     eh,0x07
         mov     gr,0x00000008
         subsx   bl,eh,gr
         cmp     bl,0xFF
         bne     TestArus_BBDSErr
         mov     fh,0x07
         mov     awx,0x00000008
         andsx   cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x07
         mov     bwx,0x00000008
         orsx    dl,gh,bwx
         cmp     dl,0x0F
         bne     TestArus_BBDSErr
         mov     al,0x07
         mov     cwx,0x00000008
         xorsx   el,al,cwx
         cmp     el,0x0F
         bne     TestArus_BBDSErr
         mov     bl,0x07
         mov     dwx,0x00000008
         mulsx   fl,bl,dwx
         cmp     fl,0x38
         bne     TestArus_BBDSErr
         mov     cl,0x07
         mov     ewx,0x00000008
         sdivsx  gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x07
         mov     fwx,0x00000008
         sremsx  ah,dl,fwx
         cmp     ah,0x07
         bne     TestArus_BBDSErr
         mov     el,0x07
         mov     gwx,0x00000009
         addsx   bh,el,gwx
         cmp     bh,0x10
         bne     TestArus_BBDSErr
         mov     fl,0x07
         mov     ar,0x00000009
         subsx   ch,fl,ar
         cmp     ch,0xFE
         bne     TestArus_BBDSErr
         mov     gl,0x07
         mov     br,0x00000009
         andsx   dh,gl,br
         cmp     dh,0x01
         bne     TestArus_BBDSErr
         mov     ah,0x07
         mov     cr,0x00000009
         orsx    eh,ah,cr
         cmp     eh,0x0F
         bne     TestArus_BBDSErr
         mov     bh,0x07
         mov     dr,0x00000009
         xorsx   fh,bh,dr
         cmp     fh,0x0E
         bne     TestArus_BBDSErr
         mov     ch,0x07
         mov     er,0x00000009
         mulsx   gh,ch,er
         cmp     gh,0x3F
         bne     TestArus_BBDSErr
         mov     dh,0x07
         mov     fr,0x00000009
         sdivsx  al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x07
         mov     gr,0x00000009
         sremsx  bl,eh,gr
         cmp     bl,0x07
         bne     TestArus_BBDSErr
         mov     fh,0x07
         mov     awx,0x00007FFF
         addsx   cl,fh,awx
         cmp     cl,0x06
         bne     TestArus_BBDSErr
         mov     gh,0x07
         mov     bwx,0x00007FFF
         subsx   dl,gh,bwx
         cmp     dl,0x08
         bne     TestArus_BBDSErr
         mov     al,0x07
         mov     cwx,0x00007FFF
         andsx   el,al,cwx
         cmp     el,0x07
         bne     TestArus_BBDSErr
         mov     bl,0x07
         mov     dwx,0x00007FFF
         orsx    fl,bl,dwx
         cmp     fl,0xFF
         bne     TestArus_BBDSErr
         mov     cl,0x07
         mov     ewx,0x00007FFF
         xorsx   gl,cl,ewx
         cmp     gl,0xF8
         bne     TestArus_BBDSErr
         mov     dl,0x07
         mov     fwx,0x00007FFF
         mulsx   ah,dl,fwx
         cmp     ah,0xF9
         bne     TestArus_BBDSErr
         mov     el,0x07
         mov     gwx,0x00007FFF
         sdivsx  bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x07
         mov     ar,0x00007FFF
         sremsx  ch,fl,ar
         cmp     ch,0x07
         bne     TestArus_BBDSErr
         mov     gl,0x07
         mov     br,0x00008000
         addsx   dh,gl,br
         cmp     dh,0x07
         bne     TestArus_BBDSErr
         mov     ah,0x07
         mov     cr,0x00008000
         subsx   eh,ah,cr
         cmp     eh,0x07
         bne     TestArus_BBDSErr
         mov     bh,0x07
         mov     dr,0x00008000
         andsx   fh,bh,dr
         cmp     fh,0x00
         bne     TestArus_BBDSErr
         mov     ch,0x07
         mov     er,0x00008000
         orsx    gh,ch,er
         cmp     gh,0x07
         bne     TestArus_BBDSErr
         mov     dh,0x07
         mov     fr,0x00008000
         xorsx   al,dh,fr
         cmp     al,0x07
         bne     TestArus_BBDSErr
         mov     eh,0x07
         mov     gr,0x00008000
         mulsx   bl,eh,gr
         cmp     bl,0x00
         bne     TestArus_BBDSErr
         mov     fh,0x07
         mov     awx,0x00008000
         sdivsx  cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x07
         mov     bwx,0x00008000
         sremsx  dl,gh,bwx
         cmp     dl,0x07
         bne     TestArus_BBDSErr
         mov     al,0x07
         mov     cwx,0x7FFFFFFF
         addsx   el,al,cwx
         cmp     el,0x06
         bne     TestArus_BBDSErr
         mov     bl,0x07
         mov     dwx,0x7FFFFFFF
         subsx   fl,bl,dwx
         cmp     fl,0x08
         bne     TestArus_BBDSErr
         mov     cl,0x07
         mov     ewx,0x7FFFFFFF
         andsx   gl,cl,ewx
         cmp     gl,0x07
         bne     TestArus_BBDSErr
         mov     dl,0x07
         mov     fwx,0x7FFFFFFF
         orsx    ah,dl,fwx
         cmp     ah,0xFF
         bne     TestArus_BBDSErr
         mov     el,0x07
         mov     gwx,0x7FFFFFFF
         xorsx   bh,el,gwx
         cmp     bh,0xF8
         bne     TestArus_BBDSErr
         mov     fl,0x07
         mov     ar,0x7FFFFFFF
         mulsx   ch,fl,ar
         cmp     ch,0xF9
         bne     TestArus_BBDSErr
         mov     gl,0x07
         mov     br,0x7FFFFFFF
         sdivsx  dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x07
         mov     cr,0x7FFFFFFF
         sremsx  eh,ah,cr
         cmp     eh,0x07
         bne     TestArus_BBDSErr
         mov     bh,0x07
         mov     dr,0x80000000
         addsx   fh,bh,dr
         cmp     fh,0x07
         bne     TestArus_BBDSErr
         mov     ch,0x07
         mov     er,0x80000000
         subsx   gh,ch,er
         cmp     gh,0x07
         bne     TestArus_BBDSErr
         mov     dh,0x07
         mov     fr,0x80000000
         andsx   al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x07
         mov     gr,0x80000000
         orsx    bl,eh,gr
         cmp     bl,0x07
         bne     TestArus_BBDSErr
         mov     fh,0x07
         mov     awx,0x80000000
         xorsx   cl,fh,awx
         cmp     cl,0x07
         bne     TestArus_BBDSErr
         mov     gh,0x07
         mov     bwx,0x80000000
         mulsx   dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x07
         mov     cwx,0x80000000
         sdivsx  el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x07
         mov     dwx,0x80000000
         sremsx  fl,bl,dwx
         cmp     fl,0x07
         bne     TestArus_BBDSErr
         mov     cl,0x07
         mov     ewx,0xFFFFFFFF
         addsx   gl,cl,ewx
         cmp     gl,0x06
         bne     TestArus_BBDSErr
         mov     dl,0x07
         mov     fwx,0xFFFFFFFF
         subsx   ah,dl,fwx
         cmp     ah,0x08
         bne     TestArus_BBDSErr
         mov     el,0x07
         mov     gwx,0xFFFFFFFF
         andsx   bh,el,gwx
         cmp     bh,0x07
         bne     TestArus_BBDSErr
         mov     fl,0x07
         mov     ar,0xFFFFFFFF
         orsx    ch,fl,ar
         cmp     ch,0xFF
         bne     TestArus_BBDSErr
         mov     gl,0x07
         mov     br,0xFFFFFFFF
         xorsx   dh,gl,br
         cmp     dh,0xF8
         bne     TestArus_BBDSErr
         mov     ah,0x07
         mov     cr,0xFFFFFFFF
         mulsx   eh,ah,cr
         cmp     eh,0xF9
         bne     TestArus_BBDSErr
         mov     bh,0x07
         mov     dr,0xFFFFFFFF
         sdivsx  fh,bh,dr
         cmp     fh,0xF9
         bne     TestArus_BBDSErr
         mov     ch,0x07
         mov     er,0xFFFFFFFF
         sremsx  gh,ch,er
         cmp     gh,0x00
         bne     TestArus_BBDSErr
         mov     dh,0x08
         mov     fr,0x00000009
         addsx   al,dh,fr
         cmp     al,0x11
         bne     TestArus_BBDSErr
         mov     eh,0x08
         mov     gr,0x00000009
         subsx   bl,eh,gr
         cmp     bl,0xFF
         bne     TestArus_BBDSErr
         mov     fh,0x08
         mov     awx,0x00000009
         andsx   cl,fh,awx
         cmp     cl,0x08
         bne     TestArus_BBDSErr
         mov     gh,0x08
         mov     bwx,0x00000009
         orsx    dl,gh,bwx
         cmp     dl,0x09
         bne     TestArus_BBDSErr
         mov     al,0x08
         mov     cwx,0x00000009
         xorsx   el,al,cwx
         cmp     el,0x01
         bne     TestArus_BBDSErr
         mov     bl,0x08
         mov     dwx,0x00000009
         mulsx   fl,bl,dwx
         cmp     fl,0x48
         bne     TestArus_BBDSErr
         mov     cl,0x08
         mov     ewx,0x00000009
         sdivsx  gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x08
         mov     fwx,0x00000009
         sremsx  ah,dl,fwx
         cmp     ah,0x08
         bne     TestArus_BBDSErr
         mov     el,0x08
         mov     gwx,0x00007FFF
         addsx   bh,el,gwx
         cmp     bh,0x07
         bne     TestArus_BBDSErr
         mov     fl,0x08
         mov     ar,0x00007FFF
         subsx   ch,fl,ar
         cmp     ch,0x09
         bne     TestArus_BBDSErr
         mov     gl,0x08
         mov     br,0x00007FFF
         andsx   dh,gl,br
         cmp     dh,0x08
         bne     TestArus_BBDSErr
         mov     ah,0x08
         mov     cr,0x00007FFF
         orsx    eh,ah,cr
         cmp     eh,0xFF
         bne     TestArus_BBDSErr
         mov     bh,0x08
         mov     dr,0x00007FFF
         xorsx   fh,bh,dr
         cmp     fh,0xF7
         bne     TestArus_BBDSErr
         mov     ch,0x08
         mov     er,0x00007FFF
         mulsx   gh,ch,er
         cmp     gh,0xF8
         bne     TestArus_BBDSErr
         mov     dh,0x08
         mov     fr,0x00007FFF
         sdivsx  al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x08
         mov     gr,0x00007FFF
         sremsx  bl,eh,gr
         cmp     bl,0x08
         bne     TestArus_BBDSErr
         mov     fh,0x08
         mov     awx,0x00008000
         addsx   cl,fh,awx
         cmp     cl,0x08
         bne     TestArus_BBDSErr
         mov     gh,0x08
         mov     bwx,0x00008000
         subsx   dl,gh,bwx
         cmp     dl,0x08
         bne     TestArus_BBDSErr
         mov     al,0x08
         mov     cwx,0x00008000
         andsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x08
         mov     dwx,0x00008000
         orsx    fl,bl,dwx
         cmp     fl,0x08
         bne     TestArus_BBDSErr
         mov     cl,0x08
         mov     ewx,0x00008000
         xorsx   gl,cl,ewx
         cmp     gl,0x08
         bne     TestArus_BBDSErr
         mov     dl,0x08
         mov     fwx,0x00008000
         mulsx   ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x08
         mov     gwx,0x00008000
         sdivsx  bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x08
         mov     ar,0x00008000
         sremsx  ch,fl,ar
         cmp     ch,0x08
         bne     TestArus_BBDSErr
         mov     gl,0x08
         mov     br,0x7FFFFFFF
         addsx   dh,gl,br
         cmp     dh,0x07
         bne     TestArus_BBDSErr
         mov     ah,0x08
         mov     cr,0x7FFFFFFF
         subsx   eh,ah,cr
         cmp     eh,0x09
         bne     TestArus_BBDSErr
         mov     bh,0x08
         mov     dr,0x7FFFFFFF
         andsx   fh,bh,dr
         cmp     fh,0x08
         bne     TestArus_BBDSErr
         mov     ch,0x08
         mov     er,0x7FFFFFFF
         orsx    gh,ch,er
         cmp     gh,0xFF
         bne     TestArus_BBDSErr
         mov     dh,0x08
         mov     fr,0x7FFFFFFF
         xorsx   al,dh,fr
         cmp     al,0xF7
         bne     TestArus_BBDSErr
         mov     eh,0x08
         mov     gr,0x7FFFFFFF
         mulsx   bl,eh,gr
         cmp     bl,0xF8
         bne     TestArus_BBDSErr
         mov     fh,0x08
         mov     awx,0x7FFFFFFF
         sdivsx  cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x08
         mov     bwx,0x7FFFFFFF
         sremsx  dl,gh,bwx
         cmp     dl,0x08
         bne     TestArus_BBDSErr
         mov     al,0x08
         mov     cwx,0x80000000
         addsx   el,al,cwx
         cmp     el,0x08
         bne     TestArus_BBDSErr
         mov     bl,0x08
         mov     dwx,0x80000000
         subsx   fl,bl,dwx
         cmp     fl,0x08
         bne     TestArus_BBDSErr
         mov     cl,0x08
         mov     ewx,0x80000000
         andsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x08
         mov     fwx,0x80000000
         orsx    ah,dl,fwx
         cmp     ah,0x08
         bne     TestArus_BBDSErr
         mov     el,0x08
         mov     gwx,0x80000000
         xorsx   bh,el,gwx
         cmp     bh,0x08
         bne     TestArus_BBDSErr
         mov     fl,0x08
         mov     ar,0x80000000
         mulsx   ch,fl,ar
         cmp     ch,0x00
         bne     TestArus_BBDSErr
         mov     gl,0x08
         mov     br,0x80000000
         sdivsx  dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x08
         mov     cr,0x80000000
         sremsx  eh,ah,cr
         cmp     eh,0x08
         bne     TestArus_BBDSErr
         mov     bh,0x08
         mov     dr,0xFFFFFFFF
         addsx   fh,bh,dr
         cmp     fh,0x07
         bne     TestArus_BBDSErr
         mov     ch,0x08
         mov     er,0xFFFFFFFF
         subsx   gh,ch,er
         cmp     gh,0x09
         bne     TestArus_BBDSErr
         mov     dh,0x08
         mov     fr,0xFFFFFFFF
         andsx   al,dh,fr
         cmp     al,0x08
         bne     TestArus_BBDSErr
         mov     eh,0x08
         mov     gr,0xFFFFFFFF
         orsx    bl,eh,gr
         cmp     bl,0xFF
         bne     TestArus_BBDSErr
         mov     fh,0x08
         mov     awx,0xFFFFFFFF
         xorsx   cl,fh,awx
         cmp     cl,0xF7
         bne     TestArus_BBDSErr
         mov     gh,0x08
         mov     bwx,0xFFFFFFFF
         mulsx   dl,gh,bwx
         cmp     dl,0xF8
         bne     TestArus_BBDSErr
         mov     al,0x08
         mov     cwx,0xFFFFFFFF
         sdivsx  el,al,cwx
         cmp     el,0xF8
         bne     TestArus_BBDSErr
         mov     bl,0x08
         mov     dwx,0xFFFFFFFF
         sremsx  fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x09
         mov     ewx,0x00007FFF
         addsx   gl,cl,ewx
         cmp     gl,0x08
         bne     TestArus_BBDSErr
         mov     dl,0x09
         mov     fwx,0x00007FFF
         subsx   ah,dl,fwx
         cmp     ah,0x0A
         bne     TestArus_BBDSErr
         mov     el,0x09
         mov     gwx,0x00007FFF
         andsx   bh,el,gwx
         cmp     bh,0x09
         bne     TestArus_BBDSErr
         mov     fl,0x09
         mov     ar,0x00007FFF
         orsx    ch,fl,ar
         cmp     ch,0xFF
         bne     TestArus_BBDSErr
         mov     gl,0x09
         mov     br,0x00007FFF
         xorsx   dh,gl,br
         cmp     dh,0xF6
         bne     TestArus_BBDSErr
         mov     ah,0x09
         mov     cr,0x00007FFF
         mulsx   eh,ah,cr
         cmp     eh,0xF7
         bne     TestArus_BBDSErr
         mov     bh,0x09
         mov     dr,0x00007FFF
         sdivsx  fh,bh,dr
         cmp     fh,0x00
         bne     TestArus_BBDSErr
         mov     ch,0x09
         mov     er,0x00007FFF
         sremsx  gh,ch,er
         cmp     gh,0x09
         bne     TestArus_BBDSErr
         mov     dh,0x09
         mov     fr,0x00008000
         addsx   al,dh,fr
         cmp     al,0x09
         bne     TestArus_BBDSErr
         mov     eh,0x09
         mov     gr,0x00008000
         subsx   bl,eh,gr
         cmp     bl,0x09
         bne     TestArus_BBDSErr
         mov     fh,0x09
         mov     awx,0x00008000
         andsx   cl,fh,awx
         cmp     cl,0x00
         bne     TestArus_BBDSErr
         mov     gh,0x09
         mov     bwx,0x00008000
         orsx    dl,gh,bwx
         cmp     dl,0x09
         bne     TestArus_BBDSErr
         mov     al,0x09
         mov     cwx,0x00008000
         xorsx   el,al,cwx
         cmp     el,0x09
         bne     TestArus_BBDSErr
         mov     bl,0x09
         mov     dwx,0x00008000
         mulsx   fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0x09
         mov     ewx,0x00008000
         sdivsx  gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x09
         mov     fwx,0x00008000
         sremsx  ah,dl,fwx
         cmp     ah,0x09
         bne     TestArus_BBDSErr
         mov     el,0x09
         mov     gwx,0x7FFFFFFF
         addsx   bh,el,gwx
         cmp     bh,0x08
         bne     TestArus_BBDSErr
         mov     fl,0x09
         mov     ar,0x7FFFFFFF
         subsx   ch,fl,ar
         cmp     ch,0x0A
         bne     TestArus_BBDSErr
         mov     gl,0x09
         mov     br,0x7FFFFFFF
         andsx   dh,gl,br
         cmp     dh,0x09
         bne     TestArus_BBDSErr
         mov     ah,0x09
         mov     cr,0x7FFFFFFF
         orsx    eh,ah,cr
         cmp     eh,0xFF
         bne     TestArus_BBDSErr
         mov     bh,0x09
         mov     dr,0x7FFFFFFF
         xorsx   fh,bh,dr
         cmp     fh,0xF6
         bne     TestArus_BBDSErr
         mov     ch,0x09
         mov     er,0x7FFFFFFF
         mulsx   gh,ch,er
         cmp     gh,0xF7
         bne     TestArus_BBDSErr
         mov     dh,0x09
         mov     fr,0x7FFFFFFF
         sdivsx  al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x09
         mov     gr,0x7FFFFFFF
         sremsx  bl,eh,gr
         cmp     bl,0x09
         bne     TestArus_BBDSErr
         mov     fh,0x09
         mov     awx,0x80000000
         addsx   cl,fh,awx
         cmp     cl,0x09
         bne     TestArus_BBDSErr
         mov     gh,0x09
         mov     bwx,0x80000000
         subsx   dl,gh,bwx
         cmp     dl,0x09
         bne     TestArus_BBDSErr
         mov     al,0x09
         mov     cwx,0x80000000
         andsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x09
         mov     dwx,0x80000000
         orsx    fl,bl,dwx
         cmp     fl,0x09
         bne     TestArus_BBDSErr
         mov     cl,0x09
         mov     ewx,0x80000000
         xorsx   gl,cl,ewx
         cmp     gl,0x09
         bne     TestArus_BBDSErr
         mov     dl,0x09
         mov     fwx,0x80000000
         mulsx   ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x09
         mov     gwx,0x80000000
         sdivsx  bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x09
         mov     ar,0x80000000
         sremsx  ch,fl,ar
         cmp     ch,0x09
         bne     TestArus_BBDSErr
         mov     gl,0x09
         mov     br,0xFFFFFFFF
         addsx   dh,gl,br
         cmp     dh,0x08
         bne     TestArus_BBDSErr
         mov     ah,0x09
         mov     cr,0xFFFFFFFF
         subsx   eh,ah,cr
         cmp     eh,0x0A
         bne     TestArus_BBDSErr
         mov     bh,0x09
         mov     dr,0xFFFFFFFF
         andsx   fh,bh,dr
         cmp     fh,0x09
         bne     TestArus_BBDSErr
         mov     ch,0x09
         mov     er,0xFFFFFFFF
         orsx    gh,ch,er
         cmp     gh,0xFF
         bne     TestArus_BBDSErr
         mov     dh,0x09
         mov     fr,0xFFFFFFFF
         xorsx   al,dh,fr
         cmp     al,0xF6
         bne     TestArus_BBDSErr
         mov     eh,0x09
         mov     gr,0xFFFFFFFF
         mulsx   bl,eh,gr
         cmp     bl,0xF7
         bne     TestArus_BBDSErr
         mov     fh,0x09
         mov     awx,0xFFFFFFFF
         sdivsx  cl,fh,awx
         cmp     cl,0xF7
         bne     TestArus_BBDSErr
         mov     gh,0x09
         mov     bwx,0xFFFFFFFF
         sremsx  dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x0F
         mov     cwx,0x00008000
         addsx   el,al,cwx
         cmp     el,0x0F
         bne     TestArus_BBDSErr
         mov     bl,0x0F
         mov     dwx,0x00008000
         subsx   fl,bl,dwx
         cmp     fl,0x0F
         bne     TestArus_BBDSErr
         mov     cl,0x0F
         mov     ewx,0x00008000
         andsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x0F
         mov     fwx,0x00008000
         orsx    ah,dl,fwx
         cmp     ah,0x0F
         bne     TestArus_BBDSErr
         mov     el,0x0F
         mov     gwx,0x00008000
         xorsx   bh,el,gwx
         cmp     bh,0x0F
         bne     TestArus_BBDSErr
         mov     fl,0x0F
         mov     ar,0x00008000
         mulsx   ch,fl,ar
         cmp     ch,0x00
         bne     TestArus_BBDSErr
         mov     gl,0x0F
         mov     br,0x00008000
         sdivsx  dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x0F
         mov     cr,0x00008000
         sremsx  eh,ah,cr
         cmp     eh,0x0F
         bne     TestArus_BBDSErr
         mov     bh,0x0F
         mov     dr,0x7FFFFFFF
         addsx   fh,bh,dr
         cmp     fh,0x0E
         bne     TestArus_BBDSErr
         mov     ch,0x0F
         mov     er,0x7FFFFFFF
         subsx   gh,ch,er
         cmp     gh,0x10
         bne     TestArus_BBDSErr
         mov     dh,0x0F
         mov     fr,0x7FFFFFFF
         andsx   al,dh,fr
         cmp     al,0x0F
         bne     TestArus_BBDSErr
         mov     eh,0x0F
         mov     gr,0x7FFFFFFF
         orsx    bl,eh,gr
         cmp     bl,0xFF
         bne     TestArus_BBDSErr
         mov     fh,0x0F
         mov     awx,0x7FFFFFFF
         xorsx   cl,fh,awx
         cmp     cl,0xF0
         bne     TestArus_BBDSErr
         mov     gh,0x0F
         mov     bwx,0x7FFFFFFF
         mulsx   dl,gh,bwx
         cmp     dl,0xF1
         bne     TestArus_BBDSErr
         mov     al,0x0F
         mov     cwx,0x7FFFFFFF
         sdivsx  el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x0F
         mov     dwx,0x7FFFFFFF
         sremsx  fl,bl,dwx
         cmp     fl,0x0F
         bne     TestArus_BBDSErr
         mov     cl,0x0F
         mov     ewx,0x80000000
         addsx   gl,cl,ewx
         cmp     gl,0x0F
         bne     TestArus_BBDSErr
         mov     dl,0x0F
         mov     fwx,0x80000000
         subsx   ah,dl,fwx
         cmp     ah,0x0F
         bne     TestArus_BBDSErr
         mov     el,0x0F
         mov     gwx,0x80000000
         andsx   bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x0F
         mov     ar,0x80000000
         orsx    ch,fl,ar
         cmp     ch,0x0F
         bne     TestArus_BBDSErr
         mov     gl,0x0F
         mov     br,0x80000000
         xorsx   dh,gl,br
         cmp     dh,0x0F
         bne     TestArus_BBDSErr
         mov     ah,0x0F
         mov     cr,0x80000000
         mulsx   eh,ah,cr
         cmp     eh,0x00
         bne     TestArus_BBDSErr
         mov     bh,0x0F
         mov     dr,0x80000000
         sdivsx  fh,bh,dr
         cmp     fh,0x00
         bne     TestArus_BBDSErr
         mov     ch,0x0F
         mov     er,0x80000000
         sremsx  gh,ch,er
         cmp     gh,0x0F
         bne     TestArus_BBDSErr
         mov     dh,0x0F
         mov     fr,0xFFFFFFFF
         addsx   al,dh,fr
         cmp     al,0x0E
         bne     TestArus_BBDSErr
         mov     eh,0x0F
         mov     gr,0xFFFFFFFF
         subsx   bl,eh,gr
         cmp     bl,0x10
         bne     TestArus_BBDSErr
         mov     fh,0x0F
         mov     awx,0xFFFFFFFF
         andsx   cl,fh,awx
         cmp     cl,0x0F
         bne     TestArus_BBDSErr
         mov     gh,0x0F
         mov     bwx,0xFFFFFFFF
         orsx    dl,gh,bwx
         cmp     dl,0xFF
         bne     TestArus_BBDSErr
         mov     al,0x0F
         mov     cwx,0xFFFFFFFF
         xorsx   el,al,cwx
         cmp     el,0xF0
         bne     TestArus_BBDSErr
         mov     bl,0x0F
         mov     dwx,0xFFFFFFFF
         mulsx   fl,bl,dwx
         cmp     fl,0xF1
         bne     TestArus_BBDSErr
         mov     cl,0x0F
         mov     ewx,0xFFFFFFFF
         sdivsx  gl,cl,ewx
         cmp     gl,0xF1
         bne     TestArus_BBDSErr
         mov     dl,0x0F
         mov     fwx,0xFFFFFFFF
         sremsx  ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x7F
         mov     gwx,0x7FFFFFFF
         addsx   bh,el,gwx
         cmp     bh,0x7E
         bne     TestArus_BBDSErr
         mov     fl,0x7F
         mov     ar,0x7FFFFFFF
         subsx   ch,fl,ar
         cmp     ch,0x80
         bne     TestArus_BBDSErr
         mov     gl,0x7F
         mov     br,0x7FFFFFFF
         andsx   dh,gl,br
         cmp     dh,0x7F
         bne     TestArus_BBDSErr
         mov     ah,0x7F
         mov     cr,0x7FFFFFFF
         orsx    eh,ah,cr
         cmp     eh,0xFF
         bne     TestArus_BBDSErr
         mov     bh,0x7F
         mov     dr,0x7FFFFFFF
         xorsx   fh,bh,dr
         cmp     fh,0x80
         bne     TestArus_BBDSErr
         mov     ch,0x7F
         mov     er,0x7FFFFFFF
         mulsx   gh,ch,er
         cmp     gh,0x81
         bne     TestArus_BBDSErr
         mov     dh,0x7F
         mov     fr,0x7FFFFFFF
         sdivsx  al,dh,fr
         cmp     al,0x00
         bne     TestArus_BBDSErr
         mov     eh,0x7F
         mov     gr,0x7FFFFFFF
         sremsx  bl,eh,gr
         cmp     bl,0x7F
         bne     TestArus_BBDSErr
         mov     fh,0x7F
         mov     awx,0x80000000
         addsx   cl,fh,awx
         cmp     cl,0x7F
         bne     TestArus_BBDSErr
         mov     gh,0x7F
         mov     bwx,0x80000000
         subsx   dl,gh,bwx
         cmp     dl,0x7F
         bne     TestArus_BBDSErr
         mov     al,0x7F
         mov     cwx,0x80000000
         andsx   el,al,cwx
         cmp     el,0x00
         bne     TestArus_BBDSErr
         mov     bl,0x7F
         mov     dwx,0x80000000
         orsx    fl,bl,dwx
         cmp     fl,0x7F
         bne     TestArus_BBDSErr
         mov     cl,0x7F
         mov     ewx,0x80000000
         xorsx   gl,cl,ewx
         cmp     gl,0x7F
         bne     TestArus_BBDSErr
         mov     dl,0x7F
         mov     fwx,0x80000000
         mulsx   ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0x7F
         mov     gwx,0x80000000
         sdivsx  bh,el,gwx
         cmp     bh,0x00
         bne     TestArus_BBDSErr
         mov     fl,0x7F
         mov     ar,0x80000000
         sremsx  ch,fl,ar
         cmp     ch,0x7F
         bne     TestArus_BBDSErr
         mov     gl,0x7F
         mov     br,0xFFFFFFFF
         addsx   dh,gl,br
         cmp     dh,0x7E
         bne     TestArus_BBDSErr
         mov     ah,0x7F
         mov     cr,0xFFFFFFFF
         subsx   eh,ah,cr
         cmp     eh,0x80
         bne     TestArus_BBDSErr
         mov     bh,0x7F
         mov     dr,0xFFFFFFFF
         andsx   fh,bh,dr
         cmp     fh,0x7F
         bne     TestArus_BBDSErr
         mov     ch,0x7F
         mov     er,0xFFFFFFFF
         orsx    gh,ch,er
         cmp     gh,0xFF
         bne     TestArus_BBDSErr
         mov     dh,0x7F
         mov     fr,0xFFFFFFFF
         xorsx   al,dh,fr
         cmp     al,0x80
         bne     TestArus_BBDSErr
         mov     eh,0x7F
         mov     gr,0xFFFFFFFF
         mulsx   bl,eh,gr
         cmp     bl,0x81
         bne     TestArus_BBDSErr
         mov     fh,0x7F
         mov     awx,0xFFFFFFFF
         sdivsx  cl,fh,awx
         cmp     cl,0x81
         bne     TestArus_BBDSErr
         mov     gh,0x7F
         mov     bwx,0xFFFFFFFF
         sremsx  dl,gh,bwx
         cmp     dl,0x00
         bne     TestArus_BBDSErr
         mov     al,0x80
         mov     cwx,0x80000000
         addsx   el,al,cwx
         cmp     el,0x80
         bne     TestArus_BBDSErr
         mov     bl,0x80
         mov     dwx,0x80000000
         subsx   fl,bl,dwx
         cmp     fl,0x80
         bne     TestArus_BBDSErr
         mov     cl,0x80
         mov     ewx,0x80000000
         andsx   gl,cl,ewx
         cmp     gl,0x00
         bne     TestArus_BBDSErr
         mov     dl,0x80
         mov     fwx,0x80000000
         orsx    ah,dl,fwx
         cmp     ah,0x80
         bne     TestArus_BBDSErr
         mov     el,0x80
         mov     gwx,0x80000000
         xorsx   bh,el,gwx
         cmp     bh,0x80
         bne     TestArus_BBDSErr
         mov     fl,0x80
         mov     ar,0x80000000
         mulsx   ch,fl,ar
         cmp     ch,0x00
         bne     TestArus_BBDSErr
         mov     gl,0x80
         mov     br,0x80000000
         sdivsx  dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0x80
         mov     cr,0x80000000
         sremsx  eh,ah,cr
         cmp     eh,0x80
         bne     TestArus_BBDSErr
         mov     bh,0x80
         mov     dr,0xFFFFFFFF
         addsx   fh,bh,dr
         cmp     fh,0x7F
         bne     TestArus_BBDSErr
         mov     ch,0x80
         mov     er,0xFFFFFFFF
         subsx   gh,ch,er
         cmp     gh,0x81
         bne     TestArus_BBDSErr
         mov     dh,0x80
         mov     fr,0xFFFFFFFF
         andsx   al,dh,fr
         cmp     al,0x80
         bne     TestArus_BBDSErr
         mov     eh,0x80
         mov     gr,0xFFFFFFFF
         orsx    bl,eh,gr
         cmp     bl,0xFF
         bne     TestArus_BBDSErr
         mov     fh,0x80
         mov     awx,0xFFFFFFFF
         xorsx   cl,fh,awx
         cmp     cl,0x7F
         bne     TestArus_BBDSErr
         mov     gh,0x80
         mov     bwx,0xFFFFFFFF
         mulsx   dl,gh,bwx
         cmp     dl,0x80
         bne     TestArus_BBDSErr
         mov     al,0x80
         mov     cwx,0xFFFFFFFF
         sdivsx  el,al,cwx
         cmp     el,0x80
         bne     TestArus_BBDSErr
         mov     bl,0x80
         mov     dwx,0xFFFFFFFF
         sremsx  fl,bl,dwx
         cmp     fl,0x00
         bne     TestArus_BBDSErr
         mov     cl,0xFF
         mov     ewx,0xFFFFFFFF
         addsx   gl,cl,ewx
         cmp     gl,0xFE
         bne     TestArus_BBDSErr
         mov     dl,0xFF
         mov     fwx,0xFFFFFFFF
         subsx   ah,dl,fwx
         cmp     ah,0x00
         bne     TestArus_BBDSErr
         mov     el,0xFF
         mov     gwx,0xFFFFFFFF
         andsx   bh,el,gwx
         cmp     bh,0xFF
         bne     TestArus_BBDSErr
         mov     fl,0xFF
         mov     ar,0xFFFFFFFF
         orsx    ch,fl,ar
         cmp     ch,0xFF
         bne     TestArus_BBDSErr
         mov     gl,0xFF
         mov     br,0xFFFFFFFF
         xorsx   dh,gl,br
         cmp     dh,0x00
         bne     TestArus_BBDSErr
         mov     ah,0xFF
         mov     cr,0xFFFFFFFF
         mulsx   eh,ah,cr
         cmp     eh,0x01
         bne     TestArus_BBDSErr
         mov     bh,0xFF
         mov     dr,0xFFFFFFFF
         sdivsx  fh,bh,dr
         cmp     fh,0x01
         bne     TestArus_BBDSErr
         mov     ch,0xFF
         mov     er,0xFFFFFFFF
         sremsx  gh,ch,er
         cmp     gh,0x00
         bne     TestArus_BBDSErr
         bra     TestArus_BBDSRet
TestArus_BBDSErr:
         nop     
         trap    
         nop     
TestArus_BBDSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
