.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BWBZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BWBZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         mov     cl,0x00
         addzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x00
         subzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x00
         andzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x00
         orzx    ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x00
         xorzx   bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x00
         mulzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x00
         udivzx  dh,gx,bh
         cmp     dh,0xFF
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x00
         uremzx  eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x00
         shlzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x00
         shrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x00
         rolzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x00
         asrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0x01
         addzx   cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0x01
         subzx   dl,gw,bl
         cmp     dl,0xFF
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0x01
         andzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x01
         orzx    fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x01
         xorzx   gl,cx,el
         cmp     gl,0x01
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x01
         mulzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x01
         udivzx  bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x01
         uremzx  ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x01
         shlzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x01
         shrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x01
         rolzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x01
         asrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x07
         addzx   al,dw,fh
         cmp     al,0x07
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x07
         subzx   bl,ew,gh
         cmp     bl,0xF9
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0x07
         andzx   cl,fw,al
         cmp     cl,0x00
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0x07
         orzx    dl,gw,bl
         cmp     dl,0x07
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0x07
         xorzx   el,ax,cl
         cmp     el,0x07
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x07
         mulzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x07
         udivzx  gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x07
         uremzx  ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x07
         shlzx   bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x07
         shrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x07
         rolzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x07
         asrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x08
         addzx   fh,bw,dh
         cmp     fh,0x08
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x08
         subzx   gh,cw,eh
         cmp     gh,0xF8
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x08
         andzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x08
         orzx    bl,ew,gh
         cmp     bl,0x08
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0x08
         xorzx   cl,fw,al
         cmp     cl,0x08
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0x08
         mulzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0x08
         udivzx  el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x08
         uremzx  fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x00
         shlzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x00
         shrzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x00
         rolzx   bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x00
         asrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x09
         addzx   dh,gx,bh
         cmp     dh,0x09
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x09
         subzx   eh,aw,ch
         cmp     eh,0xF7
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x09
         andzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x09
         orzx    gh,cw,eh
         cmp     gh,0x09
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x09
         xorzx   al,dw,fh
         cmp     al,0x09
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x09
         mulzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0x09
         udivzx  cl,fw,al
         cmp     cl,0x00
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0x09
         uremzx  dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0x01
         shlzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x01
         shrzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x01
         rolzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x01
         asrzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x0F
         addzx   bh,ex,gl
         cmp     bh,0x0F
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x0F
         subzx   ch,fx,ah
         cmp     ch,0xF1
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x0F
         andzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x0F
         orzx    eh,aw,ch
         cmp     eh,0x0F
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x0F
         xorzx   fh,bw,dh
         cmp     fh,0x0F
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x0F
         mulzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x0F
         udivzx  al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x0F
         uremzx  bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0x07
         shlzx   cl,fw,al
         cmp     cl,0x00
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0x07
         shrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0x07
         rolzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x07
         asrzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x7F
         addzx   gl,cx,el
         cmp     gl,0x7F
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x7F
         subzx   ah,dx,fl
         cmp     ah,0x81
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x7F
         andzx   bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x7F
         orzx    ch,fx,ah
         cmp     ch,0x7F
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x7F
         xorzx   dh,gx,bh
         cmp     dh,0x7F
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x7F
         mulzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x7F
         udivzx  fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x7F
         uremzx  gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x07
         shlzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x07
         shrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0x07
         rolzx   cl,fw,al
         cmp     cl,0x00
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0x07
         asrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0x80
         addzx   el,ax,cl
         cmp     el,0x80
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0x80
         subzx   fl,bx,dl
         cmp     fl,0x80
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0x80
         andzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0x80
         orzx    ah,dx,fl
         cmp     ah,0x80
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0x80
         xorzx   bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0x80
         mulzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x80
         udivzx  dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x80
         uremzx  eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x00
         shlzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x00
         shrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x00
         rolzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0000
         mov     gh,0x00
         asrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0000
         mov     al,0xFF
         addzx   cl,fw,al
         cmp     cl,0xFF
         bne     TestArus_BWBZErr
         mov     gw,0x0000
         mov     bl,0xFF
         subzx   dl,gw,bl
         cmp     dl,0x01
         bne     TestArus_BWBZErr
         mov     ax,0x0000
         mov     cl,0xFF
         andzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0000
         mov     dl,0xFF
         orzx    fl,bx,dl
         cmp     fl,0xFF
         bne     TestArus_BWBZErr
         mov     cx,0x0000
         mov     el,0xFF
         xorzx   gl,cx,el
         cmp     gl,0xFF
         bne     TestArus_BWBZErr
         mov     dx,0x0000
         mov     fl,0xFF
         mulzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0000
         mov     gl,0xFF
         udivzx  bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0000
         mov     ah,0xFF
         uremzx  ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x07
         shlzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x07
         shrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x07
         rolzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x07
         asrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0x01
         addzx   al,dw,fh
         cmp     al,0x02
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0x01
         subzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0x01
         andzx   cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0x01
         orzx    dl,gw,bl
         cmp     dl,0x01
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0x01
         xorzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0x01
         mulzx   fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0x01
         udivzx  gl,cx,el
         cmp     gl,0x01
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0x01
         uremzx  ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x01
         shlzx   bh,ex,gl
         cmp     bh,0x02
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x01
         shrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x01
         rolzx   dh,gx,bh
         cmp     dh,0x02
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x01
         asrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0001
         mov     dh,0x07
         addzx   fh,bw,dh
         cmp     fh,0x08
         bne     TestArus_BWBZErr
         mov     cw,0x0001
         mov     eh,0x07
         subzx   gh,cw,eh
         cmp     gh,0xFA
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0x07
         andzx   al,dw,fh
         cmp     al,0x01
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0x07
         orzx    bl,ew,gh
         cmp     bl,0x07
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0x07
         xorzx   cl,fw,al
         cmp     cl,0x06
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0x07
         mulzx   dl,gw,bl
         cmp     dl,0x07
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0x07
         udivzx  el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0x07
         uremzx  fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0x07
         shlzx   gl,cx,el
         cmp     gl,0x80
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0x07
         shrzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x07
         rolzx   bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x07
         asrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x08
         addzx   dh,gx,bh
         cmp     dh,0x09
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x08
         subzx   eh,aw,ch
         cmp     eh,0xF9
         bne     TestArus_BWBZErr
         mov     bw,0x0001
         mov     dh,0x08
         andzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0001
         mov     eh,0x08
         orzx    gh,cw,eh
         cmp     gh,0x09
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0x08
         xorzx   al,dw,fh
         cmp     al,0x09
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0x08
         mulzx   bl,ew,gh
         cmp     bl,0x08
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0x08
         udivzx  cl,fw,al
         cmp     cl,0x00
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0x08
         uremzx  dl,gw,bl
         cmp     dl,0x01
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0x00
         shlzx   el,ax,cl
         cmp     el,0x01
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0x00
         shrzx   fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0x00
         rolzx   gl,cx,el
         cmp     gl,0x01
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0x00
         asrzx   ah,dx,fl
         cmp     ah,0x01
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x09
         addzx   bh,ex,gl
         cmp     bh,0x0A
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x09
         subzx   ch,fx,ah
         cmp     ch,0xF8
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x09
         andzx   dh,gx,bh
         cmp     dh,0x01
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x09
         orzx    eh,aw,ch
         cmp     eh,0x09
         bne     TestArus_BWBZErr
         mov     bw,0x0001
         mov     dh,0x09
         xorzx   fh,bw,dh
         cmp     fh,0x08
         bne     TestArus_BWBZErr
         mov     cw,0x0001
         mov     eh,0x09
         mulzx   gh,cw,eh
         cmp     gh,0x09
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0x09
         udivzx  al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0x09
         uremzx  bl,ew,gh
         cmp     bl,0x01
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0x01
         shlzx   cl,fw,al
         cmp     cl,0x02
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0x01
         shrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0x01
         rolzx   el,ax,cl
         cmp     el,0x02
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0x01
         asrzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0x0F
         addzx   gl,cx,el
         cmp     gl,0x10
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0x0F
         subzx   ah,dx,fl
         cmp     ah,0xF2
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x0F
         andzx   bh,ex,gl
         cmp     bh,0x01
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x0F
         orzx    ch,fx,ah
         cmp     ch,0x0F
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x0F
         xorzx   dh,gx,bh
         cmp     dh,0x0E
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x0F
         mulzx   eh,aw,ch
         cmp     eh,0x0F
         bne     TestArus_BWBZErr
         mov     bw,0x0001
         mov     dh,0x0F
         udivzx  fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0001
         mov     eh,0x0F
         uremzx  gh,cw,eh
         cmp     gh,0x01
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0x07
         shlzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0x07
         shrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0x07
         rolzx   cl,fw,al
         cmp     cl,0x80
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0x07
         asrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0x7F
         addzx   el,ax,cl
         cmp     el,0x80
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0x7F
         subzx   fl,bx,dl
         cmp     fl,0x82
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0x7F
         andzx   gl,cx,el
         cmp     gl,0x01
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0x7F
         orzx    ah,dx,fl
         cmp     ah,0x7F
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x7F
         xorzx   bh,ex,gl
         cmp     bh,0x7E
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x7F
         mulzx   ch,fx,ah
         cmp     ch,0x7F
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x7F
         udivzx  dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x7F
         uremzx  eh,aw,ch
         cmp     eh,0x01
         bne     TestArus_BWBZErr
         mov     bw,0x0001
         mov     dh,0x07
         shlzx   fh,bw,dh
         cmp     fh,0x80
         bne     TestArus_BWBZErr
         mov     cw,0x0001
         mov     eh,0x07
         shrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0x07
         rolzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0x07
         asrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0x80
         addzx   cl,fw,al
         cmp     cl,0x81
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0x80
         subzx   dl,gw,bl
         cmp     dl,0x81
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0x80
         andzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0x80
         orzx    fl,bx,dl
         cmp     fl,0x81
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0x80
         xorzx   gl,cx,el
         cmp     gl,0x81
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0x80
         mulzx   ah,dx,fl
         cmp     ah,0x80
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x80
         udivzx  bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x80
         uremzx  ch,fx,ah
         cmp     ch,0x01
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x00
         shlzx   dh,gx,bh
         cmp     dh,0x01
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x00
         shrzx   eh,aw,ch
         cmp     eh,0x01
         bne     TestArus_BWBZErr
         mov     bw,0x0001
         mov     dh,0x00
         rolzx   fh,bw,dh
         cmp     fh,0x01
         bne     TestArus_BWBZErr
         mov     cw,0x0001
         mov     eh,0x00
         asrzx   gh,cw,eh
         cmp     gh,0x01
         bne     TestArus_BWBZErr
         mov     dw,0x0001
         mov     fh,0xFF
         addzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0001
         mov     gh,0xFF
         subzx   bl,ew,gh
         cmp     bl,0x02
         bne     TestArus_BWBZErr
         mov     fw,0x0001
         mov     al,0xFF
         andzx   cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x0001
         mov     bl,0xFF
         orzx    dl,gw,bl
         cmp     dl,0xFF
         bne     TestArus_BWBZErr
         mov     ax,0x0001
         mov     cl,0xFF
         xorzx   el,ax,cl
         cmp     el,0xFE
         bne     TestArus_BWBZErr
         mov     bx,0x0001
         mov     dl,0xFF
         mulzx   fl,bx,dl
         cmp     fl,0xFF
         bne     TestArus_BWBZErr
         mov     cx,0x0001
         mov     el,0xFF
         udivzx  gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0001
         mov     fl,0xFF
         uremzx  ah,dx,fl
         cmp     ah,0x01
         bne     TestArus_BWBZErr
         mov     ex,0x0001
         mov     gl,0x07
         shlzx   bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x0001
         mov     ah,0x07
         shrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0001
         mov     bh,0x07
         rolzx   dh,gx,bh
         cmp     dh,0x80
         bne     TestArus_BWBZErr
         mov     aw,0x0001
         mov     ch,0x07
         asrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0008
         mov     dh,0x07
         addzx   fh,bw,dh
         cmp     fh,0x0F
         bne     TestArus_BWBZErr
         mov     cw,0x0008
         mov     eh,0x07
         subzx   gh,cw,eh
         cmp     gh,0x01
         bne     TestArus_BWBZErr
         mov     dw,0x0008
         mov     fh,0x07
         andzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0008
         mov     gh,0x07
         orzx    bl,ew,gh
         cmp     bl,0x0F
         bne     TestArus_BWBZErr
         mov     fw,0x0008
         mov     al,0x07
         xorzx   cl,fw,al
         cmp     cl,0x0F
         bne     TestArus_BWBZErr
         mov     gw,0x0008
         mov     bl,0x07
         mulzx   dl,gw,bl
         cmp     dl,0x38
         bne     TestArus_BWBZErr
         mov     ax,0x0008
         mov     cl,0x07
         udivzx  el,ax,cl
         cmp     el,0x01
         bne     TestArus_BWBZErr
         mov     bx,0x0008
         mov     dl,0x07
         uremzx  fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x0008
         mov     el,0x07
         shlzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0008
         mov     fl,0x07
         shrzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0008
         mov     gl,0x07
         rolzx   bh,ex,gl
         cmp     bh,0x04
         bne     TestArus_BWBZErr
         mov     fx,0x0008
         mov     ah,0x07
         asrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0008
         mov     bh,0x08
         addzx   dh,gx,bh
         cmp     dh,0x10
         bne     TestArus_BWBZErr
         mov     aw,0x0008
         mov     ch,0x08
         subzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0008
         mov     dh,0x08
         andzx   fh,bw,dh
         cmp     fh,0x08
         bne     TestArus_BWBZErr
         mov     cw,0x0008
         mov     eh,0x08
         orzx    gh,cw,eh
         cmp     gh,0x08
         bne     TestArus_BWBZErr
         mov     dw,0x0008
         mov     fh,0x08
         xorzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0008
         mov     gh,0x08
         mulzx   bl,ew,gh
         cmp     bl,0x40
         bne     TestArus_BWBZErr
         mov     fw,0x0008
         mov     al,0x08
         udivzx  cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x0008
         mov     bl,0x08
         uremzx  dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0008
         mov     cl,0x00
         shlzx   el,ax,cl
         cmp     el,0x08
         bne     TestArus_BWBZErr
         mov     bx,0x0008
         mov     dl,0x00
         shrzx   fl,bx,dl
         cmp     fl,0x08
         bne     TestArus_BWBZErr
         mov     cx,0x0008
         mov     el,0x00
         rolzx   gl,cx,el
         cmp     gl,0x08
         bne     TestArus_BWBZErr
         mov     dx,0x0008
         mov     fl,0x00
         asrzx   ah,dx,fl
         cmp     ah,0x08
         bne     TestArus_BWBZErr
         mov     ex,0x0008
         mov     gl,0x09
         addzx   bh,ex,gl
         cmp     bh,0x11
         bne     TestArus_BWBZErr
         mov     fx,0x0008
         mov     ah,0x09
         subzx   ch,fx,ah
         cmp     ch,0xFF
         bne     TestArus_BWBZErr
         mov     gx,0x0008
         mov     bh,0x09
         andzx   dh,gx,bh
         cmp     dh,0x08
         bne     TestArus_BWBZErr
         mov     aw,0x0008
         mov     ch,0x09
         orzx    eh,aw,ch
         cmp     eh,0x09
         bne     TestArus_BWBZErr
         mov     bw,0x0008
         mov     dh,0x09
         xorzx   fh,bw,dh
         cmp     fh,0x01
         bne     TestArus_BWBZErr
         mov     cw,0x0008
         mov     eh,0x09
         mulzx   gh,cw,eh
         cmp     gh,0x48
         bne     TestArus_BWBZErr
         mov     dw,0x0008
         mov     fh,0x09
         udivzx  al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0008
         mov     gh,0x09
         uremzx  bl,ew,gh
         cmp     bl,0x08
         bne     TestArus_BWBZErr
         mov     fw,0x0008
         mov     al,0x01
         shlzx   cl,fw,al
         cmp     cl,0x10
         bne     TestArus_BWBZErr
         mov     gw,0x0008
         mov     bl,0x01
         shrzx   dl,gw,bl
         cmp     dl,0x04
         bne     TestArus_BWBZErr
         mov     ax,0x0008
         mov     cl,0x01
         rolzx   el,ax,cl
         cmp     el,0x10
         bne     TestArus_BWBZErr
         mov     bx,0x0008
         mov     dl,0x01
         asrzx   fl,bx,dl
         cmp     fl,0x04
         bne     TestArus_BWBZErr
         mov     cx,0x0008
         mov     el,0x0F
         addzx   gl,cx,el
         cmp     gl,0x17
         bne     TestArus_BWBZErr
         mov     dx,0x0008
         mov     fl,0x0F
         subzx   ah,dx,fl
         cmp     ah,0xF9
         bne     TestArus_BWBZErr
         mov     ex,0x0008
         mov     gl,0x0F
         andzx   bh,ex,gl
         cmp     bh,0x08
         bne     TestArus_BWBZErr
         mov     fx,0x0008
         mov     ah,0x0F
         orzx    ch,fx,ah
         cmp     ch,0x0F
         bne     TestArus_BWBZErr
         mov     gx,0x0008
         mov     bh,0x0F
         xorzx   dh,gx,bh
         cmp     dh,0x07
         bne     TestArus_BWBZErr
         mov     aw,0x0008
         mov     ch,0x0F
         mulzx   eh,aw,ch
         cmp     eh,0x78
         bne     TestArus_BWBZErr
         mov     bw,0x0008
         mov     dh,0x0F
         udivzx  fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0008
         mov     eh,0x0F
         uremzx  gh,cw,eh
         cmp     gh,0x08
         bne     TestArus_BWBZErr
         mov     dw,0x0008
         mov     fh,0x07
         shlzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0008
         mov     gh,0x07
         shrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0008
         mov     al,0x07
         rolzx   cl,fw,al
         cmp     cl,0x04
         bne     TestArus_BWBZErr
         mov     gw,0x0008
         mov     bl,0x07
         asrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0008
         mov     cl,0x7F
         addzx   el,ax,cl
         cmp     el,0x87
         bne     TestArus_BWBZErr
         mov     bx,0x0008
         mov     dl,0x7F
         subzx   fl,bx,dl
         cmp     fl,0x89
         bne     TestArus_BWBZErr
         mov     cx,0x0008
         mov     el,0x7F
         andzx   gl,cx,el
         cmp     gl,0x08
         bne     TestArus_BWBZErr
         mov     dx,0x0008
         mov     fl,0x7F
         orzx    ah,dx,fl
         cmp     ah,0x7F
         bne     TestArus_BWBZErr
         mov     ex,0x0008
         mov     gl,0x7F
         xorzx   bh,ex,gl
         cmp     bh,0x77
         bne     TestArus_BWBZErr
         mov     fx,0x0008
         mov     ah,0x7F
         mulzx   ch,fx,ah
         cmp     ch,0xF8
         bne     TestArus_BWBZErr
         mov     gx,0x0008
         mov     bh,0x7F
         udivzx  dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0008
         mov     ch,0x7F
         uremzx  eh,aw,ch
         cmp     eh,0x08
         bne     TestArus_BWBZErr
         mov     bw,0x0008
         mov     dh,0x07
         shlzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0008
         mov     eh,0x07
         shrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0008
         mov     fh,0x07
         rolzx   al,dw,fh
         cmp     al,0x04
         bne     TestArus_BWBZErr
         mov     ew,0x0008
         mov     gh,0x07
         asrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0008
         mov     al,0x80
         addzx   cl,fw,al
         cmp     cl,0x88
         bne     TestArus_BWBZErr
         mov     gw,0x0008
         mov     bl,0x80
         subzx   dl,gw,bl
         cmp     dl,0x88
         bne     TestArus_BWBZErr
         mov     ax,0x0008
         mov     cl,0x80
         andzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0008
         mov     dl,0x80
         orzx    fl,bx,dl
         cmp     fl,0x88
         bne     TestArus_BWBZErr
         mov     cx,0x0008
         mov     el,0x80
         xorzx   gl,cx,el
         cmp     gl,0x88
         bne     TestArus_BWBZErr
         mov     dx,0x0008
         mov     fl,0x80
         mulzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0008
         mov     gl,0x80
         udivzx  bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0008
         mov     ah,0x80
         uremzx  ch,fx,ah
         cmp     ch,0x08
         bne     TestArus_BWBZErr
         mov     gx,0x0008
         mov     bh,0x00
         shlzx   dh,gx,bh
         cmp     dh,0x08
         bne     TestArus_BWBZErr
         mov     aw,0x0008
         mov     ch,0x00
         shrzx   eh,aw,ch
         cmp     eh,0x08
         bne     TestArus_BWBZErr
         mov     bw,0x0008
         mov     dh,0x00
         rolzx   fh,bw,dh
         cmp     fh,0x08
         bne     TestArus_BWBZErr
         mov     cw,0x0008
         mov     eh,0x00
         asrzx   gh,cw,eh
         cmp     gh,0x08
         bne     TestArus_BWBZErr
         mov     dw,0x0008
         mov     fh,0xFF
         addzx   al,dw,fh
         cmp     al,0x07
         bne     TestArus_BWBZErr
         mov     ew,0x0008
         mov     gh,0xFF
         subzx   bl,ew,gh
         cmp     bl,0x09
         bne     TestArus_BWBZErr
         mov     fw,0x0008
         mov     al,0xFF
         andzx   cl,fw,al
         cmp     cl,0x08
         bne     TestArus_BWBZErr
         mov     gw,0x0008
         mov     bl,0xFF
         orzx    dl,gw,bl
         cmp     dl,0xFF
         bne     TestArus_BWBZErr
         mov     ax,0x0008
         mov     cl,0xFF
         xorzx   el,ax,cl
         cmp     el,0xF7
         bne     TestArus_BWBZErr
         mov     bx,0x0008
         mov     dl,0xFF
         mulzx   fl,bx,dl
         cmp     fl,0xF8
         bne     TestArus_BWBZErr
         mov     cx,0x0008
         mov     el,0xFF
         udivzx  gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0008
         mov     fl,0xFF
         uremzx  ah,dx,fl
         cmp     ah,0x08
         bne     TestArus_BWBZErr
         mov     ex,0x0008
         mov     gl,0x07
         shlzx   bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0008
         mov     ah,0x07
         shrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x0008
         mov     bh,0x07
         rolzx   dh,gx,bh
         cmp     dh,0x04
         bne     TestArus_BWBZErr
         mov     aw,0x0008
         mov     ch,0x07
         asrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0009
         mov     dh,0x08
         addzx   fh,bw,dh
         cmp     fh,0x11
         bne     TestArus_BWBZErr
         mov     cw,0x0009
         mov     eh,0x08
         subzx   gh,cw,eh
         cmp     gh,0x01
         bne     TestArus_BWBZErr
         mov     dw,0x0009
         mov     fh,0x08
         andzx   al,dw,fh
         cmp     al,0x08
         bne     TestArus_BWBZErr
         mov     ew,0x0009
         mov     gh,0x08
         orzx    bl,ew,gh
         cmp     bl,0x09
         bne     TestArus_BWBZErr
         mov     fw,0x0009
         mov     al,0x08
         xorzx   cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x0009
         mov     bl,0x08
         mulzx   dl,gw,bl
         cmp     dl,0x48
         bne     TestArus_BWBZErr
         mov     ax,0x0009
         mov     cl,0x08
         udivzx  el,ax,cl
         cmp     el,0x01
         bne     TestArus_BWBZErr
         mov     bx,0x0009
         mov     dl,0x08
         uremzx  fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x0009
         mov     el,0x00
         shlzx   gl,cx,el
         cmp     gl,0x09
         bne     TestArus_BWBZErr
         mov     dx,0x0009
         mov     fl,0x00
         shrzx   ah,dx,fl
         cmp     ah,0x09
         bne     TestArus_BWBZErr
         mov     ex,0x0009
         mov     gl,0x00
         rolzx   bh,ex,gl
         cmp     bh,0x09
         bne     TestArus_BWBZErr
         mov     fx,0x0009
         mov     ah,0x00
         asrzx   ch,fx,ah
         cmp     ch,0x09
         bne     TestArus_BWBZErr
         mov     gx,0x0009
         mov     bh,0x09
         addzx   dh,gx,bh
         cmp     dh,0x12
         bne     TestArus_BWBZErr
         mov     aw,0x0009
         mov     ch,0x09
         subzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0009
         mov     dh,0x09
         andzx   fh,bw,dh
         cmp     fh,0x09
         bne     TestArus_BWBZErr
         mov     cw,0x0009
         mov     eh,0x09
         orzx    gh,cw,eh
         cmp     gh,0x09
         bne     TestArus_BWBZErr
         mov     dw,0x0009
         mov     fh,0x09
         xorzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0009
         mov     gh,0x09
         mulzx   bl,ew,gh
         cmp     bl,0x51
         bne     TestArus_BWBZErr
         mov     fw,0x0009
         mov     al,0x09
         udivzx  cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x0009
         mov     bl,0x09
         uremzx  dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0009
         mov     cl,0x01
         shlzx   el,ax,cl
         cmp     el,0x12
         bne     TestArus_BWBZErr
         mov     bx,0x0009
         mov     dl,0x01
         shrzx   fl,bx,dl
         cmp     fl,0x04
         bne     TestArus_BWBZErr
         mov     cx,0x0009
         mov     el,0x01
         rolzx   gl,cx,el
         cmp     gl,0x12
         bne     TestArus_BWBZErr
         mov     dx,0x0009
         mov     fl,0x01
         asrzx   ah,dx,fl
         cmp     ah,0x04
         bne     TestArus_BWBZErr
         mov     ex,0x0009
         mov     gl,0x0F
         addzx   bh,ex,gl
         cmp     bh,0x18
         bne     TestArus_BWBZErr
         mov     fx,0x0009
         mov     ah,0x0F
         subzx   ch,fx,ah
         cmp     ch,0xFA
         bne     TestArus_BWBZErr
         mov     gx,0x0009
         mov     bh,0x0F
         andzx   dh,gx,bh
         cmp     dh,0x09
         bne     TestArus_BWBZErr
         mov     aw,0x0009
         mov     ch,0x0F
         orzx    eh,aw,ch
         cmp     eh,0x0F
         bne     TestArus_BWBZErr
         mov     bw,0x0009
         mov     dh,0x0F
         xorzx   fh,bw,dh
         cmp     fh,0x06
         bne     TestArus_BWBZErr
         mov     cw,0x0009
         mov     eh,0x0F
         mulzx   gh,cw,eh
         cmp     gh,0x87
         bne     TestArus_BWBZErr
         mov     dw,0x0009
         mov     fh,0x0F
         udivzx  al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0009
         mov     gh,0x0F
         uremzx  bl,ew,gh
         cmp     bl,0x09
         bne     TestArus_BWBZErr
         mov     fw,0x0009
         mov     al,0x07
         shlzx   cl,fw,al
         cmp     cl,0x80
         bne     TestArus_BWBZErr
         mov     gw,0x0009
         mov     bl,0x07
         shrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0009
         mov     cl,0x07
         rolzx   el,ax,cl
         cmp     el,0x84
         bne     TestArus_BWBZErr
         mov     bx,0x0009
         mov     dl,0x07
         asrzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0009
         mov     el,0x7F
         addzx   gl,cx,el
         cmp     gl,0x88
         bne     TestArus_BWBZErr
         mov     dx,0x0009
         mov     fl,0x7F
         subzx   ah,dx,fl
         cmp     ah,0x8A
         bne     TestArus_BWBZErr
         mov     ex,0x0009
         mov     gl,0x7F
         andzx   bh,ex,gl
         cmp     bh,0x09
         bne     TestArus_BWBZErr
         mov     fx,0x0009
         mov     ah,0x7F
         orzx    ch,fx,ah
         cmp     ch,0x7F
         bne     TestArus_BWBZErr
         mov     gx,0x0009
         mov     bh,0x7F
         xorzx   dh,gx,bh
         cmp     dh,0x76
         bne     TestArus_BWBZErr
         mov     aw,0x0009
         mov     ch,0x7F
         mulzx   eh,aw,ch
         cmp     eh,0x77
         bne     TestArus_BWBZErr
         mov     bw,0x0009
         mov     dh,0x7F
         udivzx  fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0009
         mov     eh,0x7F
         uremzx  gh,cw,eh
         cmp     gh,0x09
         bne     TestArus_BWBZErr
         mov     dw,0x0009
         mov     fh,0x07
         shlzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x0009
         mov     gh,0x07
         shrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0009
         mov     al,0x07
         rolzx   cl,fw,al
         cmp     cl,0x84
         bne     TestArus_BWBZErr
         mov     gw,0x0009
         mov     bl,0x07
         asrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0009
         mov     cl,0x80
         addzx   el,ax,cl
         cmp     el,0x89
         bne     TestArus_BWBZErr
         mov     bx,0x0009
         mov     dl,0x80
         subzx   fl,bx,dl
         cmp     fl,0x89
         bne     TestArus_BWBZErr
         mov     cx,0x0009
         mov     el,0x80
         andzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0009
         mov     fl,0x80
         orzx    ah,dx,fl
         cmp     ah,0x89
         bne     TestArus_BWBZErr
         mov     ex,0x0009
         mov     gl,0x80
         xorzx   bh,ex,gl
         cmp     bh,0x89
         bne     TestArus_BWBZErr
         mov     fx,0x0009
         mov     ah,0x80
         mulzx   ch,fx,ah
         cmp     ch,0x80
         bne     TestArus_BWBZErr
         mov     gx,0x0009
         mov     bh,0x80
         udivzx  dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0009
         mov     ch,0x80
         uremzx  eh,aw,ch
         cmp     eh,0x09
         bne     TestArus_BWBZErr
         mov     bw,0x0009
         mov     dh,0x00
         shlzx   fh,bw,dh
         cmp     fh,0x09
         bne     TestArus_BWBZErr
         mov     cw,0x0009
         mov     eh,0x00
         shrzx   gh,cw,eh
         cmp     gh,0x09
         bne     TestArus_BWBZErr
         mov     dw,0x0009
         mov     fh,0x00
         rolzx   al,dw,fh
         cmp     al,0x09
         bne     TestArus_BWBZErr
         mov     ew,0x0009
         mov     gh,0x00
         asrzx   bl,ew,gh
         cmp     bl,0x09
         bne     TestArus_BWBZErr
         mov     fw,0x0009
         mov     al,0xFF
         addzx   cl,fw,al
         cmp     cl,0x08
         bne     TestArus_BWBZErr
         mov     gw,0x0009
         mov     bl,0xFF
         subzx   dl,gw,bl
         cmp     dl,0x0A
         bne     TestArus_BWBZErr
         mov     ax,0x0009
         mov     cl,0xFF
         andzx   el,ax,cl
         cmp     el,0x09
         bne     TestArus_BWBZErr
         mov     bx,0x0009
         mov     dl,0xFF
         orzx    fl,bx,dl
         cmp     fl,0xFF
         bne     TestArus_BWBZErr
         mov     cx,0x0009
         mov     el,0xFF
         xorzx   gl,cx,el
         cmp     gl,0xF6
         bne     TestArus_BWBZErr
         mov     dx,0x0009
         mov     fl,0xFF
         mulzx   ah,dx,fl
         cmp     ah,0xF7
         bne     TestArus_BWBZErr
         mov     ex,0x0009
         mov     gl,0xFF
         udivzx  bh,ex,gl
         cmp     bh,0x00
         bne     TestArus_BWBZErr
         mov     fx,0x0009
         mov     ah,0xFF
         uremzx  ch,fx,ah
         cmp     ch,0x09
         bne     TestArus_BWBZErr
         mov     gx,0x0009
         mov     bh,0x07
         shlzx   dh,gx,bh
         cmp     dh,0x80
         bne     TestArus_BWBZErr
         mov     aw,0x0009
         mov     ch,0x07
         shrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0009
         mov     dh,0x07
         rolzx   fh,bw,dh
         cmp     fh,0x84
         bne     TestArus_BWBZErr
         mov     cw,0x0009
         mov     eh,0x07
         asrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x007F
         mov     fh,0x09
         addzx   al,dw,fh
         cmp     al,0x88
         bne     TestArus_BWBZErr
         mov     ew,0x007F
         mov     gh,0x09
         subzx   bl,ew,gh
         cmp     bl,0x76
         bne     TestArus_BWBZErr
         mov     fw,0x007F
         mov     al,0x09
         andzx   cl,fw,al
         cmp     cl,0x09
         bne     TestArus_BWBZErr
         mov     gw,0x007F
         mov     bl,0x09
         orzx    dl,gw,bl
         cmp     dl,0x7F
         bne     TestArus_BWBZErr
         mov     ax,0x007F
         mov     cl,0x09
         xorzx   el,ax,cl
         cmp     el,0x76
         bne     TestArus_BWBZErr
         mov     bx,0x007F
         mov     dl,0x09
         mulzx   fl,bx,dl
         cmp     fl,0x77
         bne     TestArus_BWBZErr
         mov     cx,0x007F
         mov     el,0x09
         udivzx  gl,cx,el
         cmp     gl,0x0E
         bne     TestArus_BWBZErr
         mov     dx,0x007F
         mov     fl,0x09
         uremzx  ah,dx,fl
         cmp     ah,0x01
         bne     TestArus_BWBZErr
         mov     ex,0x007F
         mov     gl,0x01
         shlzx   bh,ex,gl
         cmp     bh,0xFE
         bne     TestArus_BWBZErr
         mov     fx,0x007F
         mov     ah,0x01
         shrzx   ch,fx,ah
         cmp     ch,0x3F
         bne     TestArus_BWBZErr
         mov     gx,0x007F
         mov     bh,0x01
         rolzx   dh,gx,bh
         cmp     dh,0xFE
         bne     TestArus_BWBZErr
         mov     aw,0x007F
         mov     ch,0x01
         asrzx   eh,aw,ch
         cmp     eh,0x3F
         bne     TestArus_BWBZErr
         mov     bw,0x007F
         mov     dh,0x0F
         addzx   fh,bw,dh
         cmp     fh,0x8E
         bne     TestArus_BWBZErr
         mov     cw,0x007F
         mov     eh,0x0F
         subzx   gh,cw,eh
         cmp     gh,0x70
         bne     TestArus_BWBZErr
         mov     dw,0x007F
         mov     fh,0x0F
         andzx   al,dw,fh
         cmp     al,0x0F
         bne     TestArus_BWBZErr
         mov     ew,0x007F
         mov     gh,0x0F
         orzx    bl,ew,gh
         cmp     bl,0x7F
         bne     TestArus_BWBZErr
         mov     fw,0x007F
         mov     al,0x0F
         xorzx   cl,fw,al
         cmp     cl,0x70
         bne     TestArus_BWBZErr
         mov     gw,0x007F
         mov     bl,0x0F
         mulzx   dl,gw,bl
         cmp     dl,0x71
         bne     TestArus_BWBZErr
         mov     ax,0x007F
         mov     cl,0x0F
         udivzx  el,ax,cl
         cmp     el,0x08
         bne     TestArus_BWBZErr
         mov     bx,0x007F
         mov     dl,0x0F
         uremzx  fl,bx,dl
         cmp     fl,0x07
         bne     TestArus_BWBZErr
         mov     cx,0x007F
         mov     el,0x07
         shlzx   gl,cx,el
         cmp     gl,0x80
         bne     TestArus_BWBZErr
         mov     dx,0x007F
         mov     fl,0x07
         shrzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x007F
         mov     gl,0x07
         rolzx   bh,ex,gl
         cmp     bh,0xBF
         bne     TestArus_BWBZErr
         mov     fx,0x007F
         mov     ah,0x07
         asrzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x007F
         mov     bh,0x7F
         addzx   dh,gx,bh
         cmp     dh,0xFE
         bne     TestArus_BWBZErr
         mov     aw,0x007F
         mov     ch,0x7F
         subzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x007F
         mov     dh,0x7F
         andzx   fh,bw,dh
         cmp     fh,0x7F
         bne     TestArus_BWBZErr
         mov     cw,0x007F
         mov     eh,0x7F
         orzx    gh,cw,eh
         cmp     gh,0x7F
         bne     TestArus_BWBZErr
         mov     dw,0x007F
         mov     fh,0x7F
         xorzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x007F
         mov     gh,0x7F
         mulzx   bl,ew,gh
         cmp     bl,0x01
         bne     TestArus_BWBZErr
         mov     fw,0x007F
         mov     al,0x7F
         udivzx  cl,fw,al
         cmp     cl,0x01
         bne     TestArus_BWBZErr
         mov     gw,0x007F
         mov     bl,0x7F
         uremzx  dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x007F
         mov     cl,0x07
         shlzx   el,ax,cl
         cmp     el,0x80
         bne     TestArus_BWBZErr
         mov     bx,0x007F
         mov     dl,0x07
         shrzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x007F
         mov     el,0x07
         rolzx   gl,cx,el
         cmp     gl,0xBF
         bne     TestArus_BWBZErr
         mov     dx,0x007F
         mov     fl,0x07
         asrzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x007F
         mov     gl,0x80
         addzx   bh,ex,gl
         cmp     bh,0xFF
         bne     TestArus_BWBZErr
         mov     fx,0x007F
         mov     ah,0x80
         subzx   ch,fx,ah
         cmp     ch,0xFF
         bne     TestArus_BWBZErr
         mov     gx,0x007F
         mov     bh,0x80
         andzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x007F
         mov     ch,0x80
         orzx    eh,aw,ch
         cmp     eh,0xFF
         bne     TestArus_BWBZErr
         mov     bw,0x007F
         mov     dh,0x80
         xorzx   fh,bw,dh
         cmp     fh,0xFF
         bne     TestArus_BWBZErr
         mov     cw,0x007F
         mov     eh,0x80
         mulzx   gh,cw,eh
         cmp     gh,0x80
         bne     TestArus_BWBZErr
         mov     dw,0x007F
         mov     fh,0x80
         udivzx  al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x007F
         mov     gh,0x80
         uremzx  bl,ew,gh
         cmp     bl,0x7F
         bne     TestArus_BWBZErr
         mov     fw,0x007F
         mov     al,0x00
         shlzx   cl,fw,al
         cmp     cl,0x7F
         bne     TestArus_BWBZErr
         mov     gw,0x007F
         mov     bl,0x00
         shrzx   dl,gw,bl
         cmp     dl,0x7F
         bne     TestArus_BWBZErr
         mov     ax,0x007F
         mov     cl,0x00
         rolzx   el,ax,cl
         cmp     el,0x7F
         bne     TestArus_BWBZErr
         mov     bx,0x007F
         mov     dl,0x00
         asrzx   fl,bx,dl
         cmp     fl,0x7F
         bne     TestArus_BWBZErr
         mov     cx,0x007F
         mov     el,0xFF
         addzx   gl,cx,el
         cmp     gl,0x7E
         bne     TestArus_BWBZErr
         mov     dx,0x007F
         mov     fl,0xFF
         subzx   ah,dx,fl
         cmp     ah,0x80
         bne     TestArus_BWBZErr
         mov     ex,0x007F
         mov     gl,0xFF
         andzx   bh,ex,gl
         cmp     bh,0x7F
         bne     TestArus_BWBZErr
         mov     fx,0x007F
         mov     ah,0xFF
         orzx    ch,fx,ah
         cmp     ch,0xFF
         bne     TestArus_BWBZErr
         mov     gx,0x007F
         mov     bh,0xFF
         xorzx   dh,gx,bh
         cmp     dh,0x80
         bne     TestArus_BWBZErr
         mov     aw,0x007F
         mov     ch,0xFF
         mulzx   eh,aw,ch
         cmp     eh,0x81
         bne     TestArus_BWBZErr
         mov     bw,0x007F
         mov     dh,0xFF
         udivzx  fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x007F
         mov     eh,0xFF
         uremzx  gh,cw,eh
         cmp     gh,0x7F
         bne     TestArus_BWBZErr
         mov     dw,0x007F
         mov     fh,0x07
         shlzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x007F
         mov     gh,0x07
         shrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x007F
         mov     al,0x07
         rolzx   cl,fw,al
         cmp     cl,0xBF
         bne     TestArus_BWBZErr
         mov     gw,0x007F
         mov     bl,0x07
         asrzx   dl,gw,bl
         cmp     dl,0x00
         bne     TestArus_BWBZErr
         mov     ax,0x0080
         mov     cl,0x0F
         addzx   el,ax,cl
         cmp     el,0x8F
         bne     TestArus_BWBZErr
         mov     bx,0x0080
         mov     dl,0x0F
         subzx   fl,bx,dl
         cmp     fl,0x71
         bne     TestArus_BWBZErr
         mov     cx,0x0080
         mov     el,0x0F
         andzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0080
         mov     fl,0x0F
         orzx    ah,dx,fl
         cmp     ah,0x8F
         bne     TestArus_BWBZErr
         mov     ex,0x0080
         mov     gl,0x0F
         xorzx   bh,ex,gl
         cmp     bh,0x8F
         bne     TestArus_BWBZErr
         mov     fx,0x0080
         mov     ah,0x0F
         mulzx   ch,fx,ah
         cmp     ch,0x80
         bne     TestArus_BWBZErr
         mov     gx,0x0080
         mov     bh,0x0F
         udivzx  dh,gx,bh
         cmp     dh,0x08
         bne     TestArus_BWBZErr
         mov     aw,0x0080
         mov     ch,0x0F
         uremzx  eh,aw,ch
         cmp     eh,0x08
         bne     TestArus_BWBZErr
         mov     bw,0x0080
         mov     dh,0x07
         shlzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0080
         mov     eh,0x07
         shrzx   gh,cw,eh
         cmp     gh,0x01
         bne     TestArus_BWBZErr
         mov     dw,0x0080
         mov     fh,0x07
         rolzx   al,dw,fh
         cmp     al,0x40
         bne     TestArus_BWBZErr
         mov     ew,0x0080
         mov     gh,0x07
         asrzx   bl,ew,gh
         cmp     bl,0x01
         bne     TestArus_BWBZErr
         mov     fw,0x0080
         mov     al,0x7F
         addzx   cl,fw,al
         cmp     cl,0xFF
         bne     TestArus_BWBZErr
         mov     gw,0x0080
         mov     bl,0x7F
         subzx   dl,gw,bl
         cmp     dl,0x01
         bne     TestArus_BWBZErr
         mov     ax,0x0080
         mov     cl,0x7F
         andzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0080
         mov     dl,0x7F
         orzx    fl,bx,dl
         cmp     fl,0xFF
         bne     TestArus_BWBZErr
         mov     cx,0x0080
         mov     el,0x7F
         xorzx   gl,cx,el
         cmp     gl,0xFF
         bne     TestArus_BWBZErr
         mov     dx,0x0080
         mov     fl,0x7F
         mulzx   ah,dx,fl
         cmp     ah,0x80
         bne     TestArus_BWBZErr
         mov     ex,0x0080
         mov     gl,0x7F
         udivzx  bh,ex,gl
         cmp     bh,0x01
         bne     TestArus_BWBZErr
         mov     fx,0x0080
         mov     ah,0x7F
         uremzx  ch,fx,ah
         cmp     ch,0x01
         bne     TestArus_BWBZErr
         mov     gx,0x0080
         mov     bh,0x07
         shlzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0080
         mov     ch,0x07
         shrzx   eh,aw,ch
         cmp     eh,0x01
         bne     TestArus_BWBZErr
         mov     bw,0x0080
         mov     dh,0x07
         rolzx   fh,bw,dh
         cmp     fh,0x40
         bne     TestArus_BWBZErr
         mov     cw,0x0080
         mov     eh,0x07
         asrzx   gh,cw,eh
         cmp     gh,0x01
         bne     TestArus_BWBZErr
         mov     dw,0x0080
         mov     fh,0x80
         addzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x0080
         mov     gh,0x80
         subzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x0080
         mov     al,0x80
         andzx   cl,fw,al
         cmp     cl,0x80
         bne     TestArus_BWBZErr
         mov     gw,0x0080
         mov     bl,0x80
         orzx    dl,gw,bl
         cmp     dl,0x80
         bne     TestArus_BWBZErr
         mov     ax,0x0080
         mov     cl,0x80
         xorzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0080
         mov     dl,0x80
         mulzx   fl,bx,dl
         cmp     fl,0x00
         bne     TestArus_BWBZErr
         mov     cx,0x0080
         mov     el,0x80
         udivzx  gl,cx,el
         cmp     gl,0x01
         bne     TestArus_BWBZErr
         mov     dx,0x0080
         mov     fl,0x80
         uremzx  ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x0080
         mov     gl,0x00
         shlzx   bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x0080
         mov     ah,0x00
         shrzx   ch,fx,ah
         cmp     ch,0x80
         bne     TestArus_BWBZErr
         mov     gx,0x0080
         mov     bh,0x00
         rolzx   dh,gx,bh
         cmp     dh,0x80
         bne     TestArus_BWBZErr
         mov     aw,0x0080
         mov     ch,0x00
         asrzx   eh,aw,ch
         cmp     eh,0x80
         bne     TestArus_BWBZErr
         mov     bw,0x0080
         mov     dh,0xFF
         addzx   fh,bw,dh
         cmp     fh,0x7F
         bne     TestArus_BWBZErr
         mov     cw,0x0080
         mov     eh,0xFF
         subzx   gh,cw,eh
         cmp     gh,0x81
         bne     TestArus_BWBZErr
         mov     dw,0x0080
         mov     fh,0xFF
         andzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x0080
         mov     gh,0xFF
         orzx    bl,ew,gh
         cmp     bl,0xFF
         bne     TestArus_BWBZErr
         mov     fw,0x0080
         mov     al,0xFF
         xorzx   cl,fw,al
         cmp     cl,0x7F
         bne     TestArus_BWBZErr
         mov     gw,0x0080
         mov     bl,0xFF
         mulzx   dl,gw,bl
         cmp     dl,0x80
         bne     TestArus_BWBZErr
         mov     ax,0x0080
         mov     cl,0xFF
         udivzx  el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x0080
         mov     dl,0xFF
         uremzx  fl,bx,dl
         cmp     fl,0x80
         bne     TestArus_BWBZErr
         mov     cx,0x0080
         mov     el,0x07
         shlzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x0080
         mov     fl,0x07
         shrzx   ah,dx,fl
         cmp     ah,0x01
         bne     TestArus_BWBZErr
         mov     ex,0x0080
         mov     gl,0x07
         rolzx   bh,ex,gl
         cmp     bh,0x40
         bne     TestArus_BWBZErr
         mov     fx,0x0080
         mov     ah,0x07
         asrzx   ch,fx,ah
         cmp     ch,0x01
         bne     TestArus_BWBZErr
         mov     gx,0x7FFF
         mov     bh,0x7F
         addzx   dh,gx,bh
         cmp     dh,0x7E
         bne     TestArus_BWBZErr
         mov     aw,0x7FFF
         mov     ch,0x7F
         subzx   eh,aw,ch
         cmp     eh,0x80
         bne     TestArus_BWBZErr
         mov     bw,0x7FFF
         mov     dh,0x7F
         andzx   fh,bw,dh
         cmp     fh,0x7F
         bne     TestArus_BWBZErr
         mov     cw,0x7FFF
         mov     eh,0x7F
         orzx    gh,cw,eh
         cmp     gh,0xFF
         bne     TestArus_BWBZErr
         mov     dw,0x7FFF
         mov     fh,0x7F
         xorzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x7FFF
         mov     gh,0x7F
         mulzx   bl,ew,gh
         cmp     bl,0x81
         bne     TestArus_BWBZErr
         mov     fw,0x7FFF
         mov     al,0x7F
         udivzx  cl,fw,al
         cmp     cl,0x02
         bne     TestArus_BWBZErr
         mov     gw,0x7FFF
         mov     bl,0x7F
         uremzx  dl,gw,bl
         cmp     dl,0x01
         bne     TestArus_BWBZErr
         mov     ax,0x00FF
         mov     cl,0x07
         shlzx   el,ax,cl
         cmp     el,0x80
         bne     TestArus_BWBZErr
         mov     bx,0x00FF
         mov     dl,0x07
         shrzx   fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0x00FF
         mov     el,0x07
         rolzx   gl,cx,el
         cmp     gl,0xFF
         bne     TestArus_BWBZErr
         mov     dx,0x7FFF
         mov     fl,0x07
         asrzx   ah,dx,fl
         cmp     ah,0xFF
         bne     TestArus_BWBZErr
         mov     ex,0x7FFF
         mov     gl,0x80
         addzx   bh,ex,gl
         cmp     bh,0x7F
         bne     TestArus_BWBZErr
         mov     fx,0x7FFF
         mov     ah,0x80
         subzx   ch,fx,ah
         cmp     ch,0x7F
         bne     TestArus_BWBZErr
         mov     gx,0x7FFF
         mov     bh,0x80
         andzx   dh,gx,bh
         cmp     dh,0x80
         bne     TestArus_BWBZErr
         mov     aw,0x7FFF
         mov     ch,0x80
         orzx    eh,aw,ch
         cmp     eh,0xFF
         bne     TestArus_BWBZErr
         mov     bw,0x7FFF
         mov     dh,0x80
         xorzx   fh,bw,dh
         cmp     fh,0x7F
         bne     TestArus_BWBZErr
         mov     cw,0x7FFF
         mov     eh,0x80
         mulzx   gh,cw,eh
         cmp     gh,0x80
         bne     TestArus_BWBZErr
         mov     dw,0x7FFF
         mov     fh,0x80
         udivzx  al,dw,fh
         cmp     al,0xFF
         bne     TestArus_BWBZErr
         mov     ew,0x7FFF
         mov     gh,0x80
         uremzx  bl,ew,gh
         cmp     bl,0x7F
         bne     TestArus_BWBZErr
         mov     fw,0x00FF
         mov     al,0x00
         shlzx   cl,fw,al
         cmp     cl,0xFF
         bne     TestArus_BWBZErr
         mov     gw,0x00FF
         mov     bl,0x00
         shrzx   dl,gw,bl
         cmp     dl,0xFF
         bne     TestArus_BWBZErr
         mov     ax,0x00FF
         mov     cl,0x00
         rolzx   el,ax,cl
         cmp     el,0xFF
         bne     TestArus_BWBZErr
         mov     bx,0x7FFF
         mov     dl,0x00
         asrzx   fl,bx,dl
         cmp     fl,0xFF
         bne     TestArus_BWBZErr
         mov     cx,0x7FFF
         mov     el,0xFF
         addzx   gl,cx,el
         cmp     gl,0xFE
         bne     TestArus_BWBZErr
         mov     dx,0x7FFF
         mov     fl,0xFF
         subzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x7FFF
         mov     gl,0xFF
         andzx   bh,ex,gl
         cmp     bh,0xFF
         bne     TestArus_BWBZErr
         mov     fx,0x7FFF
         mov     ah,0xFF
         orzx    ch,fx,ah
         cmp     ch,0xFF
         bne     TestArus_BWBZErr
         mov     gx,0x7FFF
         mov     bh,0xFF
         xorzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x7FFF
         mov     ch,0xFF
         mulzx   eh,aw,ch
         cmp     eh,0x01
         bne     TestArus_BWBZErr
         mov     bw,0x7FFF
         mov     dh,0xFF
         udivzx  fh,bw,dh
         cmp     fh,0x80
         bne     TestArus_BWBZErr
         mov     cw,0x7FFF
         mov     eh,0xFF
         uremzx  gh,cw,eh
         cmp     gh,0x7F
         bne     TestArus_BWBZErr
         mov     dw,0x00FF
         mov     fh,0x07
         shlzx   al,dw,fh
         cmp     al,0x80
         bne     TestArus_BWBZErr
         mov     ew,0x00FF
         mov     gh,0x07
         shrzx   bl,ew,gh
         cmp     bl,0x01
         bne     TestArus_BWBZErr
         mov     fw,0x00FF
         mov     al,0x07
         rolzx   cl,fw,al
         cmp     cl,0xFF
         bne     TestArus_BWBZErr
         mov     gw,0x7FFF
         mov     bl,0x07
         asrzx   dl,gw,bl
         cmp     dl,0xFF
         bne     TestArus_BWBZErr
         mov     ax,0x8000
         mov     cl,0x80
         addzx   el,ax,cl
         cmp     el,0x80
         bne     TestArus_BWBZErr
         mov     bx,0x8000
         mov     dl,0x80
         subzx   fl,bx,dl
         cmp     fl,0x80
         bne     TestArus_BWBZErr
         mov     cx,0x8000
         mov     el,0x80
         andzx   gl,cx,el
         cmp     gl,0x00
         bne     TestArus_BWBZErr
         mov     dx,0x8000
         mov     fl,0x80
         orzx    ah,dx,fl
         cmp     ah,0x80
         bne     TestArus_BWBZErr
         mov     ex,0x8000
         mov     gl,0x80
         xorzx   bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x8000
         mov     ah,0x80
         mulzx   ch,fx,ah
         cmp     ch,0x00
         bne     TestArus_BWBZErr
         mov     gx,0x8000
         mov     bh,0x80
         udivzx  dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x8000
         mov     ch,0x80
         uremzx  eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x00
         shlzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x0000
         mov     eh,0x00
         shrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0x0000
         mov     fh,0x00
         rolzx   al,dw,fh
         cmp     al,0x00
         bne     TestArus_BWBZErr
         mov     ew,0x8000
         mov     gh,0x00
         asrzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0x8000
         mov     al,0xFF
         addzx   cl,fw,al
         cmp     cl,0xFF
         bne     TestArus_BWBZErr
         mov     gw,0x8000
         mov     bl,0xFF
         subzx   dl,gw,bl
         cmp     dl,0x01
         bne     TestArus_BWBZErr
         mov     ax,0x8000
         mov     cl,0xFF
         andzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0x8000
         mov     dl,0xFF
         orzx    fl,bx,dl
         cmp     fl,0xFF
         bne     TestArus_BWBZErr
         mov     cx,0x8000
         mov     el,0xFF
         xorzx   gl,cx,el
         cmp     gl,0xFF
         bne     TestArus_BWBZErr
         mov     dx,0x8000
         mov     fl,0xFF
         mulzx   ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x8000
         mov     gl,0xFF
         udivzx  bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x8000
         mov     ah,0xFF
         uremzx  ch,fx,ah
         cmp     ch,0x80
         bne     TestArus_BWBZErr
         mov     gx,0x0000
         mov     bh,0x07
         shlzx   dh,gx,bh
         cmp     dh,0x00
         bne     TestArus_BWBZErr
         mov     aw,0x0000
         mov     ch,0x07
         shrzx   eh,aw,ch
         cmp     eh,0x00
         bne     TestArus_BWBZErr
         mov     bw,0x0000
         mov     dh,0x07
         rolzx   fh,bw,dh
         cmp     fh,0x00
         bne     TestArus_BWBZErr
         mov     cw,0x8000
         mov     eh,0x07
         asrzx   gh,cw,eh
         cmp     gh,0x00
         bne     TestArus_BWBZErr
         mov     dw,0xFFFF
         mov     fh,0xFF
         addzx   al,dw,fh
         cmp     al,0xFE
         bne     TestArus_BWBZErr
         mov     ew,0xFFFF
         mov     gh,0xFF
         subzx   bl,ew,gh
         cmp     bl,0x00
         bne     TestArus_BWBZErr
         mov     fw,0xFFFF
         mov     al,0xFF
         andzx   cl,fw,al
         cmp     cl,0xFF
         bne     TestArus_BWBZErr
         mov     gw,0xFFFF
         mov     bl,0xFF
         orzx    dl,gw,bl
         cmp     dl,0xFF
         bne     TestArus_BWBZErr
         mov     ax,0xFFFF
         mov     cl,0xFF
         xorzx   el,ax,cl
         cmp     el,0x00
         bne     TestArus_BWBZErr
         mov     bx,0xFFFF
         mov     dl,0xFF
         mulzx   fl,bx,dl
         cmp     fl,0x01
         bne     TestArus_BWBZErr
         mov     cx,0xFFFF
         mov     el,0xFF
         udivzx  gl,cx,el
         cmp     gl,0x01
         bne     TestArus_BWBZErr
         mov     dx,0xFFFF
         mov     fl,0xFF
         uremzx  ah,dx,fl
         cmp     ah,0x00
         bne     TestArus_BWBZErr
         mov     ex,0x00FF
         mov     gl,0x07
         shlzx   bh,ex,gl
         cmp     bh,0x80
         bne     TestArus_BWBZErr
         mov     fx,0x00FF
         mov     ah,0x07
         shrzx   ch,fx,ah
         cmp     ch,0x01
         bne     TestArus_BWBZErr
         mov     gx,0x00FF
         mov     bh,0x07
         rolzx   dh,gx,bh
         cmp     dh,0xFF
         bne     TestArus_BWBZErr
         mov     aw,0xFFFF
         mov     ch,0x07
         asrzx   eh,aw,ch
         cmp     eh,0xFF
         bne     TestArus_BWBZErr
         bra     TestArus_BWBZRet
TestArus_BWBZErr:
         nop     
         trap    
         nop     
TestArus_BWBZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
