.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WBBS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WBBS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cl,0x00
         addsx   ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x00
         mov     dl,0x00
         subsx   fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x00
         mov     el,0x00
         andsx   gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x00
         mov     fl,0x00
         orsx    aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x00
         mov     gl,0x00
         xorsx   bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x00
         mov     ah,0x00
         mulsx   cw,fl,ah
         cmp     cw,0x0000
         bne     TestArus_WBBSErr
         mov     gl,0x00
         mov     bh,0x00
         sdivsx  dw,gl,bh
         cmp     dw,0xFFFF
         bne     TestArus_WBBSErr
         mov     ah,0x00
         mov     ch,0x00
         sremsx  ew,ah,ch
         cmp     ew,0x0000
         bne     TestArus_WBBSErr
         mov     bh,0x00
         mov     dh,0x01
         addsx   fw,bh,dh
         cmp     fw,0x0001
         bne     TestArus_WBBSErr
         mov     ch,0x00
         mov     eh,0x01
         subsx   gw,ch,eh
         cmp     gw,0xFFFF
         bne     TestArus_WBBSErr
         mov     dh,0x00
         mov     fh,0x01
         andsx   ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x00
         mov     gh,0x01
         orsx    bx,eh,gh
         cmp     bx,0x0001
         bne     TestArus_WBBSErr
         mov     fh,0x00
         mov     al,0x01
         xorsx   cx,fh,al
         cmp     cx,0x0001
         bne     TestArus_WBBSErr
         mov     gh,0x00
         mov     bl,0x01
         mulsx   dx,gh,bl
         cmp     dx,0x0000
         bne     TestArus_WBBSErr
         mov     al,0x00
         mov     cl,0x01
         sdivsx  ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x00
         mov     dl,0x01
         sremsx  fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x00
         mov     el,0x07
         addsx   gx,cl,el
         cmp     gx,0x0007
         bne     TestArus_WBBSErr
         mov     dl,0x00
         mov     fl,0x07
         subsx   aw,dl,fl
         cmp     aw,0xFFF9
         bne     TestArus_WBBSErr
         mov     el,0x00
         mov     gl,0x07
         andsx   bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x00
         mov     ah,0x07
         orsx    cw,fl,ah
         cmp     cw,0x0007
         bne     TestArus_WBBSErr
         mov     gl,0x00
         mov     bh,0x07
         xorsx   dw,gl,bh
         cmp     dw,0x0007
         bne     TestArus_WBBSErr
         mov     ah,0x00
         mov     ch,0x07
         mulsx   ew,ah,ch
         cmp     ew,0x0000
         bne     TestArus_WBBSErr
         mov     bh,0x00
         mov     dh,0x07
         sdivsx  fw,bh,dh
         cmp     fw,0x0000
         bne     TestArus_WBBSErr
         mov     ch,0x00
         mov     eh,0x07
         sremsx  gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         mov     dh,0x00
         mov     fh,0x08
         addsx   ax,dh,fh
         cmp     ax,0x0008
         bne     TestArus_WBBSErr
         mov     eh,0x00
         mov     gh,0x08
         subsx   bx,eh,gh
         cmp     bx,0xFFF8
         bne     TestArus_WBBSErr
         mov     fh,0x00
         mov     al,0x08
         andsx   cx,fh,al
         cmp     cx,0x0000
         bne     TestArus_WBBSErr
         mov     gh,0x00
         mov     bl,0x08
         orsx    dx,gh,bl
         cmp     dx,0x0008
         bne     TestArus_WBBSErr
         mov     al,0x00
         mov     cl,0x08
         xorsx   ex,al,cl
         cmp     ex,0x0008
         bne     TestArus_WBBSErr
         mov     bl,0x00
         mov     dl,0x08
         mulsx   fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x00
         mov     el,0x08
         sdivsx  gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x00
         mov     fl,0x08
         sremsx  aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x00
         mov     gl,0x09
         addsx   bw,el,gl
         cmp     bw,0x0009
         bne     TestArus_WBBSErr
         mov     fl,0x00
         mov     ah,0x09
         subsx   cw,fl,ah
         cmp     cw,0xFFF7
         bne     TestArus_WBBSErr
         mov     gl,0x00
         mov     bh,0x09
         andsx   dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x00
         mov     ch,0x09
         orsx    ew,ah,ch
         cmp     ew,0x0009
         bne     TestArus_WBBSErr
         mov     bh,0x00
         mov     dh,0x09
         xorsx   fw,bh,dh
         cmp     fw,0x0009
         bne     TestArus_WBBSErr
         mov     ch,0x00
         mov     eh,0x09
         mulsx   gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         mov     dh,0x00
         mov     fh,0x09
         sdivsx  ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x00
         mov     gh,0x09
         sremsx  bx,eh,gh
         cmp     bx,0x0000
         bne     TestArus_WBBSErr
         mov     fh,0x00
         mov     al,0x0F
         addsx   cx,fh,al
         cmp     cx,0x000F
         bne     TestArus_WBBSErr
         mov     gh,0x00
         mov     bl,0x0F
         subsx   dx,gh,bl
         cmp     dx,0xFFF1
         bne     TestArus_WBBSErr
         mov     al,0x00
         mov     cl,0x0F
         andsx   ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x00
         mov     dl,0x0F
         orsx    fx,bl,dl
         cmp     fx,0x000F
         bne     TestArus_WBBSErr
         mov     cl,0x00
         mov     el,0x0F
         xorsx   gx,cl,el
         cmp     gx,0x000F
         bne     TestArus_WBBSErr
         mov     dl,0x00
         mov     fl,0x0F
         mulsx   aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x00
         mov     gl,0x0F
         sdivsx  bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x00
         mov     ah,0x0F
         sremsx  cw,fl,ah
         cmp     cw,0x0000
         bne     TestArus_WBBSErr
         mov     gl,0x00
         mov     bh,0x7F
         addsx   dw,gl,bh
         cmp     dw,0x007F
         bne     TestArus_WBBSErr
         mov     ah,0x00
         mov     ch,0x7F
         subsx   ew,ah,ch
         cmp     ew,0xFF81
         bne     TestArus_WBBSErr
         mov     bh,0x00
         mov     dh,0x7F
         andsx   fw,bh,dh
         cmp     fw,0x0000
         bne     TestArus_WBBSErr
         mov     ch,0x00
         mov     eh,0x7F
         orsx    gw,ch,eh
         cmp     gw,0x007F
         bne     TestArus_WBBSErr
         mov     dh,0x00
         mov     fh,0x7F
         xorsx   ax,dh,fh
         cmp     ax,0x007F
         bne     TestArus_WBBSErr
         mov     eh,0x00
         mov     gh,0x7F
         mulsx   bx,eh,gh
         cmp     bx,0x0000
         bne     TestArus_WBBSErr
         mov     fh,0x00
         mov     al,0x7F
         sdivsx  cx,fh,al
         cmp     cx,0x0000
         bne     TestArus_WBBSErr
         mov     gh,0x00
         mov     bl,0x7F
         sremsx  dx,gh,bl
         cmp     dx,0x0000
         bne     TestArus_WBBSErr
         mov     al,0x00
         mov     cl,0x80
         addsx   ex,al,cl
         cmp     ex,0xFF80
         bne     TestArus_WBBSErr
         mov     bl,0x00
         mov     dl,0x80
         subsx   fx,bl,dl
         cmp     fx,0x0080
         bne     TestArus_WBBSErr
         mov     cl,0x00
         mov     el,0x80
         andsx   gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x00
         mov     fl,0x80
         orsx    aw,dl,fl
         cmp     aw,0xFF80
         bne     TestArus_WBBSErr
         mov     el,0x00
         mov     gl,0x80
         xorsx   bw,el,gl
         cmp     bw,0xFF80
         bne     TestArus_WBBSErr
         mov     fl,0x00
         mov     ah,0x80
         mulsx   cw,fl,ah
         cmp     cw,0x0000
         bne     TestArus_WBBSErr
         mov     gl,0x00
         mov     bh,0x80
         sdivsx  dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x00
         mov     ch,0x80
         sremsx  ew,ah,ch
         cmp     ew,0x0000
         bne     TestArus_WBBSErr
         mov     bh,0x00
         mov     dh,0xFF
         addsx   fw,bh,dh
         cmp     fw,0xFFFF
         bne     TestArus_WBBSErr
         mov     ch,0x00
         mov     eh,0xFF
         subsx   gw,ch,eh
         cmp     gw,0x0001
         bne     TestArus_WBBSErr
         mov     dh,0x00
         mov     fh,0xFF
         andsx   ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x00
         mov     gh,0xFF
         orsx    bx,eh,gh
         cmp     bx,0xFFFF
         bne     TestArus_WBBSErr
         mov     fh,0x00
         mov     al,0xFF
         xorsx   cx,fh,al
         cmp     cx,0xFFFF
         bne     TestArus_WBBSErr
         mov     gh,0x00
         mov     bl,0xFF
         mulsx   dx,gh,bl
         cmp     dx,0x0000
         bne     TestArus_WBBSErr
         mov     al,0x00
         mov     cl,0xFF
         sdivsx  ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x00
         mov     dl,0xFF
         sremsx  fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x01
         mov     el,0x01
         addsx   gx,cl,el
         cmp     gx,0x0002
         bne     TestArus_WBBSErr
         mov     dl,0x01
         mov     fl,0x01
         subsx   aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x01
         mov     gl,0x01
         andsx   bw,el,gl
         cmp     bw,0x0001
         bne     TestArus_WBBSErr
         mov     fl,0x01
         mov     ah,0x01
         orsx    cw,fl,ah
         cmp     cw,0x0001
         bne     TestArus_WBBSErr
         mov     gl,0x01
         mov     bh,0x01
         xorsx   dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x01
         mov     ch,0x01
         mulsx   ew,ah,ch
         cmp     ew,0x0001
         bne     TestArus_WBBSErr
         mov     bh,0x01
         mov     dh,0x01
         sdivsx  fw,bh,dh
         cmp     fw,0x0001
         bne     TestArus_WBBSErr
         mov     ch,0x01
         mov     eh,0x01
         sremsx  gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         mov     dh,0x01
         mov     fh,0x07
         addsx   ax,dh,fh
         cmp     ax,0x0008
         bne     TestArus_WBBSErr
         mov     eh,0x01
         mov     gh,0x07
         subsx   bx,eh,gh
         cmp     bx,0xFFFA
         bne     TestArus_WBBSErr
         mov     fh,0x01
         mov     al,0x07
         andsx   cx,fh,al
         cmp     cx,0x0001
         bne     TestArus_WBBSErr
         mov     gh,0x01
         mov     bl,0x07
         orsx    dx,gh,bl
         cmp     dx,0x0007
         bne     TestArus_WBBSErr
         mov     al,0x01
         mov     cl,0x07
         xorsx   ex,al,cl
         cmp     ex,0x0006
         bne     TestArus_WBBSErr
         mov     bl,0x01
         mov     dl,0x07
         mulsx   fx,bl,dl
         cmp     fx,0x0007
         bne     TestArus_WBBSErr
         mov     cl,0x01
         mov     el,0x07
         sdivsx  gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x01
         mov     fl,0x07
         sremsx  aw,dl,fl
         cmp     aw,0x0001
         bne     TestArus_WBBSErr
         mov     el,0x01
         mov     gl,0x08
         addsx   bw,el,gl
         cmp     bw,0x0009
         bne     TestArus_WBBSErr
         mov     fl,0x01
         mov     ah,0x08
         subsx   cw,fl,ah
         cmp     cw,0xFFF9
         bne     TestArus_WBBSErr
         mov     gl,0x01
         mov     bh,0x08
         andsx   dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x01
         mov     ch,0x08
         orsx    ew,ah,ch
         cmp     ew,0x0009
         bne     TestArus_WBBSErr
         mov     bh,0x01
         mov     dh,0x08
         xorsx   fw,bh,dh
         cmp     fw,0x0009
         bne     TestArus_WBBSErr
         mov     ch,0x01
         mov     eh,0x08
         mulsx   gw,ch,eh
         cmp     gw,0x0008
         bne     TestArus_WBBSErr
         mov     dh,0x01
         mov     fh,0x08
         sdivsx  ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x01
         mov     gh,0x08
         sremsx  bx,eh,gh
         cmp     bx,0x0001
         bne     TestArus_WBBSErr
         mov     fh,0x01
         mov     al,0x09
         addsx   cx,fh,al
         cmp     cx,0x000A
         bne     TestArus_WBBSErr
         mov     gh,0x01
         mov     bl,0x09
         subsx   dx,gh,bl
         cmp     dx,0xFFF8
         bne     TestArus_WBBSErr
         mov     al,0x01
         mov     cl,0x09
         andsx   ex,al,cl
         cmp     ex,0x0001
         bne     TestArus_WBBSErr
         mov     bl,0x01
         mov     dl,0x09
         orsx    fx,bl,dl
         cmp     fx,0x0009
         bne     TestArus_WBBSErr
         mov     cl,0x01
         mov     el,0x09
         xorsx   gx,cl,el
         cmp     gx,0x0008
         bne     TestArus_WBBSErr
         mov     dl,0x01
         mov     fl,0x09
         mulsx   aw,dl,fl
         cmp     aw,0x0009
         bne     TestArus_WBBSErr
         mov     el,0x01
         mov     gl,0x09
         sdivsx  bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x01
         mov     ah,0x09
         sremsx  cw,fl,ah
         cmp     cw,0x0001
         bne     TestArus_WBBSErr
         mov     gl,0x01
         mov     bh,0x0F
         addsx   dw,gl,bh
         cmp     dw,0x0010
         bne     TestArus_WBBSErr
         mov     ah,0x01
         mov     ch,0x0F
         subsx   ew,ah,ch
         cmp     ew,0xFFF2
         bne     TestArus_WBBSErr
         mov     bh,0x01
         mov     dh,0x0F
         andsx   fw,bh,dh
         cmp     fw,0x0001
         bne     TestArus_WBBSErr
         mov     ch,0x01
         mov     eh,0x0F
         orsx    gw,ch,eh
         cmp     gw,0x000F
         bne     TestArus_WBBSErr
         mov     dh,0x01
         mov     fh,0x0F
         xorsx   ax,dh,fh
         cmp     ax,0x000E
         bne     TestArus_WBBSErr
         mov     eh,0x01
         mov     gh,0x0F
         mulsx   bx,eh,gh
         cmp     bx,0x000F
         bne     TestArus_WBBSErr
         mov     fh,0x01
         mov     al,0x0F
         sdivsx  cx,fh,al
         cmp     cx,0x0000
         bne     TestArus_WBBSErr
         mov     gh,0x01
         mov     bl,0x0F
         sremsx  dx,gh,bl
         cmp     dx,0x0001
         bne     TestArus_WBBSErr
         mov     al,0x01
         mov     cl,0x7F
         addsx   ex,al,cl
         cmp     ex,0x0080
         bne     TestArus_WBBSErr
         mov     bl,0x01
         mov     dl,0x7F
         subsx   fx,bl,dl
         cmp     fx,0xFF82
         bne     TestArus_WBBSErr
         mov     cl,0x01
         mov     el,0x7F
         andsx   gx,cl,el
         cmp     gx,0x0001
         bne     TestArus_WBBSErr
         mov     dl,0x01
         mov     fl,0x7F
         orsx    aw,dl,fl
         cmp     aw,0x007F
         bne     TestArus_WBBSErr
         mov     el,0x01
         mov     gl,0x7F
         xorsx   bw,el,gl
         cmp     bw,0x007E
         bne     TestArus_WBBSErr
         mov     fl,0x01
         mov     ah,0x7F
         mulsx   cw,fl,ah
         cmp     cw,0x007F
         bne     TestArus_WBBSErr
         mov     gl,0x01
         mov     bh,0x7F
         sdivsx  dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x01
         mov     ch,0x7F
         sremsx  ew,ah,ch
         cmp     ew,0x0001
         bne     TestArus_WBBSErr
         mov     bh,0x01
         mov     dh,0x80
         addsx   fw,bh,dh
         cmp     fw,0xFF81
         bne     TestArus_WBBSErr
         mov     ch,0x01
         mov     eh,0x80
         subsx   gw,ch,eh
         cmp     gw,0x0081
         bne     TestArus_WBBSErr
         mov     dh,0x01
         mov     fh,0x80
         andsx   ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x01
         mov     gh,0x80
         orsx    bx,eh,gh
         cmp     bx,0xFF81
         bne     TestArus_WBBSErr
         mov     fh,0x01
         mov     al,0x80
         xorsx   cx,fh,al
         cmp     cx,0xFF81
         bne     TestArus_WBBSErr
         mov     gh,0x01
         mov     bl,0x80
         mulsx   dx,gh,bl
         cmp     dx,0xFF80
         bne     TestArus_WBBSErr
         mov     al,0x01
         mov     cl,0x80
         sdivsx  ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x01
         mov     dl,0x80
         sremsx  fx,bl,dl
         cmp     fx,0x0001
         bne     TestArus_WBBSErr
         mov     cl,0x01
         mov     el,0xFF
         addsx   gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x01
         mov     fl,0xFF
         subsx   aw,dl,fl
         cmp     aw,0x0002
         bne     TestArus_WBBSErr
         mov     el,0x01
         mov     gl,0xFF
         andsx   bw,el,gl
         cmp     bw,0x0001
         bne     TestArus_WBBSErr
         mov     fl,0x01
         mov     ah,0xFF
         orsx    cw,fl,ah
         cmp     cw,0xFFFF
         bne     TestArus_WBBSErr
         mov     gl,0x01
         mov     bh,0xFF
         xorsx   dw,gl,bh
         cmp     dw,0xFFFE
         bne     TestArus_WBBSErr
         mov     ah,0x01
         mov     ch,0xFF
         mulsx   ew,ah,ch
         cmp     ew,0xFFFF
         bne     TestArus_WBBSErr
         mov     bh,0x01
         mov     dh,0xFF
         sdivsx  fw,bh,dh
         cmp     fw,0xFFFF
         bne     TestArus_WBBSErr
         mov     ch,0x01
         mov     eh,0xFF
         sremsx  gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         mov     dh,0x07
         mov     fh,0x07
         addsx   ax,dh,fh
         cmp     ax,0x000E
         bne     TestArus_WBBSErr
         mov     eh,0x07
         mov     gh,0x07
         subsx   bx,eh,gh
         cmp     bx,0x0000
         bne     TestArus_WBBSErr
         mov     fh,0x07
         mov     al,0x07
         andsx   cx,fh,al
         cmp     cx,0x0007
         bne     TestArus_WBBSErr
         mov     gh,0x07
         mov     bl,0x07
         orsx    dx,gh,bl
         cmp     dx,0x0007
         bne     TestArus_WBBSErr
         mov     al,0x07
         mov     cl,0x07
         xorsx   ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x07
         mov     dl,0x07
         mulsx   fx,bl,dl
         cmp     fx,0x0031
         bne     TestArus_WBBSErr
         mov     cl,0x07
         mov     el,0x07
         sdivsx  gx,cl,el
         cmp     gx,0x0001
         bne     TestArus_WBBSErr
         mov     dl,0x07
         mov     fl,0x07
         sremsx  aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x07
         mov     gl,0x08
         addsx   bw,el,gl
         cmp     bw,0x000F
         bne     TestArus_WBBSErr
         mov     fl,0x07
         mov     ah,0x08
         subsx   cw,fl,ah
         cmp     cw,0xFFFF
         bne     TestArus_WBBSErr
         mov     gl,0x07
         mov     bh,0x08
         andsx   dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x07
         mov     ch,0x08
         orsx    ew,ah,ch
         cmp     ew,0x000F
         bne     TestArus_WBBSErr
         mov     bh,0x07
         mov     dh,0x08
         xorsx   fw,bh,dh
         cmp     fw,0x000F
         bne     TestArus_WBBSErr
         mov     ch,0x07
         mov     eh,0x08
         mulsx   gw,ch,eh
         cmp     gw,0x0038
         bne     TestArus_WBBSErr
         mov     dh,0x07
         mov     fh,0x08
         sdivsx  ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x07
         mov     gh,0x08
         sremsx  bx,eh,gh
         cmp     bx,0x0007
         bne     TestArus_WBBSErr
         mov     fh,0x07
         mov     al,0x09
         addsx   cx,fh,al
         cmp     cx,0x0010
         bne     TestArus_WBBSErr
         mov     gh,0x07
         mov     bl,0x09
         subsx   dx,gh,bl
         cmp     dx,0xFFFE
         bne     TestArus_WBBSErr
         mov     al,0x07
         mov     cl,0x09
         andsx   ex,al,cl
         cmp     ex,0x0001
         bne     TestArus_WBBSErr
         mov     bl,0x07
         mov     dl,0x09
         orsx    fx,bl,dl
         cmp     fx,0x000F
         bne     TestArus_WBBSErr
         mov     cl,0x07
         mov     el,0x09
         xorsx   gx,cl,el
         cmp     gx,0x000E
         bne     TestArus_WBBSErr
         mov     dl,0x07
         mov     fl,0x09
         mulsx   aw,dl,fl
         cmp     aw,0x003F
         bne     TestArus_WBBSErr
         mov     el,0x07
         mov     gl,0x09
         sdivsx  bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x07
         mov     ah,0x09
         sremsx  cw,fl,ah
         cmp     cw,0x0007
         bne     TestArus_WBBSErr
         mov     gl,0x07
         mov     bh,0x0F
         addsx   dw,gl,bh
         cmp     dw,0x0016
         bne     TestArus_WBBSErr
         mov     ah,0x07
         mov     ch,0x0F
         subsx   ew,ah,ch
         cmp     ew,0xFFF8
         bne     TestArus_WBBSErr
         mov     bh,0x07
         mov     dh,0x0F
         andsx   fw,bh,dh
         cmp     fw,0x0007
         bne     TestArus_WBBSErr
         mov     ch,0x07
         mov     eh,0x0F
         orsx    gw,ch,eh
         cmp     gw,0x000F
         bne     TestArus_WBBSErr
         mov     dh,0x07
         mov     fh,0x0F
         xorsx   ax,dh,fh
         cmp     ax,0x0008
         bne     TestArus_WBBSErr
         mov     eh,0x07
         mov     gh,0x0F
         mulsx   bx,eh,gh
         cmp     bx,0x0069
         bne     TestArus_WBBSErr
         mov     fh,0x07
         mov     al,0x0F
         sdivsx  cx,fh,al
         cmp     cx,0x0000
         bne     TestArus_WBBSErr
         mov     gh,0x07
         mov     bl,0x0F
         sremsx  dx,gh,bl
         cmp     dx,0x0007
         bne     TestArus_WBBSErr
         mov     al,0x07
         mov     cl,0x7F
         addsx   ex,al,cl
         cmp     ex,0x0086
         bne     TestArus_WBBSErr
         mov     bl,0x07
         mov     dl,0x7F
         subsx   fx,bl,dl
         cmp     fx,0xFF88
         bne     TestArus_WBBSErr
         mov     cl,0x07
         mov     el,0x7F
         andsx   gx,cl,el
         cmp     gx,0x0007
         bne     TestArus_WBBSErr
         mov     dl,0x07
         mov     fl,0x7F
         orsx    aw,dl,fl
         cmp     aw,0x007F
         bne     TestArus_WBBSErr
         mov     el,0x07
         mov     gl,0x7F
         xorsx   bw,el,gl
         cmp     bw,0x0078
         bne     TestArus_WBBSErr
         mov     fl,0x07
         mov     ah,0x7F
         mulsx   cw,fl,ah
         cmp     cw,0x0379
         bne     TestArus_WBBSErr
         mov     gl,0x07
         mov     bh,0x7F
         sdivsx  dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x07
         mov     ch,0x7F
         sremsx  ew,ah,ch
         cmp     ew,0x0007
         bne     TestArus_WBBSErr
         mov     bh,0x07
         mov     dh,0x80
         addsx   fw,bh,dh
         cmp     fw,0xFF87
         bne     TestArus_WBBSErr
         mov     ch,0x07
         mov     eh,0x80
         subsx   gw,ch,eh
         cmp     gw,0x0087
         bne     TestArus_WBBSErr
         mov     dh,0x07
         mov     fh,0x80
         andsx   ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x07
         mov     gh,0x80
         orsx    bx,eh,gh
         cmp     bx,0xFF87
         bne     TestArus_WBBSErr
         mov     fh,0x07
         mov     al,0x80
         xorsx   cx,fh,al
         cmp     cx,0xFF87
         bne     TestArus_WBBSErr
         mov     gh,0x07
         mov     bl,0x80
         mulsx   dx,gh,bl
         cmp     dx,0xFC80
         bne     TestArus_WBBSErr
         mov     al,0x07
         mov     cl,0x80
         sdivsx  ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x07
         mov     dl,0x80
         sremsx  fx,bl,dl
         cmp     fx,0x0007
         bne     TestArus_WBBSErr
         mov     cl,0x07
         mov     el,0xFF
         addsx   gx,cl,el
         cmp     gx,0x0006
         bne     TestArus_WBBSErr
         mov     dl,0x07
         mov     fl,0xFF
         subsx   aw,dl,fl
         cmp     aw,0x0008
         bne     TestArus_WBBSErr
         mov     el,0x07
         mov     gl,0xFF
         andsx   bw,el,gl
         cmp     bw,0x0007
         bne     TestArus_WBBSErr
         mov     fl,0x07
         mov     ah,0xFF
         orsx    cw,fl,ah
         cmp     cw,0xFFFF
         bne     TestArus_WBBSErr
         mov     gl,0x07
         mov     bh,0xFF
         xorsx   dw,gl,bh
         cmp     dw,0xFFF8
         bne     TestArus_WBBSErr
         mov     ah,0x07
         mov     ch,0xFF
         mulsx   ew,ah,ch
         cmp     ew,0xFFF9
         bne     TestArus_WBBSErr
         mov     bh,0x07
         mov     dh,0xFF
         sdivsx  fw,bh,dh
         cmp     fw,0xFFF9
         bne     TestArus_WBBSErr
         mov     ch,0x07
         mov     eh,0xFF
         sremsx  gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         mov     dh,0x08
         mov     fh,0x08
         addsx   ax,dh,fh
         cmp     ax,0x0010
         bne     TestArus_WBBSErr
         mov     eh,0x08
         mov     gh,0x08
         subsx   bx,eh,gh
         cmp     bx,0x0000
         bne     TestArus_WBBSErr
         mov     fh,0x08
         mov     al,0x08
         andsx   cx,fh,al
         cmp     cx,0x0008
         bne     TestArus_WBBSErr
         mov     gh,0x08
         mov     bl,0x08
         orsx    dx,gh,bl
         cmp     dx,0x0008
         bne     TestArus_WBBSErr
         mov     al,0x08
         mov     cl,0x08
         xorsx   ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x08
         mov     dl,0x08
         mulsx   fx,bl,dl
         cmp     fx,0x0040
         bne     TestArus_WBBSErr
         mov     cl,0x08
         mov     el,0x08
         sdivsx  gx,cl,el
         cmp     gx,0x0001
         bne     TestArus_WBBSErr
         mov     dl,0x08
         mov     fl,0x08
         sremsx  aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x08
         mov     gl,0x09
         addsx   bw,el,gl
         cmp     bw,0x0011
         bne     TestArus_WBBSErr
         mov     fl,0x08
         mov     ah,0x09
         subsx   cw,fl,ah
         cmp     cw,0xFFFF
         bne     TestArus_WBBSErr
         mov     gl,0x08
         mov     bh,0x09
         andsx   dw,gl,bh
         cmp     dw,0x0008
         bne     TestArus_WBBSErr
         mov     ah,0x08
         mov     ch,0x09
         orsx    ew,ah,ch
         cmp     ew,0x0009
         bne     TestArus_WBBSErr
         mov     bh,0x08
         mov     dh,0x09
         xorsx   fw,bh,dh
         cmp     fw,0x0001
         bne     TestArus_WBBSErr
         mov     ch,0x08
         mov     eh,0x09
         mulsx   gw,ch,eh
         cmp     gw,0x0048
         bne     TestArus_WBBSErr
         mov     dh,0x08
         mov     fh,0x09
         sdivsx  ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x08
         mov     gh,0x09
         sremsx  bx,eh,gh
         cmp     bx,0x0008
         bne     TestArus_WBBSErr
         mov     fh,0x08
         mov     al,0x0F
         addsx   cx,fh,al
         cmp     cx,0x0017
         bne     TestArus_WBBSErr
         mov     gh,0x08
         mov     bl,0x0F
         subsx   dx,gh,bl
         cmp     dx,0xFFF9
         bne     TestArus_WBBSErr
         mov     al,0x08
         mov     cl,0x0F
         andsx   ex,al,cl
         cmp     ex,0x0008
         bne     TestArus_WBBSErr
         mov     bl,0x08
         mov     dl,0x0F
         orsx    fx,bl,dl
         cmp     fx,0x000F
         bne     TestArus_WBBSErr
         mov     cl,0x08
         mov     el,0x0F
         xorsx   gx,cl,el
         cmp     gx,0x0007
         bne     TestArus_WBBSErr
         mov     dl,0x08
         mov     fl,0x0F
         mulsx   aw,dl,fl
         cmp     aw,0x0078
         bne     TestArus_WBBSErr
         mov     el,0x08
         mov     gl,0x0F
         sdivsx  bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x08
         mov     ah,0x0F
         sremsx  cw,fl,ah
         cmp     cw,0x0008
         bne     TestArus_WBBSErr
         mov     gl,0x08
         mov     bh,0x7F
         addsx   dw,gl,bh
         cmp     dw,0x0087
         bne     TestArus_WBBSErr
         mov     ah,0x08
         mov     ch,0x7F
         subsx   ew,ah,ch
         cmp     ew,0xFF89
         bne     TestArus_WBBSErr
         mov     bh,0x08
         mov     dh,0x7F
         andsx   fw,bh,dh
         cmp     fw,0x0008
         bne     TestArus_WBBSErr
         mov     ch,0x08
         mov     eh,0x7F
         orsx    gw,ch,eh
         cmp     gw,0x007F
         bne     TestArus_WBBSErr
         mov     dh,0x08
         mov     fh,0x7F
         xorsx   ax,dh,fh
         cmp     ax,0x0077
         bne     TestArus_WBBSErr
         mov     eh,0x08
         mov     gh,0x7F
         mulsx   bx,eh,gh
         cmp     bx,0x03F8
         bne     TestArus_WBBSErr
         mov     fh,0x08
         mov     al,0x7F
         sdivsx  cx,fh,al
         cmp     cx,0x0000
         bne     TestArus_WBBSErr
         mov     gh,0x08
         mov     bl,0x7F
         sremsx  dx,gh,bl
         cmp     dx,0x0008
         bne     TestArus_WBBSErr
         mov     al,0x08
         mov     cl,0x80
         addsx   ex,al,cl
         cmp     ex,0xFF88
         bne     TestArus_WBBSErr
         mov     bl,0x08
         mov     dl,0x80
         subsx   fx,bl,dl
         cmp     fx,0x0088
         bne     TestArus_WBBSErr
         mov     cl,0x08
         mov     el,0x80
         andsx   gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x08
         mov     fl,0x80
         orsx    aw,dl,fl
         cmp     aw,0xFF88
         bne     TestArus_WBBSErr
         mov     el,0x08
         mov     gl,0x80
         xorsx   bw,el,gl
         cmp     bw,0xFF88
         bne     TestArus_WBBSErr
         mov     fl,0x08
         mov     ah,0x80
         mulsx   cw,fl,ah
         cmp     cw,0xFC00
         bne     TestArus_WBBSErr
         mov     gl,0x08
         mov     bh,0x80
         sdivsx  dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x08
         mov     ch,0x80
         sremsx  ew,ah,ch
         cmp     ew,0x0008
         bne     TestArus_WBBSErr
         mov     bh,0x08
         mov     dh,0xFF
         addsx   fw,bh,dh
         cmp     fw,0x0007
         bne     TestArus_WBBSErr
         mov     ch,0x08
         mov     eh,0xFF
         subsx   gw,ch,eh
         cmp     gw,0x0009
         bne     TestArus_WBBSErr
         mov     dh,0x08
         mov     fh,0xFF
         andsx   ax,dh,fh
         cmp     ax,0x0008
         bne     TestArus_WBBSErr
         mov     eh,0x08
         mov     gh,0xFF
         orsx    bx,eh,gh
         cmp     bx,0xFFFF
         bne     TestArus_WBBSErr
         mov     fh,0x08
         mov     al,0xFF
         xorsx   cx,fh,al
         cmp     cx,0xFFF7
         bne     TestArus_WBBSErr
         mov     gh,0x08
         mov     bl,0xFF
         mulsx   dx,gh,bl
         cmp     dx,0xFFF8
         bne     TestArus_WBBSErr
         mov     al,0x08
         mov     cl,0xFF
         sdivsx  ex,al,cl
         cmp     ex,0xFFF8
         bne     TestArus_WBBSErr
         mov     bl,0x08
         mov     dl,0xFF
         sremsx  fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x09
         mov     el,0x09
         addsx   gx,cl,el
         cmp     gx,0x0012
         bne     TestArus_WBBSErr
         mov     dl,0x09
         mov     fl,0x09
         subsx   aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x09
         mov     gl,0x09
         andsx   bw,el,gl
         cmp     bw,0x0009
         bne     TestArus_WBBSErr
         mov     fl,0x09
         mov     ah,0x09
         orsx    cw,fl,ah
         cmp     cw,0x0009
         bne     TestArus_WBBSErr
         mov     gl,0x09
         mov     bh,0x09
         xorsx   dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0x09
         mov     ch,0x09
         mulsx   ew,ah,ch
         cmp     ew,0x0051
         bne     TestArus_WBBSErr
         mov     bh,0x09
         mov     dh,0x09
         sdivsx  fw,bh,dh
         cmp     fw,0x0001
         bne     TestArus_WBBSErr
         mov     ch,0x09
         mov     eh,0x09
         sremsx  gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         mov     dh,0x09
         mov     fh,0x0F
         addsx   ax,dh,fh
         cmp     ax,0x0018
         bne     TestArus_WBBSErr
         mov     eh,0x09
         mov     gh,0x0F
         subsx   bx,eh,gh
         cmp     bx,0xFFFA
         bne     TestArus_WBBSErr
         mov     fh,0x09
         mov     al,0x0F
         andsx   cx,fh,al
         cmp     cx,0x0009
         bne     TestArus_WBBSErr
         mov     gh,0x09
         mov     bl,0x0F
         orsx    dx,gh,bl
         cmp     dx,0x000F
         bne     TestArus_WBBSErr
         mov     al,0x09
         mov     cl,0x0F
         xorsx   ex,al,cl
         cmp     ex,0x0006
         bne     TestArus_WBBSErr
         mov     bl,0x09
         mov     dl,0x0F
         mulsx   fx,bl,dl
         cmp     fx,0x0087
         bne     TestArus_WBBSErr
         mov     cl,0x09
         mov     el,0x0F
         sdivsx  gx,cl,el
         cmp     gx,0x0000
         bne     TestArus_WBBSErr
         mov     dl,0x09
         mov     fl,0x0F
         sremsx  aw,dl,fl
         cmp     aw,0x0009
         bne     TestArus_WBBSErr
         mov     el,0x09
         mov     gl,0x7F
         addsx   bw,el,gl
         cmp     bw,0x0088
         bne     TestArus_WBBSErr
         mov     fl,0x09
         mov     ah,0x7F
         subsx   cw,fl,ah
         cmp     cw,0xFF8A
         bne     TestArus_WBBSErr
         mov     gl,0x09
         mov     bh,0x7F
         andsx   dw,gl,bh
         cmp     dw,0x0009
         bne     TestArus_WBBSErr
         mov     ah,0x09
         mov     ch,0x7F
         orsx    ew,ah,ch
         cmp     ew,0x007F
         bne     TestArus_WBBSErr
         mov     bh,0x09
         mov     dh,0x7F
         xorsx   fw,bh,dh
         cmp     fw,0x0076
         bne     TestArus_WBBSErr
         mov     ch,0x09
         mov     eh,0x7F
         mulsx   gw,ch,eh
         cmp     gw,0x0477
         bne     TestArus_WBBSErr
         mov     dh,0x09
         mov     fh,0x7F
         sdivsx  ax,dh,fh
         cmp     ax,0x0000
         bne     TestArus_WBBSErr
         mov     eh,0x09
         mov     gh,0x7F
         sremsx  bx,eh,gh
         cmp     bx,0x0009
         bne     TestArus_WBBSErr
         mov     fh,0x09
         mov     al,0x80
         addsx   cx,fh,al
         cmp     cx,0xFF89
         bne     TestArus_WBBSErr
         mov     gh,0x09
         mov     bl,0x80
         subsx   dx,gh,bl
         cmp     dx,0x0089
         bne     TestArus_WBBSErr
         mov     al,0x09
         mov     cl,0x80
         andsx   ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x09
         mov     dl,0x80
         orsx    fx,bl,dl
         cmp     fx,0xFF89
         bne     TestArus_WBBSErr
         mov     cl,0x09
         mov     el,0x80
         xorsx   gx,cl,el
         cmp     gx,0xFF89
         bne     TestArus_WBBSErr
         mov     dl,0x09
         mov     fl,0x80
         mulsx   aw,dl,fl
         cmp     aw,0xFB80
         bne     TestArus_WBBSErr
         mov     el,0x09
         mov     gl,0x80
         sdivsx  bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x09
         mov     ah,0x80
         sremsx  cw,fl,ah
         cmp     cw,0x0009
         bne     TestArus_WBBSErr
         mov     gl,0x09
         mov     bh,0xFF
         addsx   dw,gl,bh
         cmp     dw,0x0008
         bne     TestArus_WBBSErr
         mov     ah,0x09
         mov     ch,0xFF
         subsx   ew,ah,ch
         cmp     ew,0x000A
         bne     TestArus_WBBSErr
         mov     bh,0x09
         mov     dh,0xFF
         andsx   fw,bh,dh
         cmp     fw,0x0009
         bne     TestArus_WBBSErr
         mov     ch,0x09
         mov     eh,0xFF
         orsx    gw,ch,eh
         cmp     gw,0xFFFF
         bne     TestArus_WBBSErr
         mov     dh,0x09
         mov     fh,0xFF
         xorsx   ax,dh,fh
         cmp     ax,0xFFF6
         bne     TestArus_WBBSErr
         mov     eh,0x09
         mov     gh,0xFF
         mulsx   bx,eh,gh
         cmp     bx,0xFFF7
         bne     TestArus_WBBSErr
         mov     fh,0x09
         mov     al,0xFF
         sdivsx  cx,fh,al
         cmp     cx,0xFFF7
         bne     TestArus_WBBSErr
         mov     gh,0x09
         mov     bl,0xFF
         sremsx  dx,gh,bl
         cmp     dx,0x0000
         bne     TestArus_WBBSErr
         mov     al,0x0F
         mov     cl,0x0F
         addsx   ex,al,cl
         cmp     ex,0x001E
         bne     TestArus_WBBSErr
         mov     bl,0x0F
         mov     dl,0x0F
         subsx   fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x0F
         mov     el,0x0F
         andsx   gx,cl,el
         cmp     gx,0x000F
         bne     TestArus_WBBSErr
         mov     dl,0x0F
         mov     fl,0x0F
         orsx    aw,dl,fl
         cmp     aw,0x000F
         bne     TestArus_WBBSErr
         mov     el,0x0F
         mov     gl,0x0F
         xorsx   bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x0F
         mov     ah,0x0F
         mulsx   cw,fl,ah
         cmp     cw,0x00E1
         bne     TestArus_WBBSErr
         mov     gl,0x0F
         mov     bh,0x0F
         sdivsx  dw,gl,bh
         cmp     dw,0x0001
         bne     TestArus_WBBSErr
         mov     ah,0x0F
         mov     ch,0x0F
         sremsx  ew,ah,ch
         cmp     ew,0x0000
         bne     TestArus_WBBSErr
         mov     bh,0x0F
         mov     dh,0x7F
         addsx   fw,bh,dh
         cmp     fw,0x008E
         bne     TestArus_WBBSErr
         mov     ch,0x0F
         mov     eh,0x7F
         subsx   gw,ch,eh
         cmp     gw,0xFF90
         bne     TestArus_WBBSErr
         mov     dh,0x0F
         mov     fh,0x7F
         andsx   ax,dh,fh
         cmp     ax,0x000F
         bne     TestArus_WBBSErr
         mov     eh,0x0F
         mov     gh,0x7F
         orsx    bx,eh,gh
         cmp     bx,0x007F
         bne     TestArus_WBBSErr
         mov     fh,0x0F
         mov     al,0x7F
         xorsx   cx,fh,al
         cmp     cx,0x0070
         bne     TestArus_WBBSErr
         mov     gh,0x0F
         mov     bl,0x7F
         mulsx   dx,gh,bl
         cmp     dx,0x0771
         bne     TestArus_WBBSErr
         mov     al,0x0F
         mov     cl,0x7F
         sdivsx  ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x0F
         mov     dl,0x7F
         sremsx  fx,bl,dl
         cmp     fx,0x000F
         bne     TestArus_WBBSErr
         mov     cl,0x0F
         mov     el,0x80
         addsx   gx,cl,el
         cmp     gx,0xFF8F
         bne     TestArus_WBBSErr
         mov     dl,0x0F
         mov     fl,0x80
         subsx   aw,dl,fl
         cmp     aw,0x008F
         bne     TestArus_WBBSErr
         mov     el,0x0F
         mov     gl,0x80
         andsx   bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x0F
         mov     ah,0x80
         orsx    cw,fl,ah
         cmp     cw,0xFF8F
         bne     TestArus_WBBSErr
         mov     gl,0x0F
         mov     bh,0x80
         xorsx   dw,gl,bh
         cmp     dw,0xFF8F
         bne     TestArus_WBBSErr
         mov     ah,0x0F
         mov     ch,0x80
         mulsx   ew,ah,ch
         cmp     ew,0xF880
         bne     TestArus_WBBSErr
         mov     bh,0x0F
         mov     dh,0x80
         sdivsx  fw,bh,dh
         cmp     fw,0x0000
         bne     TestArus_WBBSErr
         mov     ch,0x0F
         mov     eh,0x80
         sremsx  gw,ch,eh
         cmp     gw,0x000F
         bne     TestArus_WBBSErr
         mov     dh,0x0F
         mov     fh,0xFF
         addsx   ax,dh,fh
         cmp     ax,0x000E
         bne     TestArus_WBBSErr
         mov     eh,0x0F
         mov     gh,0xFF
         subsx   bx,eh,gh
         cmp     bx,0x0010
         bne     TestArus_WBBSErr
         mov     fh,0x0F
         mov     al,0xFF
         andsx   cx,fh,al
         cmp     cx,0x000F
         bne     TestArus_WBBSErr
         mov     gh,0x0F
         mov     bl,0xFF
         orsx    dx,gh,bl
         cmp     dx,0xFFFF
         bne     TestArus_WBBSErr
         mov     al,0x0F
         mov     cl,0xFF
         xorsx   ex,al,cl
         cmp     ex,0xFFF0
         bne     TestArus_WBBSErr
         mov     bl,0x0F
         mov     dl,0xFF
         mulsx   fx,bl,dl
         cmp     fx,0xFFF1
         bne     TestArus_WBBSErr
         mov     cl,0x0F
         mov     el,0xFF
         sdivsx  gx,cl,el
         cmp     gx,0xFFF1
         bne     TestArus_WBBSErr
         mov     dl,0x0F
         mov     fl,0xFF
         sremsx  aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0x7F
         mov     gl,0x7F
         addsx   bw,el,gl
         cmp     bw,0x00FE
         bne     TestArus_WBBSErr
         mov     fl,0x7F
         mov     ah,0x7F
         subsx   cw,fl,ah
         cmp     cw,0x0000
         bne     TestArus_WBBSErr
         mov     gl,0x7F
         mov     bh,0x7F
         andsx   dw,gl,bh
         cmp     dw,0x007F
         bne     TestArus_WBBSErr
         mov     ah,0x7F
         mov     ch,0x7F
         orsx    ew,ah,ch
         cmp     ew,0x007F
         bne     TestArus_WBBSErr
         mov     bh,0x7F
         mov     dh,0x7F
         xorsx   fw,bh,dh
         cmp     fw,0x0000
         bne     TestArus_WBBSErr
         mov     ch,0x7F
         mov     eh,0x7F
         mulsx   gw,ch,eh
         cmp     gw,0x3F01
         bne     TestArus_WBBSErr
         mov     dh,0x7F
         mov     fh,0x7F
         sdivsx  ax,dh,fh
         cmp     ax,0x0001
         bne     TestArus_WBBSErr
         mov     eh,0x7F
         mov     gh,0x7F
         sremsx  bx,eh,gh
         cmp     bx,0x0000
         bne     TestArus_WBBSErr
         mov     fh,0x7F
         mov     al,0x80
         addsx   cx,fh,al
         cmp     cx,0xFFFF
         bne     TestArus_WBBSErr
         mov     gh,0x7F
         mov     bl,0x80
         subsx   dx,gh,bl
         cmp     dx,0x00FF
         bne     TestArus_WBBSErr
         mov     al,0x7F
         mov     cl,0x80
         andsx   ex,al,cl
         cmp     ex,0x0000
         bne     TestArus_WBBSErr
         mov     bl,0x7F
         mov     dl,0x80
         orsx    fx,bl,dl
         cmp     fx,0xFFFF
         bne     TestArus_WBBSErr
         mov     cl,0x7F
         mov     el,0x80
         xorsx   gx,cl,el
         cmp     gx,0xFFFF
         bne     TestArus_WBBSErr
         mov     dl,0x7F
         mov     fl,0x80
         mulsx   aw,dl,fl
         cmp     aw,0xC080
         bne     TestArus_WBBSErr
         mov     el,0x7F
         mov     gl,0x80
         sdivsx  bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x7F
         mov     ah,0x80
         sremsx  cw,fl,ah
         cmp     cw,0x007F
         bne     TestArus_WBBSErr
         mov     gl,0x7F
         mov     bh,0xFF
         addsx   dw,gl,bh
         cmp     dw,0x007E
         bne     TestArus_WBBSErr
         mov     ah,0x7F
         mov     ch,0xFF
         subsx   ew,ah,ch
         cmp     ew,0x0080
         bne     TestArus_WBBSErr
         mov     bh,0x7F
         mov     dh,0xFF
         andsx   fw,bh,dh
         cmp     fw,0x007F
         bne     TestArus_WBBSErr
         mov     ch,0x7F
         mov     eh,0xFF
         orsx    gw,ch,eh
         cmp     gw,0xFFFF
         bne     TestArus_WBBSErr
         mov     dh,0x7F
         mov     fh,0xFF
         xorsx   ax,dh,fh
         cmp     ax,0xFF80
         bne     TestArus_WBBSErr
         mov     eh,0x7F
         mov     gh,0xFF
         mulsx   bx,eh,gh
         cmp     bx,0xFF81
         bne     TestArus_WBBSErr
         mov     fh,0x7F
         mov     al,0xFF
         sdivsx  cx,fh,al
         cmp     cx,0xFF81
         bne     TestArus_WBBSErr
         mov     gh,0x7F
         mov     bl,0xFF
         sremsx  dx,gh,bl
         cmp     dx,0x0000
         bne     TestArus_WBBSErr
         mov     al,0x80
         mov     cl,0x80
         addsx   ex,al,cl
         cmp     ex,0xFF00
         bne     TestArus_WBBSErr
         mov     bl,0x80
         mov     dl,0x80
         subsx   fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0x80
         mov     el,0x80
         andsx   gx,cl,el
         cmp     gx,0xFF80
         bne     TestArus_WBBSErr
         mov     dl,0x80
         mov     fl,0x80
         orsx    aw,dl,fl
         cmp     aw,0xFF80
         bne     TestArus_WBBSErr
         mov     el,0x80
         mov     gl,0x80
         xorsx   bw,el,gl
         cmp     bw,0x0000
         bne     TestArus_WBBSErr
         mov     fl,0x80
         mov     ah,0x80
         mulsx   cw,fl,ah
         cmp     cw,0x4000
         bne     TestArus_WBBSErr
         mov     gl,0x80
         mov     bh,0x80
         sdivsx  dw,gl,bh
         cmp     dw,0x0001
         bne     TestArus_WBBSErr
         mov     ah,0x80
         mov     ch,0x80
         sremsx  ew,ah,ch
         cmp     ew,0x0000
         bne     TestArus_WBBSErr
         mov     bh,0x80
         mov     dh,0xFF
         addsx   fw,bh,dh
         cmp     fw,0xFF7F
         bne     TestArus_WBBSErr
         mov     ch,0x80
         mov     eh,0xFF
         subsx   gw,ch,eh
         cmp     gw,0xFF81
         bne     TestArus_WBBSErr
         mov     dh,0x80
         mov     fh,0xFF
         andsx   ax,dh,fh
         cmp     ax,0xFF80
         bne     TestArus_WBBSErr
         mov     eh,0x80
         mov     gh,0xFF
         orsx    bx,eh,gh
         cmp     bx,0xFFFF
         bne     TestArus_WBBSErr
         mov     fh,0x80
         mov     al,0xFF
         xorsx   cx,fh,al
         cmp     cx,0x007F
         bne     TestArus_WBBSErr
         mov     gh,0x80
         mov     bl,0xFF
         mulsx   dx,gh,bl
         cmp     dx,0x0080
         bne     TestArus_WBBSErr
         mov     al,0x80
         mov     cl,0xFF
         sdivsx  ex,al,cl
         cmp     ex,0x0080
         bne     TestArus_WBBSErr
         mov     bl,0x80
         mov     dl,0xFF
         sremsx  fx,bl,dl
         cmp     fx,0x0000
         bne     TestArus_WBBSErr
         mov     cl,0xFF
         mov     el,0xFF
         addsx   gx,cl,el
         cmp     gx,0xFFFE
         bne     TestArus_WBBSErr
         mov     dl,0xFF
         mov     fl,0xFF
         subsx   aw,dl,fl
         cmp     aw,0x0000
         bne     TestArus_WBBSErr
         mov     el,0xFF
         mov     gl,0xFF
         andsx   bw,el,gl
         cmp     bw,0xFFFF
         bne     TestArus_WBBSErr
         mov     fl,0xFF
         mov     ah,0xFF
         orsx    cw,fl,ah
         cmp     cw,0xFFFF
         bne     TestArus_WBBSErr
         mov     gl,0xFF
         mov     bh,0xFF
         xorsx   dw,gl,bh
         cmp     dw,0x0000
         bne     TestArus_WBBSErr
         mov     ah,0xFF
         mov     ch,0xFF
         mulsx   ew,ah,ch
         cmp     ew,0x0001
         bne     TestArus_WBBSErr
         mov     bh,0xFF
         mov     dh,0xFF
         sdivsx  fw,bh,dh
         cmp     fw,0x0001
         bne     TestArus_WBBSErr
         mov     ch,0xFF
         mov     eh,0xFF
         sremsx  gw,ch,eh
         cmp     gw,0x0000
         bne     TestArus_WBBSErr
         bra     TestArus_WBBSRet
TestArus_WBBSErr:
         nop     
         trap    
         nop     
TestArus_WBBSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
