.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WDBS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WDBS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     awx,0x00000000
         mov     cl,0x00
         addsx   ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x00000000
         mov     dl,0x00
         subsx   fx,bwx,dl
         cmp     fx,0x0000
         bne     TestArus_WDBSErr
         mov     cwx,0x00000000
         mov     el,0x00
         andsx   gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00000000
         mov     fl,0x00
         orsx    aw,dwx,fl
         cmp     aw,0x0000
         bne     TestArus_WDBSErr
         mov     ewx,0x00000000
         mov     gl,0x00
         xorsx   bw,ewx,gl
         cmp     bw,0x0000
         bne     TestArus_WDBSErr
         mov     fwx,0x00000000
         mov     ah,0x00
         mulsx   cw,fwx,ah
         cmp     cw,0x0000
         bne     TestArus_WDBSErr
         mov     gwx,0x00000000
         mov     bh,0x00
         sdivsx  dw,gwx,bh
         cmp     dw,0xFFFF
         bne     TestArus_WDBSErr
         mov     ar,0x00000000
         mov     ch,0x00
         sremsx  ew,ar,ch
         cmp     ew,0x0000
         bne     TestArus_WDBSErr
         mov     br,0x00000000
         mov     dh,0x01
         addsx   fw,br,dh
         cmp     fw,0x0001
         bne     TestArus_WDBSErr
         mov     cr,0x00000000
         mov     eh,0x01
         subsx   gw,cr,eh
         cmp     gw,0xFFFF
         bne     TestArus_WDBSErr
         mov     dr,0x00000000
         mov     fh,0x01
         andsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00000000
         mov     gh,0x01
         orsx    bx,er,gh
         cmp     bx,0x0001
         bne     TestArus_WDBSErr
         mov     fr,0x00000000
         mov     al,0x01
         xorsx   cx,fr,al
         cmp     cx,0x0001
         bne     TestArus_WDBSErr
         mov     gr,0x00000000
         mov     bl,0x01
         mulsx   dx,gr,bl
         cmp     dx,0x0000
         bne     TestArus_WDBSErr
         mov     awx,0x00000000
         mov     cl,0x01
         sdivsx  ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x00000000
         mov     dl,0x01
         sremsx  fx,bwx,dl
         cmp     fx,0x0000
         bne     TestArus_WDBSErr
         mov     cwx,0x00000000
         mov     el,0x07
         addsx   gx,cwx,el
         cmp     gx,0x0007
         bne     TestArus_WDBSErr
         mov     dwx,0x00000000
         mov     fl,0x07
         subsx   aw,dwx,fl
         cmp     aw,0xFFF9
         bne     TestArus_WDBSErr
         mov     ewx,0x00000000
         mov     gl,0x07
         andsx   bw,ewx,gl
         cmp     bw,0x0000
         bne     TestArus_WDBSErr
         mov     fwx,0x00000000
         mov     ah,0x07
         orsx    cw,fwx,ah
         cmp     cw,0x0007
         bne     TestArus_WDBSErr
         mov     gwx,0x00000000
         mov     bh,0x07
         xorsx   dw,gwx,bh
         cmp     dw,0x0007
         bne     TestArus_WDBSErr
         mov     ar,0x00000000
         mov     ch,0x07
         mulsx   ew,ar,ch
         cmp     ew,0x0000
         bne     TestArus_WDBSErr
         mov     br,0x00000000
         mov     dh,0x07
         sdivsx  fw,br,dh
         cmp     fw,0x0000
         bne     TestArus_WDBSErr
         mov     cr,0x00000000
         mov     eh,0x07
         sremsx  gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         mov     dr,0x00000000
         mov     fh,0x08
         addsx   ax,dr,fh
         cmp     ax,0x0008
         bne     TestArus_WDBSErr
         mov     er,0x00000000
         mov     gh,0x08
         subsx   bx,er,gh
         cmp     bx,0xFFF8
         bne     TestArus_WDBSErr
         mov     fr,0x00000000
         mov     al,0x08
         andsx   cx,fr,al
         cmp     cx,0x0000
         bne     TestArus_WDBSErr
         mov     gr,0x00000000
         mov     bl,0x08
         orsx    dx,gr,bl
         cmp     dx,0x0008
         bne     TestArus_WDBSErr
         mov     awx,0x00000000
         mov     cl,0x08
         xorsx   ex,awx,cl
         cmp     ex,0x0008
         bne     TestArus_WDBSErr
         mov     bwx,0x00000000
         mov     dl,0x08
         mulsx   fx,bwx,dl
         cmp     fx,0x0000
         bne     TestArus_WDBSErr
         mov     cwx,0x00000000
         mov     el,0x08
         sdivsx  gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00000000
         mov     fl,0x08
         sremsx  aw,dwx,fl
         cmp     aw,0x0000
         bne     TestArus_WDBSErr
         mov     ewx,0x00000000
         mov     gl,0x09
         addsx   bw,ewx,gl
         cmp     bw,0x0009
         bne     TestArus_WDBSErr
         mov     fwx,0x00000000
         mov     ah,0x09
         subsx   cw,fwx,ah
         cmp     cw,0xFFF7
         bne     TestArus_WDBSErr
         mov     gwx,0x00000000
         mov     bh,0x09
         andsx   dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000000
         mov     ch,0x09
         orsx    ew,ar,ch
         cmp     ew,0x0009
         bne     TestArus_WDBSErr
         mov     br,0x00000000
         mov     dh,0x09
         xorsx   fw,br,dh
         cmp     fw,0x0009
         bne     TestArus_WDBSErr
         mov     cr,0x00000000
         mov     eh,0x09
         mulsx   gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         mov     dr,0x00000000
         mov     fh,0x09
         sdivsx  ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00000000
         mov     gh,0x09
         sremsx  bx,er,gh
         cmp     bx,0x0000
         bne     TestArus_WDBSErr
         mov     fr,0x00000000
         mov     al,0x0F
         addsx   cx,fr,al
         cmp     cx,0x000F
         bne     TestArus_WDBSErr
         mov     gr,0x00000000
         mov     bl,0x0F
         subsx   dx,gr,bl
         cmp     dx,0xFFF1
         bne     TestArus_WDBSErr
         mov     awx,0x00000000
         mov     cl,0x0F
         andsx   ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x00000000
         mov     dl,0x0F
         orsx    fx,bwx,dl
         cmp     fx,0x000F
         bne     TestArus_WDBSErr
         mov     cwx,0x00000000
         mov     el,0x0F
         xorsx   gx,cwx,el
         cmp     gx,0x000F
         bne     TestArus_WDBSErr
         mov     dwx,0x00000000
         mov     fl,0x0F
         mulsx   aw,dwx,fl
         cmp     aw,0x0000
         bne     TestArus_WDBSErr
         mov     ewx,0x00000000
         mov     gl,0x0F
         sdivsx  bw,ewx,gl
         cmp     bw,0x0000
         bne     TestArus_WDBSErr
         mov     fwx,0x00000000
         mov     ah,0x0F
         sremsx  cw,fwx,ah
         cmp     cw,0x0000
         bne     TestArus_WDBSErr
         mov     gwx,0x00000000
         mov     bh,0x7F
         addsx   dw,gwx,bh
         cmp     dw,0x007F
         bne     TestArus_WDBSErr
         mov     ar,0x00000000
         mov     ch,0x7F
         subsx   ew,ar,ch
         cmp     ew,0xFF81
         bne     TestArus_WDBSErr
         mov     br,0x00000000
         mov     dh,0x7F
         andsx   fw,br,dh
         cmp     fw,0x0000
         bne     TestArus_WDBSErr
         mov     cr,0x00000000
         mov     eh,0x7F
         orsx    gw,cr,eh
         cmp     gw,0x007F
         bne     TestArus_WDBSErr
         mov     dr,0x00000000
         mov     fh,0x7F
         xorsx   ax,dr,fh
         cmp     ax,0x007F
         bne     TestArus_WDBSErr
         mov     er,0x00000000
         mov     gh,0x7F
         mulsx   bx,er,gh
         cmp     bx,0x0000
         bne     TestArus_WDBSErr
         mov     fr,0x00000000
         mov     al,0x7F
         sdivsx  cx,fr,al
         cmp     cx,0x0000
         bne     TestArus_WDBSErr
         mov     gr,0x00000000
         mov     bl,0x7F
         sremsx  dx,gr,bl
         cmp     dx,0x0000
         bne     TestArus_WDBSErr
         mov     awx,0x00000000
         mov     cl,0x80
         addsx   ex,awx,cl
         cmp     ex,0xFF80
         bne     TestArus_WDBSErr
         mov     bwx,0x00000000
         mov     dl,0x80
         subsx   fx,bwx,dl
         cmp     fx,0x0080
         bne     TestArus_WDBSErr
         mov     cwx,0x00000000
         mov     el,0x80
         andsx   gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00000000
         mov     fl,0x80
         orsx    aw,dwx,fl
         cmp     aw,0xFF80
         bne     TestArus_WDBSErr
         mov     ewx,0x00000000
         mov     gl,0x80
         xorsx   bw,ewx,gl
         cmp     bw,0xFF80
         bne     TestArus_WDBSErr
         mov     fwx,0x00000000
         mov     ah,0x80
         mulsx   cw,fwx,ah
         cmp     cw,0x0000
         bne     TestArus_WDBSErr
         mov     gwx,0x00000000
         mov     bh,0x80
         sdivsx  dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000000
         mov     ch,0x80
         sremsx  ew,ar,ch
         cmp     ew,0x0000
         bne     TestArus_WDBSErr
         mov     br,0x00000000
         mov     dh,0xFF
         addsx   fw,br,dh
         cmp     fw,0xFFFF
         bne     TestArus_WDBSErr
         mov     cr,0x00000000
         mov     eh,0xFF
         subsx   gw,cr,eh
         cmp     gw,0x0001
         bne     TestArus_WDBSErr
         mov     dr,0x00000000
         mov     fh,0xFF
         andsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00000000
         mov     gh,0xFF
         orsx    bx,er,gh
         cmp     bx,0xFFFF
         bne     TestArus_WDBSErr
         mov     fr,0x00000000
         mov     al,0xFF
         xorsx   cx,fr,al
         cmp     cx,0xFFFF
         bne     TestArus_WDBSErr
         mov     gr,0x00000000
         mov     bl,0xFF
         mulsx   dx,gr,bl
         cmp     dx,0x0000
         bne     TestArus_WDBSErr
         mov     awx,0x00000000
         mov     cl,0xFF
         sdivsx  ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x00000000
         mov     dl,0xFF
         sremsx  fx,bwx,dl
         cmp     fx,0x0000
         bne     TestArus_WDBSErr
         mov     cwx,0x00000001
         mov     el,0x01
         addsx   gx,cwx,el
         cmp     gx,0x0002
         bne     TestArus_WDBSErr
         mov     dwx,0x00000001
         mov     fl,0x01
         subsx   aw,dwx,fl
         cmp     aw,0x0000
         bne     TestArus_WDBSErr
         mov     ewx,0x00000001
         mov     gl,0x01
         andsx   bw,ewx,gl
         cmp     bw,0x0001
         bne     TestArus_WDBSErr
         mov     fwx,0x00000001
         mov     ah,0x01
         orsx    cw,fwx,ah
         cmp     cw,0x0001
         bne     TestArus_WDBSErr
         mov     gwx,0x00000001
         mov     bh,0x01
         xorsx   dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000001
         mov     ch,0x01
         mulsx   ew,ar,ch
         cmp     ew,0x0001
         bne     TestArus_WDBSErr
         mov     br,0x00000001
         mov     dh,0x01
         sdivsx  fw,br,dh
         cmp     fw,0x0001
         bne     TestArus_WDBSErr
         mov     cr,0x00000001
         mov     eh,0x01
         sremsx  gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         mov     dr,0x00000001
         mov     fh,0x07
         addsx   ax,dr,fh
         cmp     ax,0x0008
         bne     TestArus_WDBSErr
         mov     er,0x00000001
         mov     gh,0x07
         subsx   bx,er,gh
         cmp     bx,0xFFFA
         bne     TestArus_WDBSErr
         mov     fr,0x00000001
         mov     al,0x07
         andsx   cx,fr,al
         cmp     cx,0x0001
         bne     TestArus_WDBSErr
         mov     gr,0x00000001
         mov     bl,0x07
         orsx    dx,gr,bl
         cmp     dx,0x0007
         bne     TestArus_WDBSErr
         mov     awx,0x00000001
         mov     cl,0x07
         xorsx   ex,awx,cl
         cmp     ex,0x0006
         bne     TestArus_WDBSErr
         mov     bwx,0x00000001
         mov     dl,0x07
         mulsx   fx,bwx,dl
         cmp     fx,0x0007
         bne     TestArus_WDBSErr
         mov     cwx,0x00000001
         mov     el,0x07
         sdivsx  gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00000001
         mov     fl,0x07
         sremsx  aw,dwx,fl
         cmp     aw,0x0001
         bne     TestArus_WDBSErr
         mov     ewx,0x00000001
         mov     gl,0x08
         addsx   bw,ewx,gl
         cmp     bw,0x0009
         bne     TestArus_WDBSErr
         mov     fwx,0x00000001
         mov     ah,0x08
         subsx   cw,fwx,ah
         cmp     cw,0xFFF9
         bne     TestArus_WDBSErr
         mov     gwx,0x00000001
         mov     bh,0x08
         andsx   dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000001
         mov     ch,0x08
         orsx    ew,ar,ch
         cmp     ew,0x0009
         bne     TestArus_WDBSErr
         mov     br,0x00000001
         mov     dh,0x08
         xorsx   fw,br,dh
         cmp     fw,0x0009
         bne     TestArus_WDBSErr
         mov     cr,0x00000001
         mov     eh,0x08
         mulsx   gw,cr,eh
         cmp     gw,0x0008
         bne     TestArus_WDBSErr
         mov     dr,0x00000001
         mov     fh,0x08
         sdivsx  ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00000001
         mov     gh,0x08
         sremsx  bx,er,gh
         cmp     bx,0x0001
         bne     TestArus_WDBSErr
         mov     fr,0x00000001
         mov     al,0x09
         addsx   cx,fr,al
         cmp     cx,0x000A
         bne     TestArus_WDBSErr
         mov     gr,0x00000001
         mov     bl,0x09
         subsx   dx,gr,bl
         cmp     dx,0xFFF8
         bne     TestArus_WDBSErr
         mov     awx,0x00000001
         mov     cl,0x09
         andsx   ex,awx,cl
         cmp     ex,0x0001
         bne     TestArus_WDBSErr
         mov     bwx,0x00000001
         mov     dl,0x09
         orsx    fx,bwx,dl
         cmp     fx,0x0009
         bne     TestArus_WDBSErr
         mov     cwx,0x00000001
         mov     el,0x09
         xorsx   gx,cwx,el
         cmp     gx,0x0008
         bne     TestArus_WDBSErr
         mov     dwx,0x00000001
         mov     fl,0x09
         mulsx   aw,dwx,fl
         cmp     aw,0x0009
         bne     TestArus_WDBSErr
         mov     ewx,0x00000001
         mov     gl,0x09
         sdivsx  bw,ewx,gl
         cmp     bw,0x0000
         bne     TestArus_WDBSErr
         mov     fwx,0x00000001
         mov     ah,0x09
         sremsx  cw,fwx,ah
         cmp     cw,0x0001
         bne     TestArus_WDBSErr
         mov     gwx,0x00000001
         mov     bh,0x0F
         addsx   dw,gwx,bh
         cmp     dw,0x0010
         bne     TestArus_WDBSErr
         mov     ar,0x00000001
         mov     ch,0x0F
         subsx   ew,ar,ch
         cmp     ew,0xFFF2
         bne     TestArus_WDBSErr
         mov     br,0x00000001
         mov     dh,0x0F
         andsx   fw,br,dh
         cmp     fw,0x0001
         bne     TestArus_WDBSErr
         mov     cr,0x00000001
         mov     eh,0x0F
         orsx    gw,cr,eh
         cmp     gw,0x000F
         bne     TestArus_WDBSErr
         mov     dr,0x00000001
         mov     fh,0x0F
         xorsx   ax,dr,fh
         cmp     ax,0x000E
         bne     TestArus_WDBSErr
         mov     er,0x00000001
         mov     gh,0x0F
         mulsx   bx,er,gh
         cmp     bx,0x000F
         bne     TestArus_WDBSErr
         mov     fr,0x00000001
         mov     al,0x0F
         sdivsx  cx,fr,al
         cmp     cx,0x0000
         bne     TestArus_WDBSErr
         mov     gr,0x00000001
         mov     bl,0x0F
         sremsx  dx,gr,bl
         cmp     dx,0x0001
         bne     TestArus_WDBSErr
         mov     awx,0x00000001
         mov     cl,0x7F
         addsx   ex,awx,cl
         cmp     ex,0x0080
         bne     TestArus_WDBSErr
         mov     bwx,0x00000001
         mov     dl,0x7F
         subsx   fx,bwx,dl
         cmp     fx,0xFF82
         bne     TestArus_WDBSErr
         mov     cwx,0x00000001
         mov     el,0x7F
         andsx   gx,cwx,el
         cmp     gx,0x0001
         bne     TestArus_WDBSErr
         mov     dwx,0x00000001
         mov     fl,0x7F
         orsx    aw,dwx,fl
         cmp     aw,0x007F
         bne     TestArus_WDBSErr
         mov     ewx,0x00000001
         mov     gl,0x7F
         xorsx   bw,ewx,gl
         cmp     bw,0x007E
         bne     TestArus_WDBSErr
         mov     fwx,0x00000001
         mov     ah,0x7F
         mulsx   cw,fwx,ah
         cmp     cw,0x007F
         bne     TestArus_WDBSErr
         mov     gwx,0x00000001
         mov     bh,0x7F
         sdivsx  dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000001
         mov     ch,0x7F
         sremsx  ew,ar,ch
         cmp     ew,0x0001
         bne     TestArus_WDBSErr
         mov     br,0x00000001
         mov     dh,0x80
         addsx   fw,br,dh
         cmp     fw,0xFF81
         bne     TestArus_WDBSErr
         mov     cr,0x00000001
         mov     eh,0x80
         subsx   gw,cr,eh
         cmp     gw,0x0081
         bne     TestArus_WDBSErr
         mov     dr,0x00000001
         mov     fh,0x80
         andsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00000001
         mov     gh,0x80
         orsx    bx,er,gh
         cmp     bx,0xFF81
         bne     TestArus_WDBSErr
         mov     fr,0x00000001
         mov     al,0x80
         xorsx   cx,fr,al
         cmp     cx,0xFF81
         bne     TestArus_WDBSErr
         mov     gr,0x00000001
         mov     bl,0x80
         mulsx   dx,gr,bl
         cmp     dx,0xFF80
         bne     TestArus_WDBSErr
         mov     awx,0x00000001
         mov     cl,0x80
         sdivsx  ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x00000001
         mov     dl,0x80
         sremsx  fx,bwx,dl
         cmp     fx,0x0001
         bne     TestArus_WDBSErr
         mov     cwx,0x00000001
         mov     el,0xFF
         addsx   gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00000001
         mov     fl,0xFF
         subsx   aw,dwx,fl
         cmp     aw,0x0002
         bne     TestArus_WDBSErr
         mov     ewx,0x00000001
         mov     gl,0xFF
         andsx   bw,ewx,gl
         cmp     bw,0x0001
         bne     TestArus_WDBSErr
         mov     fwx,0x00000001
         mov     ah,0xFF
         orsx    cw,fwx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WDBSErr
         mov     gwx,0x00000001
         mov     bh,0xFF
         xorsx   dw,gwx,bh
         cmp     dw,0xFFFE
         bne     TestArus_WDBSErr
         mov     ar,0x00000001
         mov     ch,0xFF
         mulsx   ew,ar,ch
         cmp     ew,0xFFFF
         bne     TestArus_WDBSErr
         mov     br,0x00000001
         mov     dh,0xFF
         sdivsx  fw,br,dh
         cmp     fw,0xFFFF
         bne     TestArus_WDBSErr
         mov     cr,0x00000001
         mov     eh,0xFF
         sremsx  gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         mov     dr,0x00000008
         mov     fh,0x07
         addsx   ax,dr,fh
         cmp     ax,0x000F
         bne     TestArus_WDBSErr
         mov     er,0x00000008
         mov     gh,0x07
         subsx   bx,er,gh
         cmp     bx,0x0001
         bne     TestArus_WDBSErr
         mov     fr,0x00000008
         mov     al,0x07
         andsx   cx,fr,al
         cmp     cx,0x0000
         bne     TestArus_WDBSErr
         mov     gr,0x00000008
         mov     bl,0x07
         orsx    dx,gr,bl
         cmp     dx,0x000F
         bne     TestArus_WDBSErr
         mov     awx,0x00000008
         mov     cl,0x07
         xorsx   ex,awx,cl
         cmp     ex,0x000F
         bne     TestArus_WDBSErr
         mov     bwx,0x00000008
         mov     dl,0x07
         mulsx   fx,bwx,dl
         cmp     fx,0x0038
         bne     TestArus_WDBSErr
         mov     cwx,0x00000008
         mov     el,0x07
         sdivsx  gx,cwx,el
         cmp     gx,0x0001
         bne     TestArus_WDBSErr
         mov     dwx,0x00000008
         mov     fl,0x07
         sremsx  aw,dwx,fl
         cmp     aw,0x0001
         bne     TestArus_WDBSErr
         mov     ewx,0x00000008
         mov     gl,0x08
         addsx   bw,ewx,gl
         cmp     bw,0x0010
         bne     TestArus_WDBSErr
         mov     fwx,0x00000008
         mov     ah,0x08
         subsx   cw,fwx,ah
         cmp     cw,0x0000
         bne     TestArus_WDBSErr
         mov     gwx,0x00000008
         mov     bh,0x08
         andsx   dw,gwx,bh
         cmp     dw,0x0008
         bne     TestArus_WDBSErr
         mov     ar,0x00000008
         mov     ch,0x08
         orsx    ew,ar,ch
         cmp     ew,0x0008
         bne     TestArus_WDBSErr
         mov     br,0x00000008
         mov     dh,0x08
         xorsx   fw,br,dh
         cmp     fw,0x0000
         bne     TestArus_WDBSErr
         mov     cr,0x00000008
         mov     eh,0x08
         mulsx   gw,cr,eh
         cmp     gw,0x0040
         bne     TestArus_WDBSErr
         mov     dr,0x00000008
         mov     fh,0x08
         sdivsx  ax,dr,fh
         cmp     ax,0x0001
         bne     TestArus_WDBSErr
         mov     er,0x00000008
         mov     gh,0x08
         sremsx  bx,er,gh
         cmp     bx,0x0000
         bne     TestArus_WDBSErr
         mov     fr,0x00000008
         mov     al,0x09
         addsx   cx,fr,al
         cmp     cx,0x0011
         bne     TestArus_WDBSErr
         mov     gr,0x00000008
         mov     bl,0x09
         subsx   dx,gr,bl
         cmp     dx,0xFFFF
         bne     TestArus_WDBSErr
         mov     awx,0x00000008
         mov     cl,0x09
         andsx   ex,awx,cl
         cmp     ex,0x0008
         bne     TestArus_WDBSErr
         mov     bwx,0x00000008
         mov     dl,0x09
         orsx    fx,bwx,dl
         cmp     fx,0x0009
         bne     TestArus_WDBSErr
         mov     cwx,0x00000008
         mov     el,0x09
         xorsx   gx,cwx,el
         cmp     gx,0x0001
         bne     TestArus_WDBSErr
         mov     dwx,0x00000008
         mov     fl,0x09
         mulsx   aw,dwx,fl
         cmp     aw,0x0048
         bne     TestArus_WDBSErr
         mov     ewx,0x00000008
         mov     gl,0x09
         sdivsx  bw,ewx,gl
         cmp     bw,0x0000
         bne     TestArus_WDBSErr
         mov     fwx,0x00000008
         mov     ah,0x09
         sremsx  cw,fwx,ah
         cmp     cw,0x0008
         bne     TestArus_WDBSErr
         mov     gwx,0x00000008
         mov     bh,0x0F
         addsx   dw,gwx,bh
         cmp     dw,0x0017
         bne     TestArus_WDBSErr
         mov     ar,0x00000008
         mov     ch,0x0F
         subsx   ew,ar,ch
         cmp     ew,0xFFF9
         bne     TestArus_WDBSErr
         mov     br,0x00000008
         mov     dh,0x0F
         andsx   fw,br,dh
         cmp     fw,0x0008
         bne     TestArus_WDBSErr
         mov     cr,0x00000008
         mov     eh,0x0F
         orsx    gw,cr,eh
         cmp     gw,0x000F
         bne     TestArus_WDBSErr
         mov     dr,0x00000008
         mov     fh,0x0F
         xorsx   ax,dr,fh
         cmp     ax,0x0007
         bne     TestArus_WDBSErr
         mov     er,0x00000008
         mov     gh,0x0F
         mulsx   bx,er,gh
         cmp     bx,0x0078
         bne     TestArus_WDBSErr
         mov     fr,0x00000008
         mov     al,0x0F
         sdivsx  cx,fr,al
         cmp     cx,0x0000
         bne     TestArus_WDBSErr
         mov     gr,0x00000008
         mov     bl,0x0F
         sremsx  dx,gr,bl
         cmp     dx,0x0008
         bne     TestArus_WDBSErr
         mov     awx,0x00000008
         mov     cl,0x7F
         addsx   ex,awx,cl
         cmp     ex,0x0087
         bne     TestArus_WDBSErr
         mov     bwx,0x00000008
         mov     dl,0x7F
         subsx   fx,bwx,dl
         cmp     fx,0xFF89
         bne     TestArus_WDBSErr
         mov     cwx,0x00000008
         mov     el,0x7F
         andsx   gx,cwx,el
         cmp     gx,0x0008
         bne     TestArus_WDBSErr
         mov     dwx,0x00000008
         mov     fl,0x7F
         orsx    aw,dwx,fl
         cmp     aw,0x007F
         bne     TestArus_WDBSErr
         mov     ewx,0x00000008
         mov     gl,0x7F
         xorsx   bw,ewx,gl
         cmp     bw,0x0077
         bne     TestArus_WDBSErr
         mov     fwx,0x00000008
         mov     ah,0x7F
         mulsx   cw,fwx,ah
         cmp     cw,0x03F8
         bne     TestArus_WDBSErr
         mov     gwx,0x00000008
         mov     bh,0x7F
         sdivsx  dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000008
         mov     ch,0x7F
         sremsx  ew,ar,ch
         cmp     ew,0x0008
         bne     TestArus_WDBSErr
         mov     br,0x00000008
         mov     dh,0x80
         addsx   fw,br,dh
         cmp     fw,0xFF88
         bne     TestArus_WDBSErr
         mov     cr,0x00000008
         mov     eh,0x80
         subsx   gw,cr,eh
         cmp     gw,0x0088
         bne     TestArus_WDBSErr
         mov     dr,0x00000008
         mov     fh,0x80
         andsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00000008
         mov     gh,0x80
         orsx    bx,er,gh
         cmp     bx,0xFF88
         bne     TestArus_WDBSErr
         mov     fr,0x00000008
         mov     al,0x80
         xorsx   cx,fr,al
         cmp     cx,0xFF88
         bne     TestArus_WDBSErr
         mov     gr,0x00000008
         mov     bl,0x80
         mulsx   dx,gr,bl
         cmp     dx,0xFC00
         bne     TestArus_WDBSErr
         mov     awx,0x00000008
         mov     cl,0x80
         sdivsx  ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x00000008
         mov     dl,0x80
         sremsx  fx,bwx,dl
         cmp     fx,0x0008
         bne     TestArus_WDBSErr
         mov     cwx,0x00000008
         mov     el,0xFF
         addsx   gx,cwx,el
         cmp     gx,0x0007
         bne     TestArus_WDBSErr
         mov     dwx,0x00000008
         mov     fl,0xFF
         subsx   aw,dwx,fl
         cmp     aw,0x0009
         bne     TestArus_WDBSErr
         mov     ewx,0x00000008
         mov     gl,0xFF
         andsx   bw,ewx,gl
         cmp     bw,0x0008
         bne     TestArus_WDBSErr
         mov     fwx,0x00000008
         mov     ah,0xFF
         orsx    cw,fwx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WDBSErr
         mov     gwx,0x00000008
         mov     bh,0xFF
         xorsx   dw,gwx,bh
         cmp     dw,0xFFF7
         bne     TestArus_WDBSErr
         mov     ar,0x00000008
         mov     ch,0xFF
         mulsx   ew,ar,ch
         cmp     ew,0xFFF8
         bne     TestArus_WDBSErr
         mov     br,0x00000008
         mov     dh,0xFF
         sdivsx  fw,br,dh
         cmp     fw,0xFFF8
         bne     TestArus_WDBSErr
         mov     cr,0x00000008
         mov     eh,0xFF
         sremsx  gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         mov     dr,0x00000009
         mov     fh,0x08
         addsx   ax,dr,fh
         cmp     ax,0x0011
         bne     TestArus_WDBSErr
         mov     er,0x00000009
         mov     gh,0x08
         subsx   bx,er,gh
         cmp     bx,0x0001
         bne     TestArus_WDBSErr
         mov     fr,0x00000009
         mov     al,0x08
         andsx   cx,fr,al
         cmp     cx,0x0008
         bne     TestArus_WDBSErr
         mov     gr,0x00000009
         mov     bl,0x08
         orsx    dx,gr,bl
         cmp     dx,0x0009
         bne     TestArus_WDBSErr
         mov     awx,0x00000009
         mov     cl,0x08
         xorsx   ex,awx,cl
         cmp     ex,0x0001
         bne     TestArus_WDBSErr
         mov     bwx,0x00000009
         mov     dl,0x08
         mulsx   fx,bwx,dl
         cmp     fx,0x0048
         bne     TestArus_WDBSErr
         mov     cwx,0x00000009
         mov     el,0x08
         sdivsx  gx,cwx,el
         cmp     gx,0x0001
         bne     TestArus_WDBSErr
         mov     dwx,0x00000009
         mov     fl,0x08
         sremsx  aw,dwx,fl
         cmp     aw,0x0001
         bne     TestArus_WDBSErr
         mov     ewx,0x00000009
         mov     gl,0x09
         addsx   bw,ewx,gl
         cmp     bw,0x0012
         bne     TestArus_WDBSErr
         mov     fwx,0x00000009
         mov     ah,0x09
         subsx   cw,fwx,ah
         cmp     cw,0x0000
         bne     TestArus_WDBSErr
         mov     gwx,0x00000009
         mov     bh,0x09
         andsx   dw,gwx,bh
         cmp     dw,0x0009
         bne     TestArus_WDBSErr
         mov     ar,0x00000009
         mov     ch,0x09
         orsx    ew,ar,ch
         cmp     ew,0x0009
         bne     TestArus_WDBSErr
         mov     br,0x00000009
         mov     dh,0x09
         xorsx   fw,br,dh
         cmp     fw,0x0000
         bne     TestArus_WDBSErr
         mov     cr,0x00000009
         mov     eh,0x09
         mulsx   gw,cr,eh
         cmp     gw,0x0051
         bne     TestArus_WDBSErr
         mov     dr,0x00000009
         mov     fh,0x09
         sdivsx  ax,dr,fh
         cmp     ax,0x0001
         bne     TestArus_WDBSErr
         mov     er,0x00000009
         mov     gh,0x09
         sremsx  bx,er,gh
         cmp     bx,0x0000
         bne     TestArus_WDBSErr
         mov     fr,0x00000009
         mov     al,0x0F
         addsx   cx,fr,al
         cmp     cx,0x0018
         bne     TestArus_WDBSErr
         mov     gr,0x00000009
         mov     bl,0x0F
         subsx   dx,gr,bl
         cmp     dx,0xFFFA
         bne     TestArus_WDBSErr
         mov     awx,0x00000009
         mov     cl,0x0F
         andsx   ex,awx,cl
         cmp     ex,0x0009
         bne     TestArus_WDBSErr
         mov     bwx,0x00000009
         mov     dl,0x0F
         orsx    fx,bwx,dl
         cmp     fx,0x000F
         bne     TestArus_WDBSErr
         mov     cwx,0x00000009
         mov     el,0x0F
         xorsx   gx,cwx,el
         cmp     gx,0x0006
         bne     TestArus_WDBSErr
         mov     dwx,0x00000009
         mov     fl,0x0F
         mulsx   aw,dwx,fl
         cmp     aw,0x0087
         bne     TestArus_WDBSErr
         mov     ewx,0x00000009
         mov     gl,0x0F
         sdivsx  bw,ewx,gl
         cmp     bw,0x0000
         bne     TestArus_WDBSErr
         mov     fwx,0x00000009
         mov     ah,0x0F
         sremsx  cw,fwx,ah
         cmp     cw,0x0009
         bne     TestArus_WDBSErr
         mov     gwx,0x00000009
         mov     bh,0x7F
         addsx   dw,gwx,bh
         cmp     dw,0x0088
         bne     TestArus_WDBSErr
         mov     ar,0x00000009
         mov     ch,0x7F
         subsx   ew,ar,ch
         cmp     ew,0xFF8A
         bne     TestArus_WDBSErr
         mov     br,0x00000009
         mov     dh,0x7F
         andsx   fw,br,dh
         cmp     fw,0x0009
         bne     TestArus_WDBSErr
         mov     cr,0x00000009
         mov     eh,0x7F
         orsx    gw,cr,eh
         cmp     gw,0x007F
         bne     TestArus_WDBSErr
         mov     dr,0x00000009
         mov     fh,0x7F
         xorsx   ax,dr,fh
         cmp     ax,0x0076
         bne     TestArus_WDBSErr
         mov     er,0x00000009
         mov     gh,0x7F
         mulsx   bx,er,gh
         cmp     bx,0x0477
         bne     TestArus_WDBSErr
         mov     fr,0x00000009
         mov     al,0x7F
         sdivsx  cx,fr,al
         cmp     cx,0x0000
         bne     TestArus_WDBSErr
         mov     gr,0x00000009
         mov     bl,0x7F
         sremsx  dx,gr,bl
         cmp     dx,0x0009
         bne     TestArus_WDBSErr
         mov     awx,0x00000009
         mov     cl,0x80
         addsx   ex,awx,cl
         cmp     ex,0xFF89
         bne     TestArus_WDBSErr
         mov     bwx,0x00000009
         mov     dl,0x80
         subsx   fx,bwx,dl
         cmp     fx,0x0089
         bne     TestArus_WDBSErr
         mov     cwx,0x00000009
         mov     el,0x80
         andsx   gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00000009
         mov     fl,0x80
         orsx    aw,dwx,fl
         cmp     aw,0xFF89
         bne     TestArus_WDBSErr
         mov     ewx,0x00000009
         mov     gl,0x80
         xorsx   bw,ewx,gl
         cmp     bw,0xFF89
         bne     TestArus_WDBSErr
         mov     fwx,0x00000009
         mov     ah,0x80
         mulsx   cw,fwx,ah
         cmp     cw,0xFB80
         bne     TestArus_WDBSErr
         mov     gwx,0x00000009
         mov     bh,0x80
         sdivsx  dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x00000009
         mov     ch,0x80
         sremsx  ew,ar,ch
         cmp     ew,0x0009
         bne     TestArus_WDBSErr
         mov     br,0x00000009
         mov     dh,0xFF
         addsx   fw,br,dh
         cmp     fw,0x0008
         bne     TestArus_WDBSErr
         mov     cr,0x00000009
         mov     eh,0xFF
         subsx   gw,cr,eh
         cmp     gw,0x000A
         bne     TestArus_WDBSErr
         mov     dr,0x00000009
         mov     fh,0xFF
         andsx   ax,dr,fh
         cmp     ax,0x0009
         bne     TestArus_WDBSErr
         mov     er,0x00000009
         mov     gh,0xFF
         orsx    bx,er,gh
         cmp     bx,0xFFFF
         bne     TestArus_WDBSErr
         mov     fr,0x00000009
         mov     al,0xFF
         xorsx   cx,fr,al
         cmp     cx,0xFFF6
         bne     TestArus_WDBSErr
         mov     gr,0x00000009
         mov     bl,0xFF
         mulsx   dx,gr,bl
         cmp     dx,0xFFF7
         bne     TestArus_WDBSErr
         mov     awx,0x00000009
         mov     cl,0xFF
         sdivsx  ex,awx,cl
         cmp     ex,0xFFF7
         bne     TestArus_WDBSErr
         mov     bwx,0x00000009
         mov     dl,0xFF
         sremsx  fx,bwx,dl
         cmp     fx,0x0000
         bne     TestArus_WDBSErr
         mov     cwx,0x00007FFF
         mov     el,0x09
         addsx   gx,cwx,el
         cmp     gx,0x8008
         bne     TestArus_WDBSErr
         mov     dwx,0x00007FFF
         mov     fl,0x09
         subsx   aw,dwx,fl
         cmp     aw,0x7FF6
         bne     TestArus_WDBSErr
         mov     ewx,0x00007FFF
         mov     gl,0x09
         andsx   bw,ewx,gl
         cmp     bw,0x0009
         bne     TestArus_WDBSErr
         mov     fwx,0x00007FFF
         mov     ah,0x09
         orsx    cw,fwx,ah
         cmp     cw,0x7FFF
         bne     TestArus_WDBSErr
         mov     gwx,0x00007FFF
         mov     bh,0x09
         xorsx   dw,gwx,bh
         cmp     dw,0x7FF6
         bne     TestArus_WDBSErr
         mov     ar,0x00007FFF
         mov     ch,0x09
         mulsx   ew,ar,ch
         cmp     ew,0x7FF7
         bne     TestArus_WDBSErr
         mov     br,0x00007FFF
         mov     dh,0x09
         sdivsx  fw,br,dh
         cmp     fw,0x0E38
         bne     TestArus_WDBSErr
         mov     cr,0x00007FFF
         mov     eh,0x09
         sremsx  gw,cr,eh
         cmp     gw,0x0007
         bne     TestArus_WDBSErr
         mov     dr,0x00007FFF
         mov     fh,0x0F
         addsx   ax,dr,fh
         cmp     ax,0x800E
         bne     TestArus_WDBSErr
         mov     er,0x00007FFF
         mov     gh,0x0F
         subsx   bx,er,gh
         cmp     bx,0x7FF0
         bne     TestArus_WDBSErr
         mov     fr,0x00007FFF
         mov     al,0x0F
         andsx   cx,fr,al
         cmp     cx,0x000F
         bne     TestArus_WDBSErr
         mov     gr,0x00007FFF
         mov     bl,0x0F
         orsx    dx,gr,bl
         cmp     dx,0x7FFF
         bne     TestArus_WDBSErr
         mov     awx,0x00007FFF
         mov     cl,0x0F
         xorsx   ex,awx,cl
         cmp     ex,0x7FF0
         bne     TestArus_WDBSErr
         mov     bwx,0x00007FFF
         mov     dl,0x0F
         mulsx   fx,bwx,dl
         cmp     fx,0x7FF1
         bne     TestArus_WDBSErr
         mov     cwx,0x00007FFF
         mov     el,0x0F
         sdivsx  gx,cwx,el
         cmp     gx,0x0888
         bne     TestArus_WDBSErr
         mov     dwx,0x00007FFF
         mov     fl,0x0F
         sremsx  aw,dwx,fl
         cmp     aw,0x0007
         bne     TestArus_WDBSErr
         mov     ewx,0x00007FFF
         mov     gl,0x7F
         addsx   bw,ewx,gl
         cmp     bw,0x807E
         bne     TestArus_WDBSErr
         mov     fwx,0x00007FFF
         mov     ah,0x7F
         subsx   cw,fwx,ah
         cmp     cw,0x7F80
         bne     TestArus_WDBSErr
         mov     gwx,0x00007FFF
         mov     bh,0x7F
         andsx   dw,gwx,bh
         cmp     dw,0x007F
         bne     TestArus_WDBSErr
         mov     ar,0x00007FFF
         mov     ch,0x7F
         orsx    ew,ar,ch
         cmp     ew,0x7FFF
         bne     TestArus_WDBSErr
         mov     br,0x00007FFF
         mov     dh,0x7F
         xorsx   fw,br,dh
         cmp     fw,0x7F80
         bne     TestArus_WDBSErr
         mov     cr,0x00007FFF
         mov     eh,0x7F
         mulsx   gw,cr,eh
         cmp     gw,0x7F81
         bne     TestArus_WDBSErr
         mov     dr,0x00007FFF
         mov     fh,0x7F
         sdivsx  ax,dr,fh
         cmp     ax,0x0102
         bne     TestArus_WDBSErr
         mov     er,0x00007FFF
         mov     gh,0x7F
         sremsx  bx,er,gh
         cmp     bx,0x0001
         bne     TestArus_WDBSErr
         mov     fr,0x00007FFF
         mov     al,0x80
         addsx   cx,fr,al
         cmp     cx,0x7F7F
         bne     TestArus_WDBSErr
         mov     gr,0x00007FFF
         mov     bl,0x80
         subsx   dx,gr,bl
         cmp     dx,0x807F
         bne     TestArus_WDBSErr
         mov     awx,0x00007FFF
         mov     cl,0x80
         andsx   ex,awx,cl
         cmp     ex,0x7F80
         bne     TestArus_WDBSErr
         mov     bwx,0x00007FFF
         mov     dl,0x80
         orsx    fx,bwx,dl
         cmp     fx,0xFFFF
         bne     TestArus_WDBSErr
         mov     cwx,0x00007FFF
         mov     el,0x80
         xorsx   gx,cwx,el
         cmp     gx,0x807F
         bne     TestArus_WDBSErr
         mov     dwx,0x00007FFF
         mov     fl,0x80
         mulsx   aw,dwx,fl
         cmp     aw,0x0080
         bne     TestArus_WDBSErr
         mov     ewx,0x00007FFF
         mov     gl,0x80
         sdivsx  bw,ewx,gl
         cmp     bw,0xFF01
         bne     TestArus_WDBSErr
         mov     fwx,0x00007FFF
         mov     ah,0x80
         sremsx  cw,fwx,ah
         cmp     cw,0x007F
         bne     TestArus_WDBSErr
         mov     gwx,0x00007FFF
         mov     bh,0xFF
         addsx   dw,gwx,bh
         cmp     dw,0x7FFE
         bne     TestArus_WDBSErr
         mov     ar,0x00007FFF
         mov     ch,0xFF
         subsx   ew,ar,ch
         cmp     ew,0x8000
         bne     TestArus_WDBSErr
         mov     br,0x00007FFF
         mov     dh,0xFF
         andsx   fw,br,dh
         cmp     fw,0x7FFF
         bne     TestArus_WDBSErr
         mov     cr,0x00007FFF
         mov     eh,0xFF
         orsx    gw,cr,eh
         cmp     gw,0xFFFF
         bne     TestArus_WDBSErr
         mov     dr,0x00007FFF
         mov     fh,0xFF
         xorsx   ax,dr,fh
         cmp     ax,0x8000
         bne     TestArus_WDBSErr
         mov     er,0x00007FFF
         mov     gh,0xFF
         mulsx   bx,er,gh
         cmp     bx,0x8001
         bne     TestArus_WDBSErr
         mov     fr,0x00007FFF
         mov     al,0xFF
         sdivsx  cx,fr,al
         cmp     cx,0x8001
         bne     TestArus_WDBSErr
         mov     gr,0x00007FFF
         mov     bl,0xFF
         sremsx  dx,gr,bl
         cmp     dx,0x0000
         bne     TestArus_WDBSErr
         mov     awx,0x00008000
         mov     cl,0x0F
         addsx   ex,awx,cl
         cmp     ex,0x800F
         bne     TestArus_WDBSErr
         mov     bwx,0x00008000
         mov     dl,0x0F
         subsx   fx,bwx,dl
         cmp     fx,0x7FF1
         bne     TestArus_WDBSErr
         mov     cwx,0x00008000
         mov     el,0x0F
         andsx   gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x00008000
         mov     fl,0x0F
         orsx    aw,dwx,fl
         cmp     aw,0x800F
         bne     TestArus_WDBSErr
         mov     ewx,0x00008000
         mov     gl,0x0F
         xorsx   bw,ewx,gl
         cmp     bw,0x800F
         bne     TestArus_WDBSErr
         mov     fwx,0x00008000
         mov     ah,0x0F
         mulsx   cw,fwx,ah
         cmp     cw,0x8000
         bne     TestArus_WDBSErr
         mov     gwx,0x00008000
         mov     bh,0x0F
         sdivsx  dw,gwx,bh
         cmp     dw,0x0888
         bne     TestArus_WDBSErr
         mov     ar,0x00008000
         mov     ch,0x0F
         sremsx  ew,ar,ch
         cmp     ew,0x0008
         bne     TestArus_WDBSErr
         mov     br,0x00008000
         mov     dh,0x7F
         addsx   fw,br,dh
         cmp     fw,0x807F
         bne     TestArus_WDBSErr
         mov     cr,0x00008000
         mov     eh,0x7F
         subsx   gw,cr,eh
         cmp     gw,0x7F81
         bne     TestArus_WDBSErr
         mov     dr,0x00008000
         mov     fh,0x7F
         andsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x00008000
         mov     gh,0x7F
         orsx    bx,er,gh
         cmp     bx,0x807F
         bne     TestArus_WDBSErr
         mov     fr,0x00008000
         mov     al,0x7F
         xorsx   cx,fr,al
         cmp     cx,0x807F
         bne     TestArus_WDBSErr
         mov     gr,0x00008000
         mov     bl,0x7F
         mulsx   dx,gr,bl
         cmp     dx,0x8000
         bne     TestArus_WDBSErr
         mov     awx,0x00008000
         mov     cl,0x7F
         sdivsx  ex,awx,cl
         cmp     ex,0x0102
         bne     TestArus_WDBSErr
         mov     bwx,0x00008000
         mov     dl,0x7F
         sremsx  fx,bwx,dl
         cmp     fx,0x0002
         bne     TestArus_WDBSErr
         mov     cwx,0x00008000
         mov     el,0x80
         addsx   gx,cwx,el
         cmp     gx,0x7F80
         bne     TestArus_WDBSErr
         mov     dwx,0x00008000
         mov     fl,0x80
         subsx   aw,dwx,fl
         cmp     aw,0x8080
         bne     TestArus_WDBSErr
         mov     ewx,0x00008000
         mov     gl,0x80
         andsx   bw,ewx,gl
         cmp     bw,0x8000
         bne     TestArus_WDBSErr
         mov     fwx,0x00008000
         mov     ah,0x80
         orsx    cw,fwx,ah
         cmp     cw,0xFF80
         bne     TestArus_WDBSErr
         mov     gwx,0x00008000
         mov     bh,0x80
         xorsx   dw,gwx,bh
         cmp     dw,0x7F80
         bne     TestArus_WDBSErr
         mov     ar,0x00008000
         mov     ch,0x80
         mulsx   ew,ar,ch
         cmp     ew,0x0000
         bne     TestArus_WDBSErr
         mov     br,0x00008000
         mov     dh,0x80
         sdivsx  fw,br,dh
         cmp     fw,0xFF00
         bne     TestArus_WDBSErr
         mov     cr,0x00008000
         mov     eh,0x80
         sremsx  gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         mov     dr,0x00008000
         mov     fh,0xFF
         addsx   ax,dr,fh
         cmp     ax,0x7FFF
         bne     TestArus_WDBSErr
         mov     er,0x00008000
         mov     gh,0xFF
         subsx   bx,er,gh
         cmp     bx,0x8001
         bne     TestArus_WDBSErr
         mov     fr,0x00008000
         mov     al,0xFF
         andsx   cx,fr,al
         cmp     cx,0x8000
         bne     TestArus_WDBSErr
         mov     gr,0x00008000
         mov     bl,0xFF
         orsx    dx,gr,bl
         cmp     dx,0xFFFF
         bne     TestArus_WDBSErr
         mov     awx,0x00008000
         mov     cl,0xFF
         xorsx   ex,awx,cl
         cmp     ex,0x7FFF
         bne     TestArus_WDBSErr
         mov     bwx,0x00008000
         mov     dl,0xFF
         mulsx   fx,bwx,dl
         cmp     fx,0x8000
         bne     TestArus_WDBSErr
         mov     cwx,0x00008000
         mov     el,0xFF
         sdivsx  gx,cwx,el
         cmp     gx,0x8000
         bne     TestArus_WDBSErr
         mov     dwx,0x00008000
         mov     fl,0xFF
         sremsx  aw,dwx,fl
         cmp     aw,0x0000
         bne     TestArus_WDBSErr
         mov     ewx,0x7FFFFFFF
         mov     gl,0x7F
         addsx   bw,ewx,gl
         cmp     bw,0x007E
         bne     TestArus_WDBSErr
         mov     fwx,0x7FFFFFFF
         mov     ah,0x7F
         subsx   cw,fwx,ah
         cmp     cw,0xFF80
         bne     TestArus_WDBSErr
         mov     gwx,0x7FFFFFFF
         mov     bh,0x7F
         andsx   dw,gwx,bh
         cmp     dw,0x007F
         bne     TestArus_WDBSErr
         mov     ar,0x7FFFFFFF
         mov     ch,0x7F
         orsx    ew,ar,ch
         cmp     ew,0xFFFF
         bne     TestArus_WDBSErr
         mov     br,0x7FFFFFFF
         mov     dh,0x7F
         xorsx   fw,br,dh
         cmp     fw,0xFF80
         bne     TestArus_WDBSErr
         mov     cr,0x7FFFFFFF
         mov     eh,0x7F
         mulsx   gw,cr,eh
         cmp     gw,0xFF81
         bne     TestArus_WDBSErr
         mov     dr,0x7FFFFFFF
         mov     fh,0x7F
         sdivsx  ax,dr,fh
         cmp     ax,0x0408
         bne     TestArus_WDBSErr
         mov     er,0x7FFFFFFF
         mov     gh,0x7F
         sremsx  bx,er,gh
         cmp     bx,0x0007
         bne     TestArus_WDBSErr
         mov     fr,0x7FFFFFFF
         mov     al,0x80
         addsx   cx,fr,al
         cmp     cx,0xFF7F
         bne     TestArus_WDBSErr
         mov     gr,0x7FFFFFFF
         mov     bl,0x80
         subsx   dx,gr,bl
         cmp     dx,0x007F
         bne     TestArus_WDBSErr
         mov     awx,0x7FFFFFFF
         mov     cl,0x80
         andsx   ex,awx,cl
         cmp     ex,0xFF80
         bne     TestArus_WDBSErr
         mov     bwx,0x7FFFFFFF
         mov     dl,0x80
         orsx    fx,bwx,dl
         cmp     fx,0xFFFF
         bne     TestArus_WDBSErr
         mov     cwx,0x7FFFFFFF
         mov     el,0x80
         xorsx   gx,cwx,el
         cmp     gx,0x007F
         bne     TestArus_WDBSErr
         mov     dwx,0x7FFFFFFF
         mov     fl,0x80
         mulsx   aw,dwx,fl
         cmp     aw,0x0080
         bne     TestArus_WDBSErr
         mov     ewx,0x7FFFFFFF
         mov     gl,0x80
         sdivsx  bw,ewx,gl
         cmp     bw,0x0001
         bne     TestArus_WDBSErr
         mov     fwx,0x7FFFFFFF
         mov     ah,0x80
         sremsx  cw,fwx,ah
         cmp     cw,0x007F
         bne     TestArus_WDBSErr
         mov     gwx,0x7FFFFFFF
         mov     bh,0xFF
         addsx   dw,gwx,bh
         cmp     dw,0xFFFE
         bne     TestArus_WDBSErr
         mov     ar,0x7FFFFFFF
         mov     ch,0xFF
         subsx   ew,ar,ch
         cmp     ew,0x0000
         bne     TestArus_WDBSErr
         mov     br,0x7FFFFFFF
         mov     dh,0xFF
         andsx   fw,br,dh
         cmp     fw,0xFFFF
         bne     TestArus_WDBSErr
         mov     cr,0x7FFFFFFF
         mov     eh,0xFF
         orsx    gw,cr,eh
         cmp     gw,0xFFFF
         bne     TestArus_WDBSErr
         mov     dr,0x7FFFFFFF
         mov     fh,0xFF
         xorsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x7FFFFFFF
         mov     gh,0xFF
         mulsx   bx,er,gh
         cmp     bx,0x0001
         bne     TestArus_WDBSErr
         mov     fr,0x7FFFFFFF
         mov     al,0xFF
         sdivsx  cx,fr,al
         cmp     cx,0x0001
         bne     TestArus_WDBSErr
         mov     gr,0x7FFFFFFF
         mov     bl,0xFF
         sremsx  dx,gr,bl
         cmp     dx,0x0000
         bne     TestArus_WDBSErr
         mov     awx,0x80000000
         mov     cl,0x80
         addsx   ex,awx,cl
         cmp     ex,0xFF80
         bne     TestArus_WDBSErr
         mov     bwx,0x80000000
         mov     dl,0x80
         subsx   fx,bwx,dl
         cmp     fx,0x0080
         bne     TestArus_WDBSErr
         mov     cwx,0x80000000
         mov     el,0x80
         andsx   gx,cwx,el
         cmp     gx,0x0000
         bne     TestArus_WDBSErr
         mov     dwx,0x80000000
         mov     fl,0x80
         orsx    aw,dwx,fl
         cmp     aw,0xFF80
         bne     TestArus_WDBSErr
         mov     ewx,0x80000000
         mov     gl,0x80
         xorsx   bw,ewx,gl
         cmp     bw,0xFF80
         bne     TestArus_WDBSErr
         mov     fwx,0x80000000
         mov     ah,0x80
         mulsx   cw,fwx,ah
         cmp     cw,0x0000
         bne     TestArus_WDBSErr
         mov     gwx,0x80000000
         mov     bh,0x80
         sdivsx  dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0x80000000
         mov     ch,0x80
         sremsx  ew,ar,ch
         cmp     ew,0x0000
         bne     TestArus_WDBSErr
         mov     br,0x80000000
         mov     dh,0xFF
         addsx   fw,br,dh
         cmp     fw,0xFFFF
         bne     TestArus_WDBSErr
         mov     cr,0x80000000
         mov     eh,0xFF
         subsx   gw,cr,eh
         cmp     gw,0x0001
         bne     TestArus_WDBSErr
         mov     dr,0x80000000
         mov     fh,0xFF
         andsx   ax,dr,fh
         cmp     ax,0x0000
         bne     TestArus_WDBSErr
         mov     er,0x80000000
         mov     gh,0xFF
         orsx    bx,er,gh
         cmp     bx,0xFFFF
         bne     TestArus_WDBSErr
         mov     fr,0x80000000
         mov     al,0xFF
         xorsx   cx,fr,al
         cmp     cx,0xFFFF
         bne     TestArus_WDBSErr
         mov     gr,0x80000000
         mov     bl,0xFF
         mulsx   dx,gr,bl
         cmp     dx,0x0000
         bne     TestArus_WDBSErr
         mov     awx,0x80000000
         mov     cl,0xFF
         sdivsx  ex,awx,cl
         cmp     ex,0x0000
         bne     TestArus_WDBSErr
         mov     bwx,0x80000000
         mov     dl,0xFF
         sremsx  fx,bwx,dl
         cmp     fx,0x0000
         bne     TestArus_WDBSErr
         mov     cwx,0xFFFFFFFF
         mov     el,0xFF
         addsx   gx,cwx,el
         cmp     gx,0xFFFE
         bne     TestArus_WDBSErr
         mov     dwx,0xFFFFFFFF
         mov     fl,0xFF
         subsx   aw,dwx,fl
         cmp     aw,0x0000
         bne     TestArus_WDBSErr
         mov     ewx,0xFFFFFFFF
         mov     gl,0xFF
         andsx   bw,ewx,gl
         cmp     bw,0xFFFF
         bne     TestArus_WDBSErr
         mov     fwx,0xFFFFFFFF
         mov     ah,0xFF
         orsx    cw,fwx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WDBSErr
         mov     gwx,0xFFFFFFFF
         mov     bh,0xFF
         xorsx   dw,gwx,bh
         cmp     dw,0x0000
         bne     TestArus_WDBSErr
         mov     ar,0xFFFFFFFF
         mov     ch,0xFF
         mulsx   ew,ar,ch
         cmp     ew,0x0001
         bne     TestArus_WDBSErr
         mov     br,0xFFFFFFFF
         mov     dh,0xFF
         sdivsx  fw,br,dh
         cmp     fw,0x0001
         bne     TestArus_WDBSErr
         mov     cr,0xFFFFFFFF
         mov     eh,0xFF
         sremsx  gw,cr,eh
         cmp     gw,0x0000
         bne     TestArus_WDBSErr
         bra     TestArus_WDBSRet
TestArus_WDBSErr:
         nop     
         trap    
         nop     
TestArus_WDBSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
