.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WBDS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WBDS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cwx,0x00000000
         addsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x00
         mov     dwx,0x00000000
         subsx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0x00
         mov     ewx,0x00000000
         andsx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x00
         mov     fwx,0x00000000
         orsx    aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x00
         mov     gwx,0x00000000
         xorsx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x00
         mov     ar,0x00000000
         mulsx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDSErr
         mov     gl,0x00
         mov     br,0x00000000
         sdivsx  dw,gl,br
         cmp     dw,0xFFFF
         bne     TestArus_WBDSErr
         mov     ah,0x00
         mov     cr,0x00000000
         sremsx  ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDSErr
         mov     bh,0x00
         mov     dr,0x00000001
         addsx   fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDSErr
         mov     ch,0x00
         mov     er,0x00000001
         subsx   gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDSErr
         mov     dh,0x00
         mov     fr,0x00000001
         andsx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x00
         mov     gr,0x00000001
         orsx    bx,eh,gr
         cmp     bx,0x0001
         bne     TestArus_WBDSErr
         mov     fh,0x00
         mov     awx,0x00000001
         xorsx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDSErr
         mov     gh,0x00
         mov     bwx,0x00000001
         mulsx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x00
         mov     cwx,0x00000001
         sdivsx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x00
         mov     dwx,0x00000001
         sremsx  fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0x00
         mov     ewx,0x00000008
         addsx   gx,cl,ewx
         cmp     gx,0x0008
         bne     TestArus_WBDSErr
         mov     dl,0x00
         mov     fwx,0x00000008
         subsx   aw,dl,fwx
         cmp     aw,0xFFF8
         bne     TestArus_WBDSErr
         mov     el,0x00
         mov     gwx,0x00000008
         andsx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x00
         mov     ar,0x00000008
         orsx    cw,fl,ar
         cmp     cw,0x0008
         bne     TestArus_WBDSErr
         mov     gl,0x00
         mov     br,0x00000008
         xorsx   dw,gl,br
         cmp     dw,0x0008
         bne     TestArus_WBDSErr
         mov     ah,0x00
         mov     cr,0x00000008
         mulsx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDSErr
         mov     bh,0x00
         mov     dr,0x00000008
         sdivsx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDSErr
         mov     ch,0x00
         mov     er,0x00000008
         sremsx  gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDSErr
         mov     dh,0x00
         mov     fr,0x00000009
         addsx   ax,dh,fr
         cmp     ax,0x0009
         bne     TestArus_WBDSErr
         mov     eh,0x00
         mov     gr,0x00000009
         subsx   bx,eh,gr
         cmp     bx,0xFFF7
         bne     TestArus_WBDSErr
         mov     fh,0x00
         mov     awx,0x00000009
         andsx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x00
         mov     bwx,0x00000009
         orsx    dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDSErr
         mov     al,0x00
         mov     cwx,0x00000009
         xorsx   ex,al,cwx
         cmp     ex,0x0009
         bne     TestArus_WBDSErr
         mov     bl,0x00
         mov     dwx,0x00000009
         mulsx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0x00
         mov     ewx,0x00000009
         sdivsx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x00
         mov     fwx,0x00000009
         sremsx  aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x00
         mov     gwx,0x00007FFF
         addsx   bw,el,gwx
         cmp     bw,0x7FFF
         bne     TestArus_WBDSErr
         mov     fl,0x00
         mov     ar,0x00007FFF
         subsx   cw,fl,ar
         cmp     cw,0x8001
         bne     TestArus_WBDSErr
         mov     gl,0x00
         mov     br,0x00007FFF
         andsx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x00
         mov     cr,0x00007FFF
         orsx    ew,ah,cr
         cmp     ew,0x7FFF
         bne     TestArus_WBDSErr
         mov     bh,0x00
         mov     dr,0x00007FFF
         xorsx   fw,bh,dr
         cmp     fw,0x7FFF
         bne     TestArus_WBDSErr
         mov     ch,0x00
         mov     er,0x00007FFF
         mulsx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDSErr
         mov     dh,0x00
         mov     fr,0x00007FFF
         sdivsx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x00
         mov     gr,0x00007FFF
         sremsx  bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDSErr
         mov     fh,0x00
         mov     awx,0x00008000
         addsx   cx,fh,awx
         cmp     cx,0x8000
         bne     TestArus_WBDSErr
         mov     gh,0x00
         mov     bwx,0x00008000
         subsx   dx,gh,bwx
         cmp     dx,0x8000
         bne     TestArus_WBDSErr
         mov     al,0x00
         mov     cwx,0x00008000
         andsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x00
         mov     dwx,0x00008000
         orsx    fx,bl,dwx
         cmp     fx,0x8000
         bne     TestArus_WBDSErr
         mov     cl,0x00
         mov     ewx,0x00008000
         xorsx   gx,cl,ewx
         cmp     gx,0x8000
         bne     TestArus_WBDSErr
         mov     dl,0x00
         mov     fwx,0x00008000
         mulsx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x00
         mov     gwx,0x00008000
         sdivsx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x00
         mov     ar,0x00008000
         sremsx  cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDSErr
         mov     gl,0x00
         mov     br,0x7FFFFFFF
         addsx   dw,gl,br
         cmp     dw,0xFFFF
         bne     TestArus_WBDSErr
         mov     ah,0x00
         mov     cr,0x7FFFFFFF
         subsx   ew,ah,cr
         cmp     ew,0x0001
         bne     TestArus_WBDSErr
         mov     bh,0x00
         mov     dr,0x7FFFFFFF
         andsx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDSErr
         mov     ch,0x00
         mov     er,0x7FFFFFFF
         orsx    gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDSErr
         mov     dh,0x00
         mov     fr,0x7FFFFFFF
         xorsx   ax,dh,fr
         cmp     ax,0xFFFF
         bne     TestArus_WBDSErr
         mov     eh,0x00
         mov     gr,0x7FFFFFFF
         mulsx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDSErr
         mov     fh,0x00
         mov     awx,0x7FFFFFFF
         sdivsx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x00
         mov     bwx,0x7FFFFFFF
         sremsx  dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x00
         mov     cwx,0x80000000
         addsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x00
         mov     dwx,0x80000000
         subsx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0x00
         mov     ewx,0x80000000
         andsx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x00
         mov     fwx,0x80000000
         orsx    aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x00
         mov     gwx,0x80000000
         xorsx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x00
         mov     ar,0x80000000
         mulsx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDSErr
         mov     gl,0x00
         mov     br,0x80000000
         sdivsx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x00
         mov     cr,0x80000000
         sremsx  ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDSErr
         mov     bh,0x00
         mov     dr,0xFFFFFFFF
         addsx   fw,bh,dr
         cmp     fw,0xFFFF
         bne     TestArus_WBDSErr
         mov     ch,0x00
         mov     er,0xFFFFFFFF
         subsx   gw,ch,er
         cmp     gw,0x0001
         bne     TestArus_WBDSErr
         mov     dh,0x00
         mov     fr,0xFFFFFFFF
         andsx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x00
         mov     gr,0xFFFFFFFF
         orsx    bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDSErr
         mov     fh,0x00
         mov     awx,0xFFFFFFFF
         xorsx   cx,fh,awx
         cmp     cx,0xFFFF
         bne     TestArus_WBDSErr
         mov     gh,0x00
         mov     bwx,0xFFFFFFFF
         mulsx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x00
         mov     cwx,0xFFFFFFFF
         sdivsx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x00
         mov     dwx,0xFFFFFFFF
         sremsx  fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0x01
         mov     ewx,0x00000001
         addsx   gx,cl,ewx
         cmp     gx,0x0002
         bne     TestArus_WBDSErr
         mov     dl,0x01
         mov     fwx,0x00000001
         subsx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x01
         mov     gwx,0x00000001
         andsx   bw,el,gwx
         cmp     bw,0x0001
         bne     TestArus_WBDSErr
         mov     fl,0x01
         mov     ar,0x00000001
         orsx    cw,fl,ar
         cmp     cw,0x0001
         bne     TestArus_WBDSErr
         mov     gl,0x01
         mov     br,0x00000001
         xorsx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x01
         mov     cr,0x00000001
         mulsx   ew,ah,cr
         cmp     ew,0x0001
         bne     TestArus_WBDSErr
         mov     bh,0x01
         mov     dr,0x00000001
         sdivsx  fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDSErr
         mov     ch,0x01
         mov     er,0x00000001
         sremsx  gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDSErr
         mov     dh,0x01
         mov     fr,0x00000008
         addsx   ax,dh,fr
         cmp     ax,0x0009
         bne     TestArus_WBDSErr
         mov     eh,0x01
         mov     gr,0x00000008
         subsx   bx,eh,gr
         cmp     bx,0xFFF9
         bne     TestArus_WBDSErr
         mov     fh,0x01
         mov     awx,0x00000008
         andsx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x01
         mov     bwx,0x00000008
         orsx    dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDSErr
         mov     al,0x01
         mov     cwx,0x00000008
         xorsx   ex,al,cwx
         cmp     ex,0x0009
         bne     TestArus_WBDSErr
         mov     bl,0x01
         mov     dwx,0x00000008
         mulsx   fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDSErr
         mov     cl,0x01
         mov     ewx,0x00000008
         sdivsx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x01
         mov     fwx,0x00000008
         sremsx  aw,dl,fwx
         cmp     aw,0x0001
         bne     TestArus_WBDSErr
         mov     el,0x01
         mov     gwx,0x00000009
         addsx   bw,el,gwx
         cmp     bw,0x000A
         bne     TestArus_WBDSErr
         mov     fl,0x01
         mov     ar,0x00000009
         subsx   cw,fl,ar
         cmp     cw,0xFFF8
         bne     TestArus_WBDSErr
         mov     gl,0x01
         mov     br,0x00000009
         andsx   dw,gl,br
         cmp     dw,0x0001
         bne     TestArus_WBDSErr
         mov     ah,0x01
         mov     cr,0x00000009
         orsx    ew,ah,cr
         cmp     ew,0x0009
         bne     TestArus_WBDSErr
         mov     bh,0x01
         mov     dr,0x00000009
         xorsx   fw,bh,dr
         cmp     fw,0x0008
         bne     TestArus_WBDSErr
         mov     ch,0x01
         mov     er,0x00000009
         mulsx   gw,ch,er
         cmp     gw,0x0009
         bne     TestArus_WBDSErr
         mov     dh,0x01
         mov     fr,0x00000009
         sdivsx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x01
         mov     gr,0x00000009
         sremsx  bx,eh,gr
         cmp     bx,0x0001
         bne     TestArus_WBDSErr
         mov     fh,0x01
         mov     awx,0x00007FFF
         addsx   cx,fh,awx
         cmp     cx,0x8000
         bne     TestArus_WBDSErr
         mov     gh,0x01
         mov     bwx,0x00007FFF
         subsx   dx,gh,bwx
         cmp     dx,0x8002
         bne     TestArus_WBDSErr
         mov     al,0x01
         mov     cwx,0x00007FFF
         andsx   ex,al,cwx
         cmp     ex,0x0001
         bne     TestArus_WBDSErr
         mov     bl,0x01
         mov     dwx,0x00007FFF
         orsx    fx,bl,dwx
         cmp     fx,0x7FFF
         bne     TestArus_WBDSErr
         mov     cl,0x01
         mov     ewx,0x00007FFF
         xorsx   gx,cl,ewx
         cmp     gx,0x7FFE
         bne     TestArus_WBDSErr
         mov     dl,0x01
         mov     fwx,0x00007FFF
         mulsx   aw,dl,fwx
         cmp     aw,0x7FFF
         bne     TestArus_WBDSErr
         mov     el,0x01
         mov     gwx,0x00007FFF
         sdivsx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x01
         mov     ar,0x00007FFF
         sremsx  cw,fl,ar
         cmp     cw,0x0001
         bne     TestArus_WBDSErr
         mov     gl,0x01
         mov     br,0x00008000
         addsx   dw,gl,br
         cmp     dw,0x8001
         bne     TestArus_WBDSErr
         mov     ah,0x01
         mov     cr,0x00008000
         subsx   ew,ah,cr
         cmp     ew,0x8001
         bne     TestArus_WBDSErr
         mov     bh,0x01
         mov     dr,0x00008000
         andsx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDSErr
         mov     ch,0x01
         mov     er,0x00008000
         orsx    gw,ch,er
         cmp     gw,0x8001
         bne     TestArus_WBDSErr
         mov     dh,0x01
         mov     fr,0x00008000
         xorsx   ax,dh,fr
         cmp     ax,0x8001
         bne     TestArus_WBDSErr
         mov     eh,0x01
         mov     gr,0x00008000
         mulsx   bx,eh,gr
         cmp     bx,0x8000
         bne     TestArus_WBDSErr
         mov     fh,0x01
         mov     awx,0x00008000
         sdivsx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x01
         mov     bwx,0x00008000
         sremsx  dx,gh,bwx
         cmp     dx,0x0001
         bne     TestArus_WBDSErr
         mov     al,0x01
         mov     cwx,0x7FFFFFFF
         addsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x01
         mov     dwx,0x7FFFFFFF
         subsx   fx,bl,dwx
         cmp     fx,0x0002
         bne     TestArus_WBDSErr
         mov     cl,0x01
         mov     ewx,0x7FFFFFFF
         andsx   gx,cl,ewx
         cmp     gx,0x0001
         bne     TestArus_WBDSErr
         mov     dl,0x01
         mov     fwx,0x7FFFFFFF
         orsx    aw,dl,fwx
         cmp     aw,0xFFFF
         bne     TestArus_WBDSErr
         mov     el,0x01
         mov     gwx,0x7FFFFFFF
         xorsx   bw,el,gwx
         cmp     bw,0xFFFE
         bne     TestArus_WBDSErr
         mov     fl,0x01
         mov     ar,0x7FFFFFFF
         mulsx   cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDSErr
         mov     gl,0x01
         mov     br,0x7FFFFFFF
         sdivsx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x01
         mov     cr,0x7FFFFFFF
         sremsx  ew,ah,cr
         cmp     ew,0x0001
         bne     TestArus_WBDSErr
         mov     bh,0x01
         mov     dr,0x80000000
         addsx   fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDSErr
         mov     ch,0x01
         mov     er,0x80000000
         subsx   gw,ch,er
         cmp     gw,0x0001
         bne     TestArus_WBDSErr
         mov     dh,0x01
         mov     fr,0x80000000
         andsx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x01
         mov     gr,0x80000000
         orsx    bx,eh,gr
         cmp     bx,0x0001
         bne     TestArus_WBDSErr
         mov     fh,0x01
         mov     awx,0x80000000
         xorsx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDSErr
         mov     gh,0x01
         mov     bwx,0x80000000
         mulsx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x01
         mov     cwx,0x80000000
         sdivsx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x01
         mov     dwx,0x80000000
         sremsx  fx,bl,dwx
         cmp     fx,0x0001
         bne     TestArus_WBDSErr
         mov     cl,0x01
         mov     ewx,0xFFFFFFFF
         addsx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x01
         mov     fwx,0xFFFFFFFF
         subsx   aw,dl,fwx
         cmp     aw,0x0002
         bne     TestArus_WBDSErr
         mov     el,0x01
         mov     gwx,0xFFFFFFFF
         andsx   bw,el,gwx
         cmp     bw,0x0001
         bne     TestArus_WBDSErr
         mov     fl,0x01
         mov     ar,0xFFFFFFFF
         orsx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDSErr
         mov     gl,0x01
         mov     br,0xFFFFFFFF
         xorsx   dw,gl,br
         cmp     dw,0xFFFE
         bne     TestArus_WBDSErr
         mov     ah,0x01
         mov     cr,0xFFFFFFFF
         mulsx   ew,ah,cr
         cmp     ew,0xFFFF
         bne     TestArus_WBDSErr
         mov     bh,0x01
         mov     dr,0xFFFFFFFF
         sdivsx  fw,bh,dr
         cmp     fw,0xFFFF
         bne     TestArus_WBDSErr
         mov     ch,0x01
         mov     er,0xFFFFFFFF
         sremsx  gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDSErr
         mov     dh,0x07
         mov     fr,0x00000008
         addsx   ax,dh,fr
         cmp     ax,0x000F
         bne     TestArus_WBDSErr
         mov     eh,0x07
         mov     gr,0x00000008
         subsx   bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDSErr
         mov     fh,0x07
         mov     awx,0x00000008
         andsx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x07
         mov     bwx,0x00000008
         orsx    dx,gh,bwx
         cmp     dx,0x000F
         bne     TestArus_WBDSErr
         mov     al,0x07
         mov     cwx,0x00000008
         xorsx   ex,al,cwx
         cmp     ex,0x000F
         bne     TestArus_WBDSErr
         mov     bl,0x07
         mov     dwx,0x00000008
         mulsx   fx,bl,dwx
         cmp     fx,0x0038
         bne     TestArus_WBDSErr
         mov     cl,0x07
         mov     ewx,0x00000008
         sdivsx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x07
         mov     fwx,0x00000008
         sremsx  aw,dl,fwx
         cmp     aw,0x0007
         bne     TestArus_WBDSErr
         mov     el,0x07
         mov     gwx,0x00000009
         addsx   bw,el,gwx
         cmp     bw,0x0010
         bne     TestArus_WBDSErr
         mov     fl,0x07
         mov     ar,0x00000009
         subsx   cw,fl,ar
         cmp     cw,0xFFFE
         bne     TestArus_WBDSErr
         mov     gl,0x07
         mov     br,0x00000009
         andsx   dw,gl,br
         cmp     dw,0x0001
         bne     TestArus_WBDSErr
         mov     ah,0x07
         mov     cr,0x00000009
         orsx    ew,ah,cr
         cmp     ew,0x000F
         bne     TestArus_WBDSErr
         mov     bh,0x07
         mov     dr,0x00000009
         xorsx   fw,bh,dr
         cmp     fw,0x000E
         bne     TestArus_WBDSErr
         mov     ch,0x07
         mov     er,0x00000009
         mulsx   gw,ch,er
         cmp     gw,0x003F
         bne     TestArus_WBDSErr
         mov     dh,0x07
         mov     fr,0x00000009
         sdivsx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x07
         mov     gr,0x00000009
         sremsx  bx,eh,gr
         cmp     bx,0x0007
         bne     TestArus_WBDSErr
         mov     fh,0x07
         mov     awx,0x00007FFF
         addsx   cx,fh,awx
         cmp     cx,0x8006
         bne     TestArus_WBDSErr
         mov     gh,0x07
         mov     bwx,0x00007FFF
         subsx   dx,gh,bwx
         cmp     dx,0x8008
         bne     TestArus_WBDSErr
         mov     al,0x07
         mov     cwx,0x00007FFF
         andsx   ex,al,cwx
         cmp     ex,0x0007
         bne     TestArus_WBDSErr
         mov     bl,0x07
         mov     dwx,0x00007FFF
         orsx    fx,bl,dwx
         cmp     fx,0x7FFF
         bne     TestArus_WBDSErr
         mov     cl,0x07
         mov     ewx,0x00007FFF
         xorsx   gx,cl,ewx
         cmp     gx,0x7FF8
         bne     TestArus_WBDSErr
         mov     dl,0x07
         mov     fwx,0x00007FFF
         mulsx   aw,dl,fwx
         cmp     aw,0x7FF9
         bne     TestArus_WBDSErr
         mov     el,0x07
         mov     gwx,0x00007FFF
         sdivsx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x07
         mov     ar,0x00007FFF
         sremsx  cw,fl,ar
         cmp     cw,0x0007
         bne     TestArus_WBDSErr
         mov     gl,0x07
         mov     br,0x00008000
         addsx   dw,gl,br
         cmp     dw,0x8007
         bne     TestArus_WBDSErr
         mov     ah,0x07
         mov     cr,0x00008000
         subsx   ew,ah,cr
         cmp     ew,0x8007
         bne     TestArus_WBDSErr
         mov     bh,0x07
         mov     dr,0x00008000
         andsx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDSErr
         mov     ch,0x07
         mov     er,0x00008000
         orsx    gw,ch,er
         cmp     gw,0x8007
         bne     TestArus_WBDSErr
         mov     dh,0x07
         mov     fr,0x00008000
         xorsx   ax,dh,fr
         cmp     ax,0x8007
         bne     TestArus_WBDSErr
         mov     eh,0x07
         mov     gr,0x00008000
         mulsx   bx,eh,gr
         cmp     bx,0x8000
         bne     TestArus_WBDSErr
         mov     fh,0x07
         mov     awx,0x00008000
         sdivsx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x07
         mov     bwx,0x00008000
         sremsx  dx,gh,bwx
         cmp     dx,0x0007
         bne     TestArus_WBDSErr
         mov     al,0x07
         mov     cwx,0x7FFFFFFF
         addsx   ex,al,cwx
         cmp     ex,0x0006
         bne     TestArus_WBDSErr
         mov     bl,0x07
         mov     dwx,0x7FFFFFFF
         subsx   fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDSErr
         mov     cl,0x07
         mov     ewx,0x7FFFFFFF
         andsx   gx,cl,ewx
         cmp     gx,0x0007
         bne     TestArus_WBDSErr
         mov     dl,0x07
         mov     fwx,0x7FFFFFFF
         orsx    aw,dl,fwx
         cmp     aw,0xFFFF
         bne     TestArus_WBDSErr
         mov     el,0x07
         mov     gwx,0x7FFFFFFF
         xorsx   bw,el,gwx
         cmp     bw,0xFFF8
         bne     TestArus_WBDSErr
         mov     fl,0x07
         mov     ar,0x7FFFFFFF
         mulsx   cw,fl,ar
         cmp     cw,0xFFF9
         bne     TestArus_WBDSErr
         mov     gl,0x07
         mov     br,0x7FFFFFFF
         sdivsx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x07
         mov     cr,0x7FFFFFFF
         sremsx  ew,ah,cr
         cmp     ew,0x0007
         bne     TestArus_WBDSErr
         mov     bh,0x07
         mov     dr,0x80000000
         addsx   fw,bh,dr
         cmp     fw,0x0007
         bne     TestArus_WBDSErr
         mov     ch,0x07
         mov     er,0x80000000
         subsx   gw,ch,er
         cmp     gw,0x0007
         bne     TestArus_WBDSErr
         mov     dh,0x07
         mov     fr,0x80000000
         andsx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x07
         mov     gr,0x80000000
         orsx    bx,eh,gr
         cmp     bx,0x0007
         bne     TestArus_WBDSErr
         mov     fh,0x07
         mov     awx,0x80000000
         xorsx   cx,fh,awx
         cmp     cx,0x0007
         bne     TestArus_WBDSErr
         mov     gh,0x07
         mov     bwx,0x80000000
         mulsx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x07
         mov     cwx,0x80000000
         sdivsx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x07
         mov     dwx,0x80000000
         sremsx  fx,bl,dwx
         cmp     fx,0x0007
         bne     TestArus_WBDSErr
         mov     cl,0x07
         mov     ewx,0xFFFFFFFF
         addsx   gx,cl,ewx
         cmp     gx,0x0006
         bne     TestArus_WBDSErr
         mov     dl,0x07
         mov     fwx,0xFFFFFFFF
         subsx   aw,dl,fwx
         cmp     aw,0x0008
         bne     TestArus_WBDSErr
         mov     el,0x07
         mov     gwx,0xFFFFFFFF
         andsx   bw,el,gwx
         cmp     bw,0x0007
         bne     TestArus_WBDSErr
         mov     fl,0x07
         mov     ar,0xFFFFFFFF
         orsx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDSErr
         mov     gl,0x07
         mov     br,0xFFFFFFFF
         xorsx   dw,gl,br
         cmp     dw,0xFFF8
         bne     TestArus_WBDSErr
         mov     ah,0x07
         mov     cr,0xFFFFFFFF
         mulsx   ew,ah,cr
         cmp     ew,0xFFF9
         bne     TestArus_WBDSErr
         mov     bh,0x07
         mov     dr,0xFFFFFFFF
         sdivsx  fw,bh,dr
         cmp     fw,0xFFF9
         bne     TestArus_WBDSErr
         mov     ch,0x07
         mov     er,0xFFFFFFFF
         sremsx  gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDSErr
         mov     dh,0x08
         mov     fr,0x00000009
         addsx   ax,dh,fr
         cmp     ax,0x0011
         bne     TestArus_WBDSErr
         mov     eh,0x08
         mov     gr,0x00000009
         subsx   bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDSErr
         mov     fh,0x08
         mov     awx,0x00000009
         andsx   cx,fh,awx
         cmp     cx,0x0008
         bne     TestArus_WBDSErr
         mov     gh,0x08
         mov     bwx,0x00000009
         orsx    dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDSErr
         mov     al,0x08
         mov     cwx,0x00000009
         xorsx   ex,al,cwx
         cmp     ex,0x0001
         bne     TestArus_WBDSErr
         mov     bl,0x08
         mov     dwx,0x00000009
         mulsx   fx,bl,dwx
         cmp     fx,0x0048
         bne     TestArus_WBDSErr
         mov     cl,0x08
         mov     ewx,0x00000009
         sdivsx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x08
         mov     fwx,0x00000009
         sremsx  aw,dl,fwx
         cmp     aw,0x0008
         bne     TestArus_WBDSErr
         mov     el,0x08
         mov     gwx,0x00007FFF
         addsx   bw,el,gwx
         cmp     bw,0x8007
         bne     TestArus_WBDSErr
         mov     fl,0x08
         mov     ar,0x00007FFF
         subsx   cw,fl,ar
         cmp     cw,0x8009
         bne     TestArus_WBDSErr
         mov     gl,0x08
         mov     br,0x00007FFF
         andsx   dw,gl,br
         cmp     dw,0x0008
         bne     TestArus_WBDSErr
         mov     ah,0x08
         mov     cr,0x00007FFF
         orsx    ew,ah,cr
         cmp     ew,0x7FFF
         bne     TestArus_WBDSErr
         mov     bh,0x08
         mov     dr,0x00007FFF
         xorsx   fw,bh,dr
         cmp     fw,0x7FF7
         bne     TestArus_WBDSErr
         mov     ch,0x08
         mov     er,0x00007FFF
         mulsx   gw,ch,er
         cmp     gw,0xFFF8
         bne     TestArus_WBDSErr
         mov     dh,0x08
         mov     fr,0x00007FFF
         sdivsx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x08
         mov     gr,0x00007FFF
         sremsx  bx,eh,gr
         cmp     bx,0x0008
         bne     TestArus_WBDSErr
         mov     fh,0x08
         mov     awx,0x00008000
         addsx   cx,fh,awx
         cmp     cx,0x8008
         bne     TestArus_WBDSErr
         mov     gh,0x08
         mov     bwx,0x00008000
         subsx   dx,gh,bwx
         cmp     dx,0x8008
         bne     TestArus_WBDSErr
         mov     al,0x08
         mov     cwx,0x00008000
         andsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x08
         mov     dwx,0x00008000
         orsx    fx,bl,dwx
         cmp     fx,0x8008
         bne     TestArus_WBDSErr
         mov     cl,0x08
         mov     ewx,0x00008000
         xorsx   gx,cl,ewx
         cmp     gx,0x8008
         bne     TestArus_WBDSErr
         mov     dl,0x08
         mov     fwx,0x00008000
         mulsx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x08
         mov     gwx,0x00008000
         sdivsx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x08
         mov     ar,0x00008000
         sremsx  cw,fl,ar
         cmp     cw,0x0008
         bne     TestArus_WBDSErr
         mov     gl,0x08
         mov     br,0x7FFFFFFF
         addsx   dw,gl,br
         cmp     dw,0x0007
         bne     TestArus_WBDSErr
         mov     ah,0x08
         mov     cr,0x7FFFFFFF
         subsx   ew,ah,cr
         cmp     ew,0x0009
         bne     TestArus_WBDSErr
         mov     bh,0x08
         mov     dr,0x7FFFFFFF
         andsx   fw,bh,dr
         cmp     fw,0x0008
         bne     TestArus_WBDSErr
         mov     ch,0x08
         mov     er,0x7FFFFFFF
         orsx    gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDSErr
         mov     dh,0x08
         mov     fr,0x7FFFFFFF
         xorsx   ax,dh,fr
         cmp     ax,0xFFF7
         bne     TestArus_WBDSErr
         mov     eh,0x08
         mov     gr,0x7FFFFFFF
         mulsx   bx,eh,gr
         cmp     bx,0xFFF8
         bne     TestArus_WBDSErr
         mov     fh,0x08
         mov     awx,0x7FFFFFFF
         sdivsx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x08
         mov     bwx,0x7FFFFFFF
         sremsx  dx,gh,bwx
         cmp     dx,0x0008
         bne     TestArus_WBDSErr
         mov     al,0x08
         mov     cwx,0x80000000
         addsx   ex,al,cwx
         cmp     ex,0x0008
         bne     TestArus_WBDSErr
         mov     bl,0x08
         mov     dwx,0x80000000
         subsx   fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDSErr
         mov     cl,0x08
         mov     ewx,0x80000000
         andsx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x08
         mov     fwx,0x80000000
         orsx    aw,dl,fwx
         cmp     aw,0x0008
         bne     TestArus_WBDSErr
         mov     el,0x08
         mov     gwx,0x80000000
         xorsx   bw,el,gwx
         cmp     bw,0x0008
         bne     TestArus_WBDSErr
         mov     fl,0x08
         mov     ar,0x80000000
         mulsx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDSErr
         mov     gl,0x08
         mov     br,0x80000000
         sdivsx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x08
         mov     cr,0x80000000
         sremsx  ew,ah,cr
         cmp     ew,0x0008
         bne     TestArus_WBDSErr
         mov     bh,0x08
         mov     dr,0xFFFFFFFF
         addsx   fw,bh,dr
         cmp     fw,0x0007
         bne     TestArus_WBDSErr
         mov     ch,0x08
         mov     er,0xFFFFFFFF
         subsx   gw,ch,er
         cmp     gw,0x0009
         bne     TestArus_WBDSErr
         mov     dh,0x08
         mov     fr,0xFFFFFFFF
         andsx   ax,dh,fr
         cmp     ax,0x0008
         bne     TestArus_WBDSErr
         mov     eh,0x08
         mov     gr,0xFFFFFFFF
         orsx    bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDSErr
         mov     fh,0x08
         mov     awx,0xFFFFFFFF
         xorsx   cx,fh,awx
         cmp     cx,0xFFF7
         bne     TestArus_WBDSErr
         mov     gh,0x08
         mov     bwx,0xFFFFFFFF
         mulsx   dx,gh,bwx
         cmp     dx,0xFFF8
         bne     TestArus_WBDSErr
         mov     al,0x08
         mov     cwx,0xFFFFFFFF
         sdivsx  ex,al,cwx
         cmp     ex,0xFFF8
         bne     TestArus_WBDSErr
         mov     bl,0x08
         mov     dwx,0xFFFFFFFF
         sremsx  fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0x09
         mov     ewx,0x00007FFF
         addsx   gx,cl,ewx
         cmp     gx,0x8008
         bne     TestArus_WBDSErr
         mov     dl,0x09
         mov     fwx,0x00007FFF
         subsx   aw,dl,fwx
         cmp     aw,0x800A
         bne     TestArus_WBDSErr
         mov     el,0x09
         mov     gwx,0x00007FFF
         andsx   bw,el,gwx
         cmp     bw,0x0009
         bne     TestArus_WBDSErr
         mov     fl,0x09
         mov     ar,0x00007FFF
         orsx    cw,fl,ar
         cmp     cw,0x7FFF
         bne     TestArus_WBDSErr
         mov     gl,0x09
         mov     br,0x00007FFF
         xorsx   dw,gl,br
         cmp     dw,0x7FF6
         bne     TestArus_WBDSErr
         mov     ah,0x09
         mov     cr,0x00007FFF
         mulsx   ew,ah,cr
         cmp     ew,0x7FF7
         bne     TestArus_WBDSErr
         mov     bh,0x09
         mov     dr,0x00007FFF
         sdivsx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDSErr
         mov     ch,0x09
         mov     er,0x00007FFF
         sremsx  gw,ch,er
         cmp     gw,0x0009
         bne     TestArus_WBDSErr
         mov     dh,0x09
         mov     fr,0x00008000
         addsx   ax,dh,fr
         cmp     ax,0x8009
         bne     TestArus_WBDSErr
         mov     eh,0x09
         mov     gr,0x00008000
         subsx   bx,eh,gr
         cmp     bx,0x8009
         bne     TestArus_WBDSErr
         mov     fh,0x09
         mov     awx,0x00008000
         andsx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDSErr
         mov     gh,0x09
         mov     bwx,0x00008000
         orsx    dx,gh,bwx
         cmp     dx,0x8009
         bne     TestArus_WBDSErr
         mov     al,0x09
         mov     cwx,0x00008000
         xorsx   ex,al,cwx
         cmp     ex,0x8009
         bne     TestArus_WBDSErr
         mov     bl,0x09
         mov     dwx,0x00008000
         mulsx   fx,bl,dwx
         cmp     fx,0x8000
         bne     TestArus_WBDSErr
         mov     cl,0x09
         mov     ewx,0x00008000
         sdivsx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x09
         mov     fwx,0x00008000
         sremsx  aw,dl,fwx
         cmp     aw,0x0009
         bne     TestArus_WBDSErr
         mov     el,0x09
         mov     gwx,0x7FFFFFFF
         addsx   bw,el,gwx
         cmp     bw,0x0008
         bne     TestArus_WBDSErr
         mov     fl,0x09
         mov     ar,0x7FFFFFFF
         subsx   cw,fl,ar
         cmp     cw,0x000A
         bne     TestArus_WBDSErr
         mov     gl,0x09
         mov     br,0x7FFFFFFF
         andsx   dw,gl,br
         cmp     dw,0x0009
         bne     TestArus_WBDSErr
         mov     ah,0x09
         mov     cr,0x7FFFFFFF
         orsx    ew,ah,cr
         cmp     ew,0xFFFF
         bne     TestArus_WBDSErr
         mov     bh,0x09
         mov     dr,0x7FFFFFFF
         xorsx   fw,bh,dr
         cmp     fw,0xFFF6
         bne     TestArus_WBDSErr
         mov     ch,0x09
         mov     er,0x7FFFFFFF
         mulsx   gw,ch,er
         cmp     gw,0xFFF7
         bne     TestArus_WBDSErr
         mov     dh,0x09
         mov     fr,0x7FFFFFFF
         sdivsx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x09
         mov     gr,0x7FFFFFFF
         sremsx  bx,eh,gr
         cmp     bx,0x0009
         bne     TestArus_WBDSErr
         mov     fh,0x09
         mov     awx,0x80000000
         addsx   cx,fh,awx
         cmp     cx,0x0009
         bne     TestArus_WBDSErr
         mov     gh,0x09
         mov     bwx,0x80000000
         subsx   dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDSErr
         mov     al,0x09
         mov     cwx,0x80000000
         andsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x09
         mov     dwx,0x80000000
         orsx    fx,bl,dwx
         cmp     fx,0x0009
         bne     TestArus_WBDSErr
         mov     cl,0x09
         mov     ewx,0x80000000
         xorsx   gx,cl,ewx
         cmp     gx,0x0009
         bne     TestArus_WBDSErr
         mov     dl,0x09
         mov     fwx,0x80000000
         mulsx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x09
         mov     gwx,0x80000000
         sdivsx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x09
         mov     ar,0x80000000
         sremsx  cw,fl,ar
         cmp     cw,0x0009
         bne     TestArus_WBDSErr
         mov     gl,0x09
         mov     br,0xFFFFFFFF
         addsx   dw,gl,br
         cmp     dw,0x0008
         bne     TestArus_WBDSErr
         mov     ah,0x09
         mov     cr,0xFFFFFFFF
         subsx   ew,ah,cr
         cmp     ew,0x000A
         bne     TestArus_WBDSErr
         mov     bh,0x09
         mov     dr,0xFFFFFFFF
         andsx   fw,bh,dr
         cmp     fw,0x0009
         bne     TestArus_WBDSErr
         mov     ch,0x09
         mov     er,0xFFFFFFFF
         orsx    gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDSErr
         mov     dh,0x09
         mov     fr,0xFFFFFFFF
         xorsx   ax,dh,fr
         cmp     ax,0xFFF6
         bne     TestArus_WBDSErr
         mov     eh,0x09
         mov     gr,0xFFFFFFFF
         mulsx   bx,eh,gr
         cmp     bx,0xFFF7
         bne     TestArus_WBDSErr
         mov     fh,0x09
         mov     awx,0xFFFFFFFF
         sdivsx  cx,fh,awx
         cmp     cx,0xFFF7
         bne     TestArus_WBDSErr
         mov     gh,0x09
         mov     bwx,0xFFFFFFFF
         sremsx  dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x0F
         mov     cwx,0x00008000
         addsx   ex,al,cwx
         cmp     ex,0x800F
         bne     TestArus_WBDSErr
         mov     bl,0x0F
         mov     dwx,0x00008000
         subsx   fx,bl,dwx
         cmp     fx,0x800F
         bne     TestArus_WBDSErr
         mov     cl,0x0F
         mov     ewx,0x00008000
         andsx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x0F
         mov     fwx,0x00008000
         orsx    aw,dl,fwx
         cmp     aw,0x800F
         bne     TestArus_WBDSErr
         mov     el,0x0F
         mov     gwx,0x00008000
         xorsx   bw,el,gwx
         cmp     bw,0x800F
         bne     TestArus_WBDSErr
         mov     fl,0x0F
         mov     ar,0x00008000
         mulsx   cw,fl,ar
         cmp     cw,0x8000
         bne     TestArus_WBDSErr
         mov     gl,0x0F
         mov     br,0x00008000
         sdivsx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x0F
         mov     cr,0x00008000
         sremsx  ew,ah,cr
         cmp     ew,0x000F
         bne     TestArus_WBDSErr
         mov     bh,0x0F
         mov     dr,0x7FFFFFFF
         addsx   fw,bh,dr
         cmp     fw,0x000E
         bne     TestArus_WBDSErr
         mov     ch,0x0F
         mov     er,0x7FFFFFFF
         subsx   gw,ch,er
         cmp     gw,0x0010
         bne     TestArus_WBDSErr
         mov     dh,0x0F
         mov     fr,0x7FFFFFFF
         andsx   ax,dh,fr
         cmp     ax,0x000F
         bne     TestArus_WBDSErr
         mov     eh,0x0F
         mov     gr,0x7FFFFFFF
         orsx    bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDSErr
         mov     fh,0x0F
         mov     awx,0x7FFFFFFF
         xorsx   cx,fh,awx
         cmp     cx,0xFFF0
         bne     TestArus_WBDSErr
         mov     gh,0x0F
         mov     bwx,0x7FFFFFFF
         mulsx   dx,gh,bwx
         cmp     dx,0xFFF1
         bne     TestArus_WBDSErr
         mov     al,0x0F
         mov     cwx,0x7FFFFFFF
         sdivsx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x0F
         mov     dwx,0x7FFFFFFF
         sremsx  fx,bl,dwx
         cmp     fx,0x000F
         bne     TestArus_WBDSErr
         mov     cl,0x0F
         mov     ewx,0x80000000
         addsx   gx,cl,ewx
         cmp     gx,0x000F
         bne     TestArus_WBDSErr
         mov     dl,0x0F
         mov     fwx,0x80000000
         subsx   aw,dl,fwx
         cmp     aw,0x000F
         bne     TestArus_WBDSErr
         mov     el,0x0F
         mov     gwx,0x80000000
         andsx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x0F
         mov     ar,0x80000000
         orsx    cw,fl,ar
         cmp     cw,0x000F
         bne     TestArus_WBDSErr
         mov     gl,0x0F
         mov     br,0x80000000
         xorsx   dw,gl,br
         cmp     dw,0x000F
         bne     TestArus_WBDSErr
         mov     ah,0x0F
         mov     cr,0x80000000
         mulsx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDSErr
         mov     bh,0x0F
         mov     dr,0x80000000
         sdivsx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDSErr
         mov     ch,0x0F
         mov     er,0x80000000
         sremsx  gw,ch,er
         cmp     gw,0x000F
         bne     TestArus_WBDSErr
         mov     dh,0x0F
         mov     fr,0xFFFFFFFF
         addsx   ax,dh,fr
         cmp     ax,0x000E
         bne     TestArus_WBDSErr
         mov     eh,0x0F
         mov     gr,0xFFFFFFFF
         subsx   bx,eh,gr
         cmp     bx,0x0010
         bne     TestArus_WBDSErr
         mov     fh,0x0F
         mov     awx,0xFFFFFFFF
         andsx   cx,fh,awx
         cmp     cx,0x000F
         bne     TestArus_WBDSErr
         mov     gh,0x0F
         mov     bwx,0xFFFFFFFF
         orsx    dx,gh,bwx
         cmp     dx,0xFFFF
         bne     TestArus_WBDSErr
         mov     al,0x0F
         mov     cwx,0xFFFFFFFF
         xorsx   ex,al,cwx
         cmp     ex,0xFFF0
         bne     TestArus_WBDSErr
         mov     bl,0x0F
         mov     dwx,0xFFFFFFFF
         mulsx   fx,bl,dwx
         cmp     fx,0xFFF1
         bne     TestArus_WBDSErr
         mov     cl,0x0F
         mov     ewx,0xFFFFFFFF
         sdivsx  gx,cl,ewx
         cmp     gx,0xFFF1
         bne     TestArus_WBDSErr
         mov     dl,0x0F
         mov     fwx,0xFFFFFFFF
         sremsx  aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x7F
         mov     gwx,0x7FFFFFFF
         addsx   bw,el,gwx
         cmp     bw,0x007E
         bne     TestArus_WBDSErr
         mov     fl,0x7F
         mov     ar,0x7FFFFFFF
         subsx   cw,fl,ar
         cmp     cw,0x0080
         bne     TestArus_WBDSErr
         mov     gl,0x7F
         mov     br,0x7FFFFFFF
         andsx   dw,gl,br
         cmp     dw,0x007F
         bne     TestArus_WBDSErr
         mov     ah,0x7F
         mov     cr,0x7FFFFFFF
         orsx    ew,ah,cr
         cmp     ew,0xFFFF
         bne     TestArus_WBDSErr
         mov     bh,0x7F
         mov     dr,0x7FFFFFFF
         xorsx   fw,bh,dr
         cmp     fw,0xFF80
         bne     TestArus_WBDSErr
         mov     ch,0x7F
         mov     er,0x7FFFFFFF
         mulsx   gw,ch,er
         cmp     gw,0xFF81
         bne     TestArus_WBDSErr
         mov     dh,0x7F
         mov     fr,0x7FFFFFFF
         sdivsx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDSErr
         mov     eh,0x7F
         mov     gr,0x7FFFFFFF
         sremsx  bx,eh,gr
         cmp     bx,0x007F
         bne     TestArus_WBDSErr
         mov     fh,0x7F
         mov     awx,0x80000000
         addsx   cx,fh,awx
         cmp     cx,0x007F
         bne     TestArus_WBDSErr
         mov     gh,0x7F
         mov     bwx,0x80000000
         subsx   dx,gh,bwx
         cmp     dx,0x007F
         bne     TestArus_WBDSErr
         mov     al,0x7F
         mov     cwx,0x80000000
         andsx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDSErr
         mov     bl,0x7F
         mov     dwx,0x80000000
         orsx    fx,bl,dwx
         cmp     fx,0x007F
         bne     TestArus_WBDSErr
         mov     cl,0x7F
         mov     ewx,0x80000000
         xorsx   gx,cl,ewx
         cmp     gx,0x007F
         bne     TestArus_WBDSErr
         mov     dl,0x7F
         mov     fwx,0x80000000
         mulsx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0x7F
         mov     gwx,0x80000000
         sdivsx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDSErr
         mov     fl,0x7F
         mov     ar,0x80000000
         sremsx  cw,fl,ar
         cmp     cw,0x007F
         bne     TestArus_WBDSErr
         mov     gl,0x7F
         mov     br,0xFFFFFFFF
         addsx   dw,gl,br
         cmp     dw,0x007E
         bne     TestArus_WBDSErr
         mov     ah,0x7F
         mov     cr,0xFFFFFFFF
         subsx   ew,ah,cr
         cmp     ew,0x0080
         bne     TestArus_WBDSErr
         mov     bh,0x7F
         mov     dr,0xFFFFFFFF
         andsx   fw,bh,dr
         cmp     fw,0x007F
         bne     TestArus_WBDSErr
         mov     ch,0x7F
         mov     er,0xFFFFFFFF
         orsx    gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDSErr
         mov     dh,0x7F
         mov     fr,0xFFFFFFFF
         xorsx   ax,dh,fr
         cmp     ax,0xFF80
         bne     TestArus_WBDSErr
         mov     eh,0x7F
         mov     gr,0xFFFFFFFF
         mulsx   bx,eh,gr
         cmp     bx,0xFF81
         bne     TestArus_WBDSErr
         mov     fh,0x7F
         mov     awx,0xFFFFFFFF
         sdivsx  cx,fh,awx
         cmp     cx,0xFF81
         bne     TestArus_WBDSErr
         mov     gh,0x7F
         mov     bwx,0xFFFFFFFF
         sremsx  dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDSErr
         mov     al,0x80
         mov     cwx,0x80000000
         addsx   ex,al,cwx
         cmp     ex,0xFF80
         bne     TestArus_WBDSErr
         mov     bl,0x80
         mov     dwx,0x80000000
         subsx   fx,bl,dwx
         cmp     fx,0xFF80
         bne     TestArus_WBDSErr
         mov     cl,0x80
         mov     ewx,0x80000000
         andsx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDSErr
         mov     dl,0x80
         mov     fwx,0x80000000
         orsx    aw,dl,fwx
         cmp     aw,0xFF80
         bne     TestArus_WBDSErr
         mov     el,0x80
         mov     gwx,0x80000000
         xorsx   bw,el,gwx
         cmp     bw,0xFF80
         bne     TestArus_WBDSErr
         mov     fl,0x80
         mov     ar,0x80000000
         mulsx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDSErr
         mov     gl,0x80
         mov     br,0x80000000
         sdivsx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0x80
         mov     cr,0x80000000
         sremsx  ew,ah,cr
         cmp     ew,0xFF80
         bne     TestArus_WBDSErr
         mov     bh,0x80
         mov     dr,0xFFFFFFFF
         addsx   fw,bh,dr
         cmp     fw,0xFF7F
         bne     TestArus_WBDSErr
         mov     ch,0x80
         mov     er,0xFFFFFFFF
         subsx   gw,ch,er
         cmp     gw,0xFF81
         bne     TestArus_WBDSErr
         mov     dh,0x80
         mov     fr,0xFFFFFFFF
         andsx   ax,dh,fr
         cmp     ax,0xFF80
         bne     TestArus_WBDSErr
         mov     eh,0x80
         mov     gr,0xFFFFFFFF
         orsx    bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDSErr
         mov     fh,0x80
         mov     awx,0xFFFFFFFF
         xorsx   cx,fh,awx
         cmp     cx,0x007F
         bne     TestArus_WBDSErr
         mov     gh,0x80
         mov     bwx,0xFFFFFFFF
         mulsx   dx,gh,bwx
         cmp     dx,0x0080
         bne     TestArus_WBDSErr
         mov     al,0x80
         mov     cwx,0xFFFFFFFF
         sdivsx  ex,al,cwx
         cmp     ex,0x0080
         bne     TestArus_WBDSErr
         mov     bl,0x80
         mov     dwx,0xFFFFFFFF
         sremsx  fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDSErr
         mov     cl,0xFF
         mov     ewx,0xFFFFFFFF
         addsx   gx,cl,ewx
         cmp     gx,0xFFFE
         bne     TestArus_WBDSErr
         mov     dl,0xFF
         mov     fwx,0xFFFFFFFF
         subsx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDSErr
         mov     el,0xFF
         mov     gwx,0xFFFFFFFF
         andsx   bw,el,gwx
         cmp     bw,0xFFFF
         bne     TestArus_WBDSErr
         mov     fl,0xFF
         mov     ar,0xFFFFFFFF
         orsx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDSErr
         mov     gl,0xFF
         mov     br,0xFFFFFFFF
         xorsx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDSErr
         mov     ah,0xFF
         mov     cr,0xFFFFFFFF
         mulsx   ew,ah,cr
         cmp     ew,0x0001
         bne     TestArus_WBDSErr
         mov     bh,0xFF
         mov     dr,0xFFFFFFFF
         sdivsx  fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDSErr
         mov     ch,0xFF
         mov     er,0xFFFFFFFF
         sremsx  gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDSErr
         bra     TestArus_WBDSRet
TestArus_WBDSErr:
         nop     
         trap    
         nop     
TestArus_WBDSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
