.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BBBZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BBBZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cl,0x00
         addzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x00
         subzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x00
         andzx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x00
         orzx    ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x00
         xorzx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x00
         mulzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x00
         udivzx  dh,gl,bh
         cmp     dh,0xFF
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x00
         uremzx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x00
         shlzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x00
         shrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x00
         rolzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x00
         asrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0x01
         addzx   cl,fh,al
         cmp     cl,0x01
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0x01
         subzx   dl,gh,bl
         cmp     dl,0xFF
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0x01
         andzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x01
         orzx    fl,bl,dl
         cmp     fl,0x01
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x01
         xorzx   gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x01
         mulzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x01
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x01
         uremzx  ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x01
         shlzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x01
         shrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x01
         rolzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x01
         asrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x07
         addzx   al,dh,fh
         cmp     al,0x07
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x07
         subzx   bl,eh,gh
         cmp     bl,0xF9
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0x07
         andzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0x07
         orzx    dl,gh,bl
         cmp     dl,0x07
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0x07
         xorzx   el,al,cl
         cmp     el,0x07
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x07
         mulzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x07
         udivzx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x07
         uremzx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x07
         shlzx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x07
         shrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x07
         rolzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x07
         asrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x08
         addzx   fh,bh,dh
         cmp     fh,0x08
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x08
         subzx   gh,ch,eh
         cmp     gh,0xF8
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x08
         andzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x08
         orzx    bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0x08
         xorzx   cl,fh,al
         cmp     cl,0x08
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0x08
         mulzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0x08
         udivzx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x08
         uremzx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x00
         shlzx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x00
         shrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x00
         rolzx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x00
         asrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x09
         addzx   dh,gl,bh
         cmp     dh,0x09
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x09
         subzx   eh,ah,ch
         cmp     eh,0xF7
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x09
         andzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x09
         orzx    gh,ch,eh
         cmp     gh,0x09
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x09
         xorzx   al,dh,fh
         cmp     al,0x09
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x09
         mulzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0x09
         udivzx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0x09
         uremzx  dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0x01
         shlzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x01
         shrzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x01
         rolzx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x01
         asrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x0F
         addzx   bh,el,gl
         cmp     bh,0x0F
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x0F
         subzx   ch,fl,ah
         cmp     ch,0xF1
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x0F
         andzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x0F
         orzx    eh,ah,ch
         cmp     eh,0x0F
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x0F
         xorzx   fh,bh,dh
         cmp     fh,0x0F
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x0F
         mulzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x0F
         udivzx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x0F
         uremzx  bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0x07
         shlzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0x07
         shrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0x07
         rolzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x07
         asrzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x7F
         addzx   gl,cl,el
         cmp     gl,0x7F
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x7F
         subzx   ah,dl,fl
         cmp     ah,0x81
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x7F
         andzx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x7F
         orzx    ch,fl,ah
         cmp     ch,0x7F
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x7F
         xorzx   dh,gl,bh
         cmp     dh,0x7F
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x7F
         mulzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x7F
         udivzx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x7F
         uremzx  gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x07
         shlzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x07
         shrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0x07
         rolzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0x07
         asrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0x80
         addzx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0x80
         subzx   fl,bl,dl
         cmp     fl,0x80
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0x80
         andzx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0x80
         orzx    ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0x80
         xorzx   bh,el,gl
         cmp     bh,0x80
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0x80
         mulzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x80
         udivzx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x80
         uremzx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x00
         shlzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x00
         shrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x00
         mov     fh,0x00
         rolzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x00
         mov     gh,0x00
         asrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x00
         mov     al,0xFF
         addzx   cl,fh,al
         cmp     cl,0xFF
         bne     TestArus_BBBZErr
         mov     gh,0x00
         mov     bl,0xFF
         subzx   dl,gh,bl
         cmp     dl,0x01
         bne     TestArus_BBBZErr
         mov     al,0x00
         mov     cl,0xFF
         andzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x00
         mov     dl,0xFF
         orzx    fl,bl,dl
         cmp     fl,0xFF
         bne     TestArus_BBBZErr
         mov     cl,0x00
         mov     el,0xFF
         xorzx   gl,cl,el
         cmp     gl,0xFF
         bne     TestArus_BBBZErr
         mov     dl,0x00
         mov     fl,0xFF
         mulzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x00
         mov     gl,0xFF
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x00
         mov     ah,0xFF
         uremzx  ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x00
         mov     bh,0x07
         shlzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x00
         mov     ch,0x07
         shrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x00
         mov     dh,0x07
         rolzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x00
         mov     eh,0x07
         asrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0x01
         addzx   al,dh,fh
         cmp     al,0x02
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0x01
         subzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0x01
         andzx   cl,fh,al
         cmp     cl,0x01
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0x01
         orzx    dl,gh,bl
         cmp     dl,0x01
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0x01
         xorzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0x01
         mulzx   fl,bl,dl
         cmp     fl,0x01
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0x01
         udivzx  gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0x01
         uremzx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x01
         shlzx   bh,el,gl
         cmp     bh,0x02
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x01
         shrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x01
         rolzx   dh,gl,bh
         cmp     dh,0x02
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x01
         asrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x01
         mov     dh,0x07
         addzx   fh,bh,dh
         cmp     fh,0x08
         bne     TestArus_BBBZErr
         mov     ch,0x01
         mov     eh,0x07
         subzx   gh,ch,eh
         cmp     gh,0xFA
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0x07
         andzx   al,dh,fh
         cmp     al,0x01
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0x07
         orzx    bl,eh,gh
         cmp     bl,0x07
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0x07
         xorzx   cl,fh,al
         cmp     cl,0x06
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0x07
         mulzx   dl,gh,bl
         cmp     dl,0x07
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0x07
         udivzx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0x07
         uremzx  fl,bl,dl
         cmp     fl,0x01
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0x07
         shlzx   gl,cl,el
         cmp     gl,0x80
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0x07
         shrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x07
         rolzx   bh,el,gl
         cmp     bh,0x80
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x07
         asrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x08
         addzx   dh,gl,bh
         cmp     dh,0x09
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x08
         subzx   eh,ah,ch
         cmp     eh,0xF9
         bne     TestArus_BBBZErr
         mov     bh,0x01
         mov     dh,0x08
         andzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x01
         mov     eh,0x08
         orzx    gh,ch,eh
         cmp     gh,0x09
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0x08
         xorzx   al,dh,fh
         cmp     al,0x09
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0x08
         mulzx   bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0x08
         udivzx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0x08
         uremzx  dl,gh,bl
         cmp     dl,0x01
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0x00
         shlzx   el,al,cl
         cmp     el,0x01
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0x00
         shrzx   fl,bl,dl
         cmp     fl,0x01
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0x00
         rolzx   gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0x00
         asrzx   ah,dl,fl
         cmp     ah,0x01
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x09
         addzx   bh,el,gl
         cmp     bh,0x0A
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x09
         subzx   ch,fl,ah
         cmp     ch,0xF8
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x09
         andzx   dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x09
         orzx    eh,ah,ch
         cmp     eh,0x09
         bne     TestArus_BBBZErr
         mov     bh,0x01
         mov     dh,0x09
         xorzx   fh,bh,dh
         cmp     fh,0x08
         bne     TestArus_BBBZErr
         mov     ch,0x01
         mov     eh,0x09
         mulzx   gh,ch,eh
         cmp     gh,0x09
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0x09
         udivzx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0x09
         uremzx  bl,eh,gh
         cmp     bl,0x01
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0x01
         shlzx   cl,fh,al
         cmp     cl,0x02
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0x01
         shrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0x01
         rolzx   el,al,cl
         cmp     el,0x02
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0x01
         asrzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0x0F
         addzx   gl,cl,el
         cmp     gl,0x10
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0x0F
         subzx   ah,dl,fl
         cmp     ah,0xF2
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x0F
         andzx   bh,el,gl
         cmp     bh,0x01
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x0F
         orzx    ch,fl,ah
         cmp     ch,0x0F
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x0F
         xorzx   dh,gl,bh
         cmp     dh,0x0E
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x0F
         mulzx   eh,ah,ch
         cmp     eh,0x0F
         bne     TestArus_BBBZErr
         mov     bh,0x01
         mov     dh,0x0F
         udivzx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x01
         mov     eh,0x0F
         uremzx  gh,ch,eh
         cmp     gh,0x01
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0x07
         shlzx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0x07
         shrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0x07
         rolzx   cl,fh,al
         cmp     cl,0x80
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0x07
         asrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0x7F
         addzx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0x7F
         subzx   fl,bl,dl
         cmp     fl,0x82
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0x7F
         andzx   gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0x7F
         orzx    ah,dl,fl
         cmp     ah,0x7F
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x7F
         xorzx   bh,el,gl
         cmp     bh,0x7E
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x7F
         mulzx   ch,fl,ah
         cmp     ch,0x7F
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x7F
         udivzx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x7F
         uremzx  eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBZErr
         mov     bh,0x01
         mov     dh,0x07
         shlzx   fh,bh,dh
         cmp     fh,0x80
         bne     TestArus_BBBZErr
         mov     ch,0x01
         mov     eh,0x07
         shrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0x07
         rolzx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0x07
         asrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0x80
         addzx   cl,fh,al
         cmp     cl,0x81
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0x80
         subzx   dl,gh,bl
         cmp     dl,0x81
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0x80
         andzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0x80
         orzx    fl,bl,dl
         cmp     fl,0x81
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0x80
         xorzx   gl,cl,el
         cmp     gl,0x81
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0x80
         mulzx   ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x80
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x80
         uremzx  ch,fl,ah
         cmp     ch,0x01
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x00
         shlzx   dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x00
         shrzx   eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBZErr
         mov     bh,0x01
         mov     dh,0x00
         rolzx   fh,bh,dh
         cmp     fh,0x01
         bne     TestArus_BBBZErr
         mov     ch,0x01
         mov     eh,0x00
         asrzx   gh,ch,eh
         cmp     gh,0x01
         bne     TestArus_BBBZErr
         mov     dh,0x01
         mov     fh,0xFF
         addzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x01
         mov     gh,0xFF
         subzx   bl,eh,gh
         cmp     bl,0x02
         bne     TestArus_BBBZErr
         mov     fh,0x01
         mov     al,0xFF
         andzx   cl,fh,al
         cmp     cl,0x01
         bne     TestArus_BBBZErr
         mov     gh,0x01
         mov     bl,0xFF
         orzx    dl,gh,bl
         cmp     dl,0xFF
         bne     TestArus_BBBZErr
         mov     al,0x01
         mov     cl,0xFF
         xorzx   el,al,cl
         cmp     el,0xFE
         bne     TestArus_BBBZErr
         mov     bl,0x01
         mov     dl,0xFF
         mulzx   fl,bl,dl
         cmp     fl,0xFF
         bne     TestArus_BBBZErr
         mov     cl,0x01
         mov     el,0xFF
         udivzx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x01
         mov     fl,0xFF
         uremzx  ah,dl,fl
         cmp     ah,0x01
         bne     TestArus_BBBZErr
         mov     el,0x01
         mov     gl,0x07
         shlzx   bh,el,gl
         cmp     bh,0x80
         bne     TestArus_BBBZErr
         mov     fl,0x01
         mov     ah,0x07
         shrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x01
         mov     bh,0x07
         rolzx   dh,gl,bh
         cmp     dh,0x80
         bne     TestArus_BBBZErr
         mov     ah,0x01
         mov     ch,0x07
         asrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x07
         mov     dh,0x07
         addzx   fh,bh,dh
         cmp     fh,0x0E
         bne     TestArus_BBBZErr
         mov     ch,0x07
         mov     eh,0x07
         subzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x07
         mov     fh,0x07
         andzx   al,dh,fh
         cmp     al,0x07
         bne     TestArus_BBBZErr
         mov     eh,0x07
         mov     gh,0x07
         orzx    bl,eh,gh
         cmp     bl,0x07
         bne     TestArus_BBBZErr
         mov     fh,0x07
         mov     al,0x07
         xorzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x07
         mov     bl,0x07
         mulzx   dl,gh,bl
         cmp     dl,0x31
         bne     TestArus_BBBZErr
         mov     al,0x07
         mov     cl,0x07
         udivzx  el,al,cl
         cmp     el,0x01
         bne     TestArus_BBBZErr
         mov     bl,0x07
         mov     dl,0x07
         uremzx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x07
         mov     el,0x07
         shlzx   gl,cl,el
         cmp     gl,0x80
         bne     TestArus_BBBZErr
         mov     dl,0x07
         mov     fl,0x07
         shrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x07
         mov     gl,0x07
         rolzx   bh,el,gl
         cmp     bh,0x83
         bne     TestArus_BBBZErr
         mov     fl,0x07
         mov     ah,0x07
         asrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x07
         mov     bh,0x08
         addzx   dh,gl,bh
         cmp     dh,0x0F
         bne     TestArus_BBBZErr
         mov     ah,0x07
         mov     ch,0x08
         subzx   eh,ah,ch
         cmp     eh,0xFF
         bne     TestArus_BBBZErr
         mov     bh,0x07
         mov     dh,0x08
         andzx   fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x07
         mov     eh,0x08
         orzx    gh,ch,eh
         cmp     gh,0x0F
         bne     TestArus_BBBZErr
         mov     dh,0x07
         mov     fh,0x08
         xorzx   al,dh,fh
         cmp     al,0x0F
         bne     TestArus_BBBZErr
         mov     eh,0x07
         mov     gh,0x08
         mulzx   bl,eh,gh
         cmp     bl,0x38
         bne     TestArus_BBBZErr
         mov     fh,0x07
         mov     al,0x08
         udivzx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x07
         mov     bl,0x08
         uremzx  dl,gh,bl
         cmp     dl,0x07
         bne     TestArus_BBBZErr
         mov     al,0x07
         mov     cl,0x00
         shlzx   el,al,cl
         cmp     el,0x07
         bne     TestArus_BBBZErr
         mov     bl,0x07
         mov     dl,0x00
         shrzx   fl,bl,dl
         cmp     fl,0x07
         bne     TestArus_BBBZErr
         mov     cl,0x07
         mov     el,0x00
         rolzx   gl,cl,el
         cmp     gl,0x07
         bne     TestArus_BBBZErr
         mov     dl,0x07
         mov     fl,0x00
         asrzx   ah,dl,fl
         cmp     ah,0x07
         bne     TestArus_BBBZErr
         mov     el,0x07
         mov     gl,0x09
         addzx   bh,el,gl
         cmp     bh,0x10
         bne     TestArus_BBBZErr
         mov     fl,0x07
         mov     ah,0x09
         subzx   ch,fl,ah
         cmp     ch,0xFE
         bne     TestArus_BBBZErr
         mov     gl,0x07
         mov     bh,0x09
         andzx   dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBZErr
         mov     ah,0x07
         mov     ch,0x09
         orzx    eh,ah,ch
         cmp     eh,0x0F
         bne     TestArus_BBBZErr
         mov     bh,0x07
         mov     dh,0x09
         xorzx   fh,bh,dh
         cmp     fh,0x0E
         bne     TestArus_BBBZErr
         mov     ch,0x07
         mov     eh,0x09
         mulzx   gh,ch,eh
         cmp     gh,0x3F
         bne     TestArus_BBBZErr
         mov     dh,0x07
         mov     fh,0x09
         udivzx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x07
         mov     gh,0x09
         uremzx  bl,eh,gh
         cmp     bl,0x07
         bne     TestArus_BBBZErr
         mov     fh,0x07
         mov     al,0x01
         shlzx   cl,fh,al
         cmp     cl,0x0E
         bne     TestArus_BBBZErr
         mov     gh,0x07
         mov     bl,0x01
         shrzx   dl,gh,bl
         cmp     dl,0x03
         bne     TestArus_BBBZErr
         mov     al,0x07
         mov     cl,0x01
         rolzx   el,al,cl
         cmp     el,0x0E
         bne     TestArus_BBBZErr
         mov     bl,0x07
         mov     dl,0x01
         asrzx   fl,bl,dl
         cmp     fl,0x03
         bne     TestArus_BBBZErr
         mov     cl,0x07
         mov     el,0x0F
         addzx   gl,cl,el
         cmp     gl,0x16
         bne     TestArus_BBBZErr
         mov     dl,0x07
         mov     fl,0x0F
         subzx   ah,dl,fl
         cmp     ah,0xF8
         bne     TestArus_BBBZErr
         mov     el,0x07
         mov     gl,0x0F
         andzx   bh,el,gl
         cmp     bh,0x07
         bne     TestArus_BBBZErr
         mov     fl,0x07
         mov     ah,0x0F
         orzx    ch,fl,ah
         cmp     ch,0x0F
         bne     TestArus_BBBZErr
         mov     gl,0x07
         mov     bh,0x0F
         xorzx   dh,gl,bh
         cmp     dh,0x08
         bne     TestArus_BBBZErr
         mov     ah,0x07
         mov     ch,0x0F
         mulzx   eh,ah,ch
         cmp     eh,0x69
         bne     TestArus_BBBZErr
         mov     bh,0x07
         mov     dh,0x0F
         udivzx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x07
         mov     eh,0x0F
         uremzx  gh,ch,eh
         cmp     gh,0x07
         bne     TestArus_BBBZErr
         mov     dh,0x07
         mov     fh,0x07
         shlzx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBZErr
         mov     eh,0x07
         mov     gh,0x07
         shrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x07
         mov     al,0x07
         rolzx   cl,fh,al
         cmp     cl,0x83
         bne     TestArus_BBBZErr
         mov     gh,0x07
         mov     bl,0x07
         asrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x07
         mov     cl,0x7F
         addzx   el,al,cl
         cmp     el,0x86
         bne     TestArus_BBBZErr
         mov     bl,0x07
         mov     dl,0x7F
         subzx   fl,bl,dl
         cmp     fl,0x88
         bne     TestArus_BBBZErr
         mov     cl,0x07
         mov     el,0x7F
         andzx   gl,cl,el
         cmp     gl,0x07
         bne     TestArus_BBBZErr
         mov     dl,0x07
         mov     fl,0x7F
         orzx    ah,dl,fl
         cmp     ah,0x7F
         bne     TestArus_BBBZErr
         mov     el,0x07
         mov     gl,0x7F
         xorzx   bh,el,gl
         cmp     bh,0x78
         bne     TestArus_BBBZErr
         mov     fl,0x07
         mov     ah,0x7F
         mulzx   ch,fl,ah
         cmp     ch,0x79
         bne     TestArus_BBBZErr
         mov     gl,0x07
         mov     bh,0x7F
         udivzx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x07
         mov     ch,0x7F
         uremzx  eh,ah,ch
         cmp     eh,0x07
         bne     TestArus_BBBZErr
         mov     bh,0x07
         mov     dh,0x07
         shlzx   fh,bh,dh
         cmp     fh,0x80
         bne     TestArus_BBBZErr
         mov     ch,0x07
         mov     eh,0x07
         shrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x07
         mov     fh,0x07
         rolzx   al,dh,fh
         cmp     al,0x83
         bne     TestArus_BBBZErr
         mov     eh,0x07
         mov     gh,0x07
         asrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x07
         mov     al,0x80
         addzx   cl,fh,al
         cmp     cl,0x87
         bne     TestArus_BBBZErr
         mov     gh,0x07
         mov     bl,0x80
         subzx   dl,gh,bl
         cmp     dl,0x87
         bne     TestArus_BBBZErr
         mov     al,0x07
         mov     cl,0x80
         andzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x07
         mov     dl,0x80
         orzx    fl,bl,dl
         cmp     fl,0x87
         bne     TestArus_BBBZErr
         mov     cl,0x07
         mov     el,0x80
         xorzx   gl,cl,el
         cmp     gl,0x87
         bne     TestArus_BBBZErr
         mov     dl,0x07
         mov     fl,0x80
         mulzx   ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBZErr
         mov     el,0x07
         mov     gl,0x80
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x07
         mov     ah,0x80
         uremzx  ch,fl,ah
         cmp     ch,0x07
         bne     TestArus_BBBZErr
         mov     gl,0x07
         mov     bh,0x00
         shlzx   dh,gl,bh
         cmp     dh,0x07
         bne     TestArus_BBBZErr
         mov     ah,0x07
         mov     ch,0x00
         shrzx   eh,ah,ch
         cmp     eh,0x07
         bne     TestArus_BBBZErr
         mov     bh,0x07
         mov     dh,0x00
         rolzx   fh,bh,dh
         cmp     fh,0x07
         bne     TestArus_BBBZErr
         mov     ch,0x07
         mov     eh,0x00
         asrzx   gh,ch,eh
         cmp     gh,0x07
         bne     TestArus_BBBZErr
         mov     dh,0x07
         mov     fh,0xFF
         addzx   al,dh,fh
         cmp     al,0x06
         bne     TestArus_BBBZErr
         mov     eh,0x07
         mov     gh,0xFF
         subzx   bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBZErr
         mov     fh,0x07
         mov     al,0xFF
         andzx   cl,fh,al
         cmp     cl,0x07
         bne     TestArus_BBBZErr
         mov     gh,0x07
         mov     bl,0xFF
         orzx    dl,gh,bl
         cmp     dl,0xFF
         bne     TestArus_BBBZErr
         mov     al,0x07
         mov     cl,0xFF
         xorzx   el,al,cl
         cmp     el,0xF8
         bne     TestArus_BBBZErr
         mov     bl,0x07
         mov     dl,0xFF
         mulzx   fl,bl,dl
         cmp     fl,0xF9
         bne     TestArus_BBBZErr
         mov     cl,0x07
         mov     el,0xFF
         udivzx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x07
         mov     fl,0xFF
         uremzx  ah,dl,fl
         cmp     ah,0x07
         bne     TestArus_BBBZErr
         mov     el,0x07
         mov     gl,0x07
         shlzx   bh,el,gl
         cmp     bh,0x80
         bne     TestArus_BBBZErr
         mov     fl,0x07
         mov     ah,0x07
         shrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x07
         mov     bh,0x07
         rolzx   dh,gl,bh
         cmp     dh,0x83
         bne     TestArus_BBBZErr
         mov     ah,0x07
         mov     ch,0x07
         asrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x08
         mov     dh,0x08
         addzx   fh,bh,dh
         cmp     fh,0x10
         bne     TestArus_BBBZErr
         mov     ch,0x08
         mov     eh,0x08
         subzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x08
         mov     fh,0x08
         andzx   al,dh,fh
         cmp     al,0x08
         bne     TestArus_BBBZErr
         mov     eh,0x08
         mov     gh,0x08
         orzx    bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBZErr
         mov     fh,0x08
         mov     al,0x08
         xorzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x08
         mov     bl,0x08
         mulzx   dl,gh,bl
         cmp     dl,0x40
         bne     TestArus_BBBZErr
         mov     al,0x08
         mov     cl,0x08
         udivzx  el,al,cl
         cmp     el,0x01
         bne     TestArus_BBBZErr
         mov     bl,0x08
         mov     dl,0x08
         uremzx  fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x08
         mov     el,0x00
         shlzx   gl,cl,el
         cmp     gl,0x08
         bne     TestArus_BBBZErr
         mov     dl,0x08
         mov     fl,0x00
         shrzx   ah,dl,fl
         cmp     ah,0x08
         bne     TestArus_BBBZErr
         mov     el,0x08
         mov     gl,0x00
         rolzx   bh,el,gl
         cmp     bh,0x08
         bne     TestArus_BBBZErr
         mov     fl,0x08
         mov     ah,0x00
         asrzx   ch,fl,ah
         cmp     ch,0x08
         bne     TestArus_BBBZErr
         mov     gl,0x08
         mov     bh,0x09
         addzx   dh,gl,bh
         cmp     dh,0x11
         bne     TestArus_BBBZErr
         mov     ah,0x08
         mov     ch,0x09
         subzx   eh,ah,ch
         cmp     eh,0xFF
         bne     TestArus_BBBZErr
         mov     bh,0x08
         mov     dh,0x09
         andzx   fh,bh,dh
         cmp     fh,0x08
         bne     TestArus_BBBZErr
         mov     ch,0x08
         mov     eh,0x09
         orzx    gh,ch,eh
         cmp     gh,0x09
         bne     TestArus_BBBZErr
         mov     dh,0x08
         mov     fh,0x09
         xorzx   al,dh,fh
         cmp     al,0x01
         bne     TestArus_BBBZErr
         mov     eh,0x08
         mov     gh,0x09
         mulzx   bl,eh,gh
         cmp     bl,0x48
         bne     TestArus_BBBZErr
         mov     fh,0x08
         mov     al,0x09
         udivzx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x08
         mov     bl,0x09
         uremzx  dl,gh,bl
         cmp     dl,0x08
         bne     TestArus_BBBZErr
         mov     al,0x08
         mov     cl,0x01
         shlzx   el,al,cl
         cmp     el,0x10
         bne     TestArus_BBBZErr
         mov     bl,0x08
         mov     dl,0x01
         shrzx   fl,bl,dl
         cmp     fl,0x04
         bne     TestArus_BBBZErr
         mov     cl,0x08
         mov     el,0x01
         rolzx   gl,cl,el
         cmp     gl,0x10
         bne     TestArus_BBBZErr
         mov     dl,0x08
         mov     fl,0x01
         asrzx   ah,dl,fl
         cmp     ah,0x04
         bne     TestArus_BBBZErr
         mov     el,0x08
         mov     gl,0x0F
         addzx   bh,el,gl
         cmp     bh,0x17
         bne     TestArus_BBBZErr
         mov     fl,0x08
         mov     ah,0x0F
         subzx   ch,fl,ah
         cmp     ch,0xF9
         bne     TestArus_BBBZErr
         mov     gl,0x08
         mov     bh,0x0F
         andzx   dh,gl,bh
         cmp     dh,0x08
         bne     TestArus_BBBZErr
         mov     ah,0x08
         mov     ch,0x0F
         orzx    eh,ah,ch
         cmp     eh,0x0F
         bne     TestArus_BBBZErr
         mov     bh,0x08
         mov     dh,0x0F
         xorzx   fh,bh,dh
         cmp     fh,0x07
         bne     TestArus_BBBZErr
         mov     ch,0x08
         mov     eh,0x0F
         mulzx   gh,ch,eh
         cmp     gh,0x78
         bne     TestArus_BBBZErr
         mov     dh,0x08
         mov     fh,0x0F
         udivzx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x08
         mov     gh,0x0F
         uremzx  bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBZErr
         mov     fh,0x08
         mov     al,0x07
         shlzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x08
         mov     bl,0x07
         shrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x08
         mov     cl,0x07
         rolzx   el,al,cl
         cmp     el,0x04
         bne     TestArus_BBBZErr
         mov     bl,0x08
         mov     dl,0x07
         asrzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x08
         mov     el,0x7F
         addzx   gl,cl,el
         cmp     gl,0x87
         bne     TestArus_BBBZErr
         mov     dl,0x08
         mov     fl,0x7F
         subzx   ah,dl,fl
         cmp     ah,0x89
         bne     TestArus_BBBZErr
         mov     el,0x08
         mov     gl,0x7F
         andzx   bh,el,gl
         cmp     bh,0x08
         bne     TestArus_BBBZErr
         mov     fl,0x08
         mov     ah,0x7F
         orzx    ch,fl,ah
         cmp     ch,0x7F
         bne     TestArus_BBBZErr
         mov     gl,0x08
         mov     bh,0x7F
         xorzx   dh,gl,bh
         cmp     dh,0x77
         bne     TestArus_BBBZErr
         mov     ah,0x08
         mov     ch,0x7F
         mulzx   eh,ah,ch
         cmp     eh,0xF8
         bne     TestArus_BBBZErr
         mov     bh,0x08
         mov     dh,0x7F
         udivzx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x08
         mov     eh,0x7F
         uremzx  gh,ch,eh
         cmp     gh,0x08
         bne     TestArus_BBBZErr
         mov     dh,0x08
         mov     fh,0x07
         shlzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x08
         mov     gh,0x07
         shrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x08
         mov     al,0x07
         rolzx   cl,fh,al
         cmp     cl,0x04
         bne     TestArus_BBBZErr
         mov     gh,0x08
         mov     bl,0x07
         asrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x08
         mov     cl,0x80
         addzx   el,al,cl
         cmp     el,0x88
         bne     TestArus_BBBZErr
         mov     bl,0x08
         mov     dl,0x80
         subzx   fl,bl,dl
         cmp     fl,0x88
         bne     TestArus_BBBZErr
         mov     cl,0x08
         mov     el,0x80
         andzx   gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x08
         mov     fl,0x80
         orzx    ah,dl,fl
         cmp     ah,0x88
         bne     TestArus_BBBZErr
         mov     el,0x08
         mov     gl,0x80
         xorzx   bh,el,gl
         cmp     bh,0x88
         bne     TestArus_BBBZErr
         mov     fl,0x08
         mov     ah,0x80
         mulzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x08
         mov     bh,0x80
         udivzx  dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x08
         mov     ch,0x80
         uremzx  eh,ah,ch
         cmp     eh,0x08
         bne     TestArus_BBBZErr
         mov     bh,0x08
         mov     dh,0x00
         shlzx   fh,bh,dh
         cmp     fh,0x08
         bne     TestArus_BBBZErr
         mov     ch,0x08
         mov     eh,0x00
         shrzx   gh,ch,eh
         cmp     gh,0x08
         bne     TestArus_BBBZErr
         mov     dh,0x08
         mov     fh,0x00
         rolzx   al,dh,fh
         cmp     al,0x08
         bne     TestArus_BBBZErr
         mov     eh,0x08
         mov     gh,0x00
         asrzx   bl,eh,gh
         cmp     bl,0x08
         bne     TestArus_BBBZErr
         mov     fh,0x08
         mov     al,0xFF
         addzx   cl,fh,al
         cmp     cl,0x07
         bne     TestArus_BBBZErr
         mov     gh,0x08
         mov     bl,0xFF
         subzx   dl,gh,bl
         cmp     dl,0x09
         bne     TestArus_BBBZErr
         mov     al,0x08
         mov     cl,0xFF
         andzx   el,al,cl
         cmp     el,0x08
         bne     TestArus_BBBZErr
         mov     bl,0x08
         mov     dl,0xFF
         orzx    fl,bl,dl
         cmp     fl,0xFF
         bne     TestArus_BBBZErr
         mov     cl,0x08
         mov     el,0xFF
         xorzx   gl,cl,el
         cmp     gl,0xF7
         bne     TestArus_BBBZErr
         mov     dl,0x08
         mov     fl,0xFF
         mulzx   ah,dl,fl
         cmp     ah,0xF8
         bne     TestArus_BBBZErr
         mov     el,0x08
         mov     gl,0xFF
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x08
         mov     ah,0xFF
         uremzx  ch,fl,ah
         cmp     ch,0x08
         bne     TestArus_BBBZErr
         mov     gl,0x08
         mov     bh,0x07
         shlzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x08
         mov     ch,0x07
         shrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x08
         mov     dh,0x07
         rolzx   fh,bh,dh
         cmp     fh,0x04
         bne     TestArus_BBBZErr
         mov     ch,0x08
         mov     eh,0x07
         asrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x09
         mov     fh,0x09
         addzx   al,dh,fh
         cmp     al,0x12
         bne     TestArus_BBBZErr
         mov     eh,0x09
         mov     gh,0x09
         subzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x09
         mov     al,0x09
         andzx   cl,fh,al
         cmp     cl,0x09
         bne     TestArus_BBBZErr
         mov     gh,0x09
         mov     bl,0x09
         orzx    dl,gh,bl
         cmp     dl,0x09
         bne     TestArus_BBBZErr
         mov     al,0x09
         mov     cl,0x09
         xorzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x09
         mov     dl,0x09
         mulzx   fl,bl,dl
         cmp     fl,0x51
         bne     TestArus_BBBZErr
         mov     cl,0x09
         mov     el,0x09
         udivzx  gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBZErr
         mov     dl,0x09
         mov     fl,0x09
         uremzx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x09
         mov     gl,0x01
         shlzx   bh,el,gl
         cmp     bh,0x12
         bne     TestArus_BBBZErr
         mov     fl,0x09
         mov     ah,0x01
         shrzx   ch,fl,ah
         cmp     ch,0x04
         bne     TestArus_BBBZErr
         mov     gl,0x09
         mov     bh,0x01
         rolzx   dh,gl,bh
         cmp     dh,0x12
         bne     TestArus_BBBZErr
         mov     ah,0x09
         mov     ch,0x01
         asrzx   eh,ah,ch
         cmp     eh,0x04
         bne     TestArus_BBBZErr
         mov     bh,0x09
         mov     dh,0x0F
         addzx   fh,bh,dh
         cmp     fh,0x18
         bne     TestArus_BBBZErr
         mov     ch,0x09
         mov     eh,0x0F
         subzx   gh,ch,eh
         cmp     gh,0xFA
         bne     TestArus_BBBZErr
         mov     dh,0x09
         mov     fh,0x0F
         andzx   al,dh,fh
         cmp     al,0x09
         bne     TestArus_BBBZErr
         mov     eh,0x09
         mov     gh,0x0F
         orzx    bl,eh,gh
         cmp     bl,0x0F
         bne     TestArus_BBBZErr
         mov     fh,0x09
         mov     al,0x0F
         xorzx   cl,fh,al
         cmp     cl,0x06
         bne     TestArus_BBBZErr
         mov     gh,0x09
         mov     bl,0x0F
         mulzx   dl,gh,bl
         cmp     dl,0x87
         bne     TestArus_BBBZErr
         mov     al,0x09
         mov     cl,0x0F
         udivzx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x09
         mov     dl,0x0F
         uremzx  fl,bl,dl
         cmp     fl,0x09
         bne     TestArus_BBBZErr
         mov     cl,0x09
         mov     el,0x07
         shlzx   gl,cl,el
         cmp     gl,0x80
         bne     TestArus_BBBZErr
         mov     dl,0x09
         mov     fl,0x07
         shrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x09
         mov     gl,0x07
         rolzx   bh,el,gl
         cmp     bh,0x84
         bne     TestArus_BBBZErr
         mov     fl,0x09
         mov     ah,0x07
         asrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x09
         mov     bh,0x7F
         addzx   dh,gl,bh
         cmp     dh,0x88
         bne     TestArus_BBBZErr
         mov     ah,0x09
         mov     ch,0x7F
         subzx   eh,ah,ch
         cmp     eh,0x8A
         bne     TestArus_BBBZErr
         mov     bh,0x09
         mov     dh,0x7F
         andzx   fh,bh,dh
         cmp     fh,0x09
         bne     TestArus_BBBZErr
         mov     ch,0x09
         mov     eh,0x7F
         orzx    gh,ch,eh
         cmp     gh,0x7F
         bne     TestArus_BBBZErr
         mov     dh,0x09
         mov     fh,0x7F
         xorzx   al,dh,fh
         cmp     al,0x76
         bne     TestArus_BBBZErr
         mov     eh,0x09
         mov     gh,0x7F
         mulzx   bl,eh,gh
         cmp     bl,0x77
         bne     TestArus_BBBZErr
         mov     fh,0x09
         mov     al,0x7F
         udivzx  cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x09
         mov     bl,0x7F
         uremzx  dl,gh,bl
         cmp     dl,0x09
         bne     TestArus_BBBZErr
         mov     al,0x09
         mov     cl,0x07
         shlzx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBZErr
         mov     bl,0x09
         mov     dl,0x07
         shrzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x09
         mov     el,0x07
         rolzx   gl,cl,el
         cmp     gl,0x84
         bne     TestArus_BBBZErr
         mov     dl,0x09
         mov     fl,0x07
         asrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x09
         mov     gl,0x80
         addzx   bh,el,gl
         cmp     bh,0x89
         bne     TestArus_BBBZErr
         mov     fl,0x09
         mov     ah,0x80
         subzx   ch,fl,ah
         cmp     ch,0x89
         bne     TestArus_BBBZErr
         mov     gl,0x09
         mov     bh,0x80
         andzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x09
         mov     ch,0x80
         orzx    eh,ah,ch
         cmp     eh,0x89
         bne     TestArus_BBBZErr
         mov     bh,0x09
         mov     dh,0x80
         xorzx   fh,bh,dh
         cmp     fh,0x89
         bne     TestArus_BBBZErr
         mov     ch,0x09
         mov     eh,0x80
         mulzx   gh,ch,eh
         cmp     gh,0x80
         bne     TestArus_BBBZErr
         mov     dh,0x09
         mov     fh,0x80
         udivzx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x09
         mov     gh,0x80
         uremzx  bl,eh,gh
         cmp     bl,0x09
         bne     TestArus_BBBZErr
         mov     fh,0x09
         mov     al,0x00
         shlzx   cl,fh,al
         cmp     cl,0x09
         bne     TestArus_BBBZErr
         mov     gh,0x09
         mov     bl,0x00
         shrzx   dl,gh,bl
         cmp     dl,0x09
         bne     TestArus_BBBZErr
         mov     al,0x09
         mov     cl,0x00
         rolzx   el,al,cl
         cmp     el,0x09
         bne     TestArus_BBBZErr
         mov     bl,0x09
         mov     dl,0x00
         asrzx   fl,bl,dl
         cmp     fl,0x09
         bne     TestArus_BBBZErr
         mov     cl,0x09
         mov     el,0xFF
         addzx   gl,cl,el
         cmp     gl,0x08
         bne     TestArus_BBBZErr
         mov     dl,0x09
         mov     fl,0xFF
         subzx   ah,dl,fl
         cmp     ah,0x0A
         bne     TestArus_BBBZErr
         mov     el,0x09
         mov     gl,0xFF
         andzx   bh,el,gl
         cmp     bh,0x09
         bne     TestArus_BBBZErr
         mov     fl,0x09
         mov     ah,0xFF
         orzx    ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBZErr
         mov     gl,0x09
         mov     bh,0xFF
         xorzx   dh,gl,bh
         cmp     dh,0xF6
         bne     TestArus_BBBZErr
         mov     ah,0x09
         mov     ch,0xFF
         mulzx   eh,ah,ch
         cmp     eh,0xF7
         bne     TestArus_BBBZErr
         mov     bh,0x09
         mov     dh,0xFF
         udivzx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x09
         mov     eh,0xFF
         uremzx  gh,ch,eh
         cmp     gh,0x09
         bne     TestArus_BBBZErr
         mov     dh,0x09
         mov     fh,0x07
         shlzx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBZErr
         mov     eh,0x09
         mov     gh,0x07
         shrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x09
         mov     al,0x07
         rolzx   cl,fh,al
         cmp     cl,0x84
         bne     TestArus_BBBZErr
         mov     gh,0x09
         mov     bl,0x07
         asrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x0F
         mov     cl,0x0F
         addzx   el,al,cl
         cmp     el,0x1E
         bne     TestArus_BBBZErr
         mov     bl,0x0F
         mov     dl,0x0F
         subzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x0F
         mov     el,0x0F
         andzx   gl,cl,el
         cmp     gl,0x0F
         bne     TestArus_BBBZErr
         mov     dl,0x0F
         mov     fl,0x0F
         orzx    ah,dl,fl
         cmp     ah,0x0F
         bne     TestArus_BBBZErr
         mov     el,0x0F
         mov     gl,0x0F
         xorzx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x0F
         mov     ah,0x0F
         mulzx   ch,fl,ah
         cmp     ch,0xE1
         bne     TestArus_BBBZErr
         mov     gl,0x0F
         mov     bh,0x0F
         udivzx  dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBZErr
         mov     ah,0x0F
         mov     ch,0x0F
         uremzx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x0F
         mov     dh,0x07
         shlzx   fh,bh,dh
         cmp     fh,0x80
         bne     TestArus_BBBZErr
         mov     ch,0x0F
         mov     eh,0x07
         shrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x0F
         mov     fh,0x07
         rolzx   al,dh,fh
         cmp     al,0x87
         bne     TestArus_BBBZErr
         mov     eh,0x0F
         mov     gh,0x07
         asrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x0F
         mov     al,0x7F
         addzx   cl,fh,al
         cmp     cl,0x8E
         bne     TestArus_BBBZErr
         mov     gh,0x0F
         mov     bl,0x7F
         subzx   dl,gh,bl
         cmp     dl,0x90
         bne     TestArus_BBBZErr
         mov     al,0x0F
         mov     cl,0x7F
         andzx   el,al,cl
         cmp     el,0x0F
         bne     TestArus_BBBZErr
         mov     bl,0x0F
         mov     dl,0x7F
         orzx    fl,bl,dl
         cmp     fl,0x7F
         bne     TestArus_BBBZErr
         mov     cl,0x0F
         mov     el,0x7F
         xorzx   gl,cl,el
         cmp     gl,0x70
         bne     TestArus_BBBZErr
         mov     dl,0x0F
         mov     fl,0x7F
         mulzx   ah,dl,fl
         cmp     ah,0x71
         bne     TestArus_BBBZErr
         mov     el,0x0F
         mov     gl,0x7F
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x0F
         mov     ah,0x7F
         uremzx  ch,fl,ah
         cmp     ch,0x0F
         bne     TestArus_BBBZErr
         mov     gl,0x0F
         mov     bh,0x07
         shlzx   dh,gl,bh
         cmp     dh,0x80
         bne     TestArus_BBBZErr
         mov     ah,0x0F
         mov     ch,0x07
         shrzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x0F
         mov     dh,0x07
         rolzx   fh,bh,dh
         cmp     fh,0x87
         bne     TestArus_BBBZErr
         mov     ch,0x0F
         mov     eh,0x07
         asrzx   gh,ch,eh
         cmp     gh,0x00
         bne     TestArus_BBBZErr
         mov     dh,0x0F
         mov     fh,0x80
         addzx   al,dh,fh
         cmp     al,0x8F
         bne     TestArus_BBBZErr
         mov     eh,0x0F
         mov     gh,0x80
         subzx   bl,eh,gh
         cmp     bl,0x8F
         bne     TestArus_BBBZErr
         mov     fh,0x0F
         mov     al,0x80
         andzx   cl,fh,al
         cmp     cl,0x00
         bne     TestArus_BBBZErr
         mov     gh,0x0F
         mov     bl,0x80
         orzx    dl,gh,bl
         cmp     dl,0x8F
         bne     TestArus_BBBZErr
         mov     al,0x0F
         mov     cl,0x80
         xorzx   el,al,cl
         cmp     el,0x8F
         bne     TestArus_BBBZErr
         mov     bl,0x0F
         mov     dl,0x80
         mulzx   fl,bl,dl
         cmp     fl,0x80
         bne     TestArus_BBBZErr
         mov     cl,0x0F
         mov     el,0x80
         udivzx  gl,cl,el
         cmp     gl,0x00
         bne     TestArus_BBBZErr
         mov     dl,0x0F
         mov     fl,0x80
         uremzx  ah,dl,fl
         cmp     ah,0x0F
         bne     TestArus_BBBZErr
         mov     el,0x0F
         mov     gl,0x00
         shlzx   bh,el,gl
         cmp     bh,0x0F
         bne     TestArus_BBBZErr
         mov     fl,0x0F
         mov     ah,0x00
         shrzx   ch,fl,ah
         cmp     ch,0x0F
         bne     TestArus_BBBZErr
         mov     gl,0x0F
         mov     bh,0x00
         rolzx   dh,gl,bh
         cmp     dh,0x0F
         bne     TestArus_BBBZErr
         mov     ah,0x0F
         mov     ch,0x00
         asrzx   eh,ah,ch
         cmp     eh,0x0F
         bne     TestArus_BBBZErr
         mov     bh,0x0F
         mov     dh,0xFF
         addzx   fh,bh,dh
         cmp     fh,0x0E
         bne     TestArus_BBBZErr
         mov     ch,0x0F
         mov     eh,0xFF
         subzx   gh,ch,eh
         cmp     gh,0x10
         bne     TestArus_BBBZErr
         mov     dh,0x0F
         mov     fh,0xFF
         andzx   al,dh,fh
         cmp     al,0x0F
         bne     TestArus_BBBZErr
         mov     eh,0x0F
         mov     gh,0xFF
         orzx    bl,eh,gh
         cmp     bl,0xFF
         bne     TestArus_BBBZErr
         mov     fh,0x0F
         mov     al,0xFF
         xorzx   cl,fh,al
         cmp     cl,0xF0
         bne     TestArus_BBBZErr
         mov     gh,0x0F
         mov     bl,0xFF
         mulzx   dl,gh,bl
         cmp     dl,0xF1
         bne     TestArus_BBBZErr
         mov     al,0x0F
         mov     cl,0xFF
         udivzx  el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x0F
         mov     dl,0xFF
         uremzx  fl,bl,dl
         cmp     fl,0x0F
         bne     TestArus_BBBZErr
         mov     cl,0x0F
         mov     el,0x07
         shlzx   gl,cl,el
         cmp     gl,0x80
         bne     TestArus_BBBZErr
         mov     dl,0x0F
         mov     fl,0x07
         shrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x0F
         mov     gl,0x07
         rolzx   bh,el,gl
         cmp     bh,0x87
         bne     TestArus_BBBZErr
         mov     fl,0x0F
         mov     ah,0x07
         asrzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x7F
         mov     bh,0x7F
         addzx   dh,gl,bh
         cmp     dh,0xFE
         bne     TestArus_BBBZErr
         mov     ah,0x7F
         mov     ch,0x7F
         subzx   eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x7F
         mov     dh,0x7F
         andzx   fh,bh,dh
         cmp     fh,0x7F
         bne     TestArus_BBBZErr
         mov     ch,0x7F
         mov     eh,0x7F
         orzx    gh,ch,eh
         cmp     gh,0x7F
         bne     TestArus_BBBZErr
         mov     dh,0x7F
         mov     fh,0x7F
         xorzx   al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x7F
         mov     gh,0x7F
         mulzx   bl,eh,gh
         cmp     bl,0x01
         bne     TestArus_BBBZErr
         mov     fh,0x7F
         mov     al,0x7F
         udivzx  cl,fh,al
         cmp     cl,0x01
         bne     TestArus_BBBZErr
         mov     gh,0x7F
         mov     bl,0x7F
         uremzx  dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x7F
         mov     cl,0x07
         shlzx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBZErr
         mov     bl,0x7F
         mov     dl,0x07
         shrzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x7F
         mov     el,0x07
         rolzx   gl,cl,el
         cmp     gl,0xBF
         bne     TestArus_BBBZErr
         mov     dl,0x7F
         mov     fl,0x07
         asrzx   ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0x7F
         mov     gl,0x80
         addzx   bh,el,gl
         cmp     bh,0xFF
         bne     TestArus_BBBZErr
         mov     fl,0x7F
         mov     ah,0x80
         subzx   ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBZErr
         mov     gl,0x7F
         mov     bh,0x80
         andzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x7F
         mov     ch,0x80
         orzx    eh,ah,ch
         cmp     eh,0xFF
         bne     TestArus_BBBZErr
         mov     bh,0x7F
         mov     dh,0x80
         xorzx   fh,bh,dh
         cmp     fh,0xFF
         bne     TestArus_BBBZErr
         mov     ch,0x7F
         mov     eh,0x80
         mulzx   gh,ch,eh
         cmp     gh,0x80
         bne     TestArus_BBBZErr
         mov     dh,0x7F
         mov     fh,0x80
         udivzx  al,dh,fh
         cmp     al,0x00
         bne     TestArus_BBBZErr
         mov     eh,0x7F
         mov     gh,0x80
         uremzx  bl,eh,gh
         cmp     bl,0x7F
         bne     TestArus_BBBZErr
         mov     fh,0x7F
         mov     al,0x00
         shlzx   cl,fh,al
         cmp     cl,0x7F
         bne     TestArus_BBBZErr
         mov     gh,0x7F
         mov     bl,0x00
         shrzx   dl,gh,bl
         cmp     dl,0x7F
         bne     TestArus_BBBZErr
         mov     al,0x7F
         mov     cl,0x00
         rolzx   el,al,cl
         cmp     el,0x7F
         bne     TestArus_BBBZErr
         mov     bl,0x7F
         mov     dl,0x00
         asrzx   fl,bl,dl
         cmp     fl,0x7F
         bne     TestArus_BBBZErr
         mov     cl,0x7F
         mov     el,0xFF
         addzx   gl,cl,el
         cmp     gl,0x7E
         bne     TestArus_BBBZErr
         mov     dl,0x7F
         mov     fl,0xFF
         subzx   ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBZErr
         mov     el,0x7F
         mov     gl,0xFF
         andzx   bh,el,gl
         cmp     bh,0x7F
         bne     TestArus_BBBZErr
         mov     fl,0x7F
         mov     ah,0xFF
         orzx    ch,fl,ah
         cmp     ch,0xFF
         bne     TestArus_BBBZErr
         mov     gl,0x7F
         mov     bh,0xFF
         xorzx   dh,gl,bh
         cmp     dh,0x80
         bne     TestArus_BBBZErr
         mov     ah,0x7F
         mov     ch,0xFF
         mulzx   eh,ah,ch
         cmp     eh,0x81
         bne     TestArus_BBBZErr
         mov     bh,0x7F
         mov     dh,0xFF
         udivzx  fh,bh,dh
         cmp     fh,0x00
         bne     TestArus_BBBZErr
         mov     ch,0x7F
         mov     eh,0xFF
         uremzx  gh,ch,eh
         cmp     gh,0x7F
         bne     TestArus_BBBZErr
         mov     dh,0x7F
         mov     fh,0x07
         shlzx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBZErr
         mov     eh,0x7F
         mov     gh,0x07
         shrzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0x7F
         mov     al,0x07
         rolzx   cl,fh,al
         cmp     cl,0xBF
         bne     TestArus_BBBZErr
         mov     gh,0x7F
         mov     bl,0x07
         asrzx   dl,gh,bl
         cmp     dl,0x00
         bne     TestArus_BBBZErr
         mov     al,0x80
         mov     cl,0x80
         addzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0x80
         mov     dl,0x80
         subzx   fl,bl,dl
         cmp     fl,0x00
         bne     TestArus_BBBZErr
         mov     cl,0x80
         mov     el,0x80
         andzx   gl,cl,el
         cmp     gl,0x80
         bne     TestArus_BBBZErr
         mov     dl,0x80
         mov     fl,0x80
         orzx    ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBZErr
         mov     el,0x80
         mov     gl,0x80
         xorzx   bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x80
         mov     ah,0x80
         mulzx   ch,fl,ah
         cmp     ch,0x00
         bne     TestArus_BBBZErr
         mov     gl,0x80
         mov     bh,0x80
         udivzx  dh,gl,bh
         cmp     dh,0x01
         bne     TestArus_BBBZErr
         mov     ah,0x80
         mov     ch,0x80
         uremzx  eh,ah,ch
         cmp     eh,0x00
         bne     TestArus_BBBZErr
         mov     bh,0x80
         mov     dh,0x00
         shlzx   fh,bh,dh
         cmp     fh,0x80
         bne     TestArus_BBBZErr
         mov     ch,0x80
         mov     eh,0x00
         shrzx   gh,ch,eh
         cmp     gh,0x80
         bne     TestArus_BBBZErr
         mov     dh,0x80
         mov     fh,0x00
         rolzx   al,dh,fh
         cmp     al,0x80
         bne     TestArus_BBBZErr
         mov     eh,0x80
         mov     gh,0x00
         asrzx   bl,eh,gh
         cmp     bl,0x80
         bne     TestArus_BBBZErr
         mov     fh,0x80
         mov     al,0xFF
         addzx   cl,fh,al
         cmp     cl,0x7F
         bne     TestArus_BBBZErr
         mov     gh,0x80
         mov     bl,0xFF
         subzx   dl,gh,bl
         cmp     dl,0x81
         bne     TestArus_BBBZErr
         mov     al,0x80
         mov     cl,0xFF
         andzx   el,al,cl
         cmp     el,0x80
         bne     TestArus_BBBZErr
         mov     bl,0x80
         mov     dl,0xFF
         orzx    fl,bl,dl
         cmp     fl,0xFF
         bne     TestArus_BBBZErr
         mov     cl,0x80
         mov     el,0xFF
         xorzx   gl,cl,el
         cmp     gl,0x7F
         bne     TestArus_BBBZErr
         mov     dl,0x80
         mov     fl,0xFF
         mulzx   ah,dl,fl
         cmp     ah,0x80
         bne     TestArus_BBBZErr
         mov     el,0x80
         mov     gl,0xFF
         udivzx  bh,el,gl
         cmp     bh,0x00
         bne     TestArus_BBBZErr
         mov     fl,0x80
         mov     ah,0xFF
         uremzx  ch,fl,ah
         cmp     ch,0x80
         bne     TestArus_BBBZErr
         mov     gl,0x80
         mov     bh,0x07
         shlzx   dh,gl,bh
         cmp     dh,0x00
         bne     TestArus_BBBZErr
         mov     ah,0x80
         mov     ch,0x07
         shrzx   eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBZErr
         mov     bh,0x80
         mov     dh,0x07
         rolzx   fh,bh,dh
         cmp     fh,0x40
         bne     TestArus_BBBZErr
         mov     ch,0x80
         mov     eh,0x07
         asrzx   gh,ch,eh
         cmp     gh,0x01
         bne     TestArus_BBBZErr
         mov     dh,0xFF
         mov     fh,0xFF
         addzx   al,dh,fh
         cmp     al,0xFE
         bne     TestArus_BBBZErr
         mov     eh,0xFF
         mov     gh,0xFF
         subzx   bl,eh,gh
         cmp     bl,0x00
         bne     TestArus_BBBZErr
         mov     fh,0xFF
         mov     al,0xFF
         andzx   cl,fh,al
         cmp     cl,0xFF
         bne     TestArus_BBBZErr
         mov     gh,0xFF
         mov     bl,0xFF
         orzx    dl,gh,bl
         cmp     dl,0xFF
         bne     TestArus_BBBZErr
         mov     al,0xFF
         mov     cl,0xFF
         xorzx   el,al,cl
         cmp     el,0x00
         bne     TestArus_BBBZErr
         mov     bl,0xFF
         mov     dl,0xFF
         mulzx   fl,bl,dl
         cmp     fl,0x01
         bne     TestArus_BBBZErr
         mov     cl,0xFF
         mov     el,0xFF
         udivzx  gl,cl,el
         cmp     gl,0x01
         bne     TestArus_BBBZErr
         mov     dl,0xFF
         mov     fl,0xFF
         uremzx  ah,dl,fl
         cmp     ah,0x00
         bne     TestArus_BBBZErr
         mov     el,0xFF
         mov     gl,0x07
         shlzx   bh,el,gl
         cmp     bh,0x80
         bne     TestArus_BBBZErr
         mov     fl,0xFF
         mov     ah,0x07
         shrzx   ch,fl,ah
         cmp     ch,0x01
         bne     TestArus_BBBZErr
         mov     gl,0xFF
         mov     bh,0x07
         rolzx   dh,gl,bh
         cmp     dh,0xFF
         bne     TestArus_BBBZErr
         mov     ah,0xFF
         mov     ch,0x07
         asrzx   eh,ah,ch
         cmp     eh,0x01
         bne     TestArus_BBBZErr
         bra     TestArus_BBBZRet
TestArus_BBBZErr:
         nop     
         trap    
         nop     
TestArus_BBBZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
