.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WWWS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WWWS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         mov     cx,0x0000
         addsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0000
         mov     dx,0x0000
         subsx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x0000
         mov     ex,0x0000
         andsx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x0000
         mov     fx,0x0000
         orsx    aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x0000
         mov     gx,0x0000
         xorsx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0000
         mov     aw,0x0000
         mulsx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWSErr
         mov     gx,0x0000
         mov     bw,0x0000
         sdivsx  dw,gx,bw
         cmp     dw,0xFFFF
         bne     TestArus_WWWSErr
         mov     aw,0x0000
         mov     cw,0x0000
         sremsx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWSErr
         mov     bw,0x0000
         mov     dw,0x0001
         addsx   fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWSErr
         mov     cw,0x0000
         mov     ew,0x0001
         subsx   gw,cw,ew
         cmp     gw,0xFFFF
         bne     TestArus_WWWSErr
         mov     dw,0x0000
         mov     fw,0x0001
         andsx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0000
         mov     gw,0x0001
         orsx    bx,ew,gw
         cmp     bx,0x0001
         bne     TestArus_WWWSErr
         mov     fw,0x0000
         mov     ax,0x0001
         xorsx   cx,fw,ax
         cmp     cx,0x0001
         bne     TestArus_WWWSErr
         mov     gw,0x0000
         mov     bx,0x0001
         mulsx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWSErr
         mov     ax,0x0000
         mov     cx,0x0001
         sdivsx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0000
         mov     dx,0x0001
         sremsx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x0000
         mov     ex,0x0008
         addsx   gx,cx,ex
         cmp     gx,0x0008
         bne     TestArus_WWWSErr
         mov     dx,0x0000
         mov     fx,0x0008
         subsx   aw,dx,fx
         cmp     aw,0xFFF8
         bne     TestArus_WWWSErr
         mov     ex,0x0000
         mov     gx,0x0008
         andsx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0000
         mov     aw,0x0008
         orsx    cw,fx,aw
         cmp     cw,0x0008
         bne     TestArus_WWWSErr
         mov     gx,0x0000
         mov     bw,0x0008
         xorsx   dw,gx,bw
         cmp     dw,0x0008
         bne     TestArus_WWWSErr
         mov     aw,0x0000
         mov     cw,0x0008
         mulsx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWSErr
         mov     bw,0x0000
         mov     dw,0x0008
         sdivsx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWSErr
         mov     cw,0x0000
         mov     ew,0x0008
         sremsx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         mov     dw,0x0000
         mov     fw,0x0009
         addsx   ax,dw,fw
         cmp     ax,0x0009
         bne     TestArus_WWWSErr
         mov     ew,0x0000
         mov     gw,0x0009
         subsx   bx,ew,gw
         cmp     bx,0xFFF7
         bne     TestArus_WWWSErr
         mov     fw,0x0000
         mov     ax,0x0009
         andsx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x0000
         mov     bx,0x0009
         orsx    dx,gw,bx
         cmp     dx,0x0009
         bne     TestArus_WWWSErr
         mov     ax,0x0000
         mov     cx,0x0009
         xorsx   ex,ax,cx
         cmp     ex,0x0009
         bne     TestArus_WWWSErr
         mov     bx,0x0000
         mov     dx,0x0009
         mulsx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x0000
         mov     ex,0x0009
         sdivsx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x0000
         mov     fx,0x0009
         sremsx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x0000
         mov     gx,0x007F
         addsx   bw,ex,gx
         cmp     bw,0x007F
         bne     TestArus_WWWSErr
         mov     fx,0x0000
         mov     aw,0x007F
         subsx   cw,fx,aw
         cmp     cw,0xFF81
         bne     TestArus_WWWSErr
         mov     gx,0x0000
         mov     bw,0x007F
         andsx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x0000
         mov     cw,0x007F
         orsx    ew,aw,cw
         cmp     ew,0x007F
         bne     TestArus_WWWSErr
         mov     bw,0x0000
         mov     dw,0x007F
         xorsx   fw,bw,dw
         cmp     fw,0x007F
         bne     TestArus_WWWSErr
         mov     cw,0x0000
         mov     ew,0x007F
         mulsx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         mov     dw,0x0000
         mov     fw,0x007F
         sdivsx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0000
         mov     gw,0x007F
         sremsx  bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWSErr
         mov     fw,0x0000
         mov     ax,0x0080
         addsx   cx,fw,ax
         cmp     cx,0x0080
         bne     TestArus_WWWSErr
         mov     gw,0x0000
         mov     bx,0x0080
         subsx   dx,gw,bx
         cmp     dx,0xFF80
         bne     TestArus_WWWSErr
         mov     ax,0x0000
         mov     cx,0x0080
         andsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0000
         mov     dx,0x0080
         orsx    fx,bx,dx
         cmp     fx,0x0080
         bne     TestArus_WWWSErr
         mov     cx,0x0000
         mov     ex,0x0080
         xorsx   gx,cx,ex
         cmp     gx,0x0080
         bne     TestArus_WWWSErr
         mov     dx,0x0000
         mov     fx,0x0080
         mulsx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x0000
         mov     gx,0x0080
         sdivsx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0000
         mov     aw,0x0080
         sremsx  cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWSErr
         mov     gx,0x0000
         mov     bw,0x7FFF
         addsx   dw,gx,bw
         cmp     dw,0x7FFF
         bne     TestArus_WWWSErr
         mov     aw,0x0000
         mov     cw,0x7FFF
         subsx   ew,aw,cw
         cmp     ew,0x8001
         bne     TestArus_WWWSErr
         mov     bw,0x0000
         mov     dw,0x7FFF
         andsx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWSErr
         mov     cw,0x0000
         mov     ew,0x7FFF
         orsx    gw,cw,ew
         cmp     gw,0x7FFF
         bne     TestArus_WWWSErr
         mov     dw,0x0000
         mov     fw,0x7FFF
         xorsx   ax,dw,fw
         cmp     ax,0x7FFF
         bne     TestArus_WWWSErr
         mov     ew,0x0000
         mov     gw,0x7FFF
         mulsx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWSErr
         mov     fw,0x0000
         mov     ax,0x7FFF
         sdivsx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x0000
         mov     bx,0x7FFF
         sremsx  dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWSErr
         mov     ax,0x0000
         mov     cx,0x8000
         addsx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWSErr
         mov     bx,0x0000
         mov     dx,0x8000
         subsx   fx,bx,dx
         cmp     fx,0x8000
         bne     TestArus_WWWSErr
         mov     cx,0x0000
         mov     ex,0x8000
         andsx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x0000
         mov     fx,0x8000
         orsx    aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWSErr
         mov     ex,0x0000
         mov     gx,0x8000
         xorsx   bw,ex,gx
         cmp     bw,0x8000
         bne     TestArus_WWWSErr
         mov     fx,0x0000
         mov     aw,0x8000
         mulsx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWSErr
         mov     gx,0x0000
         mov     bw,0x8000
         sdivsx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x0000
         mov     cw,0x8000
         sremsx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWSErr
         mov     bw,0x0000
         mov     dw,0xFFFF
         addsx   fw,bw,dw
         cmp     fw,0xFFFF
         bne     TestArus_WWWSErr
         mov     cw,0x0000
         mov     ew,0xFFFF
         subsx   gw,cw,ew
         cmp     gw,0x0001
         bne     TestArus_WWWSErr
         mov     dw,0x0000
         mov     fw,0xFFFF
         andsx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0000
         mov     gw,0xFFFF
         orsx    bx,ew,gw
         cmp     bx,0xFFFF
         bne     TestArus_WWWSErr
         mov     fw,0x0000
         mov     ax,0xFFFF
         xorsx   cx,fw,ax
         cmp     cx,0xFFFF
         bne     TestArus_WWWSErr
         mov     gw,0x0000
         mov     bx,0xFFFF
         mulsx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWSErr
         mov     ax,0x0000
         mov     cx,0xFFFF
         sdivsx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0000
         mov     dx,0xFFFF
         sremsx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x0001
         mov     ex,0x0001
         addsx   gx,cx,ex
         cmp     gx,0x0002
         bne     TestArus_WWWSErr
         mov     dx,0x0001
         mov     fx,0x0001
         subsx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x0001
         mov     gx,0x0001
         andsx   bw,ex,gx
         cmp     bw,0x0001
         bne     TestArus_WWWSErr
         mov     fx,0x0001
         mov     aw,0x0001
         orsx    cw,fx,aw
         cmp     cw,0x0001
         bne     TestArus_WWWSErr
         mov     gx,0x0001
         mov     bw,0x0001
         xorsx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x0001
         mov     cw,0x0001
         mulsx   ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWSErr
         mov     bw,0x0001
         mov     dw,0x0001
         sdivsx  fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWSErr
         mov     cw,0x0001
         mov     ew,0x0001
         sremsx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         mov     dw,0x0001
         mov     fw,0x0008
         addsx   ax,dw,fw
         cmp     ax,0x0009
         bne     TestArus_WWWSErr
         mov     ew,0x0001
         mov     gw,0x0008
         subsx   bx,ew,gw
         cmp     bx,0xFFF9
         bne     TestArus_WWWSErr
         mov     fw,0x0001
         mov     ax,0x0008
         andsx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x0001
         mov     bx,0x0008
         orsx    dx,gw,bx
         cmp     dx,0x0009
         bne     TestArus_WWWSErr
         mov     ax,0x0001
         mov     cx,0x0008
         xorsx   ex,ax,cx
         cmp     ex,0x0009
         bne     TestArus_WWWSErr
         mov     bx,0x0001
         mov     dx,0x0008
         mulsx   fx,bx,dx
         cmp     fx,0x0008
         bne     TestArus_WWWSErr
         mov     cx,0x0001
         mov     ex,0x0008
         sdivsx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x0001
         mov     fx,0x0008
         sremsx  aw,dx,fx
         cmp     aw,0x0001
         bne     TestArus_WWWSErr
         mov     ex,0x0001
         mov     gx,0x0009
         addsx   bw,ex,gx
         cmp     bw,0x000A
         bne     TestArus_WWWSErr
         mov     fx,0x0001
         mov     aw,0x0009
         subsx   cw,fx,aw
         cmp     cw,0xFFF8
         bne     TestArus_WWWSErr
         mov     gx,0x0001
         mov     bw,0x0009
         andsx   dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWSErr
         mov     aw,0x0001
         mov     cw,0x0009
         orsx    ew,aw,cw
         cmp     ew,0x0009
         bne     TestArus_WWWSErr
         mov     bw,0x0001
         mov     dw,0x0009
         xorsx   fw,bw,dw
         cmp     fw,0x0008
         bne     TestArus_WWWSErr
         mov     cw,0x0001
         mov     ew,0x0009
         mulsx   gw,cw,ew
         cmp     gw,0x0009
         bne     TestArus_WWWSErr
         mov     dw,0x0001
         mov     fw,0x0009
         sdivsx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0001
         mov     gw,0x0009
         sremsx  bx,ew,gw
         cmp     bx,0x0001
         bne     TestArus_WWWSErr
         mov     fw,0x0001
         mov     ax,0x007F
         addsx   cx,fw,ax
         cmp     cx,0x0080
         bne     TestArus_WWWSErr
         mov     gw,0x0001
         mov     bx,0x007F
         subsx   dx,gw,bx
         cmp     dx,0xFF82
         bne     TestArus_WWWSErr
         mov     ax,0x0001
         mov     cx,0x007F
         andsx   ex,ax,cx
         cmp     ex,0x0001
         bne     TestArus_WWWSErr
         mov     bx,0x0001
         mov     dx,0x007F
         orsx    fx,bx,dx
         cmp     fx,0x007F
         bne     TestArus_WWWSErr
         mov     cx,0x0001
         mov     ex,0x007F
         xorsx   gx,cx,ex
         cmp     gx,0x007E
         bne     TestArus_WWWSErr
         mov     dx,0x0001
         mov     fx,0x007F
         mulsx   aw,dx,fx
         cmp     aw,0x007F
         bne     TestArus_WWWSErr
         mov     ex,0x0001
         mov     gx,0x007F
         sdivsx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0001
         mov     aw,0x007F
         sremsx  cw,fx,aw
         cmp     cw,0x0001
         bne     TestArus_WWWSErr
         mov     gx,0x0001
         mov     bw,0x0080
         addsx   dw,gx,bw
         cmp     dw,0x0081
         bne     TestArus_WWWSErr
         mov     aw,0x0001
         mov     cw,0x0080
         subsx   ew,aw,cw
         cmp     ew,0xFF81
         bne     TestArus_WWWSErr
         mov     bw,0x0001
         mov     dw,0x0080
         andsx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWSErr
         mov     cw,0x0001
         mov     ew,0x0080
         orsx    gw,cw,ew
         cmp     gw,0x0081
         bne     TestArus_WWWSErr
         mov     dw,0x0001
         mov     fw,0x0080
         xorsx   ax,dw,fw
         cmp     ax,0x0081
         bne     TestArus_WWWSErr
         mov     ew,0x0001
         mov     gw,0x0080
         mulsx   bx,ew,gw
         cmp     bx,0x0080
         bne     TestArus_WWWSErr
         mov     fw,0x0001
         mov     ax,0x0080
         sdivsx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x0001
         mov     bx,0x0080
         sremsx  dx,gw,bx
         cmp     dx,0x0001
         bne     TestArus_WWWSErr
         mov     ax,0x0001
         mov     cx,0x7FFF
         addsx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWSErr
         mov     bx,0x0001
         mov     dx,0x7FFF
         subsx   fx,bx,dx
         cmp     fx,0x8002
         bne     TestArus_WWWSErr
         mov     cx,0x0001
         mov     ex,0x7FFF
         andsx   gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWSErr
         mov     dx,0x0001
         mov     fx,0x7FFF
         orsx    aw,dx,fx
         cmp     aw,0x7FFF
         bne     TestArus_WWWSErr
         mov     ex,0x0001
         mov     gx,0x7FFF
         xorsx   bw,ex,gx
         cmp     bw,0x7FFE
         bne     TestArus_WWWSErr
         mov     fx,0x0001
         mov     aw,0x7FFF
         mulsx   cw,fx,aw
         cmp     cw,0x7FFF
         bne     TestArus_WWWSErr
         mov     gx,0x0001
         mov     bw,0x7FFF
         sdivsx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x0001
         mov     cw,0x7FFF
         sremsx  ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWSErr
         mov     bw,0x0001
         mov     dw,0x8000
         addsx   fw,bw,dw
         cmp     fw,0x8001
         bne     TestArus_WWWSErr
         mov     cw,0x0001
         mov     ew,0x8000
         subsx   gw,cw,ew
         cmp     gw,0x8001
         bne     TestArus_WWWSErr
         mov     dw,0x0001
         mov     fw,0x8000
         andsx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0001
         mov     gw,0x8000
         orsx    bx,ew,gw
         cmp     bx,0x8001
         bne     TestArus_WWWSErr
         mov     fw,0x0001
         mov     ax,0x8000
         xorsx   cx,fw,ax
         cmp     cx,0x8001
         bne     TestArus_WWWSErr
         mov     gw,0x0001
         mov     bx,0x8000
         mulsx   dx,gw,bx
         cmp     dx,0x8000
         bne     TestArus_WWWSErr
         mov     ax,0x0001
         mov     cx,0x8000
         sdivsx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0001
         mov     dx,0x8000
         sremsx  fx,bx,dx
         cmp     fx,0x0001
         bne     TestArus_WWWSErr
         mov     cx,0x0001
         mov     ex,0xFFFF
         addsx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x0001
         mov     fx,0xFFFF
         subsx   aw,dx,fx
         cmp     aw,0x0002
         bne     TestArus_WWWSErr
         mov     ex,0x0001
         mov     gx,0xFFFF
         andsx   bw,ex,gx
         cmp     bw,0x0001
         bne     TestArus_WWWSErr
         mov     fx,0x0001
         mov     aw,0xFFFF
         orsx    cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWSErr
         mov     gx,0x0001
         mov     bw,0xFFFF
         xorsx   dw,gx,bw
         cmp     dw,0xFFFE
         bne     TestArus_WWWSErr
         mov     aw,0x0001
         mov     cw,0xFFFF
         mulsx   ew,aw,cw
         cmp     ew,0xFFFF
         bne     TestArus_WWWSErr
         mov     bw,0x0001
         mov     dw,0xFFFF
         sdivsx  fw,bw,dw
         cmp     fw,0xFFFF
         bne     TestArus_WWWSErr
         mov     cw,0x0001
         mov     ew,0xFFFF
         sremsx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         mov     dw,0x0008
         mov     fw,0x0008
         addsx   ax,dw,fw
         cmp     ax,0x0010
         bne     TestArus_WWWSErr
         mov     ew,0x0008
         mov     gw,0x0008
         subsx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWSErr
         mov     fw,0x0008
         mov     ax,0x0008
         andsx   cx,fw,ax
         cmp     cx,0x0008
         bne     TestArus_WWWSErr
         mov     gw,0x0008
         mov     bx,0x0008
         orsx    dx,gw,bx
         cmp     dx,0x0008
         bne     TestArus_WWWSErr
         mov     ax,0x0008
         mov     cx,0x0008
         xorsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0008
         mov     dx,0x0008
         mulsx   fx,bx,dx
         cmp     fx,0x0040
         bne     TestArus_WWWSErr
         mov     cx,0x0008
         mov     ex,0x0008
         sdivsx  gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWSErr
         mov     dx,0x0008
         mov     fx,0x0008
         sremsx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x0008
         mov     gx,0x0009
         addsx   bw,ex,gx
         cmp     bw,0x0011
         bne     TestArus_WWWSErr
         mov     fx,0x0008
         mov     aw,0x0009
         subsx   cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWSErr
         mov     gx,0x0008
         mov     bw,0x0009
         andsx   dw,gx,bw
         cmp     dw,0x0008
         bne     TestArus_WWWSErr
         mov     aw,0x0008
         mov     cw,0x0009
         orsx    ew,aw,cw
         cmp     ew,0x0009
         bne     TestArus_WWWSErr
         mov     bw,0x0008
         mov     dw,0x0009
         xorsx   fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWSErr
         mov     cw,0x0008
         mov     ew,0x0009
         mulsx   gw,cw,ew
         cmp     gw,0x0048
         bne     TestArus_WWWSErr
         mov     dw,0x0008
         mov     fw,0x0009
         sdivsx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0008
         mov     gw,0x0009
         sremsx  bx,ew,gw
         cmp     bx,0x0008
         bne     TestArus_WWWSErr
         mov     fw,0x0008
         mov     ax,0x007F
         addsx   cx,fw,ax
         cmp     cx,0x0087
         bne     TestArus_WWWSErr
         mov     gw,0x0008
         mov     bx,0x007F
         subsx   dx,gw,bx
         cmp     dx,0xFF89
         bne     TestArus_WWWSErr
         mov     ax,0x0008
         mov     cx,0x007F
         andsx   ex,ax,cx
         cmp     ex,0x0008
         bne     TestArus_WWWSErr
         mov     bx,0x0008
         mov     dx,0x007F
         orsx    fx,bx,dx
         cmp     fx,0x007F
         bne     TestArus_WWWSErr
         mov     cx,0x0008
         mov     ex,0x007F
         xorsx   gx,cx,ex
         cmp     gx,0x0077
         bne     TestArus_WWWSErr
         mov     dx,0x0008
         mov     fx,0x007F
         mulsx   aw,dx,fx
         cmp     aw,0x03F8
         bne     TestArus_WWWSErr
         mov     ex,0x0008
         mov     gx,0x007F
         sdivsx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0008
         mov     aw,0x007F
         sremsx  cw,fx,aw
         cmp     cw,0x0008
         bne     TestArus_WWWSErr
         mov     gx,0x0008
         mov     bw,0x0080
         addsx   dw,gx,bw
         cmp     dw,0x0088
         bne     TestArus_WWWSErr
         mov     aw,0x0008
         mov     cw,0x0080
         subsx   ew,aw,cw
         cmp     ew,0xFF88
         bne     TestArus_WWWSErr
         mov     bw,0x0008
         mov     dw,0x0080
         andsx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWSErr
         mov     cw,0x0008
         mov     ew,0x0080
         orsx    gw,cw,ew
         cmp     gw,0x0088
         bne     TestArus_WWWSErr
         mov     dw,0x0008
         mov     fw,0x0080
         xorsx   ax,dw,fw
         cmp     ax,0x0088
         bne     TestArus_WWWSErr
         mov     ew,0x0008
         mov     gw,0x0080
         mulsx   bx,ew,gw
         cmp     bx,0x0400
         bne     TestArus_WWWSErr
         mov     fw,0x0008
         mov     ax,0x0080
         sdivsx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x0008
         mov     bx,0x0080
         sremsx  dx,gw,bx
         cmp     dx,0x0008
         bne     TestArus_WWWSErr
         mov     ax,0x0008
         mov     cx,0x7FFF
         addsx   ex,ax,cx
         cmp     ex,0x8007
         bne     TestArus_WWWSErr
         mov     bx,0x0008
         mov     dx,0x7FFF
         subsx   fx,bx,dx
         cmp     fx,0x8009
         bne     TestArus_WWWSErr
         mov     cx,0x0008
         mov     ex,0x7FFF
         andsx   gx,cx,ex
         cmp     gx,0x0008
         bne     TestArus_WWWSErr
         mov     dx,0x0008
         mov     fx,0x7FFF
         orsx    aw,dx,fx
         cmp     aw,0x7FFF
         bne     TestArus_WWWSErr
         mov     ex,0x0008
         mov     gx,0x7FFF
         xorsx   bw,ex,gx
         cmp     bw,0x7FF7
         bne     TestArus_WWWSErr
         mov     fx,0x0008
         mov     aw,0x7FFF
         mulsx   cw,fx,aw
         cmp     cw,0xFFF8
         bne     TestArus_WWWSErr
         mov     gx,0x0008
         mov     bw,0x7FFF
         sdivsx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x0008
         mov     cw,0x7FFF
         sremsx  ew,aw,cw
         cmp     ew,0x0008
         bne     TestArus_WWWSErr
         mov     bw,0x0008
         mov     dw,0x8000
         addsx   fw,bw,dw
         cmp     fw,0x8008
         bne     TestArus_WWWSErr
         mov     cw,0x0008
         mov     ew,0x8000
         subsx   gw,cw,ew
         cmp     gw,0x8008
         bne     TestArus_WWWSErr
         mov     dw,0x0008
         mov     fw,0x8000
         andsx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0008
         mov     gw,0x8000
         orsx    bx,ew,gw
         cmp     bx,0x8008
         bne     TestArus_WWWSErr
         mov     fw,0x0008
         mov     ax,0x8000
         xorsx   cx,fw,ax
         cmp     cx,0x8008
         bne     TestArus_WWWSErr
         mov     gw,0x0008
         mov     bx,0x8000
         mulsx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWSErr
         mov     ax,0x0008
         mov     cx,0x8000
         sdivsx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0008
         mov     dx,0x8000
         sremsx  fx,bx,dx
         cmp     fx,0x0008
         bne     TestArus_WWWSErr
         mov     cx,0x0008
         mov     ex,0xFFFF
         addsx   gx,cx,ex
         cmp     gx,0x0007
         bne     TestArus_WWWSErr
         mov     dx,0x0008
         mov     fx,0xFFFF
         subsx   aw,dx,fx
         cmp     aw,0x0009
         bne     TestArus_WWWSErr
         mov     ex,0x0008
         mov     gx,0xFFFF
         andsx   bw,ex,gx
         cmp     bw,0x0008
         bne     TestArus_WWWSErr
         mov     fx,0x0008
         mov     aw,0xFFFF
         orsx    cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWSErr
         mov     gx,0x0008
         mov     bw,0xFFFF
         xorsx   dw,gx,bw
         cmp     dw,0xFFF7
         bne     TestArus_WWWSErr
         mov     aw,0x0008
         mov     cw,0xFFFF
         mulsx   ew,aw,cw
         cmp     ew,0xFFF8
         bne     TestArus_WWWSErr
         mov     bw,0x0008
         mov     dw,0xFFFF
         sdivsx  fw,bw,dw
         cmp     fw,0xFFF8
         bne     TestArus_WWWSErr
         mov     cw,0x0008
         mov     ew,0xFFFF
         sremsx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         mov     dw,0x0009
         mov     fw,0x0009
         addsx   ax,dw,fw
         cmp     ax,0x0012
         bne     TestArus_WWWSErr
         mov     ew,0x0009
         mov     gw,0x0009
         subsx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWSErr
         mov     fw,0x0009
         mov     ax,0x0009
         andsx   cx,fw,ax
         cmp     cx,0x0009
         bne     TestArus_WWWSErr
         mov     gw,0x0009
         mov     bx,0x0009
         orsx    dx,gw,bx
         cmp     dx,0x0009
         bne     TestArus_WWWSErr
         mov     ax,0x0009
         mov     cx,0x0009
         xorsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0009
         mov     dx,0x0009
         mulsx   fx,bx,dx
         cmp     fx,0x0051
         bne     TestArus_WWWSErr
         mov     cx,0x0009
         mov     ex,0x0009
         sdivsx  gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWSErr
         mov     dx,0x0009
         mov     fx,0x0009
         sremsx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x0009
         mov     gx,0x007F
         addsx   bw,ex,gx
         cmp     bw,0x0088
         bne     TestArus_WWWSErr
         mov     fx,0x0009
         mov     aw,0x007F
         subsx   cw,fx,aw
         cmp     cw,0xFF8A
         bne     TestArus_WWWSErr
         mov     gx,0x0009
         mov     bw,0x007F
         andsx   dw,gx,bw
         cmp     dw,0x0009
         bne     TestArus_WWWSErr
         mov     aw,0x0009
         mov     cw,0x007F
         orsx    ew,aw,cw
         cmp     ew,0x007F
         bne     TestArus_WWWSErr
         mov     bw,0x0009
         mov     dw,0x007F
         xorsx   fw,bw,dw
         cmp     fw,0x0076
         bne     TestArus_WWWSErr
         mov     cw,0x0009
         mov     ew,0x007F
         mulsx   gw,cw,ew
         cmp     gw,0x0477
         bne     TestArus_WWWSErr
         mov     dw,0x0009
         mov     fw,0x007F
         sdivsx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x0009
         mov     gw,0x007F
         sremsx  bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWSErr
         mov     fw,0x0009
         mov     ax,0x0080
         addsx   cx,fw,ax
         cmp     cx,0x0089
         bne     TestArus_WWWSErr
         mov     gw,0x0009
         mov     bx,0x0080
         subsx   dx,gw,bx
         cmp     dx,0xFF89
         bne     TestArus_WWWSErr
         mov     ax,0x0009
         mov     cx,0x0080
         andsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0009
         mov     dx,0x0080
         orsx    fx,bx,dx
         cmp     fx,0x0089
         bne     TestArus_WWWSErr
         mov     cx,0x0009
         mov     ex,0x0080
         xorsx   gx,cx,ex
         cmp     gx,0x0089
         bne     TestArus_WWWSErr
         mov     dx,0x0009
         mov     fx,0x0080
         mulsx   aw,dx,fx
         cmp     aw,0x0480
         bne     TestArus_WWWSErr
         mov     ex,0x0009
         mov     gx,0x0080
         sdivsx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0009
         mov     aw,0x0080
         sremsx  cw,fx,aw
         cmp     cw,0x0009
         bne     TestArus_WWWSErr
         mov     gx,0x0009
         mov     bw,0x7FFF
         addsx   dw,gx,bw
         cmp     dw,0x8008
         bne     TestArus_WWWSErr
         mov     aw,0x0009
         mov     cw,0x7FFF
         subsx   ew,aw,cw
         cmp     ew,0x800A
         bne     TestArus_WWWSErr
         mov     bw,0x0009
         mov     dw,0x7FFF
         andsx   fw,bw,dw
         cmp     fw,0x0009
         bne     TestArus_WWWSErr
         mov     cw,0x0009
         mov     ew,0x7FFF
         orsx    gw,cw,ew
         cmp     gw,0x7FFF
         bne     TestArus_WWWSErr
         mov     dw,0x0009
         mov     fw,0x7FFF
         xorsx   ax,dw,fw
         cmp     ax,0x7FF6
         bne     TestArus_WWWSErr
         mov     ew,0x0009
         mov     gw,0x7FFF
         mulsx   bx,ew,gw
         cmp     bx,0x7FF7
         bne     TestArus_WWWSErr
         mov     fw,0x0009
         mov     ax,0x7FFF
         sdivsx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x0009
         mov     bx,0x7FFF
         sremsx  dx,gw,bx
         cmp     dx,0x0009
         bne     TestArus_WWWSErr
         mov     ax,0x0009
         mov     cx,0x8000
         addsx   ex,ax,cx
         cmp     ex,0x8009
         bne     TestArus_WWWSErr
         mov     bx,0x0009
         mov     dx,0x8000
         subsx   fx,bx,dx
         cmp     fx,0x8009
         bne     TestArus_WWWSErr
         mov     cx,0x0009
         mov     ex,0x8000
         andsx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x0009
         mov     fx,0x8000
         orsx    aw,dx,fx
         cmp     aw,0x8009
         bne     TestArus_WWWSErr
         mov     ex,0x0009
         mov     gx,0x8000
         xorsx   bw,ex,gx
         cmp     bw,0x8009
         bne     TestArus_WWWSErr
         mov     fx,0x0009
         mov     aw,0x8000
         mulsx   cw,fx,aw
         cmp     cw,0x8000
         bne     TestArus_WWWSErr
         mov     gx,0x0009
         mov     bw,0x8000
         sdivsx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x0009
         mov     cw,0x8000
         sremsx  ew,aw,cw
         cmp     ew,0x0009
         bne     TestArus_WWWSErr
         mov     bw,0x0009
         mov     dw,0xFFFF
         addsx   fw,bw,dw
         cmp     fw,0x0008
         bne     TestArus_WWWSErr
         mov     cw,0x0009
         mov     ew,0xFFFF
         subsx   gw,cw,ew
         cmp     gw,0x000A
         bne     TestArus_WWWSErr
         mov     dw,0x0009
         mov     fw,0xFFFF
         andsx   ax,dw,fw
         cmp     ax,0x0009
         bne     TestArus_WWWSErr
         mov     ew,0x0009
         mov     gw,0xFFFF
         orsx    bx,ew,gw
         cmp     bx,0xFFFF
         bne     TestArus_WWWSErr
         mov     fw,0x0009
         mov     ax,0xFFFF
         xorsx   cx,fw,ax
         cmp     cx,0xFFF6
         bne     TestArus_WWWSErr
         mov     gw,0x0009
         mov     bx,0xFFFF
         mulsx   dx,gw,bx
         cmp     dx,0xFFF7
         bne     TestArus_WWWSErr
         mov     ax,0x0009
         mov     cx,0xFFFF
         sdivsx  ex,ax,cx
         cmp     ex,0xFFF7
         bne     TestArus_WWWSErr
         mov     bx,0x0009
         mov     dx,0xFFFF
         sremsx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x007F
         mov     ex,0x007F
         addsx   gx,cx,ex
         cmp     gx,0x00FE
         bne     TestArus_WWWSErr
         mov     dx,0x007F
         mov     fx,0x007F
         subsx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x007F
         mov     gx,0x007F
         andsx   bw,ex,gx
         cmp     bw,0x007F
         bne     TestArus_WWWSErr
         mov     fx,0x007F
         mov     aw,0x007F
         orsx    cw,fx,aw
         cmp     cw,0x007F
         bne     TestArus_WWWSErr
         mov     gx,0x007F
         mov     bw,0x007F
         xorsx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0x007F
         mov     cw,0x007F
         mulsx   ew,aw,cw
         cmp     ew,0x3F01
         bne     TestArus_WWWSErr
         mov     bw,0x007F
         mov     dw,0x007F
         sdivsx  fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWSErr
         mov     cw,0x007F
         mov     ew,0x007F
         sremsx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         mov     dw,0x007F
         mov     fw,0x0080
         addsx   ax,dw,fw
         cmp     ax,0x00FF
         bne     TestArus_WWWSErr
         mov     ew,0x007F
         mov     gw,0x0080
         subsx   bx,ew,gw
         cmp     bx,0xFFFF
         bne     TestArus_WWWSErr
         mov     fw,0x007F
         mov     ax,0x0080
         andsx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWSErr
         mov     gw,0x007F
         mov     bx,0x0080
         orsx    dx,gw,bx
         cmp     dx,0x00FF
         bne     TestArus_WWWSErr
         mov     ax,0x007F
         mov     cx,0x0080
         xorsx   ex,ax,cx
         cmp     ex,0x00FF
         bne     TestArus_WWWSErr
         mov     bx,0x007F
         mov     dx,0x0080
         mulsx   fx,bx,dx
         cmp     fx,0x3F80
         bne     TestArus_WWWSErr
         mov     cx,0x007F
         mov     ex,0x0080
         sdivsx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWSErr
         mov     dx,0x007F
         mov     fx,0x0080
         sremsx  aw,dx,fx
         cmp     aw,0x007F
         bne     TestArus_WWWSErr
         mov     ex,0x007F
         mov     gx,0x7FFF
         addsx   bw,ex,gx
         cmp     bw,0x807E
         bne     TestArus_WWWSErr
         mov     fx,0x007F
         mov     aw,0x7FFF
         subsx   cw,fx,aw
         cmp     cw,0x8080
         bne     TestArus_WWWSErr
         mov     gx,0x007F
         mov     bw,0x7FFF
         andsx   dw,gx,bw
         cmp     dw,0x007F
         bne     TestArus_WWWSErr
         mov     aw,0x007F
         mov     cw,0x7FFF
         orsx    ew,aw,cw
         cmp     ew,0x7FFF
         bne     TestArus_WWWSErr
         mov     bw,0x007F
         mov     dw,0x7FFF
         xorsx   fw,bw,dw
         cmp     fw,0x7F80
         bne     TestArus_WWWSErr
         mov     cw,0x007F
         mov     ew,0x7FFF
         mulsx   gw,cw,ew
         cmp     gw,0x7F81
         bne     TestArus_WWWSErr
         mov     dw,0x007F
         mov     fw,0x7FFF
         sdivsx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWSErr
         mov     ew,0x007F
         mov     gw,0x7FFF
         sremsx  bx,ew,gw
         cmp     bx,0x007F
         bne     TestArus_WWWSErr
         mov     fw,0x007F
         mov     ax,0x8000
         addsx   cx,fw,ax
         cmp     cx,0x807F
         bne     TestArus_WWWSErr
         mov     gw,0x007F
         mov     bx,0x8000
         subsx   dx,gw,bx
         cmp     dx,0x807F
         bne     TestArus_WWWSErr
         mov     ax,0x007F
         mov     cx,0x8000
         andsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x007F
         mov     dx,0x8000
         orsx    fx,bx,dx
         cmp     fx,0x807F
         bne     TestArus_WWWSErr
         mov     cx,0x007F
         mov     ex,0x8000
         xorsx   gx,cx,ex
         cmp     gx,0x807F
         bne     TestArus_WWWSErr
         mov     dx,0x007F
         mov     fx,0x8000
         mulsx   aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWSErr
         mov     ex,0x007F
         mov     gx,0x8000
         sdivsx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x007F
         mov     aw,0x8000
         sremsx  cw,fx,aw
         cmp     cw,0x007F
         bne     TestArus_WWWSErr
         mov     gx,0x007F
         mov     bw,0xFFFF
         addsx   dw,gx,bw
         cmp     dw,0x007E
         bne     TestArus_WWWSErr
         mov     aw,0x007F
         mov     cw,0xFFFF
         subsx   ew,aw,cw
         cmp     ew,0x0080
         bne     TestArus_WWWSErr
         mov     bw,0x007F
         mov     dw,0xFFFF
         andsx   fw,bw,dw
         cmp     fw,0x007F
         bne     TestArus_WWWSErr
         mov     cw,0x007F
         mov     ew,0xFFFF
         orsx    gw,cw,ew
         cmp     gw,0xFFFF
         bne     TestArus_WWWSErr
         mov     dw,0x007F
         mov     fw,0xFFFF
         xorsx   ax,dw,fw
         cmp     ax,0xFF80
         bne     TestArus_WWWSErr
         mov     ew,0x007F
         mov     gw,0xFFFF
         mulsx   bx,ew,gw
         cmp     bx,0xFF81
         bne     TestArus_WWWSErr
         mov     fw,0x007F
         mov     ax,0xFFFF
         sdivsx  cx,fw,ax
         cmp     cx,0xFF81
         bne     TestArus_WWWSErr
         mov     gw,0x007F
         mov     bx,0xFFFF
         sremsx  dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWSErr
         mov     ax,0x0080
         mov     cx,0x0080
         addsx   ex,ax,cx
         cmp     ex,0x0100
         bne     TestArus_WWWSErr
         mov     bx,0x0080
         mov     dx,0x0080
         subsx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x0080
         mov     ex,0x0080
         andsx   gx,cx,ex
         cmp     gx,0x0080
         bne     TestArus_WWWSErr
         mov     dx,0x0080
         mov     fx,0x0080
         orsx    aw,dx,fx
         cmp     aw,0x0080
         bne     TestArus_WWWSErr
         mov     ex,0x0080
         mov     gx,0x0080
         xorsx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0080
         mov     aw,0x0080
         mulsx   cw,fx,aw
         cmp     cw,0x4000
         bne     TestArus_WWWSErr
         mov     gx,0x0080
         mov     bw,0x0080
         sdivsx  dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWSErr
         mov     aw,0x0080
         mov     cw,0x0080
         sremsx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWSErr
         mov     bw,0x0080
         mov     dw,0x7FFF
         addsx   fw,bw,dw
         cmp     fw,0x807F
         bne     TestArus_WWWSErr
         mov     cw,0x0080
         mov     ew,0x7FFF
         subsx   gw,cw,ew
         cmp     gw,0x8081
         bne     TestArus_WWWSErr
         mov     dw,0x0080
         mov     fw,0x7FFF
         andsx   ax,dw,fw
         cmp     ax,0x0080
         bne     TestArus_WWWSErr
         mov     ew,0x0080
         mov     gw,0x7FFF
         orsx    bx,ew,gw
         cmp     bx,0x7FFF
         bne     TestArus_WWWSErr
         mov     fw,0x0080
         mov     ax,0x7FFF
         xorsx   cx,fw,ax
         cmp     cx,0x7F7F
         bne     TestArus_WWWSErr
         mov     gw,0x0080
         mov     bx,0x7FFF
         mulsx   dx,gw,bx
         cmp     dx,0xFF80
         bne     TestArus_WWWSErr
         mov     ax,0x0080
         mov     cx,0x7FFF
         sdivsx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x0080
         mov     dx,0x7FFF
         sremsx  fx,bx,dx
         cmp     fx,0x0080
         bne     TestArus_WWWSErr
         mov     cx,0x0080
         mov     ex,0x8000
         addsx   gx,cx,ex
         cmp     gx,0x8080
         bne     TestArus_WWWSErr
         mov     dx,0x0080
         mov     fx,0x8000
         subsx   aw,dx,fx
         cmp     aw,0x8080
         bne     TestArus_WWWSErr
         mov     ex,0x0080
         mov     gx,0x8000
         andsx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x0080
         mov     aw,0x8000
         orsx    cw,fx,aw
         cmp     cw,0x8080
         bne     TestArus_WWWSErr
         mov     gx,0x0080
         mov     bw,0x8000
         xorsx   dw,gx,bw
         cmp     dw,0x8080
         bne     TestArus_WWWSErr
         mov     aw,0x0080
         mov     cw,0x8000
         mulsx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWSErr
         mov     bw,0x0080
         mov     dw,0x8000
         sdivsx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWSErr
         mov     cw,0x0080
         mov     ew,0x8000
         sremsx  gw,cw,ew
         cmp     gw,0x0080
         bne     TestArus_WWWSErr
         mov     dw,0x0080
         mov     fw,0xFFFF
         addsx   ax,dw,fw
         cmp     ax,0x007F
         bne     TestArus_WWWSErr
         mov     ew,0x0080
         mov     gw,0xFFFF
         subsx   bx,ew,gw
         cmp     bx,0x0081
         bne     TestArus_WWWSErr
         mov     fw,0x0080
         mov     ax,0xFFFF
         andsx   cx,fw,ax
         cmp     cx,0x0080
         bne     TestArus_WWWSErr
         mov     gw,0x0080
         mov     bx,0xFFFF
         orsx    dx,gw,bx
         cmp     dx,0xFFFF
         bne     TestArus_WWWSErr
         mov     ax,0x0080
         mov     cx,0xFFFF
         xorsx   ex,ax,cx
         cmp     ex,0xFF7F
         bne     TestArus_WWWSErr
         mov     bx,0x0080
         mov     dx,0xFFFF
         mulsx   fx,bx,dx
         cmp     fx,0xFF80
         bne     TestArus_WWWSErr
         mov     cx,0x0080
         mov     ex,0xFFFF
         sdivsx  gx,cx,ex
         cmp     gx,0xFF80
         bne     TestArus_WWWSErr
         mov     dx,0x0080
         mov     fx,0xFFFF
         sremsx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0x7FFF
         mov     gx,0x7FFF
         addsx   bw,ex,gx
         cmp     bw,0xFFFE
         bne     TestArus_WWWSErr
         mov     fx,0x7FFF
         mov     aw,0x7FFF
         subsx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWSErr
         mov     gx,0x7FFF
         mov     bw,0x7FFF
         andsx   dw,gx,bw
         cmp     dw,0x7FFF
         bne     TestArus_WWWSErr
         mov     aw,0x7FFF
         mov     cw,0x7FFF
         orsx    ew,aw,cw
         cmp     ew,0x7FFF
         bne     TestArus_WWWSErr
         mov     bw,0x7FFF
         mov     dw,0x7FFF
         xorsx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWSErr
         mov     cw,0x7FFF
         mov     ew,0x7FFF
         mulsx   gw,cw,ew
         cmp     gw,0x0001
         bne     TestArus_WWWSErr
         mov     dw,0x7FFF
         mov     fw,0x7FFF
         sdivsx  ax,dw,fw
         cmp     ax,0x0001
         bne     TestArus_WWWSErr
         mov     ew,0x7FFF
         mov     gw,0x7FFF
         sremsx  bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWSErr
         mov     fw,0x7FFF
         mov     ax,0x8000
         addsx   cx,fw,ax
         cmp     cx,0xFFFF
         bne     TestArus_WWWSErr
         mov     gw,0x7FFF
         mov     bx,0x8000
         subsx   dx,gw,bx
         cmp     dx,0xFFFF
         bne     TestArus_WWWSErr
         mov     ax,0x7FFF
         mov     cx,0x8000
         andsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x7FFF
         mov     dx,0x8000
         orsx    fx,bx,dx
         cmp     fx,0xFFFF
         bne     TestArus_WWWSErr
         mov     cx,0x7FFF
         mov     ex,0x8000
         xorsx   gx,cx,ex
         cmp     gx,0xFFFF
         bne     TestArus_WWWSErr
         mov     dx,0x7FFF
         mov     fx,0x8000
         mulsx   aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWSErr
         mov     ex,0x7FFF
         mov     gx,0x8000
         sdivsx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x7FFF
         mov     aw,0x8000
         sremsx  cw,fx,aw
         cmp     cw,0x7FFF
         bne     TestArus_WWWSErr
         mov     gx,0x7FFF
         mov     bw,0xFFFF
         addsx   dw,gx,bw
         cmp     dw,0x7FFE
         bne     TestArus_WWWSErr
         mov     aw,0x7FFF
         mov     cw,0xFFFF
         subsx   ew,aw,cw
         cmp     ew,0x8000
         bne     TestArus_WWWSErr
         mov     bw,0x7FFF
         mov     dw,0xFFFF
         andsx   fw,bw,dw
         cmp     fw,0x7FFF
         bne     TestArus_WWWSErr
         mov     cw,0x7FFF
         mov     ew,0xFFFF
         orsx    gw,cw,ew
         cmp     gw,0xFFFF
         bne     TestArus_WWWSErr
         mov     dw,0x7FFF
         mov     fw,0xFFFF
         xorsx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWSErr
         mov     ew,0x7FFF
         mov     gw,0xFFFF
         mulsx   bx,ew,gw
         cmp     bx,0x8001
         bne     TestArus_WWWSErr
         mov     fw,0x7FFF
         mov     ax,0xFFFF
         sdivsx  cx,fw,ax
         cmp     cx,0x8001
         bne     TestArus_WWWSErr
         mov     gw,0x7FFF
         mov     bx,0xFFFF
         sremsx  dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWSErr
         mov     ax,0x8000
         mov     cx,0x8000
         addsx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWSErr
         mov     bx,0x8000
         mov     dx,0x8000
         subsx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0x8000
         mov     ex,0x8000
         andsx   gx,cx,ex
         cmp     gx,0x8000
         bne     TestArus_WWWSErr
         mov     dx,0x8000
         mov     fx,0x8000
         orsx    aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWSErr
         mov     ex,0x8000
         mov     gx,0x8000
         xorsx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWSErr
         mov     fx,0x8000
         mov     aw,0x8000
         mulsx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWSErr
         mov     gx,0x8000
         mov     bw,0x8000
         sdivsx  dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWSErr
         mov     aw,0x8000
         mov     cw,0x8000
         sremsx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWSErr
         mov     bw,0x8000
         mov     dw,0xFFFF
         addsx   fw,bw,dw
         cmp     fw,0x7FFF
         bne     TestArus_WWWSErr
         mov     cw,0x8000
         mov     ew,0xFFFF
         subsx   gw,cw,ew
         cmp     gw,0x8001
         bne     TestArus_WWWSErr
         mov     dw,0x8000
         mov     fw,0xFFFF
         andsx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWSErr
         mov     ew,0x8000
         mov     gw,0xFFFF
         orsx    bx,ew,gw
         cmp     bx,0xFFFF
         bne     TestArus_WWWSErr
         mov     fw,0x8000
         mov     ax,0xFFFF
         xorsx   cx,fw,ax
         cmp     cx,0x7FFF
         bne     TestArus_WWWSErr
         mov     gw,0x8000
         mov     bx,0xFFFF
         mulsx   dx,gw,bx
         cmp     dx,0x8000
         bne     TestArus_WWWSErr
         mov     ax,0x8000
         mov     cx,0xFFFF
         sdivsx  ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWSErr
         mov     bx,0x8000
         mov     dx,0xFFFF
         sremsx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWSErr
         mov     cx,0xFFFF
         mov     ex,0xFFFF
         addsx   gx,cx,ex
         cmp     gx,0xFFFE
         bne     TestArus_WWWSErr
         mov     dx,0xFFFF
         mov     fx,0xFFFF
         subsx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWSErr
         mov     ex,0xFFFF
         mov     gx,0xFFFF
         andsx   bw,ex,gx
         cmp     bw,0xFFFF
         bne     TestArus_WWWSErr
         mov     fx,0xFFFF
         mov     aw,0xFFFF
         orsx    cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWSErr
         mov     gx,0xFFFF
         mov     bw,0xFFFF
         xorsx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWSErr
         mov     aw,0xFFFF
         mov     cw,0xFFFF
         mulsx   ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWSErr
         mov     bw,0xFFFF
         mov     dw,0xFFFF
         sdivsx  fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWSErr
         mov     cw,0xFFFF
         mov     ew,0xFFFF
         sremsx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWSErr
         bra     TestArus_WWWSRet
TestArus_WWWSErr:
         nop     
         trap    
         nop     
TestArus_WWWSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
