.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_BDWS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_BDWS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     awx,0x00000000
         mov     cx,0x0000
         addsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000000
         mov     dx,0x0000
         subsx   fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00000000
         mov     ex,0x0000
         andsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00000000
         mov     fx,0x0000
         orsx    ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000000
         mov     gx,0x0000
         xorsx   bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000000
         mov     aw,0x0000
         mulsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00000000
         mov     bw,0x0000
         sdivsx  dh,gwx,bw
         cmp     dh,0xFF
         bne     TestArus_BDWSErr
         mov     ar,0x00000000
         mov     cw,0x0000
         sremsx  eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x00000000
         mov     dw,0x0001
         addsx   fh,br,dw
         cmp     fh,0x01
         bne     TestArus_BDWSErr
         mov     cr,0x00000000
         mov     ew,0x0001
         subsx   gh,cr,ew
         cmp     gh,0xFF
         bne     TestArus_BDWSErr
         mov     dr,0x00000000
         mov     fw,0x0001
         andsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000000
         mov     gw,0x0001
         orsx    bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x00000000
         mov     ax,0x0001
         xorsx   cl,fr,ax
         cmp     cl,0x01
         bne     TestArus_BDWSErr
         mov     gr,0x00000000
         mov     bx,0x0001
         mulsx   dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00000000
         mov     cx,0x0001
         sdivsx  el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000000
         mov     dx,0x0001
         sremsx  fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00000000
         mov     ex,0x0008
         addsx   gl,cwx,ex
         cmp     gl,0x08
         bne     TestArus_BDWSErr
         mov     dwx,0x00000000
         mov     fx,0x0008
         subsx   ah,dwx,fx
         cmp     ah,0xF8
         bne     TestArus_BDWSErr
         mov     ewx,0x00000000
         mov     gx,0x0008
         andsx   bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000000
         mov     aw,0x0008
         orsx    ch,fwx,aw
         cmp     ch,0x08
         bne     TestArus_BDWSErr
         mov     gwx,0x00000000
         mov     bw,0x0008
         xorsx   dh,gwx,bw
         cmp     dh,0x08
         bne     TestArus_BDWSErr
         mov     ar,0x00000000
         mov     cw,0x0008
         mulsx   eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x00000000
         mov     dw,0x0008
         sdivsx  fh,br,dw
         cmp     fh,0x00
         bne     TestArus_BDWSErr
         mov     cr,0x00000000
         mov     ew,0x0008
         sremsx  gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         mov     dr,0x00000000
         mov     fw,0x0009
         addsx   al,dr,fw
         cmp     al,0x09
         bne     TestArus_BDWSErr
         mov     er,0x00000000
         mov     gw,0x0009
         subsx   bl,er,gw
         cmp     bl,0xF7
         bne     TestArus_BDWSErr
         mov     fr,0x00000000
         mov     ax,0x0009
         andsx   cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00000000
         mov     bx,0x0009
         orsx    dl,gr,bx
         cmp     dl,0x09
         bne     TestArus_BDWSErr
         mov     awx,0x00000000
         mov     cx,0x0009
         xorsx   el,awx,cx
         cmp     el,0x09
         bne     TestArus_BDWSErr
         mov     bwx,0x00000000
         mov     dx,0x0009
         mulsx   fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00000000
         mov     ex,0x0009
         sdivsx  gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00000000
         mov     fx,0x0009
         sremsx  ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000000
         mov     gx,0x007F
         addsx   bh,ewx,gx
         cmp     bh,0x7F
         bne     TestArus_BDWSErr
         mov     fwx,0x00000000
         mov     aw,0x007F
         subsx   ch,fwx,aw
         cmp     ch,0x81
         bne     TestArus_BDWSErr
         mov     gwx,0x00000000
         mov     bw,0x007F
         andsx   dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00000000
         mov     cw,0x007F
         orsx    eh,ar,cw
         cmp     eh,0x7F
         bne     TestArus_BDWSErr
         mov     br,0x00000000
         mov     dw,0x007F
         xorsx   fh,br,dw
         cmp     fh,0x7F
         bne     TestArus_BDWSErr
         mov     cr,0x00000000
         mov     ew,0x007F
         mulsx   gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         mov     dr,0x00000000
         mov     fw,0x007F
         sdivsx  al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000000
         mov     gw,0x007F
         sremsx  bl,er,gw
         cmp     bl,0x00
         bne     TestArus_BDWSErr
         mov     fr,0x00000000
         mov     ax,0x0080
         addsx   cl,fr,ax
         cmp     cl,0x80
         bne     TestArus_BDWSErr
         mov     gr,0x00000000
         mov     bx,0x0080
         subsx   dl,gr,bx
         cmp     dl,0x80
         bne     TestArus_BDWSErr
         mov     awx,0x00000000
         mov     cx,0x0080
         andsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000000
         mov     dx,0x0080
         orsx    fl,bwx,dx
         cmp     fl,0x80
         bne     TestArus_BDWSErr
         mov     cwx,0x00000000
         mov     ex,0x0080
         xorsx   gl,cwx,ex
         cmp     gl,0x80
         bne     TestArus_BDWSErr
         mov     dwx,0x00000000
         mov     fx,0x0080
         mulsx   ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000000
         mov     gx,0x0080
         sdivsx  bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000000
         mov     aw,0x0080
         sremsx  ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00000000
         mov     bw,0x7FFF
         addsx   dh,gwx,bw
         cmp     dh,0xFF
         bne     TestArus_BDWSErr
         mov     ar,0x00000000
         mov     cw,0x7FFF
         subsx   eh,ar,cw
         cmp     eh,0x01
         bne     TestArus_BDWSErr
         mov     br,0x00000000
         mov     dw,0x7FFF
         andsx   fh,br,dw
         cmp     fh,0x00
         bne     TestArus_BDWSErr
         mov     cr,0x00000000
         mov     ew,0x7FFF
         orsx    gh,cr,ew
         cmp     gh,0xFF
         bne     TestArus_BDWSErr
         mov     dr,0x00000000
         mov     fw,0x7FFF
         xorsx   al,dr,fw
         cmp     al,0xFF
         bne     TestArus_BDWSErr
         mov     er,0x00000000
         mov     gw,0x7FFF
         mulsx   bl,er,gw
         cmp     bl,0x00
         bne     TestArus_BDWSErr
         mov     fr,0x00000000
         mov     ax,0x7FFF
         sdivsx  cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00000000
         mov     bx,0x7FFF
         sremsx  dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00000000
         mov     cx,0x8000
         addsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000000
         mov     dx,0x8000
         subsx   fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00000000
         mov     ex,0x8000
         andsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00000000
         mov     fx,0x8000
         orsx    ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000000
         mov     gx,0x8000
         xorsx   bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000000
         mov     aw,0x8000
         mulsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00000000
         mov     bw,0x8000
         sdivsx  dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00000000
         mov     cw,0x8000
         sremsx  eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x00000000
         mov     dw,0xFFFF
         addsx   fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x00000000
         mov     ew,0xFFFF
         subsx   gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x00000000
         mov     fw,0xFFFF
         andsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000000
         mov     gw,0xFFFF
         orsx    bl,er,gw
         cmp     bl,0xFF
         bne     TestArus_BDWSErr
         mov     fr,0x00000000
         mov     ax,0xFFFF
         xorsx   cl,fr,ax
         cmp     cl,0xFF
         bne     TestArus_BDWSErr
         mov     gr,0x00000000
         mov     bx,0xFFFF
         mulsx   dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00000000
         mov     cx,0xFFFF
         sdivsx  el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000000
         mov     dx,0xFFFF
         sremsx  fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00000001
         mov     ex,0x0001
         addsx   gl,cwx,ex
         cmp     gl,0x02
         bne     TestArus_BDWSErr
         mov     dwx,0x00000001
         mov     fx,0x0001
         subsx   ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000001
         mov     gx,0x0001
         andsx   bh,ewx,gx
         cmp     bh,0x01
         bne     TestArus_BDWSErr
         mov     fwx,0x00000001
         mov     aw,0x0001
         orsx    ch,fwx,aw
         cmp     ch,0x01
         bne     TestArus_BDWSErr
         mov     gwx,0x00000001
         mov     bw,0x0001
         xorsx   dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00000001
         mov     cw,0x0001
         mulsx   eh,ar,cw
         cmp     eh,0x01
         bne     TestArus_BDWSErr
         mov     br,0x00000001
         mov     dw,0x0001
         sdivsx  fh,br,dw
         cmp     fh,0x01
         bne     TestArus_BDWSErr
         mov     cr,0x00000001
         mov     ew,0x0001
         sremsx  gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         mov     dr,0x00000001
         mov     fw,0x0008
         addsx   al,dr,fw
         cmp     al,0x09
         bne     TestArus_BDWSErr
         mov     er,0x00000001
         mov     gw,0x0008
         subsx   bl,er,gw
         cmp     bl,0xF9
         bne     TestArus_BDWSErr
         mov     fr,0x00000001
         mov     ax,0x0008
         andsx   cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00000001
         mov     bx,0x0008
         orsx    dl,gr,bx
         cmp     dl,0x09
         bne     TestArus_BDWSErr
         mov     awx,0x00000001
         mov     cx,0x0008
         xorsx   el,awx,cx
         cmp     el,0x09
         bne     TestArus_BDWSErr
         mov     bwx,0x00000001
         mov     dx,0x0008
         mulsx   fl,bwx,dx
         cmp     fl,0x08
         bne     TestArus_BDWSErr
         mov     cwx,0x00000001
         mov     ex,0x0008
         sdivsx  gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00000001
         mov     fx,0x0008
         sremsx  ah,dwx,fx
         cmp     ah,0x01
         bne     TestArus_BDWSErr
         mov     ewx,0x00000001
         mov     gx,0x0009
         addsx   bh,ewx,gx
         cmp     bh,0x0A
         bne     TestArus_BDWSErr
         mov     fwx,0x00000001
         mov     aw,0x0009
         subsx   ch,fwx,aw
         cmp     ch,0xF8
         bne     TestArus_BDWSErr
         mov     gwx,0x00000001
         mov     bw,0x0009
         andsx   dh,gwx,bw
         cmp     dh,0x01
         bne     TestArus_BDWSErr
         mov     ar,0x00000001
         mov     cw,0x0009
         orsx    eh,ar,cw
         cmp     eh,0x09
         bne     TestArus_BDWSErr
         mov     br,0x00000001
         mov     dw,0x0009
         xorsx   fh,br,dw
         cmp     fh,0x08
         bne     TestArus_BDWSErr
         mov     cr,0x00000001
         mov     ew,0x0009
         mulsx   gh,cr,ew
         cmp     gh,0x09
         bne     TestArus_BDWSErr
         mov     dr,0x00000001
         mov     fw,0x0009
         sdivsx  al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000001
         mov     gw,0x0009
         sremsx  bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x00000001
         mov     ax,0x007F
         addsx   cl,fr,ax
         cmp     cl,0x80
         bne     TestArus_BDWSErr
         mov     gr,0x00000001
         mov     bx,0x007F
         subsx   dl,gr,bx
         cmp     dl,0x82
         bne     TestArus_BDWSErr
         mov     awx,0x00000001
         mov     cx,0x007F
         andsx   el,awx,cx
         cmp     el,0x01
         bne     TestArus_BDWSErr
         mov     bwx,0x00000001
         mov     dx,0x007F
         orsx    fl,bwx,dx
         cmp     fl,0x7F
         bne     TestArus_BDWSErr
         mov     cwx,0x00000001
         mov     ex,0x007F
         xorsx   gl,cwx,ex
         cmp     gl,0x7E
         bne     TestArus_BDWSErr
         mov     dwx,0x00000001
         mov     fx,0x007F
         mulsx   ah,dwx,fx
         cmp     ah,0x7F
         bne     TestArus_BDWSErr
         mov     ewx,0x00000001
         mov     gx,0x007F
         sdivsx  bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000001
         mov     aw,0x007F
         sremsx  ch,fwx,aw
         cmp     ch,0x01
         bne     TestArus_BDWSErr
         mov     gwx,0x00000001
         mov     bw,0x0080
         addsx   dh,gwx,bw
         cmp     dh,0x81
         bne     TestArus_BDWSErr
         mov     ar,0x00000001
         mov     cw,0x0080
         subsx   eh,ar,cw
         cmp     eh,0x81
         bne     TestArus_BDWSErr
         mov     br,0x00000001
         mov     dw,0x0080
         andsx   fh,br,dw
         cmp     fh,0x00
         bne     TestArus_BDWSErr
         mov     cr,0x00000001
         mov     ew,0x0080
         orsx    gh,cr,ew
         cmp     gh,0x81
         bne     TestArus_BDWSErr
         mov     dr,0x00000001
         mov     fw,0x0080
         xorsx   al,dr,fw
         cmp     al,0x81
         bne     TestArus_BDWSErr
         mov     er,0x00000001
         mov     gw,0x0080
         mulsx   bl,er,gw
         cmp     bl,0x80
         bne     TestArus_BDWSErr
         mov     fr,0x00000001
         mov     ax,0x0080
         sdivsx  cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00000001
         mov     bx,0x0080
         sremsx  dl,gr,bx
         cmp     dl,0x01
         bne     TestArus_BDWSErr
         mov     awx,0x00000001
         mov     cx,0x7FFF
         addsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000001
         mov     dx,0x7FFF
         subsx   fl,bwx,dx
         cmp     fl,0x02
         bne     TestArus_BDWSErr
         mov     cwx,0x00000001
         mov     ex,0x7FFF
         andsx   gl,cwx,ex
         cmp     gl,0x01
         bne     TestArus_BDWSErr
         mov     dwx,0x00000001
         mov     fx,0x7FFF
         orsx    ah,dwx,fx
         cmp     ah,0xFF
         bne     TestArus_BDWSErr
         mov     ewx,0x00000001
         mov     gx,0x7FFF
         xorsx   bh,ewx,gx
         cmp     bh,0xFE
         bne     TestArus_BDWSErr
         mov     fwx,0x00000001
         mov     aw,0x7FFF
         mulsx   ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x00000001
         mov     bw,0x7FFF
         sdivsx  dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00000001
         mov     cw,0x7FFF
         sremsx  eh,ar,cw
         cmp     eh,0x01
         bne     TestArus_BDWSErr
         mov     br,0x00000001
         mov     dw,0x8000
         addsx   fh,br,dw
         cmp     fh,0x01
         bne     TestArus_BDWSErr
         mov     cr,0x00000001
         mov     ew,0x8000
         subsx   gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x00000001
         mov     fw,0x8000
         andsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000001
         mov     gw,0x8000
         orsx    bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x00000001
         mov     ax,0x8000
         xorsx   cl,fr,ax
         cmp     cl,0x01
         bne     TestArus_BDWSErr
         mov     gr,0x00000001
         mov     bx,0x8000
         mulsx   dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00000001
         mov     cx,0x8000
         sdivsx  el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000001
         mov     dx,0x8000
         sremsx  fl,bwx,dx
         cmp     fl,0x01
         bne     TestArus_BDWSErr
         mov     cwx,0x00000001
         mov     ex,0xFFFF
         addsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00000001
         mov     fx,0xFFFF
         subsx   ah,dwx,fx
         cmp     ah,0x02
         bne     TestArus_BDWSErr
         mov     ewx,0x00000001
         mov     gx,0xFFFF
         andsx   bh,ewx,gx
         cmp     bh,0x01
         bne     TestArus_BDWSErr
         mov     fwx,0x00000001
         mov     aw,0xFFFF
         orsx    ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x00000001
         mov     bw,0xFFFF
         xorsx   dh,gwx,bw
         cmp     dh,0xFE
         bne     TestArus_BDWSErr
         mov     ar,0x00000001
         mov     cw,0xFFFF
         mulsx   eh,ar,cw
         cmp     eh,0xFF
         bne     TestArus_BDWSErr
         mov     br,0x00000001
         mov     dw,0xFFFF
         sdivsx  fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x00000001
         mov     ew,0xFFFF
         sremsx  gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         mov     dr,0x00000008
         mov     fw,0x0008
         addsx   al,dr,fw
         cmp     al,0x10
         bne     TestArus_BDWSErr
         mov     er,0x00000008
         mov     gw,0x0008
         subsx   bl,er,gw
         cmp     bl,0x00
         bne     TestArus_BDWSErr
         mov     fr,0x00000008
         mov     ax,0x0008
         andsx   cl,fr,ax
         cmp     cl,0x08
         bne     TestArus_BDWSErr
         mov     gr,0x00000008
         mov     bx,0x0008
         orsx    dl,gr,bx
         cmp     dl,0x08
         bne     TestArus_BDWSErr
         mov     awx,0x00000008
         mov     cx,0x0008
         xorsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000008
         mov     dx,0x0008
         mulsx   fl,bwx,dx
         cmp     fl,0x40
         bne     TestArus_BDWSErr
         mov     cwx,0x00000008
         mov     ex,0x0008
         sdivsx  gl,cwx,ex
         cmp     gl,0x01
         bne     TestArus_BDWSErr
         mov     dwx,0x00000008
         mov     fx,0x0008
         sremsx  ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000008
         mov     gx,0x0009
         addsx   bh,ewx,gx
         cmp     bh,0x11
         bne     TestArus_BDWSErr
         mov     fwx,0x00000008
         mov     aw,0x0009
         subsx   ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x00000008
         mov     bw,0x0009
         andsx   dh,gwx,bw
         cmp     dh,0x08
         bne     TestArus_BDWSErr
         mov     ar,0x00000008
         mov     cw,0x0009
         orsx    eh,ar,cw
         cmp     eh,0x09
         bne     TestArus_BDWSErr
         mov     br,0x00000008
         mov     dw,0x0009
         xorsx   fh,br,dw
         cmp     fh,0x01
         bne     TestArus_BDWSErr
         mov     cr,0x00000008
         mov     ew,0x0009
         mulsx   gh,cr,ew
         cmp     gh,0x48
         bne     TestArus_BDWSErr
         mov     dr,0x00000008
         mov     fw,0x0009
         sdivsx  al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000008
         mov     gw,0x0009
         sremsx  bl,er,gw
         cmp     bl,0x08
         bne     TestArus_BDWSErr
         mov     fr,0x00000008
         mov     ax,0x007F
         addsx   cl,fr,ax
         cmp     cl,0x87
         bne     TestArus_BDWSErr
         mov     gr,0x00000008
         mov     bx,0x007F
         subsx   dl,gr,bx
         cmp     dl,0x89
         bne     TestArus_BDWSErr
         mov     awx,0x00000008
         mov     cx,0x007F
         andsx   el,awx,cx
         cmp     el,0x08
         bne     TestArus_BDWSErr
         mov     bwx,0x00000008
         mov     dx,0x007F
         orsx    fl,bwx,dx
         cmp     fl,0x7F
         bne     TestArus_BDWSErr
         mov     cwx,0x00000008
         mov     ex,0x007F
         xorsx   gl,cwx,ex
         cmp     gl,0x77
         bne     TestArus_BDWSErr
         mov     dwx,0x00000008
         mov     fx,0x007F
         mulsx   ah,dwx,fx
         cmp     ah,0xF8
         bne     TestArus_BDWSErr
         mov     ewx,0x00000008
         mov     gx,0x007F
         sdivsx  bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000008
         mov     aw,0x007F
         sremsx  ch,fwx,aw
         cmp     ch,0x08
         bne     TestArus_BDWSErr
         mov     gwx,0x00000008
         mov     bw,0x0080
         addsx   dh,gwx,bw
         cmp     dh,0x88
         bne     TestArus_BDWSErr
         mov     ar,0x00000008
         mov     cw,0x0080
         subsx   eh,ar,cw
         cmp     eh,0x88
         bne     TestArus_BDWSErr
         mov     br,0x00000008
         mov     dw,0x0080
         andsx   fh,br,dw
         cmp     fh,0x00
         bne     TestArus_BDWSErr
         mov     cr,0x00000008
         mov     ew,0x0080
         orsx    gh,cr,ew
         cmp     gh,0x88
         bne     TestArus_BDWSErr
         mov     dr,0x00000008
         mov     fw,0x0080
         xorsx   al,dr,fw
         cmp     al,0x88
         bne     TestArus_BDWSErr
         mov     er,0x00000008
         mov     gw,0x0080
         mulsx   bl,er,gw
         cmp     bl,0x00
         bne     TestArus_BDWSErr
         mov     fr,0x00000008
         mov     ax,0x0080
         sdivsx  cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00000008
         mov     bx,0x0080
         sremsx  dl,gr,bx
         cmp     dl,0x08
         bne     TestArus_BDWSErr
         mov     awx,0x00000008
         mov     cx,0x7FFF
         addsx   el,awx,cx
         cmp     el,0x07
         bne     TestArus_BDWSErr
         mov     bwx,0x00000008
         mov     dx,0x7FFF
         subsx   fl,bwx,dx
         cmp     fl,0x09
         bne     TestArus_BDWSErr
         mov     cwx,0x00000008
         mov     ex,0x7FFF
         andsx   gl,cwx,ex
         cmp     gl,0x08
         bne     TestArus_BDWSErr
         mov     dwx,0x00000008
         mov     fx,0x7FFF
         orsx    ah,dwx,fx
         cmp     ah,0xFF
         bne     TestArus_BDWSErr
         mov     ewx,0x00000008
         mov     gx,0x7FFF
         xorsx   bh,ewx,gx
         cmp     bh,0xF7
         bne     TestArus_BDWSErr
         mov     fwx,0x00000008
         mov     aw,0x7FFF
         mulsx   ch,fwx,aw
         cmp     ch,0xF8
         bne     TestArus_BDWSErr
         mov     gwx,0x00000008
         mov     bw,0x7FFF
         sdivsx  dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00000008
         mov     cw,0x7FFF
         sremsx  eh,ar,cw
         cmp     eh,0x08
         bne     TestArus_BDWSErr
         mov     br,0x00000008
         mov     dw,0x8000
         addsx   fh,br,dw
         cmp     fh,0x08
         bne     TestArus_BDWSErr
         mov     cr,0x00000008
         mov     ew,0x8000
         subsx   gh,cr,ew
         cmp     gh,0x08
         bne     TestArus_BDWSErr
         mov     dr,0x00000008
         mov     fw,0x8000
         andsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000008
         mov     gw,0x8000
         orsx    bl,er,gw
         cmp     bl,0x08
         bne     TestArus_BDWSErr
         mov     fr,0x00000008
         mov     ax,0x8000
         xorsx   cl,fr,ax
         cmp     cl,0x08
         bne     TestArus_BDWSErr
         mov     gr,0x00000008
         mov     bx,0x8000
         mulsx   dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00000008
         mov     cx,0x8000
         sdivsx  el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000008
         mov     dx,0x8000
         sremsx  fl,bwx,dx
         cmp     fl,0x08
         bne     TestArus_BDWSErr
         mov     cwx,0x00000008
         mov     ex,0xFFFF
         addsx   gl,cwx,ex
         cmp     gl,0x07
         bne     TestArus_BDWSErr
         mov     dwx,0x00000008
         mov     fx,0xFFFF
         subsx   ah,dwx,fx
         cmp     ah,0x09
         bne     TestArus_BDWSErr
         mov     ewx,0x00000008
         mov     gx,0xFFFF
         andsx   bh,ewx,gx
         cmp     bh,0x08
         bne     TestArus_BDWSErr
         mov     fwx,0x00000008
         mov     aw,0xFFFF
         orsx    ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x00000008
         mov     bw,0xFFFF
         xorsx   dh,gwx,bw
         cmp     dh,0xF7
         bne     TestArus_BDWSErr
         mov     ar,0x00000008
         mov     cw,0xFFFF
         mulsx   eh,ar,cw
         cmp     eh,0xF8
         bne     TestArus_BDWSErr
         mov     br,0x00000008
         mov     dw,0xFFFF
         sdivsx  fh,br,dw
         cmp     fh,0xF8
         bne     TestArus_BDWSErr
         mov     cr,0x00000008
         mov     ew,0xFFFF
         sremsx  gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         mov     dr,0x00000009
         mov     fw,0x0009
         addsx   al,dr,fw
         cmp     al,0x12
         bne     TestArus_BDWSErr
         mov     er,0x00000009
         mov     gw,0x0009
         subsx   bl,er,gw
         cmp     bl,0x00
         bne     TestArus_BDWSErr
         mov     fr,0x00000009
         mov     ax,0x0009
         andsx   cl,fr,ax
         cmp     cl,0x09
         bne     TestArus_BDWSErr
         mov     gr,0x00000009
         mov     bx,0x0009
         orsx    dl,gr,bx
         cmp     dl,0x09
         bne     TestArus_BDWSErr
         mov     awx,0x00000009
         mov     cx,0x0009
         xorsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000009
         mov     dx,0x0009
         mulsx   fl,bwx,dx
         cmp     fl,0x51
         bne     TestArus_BDWSErr
         mov     cwx,0x00000009
         mov     ex,0x0009
         sdivsx  gl,cwx,ex
         cmp     gl,0x01
         bne     TestArus_BDWSErr
         mov     dwx,0x00000009
         mov     fx,0x0009
         sremsx  ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00000009
         mov     gx,0x007F
         addsx   bh,ewx,gx
         cmp     bh,0x88
         bne     TestArus_BDWSErr
         mov     fwx,0x00000009
         mov     aw,0x007F
         subsx   ch,fwx,aw
         cmp     ch,0x8A
         bne     TestArus_BDWSErr
         mov     gwx,0x00000009
         mov     bw,0x007F
         andsx   dh,gwx,bw
         cmp     dh,0x09
         bne     TestArus_BDWSErr
         mov     ar,0x00000009
         mov     cw,0x007F
         orsx    eh,ar,cw
         cmp     eh,0x7F
         bne     TestArus_BDWSErr
         mov     br,0x00000009
         mov     dw,0x007F
         xorsx   fh,br,dw
         cmp     fh,0x76
         bne     TestArus_BDWSErr
         mov     cr,0x00000009
         mov     ew,0x007F
         mulsx   gh,cr,ew
         cmp     gh,0x77
         bne     TestArus_BDWSErr
         mov     dr,0x00000009
         mov     fw,0x007F
         sdivsx  al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00000009
         mov     gw,0x007F
         sremsx  bl,er,gw
         cmp     bl,0x09
         bne     TestArus_BDWSErr
         mov     fr,0x00000009
         mov     ax,0x0080
         addsx   cl,fr,ax
         cmp     cl,0x89
         bne     TestArus_BDWSErr
         mov     gr,0x00000009
         mov     bx,0x0080
         subsx   dl,gr,bx
         cmp     dl,0x89
         bne     TestArus_BDWSErr
         mov     awx,0x00000009
         mov     cx,0x0080
         andsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00000009
         mov     dx,0x0080
         orsx    fl,bwx,dx
         cmp     fl,0x89
         bne     TestArus_BDWSErr
         mov     cwx,0x00000009
         mov     ex,0x0080
         xorsx   gl,cwx,ex
         cmp     gl,0x89
         bne     TestArus_BDWSErr
         mov     dwx,0x00000009
         mov     fx,0x0080
         mulsx   ah,dwx,fx
         cmp     ah,0x80
         bne     TestArus_BDWSErr
         mov     ewx,0x00000009
         mov     gx,0x0080
         sdivsx  bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00000009
         mov     aw,0x0080
         sremsx  ch,fwx,aw
         cmp     ch,0x09
         bne     TestArus_BDWSErr
         mov     gwx,0x00000009
         mov     bw,0x7FFF
         addsx   dh,gwx,bw
         cmp     dh,0x08
         bne     TestArus_BDWSErr
         mov     ar,0x00000009
         mov     cw,0x7FFF
         subsx   eh,ar,cw
         cmp     eh,0x0A
         bne     TestArus_BDWSErr
         mov     br,0x00000009
         mov     dw,0x7FFF
         andsx   fh,br,dw
         cmp     fh,0x09
         bne     TestArus_BDWSErr
         mov     cr,0x00000009
         mov     ew,0x7FFF
         orsx    gh,cr,ew
         cmp     gh,0xFF
         bne     TestArus_BDWSErr
         mov     dr,0x00000009
         mov     fw,0x7FFF
         xorsx   al,dr,fw
         cmp     al,0xF6
         bne     TestArus_BDWSErr
         mov     er,0x00000009
         mov     gw,0x7FFF
         mulsx   bl,er,gw
         cmp     bl,0xF7
         bne     TestArus_BDWSErr
         mov     fr,0x00000009
         mov     ax,0x7FFF
         sdivsx  cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00000009
         mov     bx,0x7FFF
         sremsx  dl,gr,bx
         cmp     dl,0x09
         bne     TestArus_BDWSErr
         mov     awx,0x00000009
         mov     cx,0x8000
         addsx   el,awx,cx
         cmp     el,0x09
         bne     TestArus_BDWSErr
         mov     bwx,0x00000009
         mov     dx,0x8000
         subsx   fl,bwx,dx
         cmp     fl,0x09
         bne     TestArus_BDWSErr
         mov     cwx,0x00000009
         mov     ex,0x8000
         andsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00000009
         mov     fx,0x8000
         orsx    ah,dwx,fx
         cmp     ah,0x09
         bne     TestArus_BDWSErr
         mov     ewx,0x00000009
         mov     gx,0x8000
         xorsx   bh,ewx,gx
         cmp     bh,0x09
         bne     TestArus_BDWSErr
         mov     fwx,0x00000009
         mov     aw,0x8000
         mulsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00000009
         mov     bw,0x8000
         sdivsx  dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00000009
         mov     cw,0x8000
         sremsx  eh,ar,cw
         cmp     eh,0x09
         bne     TestArus_BDWSErr
         mov     br,0x00000009
         mov     dw,0xFFFF
         addsx   fh,br,dw
         cmp     fh,0x08
         bne     TestArus_BDWSErr
         mov     cr,0x00000009
         mov     ew,0xFFFF
         subsx   gh,cr,ew
         cmp     gh,0x0A
         bne     TestArus_BDWSErr
         mov     dr,0x00000009
         mov     fw,0xFFFF
         andsx   al,dr,fw
         cmp     al,0x09
         bne     TestArus_BDWSErr
         mov     er,0x00000009
         mov     gw,0xFFFF
         orsx    bl,er,gw
         cmp     bl,0xFF
         bne     TestArus_BDWSErr
         mov     fr,0x00000009
         mov     ax,0xFFFF
         xorsx   cl,fr,ax
         cmp     cl,0xF6
         bne     TestArus_BDWSErr
         mov     gr,0x00000009
         mov     bx,0xFFFF
         mulsx   dl,gr,bx
         cmp     dl,0xF7
         bne     TestArus_BDWSErr
         mov     awx,0x00000009
         mov     cx,0xFFFF
         sdivsx  el,awx,cx
         cmp     el,0xF7
         bne     TestArus_BDWSErr
         mov     bwx,0x00000009
         mov     dx,0xFFFF
         sremsx  fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00007FFF
         mov     ex,0x007F
         addsx   gl,cwx,ex
         cmp     gl,0x7E
         bne     TestArus_BDWSErr
         mov     dwx,0x00007FFF
         mov     fx,0x007F
         subsx   ah,dwx,fx
         cmp     ah,0x80
         bne     TestArus_BDWSErr
         mov     ewx,0x00007FFF
         mov     gx,0x007F
         andsx   bh,ewx,gx
         cmp     bh,0x7F
         bne     TestArus_BDWSErr
         mov     fwx,0x00007FFF
         mov     aw,0x007F
         orsx    ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x00007FFF
         mov     bw,0x007F
         xorsx   dh,gwx,bw
         cmp     dh,0x80
         bne     TestArus_BDWSErr
         mov     ar,0x00007FFF
         mov     cw,0x007F
         mulsx   eh,ar,cw
         cmp     eh,0x81
         bne     TestArus_BDWSErr
         mov     br,0x00007FFF
         mov     dw,0x007F
         sdivsx  fh,br,dw
         cmp     fh,0x02
         bne     TestArus_BDWSErr
         mov     cr,0x00007FFF
         mov     ew,0x007F
         sremsx  gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x00007FFF
         mov     fw,0x0080
         addsx   al,dr,fw
         cmp     al,0x7F
         bne     TestArus_BDWSErr
         mov     er,0x00007FFF
         mov     gw,0x0080
         subsx   bl,er,gw
         cmp     bl,0x7F
         bne     TestArus_BDWSErr
         mov     fr,0x00007FFF
         mov     ax,0x0080
         andsx   cl,fr,ax
         cmp     cl,0x80
         bne     TestArus_BDWSErr
         mov     gr,0x00007FFF
         mov     bx,0x0080
         orsx    dl,gr,bx
         cmp     dl,0xFF
         bne     TestArus_BDWSErr
         mov     awx,0x00007FFF
         mov     cx,0x0080
         xorsx   el,awx,cx
         cmp     el,0x7F
         bne     TestArus_BDWSErr
         mov     bwx,0x00007FFF
         mov     dx,0x0080
         mulsx   fl,bwx,dx
         cmp     fl,0x80
         bne     TestArus_BDWSErr
         mov     cwx,0x00007FFF
         mov     ex,0x0080
         sdivsx  gl,cwx,ex
         cmp     gl,0xFF
         bne     TestArus_BDWSErr
         mov     dwx,0x00007FFF
         mov     fx,0x0080
         sremsx  ah,dwx,fx
         cmp     ah,0x7F
         bne     TestArus_BDWSErr
         mov     ewx,0x00007FFF
         mov     gx,0x7FFF
         addsx   bh,ewx,gx
         cmp     bh,0xFE
         bne     TestArus_BDWSErr
         mov     fwx,0x00007FFF
         mov     aw,0x7FFF
         subsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00007FFF
         mov     bw,0x7FFF
         andsx   dh,gwx,bw
         cmp     dh,0xFF
         bne     TestArus_BDWSErr
         mov     ar,0x00007FFF
         mov     cw,0x7FFF
         orsx    eh,ar,cw
         cmp     eh,0xFF
         bne     TestArus_BDWSErr
         mov     br,0x00007FFF
         mov     dw,0x7FFF
         xorsx   fh,br,dw
         cmp     fh,0x00
         bne     TestArus_BDWSErr
         mov     cr,0x00007FFF
         mov     ew,0x7FFF
         mulsx   gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x00007FFF
         mov     fw,0x7FFF
         sdivsx  al,dr,fw
         cmp     al,0x01
         bne     TestArus_BDWSErr
         mov     er,0x00007FFF
         mov     gw,0x7FFF
         sremsx  bl,er,gw
         cmp     bl,0x00
         bne     TestArus_BDWSErr
         mov     fr,0x00007FFF
         mov     ax,0x8000
         addsx   cl,fr,ax
         cmp     cl,0xFF
         bne     TestArus_BDWSErr
         mov     gr,0x00007FFF
         mov     bx,0x8000
         subsx   dl,gr,bx
         cmp     dl,0xFF
         bne     TestArus_BDWSErr
         mov     awx,0x00007FFF
         mov     cx,0x8000
         andsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x00007FFF
         mov     dx,0x8000
         orsx    fl,bwx,dx
         cmp     fl,0xFF
         bne     TestArus_BDWSErr
         mov     cwx,0x00007FFF
         mov     ex,0x8000
         xorsx   gl,cwx,ex
         cmp     gl,0xFF
         bne     TestArus_BDWSErr
         mov     dwx,0x00007FFF
         mov     fx,0x8000
         mulsx   ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00007FFF
         mov     gx,0x8000
         sdivsx  bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00007FFF
         mov     aw,0x8000
         sremsx  ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x00007FFF
         mov     bw,0xFFFF
         addsx   dh,gwx,bw
         cmp     dh,0xFE
         bne     TestArus_BDWSErr
         mov     ar,0x00007FFF
         mov     cw,0xFFFF
         subsx   eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x00007FFF
         mov     dw,0xFFFF
         andsx   fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x00007FFF
         mov     ew,0xFFFF
         orsx    gh,cr,ew
         cmp     gh,0xFF
         bne     TestArus_BDWSErr
         mov     dr,0x00007FFF
         mov     fw,0xFFFF
         xorsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00007FFF
         mov     gw,0xFFFF
         mulsx   bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x00007FFF
         mov     ax,0xFFFF
         sdivsx  cl,fr,ax
         cmp     cl,0x01
         bne     TestArus_BDWSErr
         mov     gr,0x00007FFF
         mov     bx,0xFFFF
         sremsx  dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00008000
         mov     cx,0x0080
         addsx   el,awx,cx
         cmp     el,0x80
         bne     TestArus_BDWSErr
         mov     bwx,0x00008000
         mov     dx,0x0080
         subsx   fl,bwx,dx
         cmp     fl,0x80
         bne     TestArus_BDWSErr
         mov     cwx,0x00008000
         mov     ex,0x0080
         andsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00008000
         mov     fx,0x0080
         orsx    ah,dwx,fx
         cmp     ah,0x80
         bne     TestArus_BDWSErr
         mov     ewx,0x00008000
         mov     gx,0x0080
         xorsx   bh,ewx,gx
         cmp     bh,0x80
         bne     TestArus_BDWSErr
         mov     fwx,0x00008000
         mov     aw,0x0080
         mulsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00008000
         mov     bw,0x0080
         sdivsx  dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00008000
         mov     cw,0x0080
         sremsx  eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x00008000
         mov     dw,0x7FFF
         addsx   fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x00008000
         mov     ew,0x7FFF
         subsx   gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x00008000
         mov     fw,0x7FFF
         andsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x00008000
         mov     gw,0x7FFF
         orsx    bl,er,gw
         cmp     bl,0xFF
         bne     TestArus_BDWSErr
         mov     fr,0x00008000
         mov     ax,0x7FFF
         xorsx   cl,fr,ax
         cmp     cl,0xFF
         bne     TestArus_BDWSErr
         mov     gr,0x00008000
         mov     bx,0x7FFF
         mulsx   dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x00008000
         mov     cx,0x7FFF
         sdivsx  el,awx,cx
         cmp     el,0x01
         bne     TestArus_BDWSErr
         mov     bwx,0x00008000
         mov     dx,0x7FFF
         sremsx  fl,bwx,dx
         cmp     fl,0x01
         bne     TestArus_BDWSErr
         mov     cwx,0x00008000
         mov     ex,0x8000
         addsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00008000
         mov     fx,0x8000
         subsx   ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x00008000
         mov     gx,0x8000
         andsx   bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x00008000
         mov     aw,0x8000
         orsx    ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x00008000
         mov     bw,0x8000
         xorsx   dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x00008000
         mov     cw,0x8000
         mulsx   eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x00008000
         mov     dw,0x8000
         sdivsx  fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x00008000
         mov     ew,0x8000
         sremsx  gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         mov     dr,0x00008000
         mov     fw,0xFFFF
         addsx   al,dr,fw
         cmp     al,0xFF
         bne     TestArus_BDWSErr
         mov     er,0x00008000
         mov     gw,0xFFFF
         subsx   bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x00008000
         mov     ax,0xFFFF
         andsx   cl,fr,ax
         cmp     cl,0x00
         bne     TestArus_BDWSErr
         mov     gr,0x00008000
         mov     bx,0xFFFF
         orsx    dl,gr,bx
         cmp     dl,0xFF
         bne     TestArus_BDWSErr
         mov     awx,0x00008000
         mov     cx,0xFFFF
         xorsx   el,awx,cx
         cmp     el,0xFF
         bne     TestArus_BDWSErr
         mov     bwx,0x00008000
         mov     dx,0xFFFF
         mulsx   fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x00008000
         mov     ex,0xFFFF
         sdivsx  gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x00008000
         mov     fx,0xFFFF
         sremsx  ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x7FFFFFFF
         mov     gx,0x7FFF
         addsx   bh,ewx,gx
         cmp     bh,0xFE
         bne     TestArus_BDWSErr
         mov     fwx,0x7FFFFFFF
         mov     aw,0x7FFF
         subsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x7FFFFFFF
         mov     bw,0x7FFF
         andsx   dh,gwx,bw
         cmp     dh,0xFF
         bne     TestArus_BDWSErr
         mov     ar,0x7FFFFFFF
         mov     cw,0x7FFF
         orsx    eh,ar,cw
         cmp     eh,0xFF
         bne     TestArus_BDWSErr
         mov     br,0x7FFFFFFF
         mov     dw,0x7FFF
         xorsx   fh,br,dw
         cmp     fh,0x00
         bne     TestArus_BDWSErr
         mov     cr,0x7FFFFFFF
         mov     ew,0x7FFF
         mulsx   gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x7FFFFFFF
         mov     fw,0x7FFF
         sdivsx  al,dr,fw
         cmp     al,0x02
         bne     TestArus_BDWSErr
         mov     er,0x7FFFFFFF
         mov     gw,0x7FFF
         sremsx  bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x7FFFFFFF
         mov     ax,0x8000
         addsx   cl,fr,ax
         cmp     cl,0xFF
         bne     TestArus_BDWSErr
         mov     gr,0x7FFFFFFF
         mov     bx,0x8000
         subsx   dl,gr,bx
         cmp     dl,0xFF
         bne     TestArus_BDWSErr
         mov     awx,0x7FFFFFFF
         mov     cx,0x8000
         andsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x7FFFFFFF
         mov     dx,0x8000
         orsx    fl,bwx,dx
         cmp     fl,0xFF
         bne     TestArus_BDWSErr
         mov     cwx,0x7FFFFFFF
         mov     ex,0x8000
         xorsx   gl,cwx,ex
         cmp     gl,0xFF
         bne     TestArus_BDWSErr
         mov     dwx,0x7FFFFFFF
         mov     fx,0x8000
         mulsx   ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x7FFFFFFF
         mov     gx,0x8000
         sdivsx  bh,ewx,gx
         cmp     bh,0x01
         bne     TestArus_BDWSErr
         mov     fwx,0x7FFFFFFF
         mov     aw,0x8000
         sremsx  ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0x7FFFFFFF
         mov     bw,0xFFFF
         addsx   dh,gwx,bw
         cmp     dh,0xFE
         bne     TestArus_BDWSErr
         mov     ar,0x7FFFFFFF
         mov     cw,0xFFFF
         subsx   eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x7FFFFFFF
         mov     dw,0xFFFF
         andsx   fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x7FFFFFFF
         mov     ew,0xFFFF
         orsx    gh,cr,ew
         cmp     gh,0xFF
         bne     TestArus_BDWSErr
         mov     dr,0x7FFFFFFF
         mov     fw,0xFFFF
         xorsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x7FFFFFFF
         mov     gw,0xFFFF
         mulsx   bl,er,gw
         cmp     bl,0x01
         bne     TestArus_BDWSErr
         mov     fr,0x7FFFFFFF
         mov     ax,0xFFFF
         sdivsx  cl,fr,ax
         cmp     cl,0x01
         bne     TestArus_BDWSErr
         mov     gr,0x7FFFFFFF
         mov     bx,0xFFFF
         sremsx  dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x80000000
         mov     cx,0x8000
         addsx   el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x80000000
         mov     dx,0x8000
         subsx   fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0x80000000
         mov     ex,0x8000
         andsx   gl,cwx,ex
         cmp     gl,0x00
         bne     TestArus_BDWSErr
         mov     dwx,0x80000000
         mov     fx,0x8000
         orsx    ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0x80000000
         mov     gx,0x8000
         xorsx   bh,ewx,gx
         cmp     bh,0x00
         bne     TestArus_BDWSErr
         mov     fwx,0x80000000
         mov     aw,0x8000
         mulsx   ch,fwx,aw
         cmp     ch,0x00
         bne     TestArus_BDWSErr
         mov     gwx,0x80000000
         mov     bw,0x8000
         sdivsx  dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0x80000000
         mov     cw,0x8000
         sremsx  eh,ar,cw
         cmp     eh,0x00
         bne     TestArus_BDWSErr
         mov     br,0x80000000
         mov     dw,0xFFFF
         addsx   fh,br,dw
         cmp     fh,0xFF
         bne     TestArus_BDWSErr
         mov     cr,0x80000000
         mov     ew,0xFFFF
         subsx   gh,cr,ew
         cmp     gh,0x01
         bne     TestArus_BDWSErr
         mov     dr,0x80000000
         mov     fw,0xFFFF
         andsx   al,dr,fw
         cmp     al,0x00
         bne     TestArus_BDWSErr
         mov     er,0x80000000
         mov     gw,0xFFFF
         orsx    bl,er,gw
         cmp     bl,0xFF
         bne     TestArus_BDWSErr
         mov     fr,0x80000000
         mov     ax,0xFFFF
         xorsx   cl,fr,ax
         cmp     cl,0xFF
         bne     TestArus_BDWSErr
         mov     gr,0x80000000
         mov     bx,0xFFFF
         mulsx   dl,gr,bx
         cmp     dl,0x00
         bne     TestArus_BDWSErr
         mov     awx,0x80000000
         mov     cx,0xFFFF
         sdivsx  el,awx,cx
         cmp     el,0x00
         bne     TestArus_BDWSErr
         mov     bwx,0x80000000
         mov     dx,0xFFFF
         sremsx  fl,bwx,dx
         cmp     fl,0x00
         bne     TestArus_BDWSErr
         mov     cwx,0xFFFFFFFF
         mov     ex,0xFFFF
         addsx   gl,cwx,ex
         cmp     gl,0xFE
         bne     TestArus_BDWSErr
         mov     dwx,0xFFFFFFFF
         mov     fx,0xFFFF
         subsx   ah,dwx,fx
         cmp     ah,0x00
         bne     TestArus_BDWSErr
         mov     ewx,0xFFFFFFFF
         mov     gx,0xFFFF
         andsx   bh,ewx,gx
         cmp     bh,0xFF
         bne     TestArus_BDWSErr
         mov     fwx,0xFFFFFFFF
         mov     aw,0xFFFF
         orsx    ch,fwx,aw
         cmp     ch,0xFF
         bne     TestArus_BDWSErr
         mov     gwx,0xFFFFFFFF
         mov     bw,0xFFFF
         xorsx   dh,gwx,bw
         cmp     dh,0x00
         bne     TestArus_BDWSErr
         mov     ar,0xFFFFFFFF
         mov     cw,0xFFFF
         mulsx   eh,ar,cw
         cmp     eh,0x01
         bne     TestArus_BDWSErr
         mov     br,0xFFFFFFFF
         mov     dw,0xFFFF
         sdivsx  fh,br,dw
         cmp     fh,0x01
         bne     TestArus_BDWSErr
         mov     cr,0xFFFFFFFF
         mov     ew,0xFFFF
         sremsx  gh,cr,ew
         cmp     gh,0x00
         bne     TestArus_BDWSErr
         bra     TestArus_BDWSRet
TestArus_BDWSErr:
         nop     
         trap    
         nop     
TestArus_BDWSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
