.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WWWZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WWWZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         mov     cx,0x0000
         addzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x0000
         subzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x0000
         andzx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x0000
         orzx    aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x0000
         xorzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x0000
         mulzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x0000
         udivzx  dw,gx,bw
         cmp     dw,0xFFFF
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x0000
         uremzx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x0000
         shlzx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x0000
         shrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x0000
         rolzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x0000
         asrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0x0001
         addzx   cx,fw,ax
         cmp     cx,0x0001
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0x0001
         subzx   dx,gw,bx
         cmp     dx,0xFFFF
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0x0001
         andzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x0001
         orzx    fx,bx,dx
         cmp     fx,0x0001
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x0001
         xorzx   gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x0001
         mulzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x0001
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x0001
         uremzx  cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x0001
         shlzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x0001
         shrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x0001
         rolzx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x0001
         asrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x0008
         addzx   ax,dw,fw
         cmp     ax,0x0008
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x0008
         subzx   bx,ew,gw
         cmp     bx,0xFFF8
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0x0008
         andzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0x0008
         orzx    dx,gw,bx
         cmp     dx,0x0008
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0x0008
         xorzx   ex,ax,cx
         cmp     ex,0x0008
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x0008
         mulzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x0008
         udivzx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x0008
         uremzx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x0008
         shlzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x0008
         shrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x0008
         rolzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x0008
         asrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x0009
         addzx   fw,bw,dw
         cmp     fw,0x0009
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x0009
         subzx   gw,cw,ew
         cmp     gw,0xFFF7
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x0009
         andzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x0009
         orzx    bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0x0009
         xorzx   cx,fw,ax
         cmp     cx,0x0009
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0x0009
         mulzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0x0009
         udivzx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x0009
         uremzx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x0009
         shlzx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x0009
         shrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x0009
         rolzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x0009
         asrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x007F
         addzx   dw,gx,bw
         cmp     dw,0x007F
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x007F
         subzx   ew,aw,cw
         cmp     ew,0xFF81
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x007F
         andzx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x007F
         orzx    gw,cw,ew
         cmp     gw,0x007F
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x007F
         xorzx   ax,dw,fw
         cmp     ax,0x007F
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x007F
         mulzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0x007F
         udivzx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0x007F
         uremzx  dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0x000F
         shlzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x000F
         shrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x000F
         rolzx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x000F
         asrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x0080
         addzx   bw,ex,gx
         cmp     bw,0x0080
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x0080
         subzx   cw,fx,aw
         cmp     cw,0xFF80
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x0080
         andzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x0080
         orzx    ew,aw,cw
         cmp     ew,0x0080
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x0080
         xorzx   fw,bw,dw
         cmp     fw,0x0080
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x0080
         mulzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x0080
         udivzx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x0080
         uremzx  bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0x0000
         shlzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0x0000
         shrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0x0000
         rolzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x0000
         asrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x7FFF
         addzx   gx,cx,ex
         cmp     gx,0x7FFF
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x7FFF
         subzx   aw,dx,fx
         cmp     aw,0x8001
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x7FFF
         andzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x7FFF
         orzx    cw,fx,aw
         cmp     cw,0x7FFF
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x7FFF
         xorzx   dw,gx,bw
         cmp     dw,0x7FFF
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x7FFF
         mulzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x7FFF
         udivzx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x7FFF
         uremzx  gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x000F
         shlzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x000F
         shrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0x000F
         rolzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0x000F
         asrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0x8000
         addzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0x8000
         subzx   fx,bx,dx
         cmp     fx,0x8000
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0x8000
         andzx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0x8000
         orzx    aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0x8000
         xorzx   bw,ex,gx
         cmp     bw,0x8000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0x8000
         mulzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x8000
         udivzx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x8000
         uremzx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x0000
         shlzx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x0000
         shrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0000
         mov     fw,0x0000
         rolzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0000
         mov     gw,0x0000
         asrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0000
         mov     ax,0xFFFF
         addzx   cx,fw,ax
         cmp     cx,0xFFFF
         bne     TestArus_WWWZErr
         mov     gw,0x0000
         mov     bx,0xFFFF
         subzx   dx,gw,bx
         cmp     dx,0x0001
         bne     TestArus_WWWZErr
         mov     ax,0x0000
         mov     cx,0xFFFF
         andzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0000
         mov     dx,0xFFFF
         orzx    fx,bx,dx
         cmp     fx,0xFFFF
         bne     TestArus_WWWZErr
         mov     cx,0x0000
         mov     ex,0xFFFF
         xorzx   gx,cx,ex
         cmp     gx,0xFFFF
         bne     TestArus_WWWZErr
         mov     dx,0x0000
         mov     fx,0xFFFF
         mulzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0000
         mov     gx,0xFFFF
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0000
         mov     aw,0xFFFF
         uremzx  cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0000
         mov     bw,0x000F
         shlzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0000
         mov     cw,0x000F
         shrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0000
         mov     dw,0x000F
         rolzx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0000
         mov     ew,0x000F
         asrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0x0001
         addzx   ax,dw,fw
         cmp     ax,0x0002
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0x0001
         subzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0x0001
         andzx   cx,fw,ax
         cmp     cx,0x0001
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0x0001
         orzx    dx,gw,bx
         cmp     dx,0x0001
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0x0001
         xorzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0x0001
         mulzx   fx,bx,dx
         cmp     fx,0x0001
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0x0001
         udivzx  gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0x0001
         uremzx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x0001
         shlzx   bw,ex,gx
         cmp     bw,0x0002
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x0001
         shrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x0001
         rolzx   dw,gx,bw
         cmp     dw,0x0002
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x0001
         asrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0001
         mov     dw,0x0008
         addzx   fw,bw,dw
         cmp     fw,0x0009
         bne     TestArus_WWWZErr
         mov     cw,0x0001
         mov     ew,0x0008
         subzx   gw,cw,ew
         cmp     gw,0xFFF9
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0x0008
         andzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0x0008
         orzx    bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0x0008
         xorzx   cx,fw,ax
         cmp     cx,0x0009
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0x0008
         mulzx   dx,gw,bx
         cmp     dx,0x0008
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0x0008
         udivzx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0x0008
         uremzx  fx,bx,dx
         cmp     fx,0x0001
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0x0008
         shlzx   gx,cx,ex
         cmp     gx,0x0100
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0x0008
         shrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x0008
         rolzx   bw,ex,gx
         cmp     bw,0x0100
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x0008
         asrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x0009
         addzx   dw,gx,bw
         cmp     dw,0x000A
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x0009
         subzx   ew,aw,cw
         cmp     ew,0xFFF8
         bne     TestArus_WWWZErr
         mov     bw,0x0001
         mov     dw,0x0009
         andzx   fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWZErr
         mov     cw,0x0001
         mov     ew,0x0009
         orzx    gw,cw,ew
         cmp     gw,0x0009
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0x0009
         xorzx   ax,dw,fw
         cmp     ax,0x0008
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0x0009
         mulzx   bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0x0009
         udivzx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0x0009
         uremzx  dx,gw,bx
         cmp     dx,0x0001
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0x0009
         shlzx   ex,ax,cx
         cmp     ex,0x0200
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0x0009
         shrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0x0009
         rolzx   gx,cx,ex
         cmp     gx,0x0200
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0x0009
         asrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x007F
         addzx   bw,ex,gx
         cmp     bw,0x0080
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x007F
         subzx   cw,fx,aw
         cmp     cw,0xFF82
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x007F
         andzx   dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x007F
         orzx    ew,aw,cw
         cmp     ew,0x007F
         bne     TestArus_WWWZErr
         mov     bw,0x0001
         mov     dw,0x007F
         xorzx   fw,bw,dw
         cmp     fw,0x007E
         bne     TestArus_WWWZErr
         mov     cw,0x0001
         mov     ew,0x007F
         mulzx   gw,cw,ew
         cmp     gw,0x007F
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0x007F
         udivzx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0x007F
         uremzx  bx,ew,gw
         cmp     bx,0x0001
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0x000F
         shlzx   cx,fw,ax
         cmp     cx,0x8000
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0x000F
         shrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0x000F
         rolzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0x000F
         asrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0x0080
         addzx   gx,cx,ex
         cmp     gx,0x0081
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0x0080
         subzx   aw,dx,fx
         cmp     aw,0xFF81
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x0080
         andzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x0080
         orzx    cw,fx,aw
         cmp     cw,0x0081
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x0080
         xorzx   dw,gx,bw
         cmp     dw,0x0081
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x0080
         mulzx   ew,aw,cw
         cmp     ew,0x0080
         bne     TestArus_WWWZErr
         mov     bw,0x0001
         mov     dw,0x0080
         udivzx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0001
         mov     ew,0x0080
         uremzx  gw,cw,ew
         cmp     gw,0x0001
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0x0000
         shlzx   ax,dw,fw
         cmp     ax,0x0001
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0x0000
         shrzx   bx,ew,gw
         cmp     bx,0x0001
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0x0000
         rolzx   cx,fw,ax
         cmp     cx,0x0001
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0x0000
         asrzx   dx,gw,bx
         cmp     dx,0x0001
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0x7FFF
         addzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0x7FFF
         subzx   fx,bx,dx
         cmp     fx,0x8002
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0x7FFF
         andzx   gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0x7FFF
         orzx    aw,dx,fx
         cmp     aw,0x7FFF
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x7FFF
         xorzx   bw,ex,gx
         cmp     bw,0x7FFE
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x7FFF
         mulzx   cw,fx,aw
         cmp     cw,0x7FFF
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x7FFF
         udivzx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x7FFF
         uremzx  ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWZErr
         mov     bw,0x0001
         mov     dw,0x000F
         shlzx   fw,bw,dw
         cmp     fw,0x8000
         bne     TestArus_WWWZErr
         mov     cw,0x0001
         mov     ew,0x000F
         shrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0x000F
         rolzx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0x000F
         asrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0x8000
         addzx   cx,fw,ax
         cmp     cx,0x8001
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0x8000
         subzx   dx,gw,bx
         cmp     dx,0x8001
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0x8000
         andzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0x8000
         orzx    fx,bx,dx
         cmp     fx,0x8001
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0x8000
         xorzx   gx,cx,ex
         cmp     gx,0x8001
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0x8000
         mulzx   aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x8000
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x8000
         uremzx  cw,fx,aw
         cmp     cw,0x0001
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x0000
         shlzx   dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x0000
         shrzx   ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWZErr
         mov     bw,0x0001
         mov     dw,0x0000
         rolzx   fw,bw,dw
         cmp     fw,0x0001
         bne     TestArus_WWWZErr
         mov     cw,0x0001
         mov     ew,0x0000
         asrzx   gw,cw,ew
         cmp     gw,0x0001
         bne     TestArus_WWWZErr
         mov     dw,0x0001
         mov     fw,0xFFFF
         addzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0001
         mov     gw,0xFFFF
         subzx   bx,ew,gw
         cmp     bx,0x0002
         bne     TestArus_WWWZErr
         mov     fw,0x0001
         mov     ax,0xFFFF
         andzx   cx,fw,ax
         cmp     cx,0x0001
         bne     TestArus_WWWZErr
         mov     gw,0x0001
         mov     bx,0xFFFF
         orzx    dx,gw,bx
         cmp     dx,0xFFFF
         bne     TestArus_WWWZErr
         mov     ax,0x0001
         mov     cx,0xFFFF
         xorzx   ex,ax,cx
         cmp     ex,0xFFFE
         bne     TestArus_WWWZErr
         mov     bx,0x0001
         mov     dx,0xFFFF
         mulzx   fx,bx,dx
         cmp     fx,0xFFFF
         bne     TestArus_WWWZErr
         mov     cx,0x0001
         mov     ex,0xFFFF
         udivzx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0001
         mov     fx,0xFFFF
         uremzx  aw,dx,fx
         cmp     aw,0x0001
         bne     TestArus_WWWZErr
         mov     ex,0x0001
         mov     gx,0x000F
         shlzx   bw,ex,gx
         cmp     bw,0x8000
         bne     TestArus_WWWZErr
         mov     fx,0x0001
         mov     aw,0x000F
         shrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0001
         mov     bw,0x000F
         rolzx   dw,gx,bw
         cmp     dw,0x8000
         bne     TestArus_WWWZErr
         mov     aw,0x0001
         mov     cw,0x000F
         asrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0008
         mov     dw,0x0008
         addzx   fw,bw,dw
         cmp     fw,0x0010
         bne     TestArus_WWWZErr
         mov     cw,0x0008
         mov     ew,0x0008
         subzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0008
         mov     fw,0x0008
         andzx   ax,dw,fw
         cmp     ax,0x0008
         bne     TestArus_WWWZErr
         mov     ew,0x0008
         mov     gw,0x0008
         orzx    bx,ew,gw
         cmp     bx,0x0008
         bne     TestArus_WWWZErr
         mov     fw,0x0008
         mov     ax,0x0008
         xorzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0008
         mov     bx,0x0008
         mulzx   dx,gw,bx
         cmp     dx,0x0040
         bne     TestArus_WWWZErr
         mov     ax,0x0008
         mov     cx,0x0008
         udivzx  ex,ax,cx
         cmp     ex,0x0001
         bne     TestArus_WWWZErr
         mov     bx,0x0008
         mov     dx,0x0008
         uremzx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0008
         mov     ex,0x0008
         shlzx   gx,cx,ex
         cmp     gx,0x0800
         bne     TestArus_WWWZErr
         mov     dx,0x0008
         mov     fx,0x0008
         shrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0008
         mov     gx,0x0008
         rolzx   bw,ex,gx
         cmp     bw,0x0800
         bne     TestArus_WWWZErr
         mov     fx,0x0008
         mov     aw,0x0008
         asrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0008
         mov     bw,0x0009
         addzx   dw,gx,bw
         cmp     dw,0x0011
         bne     TestArus_WWWZErr
         mov     aw,0x0008
         mov     cw,0x0009
         subzx   ew,aw,cw
         cmp     ew,0xFFFF
         bne     TestArus_WWWZErr
         mov     bw,0x0008
         mov     dw,0x0009
         andzx   fw,bw,dw
         cmp     fw,0x0008
         bne     TestArus_WWWZErr
         mov     cw,0x0008
         mov     ew,0x0009
         orzx    gw,cw,ew
         cmp     gw,0x0009
         bne     TestArus_WWWZErr
         mov     dw,0x0008
         mov     fw,0x0009
         xorzx   ax,dw,fw
         cmp     ax,0x0001
         bne     TestArus_WWWZErr
         mov     ew,0x0008
         mov     gw,0x0009
         mulzx   bx,ew,gw
         cmp     bx,0x0048
         bne     TestArus_WWWZErr
         mov     fw,0x0008
         mov     ax,0x0009
         udivzx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0008
         mov     bx,0x0009
         uremzx  dx,gw,bx
         cmp     dx,0x0008
         bne     TestArus_WWWZErr
         mov     ax,0x0008
         mov     cx,0x0009
         shlzx   ex,ax,cx
         cmp     ex,0x1000
         bne     TestArus_WWWZErr
         mov     bx,0x0008
         mov     dx,0x0009
         shrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0008
         mov     ex,0x0009
         rolzx   gx,cx,ex
         cmp     gx,0x1000
         bne     TestArus_WWWZErr
         mov     dx,0x0008
         mov     fx,0x0009
         asrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0008
         mov     gx,0x007F
         addzx   bw,ex,gx
         cmp     bw,0x0087
         bne     TestArus_WWWZErr
         mov     fx,0x0008
         mov     aw,0x007F
         subzx   cw,fx,aw
         cmp     cw,0xFF89
         bne     TestArus_WWWZErr
         mov     gx,0x0008
         mov     bw,0x007F
         andzx   dw,gx,bw
         cmp     dw,0x0008
         bne     TestArus_WWWZErr
         mov     aw,0x0008
         mov     cw,0x007F
         orzx    ew,aw,cw
         cmp     ew,0x007F
         bne     TestArus_WWWZErr
         mov     bw,0x0008
         mov     dw,0x007F
         xorzx   fw,bw,dw
         cmp     fw,0x0077
         bne     TestArus_WWWZErr
         mov     cw,0x0008
         mov     ew,0x007F
         mulzx   gw,cw,ew
         cmp     gw,0x03F8
         bne     TestArus_WWWZErr
         mov     dw,0x0008
         mov     fw,0x007F
         udivzx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0008
         mov     gw,0x007F
         uremzx  bx,ew,gw
         cmp     bx,0x0008
         bne     TestArus_WWWZErr
         mov     fw,0x0008
         mov     ax,0x000F
         shlzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0008
         mov     bx,0x000F
         shrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0008
         mov     cx,0x000F
         rolzx   ex,ax,cx
         cmp     ex,0x0004
         bne     TestArus_WWWZErr
         mov     bx,0x0008
         mov     dx,0x000F
         asrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0008
         mov     ex,0x0080
         addzx   gx,cx,ex
         cmp     gx,0x0088
         bne     TestArus_WWWZErr
         mov     dx,0x0008
         mov     fx,0x0080
         subzx   aw,dx,fx
         cmp     aw,0xFF88
         bne     TestArus_WWWZErr
         mov     ex,0x0008
         mov     gx,0x0080
         andzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0008
         mov     aw,0x0080
         orzx    cw,fx,aw
         cmp     cw,0x0088
         bne     TestArus_WWWZErr
         mov     gx,0x0008
         mov     bw,0x0080
         xorzx   dw,gx,bw
         cmp     dw,0x0088
         bne     TestArus_WWWZErr
         mov     aw,0x0008
         mov     cw,0x0080
         mulzx   ew,aw,cw
         cmp     ew,0x0400
         bne     TestArus_WWWZErr
         mov     bw,0x0008
         mov     dw,0x0080
         udivzx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0008
         mov     ew,0x0080
         uremzx  gw,cw,ew
         cmp     gw,0x0008
         bne     TestArus_WWWZErr
         mov     dw,0x0008
         mov     fw,0x0000
         shlzx   ax,dw,fw
         cmp     ax,0x0008
         bne     TestArus_WWWZErr
         mov     ew,0x0008
         mov     gw,0x0000
         shrzx   bx,ew,gw
         cmp     bx,0x0008
         bne     TestArus_WWWZErr
         mov     fw,0x0008
         mov     ax,0x0000
         rolzx   cx,fw,ax
         cmp     cx,0x0008
         bne     TestArus_WWWZErr
         mov     gw,0x0008
         mov     bx,0x0000
         asrzx   dx,gw,bx
         cmp     dx,0x0008
         bne     TestArus_WWWZErr
         mov     ax,0x0008
         mov     cx,0x7FFF
         addzx   ex,ax,cx
         cmp     ex,0x8007
         bne     TestArus_WWWZErr
         mov     bx,0x0008
         mov     dx,0x7FFF
         subzx   fx,bx,dx
         cmp     fx,0x8009
         bne     TestArus_WWWZErr
         mov     cx,0x0008
         mov     ex,0x7FFF
         andzx   gx,cx,ex
         cmp     gx,0x0008
         bne     TestArus_WWWZErr
         mov     dx,0x0008
         mov     fx,0x7FFF
         orzx    aw,dx,fx
         cmp     aw,0x7FFF
         bne     TestArus_WWWZErr
         mov     ex,0x0008
         mov     gx,0x7FFF
         xorzx   bw,ex,gx
         cmp     bw,0x7FF7
         bne     TestArus_WWWZErr
         mov     fx,0x0008
         mov     aw,0x7FFF
         mulzx   cw,fx,aw
         cmp     cw,0xFFF8
         bne     TestArus_WWWZErr
         mov     gx,0x0008
         mov     bw,0x7FFF
         udivzx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0008
         mov     cw,0x7FFF
         uremzx  ew,aw,cw
         cmp     ew,0x0008
         bne     TestArus_WWWZErr
         mov     bw,0x0008
         mov     dw,0x000F
         shlzx   fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0008
         mov     ew,0x000F
         shrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0008
         mov     fw,0x000F
         rolzx   ax,dw,fw
         cmp     ax,0x0004
         bne     TestArus_WWWZErr
         mov     ew,0x0008
         mov     gw,0x000F
         asrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0008
         mov     ax,0x8000
         addzx   cx,fw,ax
         cmp     cx,0x8008
         bne     TestArus_WWWZErr
         mov     gw,0x0008
         mov     bx,0x8000
         subzx   dx,gw,bx
         cmp     dx,0x8008
         bne     TestArus_WWWZErr
         mov     ax,0x0008
         mov     cx,0x8000
         andzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0008
         mov     dx,0x8000
         orzx    fx,bx,dx
         cmp     fx,0x8008
         bne     TestArus_WWWZErr
         mov     cx,0x0008
         mov     ex,0x8000
         xorzx   gx,cx,ex
         cmp     gx,0x8008
         bne     TestArus_WWWZErr
         mov     dx,0x0008
         mov     fx,0x8000
         mulzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0008
         mov     gx,0x8000
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0008
         mov     aw,0x8000
         uremzx  cw,fx,aw
         cmp     cw,0x0008
         bne     TestArus_WWWZErr
         mov     gx,0x0008
         mov     bw,0x0000
         shlzx   dw,gx,bw
         cmp     dw,0x0008
         bne     TestArus_WWWZErr
         mov     aw,0x0008
         mov     cw,0x0000
         shrzx   ew,aw,cw
         cmp     ew,0x0008
         bne     TestArus_WWWZErr
         mov     bw,0x0008
         mov     dw,0x0000
         rolzx   fw,bw,dw
         cmp     fw,0x0008
         bne     TestArus_WWWZErr
         mov     cw,0x0008
         mov     ew,0x0000
         asrzx   gw,cw,ew
         cmp     gw,0x0008
         bne     TestArus_WWWZErr
         mov     dw,0x0008
         mov     fw,0xFFFF
         addzx   ax,dw,fw
         cmp     ax,0x0007
         bne     TestArus_WWWZErr
         mov     ew,0x0008
         mov     gw,0xFFFF
         subzx   bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0008
         mov     ax,0xFFFF
         andzx   cx,fw,ax
         cmp     cx,0x0008
         bne     TestArus_WWWZErr
         mov     gw,0x0008
         mov     bx,0xFFFF
         orzx    dx,gw,bx
         cmp     dx,0xFFFF
         bne     TestArus_WWWZErr
         mov     ax,0x0008
         mov     cx,0xFFFF
         xorzx   ex,ax,cx
         cmp     ex,0xFFF7
         bne     TestArus_WWWZErr
         mov     bx,0x0008
         mov     dx,0xFFFF
         mulzx   fx,bx,dx
         cmp     fx,0xFFF8
         bne     TestArus_WWWZErr
         mov     cx,0x0008
         mov     ex,0xFFFF
         udivzx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0008
         mov     fx,0xFFFF
         uremzx  aw,dx,fx
         cmp     aw,0x0008
         bne     TestArus_WWWZErr
         mov     ex,0x0008
         mov     gx,0x000F
         shlzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0008
         mov     aw,0x000F
         shrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0008
         mov     bw,0x000F
         rolzx   dw,gx,bw
         cmp     dw,0x0004
         bne     TestArus_WWWZErr
         mov     aw,0x0008
         mov     cw,0x000F
         asrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0009
         mov     dw,0x0009
         addzx   fw,bw,dw
         cmp     fw,0x0012
         bne     TestArus_WWWZErr
         mov     cw,0x0009
         mov     ew,0x0009
         subzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0009
         mov     fw,0x0009
         andzx   ax,dw,fw
         cmp     ax,0x0009
         bne     TestArus_WWWZErr
         mov     ew,0x0009
         mov     gw,0x0009
         orzx    bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0009
         mov     ax,0x0009
         xorzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0009
         mov     bx,0x0009
         mulzx   dx,gw,bx
         cmp     dx,0x0051
         bne     TestArus_WWWZErr
         mov     ax,0x0009
         mov     cx,0x0009
         udivzx  ex,ax,cx
         cmp     ex,0x0001
         bne     TestArus_WWWZErr
         mov     bx,0x0009
         mov     dx,0x0009
         uremzx  fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0009
         mov     ex,0x0009
         shlzx   gx,cx,ex
         cmp     gx,0x1200
         bne     TestArus_WWWZErr
         mov     dx,0x0009
         mov     fx,0x0009
         shrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0009
         mov     gx,0x0009
         rolzx   bw,ex,gx
         cmp     bw,0x1200
         bne     TestArus_WWWZErr
         mov     fx,0x0009
         mov     aw,0x0009
         asrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x0009
         mov     bw,0x007F
         addzx   dw,gx,bw
         cmp     dw,0x0088
         bne     TestArus_WWWZErr
         mov     aw,0x0009
         mov     cw,0x007F
         subzx   ew,aw,cw
         cmp     ew,0xFF8A
         bne     TestArus_WWWZErr
         mov     bw,0x0009
         mov     dw,0x007F
         andzx   fw,bw,dw
         cmp     fw,0x0009
         bne     TestArus_WWWZErr
         mov     cw,0x0009
         mov     ew,0x007F
         orzx    gw,cw,ew
         cmp     gw,0x007F
         bne     TestArus_WWWZErr
         mov     dw,0x0009
         mov     fw,0x007F
         xorzx   ax,dw,fw
         cmp     ax,0x0076
         bne     TestArus_WWWZErr
         mov     ew,0x0009
         mov     gw,0x007F
         mulzx   bx,ew,gw
         cmp     bx,0x0477
         bne     TestArus_WWWZErr
         mov     fw,0x0009
         mov     ax,0x007F
         udivzx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0009
         mov     bx,0x007F
         uremzx  dx,gw,bx
         cmp     dx,0x0009
         bne     TestArus_WWWZErr
         mov     ax,0x0009
         mov     cx,0x000F
         shlzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x0009
         mov     dx,0x000F
         shrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0009
         mov     ex,0x000F
         rolzx   gx,cx,ex
         cmp     gx,0x8004
         bne     TestArus_WWWZErr
         mov     dx,0x0009
         mov     fx,0x000F
         asrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0009
         mov     gx,0x0080
         addzx   bw,ex,gx
         cmp     bw,0x0089
         bne     TestArus_WWWZErr
         mov     fx,0x0009
         mov     aw,0x0080
         subzx   cw,fx,aw
         cmp     cw,0xFF89
         bne     TestArus_WWWZErr
         mov     gx,0x0009
         mov     bw,0x0080
         andzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0009
         mov     cw,0x0080
         orzx    ew,aw,cw
         cmp     ew,0x0089
         bne     TestArus_WWWZErr
         mov     bw,0x0009
         mov     dw,0x0080
         xorzx   fw,bw,dw
         cmp     fw,0x0089
         bne     TestArus_WWWZErr
         mov     cw,0x0009
         mov     ew,0x0080
         mulzx   gw,cw,ew
         cmp     gw,0x0480
         bne     TestArus_WWWZErr
         mov     dw,0x0009
         mov     fw,0x0080
         udivzx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x0009
         mov     gw,0x0080
         uremzx  bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0009
         mov     ax,0x0000
         shlzx   cx,fw,ax
         cmp     cx,0x0009
         bne     TestArus_WWWZErr
         mov     gw,0x0009
         mov     bx,0x0000
         shrzx   dx,gw,bx
         cmp     dx,0x0009
         bne     TestArus_WWWZErr
         mov     ax,0x0009
         mov     cx,0x0000
         rolzx   ex,ax,cx
         cmp     ex,0x0009
         bne     TestArus_WWWZErr
         mov     bx,0x0009
         mov     dx,0x0000
         asrzx   fx,bx,dx
         cmp     fx,0x0009
         bne     TestArus_WWWZErr
         mov     cx,0x0009
         mov     ex,0x7FFF
         addzx   gx,cx,ex
         cmp     gx,0x8008
         bne     TestArus_WWWZErr
         mov     dx,0x0009
         mov     fx,0x7FFF
         subzx   aw,dx,fx
         cmp     aw,0x800A
         bne     TestArus_WWWZErr
         mov     ex,0x0009
         mov     gx,0x7FFF
         andzx   bw,ex,gx
         cmp     bw,0x0009
         bne     TestArus_WWWZErr
         mov     fx,0x0009
         mov     aw,0x7FFF
         orzx    cw,fx,aw
         cmp     cw,0x7FFF
         bne     TestArus_WWWZErr
         mov     gx,0x0009
         mov     bw,0x7FFF
         xorzx   dw,gx,bw
         cmp     dw,0x7FF6
         bne     TestArus_WWWZErr
         mov     aw,0x0009
         mov     cw,0x7FFF
         mulzx   ew,aw,cw
         cmp     ew,0x7FF7
         bne     TestArus_WWWZErr
         mov     bw,0x0009
         mov     dw,0x7FFF
         udivzx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x0009
         mov     ew,0x7FFF
         uremzx  gw,cw,ew
         cmp     gw,0x0009
         bne     TestArus_WWWZErr
         mov     dw,0x0009
         mov     fw,0x000F
         shlzx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWZErr
         mov     ew,0x0009
         mov     gw,0x000F
         shrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x0009
         mov     ax,0x000F
         rolzx   cx,fw,ax
         cmp     cx,0x8004
         bne     TestArus_WWWZErr
         mov     gw,0x0009
         mov     bx,0x000F
         asrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0009
         mov     cx,0x8000
         addzx   ex,ax,cx
         cmp     ex,0x8009
         bne     TestArus_WWWZErr
         mov     bx,0x0009
         mov     dx,0x8000
         subzx   fx,bx,dx
         cmp     fx,0x8009
         bne     TestArus_WWWZErr
         mov     cx,0x0009
         mov     ex,0x8000
         andzx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0009
         mov     fx,0x8000
         orzx    aw,dx,fx
         cmp     aw,0x8009
         bne     TestArus_WWWZErr
         mov     ex,0x0009
         mov     gx,0x8000
         xorzx   bw,ex,gx
         cmp     bw,0x8009
         bne     TestArus_WWWZErr
         mov     fx,0x0009
         mov     aw,0x8000
         mulzx   cw,fx,aw
         cmp     cw,0x8000
         bne     TestArus_WWWZErr
         mov     gx,0x0009
         mov     bw,0x8000
         udivzx  dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0009
         mov     cw,0x8000
         uremzx  ew,aw,cw
         cmp     ew,0x0009
         bne     TestArus_WWWZErr
         mov     bw,0x0009
         mov     dw,0x0000
         shlzx   fw,bw,dw
         cmp     fw,0x0009
         bne     TestArus_WWWZErr
         mov     cw,0x0009
         mov     ew,0x0000
         shrzx   gw,cw,ew
         cmp     gw,0x0009
         bne     TestArus_WWWZErr
         mov     dw,0x0009
         mov     fw,0x0000
         rolzx   ax,dw,fw
         cmp     ax,0x0009
         bne     TestArus_WWWZErr
         mov     ew,0x0009
         mov     gw,0x0000
         asrzx   bx,ew,gw
         cmp     bx,0x0009
         bne     TestArus_WWWZErr
         mov     fw,0x0009
         mov     ax,0xFFFF
         addzx   cx,fw,ax
         cmp     cx,0x0008
         bne     TestArus_WWWZErr
         mov     gw,0x0009
         mov     bx,0xFFFF
         subzx   dx,gw,bx
         cmp     dx,0x000A
         bne     TestArus_WWWZErr
         mov     ax,0x0009
         mov     cx,0xFFFF
         andzx   ex,ax,cx
         cmp     ex,0x0009
         bne     TestArus_WWWZErr
         mov     bx,0x0009
         mov     dx,0xFFFF
         orzx    fx,bx,dx
         cmp     fx,0xFFFF
         bne     TestArus_WWWZErr
         mov     cx,0x0009
         mov     ex,0xFFFF
         xorzx   gx,cx,ex
         cmp     gx,0xFFF6
         bne     TestArus_WWWZErr
         mov     dx,0x0009
         mov     fx,0xFFFF
         mulzx   aw,dx,fx
         cmp     aw,0xFFF7
         bne     TestArus_WWWZErr
         mov     ex,0x0009
         mov     gx,0xFFFF
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0009
         mov     aw,0xFFFF
         uremzx  cw,fx,aw
         cmp     cw,0x0009
         bne     TestArus_WWWZErr
         mov     gx,0x0009
         mov     bw,0x000F
         shlzx   dw,gx,bw
         cmp     dw,0x8000
         bne     TestArus_WWWZErr
         mov     aw,0x0009
         mov     cw,0x000F
         shrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0009
         mov     dw,0x000F
         rolzx   fw,bw,dw
         cmp     fw,0x8004
         bne     TestArus_WWWZErr
         mov     cw,0x0009
         mov     ew,0x000F
         asrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x007F
         mov     fw,0x007F
         addzx   ax,dw,fw
         cmp     ax,0x00FE
         bne     TestArus_WWWZErr
         mov     ew,0x007F
         mov     gw,0x007F
         subzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x007F
         mov     ax,0x007F
         andzx   cx,fw,ax
         cmp     cx,0x007F
         bne     TestArus_WWWZErr
         mov     gw,0x007F
         mov     bx,0x007F
         orzx    dx,gw,bx
         cmp     dx,0x007F
         bne     TestArus_WWWZErr
         mov     ax,0x007F
         mov     cx,0x007F
         xorzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x007F
         mov     dx,0x007F
         mulzx   fx,bx,dx
         cmp     fx,0x3F01
         bne     TestArus_WWWZErr
         mov     cx,0x007F
         mov     ex,0x007F
         udivzx  gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWZErr
         mov     dx,0x007F
         mov     fx,0x007F
         uremzx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x007F
         mov     gx,0x000F
         shlzx   bw,ex,gx
         cmp     bw,0x8000
         bne     TestArus_WWWZErr
         mov     fx,0x007F
         mov     aw,0x000F
         shrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x007F
         mov     bw,0x000F
         rolzx   dw,gx,bw
         cmp     dw,0x803F
         bne     TestArus_WWWZErr
         mov     aw,0x007F
         mov     cw,0x000F
         asrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x007F
         mov     dw,0x0080
         addzx   fw,bw,dw
         cmp     fw,0x00FF
         bne     TestArus_WWWZErr
         mov     cw,0x007F
         mov     ew,0x0080
         subzx   gw,cw,ew
         cmp     gw,0xFFFF
         bne     TestArus_WWWZErr
         mov     dw,0x007F
         mov     fw,0x0080
         andzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x007F
         mov     gw,0x0080
         orzx    bx,ew,gw
         cmp     bx,0x00FF
         bne     TestArus_WWWZErr
         mov     fw,0x007F
         mov     ax,0x0080
         xorzx   cx,fw,ax
         cmp     cx,0x00FF
         bne     TestArus_WWWZErr
         mov     gw,0x007F
         mov     bx,0x0080
         mulzx   dx,gw,bx
         cmp     dx,0x3F80
         bne     TestArus_WWWZErr
         mov     ax,0x007F
         mov     cx,0x0080
         udivzx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x007F
         mov     dx,0x0080
         uremzx  fx,bx,dx
         cmp     fx,0x007F
         bne     TestArus_WWWZErr
         mov     cx,0x007F
         mov     ex,0x0000
         shlzx   gx,cx,ex
         cmp     gx,0x007F
         bne     TestArus_WWWZErr
         mov     dx,0x007F
         mov     fx,0x0000
         shrzx   aw,dx,fx
         cmp     aw,0x007F
         bne     TestArus_WWWZErr
         mov     ex,0x007F
         mov     gx,0x0000
         rolzx   bw,ex,gx
         cmp     bw,0x007F
         bne     TestArus_WWWZErr
         mov     fx,0x007F
         mov     aw,0x0000
         asrzx   cw,fx,aw
         cmp     cw,0x007F
         bne     TestArus_WWWZErr
         mov     gx,0x007F
         mov     bw,0x7FFF
         addzx   dw,gx,bw
         cmp     dw,0x807E
         bne     TestArus_WWWZErr
         mov     aw,0x007F
         mov     cw,0x7FFF
         subzx   ew,aw,cw
         cmp     ew,0x8080
         bne     TestArus_WWWZErr
         mov     bw,0x007F
         mov     dw,0x7FFF
         andzx   fw,bw,dw
         cmp     fw,0x007F
         bne     TestArus_WWWZErr
         mov     cw,0x007F
         mov     ew,0x7FFF
         orzx    gw,cw,ew
         cmp     gw,0x7FFF
         bne     TestArus_WWWZErr
         mov     dw,0x007F
         mov     fw,0x7FFF
         xorzx   ax,dw,fw
         cmp     ax,0x7F80
         bne     TestArus_WWWZErr
         mov     ew,0x007F
         mov     gw,0x7FFF
         mulzx   bx,ew,gw
         cmp     bx,0x7F81
         bne     TestArus_WWWZErr
         mov     fw,0x007F
         mov     ax,0x7FFF
         udivzx  cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x007F
         mov     bx,0x7FFF
         uremzx  dx,gw,bx
         cmp     dx,0x007F
         bne     TestArus_WWWZErr
         mov     ax,0x007F
         mov     cx,0x000F
         shlzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x007F
         mov     dx,0x000F
         shrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x007F
         mov     ex,0x000F
         rolzx   gx,cx,ex
         cmp     gx,0x803F
         bne     TestArus_WWWZErr
         mov     dx,0x007F
         mov     fx,0x000F
         asrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x007F
         mov     gx,0x8000
         addzx   bw,ex,gx
         cmp     bw,0x807F
         bne     TestArus_WWWZErr
         mov     fx,0x007F
         mov     aw,0x8000
         subzx   cw,fx,aw
         cmp     cw,0x807F
         bne     TestArus_WWWZErr
         mov     gx,0x007F
         mov     bw,0x8000
         andzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x007F
         mov     cw,0x8000
         orzx    ew,aw,cw
         cmp     ew,0x807F
         bne     TestArus_WWWZErr
         mov     bw,0x007F
         mov     dw,0x8000
         xorzx   fw,bw,dw
         cmp     fw,0x807F
         bne     TestArus_WWWZErr
         mov     cw,0x007F
         mov     ew,0x8000
         mulzx   gw,cw,ew
         cmp     gw,0x8000
         bne     TestArus_WWWZErr
         mov     dw,0x007F
         mov     fw,0x8000
         udivzx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x007F
         mov     gw,0x8000
         uremzx  bx,ew,gw
         cmp     bx,0x007F
         bne     TestArus_WWWZErr
         mov     fw,0x007F
         mov     ax,0x0000
         shlzx   cx,fw,ax
         cmp     cx,0x007F
         bne     TestArus_WWWZErr
         mov     gw,0x007F
         mov     bx,0x0000
         shrzx   dx,gw,bx
         cmp     dx,0x007F
         bne     TestArus_WWWZErr
         mov     ax,0x007F
         mov     cx,0x0000
         rolzx   ex,ax,cx
         cmp     ex,0x007F
         bne     TestArus_WWWZErr
         mov     bx,0x007F
         mov     dx,0x0000
         asrzx   fx,bx,dx
         cmp     fx,0x007F
         bne     TestArus_WWWZErr
         mov     cx,0x007F
         mov     ex,0xFFFF
         addzx   gx,cx,ex
         cmp     gx,0x007E
         bne     TestArus_WWWZErr
         mov     dx,0x007F
         mov     fx,0xFFFF
         subzx   aw,dx,fx
         cmp     aw,0x0080
         bne     TestArus_WWWZErr
         mov     ex,0x007F
         mov     gx,0xFFFF
         andzx   bw,ex,gx
         cmp     bw,0x007F
         bne     TestArus_WWWZErr
         mov     fx,0x007F
         mov     aw,0xFFFF
         orzx    cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWZErr
         mov     gx,0x007F
         mov     bw,0xFFFF
         xorzx   dw,gx,bw
         cmp     dw,0xFF80
         bne     TestArus_WWWZErr
         mov     aw,0x007F
         mov     cw,0xFFFF
         mulzx   ew,aw,cw
         cmp     ew,0xFF81
         bne     TestArus_WWWZErr
         mov     bw,0x007F
         mov     dw,0xFFFF
         udivzx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x007F
         mov     ew,0xFFFF
         uremzx  gw,cw,ew
         cmp     gw,0x007F
         bne     TestArus_WWWZErr
         mov     dw,0x007F
         mov     fw,0x000F
         shlzx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWZErr
         mov     ew,0x007F
         mov     gw,0x000F
         shrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x007F
         mov     ax,0x000F
         rolzx   cx,fw,ax
         cmp     cx,0x803F
         bne     TestArus_WWWZErr
         mov     gw,0x007F
         mov     bx,0x000F
         asrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x0080
         mov     cx,0x0080
         addzx   ex,ax,cx
         cmp     ex,0x0100
         bne     TestArus_WWWZErr
         mov     bx,0x0080
         mov     dx,0x0080
         subzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0080
         mov     ex,0x0080
         andzx   gx,cx,ex
         cmp     gx,0x0080
         bne     TestArus_WWWZErr
         mov     dx,0x0080
         mov     fx,0x0080
         orzx    aw,dx,fx
         cmp     aw,0x0080
         bne     TestArus_WWWZErr
         mov     ex,0x0080
         mov     gx,0x0080
         xorzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0080
         mov     aw,0x0080
         mulzx   cw,fx,aw
         cmp     cw,0x4000
         bne     TestArus_WWWZErr
         mov     gx,0x0080
         mov     bw,0x0080
         udivzx  dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWZErr
         mov     aw,0x0080
         mov     cw,0x0080
         uremzx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0080
         mov     dw,0x0000
         shlzx   fw,bw,dw
         cmp     fw,0x0080
         bne     TestArus_WWWZErr
         mov     cw,0x0080
         mov     ew,0x0000
         shrzx   gw,cw,ew
         cmp     gw,0x0080
         bne     TestArus_WWWZErr
         mov     dw,0x0080
         mov     fw,0x0000
         rolzx   ax,dw,fw
         cmp     ax,0x0080
         bne     TestArus_WWWZErr
         mov     ew,0x0080
         mov     gw,0x0000
         asrzx   bx,ew,gw
         cmp     bx,0x0080
         bne     TestArus_WWWZErr
         mov     fw,0x0080
         mov     ax,0x7FFF
         addzx   cx,fw,ax
         cmp     cx,0x807F
         bne     TestArus_WWWZErr
         mov     gw,0x0080
         mov     bx,0x7FFF
         subzx   dx,gw,bx
         cmp     dx,0x8081
         bne     TestArus_WWWZErr
         mov     ax,0x0080
         mov     cx,0x7FFF
         andzx   ex,ax,cx
         cmp     ex,0x0080
         bne     TestArus_WWWZErr
         mov     bx,0x0080
         mov     dx,0x7FFF
         orzx    fx,bx,dx
         cmp     fx,0x7FFF
         bne     TestArus_WWWZErr
         mov     cx,0x0080
         mov     ex,0x7FFF
         xorzx   gx,cx,ex
         cmp     gx,0x7F7F
         bne     TestArus_WWWZErr
         mov     dx,0x0080
         mov     fx,0x7FFF
         mulzx   aw,dx,fx
         cmp     aw,0xFF80
         bne     TestArus_WWWZErr
         mov     ex,0x0080
         mov     gx,0x7FFF
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x0080
         mov     aw,0x7FFF
         uremzx  cw,fx,aw
         cmp     cw,0x0080
         bne     TestArus_WWWZErr
         mov     gx,0x0080
         mov     bw,0x000F
         shlzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x0080
         mov     cw,0x000F
         shrzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x0080
         mov     dw,0x000F
         rolzx   fw,bw,dw
         cmp     fw,0x0040
         bne     TestArus_WWWZErr
         mov     cw,0x0080
         mov     ew,0x000F
         asrzx   gw,cw,ew
         cmp     gw,0x0000
         bne     TestArus_WWWZErr
         mov     dw,0x0080
         mov     fw,0x8000
         addzx   ax,dw,fw
         cmp     ax,0x8080
         bne     TestArus_WWWZErr
         mov     ew,0x0080
         mov     gw,0x8000
         subzx   bx,ew,gw
         cmp     bx,0x8080
         bne     TestArus_WWWZErr
         mov     fw,0x0080
         mov     ax,0x8000
         andzx   cx,fw,ax
         cmp     cx,0x0000
         bne     TestArus_WWWZErr
         mov     gw,0x0080
         mov     bx,0x8000
         orzx    dx,gw,bx
         cmp     dx,0x8080
         bne     TestArus_WWWZErr
         mov     ax,0x0080
         mov     cx,0x8000
         xorzx   ex,ax,cx
         cmp     ex,0x8080
         bne     TestArus_WWWZErr
         mov     bx,0x0080
         mov     dx,0x8000
         mulzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x0080
         mov     ex,0x8000
         udivzx  gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0080
         mov     fx,0x8000
         uremzx  aw,dx,fx
         cmp     aw,0x0080
         bne     TestArus_WWWZErr
         mov     ex,0x0080
         mov     gx,0x0000
         shlzx   bw,ex,gx
         cmp     bw,0x0080
         bne     TestArus_WWWZErr
         mov     fx,0x0080
         mov     aw,0x0000
         shrzx   cw,fx,aw
         cmp     cw,0x0080
         bne     TestArus_WWWZErr
         mov     gx,0x0080
         mov     bw,0x0000
         rolzx   dw,gx,bw
         cmp     dw,0x0080
         bne     TestArus_WWWZErr
         mov     aw,0x0080
         mov     cw,0x0000
         asrzx   ew,aw,cw
         cmp     ew,0x0080
         bne     TestArus_WWWZErr
         mov     bw,0x0080
         mov     dw,0xFFFF
         addzx   fw,bw,dw
         cmp     fw,0x007F
         bne     TestArus_WWWZErr
         mov     cw,0x0080
         mov     ew,0xFFFF
         subzx   gw,cw,ew
         cmp     gw,0x0081
         bne     TestArus_WWWZErr
         mov     dw,0x0080
         mov     fw,0xFFFF
         andzx   ax,dw,fw
         cmp     ax,0x0080
         bne     TestArus_WWWZErr
         mov     ew,0x0080
         mov     gw,0xFFFF
         orzx    bx,ew,gw
         cmp     bx,0xFFFF
         bne     TestArus_WWWZErr
         mov     fw,0x0080
         mov     ax,0xFFFF
         xorzx   cx,fw,ax
         cmp     cx,0xFF7F
         bne     TestArus_WWWZErr
         mov     gw,0x0080
         mov     bx,0xFFFF
         mulzx   dx,gw,bx
         cmp     dx,0xFF80
         bne     TestArus_WWWZErr
         mov     ax,0x0080
         mov     cx,0xFFFF
         udivzx  ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x0080
         mov     dx,0xFFFF
         uremzx  fx,bx,dx
         cmp     fx,0x0080
         bne     TestArus_WWWZErr
         mov     cx,0x0080
         mov     ex,0x000F
         shlzx   gx,cx,ex
         cmp     gx,0x0000
         bne     TestArus_WWWZErr
         mov     dx,0x0080
         mov     fx,0x000F
         shrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x0080
         mov     gx,0x000F
         rolzx   bw,ex,gx
         cmp     bw,0x0040
         bne     TestArus_WWWZErr
         mov     fx,0x0080
         mov     aw,0x000F
         asrzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x7FFF
         mov     bw,0x7FFF
         addzx   dw,gx,bw
         cmp     dw,0xFFFE
         bne     TestArus_WWWZErr
         mov     aw,0x7FFF
         mov     cw,0x7FFF
         subzx   ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x7FFF
         mov     dw,0x7FFF
         andzx   fw,bw,dw
         cmp     fw,0x7FFF
         bne     TestArus_WWWZErr
         mov     cw,0x7FFF
         mov     ew,0x7FFF
         orzx    gw,cw,ew
         cmp     gw,0x7FFF
         bne     TestArus_WWWZErr
         mov     dw,0x7FFF
         mov     fw,0x7FFF
         xorzx   ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x7FFF
         mov     gw,0x7FFF
         mulzx   bx,ew,gw
         cmp     bx,0x0001
         bne     TestArus_WWWZErr
         mov     fw,0x7FFF
         mov     ax,0x7FFF
         udivzx  cx,fw,ax
         cmp     cx,0x0001
         bne     TestArus_WWWZErr
         mov     gw,0x7FFF
         mov     bx,0x7FFF
         uremzx  dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x7FFF
         mov     cx,0x000F
         shlzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x7FFF
         mov     dx,0x000F
         shrzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x7FFF
         mov     ex,0x000F
         rolzx   gx,cx,ex
         cmp     gx,0xBFFF
         bne     TestArus_WWWZErr
         mov     dx,0x7FFF
         mov     fx,0x000F
         asrzx   aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0x7FFF
         mov     gx,0x8000
         addzx   bw,ex,gx
         cmp     bw,0xFFFF
         bne     TestArus_WWWZErr
         mov     fx,0x7FFF
         mov     aw,0x8000
         subzx   cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWZErr
         mov     gx,0x7FFF
         mov     bw,0x8000
         andzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x7FFF
         mov     cw,0x8000
         orzx    ew,aw,cw
         cmp     ew,0xFFFF
         bne     TestArus_WWWZErr
         mov     bw,0x7FFF
         mov     dw,0x8000
         xorzx   fw,bw,dw
         cmp     fw,0xFFFF
         bne     TestArus_WWWZErr
         mov     cw,0x7FFF
         mov     ew,0x8000
         mulzx   gw,cw,ew
         cmp     gw,0x8000
         bne     TestArus_WWWZErr
         mov     dw,0x7FFF
         mov     fw,0x8000
         udivzx  ax,dw,fw
         cmp     ax,0x0000
         bne     TestArus_WWWZErr
         mov     ew,0x7FFF
         mov     gw,0x8000
         uremzx  bx,ew,gw
         cmp     bx,0x7FFF
         bne     TestArus_WWWZErr
         mov     fw,0x7FFF
         mov     ax,0x0000
         shlzx   cx,fw,ax
         cmp     cx,0x7FFF
         bne     TestArus_WWWZErr
         mov     gw,0x7FFF
         mov     bx,0x0000
         shrzx   dx,gw,bx
         cmp     dx,0x7FFF
         bne     TestArus_WWWZErr
         mov     ax,0x7FFF
         mov     cx,0x0000
         rolzx   ex,ax,cx
         cmp     ex,0x7FFF
         bne     TestArus_WWWZErr
         mov     bx,0x7FFF
         mov     dx,0x0000
         asrzx   fx,bx,dx
         cmp     fx,0x7FFF
         bne     TestArus_WWWZErr
         mov     cx,0x7FFF
         mov     ex,0xFFFF
         addzx   gx,cx,ex
         cmp     gx,0x7FFE
         bne     TestArus_WWWZErr
         mov     dx,0x7FFF
         mov     fx,0xFFFF
         subzx   aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWZErr
         mov     ex,0x7FFF
         mov     gx,0xFFFF
         andzx   bw,ex,gx
         cmp     bw,0x7FFF
         bne     TestArus_WWWZErr
         mov     fx,0x7FFF
         mov     aw,0xFFFF
         orzx    cw,fx,aw
         cmp     cw,0xFFFF
         bne     TestArus_WWWZErr
         mov     gx,0x7FFF
         mov     bw,0xFFFF
         xorzx   dw,gx,bw
         cmp     dw,0x8000
         bne     TestArus_WWWZErr
         mov     aw,0x7FFF
         mov     cw,0xFFFF
         mulzx   ew,aw,cw
         cmp     ew,0x8001
         bne     TestArus_WWWZErr
         mov     bw,0x7FFF
         mov     dw,0xFFFF
         udivzx  fw,bw,dw
         cmp     fw,0x0000
         bne     TestArus_WWWZErr
         mov     cw,0x7FFF
         mov     ew,0xFFFF
         uremzx  gw,cw,ew
         cmp     gw,0x7FFF
         bne     TestArus_WWWZErr
         mov     dw,0x7FFF
         mov     fw,0x000F
         shlzx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWZErr
         mov     ew,0x7FFF
         mov     gw,0x000F
         shrzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0x7FFF
         mov     ax,0x000F
         rolzx   cx,fw,ax
         cmp     cx,0xBFFF
         bne     TestArus_WWWZErr
         mov     gw,0x7FFF
         mov     bx,0x000F
         asrzx   dx,gw,bx
         cmp     dx,0x0000
         bne     TestArus_WWWZErr
         mov     ax,0x8000
         mov     cx,0x8000
         addzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0x8000
         mov     dx,0x8000
         subzx   fx,bx,dx
         cmp     fx,0x0000
         bne     TestArus_WWWZErr
         mov     cx,0x8000
         mov     ex,0x8000
         andzx   gx,cx,ex
         cmp     gx,0x8000
         bne     TestArus_WWWZErr
         mov     dx,0x8000
         mov     fx,0x8000
         orzx    aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWZErr
         mov     ex,0x8000
         mov     gx,0x8000
         xorzx   bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x8000
         mov     aw,0x8000
         mulzx   cw,fx,aw
         cmp     cw,0x0000
         bne     TestArus_WWWZErr
         mov     gx,0x8000
         mov     bw,0x8000
         udivzx  dw,gx,bw
         cmp     dw,0x0001
         bne     TestArus_WWWZErr
         mov     aw,0x8000
         mov     cw,0x8000
         uremzx  ew,aw,cw
         cmp     ew,0x0000
         bne     TestArus_WWWZErr
         mov     bw,0x8000
         mov     dw,0x0000
         shlzx   fw,bw,dw
         cmp     fw,0x8000
         bne     TestArus_WWWZErr
         mov     cw,0x8000
         mov     ew,0x0000
         shrzx   gw,cw,ew
         cmp     gw,0x8000
         bne     TestArus_WWWZErr
         mov     dw,0x8000
         mov     fw,0x0000
         rolzx   ax,dw,fw
         cmp     ax,0x8000
         bne     TestArus_WWWZErr
         mov     ew,0x8000
         mov     gw,0x0000
         asrzx   bx,ew,gw
         cmp     bx,0x8000
         bne     TestArus_WWWZErr
         mov     fw,0x8000
         mov     ax,0xFFFF
         addzx   cx,fw,ax
         cmp     cx,0x7FFF
         bne     TestArus_WWWZErr
         mov     gw,0x8000
         mov     bx,0xFFFF
         subzx   dx,gw,bx
         cmp     dx,0x8001
         bne     TestArus_WWWZErr
         mov     ax,0x8000
         mov     cx,0xFFFF
         andzx   ex,ax,cx
         cmp     ex,0x8000
         bne     TestArus_WWWZErr
         mov     bx,0x8000
         mov     dx,0xFFFF
         orzx    fx,bx,dx
         cmp     fx,0xFFFF
         bne     TestArus_WWWZErr
         mov     cx,0x8000
         mov     ex,0xFFFF
         xorzx   gx,cx,ex
         cmp     gx,0x7FFF
         bne     TestArus_WWWZErr
         mov     dx,0x8000
         mov     fx,0xFFFF
         mulzx   aw,dx,fx
         cmp     aw,0x8000
         bne     TestArus_WWWZErr
         mov     ex,0x8000
         mov     gx,0xFFFF
         udivzx  bw,ex,gx
         cmp     bw,0x0000
         bne     TestArus_WWWZErr
         mov     fx,0x8000
         mov     aw,0xFFFF
         uremzx  cw,fx,aw
         cmp     cw,0x8000
         bne     TestArus_WWWZErr
         mov     gx,0x8000
         mov     bw,0x000F
         shlzx   dw,gx,bw
         cmp     dw,0x0000
         bne     TestArus_WWWZErr
         mov     aw,0x8000
         mov     cw,0x000F
         shrzx   ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWZErr
         mov     bw,0x8000
         mov     dw,0x000F
         rolzx   fw,bw,dw
         cmp     fw,0x4000
         bne     TestArus_WWWZErr
         mov     cw,0x8000
         mov     ew,0x000F
         asrzx   gw,cw,ew
         cmp     gw,0x0001
         bne     TestArus_WWWZErr
         mov     dw,0xFFFF
         mov     fw,0xFFFF
         addzx   ax,dw,fw
         cmp     ax,0xFFFE
         bne     TestArus_WWWZErr
         mov     ew,0xFFFF
         mov     gw,0xFFFF
         subzx   bx,ew,gw
         cmp     bx,0x0000
         bne     TestArus_WWWZErr
         mov     fw,0xFFFF
         mov     ax,0xFFFF
         andzx   cx,fw,ax
         cmp     cx,0xFFFF
         bne     TestArus_WWWZErr
         mov     gw,0xFFFF
         mov     bx,0xFFFF
         orzx    dx,gw,bx
         cmp     dx,0xFFFF
         bne     TestArus_WWWZErr
         mov     ax,0xFFFF
         mov     cx,0xFFFF
         xorzx   ex,ax,cx
         cmp     ex,0x0000
         bne     TestArus_WWWZErr
         mov     bx,0xFFFF
         mov     dx,0xFFFF
         mulzx   fx,bx,dx
         cmp     fx,0x0001
         bne     TestArus_WWWZErr
         mov     cx,0xFFFF
         mov     ex,0xFFFF
         udivzx  gx,cx,ex
         cmp     gx,0x0001
         bne     TestArus_WWWZErr
         mov     dx,0xFFFF
         mov     fx,0xFFFF
         uremzx  aw,dx,fx
         cmp     aw,0x0000
         bne     TestArus_WWWZErr
         mov     ex,0xFFFF
         mov     gx,0x000F
         shlzx   bw,ex,gx
         cmp     bw,0x8000
         bne     TestArus_WWWZErr
         mov     fx,0xFFFF
         mov     aw,0x000F
         shrzx   cw,fx,aw
         cmp     cw,0x0001
         bne     TestArus_WWWZErr
         mov     gx,0xFFFF
         mov     bw,0x000F
         rolzx   dw,gx,bw
         cmp     dw,0xFFFF
         bne     TestArus_WWWZErr
         mov     aw,0xFFFF
         mov     cw,0x000F
         asrzx   ew,aw,cw
         cmp     ew,0x0001
         bne     TestArus_WWWZErr
         bra     TestArus_WWWZRet
TestArus_WWWZErr:
         nop     
         trap    
         nop     
TestArus_WWWZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
