.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WBWZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WBWZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cx,0x0000
         addzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x0000
         subzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x0000
         andzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x0000
         orzx    aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x0000
         xorzx   bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x0000
         mulzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x0000
         udivzx  dw,gl,bw
         cmp     dw,0xFFFF
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x0000
         uremzx  ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x0000
         shlzx   fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x0000
         shrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x0000
         rolzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x0000
         asrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0x0001
         addzx   cx,fh,ax
         cmp     cx,0x0001
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0x0001
         subzx   dx,gh,bx
         cmp     dx,0xFFFF
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0x0001
         andzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x0001
         orzx    fx,bl,dx
         cmp     fx,0x0001
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x0001
         xorzx   gx,cl,ex
         cmp     gx,0x0001
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x0001
         mulzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x0001
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x0001
         uremzx  cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x0001
         shlzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x0001
         shrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x0001
         rolzx   fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x0001
         asrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x0008
         addzx   ax,dh,fw
         cmp     ax,0x0008
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x0008
         subzx   bx,eh,gw
         cmp     bx,0xFFF8
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0x0008
         andzx   cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0x0008
         orzx    dx,gh,bx
         cmp     dx,0x0008
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0x0008
         xorzx   ex,al,cx
         cmp     ex,0x0008
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x0008
         mulzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x0008
         udivzx  gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x0008
         uremzx  aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x0008
         shlzx   bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x0008
         shrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x0008
         rolzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x0008
         asrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x0009
         addzx   fw,bh,dw
         cmp     fw,0x0009
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x0009
         subzx   gw,ch,ew
         cmp     gw,0xFFF7
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x0009
         andzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x0009
         orzx    bx,eh,gw
         cmp     bx,0x0009
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0x0009
         xorzx   cx,fh,ax
         cmp     cx,0x0009
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0x0009
         mulzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0x0009
         udivzx  ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x0009
         uremzx  fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x0009
         shlzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x0009
         shrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x0009
         rolzx   bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x0009
         asrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x007F
         addzx   dw,gl,bw
         cmp     dw,0x007F
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x007F
         subzx   ew,ah,cw
         cmp     ew,0xFF81
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x007F
         andzx   fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x007F
         orzx    gw,ch,ew
         cmp     gw,0x007F
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x007F
         xorzx   ax,dh,fw
         cmp     ax,0x007F
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x007F
         mulzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0x007F
         udivzx  cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0x007F
         uremzx  dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0x000F
         shlzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x000F
         shrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x000F
         rolzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x000F
         asrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x0080
         addzx   bw,el,gx
         cmp     bw,0x0080
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x0080
         subzx   cw,fl,aw
         cmp     cw,0xFF80
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x0080
         andzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x0080
         orzx    ew,ah,cw
         cmp     ew,0x0080
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x0080
         xorzx   fw,bh,dw
         cmp     fw,0x0080
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x0080
         mulzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x0080
         udivzx  ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x0080
         uremzx  bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0x0000
         shlzx   cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0x0000
         shrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0x0000
         rolzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x0000
         asrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x7FFF
         addzx   gx,cl,ex
         cmp     gx,0x7FFF
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x7FFF
         subzx   aw,dl,fx
         cmp     aw,0x8001
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x7FFF
         andzx   bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x7FFF
         orzx    cw,fl,aw
         cmp     cw,0x7FFF
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x7FFF
         xorzx   dw,gl,bw
         cmp     dw,0x7FFF
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x7FFF
         mulzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x7FFF
         udivzx  fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x7FFF
         uremzx  gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x000F
         shlzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x000F
         shrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0x000F
         rolzx   cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0x000F
         asrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0x8000
         addzx   ex,al,cx
         cmp     ex,0x8000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0x8000
         subzx   fx,bl,dx
         cmp     fx,0x8000
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0x8000
         andzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0x8000
         orzx    aw,dl,fx
         cmp     aw,0x8000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0x8000
         xorzx   bw,el,gx
         cmp     bw,0x8000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0x8000
         mulzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x8000
         udivzx  dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x8000
         uremzx  ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x0000
         shlzx   fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x0000
         shrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x00
         mov     fw,0x0000
         rolzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x00
         mov     gw,0x0000
         asrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x00
         mov     ax,0xFFFF
         addzx   cx,fh,ax
         cmp     cx,0xFFFF
         bne     TestArus_WBWZErr
         mov     gh,0x00
         mov     bx,0xFFFF
         subzx   dx,gh,bx
         cmp     dx,0x0001
         bne     TestArus_WBWZErr
         mov     al,0x00
         mov     cx,0xFFFF
         andzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x00
         mov     dx,0xFFFF
         orzx    fx,bl,dx
         cmp     fx,0xFFFF
         bne     TestArus_WBWZErr
         mov     cl,0x00
         mov     ex,0xFFFF
         xorzx   gx,cl,ex
         cmp     gx,0xFFFF
         bne     TestArus_WBWZErr
         mov     dl,0x00
         mov     fx,0xFFFF
         mulzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x00
         mov     gx,0xFFFF
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x00
         mov     aw,0xFFFF
         uremzx  cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x00
         mov     bw,0x000F
         shlzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x00
         mov     cw,0x000F
         shrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x00
         mov     dw,0x000F
         rolzx   fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x00
         mov     ew,0x000F
         asrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0x0001
         addzx   ax,dh,fw
         cmp     ax,0x0002
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0x0001
         subzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0x0001
         andzx   cx,fh,ax
         cmp     cx,0x0001
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0x0001
         orzx    dx,gh,bx
         cmp     dx,0x0001
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0x0001
         xorzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0x0001
         mulzx   fx,bl,dx
         cmp     fx,0x0001
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0x0001
         udivzx  gx,cl,ex
         cmp     gx,0x0001
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0x0001
         uremzx  aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x0001
         shlzx   bw,el,gx
         cmp     bw,0x0002
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x0001
         shrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x0001
         rolzx   dw,gl,bw
         cmp     dw,0x0002
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x0001
         asrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x01
         mov     dw,0x0008
         addzx   fw,bh,dw
         cmp     fw,0x0009
         bne     TestArus_WBWZErr
         mov     ch,0x01
         mov     ew,0x0008
         subzx   gw,ch,ew
         cmp     gw,0xFFF9
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0x0008
         andzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0x0008
         orzx    bx,eh,gw
         cmp     bx,0x0009
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0x0008
         xorzx   cx,fh,ax
         cmp     cx,0x0009
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0x0008
         mulzx   dx,gh,bx
         cmp     dx,0x0008
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0x0008
         udivzx  ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0x0008
         uremzx  fx,bl,dx
         cmp     fx,0x0001
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0x0008
         shlzx   gx,cl,ex
         cmp     gx,0x0100
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0x0008
         shrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x0008
         rolzx   bw,el,gx
         cmp     bw,0x0100
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x0008
         asrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x0009
         addzx   dw,gl,bw
         cmp     dw,0x000A
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x0009
         subzx   ew,ah,cw
         cmp     ew,0xFFF8
         bne     TestArus_WBWZErr
         mov     bh,0x01
         mov     dw,0x0009
         andzx   fw,bh,dw
         cmp     fw,0x0001
         bne     TestArus_WBWZErr
         mov     ch,0x01
         mov     ew,0x0009
         orzx    gw,ch,ew
         cmp     gw,0x0009
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0x0009
         xorzx   ax,dh,fw
         cmp     ax,0x0008
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0x0009
         mulzx   bx,eh,gw
         cmp     bx,0x0009
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0x0009
         udivzx  cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0x0009
         uremzx  dx,gh,bx
         cmp     dx,0x0001
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0x0009
         shlzx   ex,al,cx
         cmp     ex,0x0200
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0x0009
         shrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0x0009
         rolzx   gx,cl,ex
         cmp     gx,0x0200
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0x0009
         asrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x007F
         addzx   bw,el,gx
         cmp     bw,0x0080
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x007F
         subzx   cw,fl,aw
         cmp     cw,0xFF82
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x007F
         andzx   dw,gl,bw
         cmp     dw,0x0001
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x007F
         orzx    ew,ah,cw
         cmp     ew,0x007F
         bne     TestArus_WBWZErr
         mov     bh,0x01
         mov     dw,0x007F
         xorzx   fw,bh,dw
         cmp     fw,0x007E
         bne     TestArus_WBWZErr
         mov     ch,0x01
         mov     ew,0x007F
         mulzx   gw,ch,ew
         cmp     gw,0x007F
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0x007F
         udivzx  ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0x007F
         uremzx  bx,eh,gw
         cmp     bx,0x0001
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0x000F
         shlzx   cx,fh,ax
         cmp     cx,0x8000
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0x000F
         shrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0x000F
         rolzx   ex,al,cx
         cmp     ex,0x8000
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0x000F
         asrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0x0080
         addzx   gx,cl,ex
         cmp     gx,0x0081
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0x0080
         subzx   aw,dl,fx
         cmp     aw,0xFF81
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x0080
         andzx   bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x0080
         orzx    cw,fl,aw
         cmp     cw,0x0081
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x0080
         xorzx   dw,gl,bw
         cmp     dw,0x0081
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x0080
         mulzx   ew,ah,cw
         cmp     ew,0x0080
         bne     TestArus_WBWZErr
         mov     bh,0x01
         mov     dw,0x0080
         udivzx  fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x01
         mov     ew,0x0080
         uremzx  gw,ch,ew
         cmp     gw,0x0001
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0x0000
         shlzx   ax,dh,fw
         cmp     ax,0x0001
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0x0000
         shrzx   bx,eh,gw
         cmp     bx,0x0001
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0x0000
         rolzx   cx,fh,ax
         cmp     cx,0x0001
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0x0000
         asrzx   dx,gh,bx
         cmp     dx,0x0001
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0x7FFF
         addzx   ex,al,cx
         cmp     ex,0x8000
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0x7FFF
         subzx   fx,bl,dx
         cmp     fx,0x8002
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0x7FFF
         andzx   gx,cl,ex
         cmp     gx,0x0001
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0x7FFF
         orzx    aw,dl,fx
         cmp     aw,0x7FFF
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x7FFF
         xorzx   bw,el,gx
         cmp     bw,0x7FFE
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x7FFF
         mulzx   cw,fl,aw
         cmp     cw,0x7FFF
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x7FFF
         udivzx  dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x7FFF
         uremzx  ew,ah,cw
         cmp     ew,0x0001
         bne     TestArus_WBWZErr
         mov     bh,0x01
         mov     dw,0x000F
         shlzx   fw,bh,dw
         cmp     fw,0x8000
         bne     TestArus_WBWZErr
         mov     ch,0x01
         mov     ew,0x000F
         shrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0x000F
         rolzx   ax,dh,fw
         cmp     ax,0x8000
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0x000F
         asrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0x8000
         addzx   cx,fh,ax
         cmp     cx,0x8001
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0x8000
         subzx   dx,gh,bx
         cmp     dx,0x8001
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0x8000
         andzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0x8000
         orzx    fx,bl,dx
         cmp     fx,0x8001
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0x8000
         xorzx   gx,cl,ex
         cmp     gx,0x8001
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0x8000
         mulzx   aw,dl,fx
         cmp     aw,0x8000
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x8000
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x8000
         uremzx  cw,fl,aw
         cmp     cw,0x0001
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x0000
         shlzx   dw,gl,bw
         cmp     dw,0x0001
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x0000
         shrzx   ew,ah,cw
         cmp     ew,0x0001
         bne     TestArus_WBWZErr
         mov     bh,0x01
         mov     dw,0x0000
         rolzx   fw,bh,dw
         cmp     fw,0x0001
         bne     TestArus_WBWZErr
         mov     ch,0x01
         mov     ew,0x0000
         asrzx   gw,ch,ew
         cmp     gw,0x0001
         bne     TestArus_WBWZErr
         mov     dh,0x01
         mov     fw,0xFFFF
         addzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x01
         mov     gw,0xFFFF
         subzx   bx,eh,gw
         cmp     bx,0x0002
         bne     TestArus_WBWZErr
         mov     fh,0x01
         mov     ax,0xFFFF
         andzx   cx,fh,ax
         cmp     cx,0x0001
         bne     TestArus_WBWZErr
         mov     gh,0x01
         mov     bx,0xFFFF
         orzx    dx,gh,bx
         cmp     dx,0xFFFF
         bne     TestArus_WBWZErr
         mov     al,0x01
         mov     cx,0xFFFF
         xorzx   ex,al,cx
         cmp     ex,0xFFFE
         bne     TestArus_WBWZErr
         mov     bl,0x01
         mov     dx,0xFFFF
         mulzx   fx,bl,dx
         cmp     fx,0xFFFF
         bne     TestArus_WBWZErr
         mov     cl,0x01
         mov     ex,0xFFFF
         udivzx  gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x01
         mov     fx,0xFFFF
         uremzx  aw,dl,fx
         cmp     aw,0x0001
         bne     TestArus_WBWZErr
         mov     el,0x01
         mov     gx,0x000F
         shlzx   bw,el,gx
         cmp     bw,0x8000
         bne     TestArus_WBWZErr
         mov     fl,0x01
         mov     aw,0x000F
         shrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x01
         mov     bw,0x000F
         rolzx   dw,gl,bw
         cmp     dw,0x8000
         bne     TestArus_WBWZErr
         mov     ah,0x01
         mov     cw,0x000F
         asrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x07
         mov     dw,0x0008
         addzx   fw,bh,dw
         cmp     fw,0x000F
         bne     TestArus_WBWZErr
         mov     ch,0x07
         mov     ew,0x0008
         subzx   gw,ch,ew
         cmp     gw,0xFFFF
         bne     TestArus_WBWZErr
         mov     dh,0x07
         mov     fw,0x0008
         andzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x07
         mov     gw,0x0008
         orzx    bx,eh,gw
         cmp     bx,0x000F
         bne     TestArus_WBWZErr
         mov     fh,0x07
         mov     ax,0x0008
         xorzx   cx,fh,ax
         cmp     cx,0x000F
         bne     TestArus_WBWZErr
         mov     gh,0x07
         mov     bx,0x0008
         mulzx   dx,gh,bx
         cmp     dx,0x0038
         bne     TestArus_WBWZErr
         mov     al,0x07
         mov     cx,0x0008
         udivzx  ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x07
         mov     dx,0x0008
         uremzx  fx,bl,dx
         cmp     fx,0x0007
         bne     TestArus_WBWZErr
         mov     cl,0x07
         mov     ex,0x0008
         shlzx   gx,cl,ex
         cmp     gx,0x0700
         bne     TestArus_WBWZErr
         mov     dl,0x07
         mov     fx,0x0008
         shrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x07
         mov     gx,0x0008
         rolzx   bw,el,gx
         cmp     bw,0x0700
         bne     TestArus_WBWZErr
         mov     fl,0x07
         mov     aw,0x0008
         asrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x07
         mov     bw,0x0009
         addzx   dw,gl,bw
         cmp     dw,0x0010
         bne     TestArus_WBWZErr
         mov     ah,0x07
         mov     cw,0x0009
         subzx   ew,ah,cw
         cmp     ew,0xFFFE
         bne     TestArus_WBWZErr
         mov     bh,0x07
         mov     dw,0x0009
         andzx   fw,bh,dw
         cmp     fw,0x0001
         bne     TestArus_WBWZErr
         mov     ch,0x07
         mov     ew,0x0009
         orzx    gw,ch,ew
         cmp     gw,0x000F
         bne     TestArus_WBWZErr
         mov     dh,0x07
         mov     fw,0x0009
         xorzx   ax,dh,fw
         cmp     ax,0x000E
         bne     TestArus_WBWZErr
         mov     eh,0x07
         mov     gw,0x0009
         mulzx   bx,eh,gw
         cmp     bx,0x003F
         bne     TestArus_WBWZErr
         mov     fh,0x07
         mov     ax,0x0009
         udivzx  cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x07
         mov     bx,0x0009
         uremzx  dx,gh,bx
         cmp     dx,0x0007
         bne     TestArus_WBWZErr
         mov     al,0x07
         mov     cx,0x0009
         shlzx   ex,al,cx
         cmp     ex,0x0E00
         bne     TestArus_WBWZErr
         mov     bl,0x07
         mov     dx,0x0009
         shrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x07
         mov     ex,0x0009
         rolzx   gx,cl,ex
         cmp     gx,0x0E00
         bne     TestArus_WBWZErr
         mov     dl,0x07
         mov     fx,0x0009
         asrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x07
         mov     gx,0x007F
         addzx   bw,el,gx
         cmp     bw,0x0086
         bne     TestArus_WBWZErr
         mov     fl,0x07
         mov     aw,0x007F
         subzx   cw,fl,aw
         cmp     cw,0xFF88
         bne     TestArus_WBWZErr
         mov     gl,0x07
         mov     bw,0x007F
         andzx   dw,gl,bw
         cmp     dw,0x0007
         bne     TestArus_WBWZErr
         mov     ah,0x07
         mov     cw,0x007F
         orzx    ew,ah,cw
         cmp     ew,0x007F
         bne     TestArus_WBWZErr
         mov     bh,0x07
         mov     dw,0x007F
         xorzx   fw,bh,dw
         cmp     fw,0x0078
         bne     TestArus_WBWZErr
         mov     ch,0x07
         mov     ew,0x007F
         mulzx   gw,ch,ew
         cmp     gw,0x0379
         bne     TestArus_WBWZErr
         mov     dh,0x07
         mov     fw,0x007F
         udivzx  ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x07
         mov     gw,0x007F
         uremzx  bx,eh,gw
         cmp     bx,0x0007
         bne     TestArus_WBWZErr
         mov     fh,0x07
         mov     ax,0x000F
         shlzx   cx,fh,ax
         cmp     cx,0x8000
         bne     TestArus_WBWZErr
         mov     gh,0x07
         mov     bx,0x000F
         shrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x07
         mov     cx,0x000F
         rolzx   ex,al,cx
         cmp     ex,0x8003
         bne     TestArus_WBWZErr
         mov     bl,0x07
         mov     dx,0x000F
         asrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x07
         mov     ex,0x0080
         addzx   gx,cl,ex
         cmp     gx,0x0087
         bne     TestArus_WBWZErr
         mov     dl,0x07
         mov     fx,0x0080
         subzx   aw,dl,fx
         cmp     aw,0xFF87
         bne     TestArus_WBWZErr
         mov     el,0x07
         mov     gx,0x0080
         andzx   bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x07
         mov     aw,0x0080
         orzx    cw,fl,aw
         cmp     cw,0x0087
         bne     TestArus_WBWZErr
         mov     gl,0x07
         mov     bw,0x0080
         xorzx   dw,gl,bw
         cmp     dw,0x0087
         bne     TestArus_WBWZErr
         mov     ah,0x07
         mov     cw,0x0080
         mulzx   ew,ah,cw
         cmp     ew,0x0380
         bne     TestArus_WBWZErr
         mov     bh,0x07
         mov     dw,0x0080
         udivzx  fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x07
         mov     ew,0x0080
         uremzx  gw,ch,ew
         cmp     gw,0x0007
         bne     TestArus_WBWZErr
         mov     dh,0x07
         mov     fw,0x0000
         shlzx   ax,dh,fw
         cmp     ax,0x0007
         bne     TestArus_WBWZErr
         mov     eh,0x07
         mov     gw,0x0000
         shrzx   bx,eh,gw
         cmp     bx,0x0007
         bne     TestArus_WBWZErr
         mov     fh,0x07
         mov     ax,0x0000
         rolzx   cx,fh,ax
         cmp     cx,0x0007
         bne     TestArus_WBWZErr
         mov     gh,0x07
         mov     bx,0x0000
         asrzx   dx,gh,bx
         cmp     dx,0x0007
         bne     TestArus_WBWZErr
         mov     al,0x07
         mov     cx,0x7FFF
         addzx   ex,al,cx
         cmp     ex,0x8006
         bne     TestArus_WBWZErr
         mov     bl,0x07
         mov     dx,0x7FFF
         subzx   fx,bl,dx
         cmp     fx,0x8008
         bne     TestArus_WBWZErr
         mov     cl,0x07
         mov     ex,0x7FFF
         andzx   gx,cl,ex
         cmp     gx,0x0007
         bne     TestArus_WBWZErr
         mov     dl,0x07
         mov     fx,0x7FFF
         orzx    aw,dl,fx
         cmp     aw,0x7FFF
         bne     TestArus_WBWZErr
         mov     el,0x07
         mov     gx,0x7FFF
         xorzx   bw,el,gx
         cmp     bw,0x7FF8
         bne     TestArus_WBWZErr
         mov     fl,0x07
         mov     aw,0x7FFF
         mulzx   cw,fl,aw
         cmp     cw,0x7FF9
         bne     TestArus_WBWZErr
         mov     gl,0x07
         mov     bw,0x7FFF
         udivzx  dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x07
         mov     cw,0x7FFF
         uremzx  ew,ah,cw
         cmp     ew,0x0007
         bne     TestArus_WBWZErr
         mov     bh,0x07
         mov     dw,0x000F
         shlzx   fw,bh,dw
         cmp     fw,0x8000
         bne     TestArus_WBWZErr
         mov     ch,0x07
         mov     ew,0x000F
         shrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x07
         mov     fw,0x000F
         rolzx   ax,dh,fw
         cmp     ax,0x8003
         bne     TestArus_WBWZErr
         mov     eh,0x07
         mov     gw,0x000F
         asrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x07
         mov     ax,0x8000
         addzx   cx,fh,ax
         cmp     cx,0x8007
         bne     TestArus_WBWZErr
         mov     gh,0x07
         mov     bx,0x8000
         subzx   dx,gh,bx
         cmp     dx,0x8007
         bne     TestArus_WBWZErr
         mov     al,0x07
         mov     cx,0x8000
         andzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x07
         mov     dx,0x8000
         orzx    fx,bl,dx
         cmp     fx,0x8007
         bne     TestArus_WBWZErr
         mov     cl,0x07
         mov     ex,0x8000
         xorzx   gx,cl,ex
         cmp     gx,0x8007
         bne     TestArus_WBWZErr
         mov     dl,0x07
         mov     fx,0x8000
         mulzx   aw,dl,fx
         cmp     aw,0x8000
         bne     TestArus_WBWZErr
         mov     el,0x07
         mov     gx,0x8000
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x07
         mov     aw,0x8000
         uremzx  cw,fl,aw
         cmp     cw,0x0007
         bne     TestArus_WBWZErr
         mov     gl,0x07
         mov     bw,0x0000
         shlzx   dw,gl,bw
         cmp     dw,0x0007
         bne     TestArus_WBWZErr
         mov     ah,0x07
         mov     cw,0x0000
         shrzx   ew,ah,cw
         cmp     ew,0x0007
         bne     TestArus_WBWZErr
         mov     bh,0x07
         mov     dw,0x0000
         rolzx   fw,bh,dw
         cmp     fw,0x0007
         bne     TestArus_WBWZErr
         mov     ch,0x07
         mov     ew,0x0000
         asrzx   gw,ch,ew
         cmp     gw,0x0007
         bne     TestArus_WBWZErr
         mov     dh,0x07
         mov     fw,0xFFFF
         addzx   ax,dh,fw
         cmp     ax,0x0006
         bne     TestArus_WBWZErr
         mov     eh,0x07
         mov     gw,0xFFFF
         subzx   bx,eh,gw
         cmp     bx,0x0008
         bne     TestArus_WBWZErr
         mov     fh,0x07
         mov     ax,0xFFFF
         andzx   cx,fh,ax
         cmp     cx,0x0007
         bne     TestArus_WBWZErr
         mov     gh,0x07
         mov     bx,0xFFFF
         orzx    dx,gh,bx
         cmp     dx,0xFFFF
         bne     TestArus_WBWZErr
         mov     al,0x07
         mov     cx,0xFFFF
         xorzx   ex,al,cx
         cmp     ex,0xFFF8
         bne     TestArus_WBWZErr
         mov     bl,0x07
         mov     dx,0xFFFF
         mulzx   fx,bl,dx
         cmp     fx,0xFFF9
         bne     TestArus_WBWZErr
         mov     cl,0x07
         mov     ex,0xFFFF
         udivzx  gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x07
         mov     fx,0xFFFF
         uremzx  aw,dl,fx
         cmp     aw,0x0007
         bne     TestArus_WBWZErr
         mov     el,0x07
         mov     gx,0x000F
         shlzx   bw,el,gx
         cmp     bw,0x8000
         bne     TestArus_WBWZErr
         mov     fl,0x07
         mov     aw,0x000F
         shrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x07
         mov     bw,0x000F
         rolzx   dw,gl,bw
         cmp     dw,0x8003
         bne     TestArus_WBWZErr
         mov     ah,0x07
         mov     cw,0x000F
         asrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x08
         mov     dw,0x0009
         addzx   fw,bh,dw
         cmp     fw,0x0011
         bne     TestArus_WBWZErr
         mov     ch,0x08
         mov     ew,0x0009
         subzx   gw,ch,ew
         cmp     gw,0xFFFF
         bne     TestArus_WBWZErr
         mov     dh,0x08
         mov     fw,0x0009
         andzx   ax,dh,fw
         cmp     ax,0x0008
         bne     TestArus_WBWZErr
         mov     eh,0x08
         mov     gw,0x0009
         orzx    bx,eh,gw
         cmp     bx,0x0009
         bne     TestArus_WBWZErr
         mov     fh,0x08
         mov     ax,0x0009
         xorzx   cx,fh,ax
         cmp     cx,0x0001
         bne     TestArus_WBWZErr
         mov     gh,0x08
         mov     bx,0x0009
         mulzx   dx,gh,bx
         cmp     dx,0x0048
         bne     TestArus_WBWZErr
         mov     al,0x08
         mov     cx,0x0009
         udivzx  ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x08
         mov     dx,0x0009
         uremzx  fx,bl,dx
         cmp     fx,0x0008
         bne     TestArus_WBWZErr
         mov     cl,0x08
         mov     ex,0x0009
         shlzx   gx,cl,ex
         cmp     gx,0x1000
         bne     TestArus_WBWZErr
         mov     dl,0x08
         mov     fx,0x0009
         shrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x08
         mov     gx,0x0009
         rolzx   bw,el,gx
         cmp     bw,0x1000
         bne     TestArus_WBWZErr
         mov     fl,0x08
         mov     aw,0x0009
         asrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x08
         mov     bw,0x007F
         addzx   dw,gl,bw
         cmp     dw,0x0087
         bne     TestArus_WBWZErr
         mov     ah,0x08
         mov     cw,0x007F
         subzx   ew,ah,cw
         cmp     ew,0xFF89
         bne     TestArus_WBWZErr
         mov     bh,0x08
         mov     dw,0x007F
         andzx   fw,bh,dw
         cmp     fw,0x0008
         bne     TestArus_WBWZErr
         mov     ch,0x08
         mov     ew,0x007F
         orzx    gw,ch,ew
         cmp     gw,0x007F
         bne     TestArus_WBWZErr
         mov     dh,0x08
         mov     fw,0x007F
         xorzx   ax,dh,fw
         cmp     ax,0x0077
         bne     TestArus_WBWZErr
         mov     eh,0x08
         mov     gw,0x007F
         mulzx   bx,eh,gw
         cmp     bx,0x03F8
         bne     TestArus_WBWZErr
         mov     fh,0x08
         mov     ax,0x007F
         udivzx  cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x08
         mov     bx,0x007F
         uremzx  dx,gh,bx
         cmp     dx,0x0008
         bne     TestArus_WBWZErr
         mov     al,0x08
         mov     cx,0x000F
         shlzx   ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x08
         mov     dx,0x000F
         shrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x08
         mov     ex,0x000F
         rolzx   gx,cl,ex
         cmp     gx,0x0004
         bne     TestArus_WBWZErr
         mov     dl,0x08
         mov     fx,0x000F
         asrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x08
         mov     gx,0x0080
         addzx   bw,el,gx
         cmp     bw,0x0088
         bne     TestArus_WBWZErr
         mov     fl,0x08
         mov     aw,0x0080
         subzx   cw,fl,aw
         cmp     cw,0xFF88
         bne     TestArus_WBWZErr
         mov     gl,0x08
         mov     bw,0x0080
         andzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x08
         mov     cw,0x0080
         orzx    ew,ah,cw
         cmp     ew,0x0088
         bne     TestArus_WBWZErr
         mov     bh,0x08
         mov     dw,0x0080
         xorzx   fw,bh,dw
         cmp     fw,0x0088
         bne     TestArus_WBWZErr
         mov     ch,0x08
         mov     ew,0x0080
         mulzx   gw,ch,ew
         cmp     gw,0x0400
         bne     TestArus_WBWZErr
         mov     dh,0x08
         mov     fw,0x0080
         udivzx  ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x08
         mov     gw,0x0080
         uremzx  bx,eh,gw
         cmp     bx,0x0008
         bne     TestArus_WBWZErr
         mov     fh,0x08
         mov     ax,0x0000
         shlzx   cx,fh,ax
         cmp     cx,0x0008
         bne     TestArus_WBWZErr
         mov     gh,0x08
         mov     bx,0x0000
         shrzx   dx,gh,bx
         cmp     dx,0x0008
         bne     TestArus_WBWZErr
         mov     al,0x08
         mov     cx,0x0000
         rolzx   ex,al,cx
         cmp     ex,0x0008
         bne     TestArus_WBWZErr
         mov     bl,0x08
         mov     dx,0x0000
         asrzx   fx,bl,dx
         cmp     fx,0x0008
         bne     TestArus_WBWZErr
         mov     cl,0x08
         mov     ex,0x7FFF
         addzx   gx,cl,ex
         cmp     gx,0x8007
         bne     TestArus_WBWZErr
         mov     dl,0x08
         mov     fx,0x7FFF
         subzx   aw,dl,fx
         cmp     aw,0x8009
         bne     TestArus_WBWZErr
         mov     el,0x08
         mov     gx,0x7FFF
         andzx   bw,el,gx
         cmp     bw,0x0008
         bne     TestArus_WBWZErr
         mov     fl,0x08
         mov     aw,0x7FFF
         orzx    cw,fl,aw
         cmp     cw,0x7FFF
         bne     TestArus_WBWZErr
         mov     gl,0x08
         mov     bw,0x7FFF
         xorzx   dw,gl,bw
         cmp     dw,0x7FF7
         bne     TestArus_WBWZErr
         mov     ah,0x08
         mov     cw,0x7FFF
         mulzx   ew,ah,cw
         cmp     ew,0xFFF8
         bne     TestArus_WBWZErr
         mov     bh,0x08
         mov     dw,0x7FFF
         udivzx  fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x08
         mov     ew,0x7FFF
         uremzx  gw,ch,ew
         cmp     gw,0x0008
         bne     TestArus_WBWZErr
         mov     dh,0x08
         mov     fw,0x000F
         shlzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x08
         mov     gw,0x000F
         shrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x08
         mov     ax,0x000F
         rolzx   cx,fh,ax
         cmp     cx,0x0004
         bne     TestArus_WBWZErr
         mov     gh,0x08
         mov     bx,0x000F
         asrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x08
         mov     cx,0x8000
         addzx   ex,al,cx
         cmp     ex,0x8008
         bne     TestArus_WBWZErr
         mov     bl,0x08
         mov     dx,0x8000
         subzx   fx,bl,dx
         cmp     fx,0x8008
         bne     TestArus_WBWZErr
         mov     cl,0x08
         mov     ex,0x8000
         andzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x08
         mov     fx,0x8000
         orzx    aw,dl,fx
         cmp     aw,0x8008
         bne     TestArus_WBWZErr
         mov     el,0x08
         mov     gx,0x8000
         xorzx   bw,el,gx
         cmp     bw,0x8008
         bne     TestArus_WBWZErr
         mov     fl,0x08
         mov     aw,0x8000
         mulzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x08
         mov     bw,0x8000
         udivzx  dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x08
         mov     cw,0x8000
         uremzx  ew,ah,cw
         cmp     ew,0x0008
         bne     TestArus_WBWZErr
         mov     bh,0x08
         mov     dw,0x0000
         shlzx   fw,bh,dw
         cmp     fw,0x0008
         bne     TestArus_WBWZErr
         mov     ch,0x08
         mov     ew,0x0000
         shrzx   gw,ch,ew
         cmp     gw,0x0008
         bne     TestArus_WBWZErr
         mov     dh,0x08
         mov     fw,0x0000
         rolzx   ax,dh,fw
         cmp     ax,0x0008
         bne     TestArus_WBWZErr
         mov     eh,0x08
         mov     gw,0x0000
         asrzx   bx,eh,gw
         cmp     bx,0x0008
         bne     TestArus_WBWZErr
         mov     fh,0x08
         mov     ax,0xFFFF
         addzx   cx,fh,ax
         cmp     cx,0x0007
         bne     TestArus_WBWZErr
         mov     gh,0x08
         mov     bx,0xFFFF
         subzx   dx,gh,bx
         cmp     dx,0x0009
         bne     TestArus_WBWZErr
         mov     al,0x08
         mov     cx,0xFFFF
         andzx   ex,al,cx
         cmp     ex,0x0008
         bne     TestArus_WBWZErr
         mov     bl,0x08
         mov     dx,0xFFFF
         orzx    fx,bl,dx
         cmp     fx,0xFFFF
         bne     TestArus_WBWZErr
         mov     cl,0x08
         mov     ex,0xFFFF
         xorzx   gx,cl,ex
         cmp     gx,0xFFF7
         bne     TestArus_WBWZErr
         mov     dl,0x08
         mov     fx,0xFFFF
         mulzx   aw,dl,fx
         cmp     aw,0xFFF8
         bne     TestArus_WBWZErr
         mov     el,0x08
         mov     gx,0xFFFF
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x08
         mov     aw,0xFFFF
         uremzx  cw,fl,aw
         cmp     cw,0x0008
         bne     TestArus_WBWZErr
         mov     gl,0x08
         mov     bw,0x000F
         shlzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x08
         mov     cw,0x000F
         shrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x08
         mov     dw,0x000F
         rolzx   fw,bh,dw
         cmp     fw,0x0004
         bne     TestArus_WBWZErr
         mov     ch,0x08
         mov     ew,0x000F
         asrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x09
         mov     fw,0x007F
         addzx   ax,dh,fw
         cmp     ax,0x0088
         bne     TestArus_WBWZErr
         mov     eh,0x09
         mov     gw,0x007F
         subzx   bx,eh,gw
         cmp     bx,0xFF8A
         bne     TestArus_WBWZErr
         mov     fh,0x09
         mov     ax,0x007F
         andzx   cx,fh,ax
         cmp     cx,0x0009
         bne     TestArus_WBWZErr
         mov     gh,0x09
         mov     bx,0x007F
         orzx    dx,gh,bx
         cmp     dx,0x007F
         bne     TestArus_WBWZErr
         mov     al,0x09
         mov     cx,0x007F
         xorzx   ex,al,cx
         cmp     ex,0x0076
         bne     TestArus_WBWZErr
         mov     bl,0x09
         mov     dx,0x007F
         mulzx   fx,bl,dx
         cmp     fx,0x0477
         bne     TestArus_WBWZErr
         mov     cl,0x09
         mov     ex,0x007F
         udivzx  gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x09
         mov     fx,0x007F
         uremzx  aw,dl,fx
         cmp     aw,0x0009
         bne     TestArus_WBWZErr
         mov     el,0x09
         mov     gx,0x000F
         shlzx   bw,el,gx
         cmp     bw,0x8000
         bne     TestArus_WBWZErr
         mov     fl,0x09
         mov     aw,0x000F
         shrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x09
         mov     bw,0x000F
         rolzx   dw,gl,bw
         cmp     dw,0x8004
         bne     TestArus_WBWZErr
         mov     ah,0x09
         mov     cw,0x000F
         asrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x09
         mov     dw,0x0080
         addzx   fw,bh,dw
         cmp     fw,0x0089
         bne     TestArus_WBWZErr
         mov     ch,0x09
         mov     ew,0x0080
         subzx   gw,ch,ew
         cmp     gw,0xFF89
         bne     TestArus_WBWZErr
         mov     dh,0x09
         mov     fw,0x0080
         andzx   ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x09
         mov     gw,0x0080
         orzx    bx,eh,gw
         cmp     bx,0x0089
         bne     TestArus_WBWZErr
         mov     fh,0x09
         mov     ax,0x0080
         xorzx   cx,fh,ax
         cmp     cx,0x0089
         bne     TestArus_WBWZErr
         mov     gh,0x09
         mov     bx,0x0080
         mulzx   dx,gh,bx
         cmp     dx,0x0480
         bne     TestArus_WBWZErr
         mov     al,0x09
         mov     cx,0x0080
         udivzx  ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x09
         mov     dx,0x0080
         uremzx  fx,bl,dx
         cmp     fx,0x0009
         bne     TestArus_WBWZErr
         mov     cl,0x09
         mov     ex,0x0000
         shlzx   gx,cl,ex
         cmp     gx,0x0009
         bne     TestArus_WBWZErr
         mov     dl,0x09
         mov     fx,0x0000
         shrzx   aw,dl,fx
         cmp     aw,0x0009
         bne     TestArus_WBWZErr
         mov     el,0x09
         mov     gx,0x0000
         rolzx   bw,el,gx
         cmp     bw,0x0009
         bne     TestArus_WBWZErr
         mov     fl,0x09
         mov     aw,0x0000
         asrzx   cw,fl,aw
         cmp     cw,0x0009
         bne     TestArus_WBWZErr
         mov     gl,0x09
         mov     bw,0x7FFF
         addzx   dw,gl,bw
         cmp     dw,0x8008
         bne     TestArus_WBWZErr
         mov     ah,0x09
         mov     cw,0x7FFF
         subzx   ew,ah,cw
         cmp     ew,0x800A
         bne     TestArus_WBWZErr
         mov     bh,0x09
         mov     dw,0x7FFF
         andzx   fw,bh,dw
         cmp     fw,0x0009
         bne     TestArus_WBWZErr
         mov     ch,0x09
         mov     ew,0x7FFF
         orzx    gw,ch,ew
         cmp     gw,0x7FFF
         bne     TestArus_WBWZErr
         mov     dh,0x09
         mov     fw,0x7FFF
         xorzx   ax,dh,fw
         cmp     ax,0x7FF6
         bne     TestArus_WBWZErr
         mov     eh,0x09
         mov     gw,0x7FFF
         mulzx   bx,eh,gw
         cmp     bx,0x7FF7
         bne     TestArus_WBWZErr
         mov     fh,0x09
         mov     ax,0x7FFF
         udivzx  cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x09
         mov     bx,0x7FFF
         uremzx  dx,gh,bx
         cmp     dx,0x0009
         bne     TestArus_WBWZErr
         mov     al,0x09
         mov     cx,0x000F
         shlzx   ex,al,cx
         cmp     ex,0x8000
         bne     TestArus_WBWZErr
         mov     bl,0x09
         mov     dx,0x000F
         shrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x09
         mov     ex,0x000F
         rolzx   gx,cl,ex
         cmp     gx,0x8004
         bne     TestArus_WBWZErr
         mov     dl,0x09
         mov     fx,0x000F
         asrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x09
         mov     gx,0x8000
         addzx   bw,el,gx
         cmp     bw,0x8009
         bne     TestArus_WBWZErr
         mov     fl,0x09
         mov     aw,0x8000
         subzx   cw,fl,aw
         cmp     cw,0x8009
         bne     TestArus_WBWZErr
         mov     gl,0x09
         mov     bw,0x8000
         andzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x09
         mov     cw,0x8000
         orzx    ew,ah,cw
         cmp     ew,0x8009
         bne     TestArus_WBWZErr
         mov     bh,0x09
         mov     dw,0x8000
         xorzx   fw,bh,dw
         cmp     fw,0x8009
         bne     TestArus_WBWZErr
         mov     ch,0x09
         mov     ew,0x8000
         mulzx   gw,ch,ew
         cmp     gw,0x8000
         bne     TestArus_WBWZErr
         mov     dh,0x09
         mov     fw,0x8000
         udivzx  ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x09
         mov     gw,0x8000
         uremzx  bx,eh,gw
         cmp     bx,0x0009
         bne     TestArus_WBWZErr
         mov     fh,0x09
         mov     ax,0x0000
         shlzx   cx,fh,ax
         cmp     cx,0x0009
         bne     TestArus_WBWZErr
         mov     gh,0x09
         mov     bx,0x0000
         shrzx   dx,gh,bx
         cmp     dx,0x0009
         bne     TestArus_WBWZErr
         mov     al,0x09
         mov     cx,0x0000
         rolzx   ex,al,cx
         cmp     ex,0x0009
         bne     TestArus_WBWZErr
         mov     bl,0x09
         mov     dx,0x0000
         asrzx   fx,bl,dx
         cmp     fx,0x0009
         bne     TestArus_WBWZErr
         mov     cl,0x09
         mov     ex,0xFFFF
         addzx   gx,cl,ex
         cmp     gx,0x0008
         bne     TestArus_WBWZErr
         mov     dl,0x09
         mov     fx,0xFFFF
         subzx   aw,dl,fx
         cmp     aw,0x000A
         bne     TestArus_WBWZErr
         mov     el,0x09
         mov     gx,0xFFFF
         andzx   bw,el,gx
         cmp     bw,0x0009
         bne     TestArus_WBWZErr
         mov     fl,0x09
         mov     aw,0xFFFF
         orzx    cw,fl,aw
         cmp     cw,0xFFFF
         bne     TestArus_WBWZErr
         mov     gl,0x09
         mov     bw,0xFFFF
         xorzx   dw,gl,bw
         cmp     dw,0xFFF6
         bne     TestArus_WBWZErr
         mov     ah,0x09
         mov     cw,0xFFFF
         mulzx   ew,ah,cw
         cmp     ew,0xFFF7
         bne     TestArus_WBWZErr
         mov     bh,0x09
         mov     dw,0xFFFF
         udivzx  fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x09
         mov     ew,0xFFFF
         uremzx  gw,ch,ew
         cmp     gw,0x0009
         bne     TestArus_WBWZErr
         mov     dh,0x09
         mov     fw,0x000F
         shlzx   ax,dh,fw
         cmp     ax,0x8000
         bne     TestArus_WBWZErr
         mov     eh,0x09
         mov     gw,0x000F
         shrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x09
         mov     ax,0x000F
         rolzx   cx,fh,ax
         cmp     cx,0x8004
         bne     TestArus_WBWZErr
         mov     gh,0x09
         mov     bx,0x000F
         asrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x0F
         mov     cx,0x0080
         addzx   ex,al,cx
         cmp     ex,0x008F
         bne     TestArus_WBWZErr
         mov     bl,0x0F
         mov     dx,0x0080
         subzx   fx,bl,dx
         cmp     fx,0xFF8F
         bne     TestArus_WBWZErr
         mov     cl,0x0F
         mov     ex,0x0080
         andzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x0F
         mov     fx,0x0080
         orzx    aw,dl,fx
         cmp     aw,0x008F
         bne     TestArus_WBWZErr
         mov     el,0x0F
         mov     gx,0x0080
         xorzx   bw,el,gx
         cmp     bw,0x008F
         bne     TestArus_WBWZErr
         mov     fl,0x0F
         mov     aw,0x0080
         mulzx   cw,fl,aw
         cmp     cw,0x0780
         bne     TestArus_WBWZErr
         mov     gl,0x0F
         mov     bw,0x0080
         udivzx  dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x0F
         mov     cw,0x0080
         uremzx  ew,ah,cw
         cmp     ew,0x000F
         bne     TestArus_WBWZErr
         mov     bh,0x0F
         mov     dw,0x0000
         shlzx   fw,bh,dw
         cmp     fw,0x000F
         bne     TestArus_WBWZErr
         mov     ch,0x0F
         mov     ew,0x0000
         shrzx   gw,ch,ew
         cmp     gw,0x000F
         bne     TestArus_WBWZErr
         mov     dh,0x0F
         mov     fw,0x0000
         rolzx   ax,dh,fw
         cmp     ax,0x000F
         bne     TestArus_WBWZErr
         mov     eh,0x0F
         mov     gw,0x0000
         asrzx   bx,eh,gw
         cmp     bx,0x000F
         bne     TestArus_WBWZErr
         mov     fh,0x0F
         mov     ax,0x7FFF
         addzx   cx,fh,ax
         cmp     cx,0x800E
         bne     TestArus_WBWZErr
         mov     gh,0x0F
         mov     bx,0x7FFF
         subzx   dx,gh,bx
         cmp     dx,0x8010
         bne     TestArus_WBWZErr
         mov     al,0x0F
         mov     cx,0x7FFF
         andzx   ex,al,cx
         cmp     ex,0x000F
         bne     TestArus_WBWZErr
         mov     bl,0x0F
         mov     dx,0x7FFF
         orzx    fx,bl,dx
         cmp     fx,0x7FFF
         bne     TestArus_WBWZErr
         mov     cl,0x0F
         mov     ex,0x7FFF
         xorzx   gx,cl,ex
         cmp     gx,0x7FF0
         bne     TestArus_WBWZErr
         mov     dl,0x0F
         mov     fx,0x7FFF
         mulzx   aw,dl,fx
         cmp     aw,0x7FF1
         bne     TestArus_WBWZErr
         mov     el,0x0F
         mov     gx,0x7FFF
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x0F
         mov     aw,0x7FFF
         uremzx  cw,fl,aw
         cmp     cw,0x000F
         bne     TestArus_WBWZErr
         mov     gl,0x0F
         mov     bw,0x000F
         shlzx   dw,gl,bw
         cmp     dw,0x8000
         bne     TestArus_WBWZErr
         mov     ah,0x0F
         mov     cw,0x000F
         shrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x0F
         mov     dw,0x000F
         rolzx   fw,bh,dw
         cmp     fw,0x8007
         bne     TestArus_WBWZErr
         mov     ch,0x0F
         mov     ew,0x000F
         asrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0x0F
         mov     fw,0x8000
         addzx   ax,dh,fw
         cmp     ax,0x800F
         bne     TestArus_WBWZErr
         mov     eh,0x0F
         mov     gw,0x8000
         subzx   bx,eh,gw
         cmp     bx,0x800F
         bne     TestArus_WBWZErr
         mov     fh,0x0F
         mov     ax,0x8000
         andzx   cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x0F
         mov     bx,0x8000
         orzx    dx,gh,bx
         cmp     dx,0x800F
         bne     TestArus_WBWZErr
         mov     al,0x0F
         mov     cx,0x8000
         xorzx   ex,al,cx
         cmp     ex,0x800F
         bne     TestArus_WBWZErr
         mov     bl,0x0F
         mov     dx,0x8000
         mulzx   fx,bl,dx
         cmp     fx,0x8000
         bne     TestArus_WBWZErr
         mov     cl,0x0F
         mov     ex,0x8000
         udivzx  gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x0F
         mov     fx,0x8000
         uremzx  aw,dl,fx
         cmp     aw,0x000F
         bne     TestArus_WBWZErr
         mov     el,0x0F
         mov     gx,0x0000
         shlzx   bw,el,gx
         cmp     bw,0x000F
         bne     TestArus_WBWZErr
         mov     fl,0x0F
         mov     aw,0x0000
         shrzx   cw,fl,aw
         cmp     cw,0x000F
         bne     TestArus_WBWZErr
         mov     gl,0x0F
         mov     bw,0x0000
         rolzx   dw,gl,bw
         cmp     dw,0x000F
         bne     TestArus_WBWZErr
         mov     ah,0x0F
         mov     cw,0x0000
         asrzx   ew,ah,cw
         cmp     ew,0x000F
         bne     TestArus_WBWZErr
         mov     bh,0x0F
         mov     dw,0xFFFF
         addzx   fw,bh,dw
         cmp     fw,0x000E
         bne     TestArus_WBWZErr
         mov     ch,0x0F
         mov     ew,0xFFFF
         subzx   gw,ch,ew
         cmp     gw,0x0010
         bne     TestArus_WBWZErr
         mov     dh,0x0F
         mov     fw,0xFFFF
         andzx   ax,dh,fw
         cmp     ax,0x000F
         bne     TestArus_WBWZErr
         mov     eh,0x0F
         mov     gw,0xFFFF
         orzx    bx,eh,gw
         cmp     bx,0xFFFF
         bne     TestArus_WBWZErr
         mov     fh,0x0F
         mov     ax,0xFFFF
         xorzx   cx,fh,ax
         cmp     cx,0xFFF0
         bne     TestArus_WBWZErr
         mov     gh,0x0F
         mov     bx,0xFFFF
         mulzx   dx,gh,bx
         cmp     dx,0xFFF1
         bne     TestArus_WBWZErr
         mov     al,0x0F
         mov     cx,0xFFFF
         udivzx  ex,al,cx
         cmp     ex,0x0000
         bne     TestArus_WBWZErr
         mov     bl,0x0F
         mov     dx,0xFFFF
         uremzx  fx,bl,dx
         cmp     fx,0x000F
         bne     TestArus_WBWZErr
         mov     cl,0x0F
         mov     ex,0x000F
         shlzx   gx,cl,ex
         cmp     gx,0x8000
         bne     TestArus_WBWZErr
         mov     dl,0x0F
         mov     fx,0x000F
         shrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x0F
         mov     gx,0x000F
         rolzx   bw,el,gx
         cmp     bw,0x8007
         bne     TestArus_WBWZErr
         mov     fl,0x0F
         mov     aw,0x000F
         asrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x7F
         mov     bw,0x7FFF
         addzx   dw,gl,bw
         cmp     dw,0x807E
         bne     TestArus_WBWZErr
         mov     ah,0x7F
         mov     cw,0x7FFF
         subzx   ew,ah,cw
         cmp     ew,0x8080
         bne     TestArus_WBWZErr
         mov     bh,0x7F
         mov     dw,0x7FFF
         andzx   fw,bh,dw
         cmp     fw,0x007F
         bne     TestArus_WBWZErr
         mov     ch,0x7F
         mov     ew,0x7FFF
         orzx    gw,ch,ew
         cmp     gw,0x7FFF
         bne     TestArus_WBWZErr
         mov     dh,0x7F
         mov     fw,0x7FFF
         xorzx   ax,dh,fw
         cmp     ax,0x7F80
         bne     TestArus_WBWZErr
         mov     eh,0x7F
         mov     gw,0x7FFF
         mulzx   bx,eh,gw
         cmp     bx,0x7F81
         bne     TestArus_WBWZErr
         mov     fh,0x7F
         mov     ax,0x7FFF
         udivzx  cx,fh,ax
         cmp     cx,0x0000
         bne     TestArus_WBWZErr
         mov     gh,0x7F
         mov     bx,0x7FFF
         uremzx  dx,gh,bx
         cmp     dx,0x007F
         bne     TestArus_WBWZErr
         mov     al,0x7F
         mov     cx,0x000F
         shlzx   ex,al,cx
         cmp     ex,0x8000
         bne     TestArus_WBWZErr
         mov     bl,0x7F
         mov     dx,0x000F
         shrzx   fx,bl,dx
         cmp     fx,0x0000
         bne     TestArus_WBWZErr
         mov     cl,0x7F
         mov     ex,0x000F
         rolzx   gx,cl,ex
         cmp     gx,0x803F
         bne     TestArus_WBWZErr
         mov     dl,0x7F
         mov     fx,0x000F
         asrzx   aw,dl,fx
         cmp     aw,0x0000
         bne     TestArus_WBWZErr
         mov     el,0x7F
         mov     gx,0x8000
         addzx   bw,el,gx
         cmp     bw,0x807F
         bne     TestArus_WBWZErr
         mov     fl,0x7F
         mov     aw,0x8000
         subzx   cw,fl,aw
         cmp     cw,0x807F
         bne     TestArus_WBWZErr
         mov     gl,0x7F
         mov     bw,0x8000
         andzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x7F
         mov     cw,0x8000
         orzx    ew,ah,cw
         cmp     ew,0x807F
         bne     TestArus_WBWZErr
         mov     bh,0x7F
         mov     dw,0x8000
         xorzx   fw,bh,dw
         cmp     fw,0x807F
         bne     TestArus_WBWZErr
         mov     ch,0x7F
         mov     ew,0x8000
         mulzx   gw,ch,ew
         cmp     gw,0x8000
         bne     TestArus_WBWZErr
         mov     dh,0x7F
         mov     fw,0x8000
         udivzx  ax,dh,fw
         cmp     ax,0x0000
         bne     TestArus_WBWZErr
         mov     eh,0x7F
         mov     gw,0x8000
         uremzx  bx,eh,gw
         cmp     bx,0x007F
         bne     TestArus_WBWZErr
         mov     fh,0x7F
         mov     ax,0x0000
         shlzx   cx,fh,ax
         cmp     cx,0x007F
         bne     TestArus_WBWZErr
         mov     gh,0x7F
         mov     bx,0x0000
         shrzx   dx,gh,bx
         cmp     dx,0x007F
         bne     TestArus_WBWZErr
         mov     al,0x7F
         mov     cx,0x0000
         rolzx   ex,al,cx
         cmp     ex,0x007F
         bne     TestArus_WBWZErr
         mov     bl,0x7F
         mov     dx,0x0000
         asrzx   fx,bl,dx
         cmp     fx,0x007F
         bne     TestArus_WBWZErr
         mov     cl,0x7F
         mov     ex,0xFFFF
         addzx   gx,cl,ex
         cmp     gx,0x007E
         bne     TestArus_WBWZErr
         mov     dl,0x7F
         mov     fx,0xFFFF
         subzx   aw,dl,fx
         cmp     aw,0x0080
         bne     TestArus_WBWZErr
         mov     el,0x7F
         mov     gx,0xFFFF
         andzx   bw,el,gx
         cmp     bw,0x007F
         bne     TestArus_WBWZErr
         mov     fl,0x7F
         mov     aw,0xFFFF
         orzx    cw,fl,aw
         cmp     cw,0xFFFF
         bne     TestArus_WBWZErr
         mov     gl,0x7F
         mov     bw,0xFFFF
         xorzx   dw,gl,bw
         cmp     dw,0xFF80
         bne     TestArus_WBWZErr
         mov     ah,0x7F
         mov     cw,0xFFFF
         mulzx   ew,ah,cw
         cmp     ew,0xFF81
         bne     TestArus_WBWZErr
         mov     bh,0x7F
         mov     dw,0xFFFF
         udivzx  fw,bh,dw
         cmp     fw,0x0000
         bne     TestArus_WBWZErr
         mov     ch,0x7F
         mov     ew,0xFFFF
         uremzx  gw,ch,ew
         cmp     gw,0x007F
         bne     TestArus_WBWZErr
         mov     dh,0x7F
         mov     fw,0x000F
         shlzx   ax,dh,fw
         cmp     ax,0x8000
         bne     TestArus_WBWZErr
         mov     eh,0x7F
         mov     gw,0x000F
         shrzx   bx,eh,gw
         cmp     bx,0x0000
         bne     TestArus_WBWZErr
         mov     fh,0x7F
         mov     ax,0x000F
         rolzx   cx,fh,ax
         cmp     cx,0x803F
         bne     TestArus_WBWZErr
         mov     gh,0x7F
         mov     bx,0x000F
         asrzx   dx,gh,bx
         cmp     dx,0x0000
         bne     TestArus_WBWZErr
         mov     al,0x80
         mov     cx,0x8000
         addzx   ex,al,cx
         cmp     ex,0x8080
         bne     TestArus_WBWZErr
         mov     bl,0x80
         mov     dx,0x8000
         subzx   fx,bl,dx
         cmp     fx,0x8080
         bne     TestArus_WBWZErr
         mov     cl,0x80
         mov     ex,0x8000
         andzx   gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0x80
         mov     fx,0x8000
         orzx    aw,dl,fx
         cmp     aw,0x8080
         bne     TestArus_WBWZErr
         mov     el,0x80
         mov     gx,0x8000
         xorzx   bw,el,gx
         cmp     bw,0x8080
         bne     TestArus_WBWZErr
         mov     fl,0x80
         mov     aw,0x8000
         mulzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0x80
         mov     bw,0x8000
         udivzx  dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x80
         mov     cw,0x8000
         uremzx  ew,ah,cw
         cmp     ew,0x0080
         bne     TestArus_WBWZErr
         mov     bh,0x80
         mov     dw,0x0000
         shlzx   fw,bh,dw
         cmp     fw,0x0080
         bne     TestArus_WBWZErr
         mov     ch,0x80
         mov     ew,0x0000
         shrzx   gw,ch,ew
         cmp     gw,0x0080
         bne     TestArus_WBWZErr
         mov     dh,0x80
         mov     fw,0x0000
         rolzx   ax,dh,fw
         cmp     ax,0x0080
         bne     TestArus_WBWZErr
         mov     eh,0x80
         mov     gw,0x0000
         asrzx   bx,eh,gw
         cmp     bx,0x0080
         bne     TestArus_WBWZErr
         mov     fh,0x80
         mov     ax,0xFFFF
         addzx   cx,fh,ax
         cmp     cx,0x007F
         bne     TestArus_WBWZErr
         mov     gh,0x80
         mov     bx,0xFFFF
         subzx   dx,gh,bx
         cmp     dx,0x0081
         bne     TestArus_WBWZErr
         mov     al,0x80
         mov     cx,0xFFFF
         andzx   ex,al,cx
         cmp     ex,0x0080
         bne     TestArus_WBWZErr
         mov     bl,0x80
         mov     dx,0xFFFF
         orzx    fx,bl,dx
         cmp     fx,0xFFFF
         bne     TestArus_WBWZErr
         mov     cl,0x80
         mov     ex,0xFFFF
         xorzx   gx,cl,ex
         cmp     gx,0xFF7F
         bne     TestArus_WBWZErr
         mov     dl,0x80
         mov     fx,0xFFFF
         mulzx   aw,dl,fx
         cmp     aw,0xFF80
         bne     TestArus_WBWZErr
         mov     el,0x80
         mov     gx,0xFFFF
         udivzx  bw,el,gx
         cmp     bw,0x0000
         bne     TestArus_WBWZErr
         mov     fl,0x80
         mov     aw,0xFFFF
         uremzx  cw,fl,aw
         cmp     cw,0x0080
         bne     TestArus_WBWZErr
         mov     gl,0x80
         mov     bw,0x000F
         shlzx   dw,gl,bw
         cmp     dw,0x0000
         bne     TestArus_WBWZErr
         mov     ah,0x80
         mov     cw,0x000F
         shrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         mov     bh,0x80
         mov     dw,0x000F
         rolzx   fw,bh,dw
         cmp     fw,0x0040
         bne     TestArus_WBWZErr
         mov     ch,0x80
         mov     ew,0x000F
         asrzx   gw,ch,ew
         cmp     gw,0x0000
         bne     TestArus_WBWZErr
         mov     dh,0xFF
         mov     fw,0xFFFF
         addzx   ax,dh,fw
         cmp     ax,0x00FE
         bne     TestArus_WBWZErr
         mov     eh,0xFF
         mov     gw,0xFFFF
         subzx   bx,eh,gw
         cmp     bx,0x0100
         bne     TestArus_WBWZErr
         mov     fh,0xFF
         mov     ax,0xFFFF
         andzx   cx,fh,ax
         cmp     cx,0x00FF
         bne     TestArus_WBWZErr
         mov     gh,0xFF
         mov     bx,0xFFFF
         orzx    dx,gh,bx
         cmp     dx,0xFFFF
         bne     TestArus_WBWZErr
         mov     al,0xFF
         mov     cx,0xFFFF
         xorzx   ex,al,cx
         cmp     ex,0xFF00
         bne     TestArus_WBWZErr
         mov     bl,0xFF
         mov     dx,0xFFFF
         mulzx   fx,bl,dx
         cmp     fx,0xFF01
         bne     TestArus_WBWZErr
         mov     cl,0xFF
         mov     ex,0xFFFF
         udivzx  gx,cl,ex
         cmp     gx,0x0000
         bne     TestArus_WBWZErr
         mov     dl,0xFF
         mov     fx,0xFFFF
         uremzx  aw,dl,fx
         cmp     aw,0x00FF
         bne     TestArus_WBWZErr
         mov     el,0xFF
         mov     gx,0x000F
         shlzx   bw,el,gx
         cmp     bw,0x8000
         bne     TestArus_WBWZErr
         mov     fl,0xFF
         mov     aw,0x000F
         shrzx   cw,fl,aw
         cmp     cw,0x0000
         bne     TestArus_WBWZErr
         mov     gl,0xFF
         mov     bw,0x000F
         rolzx   dw,gl,bw
         cmp     dw,0x807F
         bne     TestArus_WBWZErr
         mov     ah,0xFF
         mov     cw,0x000F
         asrzx   ew,ah,cw
         cmp     ew,0x0000
         bne     TestArus_WBWZErr
         bra     TestArus_WBWZRet
TestArus_WBWZErr:
         nop     
         trap    
         nop     
TestArus_WBWZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
