.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestBTM_RB

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestBTM_RB:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,4
         mov     bwx,esp
         mov     al,0x00
         mov     [bwx+0],al
         bt      [bwx+0],0
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x00
         bne     TestBTM_RBErr
         mov     al,0x00
         mov     [bwx+0],al
         btr     [bwx+0],0
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x00
         bne     TestBTM_RBErr
         mov     al,0x00
         mov     [bwx+0],al
         bts     [bwx+0],0
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x01
         bne     TestBTM_RBErr
                 
         mov     al,0x00
         bt      al,0
         bc      TestBTM_RBErr
         cmp     al,0x00
         bne     TestBTM_RBErr
         mov     al,0x00
         btr     al,0
         bc      TestBTM_RBErr
         cmp     al,0x00
         bne     TestBTM_RBErr
         mov     al,0x00
         bts     al,0
         bc      TestBTM_RBErr
         cmp     al,0x01
         bne     TestBTM_RBErr
                 
         mov     cwx,esp
         mov     bl,0x00
         mov     [cwx+1],bl
         bt      [cwx+1],1
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x00
         bne     TestBTM_RBErr
         mov     bl,0x00
         mov     [cwx+1],bl
         btr     [cwx+1],1
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x00
         bne     TestBTM_RBErr
         mov     bl,0x00
         mov     [cwx+1],bl
         bts     [cwx+1],1
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x02
         bne     TestBTM_RBErr
                 
         mov     bl,0x00
         bt      bl,1
         bc      TestBTM_RBErr
         cmp     bl,0x00
         bne     TestBTM_RBErr
         mov     bl,0x00
         btr     bl,1
         bc      TestBTM_RBErr
         cmp     bl,0x00
         bne     TestBTM_RBErr
         mov     bl,0x00
         bts     bl,1
         bc      TestBTM_RBErr
         cmp     bl,0x02
         bne     TestBTM_RBErr
                 
         mov     dwx,esp
         mov     cl,0x00
         mov     [dwx+2],cl
         bt      [dwx+2],2
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x00
         bne     TestBTM_RBErr
         mov     cl,0x00
         mov     [dwx+2],cl
         btr     [dwx+2],2
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x00
         bne     TestBTM_RBErr
         mov     cl,0x00
         mov     [dwx+2],cl
         bts     [dwx+2],2
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x04
         bne     TestBTM_RBErr
                 
         mov     cl,0x00
         bt      cl,2
         bc      TestBTM_RBErr
         cmp     cl,0x00
         bne     TestBTM_RBErr
         mov     cl,0x00
         btr     cl,2
         bc      TestBTM_RBErr
         cmp     cl,0x00
         bne     TestBTM_RBErr
         mov     cl,0x00
         bts     cl,2
         bc      TestBTM_RBErr
         cmp     cl,0x04
         bne     TestBTM_RBErr
                 
         mov     ewx,esp
         mov     dl,0x00
         mov     [ewx+3],dl
         bt      [ewx+3],3
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x00
         bne     TestBTM_RBErr
         mov     dl,0x00
         mov     [ewx+3],dl
         btr     [ewx+3],3
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x00
         bne     TestBTM_RBErr
         mov     dl,0x00
         mov     [ewx+3],dl
         bts     [ewx+3],3
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x08
         bne     TestBTM_RBErr
                 
         mov     dl,0x00
         bt      dl,3
         bc      TestBTM_RBErr
         cmp     dl,0x00
         bne     TestBTM_RBErr
         mov     dl,0x00
         btr     dl,3
         bc      TestBTM_RBErr
         cmp     dl,0x00
         bne     TestBTM_RBErr
         mov     dl,0x00
         bts     dl,3
         bc      TestBTM_RBErr
         cmp     dl,0x08
         bne     TestBTM_RBErr
                 
         mov     fwx,esp
         mov     el,0x00
         mov     [fwx+0],el
         bt      [fwx+0],4
         bc      TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x00
         bne     TestBTM_RBErr
         mov     el,0x00
         mov     [fwx+0],el
         btr     [fwx+0],4
         bc      TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x00
         bne     TestBTM_RBErr
         mov     el,0x00
         mov     [fwx+0],el
         bts     [fwx+0],4
         bc      TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x10
         bne     TestBTM_RBErr
                 
         mov     el,0x00
         bt      el,4
         bc      TestBTM_RBErr
         cmp     el,0x00
         bne     TestBTM_RBErr
         mov     el,0x00
         btr     el,4
         bc      TestBTM_RBErr
         cmp     el,0x00
         bne     TestBTM_RBErr
         mov     el,0x00
         bts     el,4
         bc      TestBTM_RBErr
         cmp     el,0x10
         bne     TestBTM_RBErr
                 
         mov     gwx,esp
         mov     fl,0x00
         mov     [gwx+1],fl
         bt      [gwx+1],5
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x00
         bne     TestBTM_RBErr
         mov     fl,0x00
         mov     [gwx+1],fl
         btr     [gwx+1],5
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x00
         bne     TestBTM_RBErr
         mov     fl,0x00
         mov     [gwx+1],fl
         bts     [gwx+1],5
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x20
         bne     TestBTM_RBErr
                 
         mov     fl,0x00
         bt      fl,5
         bc      TestBTM_RBErr
         cmp     fl,0x00
         bne     TestBTM_RBErr
         mov     fl,0x00
         btr     fl,5
         bc      TestBTM_RBErr
         cmp     fl,0x00
         bne     TestBTM_RBErr
         mov     fl,0x00
         bts     fl,5
         bc      TestBTM_RBErr
         cmp     fl,0x20
         bne     TestBTM_RBErr
                 
         mov     ar,esp
         mov     gl,0x00
         mov     [ar+2],gl
         bt      [ar+2],6
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x00
         bne     TestBTM_RBErr
         mov     gl,0x00
         mov     [ar+2],gl
         btr     [ar+2],6
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x00
         bne     TestBTM_RBErr
         mov     gl,0x00
         mov     [ar+2],gl
         bts     [ar+2],6
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x40
         bne     TestBTM_RBErr
                 
         mov     gl,0x00
         bt      gl,6
         bc      TestBTM_RBErr
         cmp     gl,0x00
         bne     TestBTM_RBErr
         mov     gl,0x00
         btr     gl,6
         bc      TestBTM_RBErr
         cmp     gl,0x00
         bne     TestBTM_RBErr
         mov     gl,0x00
         bts     gl,6
         bc      TestBTM_RBErr
         cmp     gl,0x40
         bne     TestBTM_RBErr
                 
         mov     br,esp
         mov     ah,0x00
         mov     [br+3],ah
         bt      [br+3],7
         bc      TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x00
         bne     TestBTM_RBErr
         mov     ah,0x00
         mov     [br+3],ah
         btr     [br+3],7
         bc      TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x00
         bne     TestBTM_RBErr
         mov     ah,0x00
         mov     [br+3],ah
         bts     [br+3],7
         bc      TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x80
         bne     TestBTM_RBErr
                 
         mov     ah,0x00
         bt      ah,7
         bc      TestBTM_RBErr
         cmp     ah,0x00
         bne     TestBTM_RBErr
         mov     ah,0x00
         btr     ah,7
         bc      TestBTM_RBErr
         cmp     ah,0x00
         bne     TestBTM_RBErr
         mov     ah,0x00
         bts     ah,7
         bc      TestBTM_RBErr
         cmp     ah,0x80
         bne     TestBTM_RBErr
                 
         mov     cr,esp
         mov     bh,0x01
         mov     [cr+0],bh
         bt      [cr+0],0
         bnc     TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0x01
         bne     TestBTM_RBErr
         mov     bh,0x01
         mov     [cr+0],bh
         btr     [cr+0],0
         bnc     TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0x00
         bne     TestBTM_RBErr
         mov     bh,0x01
         mov     [cr+0],bh
         bts     [cr+0],0
         bnc     TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0x01
         bne     TestBTM_RBErr
                 
         mov     bh,0x01
         bt      bh,0
         bnc     TestBTM_RBErr
         cmp     bh,0x01
         bne     TestBTM_RBErr
         mov     bh,0x01
         btr     bh,0
         bnc     TestBTM_RBErr
         cmp     bh,0x00
         bne     TestBTM_RBErr
         mov     bh,0x01
         bts     bh,0
         bnc     TestBTM_RBErr
         cmp     bh,0x01
         bne     TestBTM_RBErr
                 
         mov     dr,esp
         mov     ch,0x01
         mov     [dr+1],ch
         bt      [dr+1],1
         bc      TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0x01
         bne     TestBTM_RBErr
         mov     ch,0x01
         mov     [dr+1],ch
         btr     [dr+1],1
         bc      TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0x01
         bne     TestBTM_RBErr
         mov     ch,0x01
         mov     [dr+1],ch
         bts     [dr+1],1
         bc      TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0x03
         bne     TestBTM_RBErr
                 
         mov     ch,0x01
         bt      ch,1
         bc      TestBTM_RBErr
         cmp     ch,0x01
         bne     TestBTM_RBErr
         mov     ch,0x01
         btr     ch,1
         bc      TestBTM_RBErr
         cmp     ch,0x01
         bne     TestBTM_RBErr
         mov     ch,0x01
         bts     ch,1
         bc      TestBTM_RBErr
         cmp     ch,0x03
         bne     TestBTM_RBErr
                 
         mov     er,esp
         mov     dh,0x01
         mov     [er+2],dh
         bt      [er+2],2
         bc      TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0x01
         bne     TestBTM_RBErr
         mov     dh,0x01
         mov     [er+2],dh
         btr     [er+2],2
         bc      TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0x01
         bne     TestBTM_RBErr
         mov     dh,0x01
         mov     [er+2],dh
         bts     [er+2],2
         bc      TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0x05
         bne     TestBTM_RBErr
                 
         mov     dh,0x01
         bt      dh,2
         bc      TestBTM_RBErr
         cmp     dh,0x01
         bne     TestBTM_RBErr
         mov     dh,0x01
         btr     dh,2
         bc      TestBTM_RBErr
         cmp     dh,0x01
         bne     TestBTM_RBErr
         mov     dh,0x01
         bts     dh,2
         bc      TestBTM_RBErr
         cmp     dh,0x05
         bne     TestBTM_RBErr
                 
         mov     fr,esp
         mov     eh,0x01
         mov     [fr+3],eh
         bt      [fr+3],3
         bc      TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0x01
         bne     TestBTM_RBErr
         mov     eh,0x01
         mov     [fr+3],eh
         btr     [fr+3],3
         bc      TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0x01
         bne     TestBTM_RBErr
         mov     eh,0x01
         mov     [fr+3],eh
         bts     [fr+3],3
         bc      TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0x09
         bne     TestBTM_RBErr
                 
         mov     eh,0x01
         bt      eh,3
         bc      TestBTM_RBErr
         cmp     eh,0x01
         bne     TestBTM_RBErr
         mov     eh,0x01
         btr     eh,3
         bc      TestBTM_RBErr
         cmp     eh,0x01
         bne     TestBTM_RBErr
         mov     eh,0x01
         bts     eh,3
         bc      TestBTM_RBErr
         cmp     eh,0x09
         bne     TestBTM_RBErr
                 
         mov     gr,esp
         mov     fh,0x01
         mov     [gr+0],fh
         bt      [gr+0],4
         bc      TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0x01
         bne     TestBTM_RBErr
         mov     fh,0x01
         mov     [gr+0],fh
         btr     [gr+0],4
         bc      TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0x01
         bne     TestBTM_RBErr
         mov     fh,0x01
         mov     [gr+0],fh
         bts     [gr+0],4
         bc      TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0x11
         bne     TestBTM_RBErr
                 
         mov     fh,0x01
         bt      fh,4
         bc      TestBTM_RBErr
         cmp     fh,0x01
         bne     TestBTM_RBErr
         mov     fh,0x01
         btr     fh,4
         bc      TestBTM_RBErr
         cmp     fh,0x01
         bne     TestBTM_RBErr
         mov     fh,0x01
         bts     fh,4
         bc      TestBTM_RBErr
         cmp     fh,0x11
         bne     TestBTM_RBErr
                 
         mov     awx,esp
         mov     gh,0x01
         mov     [awx+1],gh
         bt      [awx+1],5
         bc      TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0x01
         bne     TestBTM_RBErr
         mov     gh,0x01
         mov     [awx+1],gh
         btr     [awx+1],5
         bc      TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0x01
         bne     TestBTM_RBErr
         mov     gh,0x01
         mov     [awx+1],gh
         bts     [awx+1],5
         bc      TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0x21
         bne     TestBTM_RBErr
                 
         mov     gh,0x01
         bt      gh,5
         bc      TestBTM_RBErr
         cmp     gh,0x01
         bne     TestBTM_RBErr
         mov     gh,0x01
         btr     gh,5
         bc      TestBTM_RBErr
         cmp     gh,0x01
         bne     TestBTM_RBErr
         mov     gh,0x01
         bts     gh,5
         bc      TestBTM_RBErr
         cmp     gh,0x21
         bne     TestBTM_RBErr
                 
         mov     bwx,esp
         mov     al,0x01
         mov     [bwx+2],al
         bt      [bwx+2],6
         bc      TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0x01
         bne     TestBTM_RBErr
         mov     al,0x01
         mov     [bwx+2],al
         btr     [bwx+2],6
         bc      TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0x01
         bne     TestBTM_RBErr
         mov     al,0x01
         mov     [bwx+2],al
         bts     [bwx+2],6
         bc      TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0x41
         bne     TestBTM_RBErr
                 
         mov     al,0x01
         bt      al,6
         bc      TestBTM_RBErr
         cmp     al,0x01
         bne     TestBTM_RBErr
         mov     al,0x01
         btr     al,6
         bc      TestBTM_RBErr
         cmp     al,0x01
         bne     TestBTM_RBErr
         mov     al,0x01
         bts     al,6
         bc      TestBTM_RBErr
         cmp     al,0x41
         bne     TestBTM_RBErr
                 
         mov     cwx,esp
         mov     bl,0x01
         mov     [cwx+3],bl
         bt      [cwx+3],7
         bc      TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x01
         bne     TestBTM_RBErr
         mov     bl,0x01
         mov     [cwx+3],bl
         btr     [cwx+3],7
         bc      TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x01
         bne     TestBTM_RBErr
         mov     bl,0x01
         mov     [cwx+3],bl
         bts     [cwx+3],7
         bc      TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x81
         bne     TestBTM_RBErr
                 
         mov     bl,0x01
         bt      bl,7
         bc      TestBTM_RBErr
         cmp     bl,0x01
         bne     TestBTM_RBErr
         mov     bl,0x01
         btr     bl,7
         bc      TestBTM_RBErr
         cmp     bl,0x01
         bne     TestBTM_RBErr
         mov     bl,0x01
         bts     bl,7
         bc      TestBTM_RBErr
         cmp     bl,0x81
         bne     TestBTM_RBErr
                 
         mov     dwx,esp
         mov     cl,0x07
         mov     [dwx+0],cl
         bt      [dwx+0],0
         bnc     TestBTM_RBErr
         mov     cl,[dwx+0]
         cmp     cl,0x07
         bne     TestBTM_RBErr
         mov     cl,0x07
         mov     [dwx+0],cl
         btr     [dwx+0],0
         bnc     TestBTM_RBErr
         mov     cl,[dwx+0]
         cmp     cl,0x06
         bne     TestBTM_RBErr
         mov     cl,0x07
         mov     [dwx+0],cl
         bts     [dwx+0],0
         bnc     TestBTM_RBErr
         mov     cl,[dwx+0]
         cmp     cl,0x07
         bne     TestBTM_RBErr
                 
         mov     cl,0x07
         bt      cl,0
         bnc     TestBTM_RBErr
         cmp     cl,0x07
         bne     TestBTM_RBErr
         mov     cl,0x07
         btr     cl,0
         bnc     TestBTM_RBErr
         cmp     cl,0x06
         bne     TestBTM_RBErr
         mov     cl,0x07
         bts     cl,0
         bnc     TestBTM_RBErr
         cmp     cl,0x07
         bne     TestBTM_RBErr
                 
         mov     ewx,esp
         mov     dl,0x07
         mov     [ewx+1],dl
         bt      [ewx+1],1
         bnc     TestBTM_RBErr
         mov     dl,[ewx+1]
         cmp     dl,0x07
         bne     TestBTM_RBErr
         mov     dl,0x07
         mov     [ewx+1],dl
         btr     [ewx+1],1
         bnc     TestBTM_RBErr
         mov     dl,[ewx+1]
         cmp     dl,0x05
         bne     TestBTM_RBErr
         mov     dl,0x07
         mov     [ewx+1],dl
         bts     [ewx+1],1
         bnc     TestBTM_RBErr
         mov     dl,[ewx+1]
         cmp     dl,0x07
         bne     TestBTM_RBErr
                 
         mov     dl,0x07
         bt      dl,1
         bnc     TestBTM_RBErr
         cmp     dl,0x07
         bne     TestBTM_RBErr
         mov     dl,0x07
         btr     dl,1
         bnc     TestBTM_RBErr
         cmp     dl,0x05
         bne     TestBTM_RBErr
         mov     dl,0x07
         bts     dl,1
         bnc     TestBTM_RBErr
         cmp     dl,0x07
         bne     TestBTM_RBErr
                 
         mov     fwx,esp
         mov     el,0x07
         mov     [fwx+2],el
         bt      [fwx+2],2
         bnc     TestBTM_RBErr
         mov     el,[fwx+2]
         cmp     el,0x07
         bne     TestBTM_RBErr
         mov     el,0x07
         mov     [fwx+2],el
         btr     [fwx+2],2
         bnc     TestBTM_RBErr
         mov     el,[fwx+2]
         cmp     el,0x03
         bne     TestBTM_RBErr
         mov     el,0x07
         mov     [fwx+2],el
         bts     [fwx+2],2
         bnc     TestBTM_RBErr
         mov     el,[fwx+2]
         cmp     el,0x07
         bne     TestBTM_RBErr
                 
         mov     el,0x07
         bt      el,2
         bnc     TestBTM_RBErr
         cmp     el,0x07
         bne     TestBTM_RBErr
         mov     el,0x07
         btr     el,2
         bnc     TestBTM_RBErr
         cmp     el,0x03
         bne     TestBTM_RBErr
         mov     el,0x07
         bts     el,2
         bnc     TestBTM_RBErr
         cmp     el,0x07
         bne     TestBTM_RBErr
                 
         mov     gwx,esp
         mov     fl,0x07
         mov     [gwx+3],fl
         bt      [gwx+3],3
         bc      TestBTM_RBErr
         mov     fl,[gwx+3]
         cmp     fl,0x07
         bne     TestBTM_RBErr
         mov     fl,0x07
         mov     [gwx+3],fl
         btr     [gwx+3],3
         bc      TestBTM_RBErr
         mov     fl,[gwx+3]
         cmp     fl,0x07
         bne     TestBTM_RBErr
         mov     fl,0x07
         mov     [gwx+3],fl
         bts     [gwx+3],3
         bc      TestBTM_RBErr
         mov     fl,[gwx+3]
         cmp     fl,0x0F
         bne     TestBTM_RBErr
                 
         mov     fl,0x07
         bt      fl,3
         bc      TestBTM_RBErr
         cmp     fl,0x07
         bne     TestBTM_RBErr
         mov     fl,0x07
         btr     fl,3
         bc      TestBTM_RBErr
         cmp     fl,0x07
         bne     TestBTM_RBErr
         mov     fl,0x07
         bts     fl,3
         bc      TestBTM_RBErr
         cmp     fl,0x0F
         bne     TestBTM_RBErr
                 
         mov     ar,esp
         mov     gl,0x07
         mov     [ar+0],gl
         bt      [ar+0],4
         bc      TestBTM_RBErr
         mov     gl,[ar+0]
         cmp     gl,0x07
         bne     TestBTM_RBErr
         mov     gl,0x07
         mov     [ar+0],gl
         btr     [ar+0],4
         bc      TestBTM_RBErr
         mov     gl,[ar+0]
         cmp     gl,0x07
         bne     TestBTM_RBErr
         mov     gl,0x07
         mov     [ar+0],gl
         bts     [ar+0],4
         bc      TestBTM_RBErr
         mov     gl,[ar+0]
         cmp     gl,0x17
         bne     TestBTM_RBErr
                 
         mov     gl,0x07
         bt      gl,4
         bc      TestBTM_RBErr
         cmp     gl,0x07
         bne     TestBTM_RBErr
         mov     gl,0x07
         btr     gl,4
         bc      TestBTM_RBErr
         cmp     gl,0x07
         bne     TestBTM_RBErr
         mov     gl,0x07
         bts     gl,4
         bc      TestBTM_RBErr
         cmp     gl,0x17
         bne     TestBTM_RBErr
                 
         mov     br,esp
         mov     ah,0x07
         mov     [br+1],ah
         bt      [br+1],5
         bc      TestBTM_RBErr
         mov     ah,[br+1]
         cmp     ah,0x07
         bne     TestBTM_RBErr
         mov     ah,0x07
         mov     [br+1],ah
         btr     [br+1],5
         bc      TestBTM_RBErr
         mov     ah,[br+1]
         cmp     ah,0x07
         bne     TestBTM_RBErr
         mov     ah,0x07
         mov     [br+1],ah
         bts     [br+1],5
         bc      TestBTM_RBErr
         mov     ah,[br+1]
         cmp     ah,0x27
         bne     TestBTM_RBErr
                 
         mov     ah,0x07
         bt      ah,5
         bc      TestBTM_RBErr
         cmp     ah,0x07
         bne     TestBTM_RBErr
         mov     ah,0x07
         btr     ah,5
         bc      TestBTM_RBErr
         cmp     ah,0x07
         bne     TestBTM_RBErr
         mov     ah,0x07
         bts     ah,5
         bc      TestBTM_RBErr
         cmp     ah,0x27
         bne     TestBTM_RBErr
                 
         mov     cr,esp
         mov     bh,0x07
         mov     [cr+2],bh
         bt      [cr+2],6
         bc      TestBTM_RBErr
         mov     bh,[cr+2]
         cmp     bh,0x07
         bne     TestBTM_RBErr
         mov     bh,0x07
         mov     [cr+2],bh
         btr     [cr+2],6
         bc      TestBTM_RBErr
         mov     bh,[cr+2]
         cmp     bh,0x07
         bne     TestBTM_RBErr
         mov     bh,0x07
         mov     [cr+2],bh
         bts     [cr+2],6
         bc      TestBTM_RBErr
         mov     bh,[cr+2]
         cmp     bh,0x47
         bne     TestBTM_RBErr
                 
         mov     bh,0x07
         bt      bh,6
         bc      TestBTM_RBErr
         cmp     bh,0x07
         bne     TestBTM_RBErr
         mov     bh,0x07
         btr     bh,6
         bc      TestBTM_RBErr
         cmp     bh,0x07
         bne     TestBTM_RBErr
         mov     bh,0x07
         bts     bh,6
         bc      TestBTM_RBErr
         cmp     bh,0x47
         bne     TestBTM_RBErr
                 
         mov     dr,esp
         mov     ch,0x07
         mov     [dr+3],ch
         bt      [dr+3],7
         bc      TestBTM_RBErr
         mov     ch,[dr+3]
         cmp     ch,0x07
         bne     TestBTM_RBErr
         mov     ch,0x07
         mov     [dr+3],ch
         btr     [dr+3],7
         bc      TestBTM_RBErr
         mov     ch,[dr+3]
         cmp     ch,0x07
         bne     TestBTM_RBErr
         mov     ch,0x07
         mov     [dr+3],ch
         bts     [dr+3],7
         bc      TestBTM_RBErr
         mov     ch,[dr+3]
         cmp     ch,0x87
         bne     TestBTM_RBErr
                 
         mov     ch,0x07
         bt      ch,7
         bc      TestBTM_RBErr
         cmp     ch,0x07
         bne     TestBTM_RBErr
         mov     ch,0x07
         btr     ch,7
         bc      TestBTM_RBErr
         cmp     ch,0x07
         bne     TestBTM_RBErr
         mov     ch,0x07
         bts     ch,7
         bc      TestBTM_RBErr
         cmp     ch,0x87
         bne     TestBTM_RBErr
                 
         mov     er,esp
         mov     dh,0x08
         mov     [er+0],dh
         bt      [er+0],0
         bc      TestBTM_RBErr
         mov     dh,[er+0]
         cmp     dh,0x08
         bne     TestBTM_RBErr
         mov     dh,0x08
         mov     [er+0],dh
         btr     [er+0],0
         bc      TestBTM_RBErr
         mov     dh,[er+0]
         cmp     dh,0x08
         bne     TestBTM_RBErr
         mov     dh,0x08
         mov     [er+0],dh
         bts     [er+0],0
         bc      TestBTM_RBErr
         mov     dh,[er+0]
         cmp     dh,0x09
         bne     TestBTM_RBErr
                 
         mov     dh,0x08
         bt      dh,0
         bc      TestBTM_RBErr
         cmp     dh,0x08
         bne     TestBTM_RBErr
         mov     dh,0x08
         btr     dh,0
         bc      TestBTM_RBErr
         cmp     dh,0x08
         bne     TestBTM_RBErr
         mov     dh,0x08
         bts     dh,0
         bc      TestBTM_RBErr
         cmp     dh,0x09
         bne     TestBTM_RBErr
                 
         mov     fr,esp
         mov     eh,0x08
         mov     [fr+1],eh
         bt      [fr+1],1
         bc      TestBTM_RBErr
         mov     eh,[fr+1]
         cmp     eh,0x08
         bne     TestBTM_RBErr
         mov     eh,0x08
         mov     [fr+1],eh
         btr     [fr+1],1
         bc      TestBTM_RBErr
         mov     eh,[fr+1]
         cmp     eh,0x08
         bne     TestBTM_RBErr
         mov     eh,0x08
         mov     [fr+1],eh
         bts     [fr+1],1
         bc      TestBTM_RBErr
         mov     eh,[fr+1]
         cmp     eh,0x0A
         bne     TestBTM_RBErr
                 
         mov     eh,0x08
         bt      eh,1
         bc      TestBTM_RBErr
         cmp     eh,0x08
         bne     TestBTM_RBErr
         mov     eh,0x08
         btr     eh,1
         bc      TestBTM_RBErr
         cmp     eh,0x08
         bne     TestBTM_RBErr
         mov     eh,0x08
         bts     eh,1
         bc      TestBTM_RBErr
         cmp     eh,0x0A
         bne     TestBTM_RBErr
                 
         mov     gr,esp
         mov     fh,0x08
         mov     [gr+2],fh
         bt      [gr+2],2
         bc      TestBTM_RBErr
         mov     fh,[gr+2]
         cmp     fh,0x08
         bne     TestBTM_RBErr
         mov     fh,0x08
         mov     [gr+2],fh
         btr     [gr+2],2
         bc      TestBTM_RBErr
         mov     fh,[gr+2]
         cmp     fh,0x08
         bne     TestBTM_RBErr
         mov     fh,0x08
         mov     [gr+2],fh
         bts     [gr+2],2
         bc      TestBTM_RBErr
         mov     fh,[gr+2]
         cmp     fh,0x0C
         bne     TestBTM_RBErr
                 
         mov     fh,0x08
         bt      fh,2
         bc      TestBTM_RBErr
         cmp     fh,0x08
         bne     TestBTM_RBErr
         mov     fh,0x08
         btr     fh,2
         bc      TestBTM_RBErr
         cmp     fh,0x08
         bne     TestBTM_RBErr
         mov     fh,0x08
         bts     fh,2
         bc      TestBTM_RBErr
         cmp     fh,0x0C
         bne     TestBTM_RBErr
                 
         mov     awx,esp
         mov     gh,0x08
         mov     [awx+3],gh
         bt      [awx+3],3
         bnc     TestBTM_RBErr
         mov     gh,[awx+3]
         cmp     gh,0x08
         bne     TestBTM_RBErr
         mov     gh,0x08
         mov     [awx+3],gh
         btr     [awx+3],3
         bnc     TestBTM_RBErr
         mov     gh,[awx+3]
         cmp     gh,0x00
         bne     TestBTM_RBErr
         mov     gh,0x08
         mov     [awx+3],gh
         bts     [awx+3],3
         bnc     TestBTM_RBErr
         mov     gh,[awx+3]
         cmp     gh,0x08
         bne     TestBTM_RBErr
                 
         mov     gh,0x08
         bt      gh,3
         bnc     TestBTM_RBErr
         cmp     gh,0x08
         bne     TestBTM_RBErr
         mov     gh,0x08
         btr     gh,3
         bnc     TestBTM_RBErr
         cmp     gh,0x00
         bne     TestBTM_RBErr
         mov     gh,0x08
         bts     gh,3
         bnc     TestBTM_RBErr
         cmp     gh,0x08
         bne     TestBTM_RBErr
                 
         mov     bwx,esp
         mov     al,0x08
         mov     [bwx+0],al
         bt      [bwx+0],4
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x08
         bne     TestBTM_RBErr
         mov     al,0x08
         mov     [bwx+0],al
         btr     [bwx+0],4
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x08
         bne     TestBTM_RBErr
         mov     al,0x08
         mov     [bwx+0],al
         bts     [bwx+0],4
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x18
         bne     TestBTM_RBErr
                 
         mov     al,0x08
         bt      al,4
         bc      TestBTM_RBErr
         cmp     al,0x08
         bne     TestBTM_RBErr
         mov     al,0x08
         btr     al,4
         bc      TestBTM_RBErr
         cmp     al,0x08
         bne     TestBTM_RBErr
         mov     al,0x08
         bts     al,4
         bc      TestBTM_RBErr
         cmp     al,0x18
         bne     TestBTM_RBErr
                 
         mov     cwx,esp
         mov     bl,0x08
         mov     [cwx+1],bl
         bt      [cwx+1],5
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x08
         bne     TestBTM_RBErr
         mov     bl,0x08
         mov     [cwx+1],bl
         btr     [cwx+1],5
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x08
         bne     TestBTM_RBErr
         mov     bl,0x08
         mov     [cwx+1],bl
         bts     [cwx+1],5
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x28
         bne     TestBTM_RBErr
                 
         mov     bl,0x08
         bt      bl,5
         bc      TestBTM_RBErr
         cmp     bl,0x08
         bne     TestBTM_RBErr
         mov     bl,0x08
         btr     bl,5
         bc      TestBTM_RBErr
         cmp     bl,0x08
         bne     TestBTM_RBErr
         mov     bl,0x08
         bts     bl,5
         bc      TestBTM_RBErr
         cmp     bl,0x28
         bne     TestBTM_RBErr
                 
         mov     dwx,esp
         mov     cl,0x08
         mov     [dwx+2],cl
         bt      [dwx+2],6
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x08
         bne     TestBTM_RBErr
         mov     cl,0x08
         mov     [dwx+2],cl
         btr     [dwx+2],6
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x08
         bne     TestBTM_RBErr
         mov     cl,0x08
         mov     [dwx+2],cl
         bts     [dwx+2],6
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x48
         bne     TestBTM_RBErr
                 
         mov     cl,0x08
         bt      cl,6
         bc      TestBTM_RBErr
         cmp     cl,0x08
         bne     TestBTM_RBErr
         mov     cl,0x08
         btr     cl,6
         bc      TestBTM_RBErr
         cmp     cl,0x08
         bne     TestBTM_RBErr
         mov     cl,0x08
         bts     cl,6
         bc      TestBTM_RBErr
         cmp     cl,0x48
         bne     TestBTM_RBErr
                 
         mov     ewx,esp
         mov     dl,0x08
         mov     [ewx+3],dl
         bt      [ewx+3],7
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x08
         bne     TestBTM_RBErr
         mov     dl,0x08
         mov     [ewx+3],dl
         btr     [ewx+3],7
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x08
         bne     TestBTM_RBErr
         mov     dl,0x08
         mov     [ewx+3],dl
         bts     [ewx+3],7
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x88
         bne     TestBTM_RBErr
                 
         mov     dl,0x08
         bt      dl,7
         bc      TestBTM_RBErr
         cmp     dl,0x08
         bne     TestBTM_RBErr
         mov     dl,0x08
         btr     dl,7
         bc      TestBTM_RBErr
         cmp     dl,0x08
         bne     TestBTM_RBErr
         mov     dl,0x08
         bts     dl,7
         bc      TestBTM_RBErr
         cmp     dl,0x88
         bne     TestBTM_RBErr
                 
         mov     fwx,esp
         mov     el,0x09
         mov     [fwx+0],el
         bt      [fwx+0],0
         bnc     TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x09
         bne     TestBTM_RBErr
         mov     el,0x09
         mov     [fwx+0],el
         btr     [fwx+0],0
         bnc     TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x08
         bne     TestBTM_RBErr
         mov     el,0x09
         mov     [fwx+0],el
         bts     [fwx+0],0
         bnc     TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x09
         bne     TestBTM_RBErr
                 
         mov     el,0x09
         bt      el,0
         bnc     TestBTM_RBErr
         cmp     el,0x09
         bne     TestBTM_RBErr
         mov     el,0x09
         btr     el,0
         bnc     TestBTM_RBErr
         cmp     el,0x08
         bne     TestBTM_RBErr
         mov     el,0x09
         bts     el,0
         bnc     TestBTM_RBErr
         cmp     el,0x09
         bne     TestBTM_RBErr
                 
         mov     gwx,esp
         mov     fl,0x09
         mov     [gwx+1],fl
         bt      [gwx+1],1
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x09
         bne     TestBTM_RBErr
         mov     fl,0x09
         mov     [gwx+1],fl
         btr     [gwx+1],1
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x09
         bne     TestBTM_RBErr
         mov     fl,0x09
         mov     [gwx+1],fl
         bts     [gwx+1],1
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x0B
         bne     TestBTM_RBErr
                 
         mov     fl,0x09
         bt      fl,1
         bc      TestBTM_RBErr
         cmp     fl,0x09
         bne     TestBTM_RBErr
         mov     fl,0x09
         btr     fl,1
         bc      TestBTM_RBErr
         cmp     fl,0x09
         bne     TestBTM_RBErr
         mov     fl,0x09
         bts     fl,1
         bc      TestBTM_RBErr
         cmp     fl,0x0B
         bne     TestBTM_RBErr
                 
         mov     ar,esp
         mov     gl,0x09
         mov     [ar+2],gl
         bt      [ar+2],2
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x09
         bne     TestBTM_RBErr
         mov     gl,0x09
         mov     [ar+2],gl
         btr     [ar+2],2
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x09
         bne     TestBTM_RBErr
         mov     gl,0x09
         mov     [ar+2],gl
         bts     [ar+2],2
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x0D
         bne     TestBTM_RBErr
                 
         mov     gl,0x09
         bt      gl,2
         bc      TestBTM_RBErr
         cmp     gl,0x09
         bne     TestBTM_RBErr
         mov     gl,0x09
         btr     gl,2
         bc      TestBTM_RBErr
         cmp     gl,0x09
         bne     TestBTM_RBErr
         mov     gl,0x09
         bts     gl,2
         bc      TestBTM_RBErr
         cmp     gl,0x0D
         bne     TestBTM_RBErr
                 
         mov     br,esp
         mov     ah,0x09
         mov     [br+3],ah
         bt      [br+3],3
         bnc     TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x09
         bne     TestBTM_RBErr
         mov     ah,0x09
         mov     [br+3],ah
         btr     [br+3],3
         bnc     TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x01
         bne     TestBTM_RBErr
         mov     ah,0x09
         mov     [br+3],ah
         bts     [br+3],3
         bnc     TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x09
         bne     TestBTM_RBErr
                 
         mov     ah,0x09
         bt      ah,3
         bnc     TestBTM_RBErr
         cmp     ah,0x09
         bne     TestBTM_RBErr
         mov     ah,0x09
         btr     ah,3
         bnc     TestBTM_RBErr
         cmp     ah,0x01
         bne     TestBTM_RBErr
         mov     ah,0x09
         bts     ah,3
         bnc     TestBTM_RBErr
         cmp     ah,0x09
         bne     TestBTM_RBErr
                 
         mov     cr,esp
         mov     bh,0x09
         mov     [cr+0],bh
         bt      [cr+0],4
         bc      TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0x09
         bne     TestBTM_RBErr
         mov     bh,0x09
         mov     [cr+0],bh
         btr     [cr+0],4
         bc      TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0x09
         bne     TestBTM_RBErr
         mov     bh,0x09
         mov     [cr+0],bh
         bts     [cr+0],4
         bc      TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0x19
         bne     TestBTM_RBErr
                 
         mov     bh,0x09
         bt      bh,4
         bc      TestBTM_RBErr
         cmp     bh,0x09
         bne     TestBTM_RBErr
         mov     bh,0x09
         btr     bh,4
         bc      TestBTM_RBErr
         cmp     bh,0x09
         bne     TestBTM_RBErr
         mov     bh,0x09
         bts     bh,4
         bc      TestBTM_RBErr
         cmp     bh,0x19
         bne     TestBTM_RBErr
                 
         mov     dr,esp
         mov     ch,0x09
         mov     [dr+1],ch
         bt      [dr+1],5
         bc      TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0x09
         bne     TestBTM_RBErr
         mov     ch,0x09
         mov     [dr+1],ch
         btr     [dr+1],5
         bc      TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0x09
         bne     TestBTM_RBErr
         mov     ch,0x09
         mov     [dr+1],ch
         bts     [dr+1],5
         bc      TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0x29
         bne     TestBTM_RBErr
                 
         mov     ch,0x09
         bt      ch,5
         bc      TestBTM_RBErr
         cmp     ch,0x09
         bne     TestBTM_RBErr
         mov     ch,0x09
         btr     ch,5
         bc      TestBTM_RBErr
         cmp     ch,0x09
         bne     TestBTM_RBErr
         mov     ch,0x09
         bts     ch,5
         bc      TestBTM_RBErr
         cmp     ch,0x29
         bne     TestBTM_RBErr
                 
         mov     er,esp
         mov     dh,0x09
         mov     [er+2],dh
         bt      [er+2],6
         bc      TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0x09
         bne     TestBTM_RBErr
         mov     dh,0x09
         mov     [er+2],dh
         btr     [er+2],6
         bc      TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0x09
         bne     TestBTM_RBErr
         mov     dh,0x09
         mov     [er+2],dh
         bts     [er+2],6
         bc      TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0x49
         bne     TestBTM_RBErr
                 
         mov     dh,0x09
         bt      dh,6
         bc      TestBTM_RBErr
         cmp     dh,0x09
         bne     TestBTM_RBErr
         mov     dh,0x09
         btr     dh,6
         bc      TestBTM_RBErr
         cmp     dh,0x09
         bne     TestBTM_RBErr
         mov     dh,0x09
         bts     dh,6
         bc      TestBTM_RBErr
         cmp     dh,0x49
         bne     TestBTM_RBErr
                 
         mov     fr,esp
         mov     eh,0x09
         mov     [fr+3],eh
         bt      [fr+3],7
         bc      TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0x09
         bne     TestBTM_RBErr
         mov     eh,0x09
         mov     [fr+3],eh
         btr     [fr+3],7
         bc      TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0x09
         bne     TestBTM_RBErr
         mov     eh,0x09
         mov     [fr+3],eh
         bts     [fr+3],7
         bc      TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0x89
         bne     TestBTM_RBErr
                 
         mov     eh,0x09
         bt      eh,7
         bc      TestBTM_RBErr
         cmp     eh,0x09
         bne     TestBTM_RBErr
         mov     eh,0x09
         btr     eh,7
         bc      TestBTM_RBErr
         cmp     eh,0x09
         bne     TestBTM_RBErr
         mov     eh,0x09
         bts     eh,7
         bc      TestBTM_RBErr
         cmp     eh,0x89
         bne     TestBTM_RBErr
                 
         mov     gr,esp
         mov     fh,0x0F
         mov     [gr+0],fh
         bt      [gr+0],0
         bnc     TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0x0F
         bne     TestBTM_RBErr
         mov     fh,0x0F
         mov     [gr+0],fh
         btr     [gr+0],0
         bnc     TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0x0E
         bne     TestBTM_RBErr
         mov     fh,0x0F
         mov     [gr+0],fh
         bts     [gr+0],0
         bnc     TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0x0F
         bne     TestBTM_RBErr
                 
         mov     fh,0x0F
         bt      fh,0
         bnc     TestBTM_RBErr
         cmp     fh,0x0F
         bne     TestBTM_RBErr
         mov     fh,0x0F
         btr     fh,0
         bnc     TestBTM_RBErr
         cmp     fh,0x0E
         bne     TestBTM_RBErr
         mov     fh,0x0F
         bts     fh,0
         bnc     TestBTM_RBErr
         cmp     fh,0x0F
         bne     TestBTM_RBErr
                 
         mov     awx,esp
         mov     gh,0x0F
         mov     [awx+1],gh
         bt      [awx+1],1
         bnc     TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0x0F
         bne     TestBTM_RBErr
         mov     gh,0x0F
         mov     [awx+1],gh
         btr     [awx+1],1
         bnc     TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0x0D
         bne     TestBTM_RBErr
         mov     gh,0x0F
         mov     [awx+1],gh
         bts     [awx+1],1
         bnc     TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0x0F
         bne     TestBTM_RBErr
                 
         mov     gh,0x0F
         bt      gh,1
         bnc     TestBTM_RBErr
         cmp     gh,0x0F
         bne     TestBTM_RBErr
         mov     gh,0x0F
         btr     gh,1
         bnc     TestBTM_RBErr
         cmp     gh,0x0D
         bne     TestBTM_RBErr
         mov     gh,0x0F
         bts     gh,1
         bnc     TestBTM_RBErr
         cmp     gh,0x0F
         bne     TestBTM_RBErr
                 
         mov     bwx,esp
         mov     al,0x0F
         mov     [bwx+2],al
         bt      [bwx+2],2
         bnc     TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0x0F
         bne     TestBTM_RBErr
         mov     al,0x0F
         mov     [bwx+2],al
         btr     [bwx+2],2
         bnc     TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0x0B
         bne     TestBTM_RBErr
         mov     al,0x0F
         mov     [bwx+2],al
         bts     [bwx+2],2
         bnc     TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0x0F
         bne     TestBTM_RBErr
                 
         mov     al,0x0F
         bt      al,2
         bnc     TestBTM_RBErr
         cmp     al,0x0F
         bne     TestBTM_RBErr
         mov     al,0x0F
         btr     al,2
         bnc     TestBTM_RBErr
         cmp     al,0x0B
         bne     TestBTM_RBErr
         mov     al,0x0F
         bts     al,2
         bnc     TestBTM_RBErr
         cmp     al,0x0F
         bne     TestBTM_RBErr
                 
         mov     cwx,esp
         mov     bl,0x0F
         mov     [cwx+3],bl
         bt      [cwx+3],3
         bnc     TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x0F
         bne     TestBTM_RBErr
         mov     bl,0x0F
         mov     [cwx+3],bl
         btr     [cwx+3],3
         bnc     TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x07
         bne     TestBTM_RBErr
         mov     bl,0x0F
         mov     [cwx+3],bl
         bts     [cwx+3],3
         bnc     TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x0F
         bne     TestBTM_RBErr
                 
         mov     bl,0x0F
         bt      bl,3
         bnc     TestBTM_RBErr
         cmp     bl,0x0F
         bne     TestBTM_RBErr
         mov     bl,0x0F
         btr     bl,3
         bnc     TestBTM_RBErr
         cmp     bl,0x07
         bne     TestBTM_RBErr
         mov     bl,0x0F
         bts     bl,3
         bnc     TestBTM_RBErr
         cmp     bl,0x0F
         bne     TestBTM_RBErr
                 
         mov     dwx,esp
         mov     cl,0x0F
         mov     [dwx+0],cl
         bt      [dwx+0],4
         bc      TestBTM_RBErr
         mov     cl,[dwx+0]
         cmp     cl,0x0F
         bne     TestBTM_RBErr
         mov     cl,0x0F
         mov     [dwx+0],cl
         btr     [dwx+0],4
         bc      TestBTM_RBErr
         mov     cl,[dwx+0]
         cmp     cl,0x0F
         bne     TestBTM_RBErr
         mov     cl,0x0F
         mov     [dwx+0],cl
         bts     [dwx+0],4
         bc      TestBTM_RBErr
         mov     cl,[dwx+0]
         cmp     cl,0x1F
         bne     TestBTM_RBErr
                 
         mov     cl,0x0F
         bt      cl,4
         bc      TestBTM_RBErr
         cmp     cl,0x0F
         bne     TestBTM_RBErr
         mov     cl,0x0F
         btr     cl,4
         bc      TestBTM_RBErr
         cmp     cl,0x0F
         bne     TestBTM_RBErr
         mov     cl,0x0F
         bts     cl,4
         bc      TestBTM_RBErr
         cmp     cl,0x1F
         bne     TestBTM_RBErr
                 
         mov     ewx,esp
         mov     dl,0x0F
         mov     [ewx+1],dl
         bt      [ewx+1],5
         bc      TestBTM_RBErr
         mov     dl,[ewx+1]
         cmp     dl,0x0F
         bne     TestBTM_RBErr
         mov     dl,0x0F
         mov     [ewx+1],dl
         btr     [ewx+1],5
         bc      TestBTM_RBErr
         mov     dl,[ewx+1]
         cmp     dl,0x0F
         bne     TestBTM_RBErr
         mov     dl,0x0F
         mov     [ewx+1],dl
         bts     [ewx+1],5
         bc      TestBTM_RBErr
         mov     dl,[ewx+1]
         cmp     dl,0x2F
         bne     TestBTM_RBErr
                 
         mov     dl,0x0F
         bt      dl,5
         bc      TestBTM_RBErr
         cmp     dl,0x0F
         bne     TestBTM_RBErr
         mov     dl,0x0F
         btr     dl,5
         bc      TestBTM_RBErr
         cmp     dl,0x0F
         bne     TestBTM_RBErr
         mov     dl,0x0F
         bts     dl,5
         bc      TestBTM_RBErr
         cmp     dl,0x2F
         bne     TestBTM_RBErr
                 
         mov     fwx,esp
         mov     el,0x0F
         mov     [fwx+2],el
         bt      [fwx+2],6
         bc      TestBTM_RBErr
         mov     el,[fwx+2]
         cmp     el,0x0F
         bne     TestBTM_RBErr
         mov     el,0x0F
         mov     [fwx+2],el
         btr     [fwx+2],6
         bc      TestBTM_RBErr
         mov     el,[fwx+2]
         cmp     el,0x0F
         bne     TestBTM_RBErr
         mov     el,0x0F
         mov     [fwx+2],el
         bts     [fwx+2],6
         bc      TestBTM_RBErr
         mov     el,[fwx+2]
         cmp     el,0x4F
         bne     TestBTM_RBErr
                 
         mov     el,0x0F
         bt      el,6
         bc      TestBTM_RBErr
         cmp     el,0x0F
         bne     TestBTM_RBErr
         mov     el,0x0F
         btr     el,6
         bc      TestBTM_RBErr
         cmp     el,0x0F
         bne     TestBTM_RBErr
         mov     el,0x0F
         bts     el,6
         bc      TestBTM_RBErr
         cmp     el,0x4F
         bne     TestBTM_RBErr
                 
         mov     gwx,esp
         mov     fl,0x0F
         mov     [gwx+3],fl
         bt      [gwx+3],7
         bc      TestBTM_RBErr
         mov     fl,[gwx+3]
         cmp     fl,0x0F
         bne     TestBTM_RBErr
         mov     fl,0x0F
         mov     [gwx+3],fl
         btr     [gwx+3],7
         bc      TestBTM_RBErr
         mov     fl,[gwx+3]
         cmp     fl,0x0F
         bne     TestBTM_RBErr
         mov     fl,0x0F
         mov     [gwx+3],fl
         bts     [gwx+3],7
         bc      TestBTM_RBErr
         mov     fl,[gwx+3]
         cmp     fl,0x8F
         bne     TestBTM_RBErr
                 
         mov     fl,0x0F
         bt      fl,7
         bc      TestBTM_RBErr
         cmp     fl,0x0F
         bne     TestBTM_RBErr
         mov     fl,0x0F
         btr     fl,7
         bc      TestBTM_RBErr
         cmp     fl,0x0F
         bne     TestBTM_RBErr
         mov     fl,0x0F
         bts     fl,7
         bc      TestBTM_RBErr
         cmp     fl,0x8F
         bne     TestBTM_RBErr
                 
         mov     ar,esp
         mov     gl,0x7F
         mov     [ar+0],gl
         bt      [ar+0],0
         bnc     TestBTM_RBErr
         mov     gl,[ar+0]
         cmp     gl,0x7F
         bne     TestBTM_RBErr
         mov     gl,0x7F
         mov     [ar+0],gl
         btr     [ar+0],0
         bnc     TestBTM_RBErr
         mov     gl,[ar+0]
         cmp     gl,0x7E
         bne     TestBTM_RBErr
         mov     gl,0x7F
         mov     [ar+0],gl
         bts     [ar+0],0
         bnc     TestBTM_RBErr
         mov     gl,[ar+0]
         cmp     gl,0x7F
         bne     TestBTM_RBErr
                 
         mov     gl,0x7F
         bt      gl,0
         bnc     TestBTM_RBErr
         cmp     gl,0x7F
         bne     TestBTM_RBErr
         mov     gl,0x7F
         btr     gl,0
         bnc     TestBTM_RBErr
         cmp     gl,0x7E
         bne     TestBTM_RBErr
         mov     gl,0x7F
         bts     gl,0
         bnc     TestBTM_RBErr
         cmp     gl,0x7F
         bne     TestBTM_RBErr
                 
         mov     br,esp
         mov     ah,0x7F
         mov     [br+1],ah
         bt      [br+1],1
         bnc     TestBTM_RBErr
         mov     ah,[br+1]
         cmp     ah,0x7F
         bne     TestBTM_RBErr
         mov     ah,0x7F
         mov     [br+1],ah
         btr     [br+1],1
         bnc     TestBTM_RBErr
         mov     ah,[br+1]
         cmp     ah,0x7D
         bne     TestBTM_RBErr
         mov     ah,0x7F
         mov     [br+1],ah
         bts     [br+1],1
         bnc     TestBTM_RBErr
         mov     ah,[br+1]
         cmp     ah,0x7F
         bne     TestBTM_RBErr
                 
         mov     ah,0x7F
         bt      ah,1
         bnc     TestBTM_RBErr
         cmp     ah,0x7F
         bne     TestBTM_RBErr
         mov     ah,0x7F
         btr     ah,1
         bnc     TestBTM_RBErr
         cmp     ah,0x7D
         bne     TestBTM_RBErr
         mov     ah,0x7F
         bts     ah,1
         bnc     TestBTM_RBErr
         cmp     ah,0x7F
         bne     TestBTM_RBErr
                 
         mov     cr,esp
         mov     bh,0x7F
         mov     [cr+2],bh
         bt      [cr+2],2
         bnc     TestBTM_RBErr
         mov     bh,[cr+2]
         cmp     bh,0x7F
         bne     TestBTM_RBErr
         mov     bh,0x7F
         mov     [cr+2],bh
         btr     [cr+2],2
         bnc     TestBTM_RBErr
         mov     bh,[cr+2]
         cmp     bh,0x7B
         bne     TestBTM_RBErr
         mov     bh,0x7F
         mov     [cr+2],bh
         bts     [cr+2],2
         bnc     TestBTM_RBErr
         mov     bh,[cr+2]
         cmp     bh,0x7F
         bne     TestBTM_RBErr
                 
         mov     bh,0x7F
         bt      bh,2
         bnc     TestBTM_RBErr
         cmp     bh,0x7F
         bne     TestBTM_RBErr
         mov     bh,0x7F
         btr     bh,2
         bnc     TestBTM_RBErr
         cmp     bh,0x7B
         bne     TestBTM_RBErr
         mov     bh,0x7F
         bts     bh,2
         bnc     TestBTM_RBErr
         cmp     bh,0x7F
         bne     TestBTM_RBErr
                 
         mov     dr,esp
         mov     ch,0x7F
         mov     [dr+3],ch
         bt      [dr+3],3
         bnc     TestBTM_RBErr
         mov     ch,[dr+3]
         cmp     ch,0x7F
         bne     TestBTM_RBErr
         mov     ch,0x7F
         mov     [dr+3],ch
         btr     [dr+3],3
         bnc     TestBTM_RBErr
         mov     ch,[dr+3]
         cmp     ch,0x77
         bne     TestBTM_RBErr
         mov     ch,0x7F
         mov     [dr+3],ch
         bts     [dr+3],3
         bnc     TestBTM_RBErr
         mov     ch,[dr+3]
         cmp     ch,0x7F
         bne     TestBTM_RBErr
                 
         mov     ch,0x7F
         bt      ch,3
         bnc     TestBTM_RBErr
         cmp     ch,0x7F
         bne     TestBTM_RBErr
         mov     ch,0x7F
         btr     ch,3
         bnc     TestBTM_RBErr
         cmp     ch,0x77
         bne     TestBTM_RBErr
         mov     ch,0x7F
         bts     ch,3
         bnc     TestBTM_RBErr
         cmp     ch,0x7F
         bne     TestBTM_RBErr
                 
         mov     er,esp
         mov     dh,0x7F
         mov     [er+0],dh
         bt      [er+0],4
         bnc     TestBTM_RBErr
         mov     dh,[er+0]
         cmp     dh,0x7F
         bne     TestBTM_RBErr
         mov     dh,0x7F
         mov     [er+0],dh
         btr     [er+0],4
         bnc     TestBTM_RBErr
         mov     dh,[er+0]
         cmp     dh,0x6F
         bne     TestBTM_RBErr
         mov     dh,0x7F
         mov     [er+0],dh
         bts     [er+0],4
         bnc     TestBTM_RBErr
         mov     dh,[er+0]
         cmp     dh,0x7F
         bne     TestBTM_RBErr
                 
         mov     dh,0x7F
         bt      dh,4
         bnc     TestBTM_RBErr
         cmp     dh,0x7F
         bne     TestBTM_RBErr
         mov     dh,0x7F
         btr     dh,4
         bnc     TestBTM_RBErr
         cmp     dh,0x6F
         bne     TestBTM_RBErr
         mov     dh,0x7F
         bts     dh,4
         bnc     TestBTM_RBErr
         cmp     dh,0x7F
         bne     TestBTM_RBErr
                 
         mov     fr,esp
         mov     eh,0x7F
         mov     [fr+1],eh
         bt      [fr+1],5
         bnc     TestBTM_RBErr
         mov     eh,[fr+1]
         cmp     eh,0x7F
         bne     TestBTM_RBErr
         mov     eh,0x7F
         mov     [fr+1],eh
         btr     [fr+1],5
         bnc     TestBTM_RBErr
         mov     eh,[fr+1]
         cmp     eh,0x5F
         bne     TestBTM_RBErr
         mov     eh,0x7F
         mov     [fr+1],eh
         bts     [fr+1],5
         bnc     TestBTM_RBErr
         mov     eh,[fr+1]
         cmp     eh,0x7F
         bne     TestBTM_RBErr
                 
         mov     eh,0x7F
         bt      eh,5
         bnc     TestBTM_RBErr
         cmp     eh,0x7F
         bne     TestBTM_RBErr
         mov     eh,0x7F
         btr     eh,5
         bnc     TestBTM_RBErr
         cmp     eh,0x5F
         bne     TestBTM_RBErr
         mov     eh,0x7F
         bts     eh,5
         bnc     TestBTM_RBErr
         cmp     eh,0x7F
         bne     TestBTM_RBErr
                 
         mov     gr,esp
         mov     fh,0x7F
         mov     [gr+2],fh
         bt      [gr+2],6
         bnc     TestBTM_RBErr
         mov     fh,[gr+2]
         cmp     fh,0x7F
         bne     TestBTM_RBErr
         mov     fh,0x7F
         mov     [gr+2],fh
         btr     [gr+2],6
         bnc     TestBTM_RBErr
         mov     fh,[gr+2]
         cmp     fh,0x3F
         bne     TestBTM_RBErr
         mov     fh,0x7F
         mov     [gr+2],fh
         bts     [gr+2],6
         bnc     TestBTM_RBErr
         mov     fh,[gr+2]
         cmp     fh,0x7F
         bne     TestBTM_RBErr
                 
         mov     fh,0x7F
         bt      fh,6
         bnc     TestBTM_RBErr
         cmp     fh,0x7F
         bne     TestBTM_RBErr
         mov     fh,0x7F
         btr     fh,6
         bnc     TestBTM_RBErr
         cmp     fh,0x3F
         bne     TestBTM_RBErr
         mov     fh,0x7F
         bts     fh,6
         bnc     TestBTM_RBErr
         cmp     fh,0x7F
         bne     TestBTM_RBErr
                 
         mov     awx,esp
         mov     gh,0x7F
         mov     [awx+3],gh
         bt      [awx+3],7
         bc      TestBTM_RBErr
         mov     gh,[awx+3]
         cmp     gh,0x7F
         bne     TestBTM_RBErr
         mov     gh,0x7F
         mov     [awx+3],gh
         btr     [awx+3],7
         bc      TestBTM_RBErr
         mov     gh,[awx+3]
         cmp     gh,0x7F
         bne     TestBTM_RBErr
         mov     gh,0x7F
         mov     [awx+3],gh
         bts     [awx+3],7
         bc      TestBTM_RBErr
         mov     gh,[awx+3]
         cmp     gh,0xFF
         bne     TestBTM_RBErr
                 
         mov     gh,0x7F
         bt      gh,7
         bc      TestBTM_RBErr
         cmp     gh,0x7F
         bne     TestBTM_RBErr
         mov     gh,0x7F
         btr     gh,7
         bc      TestBTM_RBErr
         cmp     gh,0x7F
         bne     TestBTM_RBErr
         mov     gh,0x7F
         bts     gh,7
         bc      TestBTM_RBErr
         cmp     gh,0xFF
         bne     TestBTM_RBErr
                 
         mov     bwx,esp
         mov     al,0x80
         mov     [bwx+0],al
         bt      [bwx+0],0
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x80
         bne     TestBTM_RBErr
         mov     al,0x80
         mov     [bwx+0],al
         btr     [bwx+0],0
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x80
         bne     TestBTM_RBErr
         mov     al,0x80
         mov     [bwx+0],al
         bts     [bwx+0],0
         bc      TestBTM_RBErr
         mov     al,[bwx+0]
         cmp     al,0x81
         bne     TestBTM_RBErr
                 
         mov     al,0x80
         bt      al,0
         bc      TestBTM_RBErr
         cmp     al,0x80
         bne     TestBTM_RBErr
         mov     al,0x80
         btr     al,0
         bc      TestBTM_RBErr
         cmp     al,0x80
         bne     TestBTM_RBErr
         mov     al,0x80
         bts     al,0
         bc      TestBTM_RBErr
         cmp     al,0x81
         bne     TestBTM_RBErr
                 
         mov     cwx,esp
         mov     bl,0x80
         mov     [cwx+1],bl
         bt      [cwx+1],1
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x80
         bne     TestBTM_RBErr
         mov     bl,0x80
         mov     [cwx+1],bl
         btr     [cwx+1],1
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x80
         bne     TestBTM_RBErr
         mov     bl,0x80
         mov     [cwx+1],bl
         bts     [cwx+1],1
         bc      TestBTM_RBErr
         mov     bl,[cwx+1]
         cmp     bl,0x82
         bne     TestBTM_RBErr
                 
         mov     bl,0x80
         bt      bl,1
         bc      TestBTM_RBErr
         cmp     bl,0x80
         bne     TestBTM_RBErr
         mov     bl,0x80
         btr     bl,1
         bc      TestBTM_RBErr
         cmp     bl,0x80
         bne     TestBTM_RBErr
         mov     bl,0x80
         bts     bl,1
         bc      TestBTM_RBErr
         cmp     bl,0x82
         bne     TestBTM_RBErr
                 
         mov     dwx,esp
         mov     cl,0x80
         mov     [dwx+2],cl
         bt      [dwx+2],2
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x80
         bne     TestBTM_RBErr
         mov     cl,0x80
         mov     [dwx+2],cl
         btr     [dwx+2],2
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x80
         bne     TestBTM_RBErr
         mov     cl,0x80
         mov     [dwx+2],cl
         bts     [dwx+2],2
         bc      TestBTM_RBErr
         mov     cl,[dwx+2]
         cmp     cl,0x84
         bne     TestBTM_RBErr
                 
         mov     cl,0x80
         bt      cl,2
         bc      TestBTM_RBErr
         cmp     cl,0x80
         bne     TestBTM_RBErr
         mov     cl,0x80
         btr     cl,2
         bc      TestBTM_RBErr
         cmp     cl,0x80
         bne     TestBTM_RBErr
         mov     cl,0x80
         bts     cl,2
         bc      TestBTM_RBErr
         cmp     cl,0x84
         bne     TestBTM_RBErr
                 
         mov     ewx,esp
         mov     dl,0x80
         mov     [ewx+3],dl
         bt      [ewx+3],3
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x80
         bne     TestBTM_RBErr
         mov     dl,0x80
         mov     [ewx+3],dl
         btr     [ewx+3],3
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x80
         bne     TestBTM_RBErr
         mov     dl,0x80
         mov     [ewx+3],dl
         bts     [ewx+3],3
         bc      TestBTM_RBErr
         mov     dl,[ewx+3]
         cmp     dl,0x88
         bne     TestBTM_RBErr
                 
         mov     dl,0x80
         bt      dl,3
         bc      TestBTM_RBErr
         cmp     dl,0x80
         bne     TestBTM_RBErr
         mov     dl,0x80
         btr     dl,3
         bc      TestBTM_RBErr
         cmp     dl,0x80
         bne     TestBTM_RBErr
         mov     dl,0x80
         bts     dl,3
         bc      TestBTM_RBErr
         cmp     dl,0x88
         bne     TestBTM_RBErr
                 
         mov     fwx,esp
         mov     el,0x80
         mov     [fwx+0],el
         bt      [fwx+0],4
         bc      TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x80
         bne     TestBTM_RBErr
         mov     el,0x80
         mov     [fwx+0],el
         btr     [fwx+0],4
         bc      TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x80
         bne     TestBTM_RBErr
         mov     el,0x80
         mov     [fwx+0],el
         bts     [fwx+0],4
         bc      TestBTM_RBErr
         mov     el,[fwx+0]
         cmp     el,0x90
         bne     TestBTM_RBErr
                 
         mov     el,0x80
         bt      el,4
         bc      TestBTM_RBErr
         cmp     el,0x80
         bne     TestBTM_RBErr
         mov     el,0x80
         btr     el,4
         bc      TestBTM_RBErr
         cmp     el,0x80
         bne     TestBTM_RBErr
         mov     el,0x80
         bts     el,4
         bc      TestBTM_RBErr
         cmp     el,0x90
         bne     TestBTM_RBErr
                 
         mov     gwx,esp
         mov     fl,0x80
         mov     [gwx+1],fl
         bt      [gwx+1],5
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x80
         bne     TestBTM_RBErr
         mov     fl,0x80
         mov     [gwx+1],fl
         btr     [gwx+1],5
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0x80
         bne     TestBTM_RBErr
         mov     fl,0x80
         mov     [gwx+1],fl
         bts     [gwx+1],5
         bc      TestBTM_RBErr
         mov     fl,[gwx+1]
         cmp     fl,0xA0
         bne     TestBTM_RBErr
                 
         mov     fl,0x80
         bt      fl,5
         bc      TestBTM_RBErr
         cmp     fl,0x80
         bne     TestBTM_RBErr
         mov     fl,0x80
         btr     fl,5
         bc      TestBTM_RBErr
         cmp     fl,0x80
         bne     TestBTM_RBErr
         mov     fl,0x80
         bts     fl,5
         bc      TestBTM_RBErr
         cmp     fl,0xA0
         bne     TestBTM_RBErr
                 
         mov     ar,esp
         mov     gl,0x80
         mov     [ar+2],gl
         bt      [ar+2],6
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x80
         bne     TestBTM_RBErr
         mov     gl,0x80
         mov     [ar+2],gl
         btr     [ar+2],6
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0x80
         bne     TestBTM_RBErr
         mov     gl,0x80
         mov     [ar+2],gl
         bts     [ar+2],6
         bc      TestBTM_RBErr
         mov     gl,[ar+2]
         cmp     gl,0xC0
         bne     TestBTM_RBErr
                 
         mov     gl,0x80
         bt      gl,6
         bc      TestBTM_RBErr
         cmp     gl,0x80
         bne     TestBTM_RBErr
         mov     gl,0x80
         btr     gl,6
         bc      TestBTM_RBErr
         cmp     gl,0x80
         bne     TestBTM_RBErr
         mov     gl,0x80
         bts     gl,6
         bc      TestBTM_RBErr
         cmp     gl,0xC0
         bne     TestBTM_RBErr
                 
         mov     br,esp
         mov     ah,0x80
         mov     [br+3],ah
         bt      [br+3],7
         bnc     TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x80
         bne     TestBTM_RBErr
         mov     ah,0x80
         mov     [br+3],ah
         btr     [br+3],7
         bnc     TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x00
         bne     TestBTM_RBErr
         mov     ah,0x80
         mov     [br+3],ah
         bts     [br+3],7
         bnc     TestBTM_RBErr
         mov     ah,[br+3]
         cmp     ah,0x80
         bne     TestBTM_RBErr
                 
         mov     ah,0x80
         bt      ah,7
         bnc     TestBTM_RBErr
         cmp     ah,0x80
         bne     TestBTM_RBErr
         mov     ah,0x80
         btr     ah,7
         bnc     TestBTM_RBErr
         cmp     ah,0x00
         bne     TestBTM_RBErr
         mov     ah,0x80
         bts     ah,7
         bnc     TestBTM_RBErr
         cmp     ah,0x80
         bne     TestBTM_RBErr
                 
         mov     cr,esp
         mov     bh,0xFF
         mov     [cr+0],bh
         bt      [cr+0],0
         bnc     TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0xFF
         bne     TestBTM_RBErr
         mov     bh,0xFF
         mov     [cr+0],bh
         btr     [cr+0],0
         bnc     TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0xFE
         bne     TestBTM_RBErr
         mov     bh,0xFF
         mov     [cr+0],bh
         bts     [cr+0],0
         bnc     TestBTM_RBErr
         mov     bh,[cr+0]
         cmp     bh,0xFF
         bne     TestBTM_RBErr
                 
         mov     bh,0xFF
         bt      bh,0
         bnc     TestBTM_RBErr
         cmp     bh,0xFF
         bne     TestBTM_RBErr
         mov     bh,0xFF
         btr     bh,0
         bnc     TestBTM_RBErr
         cmp     bh,0xFE
         bne     TestBTM_RBErr
         mov     bh,0xFF
         bts     bh,0
         bnc     TestBTM_RBErr
         cmp     bh,0xFF
         bne     TestBTM_RBErr
                 
         mov     dr,esp
         mov     ch,0xFF
         mov     [dr+1],ch
         bt      [dr+1],1
         bnc     TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0xFF
         bne     TestBTM_RBErr
         mov     ch,0xFF
         mov     [dr+1],ch
         btr     [dr+1],1
         bnc     TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0xFD
         bne     TestBTM_RBErr
         mov     ch,0xFF
         mov     [dr+1],ch
         bts     [dr+1],1
         bnc     TestBTM_RBErr
         mov     ch,[dr+1]
         cmp     ch,0xFF
         bne     TestBTM_RBErr
                 
         mov     ch,0xFF
         bt      ch,1
         bnc     TestBTM_RBErr
         cmp     ch,0xFF
         bne     TestBTM_RBErr
         mov     ch,0xFF
         btr     ch,1
         bnc     TestBTM_RBErr
         cmp     ch,0xFD
         bne     TestBTM_RBErr
         mov     ch,0xFF
         bts     ch,1
         bnc     TestBTM_RBErr
         cmp     ch,0xFF
         bne     TestBTM_RBErr
                 
         mov     er,esp
         mov     dh,0xFF
         mov     [er+2],dh
         bt      [er+2],2
         bnc     TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0xFF
         bne     TestBTM_RBErr
         mov     dh,0xFF
         mov     [er+2],dh
         btr     [er+2],2
         bnc     TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0xFB
         bne     TestBTM_RBErr
         mov     dh,0xFF
         mov     [er+2],dh
         bts     [er+2],2
         bnc     TestBTM_RBErr
         mov     dh,[er+2]
         cmp     dh,0xFF
         bne     TestBTM_RBErr
                 
         mov     dh,0xFF
         bt      dh,2
         bnc     TestBTM_RBErr
         cmp     dh,0xFF
         bne     TestBTM_RBErr
         mov     dh,0xFF
         btr     dh,2
         bnc     TestBTM_RBErr
         cmp     dh,0xFB
         bne     TestBTM_RBErr
         mov     dh,0xFF
         bts     dh,2
         bnc     TestBTM_RBErr
         cmp     dh,0xFF
         bne     TestBTM_RBErr
                 
         mov     fr,esp
         mov     eh,0xFF
         mov     [fr+3],eh
         bt      [fr+3],3
         bnc     TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0xFF
         bne     TestBTM_RBErr
         mov     eh,0xFF
         mov     [fr+3],eh
         btr     [fr+3],3
         bnc     TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0xF7
         bne     TestBTM_RBErr
         mov     eh,0xFF
         mov     [fr+3],eh
         bts     [fr+3],3
         bnc     TestBTM_RBErr
         mov     eh,[fr+3]
         cmp     eh,0xFF
         bne     TestBTM_RBErr
                 
         mov     eh,0xFF
         bt      eh,3
         bnc     TestBTM_RBErr
         cmp     eh,0xFF
         bne     TestBTM_RBErr
         mov     eh,0xFF
         btr     eh,3
         bnc     TestBTM_RBErr
         cmp     eh,0xF7
         bne     TestBTM_RBErr
         mov     eh,0xFF
         bts     eh,3
         bnc     TestBTM_RBErr
         cmp     eh,0xFF
         bne     TestBTM_RBErr
                 
         mov     gr,esp
         mov     fh,0xFF
         mov     [gr+0],fh
         bt      [gr+0],4
         bnc     TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0xFF
         bne     TestBTM_RBErr
         mov     fh,0xFF
         mov     [gr+0],fh
         btr     [gr+0],4
         bnc     TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0xEF
         bne     TestBTM_RBErr
         mov     fh,0xFF
         mov     [gr+0],fh
         bts     [gr+0],4
         bnc     TestBTM_RBErr
         mov     fh,[gr+0]
         cmp     fh,0xFF
         bne     TestBTM_RBErr
                 
         mov     fh,0xFF
         bt      fh,4
         bnc     TestBTM_RBErr
         cmp     fh,0xFF
         bne     TestBTM_RBErr
         mov     fh,0xFF
         btr     fh,4
         bnc     TestBTM_RBErr
         cmp     fh,0xEF
         bne     TestBTM_RBErr
         mov     fh,0xFF
         bts     fh,4
         bnc     TestBTM_RBErr
         cmp     fh,0xFF
         bne     TestBTM_RBErr
                 
         mov     awx,esp
         mov     gh,0xFF
         mov     [awx+1],gh
         bt      [awx+1],5
         bnc     TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0xFF
         bne     TestBTM_RBErr
         mov     gh,0xFF
         mov     [awx+1],gh
         btr     [awx+1],5
         bnc     TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0xDF
         bne     TestBTM_RBErr
         mov     gh,0xFF
         mov     [awx+1],gh
         bts     [awx+1],5
         bnc     TestBTM_RBErr
         mov     gh,[awx+1]
         cmp     gh,0xFF
         bne     TestBTM_RBErr
                 
         mov     gh,0xFF
         bt      gh,5
         bnc     TestBTM_RBErr
         cmp     gh,0xFF
         bne     TestBTM_RBErr
         mov     gh,0xFF
         btr     gh,5
         bnc     TestBTM_RBErr
         cmp     gh,0xDF
         bne     TestBTM_RBErr
         mov     gh,0xFF
         bts     gh,5
         bnc     TestBTM_RBErr
         cmp     gh,0xFF
         bne     TestBTM_RBErr
                 
         mov     bwx,esp
         mov     al,0xFF
         mov     [bwx+2],al
         bt      [bwx+2],6
         bnc     TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0xFF
         bne     TestBTM_RBErr
         mov     al,0xFF
         mov     [bwx+2],al
         btr     [bwx+2],6
         bnc     TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0xBF
         bne     TestBTM_RBErr
         mov     al,0xFF
         mov     [bwx+2],al
         bts     [bwx+2],6
         bnc     TestBTM_RBErr
         mov     al,[bwx+2]
         cmp     al,0xFF
         bne     TestBTM_RBErr
                 
         mov     al,0xFF
         bt      al,6
         bnc     TestBTM_RBErr
         cmp     al,0xFF
         bne     TestBTM_RBErr
         mov     al,0xFF
         btr     al,6
         bnc     TestBTM_RBErr
         cmp     al,0xBF
         bne     TestBTM_RBErr
         mov     al,0xFF
         bts     al,6
         bnc     TestBTM_RBErr
         cmp     al,0xFF
         bne     TestBTM_RBErr
                 
         mov     cwx,esp
         mov     bl,0xFF
         mov     [cwx+3],bl
         bt      [cwx+3],7
         bnc     TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0xFF
         bne     TestBTM_RBErr
         mov     bl,0xFF
         mov     [cwx+3],bl
         btr     [cwx+3],7
         bnc     TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0x7F
         bne     TestBTM_RBErr
         mov     bl,0xFF
         mov     [cwx+3],bl
         bts     [cwx+3],7
         bnc     TestBTM_RBErr
         mov     bl,[cwx+3]
         cmp     bl,0xFF
         bne     TestBTM_RBErr
                 
         mov     bl,0xFF
         bt      bl,7
         bnc     TestBTM_RBErr
         cmp     bl,0xFF
         bne     TestBTM_RBErr
         mov     bl,0xFF
         btr     bl,7
         bnc     TestBTM_RBErr
         cmp     bl,0x7F
         bne     TestBTM_RBErr
         mov     bl,0xFF
         bts     bl,7
         bnc     TestBTM_RBErr
         cmp     bl,0xFF
         bne     TestBTM_RBErr
                 
         bra     TestBTM_RBRet
TestBTM_RBErr:
         nop     
         trap    
         nop     
TestBTM_RBRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,4,0
