.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WWBS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WWBS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         mov     cl,0x00
         addsx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x0000
         mov     dl,0x00
         subsx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBSErr
         mov     cx,0x0000
         mov     el,0x00
         andsx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0000
         mov     fl,0x00
         orsx    aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBSErr
         mov     ex,0x0000
         mov     gl,0x00
         xorsx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x0000
         mov     ah,0x00
         mulsx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x0000
         mov     bh,0x00
         sdivsx  dw,gx,bh
         cmp     dw,0xFFFF
         bne     TestArus_WWBSErr
         mov     aw,0x0000
         mov     ch,0x00
         sremsx  ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBSErr
         mov     bw,0x0000
         mov     dh,0x01
         addsx   fw,bw,dh
         cmp     fw,0x0001
         bne     TestArus_WWBSErr
         mov     cw,0x0000
         mov     eh,0x01
         subsx   gw,cw,eh
         cmp     gw,0xFFFF
         bne     TestArus_WWBSErr
         mov     dw,0x0000
         mov     fh,0x01
         andsx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0000
         mov     gh,0x01
         orsx    bx,ew,gh
         cmp     bx,0x0001
         bne     TestArus_WWBSErr
         mov     fw,0x0000
         mov     al,0x01
         xorsx   cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBSErr
         mov     gw,0x0000
         mov     bl,0x01
         mulsx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBSErr
         mov     ax,0x0000
         mov     cl,0x01
         sdivsx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x0000
         mov     dl,0x01
         sremsx  fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBSErr
         mov     cx,0x0000
         mov     el,0x07
         addsx   gx,cx,el
         cmp     gx,0x0007
         bne     TestArus_WWBSErr
         mov     dx,0x0000
         mov     fl,0x07
         subsx   aw,dx,fl
         cmp     aw,0xFFF9
         bne     TestArus_WWBSErr
         mov     ex,0x0000
         mov     gl,0x07
         andsx   bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x0000
         mov     ah,0x07
         orsx    cw,fx,ah
         cmp     cw,0x0007
         bne     TestArus_WWBSErr
         mov     gx,0x0000
         mov     bh,0x07
         xorsx   dw,gx,bh
         cmp     dw,0x0007
         bne     TestArus_WWBSErr
         mov     aw,0x0000
         mov     ch,0x07
         mulsx   ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBSErr
         mov     bw,0x0000
         mov     dh,0x07
         sdivsx  fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBSErr
         mov     cw,0x0000
         mov     eh,0x07
         sremsx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         mov     dw,0x0000
         mov     fh,0x08
         addsx   ax,dw,fh
         cmp     ax,0x0008
         bne     TestArus_WWBSErr
         mov     ew,0x0000
         mov     gh,0x08
         subsx   bx,ew,gh
         cmp     bx,0xFFF8
         bne     TestArus_WWBSErr
         mov     fw,0x0000
         mov     al,0x08
         andsx   cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBSErr
         mov     gw,0x0000
         mov     bl,0x08
         orsx    dx,gw,bl
         cmp     dx,0x0008
         bne     TestArus_WWBSErr
         mov     ax,0x0000
         mov     cl,0x08
         xorsx   ex,ax,cl
         cmp     ex,0x0008
         bne     TestArus_WWBSErr
         mov     bx,0x0000
         mov     dl,0x08
         mulsx   fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBSErr
         mov     cx,0x0000
         mov     el,0x08
         sdivsx  gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0000
         mov     fl,0x08
         sremsx  aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBSErr
         mov     ex,0x0000
         mov     gl,0x09
         addsx   bw,ex,gl
         cmp     bw,0x0009
         bne     TestArus_WWBSErr
         mov     fx,0x0000
         mov     ah,0x09
         subsx   cw,fx,ah
         cmp     cw,0xFFF7
         bne     TestArus_WWBSErr
         mov     gx,0x0000
         mov     bh,0x09
         andsx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0000
         mov     ch,0x09
         orsx    ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBSErr
         mov     bw,0x0000
         mov     dh,0x09
         xorsx   fw,bw,dh
         cmp     fw,0x0009
         bne     TestArus_WWBSErr
         mov     cw,0x0000
         mov     eh,0x09
         mulsx   gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         mov     dw,0x0000
         mov     fh,0x09
         sdivsx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0000
         mov     gh,0x09
         sremsx  bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBSErr
         mov     fw,0x0000
         mov     al,0x0F
         addsx   cx,fw,al
         cmp     cx,0x000F
         bne     TestArus_WWBSErr
         mov     gw,0x0000
         mov     bl,0x0F
         subsx   dx,gw,bl
         cmp     dx,0xFFF1
         bne     TestArus_WWBSErr
         mov     ax,0x0000
         mov     cl,0x0F
         andsx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x0000
         mov     dl,0x0F
         orsx    fx,bx,dl
         cmp     fx,0x000F
         bne     TestArus_WWBSErr
         mov     cx,0x0000
         mov     el,0x0F
         xorsx   gx,cx,el
         cmp     gx,0x000F
         bne     TestArus_WWBSErr
         mov     dx,0x0000
         mov     fl,0x0F
         mulsx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBSErr
         mov     ex,0x0000
         mov     gl,0x0F
         sdivsx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x0000
         mov     ah,0x0F
         sremsx  cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x0000
         mov     bh,0x7F
         addsx   dw,gx,bh
         cmp     dw,0x007F
         bne     TestArus_WWBSErr
         mov     aw,0x0000
         mov     ch,0x7F
         subsx   ew,aw,ch
         cmp     ew,0xFF81
         bne     TestArus_WWBSErr
         mov     bw,0x0000
         mov     dh,0x7F
         andsx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBSErr
         mov     cw,0x0000
         mov     eh,0x7F
         orsx    gw,cw,eh
         cmp     gw,0x007F
         bne     TestArus_WWBSErr
         mov     dw,0x0000
         mov     fh,0x7F
         xorsx   ax,dw,fh
         cmp     ax,0x007F
         bne     TestArus_WWBSErr
         mov     ew,0x0000
         mov     gh,0x7F
         mulsx   bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBSErr
         mov     fw,0x0000
         mov     al,0x7F
         sdivsx  cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBSErr
         mov     gw,0x0000
         mov     bl,0x7F
         sremsx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBSErr
         mov     ax,0x0000
         mov     cl,0x80
         addsx   ex,ax,cl
         cmp     ex,0xFF80
         bne     TestArus_WWBSErr
         mov     bx,0x0000
         mov     dl,0x80
         subsx   fx,bx,dl
         cmp     fx,0x0080
         bne     TestArus_WWBSErr
         mov     cx,0x0000
         mov     el,0x80
         andsx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0000
         mov     fl,0x80
         orsx    aw,dx,fl
         cmp     aw,0xFF80
         bne     TestArus_WWBSErr
         mov     ex,0x0000
         mov     gl,0x80
         xorsx   bw,ex,gl
         cmp     bw,0xFF80
         bne     TestArus_WWBSErr
         mov     fx,0x0000
         mov     ah,0x80
         mulsx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x0000
         mov     bh,0x80
         sdivsx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0000
         mov     ch,0x80
         sremsx  ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBSErr
         mov     bw,0x0000
         mov     dh,0xFF
         addsx   fw,bw,dh
         cmp     fw,0xFFFF
         bne     TestArus_WWBSErr
         mov     cw,0x0000
         mov     eh,0xFF
         subsx   gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBSErr
         mov     dw,0x0000
         mov     fh,0xFF
         andsx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0000
         mov     gh,0xFF
         orsx    bx,ew,gh
         cmp     bx,0xFFFF
         bne     TestArus_WWBSErr
         mov     fw,0x0000
         mov     al,0xFF
         xorsx   cx,fw,al
         cmp     cx,0xFFFF
         bne     TestArus_WWBSErr
         mov     gw,0x0000
         mov     bl,0xFF
         mulsx   dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBSErr
         mov     ax,0x0000
         mov     cl,0xFF
         sdivsx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x0000
         mov     dl,0xFF
         sremsx  fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBSErr
         mov     cx,0x0001
         mov     el,0x01
         addsx   gx,cx,el
         cmp     gx,0x0002
         bne     TestArus_WWBSErr
         mov     dx,0x0001
         mov     fl,0x01
         subsx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBSErr
         mov     ex,0x0001
         mov     gl,0x01
         andsx   bw,ex,gl
         cmp     bw,0x0001
         bne     TestArus_WWBSErr
         mov     fx,0x0001
         mov     ah,0x01
         orsx    cw,fx,ah
         cmp     cw,0x0001
         bne     TestArus_WWBSErr
         mov     gx,0x0001
         mov     bh,0x01
         xorsx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0001
         mov     ch,0x01
         mulsx   ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBSErr
         mov     bw,0x0001
         mov     dh,0x01
         sdivsx  fw,bw,dh
         cmp     fw,0x0001
         bne     TestArus_WWBSErr
         mov     cw,0x0001
         mov     eh,0x01
         sremsx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         mov     dw,0x0001
         mov     fh,0x07
         addsx   ax,dw,fh
         cmp     ax,0x0008
         bne     TestArus_WWBSErr
         mov     ew,0x0001
         mov     gh,0x07
         subsx   bx,ew,gh
         cmp     bx,0xFFFA
         bne     TestArus_WWBSErr
         mov     fw,0x0001
         mov     al,0x07
         andsx   cx,fw,al
         cmp     cx,0x0001
         bne     TestArus_WWBSErr
         mov     gw,0x0001
         mov     bl,0x07
         orsx    dx,gw,bl
         cmp     dx,0x0007
         bne     TestArus_WWBSErr
         mov     ax,0x0001
         mov     cl,0x07
         xorsx   ex,ax,cl
         cmp     ex,0x0006
         bne     TestArus_WWBSErr
         mov     bx,0x0001
         mov     dl,0x07
         mulsx   fx,bx,dl
         cmp     fx,0x0007
         bne     TestArus_WWBSErr
         mov     cx,0x0001
         mov     el,0x07
         sdivsx  gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0001
         mov     fl,0x07
         sremsx  aw,dx,fl
         cmp     aw,0x0001
         bne     TestArus_WWBSErr
         mov     ex,0x0001
         mov     gl,0x08
         addsx   bw,ex,gl
         cmp     bw,0x0009
         bne     TestArus_WWBSErr
         mov     fx,0x0001
         mov     ah,0x08
         subsx   cw,fx,ah
         cmp     cw,0xFFF9
         bne     TestArus_WWBSErr
         mov     gx,0x0001
         mov     bh,0x08
         andsx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0001
         mov     ch,0x08
         orsx    ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBSErr
         mov     bw,0x0001
         mov     dh,0x08
         xorsx   fw,bw,dh
         cmp     fw,0x0009
         bne     TestArus_WWBSErr
         mov     cw,0x0001
         mov     eh,0x08
         mulsx   gw,cw,eh
         cmp     gw,0x0008
         bne     TestArus_WWBSErr
         mov     dw,0x0001
         mov     fh,0x08
         sdivsx  ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0001
         mov     gh,0x08
         sremsx  bx,ew,gh
         cmp     bx,0x0001
         bne     TestArus_WWBSErr
         mov     fw,0x0001
         mov     al,0x09
         addsx   cx,fw,al
         cmp     cx,0x000A
         bne     TestArus_WWBSErr
         mov     gw,0x0001
         mov     bl,0x09
         subsx   dx,gw,bl
         cmp     dx,0xFFF8
         bne     TestArus_WWBSErr
         mov     ax,0x0001
         mov     cl,0x09
         andsx   ex,ax,cl
         cmp     ex,0x0001
         bne     TestArus_WWBSErr
         mov     bx,0x0001
         mov     dl,0x09
         orsx    fx,bx,dl
         cmp     fx,0x0009
         bne     TestArus_WWBSErr
         mov     cx,0x0001
         mov     el,0x09
         xorsx   gx,cx,el
         cmp     gx,0x0008
         bne     TestArus_WWBSErr
         mov     dx,0x0001
         mov     fl,0x09
         mulsx   aw,dx,fl
         cmp     aw,0x0009
         bne     TestArus_WWBSErr
         mov     ex,0x0001
         mov     gl,0x09
         sdivsx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x0001
         mov     ah,0x09
         sremsx  cw,fx,ah
         cmp     cw,0x0001
         bne     TestArus_WWBSErr
         mov     gx,0x0001
         mov     bh,0x0F
         addsx   dw,gx,bh
         cmp     dw,0x0010
         bne     TestArus_WWBSErr
         mov     aw,0x0001
         mov     ch,0x0F
         subsx   ew,aw,ch
         cmp     ew,0xFFF2
         bne     TestArus_WWBSErr
         mov     bw,0x0001
         mov     dh,0x0F
         andsx   fw,bw,dh
         cmp     fw,0x0001
         bne     TestArus_WWBSErr
         mov     cw,0x0001
         mov     eh,0x0F
         orsx    gw,cw,eh
         cmp     gw,0x000F
         bne     TestArus_WWBSErr
         mov     dw,0x0001
         mov     fh,0x0F
         xorsx   ax,dw,fh
         cmp     ax,0x000E
         bne     TestArus_WWBSErr
         mov     ew,0x0001
         mov     gh,0x0F
         mulsx   bx,ew,gh
         cmp     bx,0x000F
         bne     TestArus_WWBSErr
         mov     fw,0x0001
         mov     al,0x0F
         sdivsx  cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBSErr
         mov     gw,0x0001
         mov     bl,0x0F
         sremsx  dx,gw,bl
         cmp     dx,0x0001
         bne     TestArus_WWBSErr
         mov     ax,0x0001
         mov     cl,0x7F
         addsx   ex,ax,cl
         cmp     ex,0x0080
         bne     TestArus_WWBSErr
         mov     bx,0x0001
         mov     dl,0x7F
         subsx   fx,bx,dl
         cmp     fx,0xFF82
         bne     TestArus_WWBSErr
         mov     cx,0x0001
         mov     el,0x7F
         andsx   gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBSErr
         mov     dx,0x0001
         mov     fl,0x7F
         orsx    aw,dx,fl
         cmp     aw,0x007F
         bne     TestArus_WWBSErr
         mov     ex,0x0001
         mov     gl,0x7F
         xorsx   bw,ex,gl
         cmp     bw,0x007E
         bne     TestArus_WWBSErr
         mov     fx,0x0001
         mov     ah,0x7F
         mulsx   cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBSErr
         mov     gx,0x0001
         mov     bh,0x7F
         sdivsx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0001
         mov     ch,0x7F
         sremsx  ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBSErr
         mov     bw,0x0001
         mov     dh,0x80
         addsx   fw,bw,dh
         cmp     fw,0xFF81
         bne     TestArus_WWBSErr
         mov     cw,0x0001
         mov     eh,0x80
         subsx   gw,cw,eh
         cmp     gw,0x0081
         bne     TestArus_WWBSErr
         mov     dw,0x0001
         mov     fh,0x80
         andsx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0001
         mov     gh,0x80
         orsx    bx,ew,gh
         cmp     bx,0xFF81
         bne     TestArus_WWBSErr
         mov     fw,0x0001
         mov     al,0x80
         xorsx   cx,fw,al
         cmp     cx,0xFF81
         bne     TestArus_WWBSErr
         mov     gw,0x0001
         mov     bl,0x80
         mulsx   dx,gw,bl
         cmp     dx,0xFF80
         bne     TestArus_WWBSErr
         mov     ax,0x0001
         mov     cl,0x80
         sdivsx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x0001
         mov     dl,0x80
         sremsx  fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBSErr
         mov     cx,0x0001
         mov     el,0xFF
         addsx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0001
         mov     fl,0xFF
         subsx   aw,dx,fl
         cmp     aw,0x0002
         bne     TestArus_WWBSErr
         mov     ex,0x0001
         mov     gl,0xFF
         andsx   bw,ex,gl
         cmp     bw,0x0001
         bne     TestArus_WWBSErr
         mov     fx,0x0001
         mov     ah,0xFF
         orsx    cw,fx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WWBSErr
         mov     gx,0x0001
         mov     bh,0xFF
         xorsx   dw,gx,bh
         cmp     dw,0xFFFE
         bne     TestArus_WWBSErr
         mov     aw,0x0001
         mov     ch,0xFF
         mulsx   ew,aw,ch
         cmp     ew,0xFFFF
         bne     TestArus_WWBSErr
         mov     bw,0x0001
         mov     dh,0xFF
         sdivsx  fw,bw,dh
         cmp     fw,0xFFFF
         bne     TestArus_WWBSErr
         mov     cw,0x0001
         mov     eh,0xFF
         sremsx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         mov     dw,0x0008
         mov     fh,0x07
         addsx   ax,dw,fh
         cmp     ax,0x000F
         bne     TestArus_WWBSErr
         mov     ew,0x0008
         mov     gh,0x07
         subsx   bx,ew,gh
         cmp     bx,0x0001
         bne     TestArus_WWBSErr
         mov     fw,0x0008
         mov     al,0x07
         andsx   cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBSErr
         mov     gw,0x0008
         mov     bl,0x07
         orsx    dx,gw,bl
         cmp     dx,0x000F
         bne     TestArus_WWBSErr
         mov     ax,0x0008
         mov     cl,0x07
         xorsx   ex,ax,cl
         cmp     ex,0x000F
         bne     TestArus_WWBSErr
         mov     bx,0x0008
         mov     dl,0x07
         mulsx   fx,bx,dl
         cmp     fx,0x0038
         bne     TestArus_WWBSErr
         mov     cx,0x0008
         mov     el,0x07
         sdivsx  gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBSErr
         mov     dx,0x0008
         mov     fl,0x07
         sremsx  aw,dx,fl
         cmp     aw,0x0001
         bne     TestArus_WWBSErr
         mov     ex,0x0008
         mov     gl,0x08
         addsx   bw,ex,gl
         cmp     bw,0x0010
         bne     TestArus_WWBSErr
         mov     fx,0x0008
         mov     ah,0x08
         subsx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x0008
         mov     bh,0x08
         andsx   dw,gx,bh
         cmp     dw,0x0008
         bne     TestArus_WWBSErr
         mov     aw,0x0008
         mov     ch,0x08
         orsx    ew,aw,ch
         cmp     ew,0x0008
         bne     TestArus_WWBSErr
         mov     bw,0x0008
         mov     dh,0x08
         xorsx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBSErr
         mov     cw,0x0008
         mov     eh,0x08
         mulsx   gw,cw,eh
         cmp     gw,0x0040
         bne     TestArus_WWBSErr
         mov     dw,0x0008
         mov     fh,0x08
         sdivsx  ax,dw,fh
         cmp     ax,0x0001
         bne     TestArus_WWBSErr
         mov     ew,0x0008
         mov     gh,0x08
         sremsx  bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBSErr
         mov     fw,0x0008
         mov     al,0x09
         addsx   cx,fw,al
         cmp     cx,0x0011
         bne     TestArus_WWBSErr
         mov     gw,0x0008
         mov     bl,0x09
         subsx   dx,gw,bl
         cmp     dx,0xFFFF
         bne     TestArus_WWBSErr
         mov     ax,0x0008
         mov     cl,0x09
         andsx   ex,ax,cl
         cmp     ex,0x0008
         bne     TestArus_WWBSErr
         mov     bx,0x0008
         mov     dl,0x09
         orsx    fx,bx,dl
         cmp     fx,0x0009
         bne     TestArus_WWBSErr
         mov     cx,0x0008
         mov     el,0x09
         xorsx   gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBSErr
         mov     dx,0x0008
         mov     fl,0x09
         mulsx   aw,dx,fl
         cmp     aw,0x0048
         bne     TestArus_WWBSErr
         mov     ex,0x0008
         mov     gl,0x09
         sdivsx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x0008
         mov     ah,0x09
         sremsx  cw,fx,ah
         cmp     cw,0x0008
         bne     TestArus_WWBSErr
         mov     gx,0x0008
         mov     bh,0x0F
         addsx   dw,gx,bh
         cmp     dw,0x0017
         bne     TestArus_WWBSErr
         mov     aw,0x0008
         mov     ch,0x0F
         subsx   ew,aw,ch
         cmp     ew,0xFFF9
         bne     TestArus_WWBSErr
         mov     bw,0x0008
         mov     dh,0x0F
         andsx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBSErr
         mov     cw,0x0008
         mov     eh,0x0F
         orsx    gw,cw,eh
         cmp     gw,0x000F
         bne     TestArus_WWBSErr
         mov     dw,0x0008
         mov     fh,0x0F
         xorsx   ax,dw,fh
         cmp     ax,0x0007
         bne     TestArus_WWBSErr
         mov     ew,0x0008
         mov     gh,0x0F
         mulsx   bx,ew,gh
         cmp     bx,0x0078
         bne     TestArus_WWBSErr
         mov     fw,0x0008
         mov     al,0x0F
         sdivsx  cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBSErr
         mov     gw,0x0008
         mov     bl,0x0F
         sremsx  dx,gw,bl
         cmp     dx,0x0008
         bne     TestArus_WWBSErr
         mov     ax,0x0008
         mov     cl,0x7F
         addsx   ex,ax,cl
         cmp     ex,0x0087
         bne     TestArus_WWBSErr
         mov     bx,0x0008
         mov     dl,0x7F
         subsx   fx,bx,dl
         cmp     fx,0xFF89
         bne     TestArus_WWBSErr
         mov     cx,0x0008
         mov     el,0x7F
         andsx   gx,cx,el
         cmp     gx,0x0008
         bne     TestArus_WWBSErr
         mov     dx,0x0008
         mov     fl,0x7F
         orsx    aw,dx,fl
         cmp     aw,0x007F
         bne     TestArus_WWBSErr
         mov     ex,0x0008
         mov     gl,0x7F
         xorsx   bw,ex,gl
         cmp     bw,0x0077
         bne     TestArus_WWBSErr
         mov     fx,0x0008
         mov     ah,0x7F
         mulsx   cw,fx,ah
         cmp     cw,0x03F8
         bne     TestArus_WWBSErr
         mov     gx,0x0008
         mov     bh,0x7F
         sdivsx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0008
         mov     ch,0x7F
         sremsx  ew,aw,ch
         cmp     ew,0x0008
         bne     TestArus_WWBSErr
         mov     bw,0x0008
         mov     dh,0x80
         addsx   fw,bw,dh
         cmp     fw,0xFF88
         bne     TestArus_WWBSErr
         mov     cw,0x0008
         mov     eh,0x80
         subsx   gw,cw,eh
         cmp     gw,0x0088
         bne     TestArus_WWBSErr
         mov     dw,0x0008
         mov     fh,0x80
         andsx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0008
         mov     gh,0x80
         orsx    bx,ew,gh
         cmp     bx,0xFF88
         bne     TestArus_WWBSErr
         mov     fw,0x0008
         mov     al,0x80
         xorsx   cx,fw,al
         cmp     cx,0xFF88
         bne     TestArus_WWBSErr
         mov     gw,0x0008
         mov     bl,0x80
         mulsx   dx,gw,bl
         cmp     dx,0xFC00
         bne     TestArus_WWBSErr
         mov     ax,0x0008
         mov     cl,0x80
         sdivsx  ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x0008
         mov     dl,0x80
         sremsx  fx,bx,dl
         cmp     fx,0x0008
         bne     TestArus_WWBSErr
         mov     cx,0x0008
         mov     el,0xFF
         addsx   gx,cx,el
         cmp     gx,0x0007
         bne     TestArus_WWBSErr
         mov     dx,0x0008
         mov     fl,0xFF
         subsx   aw,dx,fl
         cmp     aw,0x0009
         bne     TestArus_WWBSErr
         mov     ex,0x0008
         mov     gl,0xFF
         andsx   bw,ex,gl
         cmp     bw,0x0008
         bne     TestArus_WWBSErr
         mov     fx,0x0008
         mov     ah,0xFF
         orsx    cw,fx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WWBSErr
         mov     gx,0x0008
         mov     bh,0xFF
         xorsx   dw,gx,bh
         cmp     dw,0xFFF7
         bne     TestArus_WWBSErr
         mov     aw,0x0008
         mov     ch,0xFF
         mulsx   ew,aw,ch
         cmp     ew,0xFFF8
         bne     TestArus_WWBSErr
         mov     bw,0x0008
         mov     dh,0xFF
         sdivsx  fw,bw,dh
         cmp     fw,0xFFF8
         bne     TestArus_WWBSErr
         mov     cw,0x0008
         mov     eh,0xFF
         sremsx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         mov     dw,0x0009
         mov     fh,0x08
         addsx   ax,dw,fh
         cmp     ax,0x0011
         bne     TestArus_WWBSErr
         mov     ew,0x0009
         mov     gh,0x08
         subsx   bx,ew,gh
         cmp     bx,0x0001
         bne     TestArus_WWBSErr
         mov     fw,0x0009
         mov     al,0x08
         andsx   cx,fw,al
         cmp     cx,0x0008
         bne     TestArus_WWBSErr
         mov     gw,0x0009
         mov     bl,0x08
         orsx    dx,gw,bl
         cmp     dx,0x0009
         bne     TestArus_WWBSErr
         mov     ax,0x0009
         mov     cl,0x08
         xorsx   ex,ax,cl
         cmp     ex,0x0001
         bne     TestArus_WWBSErr
         mov     bx,0x0009
         mov     dl,0x08
         mulsx   fx,bx,dl
         cmp     fx,0x0048
         bne     TestArus_WWBSErr
         mov     cx,0x0009
         mov     el,0x08
         sdivsx  gx,cx,el
         cmp     gx,0x0001
         bne     TestArus_WWBSErr
         mov     dx,0x0009
         mov     fl,0x08
         sremsx  aw,dx,fl
         cmp     aw,0x0001
         bne     TestArus_WWBSErr
         mov     ex,0x0009
         mov     gl,0x09
         addsx   bw,ex,gl
         cmp     bw,0x0012
         bne     TestArus_WWBSErr
         mov     fx,0x0009
         mov     ah,0x09
         subsx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x0009
         mov     bh,0x09
         andsx   dw,gx,bh
         cmp     dw,0x0009
         bne     TestArus_WWBSErr
         mov     aw,0x0009
         mov     ch,0x09
         orsx    ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBSErr
         mov     bw,0x0009
         mov     dh,0x09
         xorsx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBSErr
         mov     cw,0x0009
         mov     eh,0x09
         mulsx   gw,cw,eh
         cmp     gw,0x0051
         bne     TestArus_WWBSErr
         mov     dw,0x0009
         mov     fh,0x09
         sdivsx  ax,dw,fh
         cmp     ax,0x0001
         bne     TestArus_WWBSErr
         mov     ew,0x0009
         mov     gh,0x09
         sremsx  bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBSErr
         mov     fw,0x0009
         mov     al,0x0F
         addsx   cx,fw,al
         cmp     cx,0x0018
         bne     TestArus_WWBSErr
         mov     gw,0x0009
         mov     bl,0x0F
         subsx   dx,gw,bl
         cmp     dx,0xFFFA
         bne     TestArus_WWBSErr
         mov     ax,0x0009
         mov     cl,0x0F
         andsx   ex,ax,cl
         cmp     ex,0x0009
         bne     TestArus_WWBSErr
         mov     bx,0x0009
         mov     dl,0x0F
         orsx    fx,bx,dl
         cmp     fx,0x000F
         bne     TestArus_WWBSErr
         mov     cx,0x0009
         mov     el,0x0F
         xorsx   gx,cx,el
         cmp     gx,0x0006
         bne     TestArus_WWBSErr
         mov     dx,0x0009
         mov     fl,0x0F
         mulsx   aw,dx,fl
         cmp     aw,0x0087
         bne     TestArus_WWBSErr
         mov     ex,0x0009
         mov     gl,0x0F
         sdivsx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x0009
         mov     ah,0x0F
         sremsx  cw,fx,ah
         cmp     cw,0x0009
         bne     TestArus_WWBSErr
         mov     gx,0x0009
         mov     bh,0x7F
         addsx   dw,gx,bh
         cmp     dw,0x0088
         bne     TestArus_WWBSErr
         mov     aw,0x0009
         mov     ch,0x7F
         subsx   ew,aw,ch
         cmp     ew,0xFF8A
         bne     TestArus_WWBSErr
         mov     bw,0x0009
         mov     dh,0x7F
         andsx   fw,bw,dh
         cmp     fw,0x0009
         bne     TestArus_WWBSErr
         mov     cw,0x0009
         mov     eh,0x7F
         orsx    gw,cw,eh
         cmp     gw,0x007F
         bne     TestArus_WWBSErr
         mov     dw,0x0009
         mov     fh,0x7F
         xorsx   ax,dw,fh
         cmp     ax,0x0076
         bne     TestArus_WWBSErr
         mov     ew,0x0009
         mov     gh,0x7F
         mulsx   bx,ew,gh
         cmp     bx,0x0477
         bne     TestArus_WWBSErr
         mov     fw,0x0009
         mov     al,0x7F
         sdivsx  cx,fw,al
         cmp     cx,0x0000
         bne     TestArus_WWBSErr
         mov     gw,0x0009
         mov     bl,0x7F
         sremsx  dx,gw,bl
         cmp     dx,0x0009
         bne     TestArus_WWBSErr
         mov     ax,0x0009
         mov     cl,0x80
         addsx   ex,ax,cl
         cmp     ex,0xFF89
         bne     TestArus_WWBSErr
         mov     bx,0x0009
         mov     dl,0x80
         subsx   fx,bx,dl
         cmp     fx,0x0089
         bne     TestArus_WWBSErr
         mov     cx,0x0009
         mov     el,0x80
         andsx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0009
         mov     fl,0x80
         orsx    aw,dx,fl
         cmp     aw,0xFF89
         bne     TestArus_WWBSErr
         mov     ex,0x0009
         mov     gl,0x80
         xorsx   bw,ex,gl
         cmp     bw,0xFF89
         bne     TestArus_WWBSErr
         mov     fx,0x0009
         mov     ah,0x80
         mulsx   cw,fx,ah
         cmp     cw,0xFB80
         bne     TestArus_WWBSErr
         mov     gx,0x0009
         mov     bh,0x80
         sdivsx  dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0x0009
         mov     ch,0x80
         sremsx  ew,aw,ch
         cmp     ew,0x0009
         bne     TestArus_WWBSErr
         mov     bw,0x0009
         mov     dh,0xFF
         addsx   fw,bw,dh
         cmp     fw,0x0008
         bne     TestArus_WWBSErr
         mov     cw,0x0009
         mov     eh,0xFF
         subsx   gw,cw,eh
         cmp     gw,0x000A
         bne     TestArus_WWBSErr
         mov     dw,0x0009
         mov     fh,0xFF
         andsx   ax,dw,fh
         cmp     ax,0x0009
         bne     TestArus_WWBSErr
         mov     ew,0x0009
         mov     gh,0xFF
         orsx    bx,ew,gh
         cmp     bx,0xFFFF
         bne     TestArus_WWBSErr
         mov     fw,0x0009
         mov     al,0xFF
         xorsx   cx,fw,al
         cmp     cx,0xFFF6
         bne     TestArus_WWBSErr
         mov     gw,0x0009
         mov     bl,0xFF
         mulsx   dx,gw,bl
         cmp     dx,0xFFF7
         bne     TestArus_WWBSErr
         mov     ax,0x0009
         mov     cl,0xFF
         sdivsx  ex,ax,cl
         cmp     ex,0xFFF7
         bne     TestArus_WWBSErr
         mov     bx,0x0009
         mov     dl,0xFF
         sremsx  fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBSErr
         mov     cx,0x007F
         mov     el,0x09
         addsx   gx,cx,el
         cmp     gx,0x0088
         bne     TestArus_WWBSErr
         mov     dx,0x007F
         mov     fl,0x09
         subsx   aw,dx,fl
         cmp     aw,0x0076
         bne     TestArus_WWBSErr
         mov     ex,0x007F
         mov     gl,0x09
         andsx   bw,ex,gl
         cmp     bw,0x0009
         bne     TestArus_WWBSErr
         mov     fx,0x007F
         mov     ah,0x09
         orsx    cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBSErr
         mov     gx,0x007F
         mov     bh,0x09
         xorsx   dw,gx,bh
         cmp     dw,0x0076
         bne     TestArus_WWBSErr
         mov     aw,0x007F
         mov     ch,0x09
         mulsx   ew,aw,ch
         cmp     ew,0x0477
         bne     TestArus_WWBSErr
         mov     bw,0x007F
         mov     dh,0x09
         sdivsx  fw,bw,dh
         cmp     fw,0x000E
         bne     TestArus_WWBSErr
         mov     cw,0x007F
         mov     eh,0x09
         sremsx  gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBSErr
         mov     dw,0x007F
         mov     fh,0x0F
         addsx   ax,dw,fh
         cmp     ax,0x008E
         bne     TestArus_WWBSErr
         mov     ew,0x007F
         mov     gh,0x0F
         subsx   bx,ew,gh
         cmp     bx,0x0070
         bne     TestArus_WWBSErr
         mov     fw,0x007F
         mov     al,0x0F
         andsx   cx,fw,al
         cmp     cx,0x000F
         bne     TestArus_WWBSErr
         mov     gw,0x007F
         mov     bl,0x0F
         orsx    dx,gw,bl
         cmp     dx,0x007F
         bne     TestArus_WWBSErr
         mov     ax,0x007F
         mov     cl,0x0F
         xorsx   ex,ax,cl
         cmp     ex,0x0070
         bne     TestArus_WWBSErr
         mov     bx,0x007F
         mov     dl,0x0F
         mulsx   fx,bx,dl
         cmp     fx,0x0771
         bne     TestArus_WWBSErr
         mov     cx,0x007F
         mov     el,0x0F
         sdivsx  gx,cx,el
         cmp     gx,0x0008
         bne     TestArus_WWBSErr
         mov     dx,0x007F
         mov     fl,0x0F
         sremsx  aw,dx,fl
         cmp     aw,0x0007
         bne     TestArus_WWBSErr
         mov     ex,0x007F
         mov     gl,0x7F
         addsx   bw,ex,gl
         cmp     bw,0x00FE
         bne     TestArus_WWBSErr
         mov     fx,0x007F
         mov     ah,0x7F
         subsx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x007F
         mov     bh,0x7F
         andsx   dw,gx,bh
         cmp     dw,0x007F
         bne     TestArus_WWBSErr
         mov     aw,0x007F
         mov     ch,0x7F
         orsx    ew,aw,ch
         cmp     ew,0x007F
         bne     TestArus_WWBSErr
         mov     bw,0x007F
         mov     dh,0x7F
         xorsx   fw,bw,dh
         cmp     fw,0x0000
         bne     TestArus_WWBSErr
         mov     cw,0x007F
         mov     eh,0x7F
         mulsx   gw,cw,eh
         cmp     gw,0x3F01
         bne     TestArus_WWBSErr
         mov     dw,0x007F
         mov     fh,0x7F
         sdivsx  ax,dw,fh
         cmp     ax,0x0001
         bne     TestArus_WWBSErr
         mov     ew,0x007F
         mov     gh,0x7F
         sremsx  bx,ew,gh
         cmp     bx,0x0000
         bne     TestArus_WWBSErr
         mov     fw,0x007F
         mov     al,0x80
         addsx   cx,fw,al
         cmp     cx,0xFFFF
         bne     TestArus_WWBSErr
         mov     gw,0x007F
         mov     bl,0x80
         subsx   dx,gw,bl
         cmp     dx,0x00FF
         bne     TestArus_WWBSErr
         mov     ax,0x007F
         mov     cl,0x80
         andsx   ex,ax,cl
         cmp     ex,0x0000
         bne     TestArus_WWBSErr
         mov     bx,0x007F
         mov     dl,0x80
         orsx    fx,bx,dl
         cmp     fx,0xFFFF
         bne     TestArus_WWBSErr
         mov     cx,0x007F
         mov     el,0x80
         xorsx   gx,cx,el
         cmp     gx,0xFFFF
         bne     TestArus_WWBSErr
         mov     dx,0x007F
         mov     fl,0x80
         mulsx   aw,dx,fl
         cmp     aw,0xC080
         bne     TestArus_WWBSErr
         mov     ex,0x007F
         mov     gl,0x80
         sdivsx  bw,ex,gl
         cmp     bw,0x0000
         bne     TestArus_WWBSErr
         mov     fx,0x007F
         mov     ah,0x80
         sremsx  cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBSErr
         mov     gx,0x007F
         mov     bh,0xFF
         addsx   dw,gx,bh
         cmp     dw,0x007E
         bne     TestArus_WWBSErr
         mov     aw,0x007F
         mov     ch,0xFF
         subsx   ew,aw,ch
         cmp     ew,0x0080
         bne     TestArus_WWBSErr
         mov     bw,0x007F
         mov     dh,0xFF
         andsx   fw,bw,dh
         cmp     fw,0x007F
         bne     TestArus_WWBSErr
         mov     cw,0x007F
         mov     eh,0xFF
         orsx    gw,cw,eh
         cmp     gw,0xFFFF
         bne     TestArus_WWBSErr
         mov     dw,0x007F
         mov     fh,0xFF
         xorsx   ax,dw,fh
         cmp     ax,0xFF80
         bne     TestArus_WWBSErr
         mov     ew,0x007F
         mov     gh,0xFF
         mulsx   bx,ew,gh
         cmp     bx,0xFF81
         bne     TestArus_WWBSErr
         mov     fw,0x007F
         mov     al,0xFF
         sdivsx  cx,fw,al
         cmp     cx,0xFF81
         bne     TestArus_WWBSErr
         mov     gw,0x007F
         mov     bl,0xFF
         sremsx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBSErr
         mov     ax,0x0080
         mov     cl,0x0F
         addsx   ex,ax,cl
         cmp     ex,0x008F
         bne     TestArus_WWBSErr
         mov     bx,0x0080
         mov     dl,0x0F
         subsx   fx,bx,dl
         cmp     fx,0x0071
         bne     TestArus_WWBSErr
         mov     cx,0x0080
         mov     el,0x0F
         andsx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0080
         mov     fl,0x0F
         orsx    aw,dx,fl
         cmp     aw,0x008F
         bne     TestArus_WWBSErr
         mov     ex,0x0080
         mov     gl,0x0F
         xorsx   bw,ex,gl
         cmp     bw,0x008F
         bne     TestArus_WWBSErr
         mov     fx,0x0080
         mov     ah,0x0F
         mulsx   cw,fx,ah
         cmp     cw,0x0780
         bne     TestArus_WWBSErr
         mov     gx,0x0080
         mov     bh,0x0F
         sdivsx  dw,gx,bh
         cmp     dw,0x0008
         bne     TestArus_WWBSErr
         mov     aw,0x0080
         mov     ch,0x0F
         sremsx  ew,aw,ch
         cmp     ew,0x0008
         bne     TestArus_WWBSErr
         mov     bw,0x0080
         mov     dh,0x7F
         addsx   fw,bw,dh
         cmp     fw,0x00FF
         bne     TestArus_WWBSErr
         mov     cw,0x0080
         mov     eh,0x7F
         subsx   gw,cw,eh
         cmp     gw,0x0001
         bne     TestArus_WWBSErr
         mov     dw,0x0080
         mov     fh,0x7F
         andsx   ax,dw,fh
         cmp     ax,0x0000
         bne     TestArus_WWBSErr
         mov     ew,0x0080
         mov     gh,0x7F
         orsx    bx,ew,gh
         cmp     bx,0x00FF
         bne     TestArus_WWBSErr
         mov     fw,0x0080
         mov     al,0x7F
         xorsx   cx,fw,al
         cmp     cx,0x00FF
         bne     TestArus_WWBSErr
         mov     gw,0x0080
         mov     bl,0x7F
         mulsx   dx,gw,bl
         cmp     dx,0x3F80
         bne     TestArus_WWBSErr
         mov     ax,0x0080
         mov     cl,0x7F
         sdivsx  ex,ax,cl
         cmp     ex,0x0001
         bne     TestArus_WWBSErr
         mov     bx,0x0080
         mov     dl,0x7F
         sremsx  fx,bx,dl
         cmp     fx,0x0001
         bne     TestArus_WWBSErr
         mov     cx,0x0080
         mov     el,0x80
         addsx   gx,cx,el
         cmp     gx,0x0000
         bne     TestArus_WWBSErr
         mov     dx,0x0080
         mov     fl,0x80
         subsx   aw,dx,fl
         cmp     aw,0x0100
         bne     TestArus_WWBSErr
         mov     ex,0x0080
         mov     gl,0x80
         andsx   bw,ex,gl
         cmp     bw,0x0080
         bne     TestArus_WWBSErr
         mov     fx,0x0080
         mov     ah,0x80
         orsx    cw,fx,ah
         cmp     cw,0xFF80
         bne     TestArus_WWBSErr
         mov     gx,0x0080
         mov     bh,0x80
         xorsx   dw,gx,bh
         cmp     dw,0xFF00
         bne     TestArus_WWBSErr
         mov     aw,0x0080
         mov     ch,0x80
         mulsx   ew,aw,ch
         cmp     ew,0xC000
         bne     TestArus_WWBSErr
         mov     bw,0x0080
         mov     dh,0x80
         sdivsx  fw,bw,dh
         cmp     fw,0xFFFF
         bne     TestArus_WWBSErr
         mov     cw,0x0080
         mov     eh,0x80
         sremsx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         mov     dw,0x0080
         mov     fh,0xFF
         addsx   ax,dw,fh
         cmp     ax,0x007F
         bne     TestArus_WWBSErr
         mov     ew,0x0080
         mov     gh,0xFF
         subsx   bx,ew,gh
         cmp     bx,0x0081
         bne     TestArus_WWBSErr
         mov     fw,0x0080
         mov     al,0xFF
         andsx   cx,fw,al
         cmp     cx,0x0080
         bne     TestArus_WWBSErr
         mov     gw,0x0080
         mov     bl,0xFF
         orsx    dx,gw,bl
         cmp     dx,0xFFFF
         bne     TestArus_WWBSErr
         mov     ax,0x0080
         mov     cl,0xFF
         xorsx   ex,ax,cl
         cmp     ex,0xFF7F
         bne     TestArus_WWBSErr
         mov     bx,0x0080
         mov     dl,0xFF
         mulsx   fx,bx,dl
         cmp     fx,0xFF80
         bne     TestArus_WWBSErr
         mov     cx,0x0080
         mov     el,0xFF
         sdivsx  gx,cx,el
         cmp     gx,0xFF80
         bne     TestArus_WWBSErr
         mov     dx,0x0080
         mov     fl,0xFF
         sremsx  aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBSErr
         mov     ex,0x7FFF
         mov     gl,0x7F
         addsx   bw,ex,gl
         cmp     bw,0x807E
         bne     TestArus_WWBSErr
         mov     fx,0x7FFF
         mov     ah,0x7F
         subsx   cw,fx,ah
         cmp     cw,0x7F80
         bne     TestArus_WWBSErr
         mov     gx,0x7FFF
         mov     bh,0x7F
         andsx   dw,gx,bh
         cmp     dw,0x007F
         bne     TestArus_WWBSErr
         mov     aw,0x7FFF
         mov     ch,0x7F
         orsx    ew,aw,ch
         cmp     ew,0x7FFF
         bne     TestArus_WWBSErr
         mov     bw,0x7FFF
         mov     dh,0x7F
         xorsx   fw,bw,dh
         cmp     fw,0x7F80
         bne     TestArus_WWBSErr
         mov     cw,0x7FFF
         mov     eh,0x7F
         mulsx   gw,cw,eh
         cmp     gw,0x7F81
         bne     TestArus_WWBSErr
         mov     dw,0x7FFF
         mov     fh,0x7F
         sdivsx  ax,dw,fh
         cmp     ax,0x0102
         bne     TestArus_WWBSErr
         mov     ew,0x7FFF
         mov     gh,0x7F
         sremsx  bx,ew,gh
         cmp     bx,0x0001
         bne     TestArus_WWBSErr
         mov     fw,0x7FFF
         mov     al,0x80
         addsx   cx,fw,al
         cmp     cx,0x7F7F
         bne     TestArus_WWBSErr
         mov     gw,0x7FFF
         mov     bl,0x80
         subsx   dx,gw,bl
         cmp     dx,0x807F
         bne     TestArus_WWBSErr
         mov     ax,0x7FFF
         mov     cl,0x80
         andsx   ex,ax,cl
         cmp     ex,0x7F80
         bne     TestArus_WWBSErr
         mov     bx,0x7FFF
         mov     dl,0x80
         orsx    fx,bx,dl
         cmp     fx,0xFFFF
         bne     TestArus_WWBSErr
         mov     cx,0x7FFF
         mov     el,0x80
         xorsx   gx,cx,el
         cmp     gx,0x807F
         bne     TestArus_WWBSErr
         mov     dx,0x7FFF
         mov     fl,0x80
         mulsx   aw,dx,fl
         cmp     aw,0x0080
         bne     TestArus_WWBSErr
         mov     ex,0x7FFF
         mov     gl,0x80
         sdivsx  bw,ex,gl
         cmp     bw,0xFF01
         bne     TestArus_WWBSErr
         mov     fx,0x7FFF
         mov     ah,0x80
         sremsx  cw,fx,ah
         cmp     cw,0x007F
         bne     TestArus_WWBSErr
         mov     gx,0x7FFF
         mov     bh,0xFF
         addsx   dw,gx,bh
         cmp     dw,0x7FFE
         bne     TestArus_WWBSErr
         mov     aw,0x7FFF
         mov     ch,0xFF
         subsx   ew,aw,ch
         cmp     ew,0x8000
         bne     TestArus_WWBSErr
         mov     bw,0x7FFF
         mov     dh,0xFF
         andsx   fw,bw,dh
         cmp     fw,0x7FFF
         bne     TestArus_WWBSErr
         mov     cw,0x7FFF
         mov     eh,0xFF
         orsx    gw,cw,eh
         cmp     gw,0xFFFF
         bne     TestArus_WWBSErr
         mov     dw,0x7FFF
         mov     fh,0xFF
         xorsx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBSErr
         mov     ew,0x7FFF
         mov     gh,0xFF
         mulsx   bx,ew,gh
         cmp     bx,0x8001
         bne     TestArus_WWBSErr
         mov     fw,0x7FFF
         mov     al,0xFF
         sdivsx  cx,fw,al
         cmp     cx,0x8001
         bne     TestArus_WWBSErr
         mov     gw,0x7FFF
         mov     bl,0xFF
         sremsx  dx,gw,bl
         cmp     dx,0x0000
         bne     TestArus_WWBSErr
         mov     ax,0x8000
         mov     cl,0x80
         addsx   ex,ax,cl
         cmp     ex,0x7F80
         bne     TestArus_WWBSErr
         mov     bx,0x8000
         mov     dl,0x80
         subsx   fx,bx,dl
         cmp     fx,0x8080
         bne     TestArus_WWBSErr
         mov     cx,0x8000
         mov     el,0x80
         andsx   gx,cx,el
         cmp     gx,0x8000
         bne     TestArus_WWBSErr
         mov     dx,0x8000
         mov     fl,0x80
         orsx    aw,dx,fl
         cmp     aw,0xFF80
         bne     TestArus_WWBSErr
         mov     ex,0x8000
         mov     gl,0x80
         xorsx   bw,ex,gl
         cmp     bw,0x7F80
         bne     TestArus_WWBSErr
         mov     fx,0x8000
         mov     ah,0x80
         mulsx   cw,fx,ah
         cmp     cw,0x0000
         bne     TestArus_WWBSErr
         mov     gx,0x8000
         mov     bh,0x80
         sdivsx  dw,gx,bh
         cmp     dw,0x0100
         bne     TestArus_WWBSErr
         mov     aw,0x8000
         mov     ch,0x80
         sremsx  ew,aw,ch
         cmp     ew,0x0000
         bne     TestArus_WWBSErr
         mov     bw,0x8000
         mov     dh,0xFF
         addsx   fw,bw,dh
         cmp     fw,0x7FFF
         bne     TestArus_WWBSErr
         mov     cw,0x8000
         mov     eh,0xFF
         subsx   gw,cw,eh
         cmp     gw,0x8001
         bne     TestArus_WWBSErr
         mov     dw,0x8000
         mov     fh,0xFF
         andsx   ax,dw,fh
         cmp     ax,0x8000
         bne     TestArus_WWBSErr
         mov     ew,0x8000
         mov     gh,0xFF
         orsx    bx,ew,gh
         cmp     bx,0xFFFF
         bne     TestArus_WWBSErr
         mov     fw,0x8000
         mov     al,0xFF
         xorsx   cx,fw,al
         cmp     cx,0x7FFF
         bne     TestArus_WWBSErr
         mov     gw,0x8000
         mov     bl,0xFF
         mulsx   dx,gw,bl
         cmp     dx,0x8000
         bne     TestArus_WWBSErr
         mov     ax,0x8000
         mov     cl,0xFF
         sdivsx  ex,ax,cl
         cmp     ex,0x8000
         bne     TestArus_WWBSErr
         mov     bx,0x8000
         mov     dl,0xFF
         sremsx  fx,bx,dl
         cmp     fx,0x0000
         bne     TestArus_WWBSErr
         mov     cx,0xFFFF
         mov     el,0xFF
         addsx   gx,cx,el
         cmp     gx,0xFFFE
         bne     TestArus_WWBSErr
         mov     dx,0xFFFF
         mov     fl,0xFF
         subsx   aw,dx,fl
         cmp     aw,0x0000
         bne     TestArus_WWBSErr
         mov     ex,0xFFFF
         mov     gl,0xFF
         andsx   bw,ex,gl
         cmp     bw,0xFFFF
         bne     TestArus_WWBSErr
         mov     fx,0xFFFF
         mov     ah,0xFF
         orsx    cw,fx,ah
         cmp     cw,0xFFFF
         bne     TestArus_WWBSErr
         mov     gx,0xFFFF
         mov     bh,0xFF
         xorsx   dw,gx,bh
         cmp     dw,0x0000
         bne     TestArus_WWBSErr
         mov     aw,0xFFFF
         mov     ch,0xFF
         mulsx   ew,aw,ch
         cmp     ew,0x0001
         bne     TestArus_WWBSErr
         mov     bw,0xFFFF
         mov     dh,0xFF
         sdivsx  fw,bw,dh
         cmp     fw,0x0001
         bne     TestArus_WWBSErr
         mov     cw,0xFFFF
         mov     eh,0xFF
         sremsx  gw,cw,eh
         cmp     gw,0x0000
         bne     TestArus_WWBSErr
         bra     TestArus_WWBSRet
TestArus_WWBSErr:
         nop     
         trap    
         nop     
TestArus_WWBSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
