.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArus_WBDZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArus_WBDZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     al,0x00
         mov     cwx,0x00000000
         addzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x00000000
         subzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x00000000
         andzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x00000000
         orzx    aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x00000000
         xorzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x00000000
         mulzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x00000000
         udivzx  dw,gl,br
         cmp     dw,0xFFFF
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x00000000
         uremzx  ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x00000000
         shlzx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x00000000
         shrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x00000000
         rolzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x00000000
         asrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0x00000001
         addzx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0x00000001
         subzx   dx,gh,bwx
         cmp     dx,0xFFFF
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0x00000001
         andzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x00000001
         orzx    fx,bl,dwx
         cmp     fx,0x0001
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x00000001
         xorzx   gx,cl,ewx
         cmp     gx,0x0001
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x00000001
         mulzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x00000001
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x00000001
         uremzx  cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x00000001
         shlzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x00000001
         shrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x00000001
         rolzx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x00000001
         asrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x00000008
         addzx   ax,dh,fr
         cmp     ax,0x0008
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x00000008
         subzx   bx,eh,gr
         cmp     bx,0xFFF8
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0x00000008
         andzx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0x00000008
         orzx    dx,gh,bwx
         cmp     dx,0x0008
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0x00000008
         xorzx   ex,al,cwx
         cmp     ex,0x0008
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x00000008
         mulzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x00000008
         udivzx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x00000008
         uremzx  aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x00000008
         shlzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x00000008
         shrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x00000008
         rolzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x00000008
         asrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x00000009
         addzx   fw,bh,dr
         cmp     fw,0x0009
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x00000009
         subzx   gw,ch,er
         cmp     gw,0xFFF7
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x00000009
         andzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x00000009
         orzx    bx,eh,gr
         cmp     bx,0x0009
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0x00000009
         xorzx   cx,fh,awx
         cmp     cx,0x0009
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0x00000009
         mulzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0x00000009
         udivzx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x00000009
         uremzx  fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x00000009
         shlzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x00000009
         shrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x00000009
         rolzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x00000009
         asrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x00007FFF
         addzx   dw,gl,br
         cmp     dw,0x7FFF
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x00007FFF
         subzx   ew,ah,cr
         cmp     ew,0x8001
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x00007FFF
         andzx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x00007FFF
         orzx    gw,ch,er
         cmp     gw,0x7FFF
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x00007FFF
         xorzx   ax,dh,fr
         cmp     ax,0x7FFF
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x00007FFF
         mulzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0x00007FFF
         udivzx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0x00007FFF
         uremzx  dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0x0000000F
         shlzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x0000000F
         shrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x0000000F
         rolzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x0000000F
         asrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x00008000
         addzx   bw,el,gwx
         cmp     bw,0x8000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x00008000
         subzx   cw,fl,ar
         cmp     cw,0x8000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x00008000
         andzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x00008000
         orzx    ew,ah,cr
         cmp     ew,0x8000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x00008000
         xorzx   fw,bh,dr
         cmp     fw,0x8000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x00008000
         mulzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x00008000
         udivzx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x00008000
         uremzx  bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0x00000000
         shlzx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0x00000000
         shrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0x00000000
         rolzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x00000000
         asrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x7FFFFFFF
         addzx   gx,cl,ewx
         cmp     gx,0xFFFF
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x7FFFFFFF
         subzx   aw,dl,fwx
         cmp     aw,0x0001
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x7FFFFFFF
         andzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x7FFFFFFF
         orzx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x7FFFFFFF
         xorzx   dw,gl,br
         cmp     dw,0xFFFF
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x7FFFFFFF
         mulzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x7FFFFFFF
         udivzx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x7FFFFFFF
         uremzx  gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x0000000F
         shlzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x0000000F
         shrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0x0000000F
         rolzx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0x0000000F
         asrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0x80000000
         addzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0x80000000
         subzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0x80000000
         andzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0x80000000
         orzx    aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0x80000000
         xorzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0x80000000
         mulzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x80000000
         udivzx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x80000000
         uremzx  ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x00000000
         shlzx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x00000000
         shrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x00
         mov     fr,0x00000000
         rolzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x00
         mov     gr,0x00000000
         asrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x00
         mov     awx,0xFFFFFFFF
         addzx   cx,fh,awx
         cmp     cx,0xFFFF
         bne     TestArus_WBDZErr
         mov     gh,0x00
         mov     bwx,0xFFFFFFFF
         subzx   dx,gh,bwx
         cmp     dx,0x0001
         bne     TestArus_WBDZErr
         mov     al,0x00
         mov     cwx,0xFFFFFFFF
         andzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x00
         mov     dwx,0xFFFFFFFF
         orzx    fx,bl,dwx
         cmp     fx,0xFFFF
         bne     TestArus_WBDZErr
         mov     cl,0x00
         mov     ewx,0xFFFFFFFF
         xorzx   gx,cl,ewx
         cmp     gx,0xFFFF
         bne     TestArus_WBDZErr
         mov     dl,0x00
         mov     fwx,0xFFFFFFFF
         mulzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x00
         mov     gwx,0xFFFFFFFF
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x00
         mov     ar,0xFFFFFFFF
         uremzx  cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x00
         mov     br,0x0000000F
         shlzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x00
         mov     cr,0x0000000F
         shrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x00
         mov     dr,0x0000000F
         rolzx   fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x00
         mov     er,0x0000000F
         asrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0x00000001
         addzx   ax,dh,fr
         cmp     ax,0x0002
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0x00000001
         subzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0x00000001
         andzx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0x00000001
         orzx    dx,gh,bwx
         cmp     dx,0x0001
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0x00000001
         xorzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0x00000001
         mulzx   fx,bl,dwx
         cmp     fx,0x0001
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0x00000001
         udivzx  gx,cl,ewx
         cmp     gx,0x0001
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0x00000001
         uremzx  aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x00000001
         shlzx   bw,el,gwx
         cmp     bw,0x0002
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x00000001
         shrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x00000001
         rolzx   dw,gl,br
         cmp     dw,0x0002
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x00000001
         asrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x01
         mov     dr,0x00000008
         addzx   fw,bh,dr
         cmp     fw,0x0009
         bne     TestArus_WBDZErr
         mov     ch,0x01
         mov     er,0x00000008
         subzx   gw,ch,er
         cmp     gw,0xFFF9
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0x00000008
         andzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0x00000008
         orzx    bx,eh,gr
         cmp     bx,0x0009
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0x00000008
         xorzx   cx,fh,awx
         cmp     cx,0x0009
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0x00000008
         mulzx   dx,gh,bwx
         cmp     dx,0x0008
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0x00000008
         udivzx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0x00000008
         uremzx  fx,bl,dwx
         cmp     fx,0x0001
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0x00000008
         shlzx   gx,cl,ewx
         cmp     gx,0x0100
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0x00000008
         shrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x00000008
         rolzx   bw,el,gwx
         cmp     bw,0x0100
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x00000008
         asrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x00000009
         addzx   dw,gl,br
         cmp     dw,0x000A
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x00000009
         subzx   ew,ah,cr
         cmp     ew,0xFFF8
         bne     TestArus_WBDZErr
         mov     bh,0x01
         mov     dr,0x00000009
         andzx   fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDZErr
         mov     ch,0x01
         mov     er,0x00000009
         orzx    gw,ch,er
         cmp     gw,0x0009
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0x00000009
         xorzx   ax,dh,fr
         cmp     ax,0x0008
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0x00000009
         mulzx   bx,eh,gr
         cmp     bx,0x0009
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0x00000009
         udivzx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0x00000009
         uremzx  dx,gh,bwx
         cmp     dx,0x0001
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0x00000009
         shlzx   ex,al,cwx
         cmp     ex,0x0200
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0x00000009
         shrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0x00000009
         rolzx   gx,cl,ewx
         cmp     gx,0x0200
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0x00000009
         asrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x00007FFF
         addzx   bw,el,gwx
         cmp     bw,0x8000
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x00007FFF
         subzx   cw,fl,ar
         cmp     cw,0x8002
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x00007FFF
         andzx   dw,gl,br
         cmp     dw,0x0001
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x00007FFF
         orzx    ew,ah,cr
         cmp     ew,0x7FFF
         bne     TestArus_WBDZErr
         mov     bh,0x01
         mov     dr,0x00007FFF
         xorzx   fw,bh,dr
         cmp     fw,0x7FFE
         bne     TestArus_WBDZErr
         mov     ch,0x01
         mov     er,0x00007FFF
         mulzx   gw,ch,er
         cmp     gw,0x7FFF
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0x00007FFF
         udivzx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0x00007FFF
         uremzx  bx,eh,gr
         cmp     bx,0x0001
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0x0000000F
         shlzx   cx,fh,awx
         cmp     cx,0x8000
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0x0000000F
         shrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0x0000000F
         rolzx   ex,al,cwx
         cmp     ex,0x8000
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0x0000000F
         asrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0x00008000
         addzx   gx,cl,ewx
         cmp     gx,0x8001
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0x00008000
         subzx   aw,dl,fwx
         cmp     aw,0x8001
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x00008000
         andzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x00008000
         orzx    cw,fl,ar
         cmp     cw,0x8001
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x00008000
         xorzx   dw,gl,br
         cmp     dw,0x8001
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x00008000
         mulzx   ew,ah,cr
         cmp     ew,0x8000
         bne     TestArus_WBDZErr
         mov     bh,0x01
         mov     dr,0x00008000
         udivzx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x01
         mov     er,0x00008000
         uremzx  gw,ch,er
         cmp     gw,0x0001
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0x00000000
         shlzx   ax,dh,fr
         cmp     ax,0x0001
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0x00000000
         shrzx   bx,eh,gr
         cmp     bx,0x0001
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0x00000000
         rolzx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0x00000000
         asrzx   dx,gh,bwx
         cmp     dx,0x0001
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0x7FFFFFFF
         addzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0x7FFFFFFF
         subzx   fx,bl,dwx
         cmp     fx,0x0002
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0x7FFFFFFF
         andzx   gx,cl,ewx
         cmp     gx,0x0001
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0x7FFFFFFF
         orzx    aw,dl,fwx
         cmp     aw,0xFFFF
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x7FFFFFFF
         xorzx   bw,el,gwx
         cmp     bw,0xFFFE
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x7FFFFFFF
         mulzx   cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x7FFFFFFF
         udivzx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x7FFFFFFF
         uremzx  ew,ah,cr
         cmp     ew,0x0001
         bne     TestArus_WBDZErr
         mov     bh,0x01
         mov     dr,0x0000000F
         shlzx   fw,bh,dr
         cmp     fw,0x8000
         bne     TestArus_WBDZErr
         mov     ch,0x01
         mov     er,0x0000000F
         shrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0x0000000F
         rolzx   ax,dh,fr
         cmp     ax,0x8000
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0x0000000F
         asrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0x80000000
         addzx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0x80000000
         subzx   dx,gh,bwx
         cmp     dx,0x0001
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0x80000000
         andzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0x80000000
         orzx    fx,bl,dwx
         cmp     fx,0x0001
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0x80000000
         xorzx   gx,cl,ewx
         cmp     gx,0x0001
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0x80000000
         mulzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x80000000
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x80000000
         uremzx  cw,fl,ar
         cmp     cw,0x0001
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x00000000
         shlzx   dw,gl,br
         cmp     dw,0x0001
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x00000000
         shrzx   ew,ah,cr
         cmp     ew,0x0001
         bne     TestArus_WBDZErr
         mov     bh,0x01
         mov     dr,0x00000000
         rolzx   fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDZErr
         mov     ch,0x01
         mov     er,0x00000000
         asrzx   gw,ch,er
         cmp     gw,0x0001
         bne     TestArus_WBDZErr
         mov     dh,0x01
         mov     fr,0xFFFFFFFF
         addzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x01
         mov     gr,0xFFFFFFFF
         subzx   bx,eh,gr
         cmp     bx,0x0002
         bne     TestArus_WBDZErr
         mov     fh,0x01
         mov     awx,0xFFFFFFFF
         andzx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDZErr
         mov     gh,0x01
         mov     bwx,0xFFFFFFFF
         orzx    dx,gh,bwx
         cmp     dx,0xFFFF
         bne     TestArus_WBDZErr
         mov     al,0x01
         mov     cwx,0xFFFFFFFF
         xorzx   ex,al,cwx
         cmp     ex,0xFFFE
         bne     TestArus_WBDZErr
         mov     bl,0x01
         mov     dwx,0xFFFFFFFF
         mulzx   fx,bl,dwx
         cmp     fx,0xFFFF
         bne     TestArus_WBDZErr
         mov     cl,0x01
         mov     ewx,0xFFFFFFFF
         udivzx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x01
         mov     fwx,0xFFFFFFFF
         uremzx  aw,dl,fwx
         cmp     aw,0x0001
         bne     TestArus_WBDZErr
         mov     el,0x01
         mov     gwx,0x0000000F
         shlzx   bw,el,gwx
         cmp     bw,0x8000
         bne     TestArus_WBDZErr
         mov     fl,0x01
         mov     ar,0x0000000F
         shrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x01
         mov     br,0x0000000F
         rolzx   dw,gl,br
         cmp     dw,0x8000
         bne     TestArus_WBDZErr
         mov     ah,0x01
         mov     cr,0x0000000F
         asrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x07
         mov     dr,0x00000008
         addzx   fw,bh,dr
         cmp     fw,0x000F
         bne     TestArus_WBDZErr
         mov     ch,0x07
         mov     er,0x00000008
         subzx   gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDZErr
         mov     dh,0x07
         mov     fr,0x00000008
         andzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x07
         mov     gr,0x00000008
         orzx    bx,eh,gr
         cmp     bx,0x000F
         bne     TestArus_WBDZErr
         mov     fh,0x07
         mov     awx,0x00000008
         xorzx   cx,fh,awx
         cmp     cx,0x000F
         bne     TestArus_WBDZErr
         mov     gh,0x07
         mov     bwx,0x00000008
         mulzx   dx,gh,bwx
         cmp     dx,0x0038
         bne     TestArus_WBDZErr
         mov     al,0x07
         mov     cwx,0x00000008
         udivzx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x07
         mov     dwx,0x00000008
         uremzx  fx,bl,dwx
         cmp     fx,0x0007
         bne     TestArus_WBDZErr
         mov     cl,0x07
         mov     ewx,0x00000008
         shlzx   gx,cl,ewx
         cmp     gx,0x0700
         bne     TestArus_WBDZErr
         mov     dl,0x07
         mov     fwx,0x00000008
         shrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x07
         mov     gwx,0x00000008
         rolzx   bw,el,gwx
         cmp     bw,0x0700
         bne     TestArus_WBDZErr
         mov     fl,0x07
         mov     ar,0x00000008
         asrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x07
         mov     br,0x00000009
         addzx   dw,gl,br
         cmp     dw,0x0010
         bne     TestArus_WBDZErr
         mov     ah,0x07
         mov     cr,0x00000009
         subzx   ew,ah,cr
         cmp     ew,0xFFFE
         bne     TestArus_WBDZErr
         mov     bh,0x07
         mov     dr,0x00000009
         andzx   fw,bh,dr
         cmp     fw,0x0001
         bne     TestArus_WBDZErr
         mov     ch,0x07
         mov     er,0x00000009
         orzx    gw,ch,er
         cmp     gw,0x000F
         bne     TestArus_WBDZErr
         mov     dh,0x07
         mov     fr,0x00000009
         xorzx   ax,dh,fr
         cmp     ax,0x000E
         bne     TestArus_WBDZErr
         mov     eh,0x07
         mov     gr,0x00000009
         mulzx   bx,eh,gr
         cmp     bx,0x003F
         bne     TestArus_WBDZErr
         mov     fh,0x07
         mov     awx,0x00000009
         udivzx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x07
         mov     bwx,0x00000009
         uremzx  dx,gh,bwx
         cmp     dx,0x0007
         bne     TestArus_WBDZErr
         mov     al,0x07
         mov     cwx,0x00000009
         shlzx   ex,al,cwx
         cmp     ex,0x0E00
         bne     TestArus_WBDZErr
         mov     bl,0x07
         mov     dwx,0x00000009
         shrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x07
         mov     ewx,0x00000009
         rolzx   gx,cl,ewx
         cmp     gx,0x0E00
         bne     TestArus_WBDZErr
         mov     dl,0x07
         mov     fwx,0x00000009
         asrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x07
         mov     gwx,0x00007FFF
         addzx   bw,el,gwx
         cmp     bw,0x8006
         bne     TestArus_WBDZErr
         mov     fl,0x07
         mov     ar,0x00007FFF
         subzx   cw,fl,ar
         cmp     cw,0x8008
         bne     TestArus_WBDZErr
         mov     gl,0x07
         mov     br,0x00007FFF
         andzx   dw,gl,br
         cmp     dw,0x0007
         bne     TestArus_WBDZErr
         mov     ah,0x07
         mov     cr,0x00007FFF
         orzx    ew,ah,cr
         cmp     ew,0x7FFF
         bne     TestArus_WBDZErr
         mov     bh,0x07
         mov     dr,0x00007FFF
         xorzx   fw,bh,dr
         cmp     fw,0x7FF8
         bne     TestArus_WBDZErr
         mov     ch,0x07
         mov     er,0x00007FFF
         mulzx   gw,ch,er
         cmp     gw,0x7FF9
         bne     TestArus_WBDZErr
         mov     dh,0x07
         mov     fr,0x00007FFF
         udivzx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x07
         mov     gr,0x00007FFF
         uremzx  bx,eh,gr
         cmp     bx,0x0007
         bne     TestArus_WBDZErr
         mov     fh,0x07
         mov     awx,0x0000000F
         shlzx   cx,fh,awx
         cmp     cx,0x8000
         bne     TestArus_WBDZErr
         mov     gh,0x07
         mov     bwx,0x0000000F
         shrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x07
         mov     cwx,0x0000000F
         rolzx   ex,al,cwx
         cmp     ex,0x8003
         bne     TestArus_WBDZErr
         mov     bl,0x07
         mov     dwx,0x0000000F
         asrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x07
         mov     ewx,0x00008000
         addzx   gx,cl,ewx
         cmp     gx,0x8007
         bne     TestArus_WBDZErr
         mov     dl,0x07
         mov     fwx,0x00008000
         subzx   aw,dl,fwx
         cmp     aw,0x8007
         bne     TestArus_WBDZErr
         mov     el,0x07
         mov     gwx,0x00008000
         andzx   bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x07
         mov     ar,0x00008000
         orzx    cw,fl,ar
         cmp     cw,0x8007
         bne     TestArus_WBDZErr
         mov     gl,0x07
         mov     br,0x00008000
         xorzx   dw,gl,br
         cmp     dw,0x8007
         bne     TestArus_WBDZErr
         mov     ah,0x07
         mov     cr,0x00008000
         mulzx   ew,ah,cr
         cmp     ew,0x8000
         bne     TestArus_WBDZErr
         mov     bh,0x07
         mov     dr,0x00008000
         udivzx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x07
         mov     er,0x00008000
         uremzx  gw,ch,er
         cmp     gw,0x0007
         bne     TestArus_WBDZErr
         mov     dh,0x07
         mov     fr,0x00000000
         shlzx   ax,dh,fr
         cmp     ax,0x0007
         bne     TestArus_WBDZErr
         mov     eh,0x07
         mov     gr,0x00000000
         shrzx   bx,eh,gr
         cmp     bx,0x0007
         bne     TestArus_WBDZErr
         mov     fh,0x07
         mov     awx,0x00000000
         rolzx   cx,fh,awx
         cmp     cx,0x0007
         bne     TestArus_WBDZErr
         mov     gh,0x07
         mov     bwx,0x00000000
         asrzx   dx,gh,bwx
         cmp     dx,0x0007
         bne     TestArus_WBDZErr
         mov     al,0x07
         mov     cwx,0x7FFFFFFF
         addzx   ex,al,cwx
         cmp     ex,0x0006
         bne     TestArus_WBDZErr
         mov     bl,0x07
         mov     dwx,0x7FFFFFFF
         subzx   fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDZErr
         mov     cl,0x07
         mov     ewx,0x7FFFFFFF
         andzx   gx,cl,ewx
         cmp     gx,0x0007
         bne     TestArus_WBDZErr
         mov     dl,0x07
         mov     fwx,0x7FFFFFFF
         orzx    aw,dl,fwx
         cmp     aw,0xFFFF
         bne     TestArus_WBDZErr
         mov     el,0x07
         mov     gwx,0x7FFFFFFF
         xorzx   bw,el,gwx
         cmp     bw,0xFFF8
         bne     TestArus_WBDZErr
         mov     fl,0x07
         mov     ar,0x7FFFFFFF
         mulzx   cw,fl,ar
         cmp     cw,0xFFF9
         bne     TestArus_WBDZErr
         mov     gl,0x07
         mov     br,0x7FFFFFFF
         udivzx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x07
         mov     cr,0x7FFFFFFF
         uremzx  ew,ah,cr
         cmp     ew,0x0007
         bne     TestArus_WBDZErr
         mov     bh,0x07
         mov     dr,0x0000000F
         shlzx   fw,bh,dr
         cmp     fw,0x8000
         bne     TestArus_WBDZErr
         mov     ch,0x07
         mov     er,0x0000000F
         shrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x07
         mov     fr,0x0000000F
         rolzx   ax,dh,fr
         cmp     ax,0x8003
         bne     TestArus_WBDZErr
         mov     eh,0x07
         mov     gr,0x0000000F
         asrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x07
         mov     awx,0x80000000
         addzx   cx,fh,awx
         cmp     cx,0x0007
         bne     TestArus_WBDZErr
         mov     gh,0x07
         mov     bwx,0x80000000
         subzx   dx,gh,bwx
         cmp     dx,0x0007
         bne     TestArus_WBDZErr
         mov     al,0x07
         mov     cwx,0x80000000
         andzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x07
         mov     dwx,0x80000000
         orzx    fx,bl,dwx
         cmp     fx,0x0007
         bne     TestArus_WBDZErr
         mov     cl,0x07
         mov     ewx,0x80000000
         xorzx   gx,cl,ewx
         cmp     gx,0x0007
         bne     TestArus_WBDZErr
         mov     dl,0x07
         mov     fwx,0x80000000
         mulzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x07
         mov     gwx,0x80000000
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x07
         mov     ar,0x80000000
         uremzx  cw,fl,ar
         cmp     cw,0x0007
         bne     TestArus_WBDZErr
         mov     gl,0x07
         mov     br,0x00000000
         shlzx   dw,gl,br
         cmp     dw,0x0007
         bne     TestArus_WBDZErr
         mov     ah,0x07
         mov     cr,0x00000000
         shrzx   ew,ah,cr
         cmp     ew,0x0007
         bne     TestArus_WBDZErr
         mov     bh,0x07
         mov     dr,0x00000000
         rolzx   fw,bh,dr
         cmp     fw,0x0007
         bne     TestArus_WBDZErr
         mov     ch,0x07
         mov     er,0x00000000
         asrzx   gw,ch,er
         cmp     gw,0x0007
         bne     TestArus_WBDZErr
         mov     dh,0x07
         mov     fr,0xFFFFFFFF
         addzx   ax,dh,fr
         cmp     ax,0x0006
         bne     TestArus_WBDZErr
         mov     eh,0x07
         mov     gr,0xFFFFFFFF
         subzx   bx,eh,gr
         cmp     bx,0x0008
         bne     TestArus_WBDZErr
         mov     fh,0x07
         mov     awx,0xFFFFFFFF
         andzx   cx,fh,awx
         cmp     cx,0x0007
         bne     TestArus_WBDZErr
         mov     gh,0x07
         mov     bwx,0xFFFFFFFF
         orzx    dx,gh,bwx
         cmp     dx,0xFFFF
         bne     TestArus_WBDZErr
         mov     al,0x07
         mov     cwx,0xFFFFFFFF
         xorzx   ex,al,cwx
         cmp     ex,0xFFF8
         bne     TestArus_WBDZErr
         mov     bl,0x07
         mov     dwx,0xFFFFFFFF
         mulzx   fx,bl,dwx
         cmp     fx,0xFFF9
         bne     TestArus_WBDZErr
         mov     cl,0x07
         mov     ewx,0xFFFFFFFF
         udivzx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x07
         mov     fwx,0xFFFFFFFF
         uremzx  aw,dl,fwx
         cmp     aw,0x0007
         bne     TestArus_WBDZErr
         mov     el,0x07
         mov     gwx,0x0000000F
         shlzx   bw,el,gwx
         cmp     bw,0x8000
         bne     TestArus_WBDZErr
         mov     fl,0x07
         mov     ar,0x0000000F
         shrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x07
         mov     br,0x0000000F
         rolzx   dw,gl,br
         cmp     dw,0x8003
         bne     TestArus_WBDZErr
         mov     ah,0x07
         mov     cr,0x0000000F
         asrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x08
         mov     dr,0x00000009
         addzx   fw,bh,dr
         cmp     fw,0x0011
         bne     TestArus_WBDZErr
         mov     ch,0x08
         mov     er,0x00000009
         subzx   gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDZErr
         mov     dh,0x08
         mov     fr,0x00000009
         andzx   ax,dh,fr
         cmp     ax,0x0008
         bne     TestArus_WBDZErr
         mov     eh,0x08
         mov     gr,0x00000009
         orzx    bx,eh,gr
         cmp     bx,0x0009
         bne     TestArus_WBDZErr
         mov     fh,0x08
         mov     awx,0x00000009
         xorzx   cx,fh,awx
         cmp     cx,0x0001
         bne     TestArus_WBDZErr
         mov     gh,0x08
         mov     bwx,0x00000009
         mulzx   dx,gh,bwx
         cmp     dx,0x0048
         bne     TestArus_WBDZErr
         mov     al,0x08
         mov     cwx,0x00000009
         udivzx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x08
         mov     dwx,0x00000009
         uremzx  fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDZErr
         mov     cl,0x08
         mov     ewx,0x00000009
         shlzx   gx,cl,ewx
         cmp     gx,0x1000
         bne     TestArus_WBDZErr
         mov     dl,0x08
         mov     fwx,0x00000009
         shrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x08
         mov     gwx,0x00000009
         rolzx   bw,el,gwx
         cmp     bw,0x1000
         bne     TestArus_WBDZErr
         mov     fl,0x08
         mov     ar,0x00000009
         asrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x08
         mov     br,0x00007FFF
         addzx   dw,gl,br
         cmp     dw,0x8007
         bne     TestArus_WBDZErr
         mov     ah,0x08
         mov     cr,0x00007FFF
         subzx   ew,ah,cr
         cmp     ew,0x8009
         bne     TestArus_WBDZErr
         mov     bh,0x08
         mov     dr,0x00007FFF
         andzx   fw,bh,dr
         cmp     fw,0x0008
         bne     TestArus_WBDZErr
         mov     ch,0x08
         mov     er,0x00007FFF
         orzx    gw,ch,er
         cmp     gw,0x7FFF
         bne     TestArus_WBDZErr
         mov     dh,0x08
         mov     fr,0x00007FFF
         xorzx   ax,dh,fr
         cmp     ax,0x7FF7
         bne     TestArus_WBDZErr
         mov     eh,0x08
         mov     gr,0x00007FFF
         mulzx   bx,eh,gr
         cmp     bx,0xFFF8
         bne     TestArus_WBDZErr
         mov     fh,0x08
         mov     awx,0x00007FFF
         udivzx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x08
         mov     bwx,0x00007FFF
         uremzx  dx,gh,bwx
         cmp     dx,0x0008
         bne     TestArus_WBDZErr
         mov     al,0x08
         mov     cwx,0x0000000F
         shlzx   ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x08
         mov     dwx,0x0000000F
         shrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x08
         mov     ewx,0x0000000F
         rolzx   gx,cl,ewx
         cmp     gx,0x0004
         bne     TestArus_WBDZErr
         mov     dl,0x08
         mov     fwx,0x0000000F
         asrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x08
         mov     gwx,0x00008000
         addzx   bw,el,gwx
         cmp     bw,0x8008
         bne     TestArus_WBDZErr
         mov     fl,0x08
         mov     ar,0x00008000
         subzx   cw,fl,ar
         cmp     cw,0x8008
         bne     TestArus_WBDZErr
         mov     gl,0x08
         mov     br,0x00008000
         andzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x08
         mov     cr,0x00008000
         orzx    ew,ah,cr
         cmp     ew,0x8008
         bne     TestArus_WBDZErr
         mov     bh,0x08
         mov     dr,0x00008000
         xorzx   fw,bh,dr
         cmp     fw,0x8008
         bne     TestArus_WBDZErr
         mov     ch,0x08
         mov     er,0x00008000
         mulzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x08
         mov     fr,0x00008000
         udivzx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x08
         mov     gr,0x00008000
         uremzx  bx,eh,gr
         cmp     bx,0x0008
         bne     TestArus_WBDZErr
         mov     fh,0x08
         mov     awx,0x00000000
         shlzx   cx,fh,awx
         cmp     cx,0x0008
         bne     TestArus_WBDZErr
         mov     gh,0x08
         mov     bwx,0x00000000
         shrzx   dx,gh,bwx
         cmp     dx,0x0008
         bne     TestArus_WBDZErr
         mov     al,0x08
         mov     cwx,0x00000000
         rolzx   ex,al,cwx
         cmp     ex,0x0008
         bne     TestArus_WBDZErr
         mov     bl,0x08
         mov     dwx,0x00000000
         asrzx   fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDZErr
         mov     cl,0x08
         mov     ewx,0x7FFFFFFF
         addzx   gx,cl,ewx
         cmp     gx,0x0007
         bne     TestArus_WBDZErr
         mov     dl,0x08
         mov     fwx,0x7FFFFFFF
         subzx   aw,dl,fwx
         cmp     aw,0x0009
         bne     TestArus_WBDZErr
         mov     el,0x08
         mov     gwx,0x7FFFFFFF
         andzx   bw,el,gwx
         cmp     bw,0x0008
         bne     TestArus_WBDZErr
         mov     fl,0x08
         mov     ar,0x7FFFFFFF
         orzx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDZErr
         mov     gl,0x08
         mov     br,0x7FFFFFFF
         xorzx   dw,gl,br
         cmp     dw,0xFFF7
         bne     TestArus_WBDZErr
         mov     ah,0x08
         mov     cr,0x7FFFFFFF
         mulzx   ew,ah,cr
         cmp     ew,0xFFF8
         bne     TestArus_WBDZErr
         mov     bh,0x08
         mov     dr,0x7FFFFFFF
         udivzx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x08
         mov     er,0x7FFFFFFF
         uremzx  gw,ch,er
         cmp     gw,0x0008
         bne     TestArus_WBDZErr
         mov     dh,0x08
         mov     fr,0x0000000F
         shlzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x08
         mov     gr,0x0000000F
         shrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x08
         mov     awx,0x0000000F
         rolzx   cx,fh,awx
         cmp     cx,0x0004
         bne     TestArus_WBDZErr
         mov     gh,0x08
         mov     bwx,0x0000000F
         asrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x08
         mov     cwx,0x80000000
         addzx   ex,al,cwx
         cmp     ex,0x0008
         bne     TestArus_WBDZErr
         mov     bl,0x08
         mov     dwx,0x80000000
         subzx   fx,bl,dwx
         cmp     fx,0x0008
         bne     TestArus_WBDZErr
         mov     cl,0x08
         mov     ewx,0x80000000
         andzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x08
         mov     fwx,0x80000000
         orzx    aw,dl,fwx
         cmp     aw,0x0008
         bne     TestArus_WBDZErr
         mov     el,0x08
         mov     gwx,0x80000000
         xorzx   bw,el,gwx
         cmp     bw,0x0008
         bne     TestArus_WBDZErr
         mov     fl,0x08
         mov     ar,0x80000000
         mulzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x08
         mov     br,0x80000000
         udivzx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x08
         mov     cr,0x80000000
         uremzx  ew,ah,cr
         cmp     ew,0x0008
         bne     TestArus_WBDZErr
         mov     bh,0x08
         mov     dr,0x00000000
         shlzx   fw,bh,dr
         cmp     fw,0x0008
         bne     TestArus_WBDZErr
         mov     ch,0x08
         mov     er,0x00000000
         shrzx   gw,ch,er
         cmp     gw,0x0008
         bne     TestArus_WBDZErr
         mov     dh,0x08
         mov     fr,0x00000000
         rolzx   ax,dh,fr
         cmp     ax,0x0008
         bne     TestArus_WBDZErr
         mov     eh,0x08
         mov     gr,0x00000000
         asrzx   bx,eh,gr
         cmp     bx,0x0008
         bne     TestArus_WBDZErr
         mov     fh,0x08
         mov     awx,0xFFFFFFFF
         addzx   cx,fh,awx
         cmp     cx,0x0007
         bne     TestArus_WBDZErr
         mov     gh,0x08
         mov     bwx,0xFFFFFFFF
         subzx   dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDZErr
         mov     al,0x08
         mov     cwx,0xFFFFFFFF
         andzx   ex,al,cwx
         cmp     ex,0x0008
         bne     TestArus_WBDZErr
         mov     bl,0x08
         mov     dwx,0xFFFFFFFF
         orzx    fx,bl,dwx
         cmp     fx,0xFFFF
         bne     TestArus_WBDZErr
         mov     cl,0x08
         mov     ewx,0xFFFFFFFF
         xorzx   gx,cl,ewx
         cmp     gx,0xFFF7
         bne     TestArus_WBDZErr
         mov     dl,0x08
         mov     fwx,0xFFFFFFFF
         mulzx   aw,dl,fwx
         cmp     aw,0xFFF8
         bne     TestArus_WBDZErr
         mov     el,0x08
         mov     gwx,0xFFFFFFFF
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x08
         mov     ar,0xFFFFFFFF
         uremzx  cw,fl,ar
         cmp     cw,0x0008
         bne     TestArus_WBDZErr
         mov     gl,0x08
         mov     br,0x0000000F
         shlzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x08
         mov     cr,0x0000000F
         shrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x08
         mov     dr,0x0000000F
         rolzx   fw,bh,dr
         cmp     fw,0x0004
         bne     TestArus_WBDZErr
         mov     ch,0x08
         mov     er,0x0000000F
         asrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x09
         mov     fr,0x00007FFF
         addzx   ax,dh,fr
         cmp     ax,0x8008
         bne     TestArus_WBDZErr
         mov     eh,0x09
         mov     gr,0x00007FFF
         subzx   bx,eh,gr
         cmp     bx,0x800A
         bne     TestArus_WBDZErr
         mov     fh,0x09
         mov     awx,0x00007FFF
         andzx   cx,fh,awx
         cmp     cx,0x0009
         bne     TestArus_WBDZErr
         mov     gh,0x09
         mov     bwx,0x00007FFF
         orzx    dx,gh,bwx
         cmp     dx,0x7FFF
         bne     TestArus_WBDZErr
         mov     al,0x09
         mov     cwx,0x00007FFF
         xorzx   ex,al,cwx
         cmp     ex,0x7FF6
         bne     TestArus_WBDZErr
         mov     bl,0x09
         mov     dwx,0x00007FFF
         mulzx   fx,bl,dwx
         cmp     fx,0x7FF7
         bne     TestArus_WBDZErr
         mov     cl,0x09
         mov     ewx,0x00007FFF
         udivzx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x09
         mov     fwx,0x00007FFF
         uremzx  aw,dl,fwx
         cmp     aw,0x0009
         bne     TestArus_WBDZErr
         mov     el,0x09
         mov     gwx,0x0000000F
         shlzx   bw,el,gwx
         cmp     bw,0x8000
         bne     TestArus_WBDZErr
         mov     fl,0x09
         mov     ar,0x0000000F
         shrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x09
         mov     br,0x0000000F
         rolzx   dw,gl,br
         cmp     dw,0x8004
         bne     TestArus_WBDZErr
         mov     ah,0x09
         mov     cr,0x0000000F
         asrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x09
         mov     dr,0x00008000
         addzx   fw,bh,dr
         cmp     fw,0x8009
         bne     TestArus_WBDZErr
         mov     ch,0x09
         mov     er,0x00008000
         subzx   gw,ch,er
         cmp     gw,0x8009
         bne     TestArus_WBDZErr
         mov     dh,0x09
         mov     fr,0x00008000
         andzx   ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x09
         mov     gr,0x00008000
         orzx    bx,eh,gr
         cmp     bx,0x8009
         bne     TestArus_WBDZErr
         mov     fh,0x09
         mov     awx,0x00008000
         xorzx   cx,fh,awx
         cmp     cx,0x8009
         bne     TestArus_WBDZErr
         mov     gh,0x09
         mov     bwx,0x00008000
         mulzx   dx,gh,bwx
         cmp     dx,0x8000
         bne     TestArus_WBDZErr
         mov     al,0x09
         mov     cwx,0x00008000
         udivzx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x09
         mov     dwx,0x00008000
         uremzx  fx,bl,dwx
         cmp     fx,0x0009
         bne     TestArus_WBDZErr
         mov     cl,0x09
         mov     ewx,0x00000000
         shlzx   gx,cl,ewx
         cmp     gx,0x0009
         bne     TestArus_WBDZErr
         mov     dl,0x09
         mov     fwx,0x00000000
         shrzx   aw,dl,fwx
         cmp     aw,0x0009
         bne     TestArus_WBDZErr
         mov     el,0x09
         mov     gwx,0x00000000
         rolzx   bw,el,gwx
         cmp     bw,0x0009
         bne     TestArus_WBDZErr
         mov     fl,0x09
         mov     ar,0x00000000
         asrzx   cw,fl,ar
         cmp     cw,0x0009
         bne     TestArus_WBDZErr
         mov     gl,0x09
         mov     br,0x7FFFFFFF
         addzx   dw,gl,br
         cmp     dw,0x0008
         bne     TestArus_WBDZErr
         mov     ah,0x09
         mov     cr,0x7FFFFFFF
         subzx   ew,ah,cr
         cmp     ew,0x000A
         bne     TestArus_WBDZErr
         mov     bh,0x09
         mov     dr,0x7FFFFFFF
         andzx   fw,bh,dr
         cmp     fw,0x0009
         bne     TestArus_WBDZErr
         mov     ch,0x09
         mov     er,0x7FFFFFFF
         orzx    gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDZErr
         mov     dh,0x09
         mov     fr,0x7FFFFFFF
         xorzx   ax,dh,fr
         cmp     ax,0xFFF6
         bne     TestArus_WBDZErr
         mov     eh,0x09
         mov     gr,0x7FFFFFFF
         mulzx   bx,eh,gr
         cmp     bx,0xFFF7
         bne     TestArus_WBDZErr
         mov     fh,0x09
         mov     awx,0x7FFFFFFF
         udivzx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x09
         mov     bwx,0x7FFFFFFF
         uremzx  dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDZErr
         mov     al,0x09
         mov     cwx,0x0000000F
         shlzx   ex,al,cwx
         cmp     ex,0x8000
         bne     TestArus_WBDZErr
         mov     bl,0x09
         mov     dwx,0x0000000F
         shrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x09
         mov     ewx,0x0000000F
         rolzx   gx,cl,ewx
         cmp     gx,0x8004
         bne     TestArus_WBDZErr
         mov     dl,0x09
         mov     fwx,0x0000000F
         asrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x09
         mov     gwx,0x80000000
         addzx   bw,el,gwx
         cmp     bw,0x0009
         bne     TestArus_WBDZErr
         mov     fl,0x09
         mov     ar,0x80000000
         subzx   cw,fl,ar
         cmp     cw,0x0009
         bne     TestArus_WBDZErr
         mov     gl,0x09
         mov     br,0x80000000
         andzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x09
         mov     cr,0x80000000
         orzx    ew,ah,cr
         cmp     ew,0x0009
         bne     TestArus_WBDZErr
         mov     bh,0x09
         mov     dr,0x80000000
         xorzx   fw,bh,dr
         cmp     fw,0x0009
         bne     TestArus_WBDZErr
         mov     ch,0x09
         mov     er,0x80000000
         mulzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x09
         mov     fr,0x80000000
         udivzx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x09
         mov     gr,0x80000000
         uremzx  bx,eh,gr
         cmp     bx,0x0009
         bne     TestArus_WBDZErr
         mov     fh,0x09
         mov     awx,0x00000000
         shlzx   cx,fh,awx
         cmp     cx,0x0009
         bne     TestArus_WBDZErr
         mov     gh,0x09
         mov     bwx,0x00000000
         shrzx   dx,gh,bwx
         cmp     dx,0x0009
         bne     TestArus_WBDZErr
         mov     al,0x09
         mov     cwx,0x00000000
         rolzx   ex,al,cwx
         cmp     ex,0x0009
         bne     TestArus_WBDZErr
         mov     bl,0x09
         mov     dwx,0x00000000
         asrzx   fx,bl,dwx
         cmp     fx,0x0009
         bne     TestArus_WBDZErr
         mov     cl,0x09
         mov     ewx,0xFFFFFFFF
         addzx   gx,cl,ewx
         cmp     gx,0x0008
         bne     TestArus_WBDZErr
         mov     dl,0x09
         mov     fwx,0xFFFFFFFF
         subzx   aw,dl,fwx
         cmp     aw,0x000A
         bne     TestArus_WBDZErr
         mov     el,0x09
         mov     gwx,0xFFFFFFFF
         andzx   bw,el,gwx
         cmp     bw,0x0009
         bne     TestArus_WBDZErr
         mov     fl,0x09
         mov     ar,0xFFFFFFFF
         orzx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDZErr
         mov     gl,0x09
         mov     br,0xFFFFFFFF
         xorzx   dw,gl,br
         cmp     dw,0xFFF6
         bne     TestArus_WBDZErr
         mov     ah,0x09
         mov     cr,0xFFFFFFFF
         mulzx   ew,ah,cr
         cmp     ew,0xFFF7
         bne     TestArus_WBDZErr
         mov     bh,0x09
         mov     dr,0xFFFFFFFF
         udivzx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x09
         mov     er,0xFFFFFFFF
         uremzx  gw,ch,er
         cmp     gw,0x0009
         bne     TestArus_WBDZErr
         mov     dh,0x09
         mov     fr,0x0000000F
         shlzx   ax,dh,fr
         cmp     ax,0x8000
         bne     TestArus_WBDZErr
         mov     eh,0x09
         mov     gr,0x0000000F
         shrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x09
         mov     awx,0x0000000F
         rolzx   cx,fh,awx
         cmp     cx,0x8004
         bne     TestArus_WBDZErr
         mov     gh,0x09
         mov     bwx,0x0000000F
         asrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x0F
         mov     cwx,0x00008000
         addzx   ex,al,cwx
         cmp     ex,0x800F
         bne     TestArus_WBDZErr
         mov     bl,0x0F
         mov     dwx,0x00008000
         subzx   fx,bl,dwx
         cmp     fx,0x800F
         bne     TestArus_WBDZErr
         mov     cl,0x0F
         mov     ewx,0x00008000
         andzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x0F
         mov     fwx,0x00008000
         orzx    aw,dl,fwx
         cmp     aw,0x800F
         bne     TestArus_WBDZErr
         mov     el,0x0F
         mov     gwx,0x00008000
         xorzx   bw,el,gwx
         cmp     bw,0x800F
         bne     TestArus_WBDZErr
         mov     fl,0x0F
         mov     ar,0x00008000
         mulzx   cw,fl,ar
         cmp     cw,0x8000
         bne     TestArus_WBDZErr
         mov     gl,0x0F
         mov     br,0x00008000
         udivzx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x0F
         mov     cr,0x00008000
         uremzx  ew,ah,cr
         cmp     ew,0x000F
         bne     TestArus_WBDZErr
         mov     bh,0x0F
         mov     dr,0x00000000
         shlzx   fw,bh,dr
         cmp     fw,0x000F
         bne     TestArus_WBDZErr
         mov     ch,0x0F
         mov     er,0x00000000
         shrzx   gw,ch,er
         cmp     gw,0x000F
         bne     TestArus_WBDZErr
         mov     dh,0x0F
         mov     fr,0x00000000
         rolzx   ax,dh,fr
         cmp     ax,0x000F
         bne     TestArus_WBDZErr
         mov     eh,0x0F
         mov     gr,0x00000000
         asrzx   bx,eh,gr
         cmp     bx,0x000F
         bne     TestArus_WBDZErr
         mov     fh,0x0F
         mov     awx,0x7FFFFFFF
         addzx   cx,fh,awx
         cmp     cx,0x000E
         bne     TestArus_WBDZErr
         mov     gh,0x0F
         mov     bwx,0x7FFFFFFF
         subzx   dx,gh,bwx
         cmp     dx,0x0010
         bne     TestArus_WBDZErr
         mov     al,0x0F
         mov     cwx,0x7FFFFFFF
         andzx   ex,al,cwx
         cmp     ex,0x000F
         bne     TestArus_WBDZErr
         mov     bl,0x0F
         mov     dwx,0x7FFFFFFF
         orzx    fx,bl,dwx
         cmp     fx,0xFFFF
         bne     TestArus_WBDZErr
         mov     cl,0x0F
         mov     ewx,0x7FFFFFFF
         xorzx   gx,cl,ewx
         cmp     gx,0xFFF0
         bne     TestArus_WBDZErr
         mov     dl,0x0F
         mov     fwx,0x7FFFFFFF
         mulzx   aw,dl,fwx
         cmp     aw,0xFFF1
         bne     TestArus_WBDZErr
         mov     el,0x0F
         mov     gwx,0x7FFFFFFF
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x0F
         mov     ar,0x7FFFFFFF
         uremzx  cw,fl,ar
         cmp     cw,0x000F
         bne     TestArus_WBDZErr
         mov     gl,0x0F
         mov     br,0x0000000F
         shlzx   dw,gl,br
         cmp     dw,0x8000
         bne     TestArus_WBDZErr
         mov     ah,0x0F
         mov     cr,0x0000000F
         shrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x0F
         mov     dr,0x0000000F
         rolzx   fw,bh,dr
         cmp     fw,0x8007
         bne     TestArus_WBDZErr
         mov     ch,0x0F
         mov     er,0x0000000F
         asrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x0F
         mov     fr,0x80000000
         addzx   ax,dh,fr
         cmp     ax,0x000F
         bne     TestArus_WBDZErr
         mov     eh,0x0F
         mov     gr,0x80000000
         subzx   bx,eh,gr
         cmp     bx,0x000F
         bne     TestArus_WBDZErr
         mov     fh,0x0F
         mov     awx,0x80000000
         andzx   cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x0F
         mov     bwx,0x80000000
         orzx    dx,gh,bwx
         cmp     dx,0x000F
         bne     TestArus_WBDZErr
         mov     al,0x0F
         mov     cwx,0x80000000
         xorzx   ex,al,cwx
         cmp     ex,0x000F
         bne     TestArus_WBDZErr
         mov     bl,0x0F
         mov     dwx,0x80000000
         mulzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x0F
         mov     ewx,0x80000000
         udivzx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x0F
         mov     fwx,0x80000000
         uremzx  aw,dl,fwx
         cmp     aw,0x000F
         bne     TestArus_WBDZErr
         mov     el,0x0F
         mov     gwx,0x00000000
         shlzx   bw,el,gwx
         cmp     bw,0x000F
         bne     TestArus_WBDZErr
         mov     fl,0x0F
         mov     ar,0x00000000
         shrzx   cw,fl,ar
         cmp     cw,0x000F
         bne     TestArus_WBDZErr
         mov     gl,0x0F
         mov     br,0x00000000
         rolzx   dw,gl,br
         cmp     dw,0x000F
         bne     TestArus_WBDZErr
         mov     ah,0x0F
         mov     cr,0x00000000
         asrzx   ew,ah,cr
         cmp     ew,0x000F
         bne     TestArus_WBDZErr
         mov     bh,0x0F
         mov     dr,0xFFFFFFFF
         addzx   fw,bh,dr
         cmp     fw,0x000E
         bne     TestArus_WBDZErr
         mov     ch,0x0F
         mov     er,0xFFFFFFFF
         subzx   gw,ch,er
         cmp     gw,0x0010
         bne     TestArus_WBDZErr
         mov     dh,0x0F
         mov     fr,0xFFFFFFFF
         andzx   ax,dh,fr
         cmp     ax,0x000F
         bne     TestArus_WBDZErr
         mov     eh,0x0F
         mov     gr,0xFFFFFFFF
         orzx    bx,eh,gr
         cmp     bx,0xFFFF
         bne     TestArus_WBDZErr
         mov     fh,0x0F
         mov     awx,0xFFFFFFFF
         xorzx   cx,fh,awx
         cmp     cx,0xFFF0
         bne     TestArus_WBDZErr
         mov     gh,0x0F
         mov     bwx,0xFFFFFFFF
         mulzx   dx,gh,bwx
         cmp     dx,0xFFF1
         bne     TestArus_WBDZErr
         mov     al,0x0F
         mov     cwx,0xFFFFFFFF
         udivzx  ex,al,cwx
         cmp     ex,0x0000
         bne     TestArus_WBDZErr
         mov     bl,0x0F
         mov     dwx,0xFFFFFFFF
         uremzx  fx,bl,dwx
         cmp     fx,0x000F
         bne     TestArus_WBDZErr
         mov     cl,0x0F
         mov     ewx,0x0000000F
         shlzx   gx,cl,ewx
         cmp     gx,0x8000
         bne     TestArus_WBDZErr
         mov     dl,0x0F
         mov     fwx,0x0000000F
         shrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x0F
         mov     gwx,0x0000000F
         rolzx   bw,el,gwx
         cmp     bw,0x8007
         bne     TestArus_WBDZErr
         mov     fl,0x0F
         mov     ar,0x0000000F
         asrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x7F
         mov     br,0x7FFFFFFF
         addzx   dw,gl,br
         cmp     dw,0x007E
         bne     TestArus_WBDZErr
         mov     ah,0x7F
         mov     cr,0x7FFFFFFF
         subzx   ew,ah,cr
         cmp     ew,0x0080
         bne     TestArus_WBDZErr
         mov     bh,0x7F
         mov     dr,0x7FFFFFFF
         andzx   fw,bh,dr
         cmp     fw,0x007F
         bne     TestArus_WBDZErr
         mov     ch,0x7F
         mov     er,0x7FFFFFFF
         orzx    gw,ch,er
         cmp     gw,0xFFFF
         bne     TestArus_WBDZErr
         mov     dh,0x7F
         mov     fr,0x7FFFFFFF
         xorzx   ax,dh,fr
         cmp     ax,0xFF80
         bne     TestArus_WBDZErr
         mov     eh,0x7F
         mov     gr,0x7FFFFFFF
         mulzx   bx,eh,gr
         cmp     bx,0xFF81
         bne     TestArus_WBDZErr
         mov     fh,0x7F
         mov     awx,0x7FFFFFFF
         udivzx  cx,fh,awx
         cmp     cx,0x0000
         bne     TestArus_WBDZErr
         mov     gh,0x7F
         mov     bwx,0x7FFFFFFF
         uremzx  dx,gh,bwx
         cmp     dx,0x007F
         bne     TestArus_WBDZErr
         mov     al,0x7F
         mov     cwx,0x0000000F
         shlzx   ex,al,cwx
         cmp     ex,0x8000
         bne     TestArus_WBDZErr
         mov     bl,0x7F
         mov     dwx,0x0000000F
         shrzx   fx,bl,dwx
         cmp     fx,0x0000
         bne     TestArus_WBDZErr
         mov     cl,0x7F
         mov     ewx,0x0000000F
         rolzx   gx,cl,ewx
         cmp     gx,0x803F
         bne     TestArus_WBDZErr
         mov     dl,0x7F
         mov     fwx,0x0000000F
         asrzx   aw,dl,fwx
         cmp     aw,0x0000
         bne     TestArus_WBDZErr
         mov     el,0x7F
         mov     gwx,0x80000000
         addzx   bw,el,gwx
         cmp     bw,0x007F
         bne     TestArus_WBDZErr
         mov     fl,0x7F
         mov     ar,0x80000000
         subzx   cw,fl,ar
         cmp     cw,0x007F
         bne     TestArus_WBDZErr
         mov     gl,0x7F
         mov     br,0x80000000
         andzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x7F
         mov     cr,0x80000000
         orzx    ew,ah,cr
         cmp     ew,0x007F
         bne     TestArus_WBDZErr
         mov     bh,0x7F
         mov     dr,0x80000000
         xorzx   fw,bh,dr
         cmp     fw,0x007F
         bne     TestArus_WBDZErr
         mov     ch,0x7F
         mov     er,0x80000000
         mulzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0x7F
         mov     fr,0x80000000
         udivzx  ax,dh,fr
         cmp     ax,0x0000
         bne     TestArus_WBDZErr
         mov     eh,0x7F
         mov     gr,0x80000000
         uremzx  bx,eh,gr
         cmp     bx,0x007F
         bne     TestArus_WBDZErr
         mov     fh,0x7F
         mov     awx,0x00000000
         shlzx   cx,fh,awx
         cmp     cx,0x007F
         bne     TestArus_WBDZErr
         mov     gh,0x7F
         mov     bwx,0x00000000
         shrzx   dx,gh,bwx
         cmp     dx,0x007F
         bne     TestArus_WBDZErr
         mov     al,0x7F
         mov     cwx,0x00000000
         rolzx   ex,al,cwx
         cmp     ex,0x007F
         bne     TestArus_WBDZErr
         mov     bl,0x7F
         mov     dwx,0x00000000
         asrzx   fx,bl,dwx
         cmp     fx,0x007F
         bne     TestArus_WBDZErr
         mov     cl,0x7F
         mov     ewx,0xFFFFFFFF
         addzx   gx,cl,ewx
         cmp     gx,0x007E
         bne     TestArus_WBDZErr
         mov     dl,0x7F
         mov     fwx,0xFFFFFFFF
         subzx   aw,dl,fwx
         cmp     aw,0x0080
         bne     TestArus_WBDZErr
         mov     el,0x7F
         mov     gwx,0xFFFFFFFF
         andzx   bw,el,gwx
         cmp     bw,0x007F
         bne     TestArus_WBDZErr
         mov     fl,0x7F
         mov     ar,0xFFFFFFFF
         orzx    cw,fl,ar
         cmp     cw,0xFFFF
         bne     TestArus_WBDZErr
         mov     gl,0x7F
         mov     br,0xFFFFFFFF
         xorzx   dw,gl,br
         cmp     dw,0xFF80
         bne     TestArus_WBDZErr
         mov     ah,0x7F
         mov     cr,0xFFFFFFFF
         mulzx   ew,ah,cr
         cmp     ew,0xFF81
         bne     TestArus_WBDZErr
         mov     bh,0x7F
         mov     dr,0xFFFFFFFF
         udivzx  fw,bh,dr
         cmp     fw,0x0000
         bne     TestArus_WBDZErr
         mov     ch,0x7F
         mov     er,0xFFFFFFFF
         uremzx  gw,ch,er
         cmp     gw,0x007F
         bne     TestArus_WBDZErr
         mov     dh,0x7F
         mov     fr,0x0000000F
         shlzx   ax,dh,fr
         cmp     ax,0x8000
         bne     TestArus_WBDZErr
         mov     eh,0x7F
         mov     gr,0x0000000F
         shrzx   bx,eh,gr
         cmp     bx,0x0000
         bne     TestArus_WBDZErr
         mov     fh,0x7F
         mov     awx,0x0000000F
         rolzx   cx,fh,awx
         cmp     cx,0x803F
         bne     TestArus_WBDZErr
         mov     gh,0x7F
         mov     bwx,0x0000000F
         asrzx   dx,gh,bwx
         cmp     dx,0x0000
         bne     TestArus_WBDZErr
         mov     al,0x80
         mov     cwx,0x80000000
         addzx   ex,al,cwx
         cmp     ex,0x0080
         bne     TestArus_WBDZErr
         mov     bl,0x80
         mov     dwx,0x80000000
         subzx   fx,bl,dwx
         cmp     fx,0x0080
         bne     TestArus_WBDZErr
         mov     cl,0x80
         mov     ewx,0x80000000
         andzx   gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0x80
         mov     fwx,0x80000000
         orzx    aw,dl,fwx
         cmp     aw,0x0080
         bne     TestArus_WBDZErr
         mov     el,0x80
         mov     gwx,0x80000000
         xorzx   bw,el,gwx
         cmp     bw,0x0080
         bne     TestArus_WBDZErr
         mov     fl,0x80
         mov     ar,0x80000000
         mulzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0x80
         mov     br,0x80000000
         udivzx  dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x80
         mov     cr,0x80000000
         uremzx  ew,ah,cr
         cmp     ew,0x0080
         bne     TestArus_WBDZErr
         mov     bh,0x80
         mov     dr,0x00000000
         shlzx   fw,bh,dr
         cmp     fw,0x0080
         bne     TestArus_WBDZErr
         mov     ch,0x80
         mov     er,0x00000000
         shrzx   gw,ch,er
         cmp     gw,0x0080
         bne     TestArus_WBDZErr
         mov     dh,0x80
         mov     fr,0x00000000
         rolzx   ax,dh,fr
         cmp     ax,0x0080
         bne     TestArus_WBDZErr
         mov     eh,0x80
         mov     gr,0x00000000
         asrzx   bx,eh,gr
         cmp     bx,0x0080
         bne     TestArus_WBDZErr
         mov     fh,0x80
         mov     awx,0xFFFFFFFF
         addzx   cx,fh,awx
         cmp     cx,0x007F
         bne     TestArus_WBDZErr
         mov     gh,0x80
         mov     bwx,0xFFFFFFFF
         subzx   dx,gh,bwx
         cmp     dx,0x0081
         bne     TestArus_WBDZErr
         mov     al,0x80
         mov     cwx,0xFFFFFFFF
         andzx   ex,al,cwx
         cmp     ex,0x0080
         bne     TestArus_WBDZErr
         mov     bl,0x80
         mov     dwx,0xFFFFFFFF
         orzx    fx,bl,dwx
         cmp     fx,0xFFFF
         bne     TestArus_WBDZErr
         mov     cl,0x80
         mov     ewx,0xFFFFFFFF
         xorzx   gx,cl,ewx
         cmp     gx,0xFF7F
         bne     TestArus_WBDZErr
         mov     dl,0x80
         mov     fwx,0xFFFFFFFF
         mulzx   aw,dl,fwx
         cmp     aw,0xFF80
         bne     TestArus_WBDZErr
         mov     el,0x80
         mov     gwx,0xFFFFFFFF
         udivzx  bw,el,gwx
         cmp     bw,0x0000
         bne     TestArus_WBDZErr
         mov     fl,0x80
         mov     ar,0xFFFFFFFF
         uremzx  cw,fl,ar
         cmp     cw,0x0080
         bne     TestArus_WBDZErr
         mov     gl,0x80
         mov     br,0x0000000F
         shlzx   dw,gl,br
         cmp     dw,0x0000
         bne     TestArus_WBDZErr
         mov     ah,0x80
         mov     cr,0x0000000F
         shrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         mov     bh,0x80
         mov     dr,0x0000000F
         rolzx   fw,bh,dr
         cmp     fw,0x0040
         bne     TestArus_WBDZErr
         mov     ch,0x80
         mov     er,0x0000000F
         asrzx   gw,ch,er
         cmp     gw,0x0000
         bne     TestArus_WBDZErr
         mov     dh,0xFF
         mov     fr,0xFFFFFFFF
         addzx   ax,dh,fr
         cmp     ax,0x00FE
         bne     TestArus_WBDZErr
         mov     eh,0xFF
         mov     gr,0xFFFFFFFF
         subzx   bx,eh,gr
         cmp     bx,0x0100
         bne     TestArus_WBDZErr
         mov     fh,0xFF
         mov     awx,0xFFFFFFFF
         andzx   cx,fh,awx
         cmp     cx,0x00FF
         bne     TestArus_WBDZErr
         mov     gh,0xFF
         mov     bwx,0xFFFFFFFF
         orzx    dx,gh,bwx
         cmp     dx,0xFFFF
         bne     TestArus_WBDZErr
         mov     al,0xFF
         mov     cwx,0xFFFFFFFF
         xorzx   ex,al,cwx
         cmp     ex,0xFF00
         bne     TestArus_WBDZErr
         mov     bl,0xFF
         mov     dwx,0xFFFFFFFF
         mulzx   fx,bl,dwx
         cmp     fx,0xFF01
         bne     TestArus_WBDZErr
         mov     cl,0xFF
         mov     ewx,0xFFFFFFFF
         udivzx  gx,cl,ewx
         cmp     gx,0x0000
         bne     TestArus_WBDZErr
         mov     dl,0xFF
         mov     fwx,0xFFFFFFFF
         uremzx  aw,dl,fwx
         cmp     aw,0x00FF
         bne     TestArus_WBDZErr
         mov     el,0xFF
         mov     gwx,0x0000000F
         shlzx   bw,el,gwx
         cmp     bw,0x8000
         bne     TestArus_WBDZErr
         mov     fl,0xFF
         mov     ar,0x0000000F
         shrzx   cw,fl,ar
         cmp     cw,0x0000
         bne     TestArus_WBDZErr
         mov     gl,0xFF
         mov     br,0x0000000F
         rolzx   dw,gl,br
         cmp     dw,0x807F
         bne     TestArus_WBDZErr
         mov     ah,0xFF
         mov     cr,0x0000000F
         asrzx   ew,ah,cr
         cmp     ew,0x0000
         bne     TestArus_WBDZErr
         bra     TestArus_WBDZRet
TestArus_WBDZErr:
         nop     
         trap    
         nop     
TestArus_WBDZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
