.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArui_WWZ

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArui_WWZ:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         addzx   ex,ax,0x00
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0000
         subzx   fx,bx,0x00
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0000
         andzx   gx,cx,0x00
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0000
         orzx    aw,dx,0x00
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0000
         xorzx   bw,ex,0x00
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0000
         mulzx   cw,fx,0x00
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0000
         udivzx  dw,gx,0x00
         cmp     dw,0xFFFF
         bne     TestArui_WWZErr
         mov     aw,0x0000
         uremzx  ew,aw,0x00
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0000
         shlzx   fw,bw,0x00
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0000
         shrzx   gw,cw,0x00
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0000
         rolzx   ax,dw,0x00
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0000
         asrzx   bx,ew,0x00
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0000
         addzx   cx,fw,0x01
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x0000
         subzx   dx,gw,0x01
         cmp     dx,0xFFFF
         bne     TestArui_WWZErr
         mov     ax,0x0000
         andzx   ex,ax,0x01
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0000
         orzx    fx,bx,0x01
         cmp     fx,0x0001
         bne     TestArui_WWZErr
         mov     cx,0x0000
         xorzx   gx,cx,0x01
         cmp     gx,0x0001
         bne     TestArui_WWZErr
         mov     dx,0x0000
         mulzx   aw,dx,0x01
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0000
         udivzx  bw,ex,0x01
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0000
         uremzx  cw,fx,0x01
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0000
         shlzx   dw,gx,0x01
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0000
         shrzx   ew,aw,0x01
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0000
         rolzx   fw,bw,0x01
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0000
         asrzx   gw,cw,0x01
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0000
         addzx   ax,dw,0x07
         cmp     ax,0x0007
         bne     TestArui_WWZErr
         mov     ew,0x0000
         subzx   bx,ew,0x07
         cmp     bx,0xFFF9
         bne     TestArui_WWZErr
         mov     fw,0x0000
         andzx   cx,fw,0x07
         cmp     cx,0x0000
         bne     TestArui_WWZErr
         mov     gw,0x0000
         orzx    dx,gw,0x07
         cmp     dx,0x0007
         bne     TestArui_WWZErr
         mov     ax,0x0000
         xorzx   ex,ax,0x07
         cmp     ex,0x0007
         bne     TestArui_WWZErr
         mov     bx,0x0000
         mulzx   fx,bx,0x07
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0000
         udivzx  gx,cx,0x07
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0000
         uremzx  aw,dx,0x07
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0000
         shlzx   bw,ex,0x07
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0000
         shrzx   cw,fx,0x07
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0000
         rolzx   dw,gx,0x07
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0000
         asrzx   ew,aw,0x07
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0000
         addzx   fw,bw,0x08
         cmp     fw,0x0008
         bne     TestArui_WWZErr
         mov     cw,0x0000
         subzx   gw,cw,0x08
         cmp     gw,0xFFF8
         bne     TestArui_WWZErr
         mov     dw,0x0000
         andzx   ax,dw,0x08
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0000
         orzx    bx,ew,0x08
         cmp     bx,0x0008
         bne     TestArui_WWZErr
         mov     fw,0x0000
         xorzx   cx,fw,0x08
         cmp     cx,0x0008
         bne     TestArui_WWZErr
         mov     gw,0x0000
         mulzx   dx,gw,0x08
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0000
         udivzx  ex,ax,0x08
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0000
         uremzx  fx,bx,0x08
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0000
         shlzx   gx,cx,0x08
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0000
         shrzx   aw,dx,0x08
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0000
         rolzx   bw,ex,0x08
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0000
         asrzx   cw,fx,0x08
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0000
         addzx   dw,gx,0x09
         cmp     dw,0x0009
         bne     TestArui_WWZErr
         mov     aw,0x0000
         subzx   ew,aw,0x09
         cmp     ew,0xFFF7
         bne     TestArui_WWZErr
         mov     bw,0x0000
         andzx   fw,bw,0x09
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0000
         orzx    gw,cw,0x09
         cmp     gw,0x0009
         bne     TestArui_WWZErr
         mov     dw,0x0000
         xorzx   ax,dw,0x09
         cmp     ax,0x0009
         bne     TestArui_WWZErr
         mov     ew,0x0000
         mulzx   bx,ew,0x09
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0000
         udivzx  cx,fw,0x09
         cmp     cx,0x0000
         bne     TestArui_WWZErr
         mov     gw,0x0000
         uremzx  dx,gw,0x09
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0000
         shlzx   ex,ax,0x09
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0000
         shrzx   fx,bx,0x09
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0000
         rolzx   gx,cx,0x09
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0000
         asrzx   aw,dx,0x09
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0000
         addzx   bw,ex,0x0F
         cmp     bw,0x000F
         bne     TestArui_WWZErr
         mov     fx,0x0000
         subzx   cw,fx,0x0F
         cmp     cw,0xFFF1
         bne     TestArui_WWZErr
         mov     gx,0x0000
         andzx   dw,gx,0x0F
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0000
         orzx    ew,aw,0x0F
         cmp     ew,0x000F
         bne     TestArui_WWZErr
         mov     bw,0x0000
         xorzx   fw,bw,0x0F
         cmp     fw,0x000F
         bne     TestArui_WWZErr
         mov     cw,0x0000
         mulzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0000
         udivzx  ax,dw,0x0F
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0000
         uremzx  bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0000
         shlzx   cx,fw,0x0F
         cmp     cx,0x0000
         bne     TestArui_WWZErr
         mov     gw,0x0000
         shrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0000
         rolzx   ex,ax,0x0F
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0000
         asrzx   fx,bx,0x0F
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0000
         addzx   gx,cx,0x7F
         cmp     gx,0x007F
         bne     TestArui_WWZErr
         mov     dx,0x0000
         subzx   aw,dx,0x7F
         cmp     aw,0xFF81
         bne     TestArui_WWZErr
         mov     ex,0x0000
         andzx   bw,ex,0x7F
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0000
         orzx    cw,fx,0x7F
         cmp     cw,0x007F
         bne     TestArui_WWZErr
         mov     gx,0x0000
         xorzx   dw,gx,0x7F
         cmp     dw,0x007F
         bne     TestArui_WWZErr
         mov     aw,0x0000
         mulzx   ew,aw,0x7F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0000
         udivzx  fw,bw,0x7F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0000
         uremzx  gw,cw,0x7F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0000
         shlzx   ax,dw,0x0F
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0000
         shrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0000
         rolzx   cx,fw,0x0F
         cmp     cx,0x0000
         bne     TestArui_WWZErr
         mov     gw,0x0000
         asrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0000
         addzx   ex,ax,0x80
         cmp     ex,0x0080
         bne     TestArui_WWZErr
         mov     bx,0x0000
         subzx   fx,bx,0x80
         cmp     fx,0xFF80
         bne     TestArui_WWZErr
         mov     cx,0x0000
         andzx   gx,cx,0x80
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0000
         orzx    aw,dx,0x80
         cmp     aw,0x0080
         bne     TestArui_WWZErr
         mov     ex,0x0000
         xorzx   bw,ex,0x80
         cmp     bw,0x0080
         bne     TestArui_WWZErr
         mov     fx,0x0000
         mulzx   cw,fx,0x80
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0000
         udivzx  dw,gx,0x80
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0000
         uremzx  ew,aw,0x80
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0000
         shlzx   fw,bw,0x00
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0000
         shrzx   gw,cw,0x00
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0000
         rolzx   ax,dw,0x00
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0000
         asrzx   bx,ew,0x00
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0000
         addzx   cx,fw,0xFF
         cmp     cx,0x00FF
         bne     TestArui_WWZErr
         mov     gw,0x0000
         subzx   dx,gw,0xFF
         cmp     dx,0xFF01
         bne     TestArui_WWZErr
         mov     ax,0x0000
         andzx   ex,ax,0xFF
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0000
         orzx    fx,bx,0xFF
         cmp     fx,0x00FF
         bne     TestArui_WWZErr
         mov     cx,0x0000
         xorzx   gx,cx,0xFF
         cmp     gx,0x00FF
         bne     TestArui_WWZErr
         mov     dx,0x0000
         mulzx   aw,dx,0xFF
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0000
         udivzx  bw,ex,0xFF
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0000
         uremzx  cw,fx,0xFF
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0000
         shlzx   dw,gx,0x0F
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0000
         shrzx   ew,aw,0x0F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0000
         rolzx   fw,bw,0x0F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0000
         asrzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0001
         addzx   ax,dw,0x01
         cmp     ax,0x0002
         bne     TestArui_WWZErr
         mov     ew,0x0001
         subzx   bx,ew,0x01
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0001
         andzx   cx,fw,0x01
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x0001
         orzx    dx,gw,0x01
         cmp     dx,0x0001
         bne     TestArui_WWZErr
         mov     ax,0x0001
         xorzx   ex,ax,0x01
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0001
         mulzx   fx,bx,0x01
         cmp     fx,0x0001
         bne     TestArui_WWZErr
         mov     cx,0x0001
         udivzx  gx,cx,0x01
         cmp     gx,0x0001
         bne     TestArui_WWZErr
         mov     dx,0x0001
         uremzx  aw,dx,0x01
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0001
         shlzx   bw,ex,0x01
         cmp     bw,0x0002
         bne     TestArui_WWZErr
         mov     fx,0x0001
         shrzx   cw,fx,0x01
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0001
         rolzx   dw,gx,0x01
         cmp     dw,0x0002
         bne     TestArui_WWZErr
         mov     aw,0x0001
         asrzx   ew,aw,0x01
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0001
         addzx   fw,bw,0x07
         cmp     fw,0x0008
         bne     TestArui_WWZErr
         mov     cw,0x0001
         subzx   gw,cw,0x07
         cmp     gw,0xFFFA
         bne     TestArui_WWZErr
         mov     dw,0x0001
         andzx   ax,dw,0x07
         cmp     ax,0x0001
         bne     TestArui_WWZErr
         mov     ew,0x0001
         orzx    bx,ew,0x07
         cmp     bx,0x0007
         bne     TestArui_WWZErr
         mov     fw,0x0001
         xorzx   cx,fw,0x07
         cmp     cx,0x0006
         bne     TestArui_WWZErr
         mov     gw,0x0001
         mulzx   dx,gw,0x07
         cmp     dx,0x0007
         bne     TestArui_WWZErr
         mov     ax,0x0001
         udivzx  ex,ax,0x07
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0001
         uremzx  fx,bx,0x07
         cmp     fx,0x0001
         bne     TestArui_WWZErr
         mov     cx,0x0001
         shlzx   gx,cx,0x07
         cmp     gx,0x0080
         bne     TestArui_WWZErr
         mov     dx,0x0001
         shrzx   aw,dx,0x07
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0001
         rolzx   bw,ex,0x07
         cmp     bw,0x0080
         bne     TestArui_WWZErr
         mov     fx,0x0001
         asrzx   cw,fx,0x07
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0001
         addzx   dw,gx,0x08
         cmp     dw,0x0009
         bne     TestArui_WWZErr
         mov     aw,0x0001
         subzx   ew,aw,0x08
         cmp     ew,0xFFF9
         bne     TestArui_WWZErr
         mov     bw,0x0001
         andzx   fw,bw,0x08
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0001
         orzx    gw,cw,0x08
         cmp     gw,0x0009
         bne     TestArui_WWZErr
         mov     dw,0x0001
         xorzx   ax,dw,0x08
         cmp     ax,0x0009
         bne     TestArui_WWZErr
         mov     ew,0x0001
         mulzx   bx,ew,0x08
         cmp     bx,0x0008
         bne     TestArui_WWZErr
         mov     fw,0x0001
         udivzx  cx,fw,0x08
         cmp     cx,0x0000
         bne     TestArui_WWZErr
         mov     gw,0x0001
         uremzx  dx,gw,0x08
         cmp     dx,0x0001
         bne     TestArui_WWZErr
         mov     ax,0x0001
         shlzx   ex,ax,0x08
         cmp     ex,0x0100
         bne     TestArui_WWZErr
         mov     bx,0x0001
         shrzx   fx,bx,0x08
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0001
         rolzx   gx,cx,0x08
         cmp     gx,0x0100
         bne     TestArui_WWZErr
         mov     dx,0x0001
         asrzx   aw,dx,0x08
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0001
         addzx   bw,ex,0x09
         cmp     bw,0x000A
         bne     TestArui_WWZErr
         mov     fx,0x0001
         subzx   cw,fx,0x09
         cmp     cw,0xFFF8
         bne     TestArui_WWZErr
         mov     gx,0x0001
         andzx   dw,gx,0x09
         cmp     dw,0x0001
         bne     TestArui_WWZErr
         mov     aw,0x0001
         orzx    ew,aw,0x09
         cmp     ew,0x0009
         bne     TestArui_WWZErr
         mov     bw,0x0001
         xorzx   fw,bw,0x09
         cmp     fw,0x0008
         bne     TestArui_WWZErr
         mov     cw,0x0001
         mulzx   gw,cw,0x09
         cmp     gw,0x0009
         bne     TestArui_WWZErr
         mov     dw,0x0001
         udivzx  ax,dw,0x09
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0001
         uremzx  bx,ew,0x09
         cmp     bx,0x0001
         bne     TestArui_WWZErr
         mov     fw,0x0001
         shlzx   cx,fw,0x09
         cmp     cx,0x0200
         bne     TestArui_WWZErr
         mov     gw,0x0001
         shrzx   dx,gw,0x09
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0001
         rolzx   ex,ax,0x09
         cmp     ex,0x0200
         bne     TestArui_WWZErr
         mov     bx,0x0001
         asrzx   fx,bx,0x09
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0001
         addzx   gx,cx,0x0F
         cmp     gx,0x0010
         bne     TestArui_WWZErr
         mov     dx,0x0001
         subzx   aw,dx,0x0F
         cmp     aw,0xFFF2
         bne     TestArui_WWZErr
         mov     ex,0x0001
         andzx   bw,ex,0x0F
         cmp     bw,0x0001
         bne     TestArui_WWZErr
         mov     fx,0x0001
         orzx    cw,fx,0x0F
         cmp     cw,0x000F
         bne     TestArui_WWZErr
         mov     gx,0x0001
         xorzx   dw,gx,0x0F
         cmp     dw,0x000E
         bne     TestArui_WWZErr
         mov     aw,0x0001
         mulzx   ew,aw,0x0F
         cmp     ew,0x000F
         bne     TestArui_WWZErr
         mov     bw,0x0001
         udivzx  fw,bw,0x0F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0001
         uremzx  gw,cw,0x0F
         cmp     gw,0x0001
         bne     TestArui_WWZErr
         mov     dw,0x0001
         shlzx   ax,dw,0x0F
         cmp     ax,0x8000
         bne     TestArui_WWZErr
         mov     ew,0x0001
         shrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0001
         rolzx   cx,fw,0x0F
         cmp     cx,0x8000
         bne     TestArui_WWZErr
         mov     gw,0x0001
         asrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0001
         addzx   ex,ax,0x7F
         cmp     ex,0x0080
         bne     TestArui_WWZErr
         mov     bx,0x0001
         subzx   fx,bx,0x7F
         cmp     fx,0xFF82
         bne     TestArui_WWZErr
         mov     cx,0x0001
         andzx   gx,cx,0x7F
         cmp     gx,0x0001
         bne     TestArui_WWZErr
         mov     dx,0x0001
         orzx    aw,dx,0x7F
         cmp     aw,0x007F
         bne     TestArui_WWZErr
         mov     ex,0x0001
         xorzx   bw,ex,0x7F
         cmp     bw,0x007E
         bne     TestArui_WWZErr
         mov     fx,0x0001
         mulzx   cw,fx,0x7F
         cmp     cw,0x007F
         bne     TestArui_WWZErr
         mov     gx,0x0001
         udivzx  dw,gx,0x7F
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0001
         uremzx  ew,aw,0x7F
         cmp     ew,0x0001
         bne     TestArui_WWZErr
         mov     bw,0x0001
         shlzx   fw,bw,0x0F
         cmp     fw,0x8000
         bne     TestArui_WWZErr
         mov     cw,0x0001
         shrzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0001
         rolzx   ax,dw,0x0F
         cmp     ax,0x8000
         bne     TestArui_WWZErr
         mov     ew,0x0001
         asrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0001
         addzx   cx,fw,0x80
         cmp     cx,0x0081
         bne     TestArui_WWZErr
         mov     gw,0x0001
         subzx   dx,gw,0x80
         cmp     dx,0xFF81
         bne     TestArui_WWZErr
         mov     ax,0x0001
         andzx   ex,ax,0x80
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0001
         orzx    fx,bx,0x80
         cmp     fx,0x0081
         bne     TestArui_WWZErr
         mov     cx,0x0001
         xorzx   gx,cx,0x80
         cmp     gx,0x0081
         bne     TestArui_WWZErr
         mov     dx,0x0001
         mulzx   aw,dx,0x80
         cmp     aw,0x0080
         bne     TestArui_WWZErr
         mov     ex,0x0001
         udivzx  bw,ex,0x80
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0001
         uremzx  cw,fx,0x80
         cmp     cw,0x0001
         bne     TestArui_WWZErr
         mov     gx,0x0001
         shlzx   dw,gx,0x00
         cmp     dw,0x0001
         bne     TestArui_WWZErr
         mov     aw,0x0001
         shrzx   ew,aw,0x00
         cmp     ew,0x0001
         bne     TestArui_WWZErr
         mov     bw,0x0001
         rolzx   fw,bw,0x00
         cmp     fw,0x0001
         bne     TestArui_WWZErr
         mov     cw,0x0001
         asrzx   gw,cw,0x00
         cmp     gw,0x0001
         bne     TestArui_WWZErr
         mov     dw,0x0001
         addzx   ax,dw,0xFF
         cmp     ax,0x0100
         bne     TestArui_WWZErr
         mov     ew,0x0001
         subzx   bx,ew,0xFF
         cmp     bx,0xFF02
         bne     TestArui_WWZErr
         mov     fw,0x0001
         andzx   cx,fw,0xFF
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x0001
         orzx    dx,gw,0xFF
         cmp     dx,0x00FF
         bne     TestArui_WWZErr
         mov     ax,0x0001
         xorzx   ex,ax,0xFF
         cmp     ex,0x00FE
         bne     TestArui_WWZErr
         mov     bx,0x0001
         mulzx   fx,bx,0xFF
         cmp     fx,0x00FF
         bne     TestArui_WWZErr
         mov     cx,0x0001
         udivzx  gx,cx,0xFF
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0001
         uremzx  aw,dx,0xFF
         cmp     aw,0x0001
         bne     TestArui_WWZErr
         mov     ex,0x0001
         shlzx   bw,ex,0x0F
         cmp     bw,0x8000
         bne     TestArui_WWZErr
         mov     fx,0x0001
         shrzx   cw,fx,0x0F
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0001
         rolzx   dw,gx,0x0F
         cmp     dw,0x8000
         bne     TestArui_WWZErr
         mov     aw,0x0001
         asrzx   ew,aw,0x0F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0008
         addzx   fw,bw,0x07
         cmp     fw,0x000F
         bne     TestArui_WWZErr
         mov     cw,0x0008
         subzx   gw,cw,0x07
         cmp     gw,0x0001
         bne     TestArui_WWZErr
         mov     dw,0x0008
         andzx   ax,dw,0x07
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0008
         orzx    bx,ew,0x07
         cmp     bx,0x000F
         bne     TestArui_WWZErr
         mov     fw,0x0008
         xorzx   cx,fw,0x07
         cmp     cx,0x000F
         bne     TestArui_WWZErr
         mov     gw,0x0008
         mulzx   dx,gw,0x07
         cmp     dx,0x0038
         bne     TestArui_WWZErr
         mov     ax,0x0008
         udivzx  ex,ax,0x07
         cmp     ex,0x0001
         bne     TestArui_WWZErr
         mov     bx,0x0008
         uremzx  fx,bx,0x07
         cmp     fx,0x0001
         bne     TestArui_WWZErr
         mov     cx,0x0008
         shlzx   gx,cx,0x07
         cmp     gx,0x0400
         bne     TestArui_WWZErr
         mov     dx,0x0008
         shrzx   aw,dx,0x07
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0008
         rolzx   bw,ex,0x07
         cmp     bw,0x0400
         bne     TestArui_WWZErr
         mov     fx,0x0008
         asrzx   cw,fx,0x07
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0008
         addzx   dw,gx,0x08
         cmp     dw,0x0010
         bne     TestArui_WWZErr
         mov     aw,0x0008
         subzx   ew,aw,0x08
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0008
         andzx   fw,bw,0x08
         cmp     fw,0x0008
         bne     TestArui_WWZErr
         mov     cw,0x0008
         orzx    gw,cw,0x08
         cmp     gw,0x0008
         bne     TestArui_WWZErr
         mov     dw,0x0008
         xorzx   ax,dw,0x08
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0008
         mulzx   bx,ew,0x08
         cmp     bx,0x0040
         bne     TestArui_WWZErr
         mov     fw,0x0008
         udivzx  cx,fw,0x08
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x0008
         uremzx  dx,gw,0x08
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0008
         shlzx   ex,ax,0x08
         cmp     ex,0x0800
         bne     TestArui_WWZErr
         mov     bx,0x0008
         shrzx   fx,bx,0x08
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0008
         rolzx   gx,cx,0x08
         cmp     gx,0x0800
         bne     TestArui_WWZErr
         mov     dx,0x0008
         asrzx   aw,dx,0x08
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0008
         addzx   bw,ex,0x09
         cmp     bw,0x0011
         bne     TestArui_WWZErr
         mov     fx,0x0008
         subzx   cw,fx,0x09
         cmp     cw,0xFFFF
         bne     TestArui_WWZErr
         mov     gx,0x0008
         andzx   dw,gx,0x09
         cmp     dw,0x0008
         bne     TestArui_WWZErr
         mov     aw,0x0008
         orzx    ew,aw,0x09
         cmp     ew,0x0009
         bne     TestArui_WWZErr
         mov     bw,0x0008
         xorzx   fw,bw,0x09
         cmp     fw,0x0001
         bne     TestArui_WWZErr
         mov     cw,0x0008
         mulzx   gw,cw,0x09
         cmp     gw,0x0048
         bne     TestArui_WWZErr
         mov     dw,0x0008
         udivzx  ax,dw,0x09
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0008
         uremzx  bx,ew,0x09
         cmp     bx,0x0008
         bne     TestArui_WWZErr
         mov     fw,0x0008
         shlzx   cx,fw,0x09
         cmp     cx,0x1000
         bne     TestArui_WWZErr
         mov     gw,0x0008
         shrzx   dx,gw,0x09
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0008
         rolzx   ex,ax,0x09
         cmp     ex,0x1000
         bne     TestArui_WWZErr
         mov     bx,0x0008
         asrzx   fx,bx,0x09
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0008
         addzx   gx,cx,0x0F
         cmp     gx,0x0017
         bne     TestArui_WWZErr
         mov     dx,0x0008
         subzx   aw,dx,0x0F
         cmp     aw,0xFFF9
         bne     TestArui_WWZErr
         mov     ex,0x0008
         andzx   bw,ex,0x0F
         cmp     bw,0x0008
         bne     TestArui_WWZErr
         mov     fx,0x0008
         orzx    cw,fx,0x0F
         cmp     cw,0x000F
         bne     TestArui_WWZErr
         mov     gx,0x0008
         xorzx   dw,gx,0x0F
         cmp     dw,0x0007
         bne     TestArui_WWZErr
         mov     aw,0x0008
         mulzx   ew,aw,0x0F
         cmp     ew,0x0078
         bne     TestArui_WWZErr
         mov     bw,0x0008
         udivzx  fw,bw,0x0F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0008
         uremzx  gw,cw,0x0F
         cmp     gw,0x0008
         bne     TestArui_WWZErr
         mov     dw,0x0008
         shlzx   ax,dw,0x0F
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0008
         shrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0008
         rolzx   cx,fw,0x0F
         cmp     cx,0x0004
         bne     TestArui_WWZErr
         mov     gw,0x0008
         asrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0008
         addzx   ex,ax,0x7F
         cmp     ex,0x0087
         bne     TestArui_WWZErr
         mov     bx,0x0008
         subzx   fx,bx,0x7F
         cmp     fx,0xFF89
         bne     TestArui_WWZErr
         mov     cx,0x0008
         andzx   gx,cx,0x7F
         cmp     gx,0x0008
         bne     TestArui_WWZErr
         mov     dx,0x0008
         orzx    aw,dx,0x7F
         cmp     aw,0x007F
         bne     TestArui_WWZErr
         mov     ex,0x0008
         xorzx   bw,ex,0x7F
         cmp     bw,0x0077
         bne     TestArui_WWZErr
         mov     fx,0x0008
         mulzx   cw,fx,0x7F
         cmp     cw,0x03F8
         bne     TestArui_WWZErr
         mov     gx,0x0008
         udivzx  dw,gx,0x7F
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0008
         uremzx  ew,aw,0x7F
         cmp     ew,0x0008
         bne     TestArui_WWZErr
         mov     bw,0x0008
         shlzx   fw,bw,0x0F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0008
         shrzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0008
         rolzx   ax,dw,0x0F
         cmp     ax,0x0004
         bne     TestArui_WWZErr
         mov     ew,0x0008
         asrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0008
         addzx   cx,fw,0x80
         cmp     cx,0x0088
         bne     TestArui_WWZErr
         mov     gw,0x0008
         subzx   dx,gw,0x80
         cmp     dx,0xFF88
         bne     TestArui_WWZErr
         mov     ax,0x0008
         andzx   ex,ax,0x80
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0008
         orzx    fx,bx,0x80
         cmp     fx,0x0088
         bne     TestArui_WWZErr
         mov     cx,0x0008
         xorzx   gx,cx,0x80
         cmp     gx,0x0088
         bne     TestArui_WWZErr
         mov     dx,0x0008
         mulzx   aw,dx,0x80
         cmp     aw,0x0400
         bne     TestArui_WWZErr
         mov     ex,0x0008
         udivzx  bw,ex,0x80
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0008
         uremzx  cw,fx,0x80
         cmp     cw,0x0008
         bne     TestArui_WWZErr
         mov     gx,0x0008
         shlzx   dw,gx,0x00
         cmp     dw,0x0008
         bne     TestArui_WWZErr
         mov     aw,0x0008
         shrzx   ew,aw,0x00
         cmp     ew,0x0008
         bne     TestArui_WWZErr
         mov     bw,0x0008
         rolzx   fw,bw,0x00
         cmp     fw,0x0008
         bne     TestArui_WWZErr
         mov     cw,0x0008
         asrzx   gw,cw,0x00
         cmp     gw,0x0008
         bne     TestArui_WWZErr
         mov     dw,0x0008
         addzx   ax,dw,0xFF
         cmp     ax,0x0107
         bne     TestArui_WWZErr
         mov     ew,0x0008
         subzx   bx,ew,0xFF
         cmp     bx,0xFF09
         bne     TestArui_WWZErr
         mov     fw,0x0008
         andzx   cx,fw,0xFF
         cmp     cx,0x0008
         bne     TestArui_WWZErr
         mov     gw,0x0008
         orzx    dx,gw,0xFF
         cmp     dx,0x00FF
         bne     TestArui_WWZErr
         mov     ax,0x0008
         xorzx   ex,ax,0xFF
         cmp     ex,0x00F7
         bne     TestArui_WWZErr
         mov     bx,0x0008
         mulzx   fx,bx,0xFF
         cmp     fx,0x07F8
         bne     TestArui_WWZErr
         mov     cx,0x0008
         udivzx  gx,cx,0xFF
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0008
         uremzx  aw,dx,0xFF
         cmp     aw,0x0008
         bne     TestArui_WWZErr
         mov     ex,0x0008
         shlzx   bw,ex,0x0F
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0008
         shrzx   cw,fx,0x0F
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0008
         rolzx   dw,gx,0x0F
         cmp     dw,0x0004
         bne     TestArui_WWZErr
         mov     aw,0x0008
         asrzx   ew,aw,0x0F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0009
         addzx   fw,bw,0x08
         cmp     fw,0x0011
         bne     TestArui_WWZErr
         mov     cw,0x0009
         subzx   gw,cw,0x08
         cmp     gw,0x0001
         bne     TestArui_WWZErr
         mov     dw,0x0009
         andzx   ax,dw,0x08
         cmp     ax,0x0008
         bne     TestArui_WWZErr
         mov     ew,0x0009
         orzx    bx,ew,0x08
         cmp     bx,0x0009
         bne     TestArui_WWZErr
         mov     fw,0x0009
         xorzx   cx,fw,0x08
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x0009
         mulzx   dx,gw,0x08
         cmp     dx,0x0048
         bne     TestArui_WWZErr
         mov     ax,0x0009
         udivzx  ex,ax,0x08
         cmp     ex,0x0001
         bne     TestArui_WWZErr
         mov     bx,0x0009
         uremzx  fx,bx,0x08
         cmp     fx,0x0001
         bne     TestArui_WWZErr
         mov     cx,0x0009
         shlzx   gx,cx,0x08
         cmp     gx,0x0900
         bne     TestArui_WWZErr
         mov     dx,0x0009
         shrzx   aw,dx,0x08
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0009
         rolzx   bw,ex,0x08
         cmp     bw,0x0900
         bne     TestArui_WWZErr
         mov     fx,0x0009
         asrzx   cw,fx,0x08
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x0009
         addzx   dw,gx,0x09
         cmp     dw,0x0012
         bne     TestArui_WWZErr
         mov     aw,0x0009
         subzx   ew,aw,0x09
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0009
         andzx   fw,bw,0x09
         cmp     fw,0x0009
         bne     TestArui_WWZErr
         mov     cw,0x0009
         orzx    gw,cw,0x09
         cmp     gw,0x0009
         bne     TestArui_WWZErr
         mov     dw,0x0009
         xorzx   ax,dw,0x09
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0009
         mulzx   bx,ew,0x09
         cmp     bx,0x0051
         bne     TestArui_WWZErr
         mov     fw,0x0009
         udivzx  cx,fw,0x09
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x0009
         uremzx  dx,gw,0x09
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0009
         shlzx   ex,ax,0x09
         cmp     ex,0x1200
         bne     TestArui_WWZErr
         mov     bx,0x0009
         shrzx   fx,bx,0x09
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0009
         rolzx   gx,cx,0x09
         cmp     gx,0x1200
         bne     TestArui_WWZErr
         mov     dx,0x0009
         asrzx   aw,dx,0x09
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0009
         addzx   bw,ex,0x0F
         cmp     bw,0x0018
         bne     TestArui_WWZErr
         mov     fx,0x0009
         subzx   cw,fx,0x0F
         cmp     cw,0xFFFA
         bne     TestArui_WWZErr
         mov     gx,0x0009
         andzx   dw,gx,0x0F
         cmp     dw,0x0009
         bne     TestArui_WWZErr
         mov     aw,0x0009
         orzx    ew,aw,0x0F
         cmp     ew,0x000F
         bne     TestArui_WWZErr
         mov     bw,0x0009
         xorzx   fw,bw,0x0F
         cmp     fw,0x0006
         bne     TestArui_WWZErr
         mov     cw,0x0009
         mulzx   gw,cw,0x0F
         cmp     gw,0x0087
         bne     TestArui_WWZErr
         mov     dw,0x0009
         udivzx  ax,dw,0x0F
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x0009
         uremzx  bx,ew,0x0F
         cmp     bx,0x0009
         bne     TestArui_WWZErr
         mov     fw,0x0009
         shlzx   cx,fw,0x0F
         cmp     cx,0x8000
         bne     TestArui_WWZErr
         mov     gw,0x0009
         shrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0009
         rolzx   ex,ax,0x0F
         cmp     ex,0x8004
         bne     TestArui_WWZErr
         mov     bx,0x0009
         asrzx   fx,bx,0x0F
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x0009
         addzx   gx,cx,0x7F
         cmp     gx,0x0088
         bne     TestArui_WWZErr
         mov     dx,0x0009
         subzx   aw,dx,0x7F
         cmp     aw,0xFF8A
         bne     TestArui_WWZErr
         mov     ex,0x0009
         andzx   bw,ex,0x7F
         cmp     bw,0x0009
         bne     TestArui_WWZErr
         mov     fx,0x0009
         orzx    cw,fx,0x7F
         cmp     cw,0x007F
         bne     TestArui_WWZErr
         mov     gx,0x0009
         xorzx   dw,gx,0x7F
         cmp     dw,0x0076
         bne     TestArui_WWZErr
         mov     aw,0x0009
         mulzx   ew,aw,0x7F
         cmp     ew,0x0477
         bne     TestArui_WWZErr
         mov     bw,0x0009
         udivzx  fw,bw,0x7F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0009
         uremzx  gw,cw,0x7F
         cmp     gw,0x0009
         bne     TestArui_WWZErr
         mov     dw,0x0009
         shlzx   ax,dw,0x0F
         cmp     ax,0x8000
         bne     TestArui_WWZErr
         mov     ew,0x0009
         shrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0009
         rolzx   cx,fw,0x0F
         cmp     cx,0x8004
         bne     TestArui_WWZErr
         mov     gw,0x0009
         asrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0009
         addzx   ex,ax,0x80
         cmp     ex,0x0089
         bne     TestArui_WWZErr
         mov     bx,0x0009
         subzx   fx,bx,0x80
         cmp     fx,0xFF89
         bne     TestArui_WWZErr
         mov     cx,0x0009
         andzx   gx,cx,0x80
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0009
         orzx    aw,dx,0x80
         cmp     aw,0x0089
         bne     TestArui_WWZErr
         mov     ex,0x0009
         xorzx   bw,ex,0x80
         cmp     bw,0x0089
         bne     TestArui_WWZErr
         mov     fx,0x0009
         mulzx   cw,fx,0x80
         cmp     cw,0x0480
         bne     TestArui_WWZErr
         mov     gx,0x0009
         udivzx  dw,gx,0x80
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0009
         uremzx  ew,aw,0x80
         cmp     ew,0x0009
         bne     TestArui_WWZErr
         mov     bw,0x0009
         shlzx   fw,bw,0x00
         cmp     fw,0x0009
         bne     TestArui_WWZErr
         mov     cw,0x0009
         shrzx   gw,cw,0x00
         cmp     gw,0x0009
         bne     TestArui_WWZErr
         mov     dw,0x0009
         rolzx   ax,dw,0x00
         cmp     ax,0x0009
         bne     TestArui_WWZErr
         mov     ew,0x0009
         asrzx   bx,ew,0x00
         cmp     bx,0x0009
         bne     TestArui_WWZErr
         mov     fw,0x0009
         addzx   cx,fw,0xFF
         cmp     cx,0x0108
         bne     TestArui_WWZErr
         mov     gw,0x0009
         subzx   dx,gw,0xFF
         cmp     dx,0xFF0A
         bne     TestArui_WWZErr
         mov     ax,0x0009
         andzx   ex,ax,0xFF
         cmp     ex,0x0009
         bne     TestArui_WWZErr
         mov     bx,0x0009
         orzx    fx,bx,0xFF
         cmp     fx,0x00FF
         bne     TestArui_WWZErr
         mov     cx,0x0009
         xorzx   gx,cx,0xFF
         cmp     gx,0x00F6
         bne     TestArui_WWZErr
         mov     dx,0x0009
         mulzx   aw,dx,0xFF
         cmp     aw,0x08F7
         bne     TestArui_WWZErr
         mov     ex,0x0009
         udivzx  bw,ex,0xFF
         cmp     bw,0x0000
         bne     TestArui_WWZErr
         mov     fx,0x0009
         uremzx  cw,fx,0xFF
         cmp     cw,0x0009
         bne     TestArui_WWZErr
         mov     gx,0x0009
         shlzx   dw,gx,0x0F
         cmp     dw,0x8000
         bne     TestArui_WWZErr
         mov     aw,0x0009
         shrzx   ew,aw,0x0F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0009
         rolzx   fw,bw,0x0F
         cmp     fw,0x8004
         bne     TestArui_WWZErr
         mov     cw,0x0009
         asrzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x007F
         addzx   ax,dw,0x09
         cmp     ax,0x0088
         bne     TestArui_WWZErr
         mov     ew,0x007F
         subzx   bx,ew,0x09
         cmp     bx,0x0076
         bne     TestArui_WWZErr
         mov     fw,0x007F
         andzx   cx,fw,0x09
         cmp     cx,0x0009
         bne     TestArui_WWZErr
         mov     gw,0x007F
         orzx    dx,gw,0x09
         cmp     dx,0x007F
         bne     TestArui_WWZErr
         mov     ax,0x007F
         xorzx   ex,ax,0x09
         cmp     ex,0x0076
         bne     TestArui_WWZErr
         mov     bx,0x007F
         mulzx   fx,bx,0x09
         cmp     fx,0x0477
         bne     TestArui_WWZErr
         mov     cx,0x007F
         udivzx  gx,cx,0x09
         cmp     gx,0x000E
         bne     TestArui_WWZErr
         mov     dx,0x007F
         uremzx  aw,dx,0x09
         cmp     aw,0x0001
         bne     TestArui_WWZErr
         mov     ex,0x007F
         shlzx   bw,ex,0x09
         cmp     bw,0xFE00
         bne     TestArui_WWZErr
         mov     fx,0x007F
         shrzx   cw,fx,0x09
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x007F
         rolzx   dw,gx,0x09
         cmp     dw,0xFE00
         bne     TestArui_WWZErr
         mov     aw,0x007F
         asrzx   ew,aw,0x09
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x007F
         addzx   fw,bw,0x0F
         cmp     fw,0x008E
         bne     TestArui_WWZErr
         mov     cw,0x007F
         subzx   gw,cw,0x0F
         cmp     gw,0x0070
         bne     TestArui_WWZErr
         mov     dw,0x007F
         andzx   ax,dw,0x0F
         cmp     ax,0x000F
         bne     TestArui_WWZErr
         mov     ew,0x007F
         orzx    bx,ew,0x0F
         cmp     bx,0x007F
         bne     TestArui_WWZErr
         mov     fw,0x007F
         xorzx   cx,fw,0x0F
         cmp     cx,0x0070
         bne     TestArui_WWZErr
         mov     gw,0x007F
         mulzx   dx,gw,0x0F
         cmp     dx,0x0771
         bne     TestArui_WWZErr
         mov     ax,0x007F
         udivzx  ex,ax,0x0F
         cmp     ex,0x0008
         bne     TestArui_WWZErr
         mov     bx,0x007F
         uremzx  fx,bx,0x0F
         cmp     fx,0x0007
         bne     TestArui_WWZErr
         mov     cx,0x007F
         shlzx   gx,cx,0x0F
         cmp     gx,0x8000
         bne     TestArui_WWZErr
         mov     dx,0x007F
         shrzx   aw,dx,0x0F
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x007F
         rolzx   bw,ex,0x0F
         cmp     bw,0x803F
         bne     TestArui_WWZErr
         mov     fx,0x007F
         asrzx   cw,fx,0x0F
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x007F
         addzx   dw,gx,0x7F
         cmp     dw,0x00FE
         bne     TestArui_WWZErr
         mov     aw,0x007F
         subzx   ew,aw,0x7F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x007F
         andzx   fw,bw,0x7F
         cmp     fw,0x007F
         bne     TestArui_WWZErr
         mov     cw,0x007F
         orzx    gw,cw,0x7F
         cmp     gw,0x007F
         bne     TestArui_WWZErr
         mov     dw,0x007F
         xorzx   ax,dw,0x7F
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x007F
         mulzx   bx,ew,0x7F
         cmp     bx,0x3F01
         bne     TestArui_WWZErr
         mov     fw,0x007F
         udivzx  cx,fw,0x7F
         cmp     cx,0x0001
         bne     TestArui_WWZErr
         mov     gw,0x007F
         uremzx  dx,gw,0x7F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x007F
         shlzx   ex,ax,0x0F
         cmp     ex,0x8000
         bne     TestArui_WWZErr
         mov     bx,0x007F
         shrzx   fx,bx,0x0F
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x007F
         rolzx   gx,cx,0x0F
         cmp     gx,0x803F
         bne     TestArui_WWZErr
         mov     dx,0x007F
         asrzx   aw,dx,0x0F
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x007F
         addzx   bw,ex,0x80
         cmp     bw,0x00FF
         bne     TestArui_WWZErr
         mov     fx,0x007F
         subzx   cw,fx,0x80
         cmp     cw,0xFFFF
         bne     TestArui_WWZErr
         mov     gx,0x007F
         andzx   dw,gx,0x80
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x007F
         orzx    ew,aw,0x80
         cmp     ew,0x00FF
         bne     TestArui_WWZErr
         mov     bw,0x007F
         xorzx   fw,bw,0x80
         cmp     fw,0x00FF
         bne     TestArui_WWZErr
         mov     cw,0x007F
         mulzx   gw,cw,0x80
         cmp     gw,0x3F80
         bne     TestArui_WWZErr
         mov     dw,0x007F
         udivzx  ax,dw,0x80
         cmp     ax,0x0000
         bne     TestArui_WWZErr
         mov     ew,0x007F
         uremzx  bx,ew,0x80
         cmp     bx,0x007F
         bne     TestArui_WWZErr
         mov     fw,0x007F
         shlzx   cx,fw,0x00
         cmp     cx,0x007F
         bne     TestArui_WWZErr
         mov     gw,0x007F
         shrzx   dx,gw,0x00
         cmp     dx,0x007F
         bne     TestArui_WWZErr
         mov     ax,0x007F
         rolzx   ex,ax,0x00
         cmp     ex,0x007F
         bne     TestArui_WWZErr
         mov     bx,0x007F
         asrzx   fx,bx,0x00
         cmp     fx,0x007F
         bne     TestArui_WWZErr
         mov     cx,0x007F
         addzx   gx,cx,0xFF
         cmp     gx,0x017E
         bne     TestArui_WWZErr
         mov     dx,0x007F
         subzx   aw,dx,0xFF
         cmp     aw,0xFF80
         bne     TestArui_WWZErr
         mov     ex,0x007F
         andzx   bw,ex,0xFF
         cmp     bw,0x007F
         bne     TestArui_WWZErr
         mov     fx,0x007F
         orzx    cw,fx,0xFF
         cmp     cw,0x00FF
         bne     TestArui_WWZErr
         mov     gx,0x007F
         xorzx   dw,gx,0xFF
         cmp     dw,0x0080
         bne     TestArui_WWZErr
         mov     aw,0x007F
         mulzx   ew,aw,0xFF
         cmp     ew,0x7E81
         bne     TestArui_WWZErr
         mov     bw,0x007F
         udivzx  fw,bw,0xFF
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x007F
         uremzx  gw,cw,0xFF
         cmp     gw,0x007F
         bne     TestArui_WWZErr
         mov     dw,0x007F
         shlzx   ax,dw,0x0F
         cmp     ax,0x8000
         bne     TestArui_WWZErr
         mov     ew,0x007F
         shrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x007F
         rolzx   cx,fw,0x0F
         cmp     cx,0x803F
         bne     TestArui_WWZErr
         mov     gw,0x007F
         asrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x0080
         addzx   ex,ax,0x0F
         cmp     ex,0x008F
         bne     TestArui_WWZErr
         mov     bx,0x0080
         subzx   fx,bx,0x0F
         cmp     fx,0x0071
         bne     TestArui_WWZErr
         mov     cx,0x0080
         andzx   gx,cx,0x0F
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0080
         orzx    aw,dx,0x0F
         cmp     aw,0x008F
         bne     TestArui_WWZErr
         mov     ex,0x0080
         xorzx   bw,ex,0x0F
         cmp     bw,0x008F
         bne     TestArui_WWZErr
         mov     fx,0x0080
         mulzx   cw,fx,0x0F
         cmp     cw,0x0780
         bne     TestArui_WWZErr
         mov     gx,0x0080
         udivzx  dw,gx,0x0F
         cmp     dw,0x0008
         bne     TestArui_WWZErr
         mov     aw,0x0080
         uremzx  ew,aw,0x0F
         cmp     ew,0x0008
         bne     TestArui_WWZErr
         mov     bw,0x0080
         shlzx   fw,bw,0x0F
         cmp     fw,0x0000
         bne     TestArui_WWZErr
         mov     cw,0x0080
         shrzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0080
         rolzx   ax,dw,0x0F
         cmp     ax,0x0040
         bne     TestArui_WWZErr
         mov     ew,0x0080
         asrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0080
         addzx   cx,fw,0x7F
         cmp     cx,0x00FF
         bne     TestArui_WWZErr
         mov     gw,0x0080
         subzx   dx,gw,0x7F
         cmp     dx,0x0001
         bne     TestArui_WWZErr
         mov     ax,0x0080
         andzx   ex,ax,0x7F
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0080
         orzx    fx,bx,0x7F
         cmp     fx,0x00FF
         bne     TestArui_WWZErr
         mov     cx,0x0080
         xorzx   gx,cx,0x7F
         cmp     gx,0x00FF
         bne     TestArui_WWZErr
         mov     dx,0x0080
         mulzx   aw,dx,0x7F
         cmp     aw,0x3F80
         bne     TestArui_WWZErr
         mov     ex,0x0080
         udivzx  bw,ex,0x7F
         cmp     bw,0x0001
         bne     TestArui_WWZErr
         mov     fx,0x0080
         uremzx  cw,fx,0x7F
         cmp     cw,0x0001
         bne     TestArui_WWZErr
         mov     gx,0x0080
         shlzx   dw,gx,0x0F
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x0080
         shrzx   ew,aw,0x0F
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x0080
         rolzx   fw,bw,0x0F
         cmp     fw,0x0040
         bne     TestArui_WWZErr
         mov     cw,0x0080
         asrzx   gw,cw,0x0F
         cmp     gw,0x0000
         bne     TestArui_WWZErr
         mov     dw,0x0080
         addzx   ax,dw,0x80
         cmp     ax,0x0100
         bne     TestArui_WWZErr
         mov     ew,0x0080
         subzx   bx,ew,0x80
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x0080
         andzx   cx,fw,0x80
         cmp     cx,0x0080
         bne     TestArui_WWZErr
         mov     gw,0x0080
         orzx    dx,gw,0x80
         cmp     dx,0x0080
         bne     TestArui_WWZErr
         mov     ax,0x0080
         xorzx   ex,ax,0x80
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0080
         mulzx   fx,bx,0x80
         cmp     fx,0x4000
         bne     TestArui_WWZErr
         mov     cx,0x0080
         udivzx  gx,cx,0x80
         cmp     gx,0x0001
         bne     TestArui_WWZErr
         mov     dx,0x0080
         uremzx  aw,dx,0x80
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0080
         shlzx   bw,ex,0x00
         cmp     bw,0x0080
         bne     TestArui_WWZErr
         mov     fx,0x0080
         shrzx   cw,fx,0x00
         cmp     cw,0x0080
         bne     TestArui_WWZErr
         mov     gx,0x0080
         rolzx   dw,gx,0x00
         cmp     dw,0x0080
         bne     TestArui_WWZErr
         mov     aw,0x0080
         asrzx   ew,aw,0x00
         cmp     ew,0x0080
         bne     TestArui_WWZErr
         mov     bw,0x0080
         addzx   fw,bw,0xFF
         cmp     fw,0x017F
         bne     TestArui_WWZErr
         mov     cw,0x0080
         subzx   gw,cw,0xFF
         cmp     gw,0xFF81
         bne     TestArui_WWZErr
         mov     dw,0x0080
         andzx   ax,dw,0xFF
         cmp     ax,0x0080
         bne     TestArui_WWZErr
         mov     ew,0x0080
         orzx    bx,ew,0xFF
         cmp     bx,0x00FF
         bne     TestArui_WWZErr
         mov     fw,0x0080
         xorzx   cx,fw,0xFF
         cmp     cx,0x007F
         bne     TestArui_WWZErr
         mov     gw,0x0080
         mulzx   dx,gw,0xFF
         cmp     dx,0x7F80
         bne     TestArui_WWZErr
         mov     ax,0x0080
         udivzx  ex,ax,0xFF
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x0080
         uremzx  fx,bx,0xFF
         cmp     fx,0x0080
         bne     TestArui_WWZErr
         mov     cx,0x0080
         shlzx   gx,cx,0x0F
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x0080
         shrzx   aw,dx,0x0F
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x0080
         rolzx   bw,ex,0x0F
         cmp     bw,0x0040
         bne     TestArui_WWZErr
         mov     fx,0x0080
         asrzx   cw,fx,0x0F
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x7FFF
         addzx   dw,gx,0x7F
         cmp     dw,0x807E
         bne     TestArui_WWZErr
         mov     aw,0x7FFF
         subzx   ew,aw,0x7F
         cmp     ew,0x7F80
         bne     TestArui_WWZErr
         mov     bw,0x7FFF
         andzx   fw,bw,0x7F
         cmp     fw,0x007F
         bne     TestArui_WWZErr
         mov     cw,0x7FFF
         orzx    gw,cw,0x7F
         cmp     gw,0x7FFF
         bne     TestArui_WWZErr
         mov     dw,0x7FFF
         xorzx   ax,dw,0x7F
         cmp     ax,0x7F80
         bne     TestArui_WWZErr
         mov     ew,0x7FFF
         mulzx   bx,ew,0x7F
         cmp     bx,0x7F81
         bne     TestArui_WWZErr
         mov     fw,0x7FFF
         udivzx  cx,fw,0x7F
         cmp     cx,0x0102
         bne     TestArui_WWZErr
         mov     gw,0x7FFF
         uremzx  dx,gw,0x7F
         cmp     dx,0x0001
         bne     TestArui_WWZErr
         mov     ax,0x7FFF
         shlzx   ex,ax,0x0F
         cmp     ex,0x8000
         bne     TestArui_WWZErr
         mov     bx,0x7FFF
         shrzx   fx,bx,0x0F
         cmp     fx,0x0000
         bne     TestArui_WWZErr
         mov     cx,0x7FFF
         rolzx   gx,cx,0x0F
         cmp     gx,0xBFFF
         bne     TestArui_WWZErr
         mov     dx,0x7FFF
         asrzx   aw,dx,0x0F
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0x7FFF
         addzx   bw,ex,0x80
         cmp     bw,0x807F
         bne     TestArui_WWZErr
         mov     fx,0x7FFF
         subzx   cw,fx,0x80
         cmp     cw,0x7F7F
         bne     TestArui_WWZErr
         mov     gx,0x7FFF
         andzx   dw,gx,0x80
         cmp     dw,0x0080
         bne     TestArui_WWZErr
         mov     aw,0x7FFF
         orzx    ew,aw,0x80
         cmp     ew,0x7FFF
         bne     TestArui_WWZErr
         mov     bw,0x7FFF
         xorzx   fw,bw,0x80
         cmp     fw,0x7F7F
         bne     TestArui_WWZErr
         mov     cw,0x7FFF
         mulzx   gw,cw,0x80
         cmp     gw,0xFF80
         bne     TestArui_WWZErr
         mov     dw,0x7FFF
         udivzx  ax,dw,0x80
         cmp     ax,0x00FF
         bne     TestArui_WWZErr
         mov     ew,0x7FFF
         uremzx  bx,ew,0x80
         cmp     bx,0x007F
         bne     TestArui_WWZErr
         mov     fw,0x7FFF
         shlzx   cx,fw,0x00
         cmp     cx,0x7FFF
         bne     TestArui_WWZErr
         mov     gw,0x7FFF
         shrzx   dx,gw,0x00
         cmp     dx,0x7FFF
         bne     TestArui_WWZErr
         mov     ax,0x7FFF
         rolzx   ex,ax,0x00
         cmp     ex,0x7FFF
         bne     TestArui_WWZErr
         mov     bx,0x7FFF
         asrzx   fx,bx,0x00
         cmp     fx,0x7FFF
         bne     TestArui_WWZErr
         mov     cx,0x7FFF
         addzx   gx,cx,0xFF
         cmp     gx,0x80FE
         bne     TestArui_WWZErr
         mov     dx,0x7FFF
         subzx   aw,dx,0xFF
         cmp     aw,0x7F00
         bne     TestArui_WWZErr
         mov     ex,0x7FFF
         andzx   bw,ex,0xFF
         cmp     bw,0x00FF
         bne     TestArui_WWZErr
         mov     fx,0x7FFF
         orzx    cw,fx,0xFF
         cmp     cw,0x7FFF
         bne     TestArui_WWZErr
         mov     gx,0x7FFF
         xorzx   dw,gx,0xFF
         cmp     dw,0x7F00
         bne     TestArui_WWZErr
         mov     aw,0x7FFF
         mulzx   ew,aw,0xFF
         cmp     ew,0x7F01
         bne     TestArui_WWZErr
         mov     bw,0x7FFF
         udivzx  fw,bw,0xFF
         cmp     fw,0x0080
         bne     TestArui_WWZErr
         mov     cw,0x7FFF
         uremzx  gw,cw,0xFF
         cmp     gw,0x007F
         bne     TestArui_WWZErr
         mov     dw,0x7FFF
         shlzx   ax,dw,0x0F
         cmp     ax,0x8000
         bne     TestArui_WWZErr
         mov     ew,0x7FFF
         shrzx   bx,ew,0x0F
         cmp     bx,0x0000
         bne     TestArui_WWZErr
         mov     fw,0x7FFF
         rolzx   cx,fw,0x0F
         cmp     cx,0xBFFF
         bne     TestArui_WWZErr
         mov     gw,0x7FFF
         asrzx   dx,gw,0x0F
         cmp     dx,0x0000
         bne     TestArui_WWZErr
         mov     ax,0x8000
         addzx   ex,ax,0x80
         cmp     ex,0x8080
         bne     TestArui_WWZErr
         mov     bx,0x8000
         subzx   fx,bx,0x80
         cmp     fx,0x7F80
         bne     TestArui_WWZErr
         mov     cx,0x8000
         andzx   gx,cx,0x80
         cmp     gx,0x0000
         bne     TestArui_WWZErr
         mov     dx,0x8000
         orzx    aw,dx,0x80
         cmp     aw,0x8080
         bne     TestArui_WWZErr
         mov     ex,0x8000
         xorzx   bw,ex,0x80
         cmp     bw,0x8080
         bne     TestArui_WWZErr
         mov     fx,0x8000
         mulzx   cw,fx,0x80
         cmp     cw,0x0000
         bne     TestArui_WWZErr
         mov     gx,0x8000
         udivzx  dw,gx,0x80
         cmp     dw,0x0100
         bne     TestArui_WWZErr
         mov     aw,0x8000
         uremzx  ew,aw,0x80
         cmp     ew,0x0000
         bne     TestArui_WWZErr
         mov     bw,0x8000
         shlzx   fw,bw,0x00
         cmp     fw,0x8000
         bne     TestArui_WWZErr
         mov     cw,0x8000
         shrzx   gw,cw,0x00
         cmp     gw,0x8000
         bne     TestArui_WWZErr
         mov     dw,0x8000
         rolzx   ax,dw,0x00
         cmp     ax,0x8000
         bne     TestArui_WWZErr
         mov     ew,0x8000
         asrzx   bx,ew,0x00
         cmp     bx,0x8000
         bne     TestArui_WWZErr
         mov     fw,0x8000
         addzx   cx,fw,0xFF
         cmp     cx,0x80FF
         bne     TestArui_WWZErr
         mov     gw,0x8000
         subzx   dx,gw,0xFF
         cmp     dx,0x7F01
         bne     TestArui_WWZErr
         mov     ax,0x8000
         andzx   ex,ax,0xFF
         cmp     ex,0x0000
         bne     TestArui_WWZErr
         mov     bx,0x8000
         orzx    fx,bx,0xFF
         cmp     fx,0x80FF
         bne     TestArui_WWZErr
         mov     cx,0x8000
         xorzx   gx,cx,0xFF
         cmp     gx,0x80FF
         bne     TestArui_WWZErr
         mov     dx,0x8000
         mulzx   aw,dx,0xFF
         cmp     aw,0x8000
         bne     TestArui_WWZErr
         mov     ex,0x8000
         udivzx  bw,ex,0xFF
         cmp     bw,0x0080
         bne     TestArui_WWZErr
         mov     fx,0x8000
         uremzx  cw,fx,0xFF
         cmp     cw,0x0080
         bne     TestArui_WWZErr
         mov     gx,0x8000
         shlzx   dw,gx,0x0F
         cmp     dw,0x0000
         bne     TestArui_WWZErr
         mov     aw,0x8000
         shrzx   ew,aw,0x0F
         cmp     ew,0x0001
         bne     TestArui_WWZErr
         mov     bw,0x8000
         rolzx   fw,bw,0x0F
         cmp     fw,0x4000
         bne     TestArui_WWZErr
         mov     cw,0x8000
         asrzx   gw,cw,0x0F
         cmp     gw,0x0001
         bne     TestArui_WWZErr
         mov     dw,0xFFFF
         addzx   ax,dw,0xFF
         cmp     ax,0x00FE
         bne     TestArui_WWZErr
         mov     ew,0xFFFF
         subzx   bx,ew,0xFF
         cmp     bx,0xFF00
         bne     TestArui_WWZErr
         mov     fw,0xFFFF
         andzx   cx,fw,0xFF
         cmp     cx,0x00FF
         bne     TestArui_WWZErr
         mov     gw,0xFFFF
         orzx    dx,gw,0xFF
         cmp     dx,0xFFFF
         bne     TestArui_WWZErr
         mov     ax,0xFFFF
         xorzx   ex,ax,0xFF
         cmp     ex,0xFF00
         bne     TestArui_WWZErr
         mov     bx,0xFFFF
         mulzx   fx,bx,0xFF
         cmp     fx,0xFF01
         bne     TestArui_WWZErr
         mov     cx,0xFFFF
         udivzx  gx,cx,0xFF
         cmp     gx,0x0101
         bne     TestArui_WWZErr
         mov     dx,0xFFFF
         uremzx  aw,dx,0xFF
         cmp     aw,0x0000
         bne     TestArui_WWZErr
         mov     ex,0xFFFF
         shlzx   bw,ex,0x0F
         cmp     bw,0x8000
         bne     TestArui_WWZErr
         mov     fx,0xFFFF
         shrzx   cw,fx,0x0F
         cmp     cw,0x0001
         bne     TestArui_WWZErr
         mov     gx,0xFFFF
         rolzx   dw,gx,0x0F
         cmp     dw,0xFFFF
         bne     TestArui_WWZErr
         mov     aw,0xFFFF
         asrzx   ew,aw,0x0F
         cmp     ew,0x0001
         bne     TestArui_WWZErr
         bra     TestArui_WWZRet
TestArui_WWZErr:
         nop     
         trap    
         nop     
TestArui_WWZRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
