.seg data
        #Stack StartA, 0
    FStackA:

.seg code

Start_@ep:
StartTable:
        dd StartA or $10000000
        dd StartB or $10000000

StartA:
        mov     esp,FStackA

        bra     TestArui_WWS

        nop
        test_end
        nop

  saWait:
        bra     saWait

StartB:
        mov     awx,10
        bra     StartB

TestArui_WWS:
         enter   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0
         mov     ax,0x0000
         addsx   ex,ax,0x00
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x0000
         subsx   fx,bx,0x00
         cmp     fx,0x0000
         bne     TestArui_WWSErr
         mov     cx,0x0000
         andsx   gx,cx,0x00
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0000
         orsx    aw,dx,0x00
         cmp     aw,0x0000
         bne     TestArui_WWSErr
         mov     ex,0x0000
         xorsx   bw,ex,0x00
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x0000
         mulsx   cw,fx,0x00
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x0000
         sdivsx  dw,gx,0x00
         cmp     dw,0xFFFF
         bne     TestArui_WWSErr
         mov     aw,0x0000
         sremsx  ew,aw,0x00
         cmp     ew,0x0000
         bne     TestArui_WWSErr
         mov     bw,0x0000
         addsx   fw,bw,0x01
         cmp     fw,0x0001
         bne     TestArui_WWSErr
         mov     cw,0x0000
         subsx   gw,cw,0x01
         cmp     gw,0xFFFF
         bne     TestArui_WWSErr
         mov     dw,0x0000
         andsx   ax,dw,0x01
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0000
         orsx    bx,ew,0x01
         cmp     bx,0x0001
         bne     TestArui_WWSErr
         mov     fw,0x0000
         xorsx   cx,fw,0x01
         cmp     cx,0x0001
         bne     TestArui_WWSErr
         mov     gw,0x0000
         mulsx   dx,gw,0x01
         cmp     dx,0x0000
         bne     TestArui_WWSErr
         mov     ax,0x0000
         sdivsx  ex,ax,0x01
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x0000
         sremsx  fx,bx,0x01
         cmp     fx,0x0000
         bne     TestArui_WWSErr
         mov     cx,0x0000
         addsx   gx,cx,0x07
         cmp     gx,0x0007
         bne     TestArui_WWSErr
         mov     dx,0x0000
         subsx   aw,dx,0x07
         cmp     aw,0xFFF9
         bne     TestArui_WWSErr
         mov     ex,0x0000
         andsx   bw,ex,0x07
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x0000
         orsx    cw,fx,0x07
         cmp     cw,0x0007
         bne     TestArui_WWSErr
         mov     gx,0x0000
         xorsx   dw,gx,0x07
         cmp     dw,0x0007
         bne     TestArui_WWSErr
         mov     aw,0x0000
         mulsx   ew,aw,0x07
         cmp     ew,0x0000
         bne     TestArui_WWSErr
         mov     bw,0x0000
         sdivsx  fw,bw,0x07
         cmp     fw,0x0000
         bne     TestArui_WWSErr
         mov     cw,0x0000
         sremsx  gw,cw,0x07
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         mov     dw,0x0000
         addsx   ax,dw,0x08
         cmp     ax,0x0008
         bne     TestArui_WWSErr
         mov     ew,0x0000
         subsx   bx,ew,0x08
         cmp     bx,0xFFF8
         bne     TestArui_WWSErr
         mov     fw,0x0000
         andsx   cx,fw,0x08
         cmp     cx,0x0000
         bne     TestArui_WWSErr
         mov     gw,0x0000
         orsx    dx,gw,0x08
         cmp     dx,0x0008
         bne     TestArui_WWSErr
         mov     ax,0x0000
         xorsx   ex,ax,0x08
         cmp     ex,0x0008
         bne     TestArui_WWSErr
         mov     bx,0x0000
         mulsx   fx,bx,0x08
         cmp     fx,0x0000
         bne     TestArui_WWSErr
         mov     cx,0x0000
         sdivsx  gx,cx,0x08
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0000
         sremsx  aw,dx,0x08
         cmp     aw,0x0000
         bne     TestArui_WWSErr
         mov     ex,0x0000
         addsx   bw,ex,0x09
         cmp     bw,0x0009
         bne     TestArui_WWSErr
         mov     fx,0x0000
         subsx   cw,fx,0x09
         cmp     cw,0xFFF7
         bne     TestArui_WWSErr
         mov     gx,0x0000
         andsx   dw,gx,0x09
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0000
         orsx    ew,aw,0x09
         cmp     ew,0x0009
         bne     TestArui_WWSErr
         mov     bw,0x0000
         xorsx   fw,bw,0x09
         cmp     fw,0x0009
         bne     TestArui_WWSErr
         mov     cw,0x0000
         mulsx   gw,cw,0x09
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         mov     dw,0x0000
         sdivsx  ax,dw,0x09
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0000
         sremsx  bx,ew,0x09
         cmp     bx,0x0000
         bne     TestArui_WWSErr
         mov     fw,0x0000
         addsx   cx,fw,0x0F
         cmp     cx,0x000F
         bne     TestArui_WWSErr
         mov     gw,0x0000
         subsx   dx,gw,0x0F
         cmp     dx,0xFFF1
         bne     TestArui_WWSErr
         mov     ax,0x0000
         andsx   ex,ax,0x0F
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x0000
         orsx    fx,bx,0x0F
         cmp     fx,0x000F
         bne     TestArui_WWSErr
         mov     cx,0x0000
         xorsx   gx,cx,0x0F
         cmp     gx,0x000F
         bne     TestArui_WWSErr
         mov     dx,0x0000
         mulsx   aw,dx,0x0F
         cmp     aw,0x0000
         bne     TestArui_WWSErr
         mov     ex,0x0000
         sdivsx  bw,ex,0x0F
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x0000
         sremsx  cw,fx,0x0F
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x0000
         addsx   dw,gx,0x7F
         cmp     dw,0x007F
         bne     TestArui_WWSErr
         mov     aw,0x0000
         subsx   ew,aw,0x7F
         cmp     ew,0xFF81
         bne     TestArui_WWSErr
         mov     bw,0x0000
         andsx   fw,bw,0x7F
         cmp     fw,0x0000
         bne     TestArui_WWSErr
         mov     cw,0x0000
         orsx    gw,cw,0x7F
         cmp     gw,0x007F
         bne     TestArui_WWSErr
         mov     dw,0x0000
         xorsx   ax,dw,0x7F
         cmp     ax,0x007F
         bne     TestArui_WWSErr
         mov     ew,0x0000
         mulsx   bx,ew,0x7F
         cmp     bx,0x0000
         bne     TestArui_WWSErr
         mov     fw,0x0000
         sdivsx  cx,fw,0x7F
         cmp     cx,0x0000
         bne     TestArui_WWSErr
         mov     gw,0x0000
         sremsx  dx,gw,0x7F
         cmp     dx,0x0000
         bne     TestArui_WWSErr
         mov     ax,0x0000
         addsx   ex,ax,0x80
         cmp     ex,0xFF80
         bne     TestArui_WWSErr
         mov     bx,0x0000
         subsx   fx,bx,0x80
         cmp     fx,0x0080
         bne     TestArui_WWSErr
         mov     cx,0x0000
         andsx   gx,cx,0x80
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0000
         orsx    aw,dx,0x80
         cmp     aw,0xFF80
         bne     TestArui_WWSErr
         mov     ex,0x0000
         xorsx   bw,ex,0x80
         cmp     bw,0xFF80
         bne     TestArui_WWSErr
         mov     fx,0x0000
         mulsx   cw,fx,0x80
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x0000
         sdivsx  dw,gx,0x80
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0000
         sremsx  ew,aw,0x80
         cmp     ew,0x0000
         bne     TestArui_WWSErr
         mov     bw,0x0000
         addsx   fw,bw,0xFF
         cmp     fw,0xFFFF
         bne     TestArui_WWSErr
         mov     cw,0x0000
         subsx   gw,cw,0xFF
         cmp     gw,0x0001
         bne     TestArui_WWSErr
         mov     dw,0x0000
         andsx   ax,dw,0xFF
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0000
         orsx    bx,ew,0xFF
         cmp     bx,0xFFFF
         bne     TestArui_WWSErr
         mov     fw,0x0000
         xorsx   cx,fw,0xFF
         cmp     cx,0xFFFF
         bne     TestArui_WWSErr
         mov     gw,0x0000
         mulsx   dx,gw,0xFF
         cmp     dx,0x0000
         bne     TestArui_WWSErr
         mov     ax,0x0000
         sdivsx  ex,ax,0xFF
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x0000
         sremsx  fx,bx,0xFF
         cmp     fx,0x0000
         bne     TestArui_WWSErr
         mov     cx,0x0001
         addsx   gx,cx,0x01
         cmp     gx,0x0002
         bne     TestArui_WWSErr
         mov     dx,0x0001
         subsx   aw,dx,0x01
         cmp     aw,0x0000
         bne     TestArui_WWSErr
         mov     ex,0x0001
         andsx   bw,ex,0x01
         cmp     bw,0x0001
         bne     TestArui_WWSErr
         mov     fx,0x0001
         orsx    cw,fx,0x01
         cmp     cw,0x0001
         bne     TestArui_WWSErr
         mov     gx,0x0001
         xorsx   dw,gx,0x01
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0001
         mulsx   ew,aw,0x01
         cmp     ew,0x0001
         bne     TestArui_WWSErr
         mov     bw,0x0001
         sdivsx  fw,bw,0x01
         cmp     fw,0x0001
         bne     TestArui_WWSErr
         mov     cw,0x0001
         sremsx  gw,cw,0x01
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         mov     dw,0x0001
         addsx   ax,dw,0x07
         cmp     ax,0x0008
         bne     TestArui_WWSErr
         mov     ew,0x0001
         subsx   bx,ew,0x07
         cmp     bx,0xFFFA
         bne     TestArui_WWSErr
         mov     fw,0x0001
         andsx   cx,fw,0x07
         cmp     cx,0x0001
         bne     TestArui_WWSErr
         mov     gw,0x0001
         orsx    dx,gw,0x07
         cmp     dx,0x0007
         bne     TestArui_WWSErr
         mov     ax,0x0001
         xorsx   ex,ax,0x07
         cmp     ex,0x0006
         bne     TestArui_WWSErr
         mov     bx,0x0001
         mulsx   fx,bx,0x07
         cmp     fx,0x0007
         bne     TestArui_WWSErr
         mov     cx,0x0001
         sdivsx  gx,cx,0x07
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0001
         sremsx  aw,dx,0x07
         cmp     aw,0x0001
         bne     TestArui_WWSErr
         mov     ex,0x0001
         addsx   bw,ex,0x08
         cmp     bw,0x0009
         bne     TestArui_WWSErr
         mov     fx,0x0001
         subsx   cw,fx,0x08
         cmp     cw,0xFFF9
         bne     TestArui_WWSErr
         mov     gx,0x0001
         andsx   dw,gx,0x08
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0001
         orsx    ew,aw,0x08
         cmp     ew,0x0009
         bne     TestArui_WWSErr
         mov     bw,0x0001
         xorsx   fw,bw,0x08
         cmp     fw,0x0009
         bne     TestArui_WWSErr
         mov     cw,0x0001
         mulsx   gw,cw,0x08
         cmp     gw,0x0008
         bne     TestArui_WWSErr
         mov     dw,0x0001
         sdivsx  ax,dw,0x08
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0001
         sremsx  bx,ew,0x08
         cmp     bx,0x0001
         bne     TestArui_WWSErr
         mov     fw,0x0001
         addsx   cx,fw,0x09
         cmp     cx,0x000A
         bne     TestArui_WWSErr
         mov     gw,0x0001
         subsx   dx,gw,0x09
         cmp     dx,0xFFF8
         bne     TestArui_WWSErr
         mov     ax,0x0001
         andsx   ex,ax,0x09
         cmp     ex,0x0001
         bne     TestArui_WWSErr
         mov     bx,0x0001
         orsx    fx,bx,0x09
         cmp     fx,0x0009
         bne     TestArui_WWSErr
         mov     cx,0x0001
         xorsx   gx,cx,0x09
         cmp     gx,0x0008
         bne     TestArui_WWSErr
         mov     dx,0x0001
         mulsx   aw,dx,0x09
         cmp     aw,0x0009
         bne     TestArui_WWSErr
         mov     ex,0x0001
         sdivsx  bw,ex,0x09
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x0001
         sremsx  cw,fx,0x09
         cmp     cw,0x0001
         bne     TestArui_WWSErr
         mov     gx,0x0001
         addsx   dw,gx,0x0F
         cmp     dw,0x0010
         bne     TestArui_WWSErr
         mov     aw,0x0001
         subsx   ew,aw,0x0F
         cmp     ew,0xFFF2
         bne     TestArui_WWSErr
         mov     bw,0x0001
         andsx   fw,bw,0x0F
         cmp     fw,0x0001
         bne     TestArui_WWSErr
         mov     cw,0x0001
         orsx    gw,cw,0x0F
         cmp     gw,0x000F
         bne     TestArui_WWSErr
         mov     dw,0x0001
         xorsx   ax,dw,0x0F
         cmp     ax,0x000E
         bne     TestArui_WWSErr
         mov     ew,0x0001
         mulsx   bx,ew,0x0F
         cmp     bx,0x000F
         bne     TestArui_WWSErr
         mov     fw,0x0001
         sdivsx  cx,fw,0x0F
         cmp     cx,0x0000
         bne     TestArui_WWSErr
         mov     gw,0x0001
         sremsx  dx,gw,0x0F
         cmp     dx,0x0001
         bne     TestArui_WWSErr
         mov     ax,0x0001
         addsx   ex,ax,0x7F
         cmp     ex,0x0080
         bne     TestArui_WWSErr
         mov     bx,0x0001
         subsx   fx,bx,0x7F
         cmp     fx,0xFF82
         bne     TestArui_WWSErr
         mov     cx,0x0001
         andsx   gx,cx,0x7F
         cmp     gx,0x0001
         bne     TestArui_WWSErr
         mov     dx,0x0001
         orsx    aw,dx,0x7F
         cmp     aw,0x007F
         bne     TestArui_WWSErr
         mov     ex,0x0001
         xorsx   bw,ex,0x7F
         cmp     bw,0x007E
         bne     TestArui_WWSErr
         mov     fx,0x0001
         mulsx   cw,fx,0x7F
         cmp     cw,0x007F
         bne     TestArui_WWSErr
         mov     gx,0x0001
         sdivsx  dw,gx,0x7F
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0001
         sremsx  ew,aw,0x7F
         cmp     ew,0x0001
         bne     TestArui_WWSErr
         mov     bw,0x0001
         addsx   fw,bw,0x80
         cmp     fw,0xFF81
         bne     TestArui_WWSErr
         mov     cw,0x0001
         subsx   gw,cw,0x80
         cmp     gw,0x0081
         bne     TestArui_WWSErr
         mov     dw,0x0001
         andsx   ax,dw,0x80
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0001
         orsx    bx,ew,0x80
         cmp     bx,0xFF81
         bne     TestArui_WWSErr
         mov     fw,0x0001
         xorsx   cx,fw,0x80
         cmp     cx,0xFF81
         bne     TestArui_WWSErr
         mov     gw,0x0001
         mulsx   dx,gw,0x80
         cmp     dx,0xFF80
         bne     TestArui_WWSErr
         mov     ax,0x0001
         sdivsx  ex,ax,0x80
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x0001
         sremsx  fx,bx,0x80
         cmp     fx,0x0001
         bne     TestArui_WWSErr
         mov     cx,0x0001
         addsx   gx,cx,0xFF
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0001
         subsx   aw,dx,0xFF
         cmp     aw,0x0002
         bne     TestArui_WWSErr
         mov     ex,0x0001
         andsx   bw,ex,0xFF
         cmp     bw,0x0001
         bne     TestArui_WWSErr
         mov     fx,0x0001
         orsx    cw,fx,0xFF
         cmp     cw,0xFFFF
         bne     TestArui_WWSErr
         mov     gx,0x0001
         xorsx   dw,gx,0xFF
         cmp     dw,0xFFFE
         bne     TestArui_WWSErr
         mov     aw,0x0001
         mulsx   ew,aw,0xFF
         cmp     ew,0xFFFF
         bne     TestArui_WWSErr
         mov     bw,0x0001
         sdivsx  fw,bw,0xFF
         cmp     fw,0xFFFF
         bne     TestArui_WWSErr
         mov     cw,0x0001
         sremsx  gw,cw,0xFF
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         mov     dw,0x0008
         addsx   ax,dw,0x07
         cmp     ax,0x000F
         bne     TestArui_WWSErr
         mov     ew,0x0008
         subsx   bx,ew,0x07
         cmp     bx,0x0001
         bne     TestArui_WWSErr
         mov     fw,0x0008
         andsx   cx,fw,0x07
         cmp     cx,0x0000
         bne     TestArui_WWSErr
         mov     gw,0x0008
         orsx    dx,gw,0x07
         cmp     dx,0x000F
         bne     TestArui_WWSErr
         mov     ax,0x0008
         xorsx   ex,ax,0x07
         cmp     ex,0x000F
         bne     TestArui_WWSErr
         mov     bx,0x0008
         mulsx   fx,bx,0x07
         cmp     fx,0x0038
         bne     TestArui_WWSErr
         mov     cx,0x0008
         sdivsx  gx,cx,0x07
         cmp     gx,0x0001
         bne     TestArui_WWSErr
         mov     dx,0x0008
         sremsx  aw,dx,0x07
         cmp     aw,0x0001
         bne     TestArui_WWSErr
         mov     ex,0x0008
         addsx   bw,ex,0x08
         cmp     bw,0x0010
         bne     TestArui_WWSErr
         mov     fx,0x0008
         subsx   cw,fx,0x08
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x0008
         andsx   dw,gx,0x08
         cmp     dw,0x0008
         bne     TestArui_WWSErr
         mov     aw,0x0008
         orsx    ew,aw,0x08
         cmp     ew,0x0008
         bne     TestArui_WWSErr
         mov     bw,0x0008
         xorsx   fw,bw,0x08
         cmp     fw,0x0000
         bne     TestArui_WWSErr
         mov     cw,0x0008
         mulsx   gw,cw,0x08
         cmp     gw,0x0040
         bne     TestArui_WWSErr
         mov     dw,0x0008
         sdivsx  ax,dw,0x08
         cmp     ax,0x0001
         bne     TestArui_WWSErr
         mov     ew,0x0008
         sremsx  bx,ew,0x08
         cmp     bx,0x0000
         bne     TestArui_WWSErr
         mov     fw,0x0008
         addsx   cx,fw,0x09
         cmp     cx,0x0011
         bne     TestArui_WWSErr
         mov     gw,0x0008
         subsx   dx,gw,0x09
         cmp     dx,0xFFFF
         bne     TestArui_WWSErr
         mov     ax,0x0008
         andsx   ex,ax,0x09
         cmp     ex,0x0008
         bne     TestArui_WWSErr
         mov     bx,0x0008
         orsx    fx,bx,0x09
         cmp     fx,0x0009
         bne     TestArui_WWSErr
         mov     cx,0x0008
         xorsx   gx,cx,0x09
         cmp     gx,0x0001
         bne     TestArui_WWSErr
         mov     dx,0x0008
         mulsx   aw,dx,0x09
         cmp     aw,0x0048
         bne     TestArui_WWSErr
         mov     ex,0x0008
         sdivsx  bw,ex,0x09
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x0008
         sremsx  cw,fx,0x09
         cmp     cw,0x0008
         bne     TestArui_WWSErr
         mov     gx,0x0008
         addsx   dw,gx,0x0F
         cmp     dw,0x0017
         bne     TestArui_WWSErr
         mov     aw,0x0008
         subsx   ew,aw,0x0F
         cmp     ew,0xFFF9
         bne     TestArui_WWSErr
         mov     bw,0x0008
         andsx   fw,bw,0x0F
         cmp     fw,0x0008
         bne     TestArui_WWSErr
         mov     cw,0x0008
         orsx    gw,cw,0x0F
         cmp     gw,0x000F
         bne     TestArui_WWSErr
         mov     dw,0x0008
         xorsx   ax,dw,0x0F
         cmp     ax,0x0007
         bne     TestArui_WWSErr
         mov     ew,0x0008
         mulsx   bx,ew,0x0F
         cmp     bx,0x0078
         bne     TestArui_WWSErr
         mov     fw,0x0008
         sdivsx  cx,fw,0x0F
         cmp     cx,0x0000
         bne     TestArui_WWSErr
         mov     gw,0x0008
         sremsx  dx,gw,0x0F
         cmp     dx,0x0008
         bne     TestArui_WWSErr
         mov     ax,0x0008
         addsx   ex,ax,0x7F
         cmp     ex,0x0087
         bne     TestArui_WWSErr
         mov     bx,0x0008
         subsx   fx,bx,0x7F
         cmp     fx,0xFF89
         bne     TestArui_WWSErr
         mov     cx,0x0008
         andsx   gx,cx,0x7F
         cmp     gx,0x0008
         bne     TestArui_WWSErr
         mov     dx,0x0008
         orsx    aw,dx,0x7F
         cmp     aw,0x007F
         bne     TestArui_WWSErr
         mov     ex,0x0008
         xorsx   bw,ex,0x7F
         cmp     bw,0x0077
         bne     TestArui_WWSErr
         mov     fx,0x0008
         mulsx   cw,fx,0x7F
         cmp     cw,0x03F8
         bne     TestArui_WWSErr
         mov     gx,0x0008
         sdivsx  dw,gx,0x7F
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0008
         sremsx  ew,aw,0x7F
         cmp     ew,0x0008
         bne     TestArui_WWSErr
         mov     bw,0x0008
         addsx   fw,bw,0x80
         cmp     fw,0xFF88
         bne     TestArui_WWSErr
         mov     cw,0x0008
         subsx   gw,cw,0x80
         cmp     gw,0x0088
         bne     TestArui_WWSErr
         mov     dw,0x0008
         andsx   ax,dw,0x80
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0008
         orsx    bx,ew,0x80
         cmp     bx,0xFF88
         bne     TestArui_WWSErr
         mov     fw,0x0008
         xorsx   cx,fw,0x80
         cmp     cx,0xFF88
         bne     TestArui_WWSErr
         mov     gw,0x0008
         mulsx   dx,gw,0x80
         cmp     dx,0xFC00
         bne     TestArui_WWSErr
         mov     ax,0x0008
         sdivsx  ex,ax,0x80
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x0008
         sremsx  fx,bx,0x80
         cmp     fx,0x0008
         bne     TestArui_WWSErr
         mov     cx,0x0008
         addsx   gx,cx,0xFF
         cmp     gx,0x0007
         bne     TestArui_WWSErr
         mov     dx,0x0008
         subsx   aw,dx,0xFF
         cmp     aw,0x0009
         bne     TestArui_WWSErr
         mov     ex,0x0008
         andsx   bw,ex,0xFF
         cmp     bw,0x0008
         bne     TestArui_WWSErr
         mov     fx,0x0008
         orsx    cw,fx,0xFF
         cmp     cw,0xFFFF
         bne     TestArui_WWSErr
         mov     gx,0x0008
         xorsx   dw,gx,0xFF
         cmp     dw,0xFFF7
         bne     TestArui_WWSErr
         mov     aw,0x0008
         mulsx   ew,aw,0xFF
         cmp     ew,0xFFF8
         bne     TestArui_WWSErr
         mov     bw,0x0008
         sdivsx  fw,bw,0xFF
         cmp     fw,0xFFF8
         bne     TestArui_WWSErr
         mov     cw,0x0008
         sremsx  gw,cw,0xFF
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         mov     dw,0x0009
         addsx   ax,dw,0x08
         cmp     ax,0x0011
         bne     TestArui_WWSErr
         mov     ew,0x0009
         subsx   bx,ew,0x08
         cmp     bx,0x0001
         bne     TestArui_WWSErr
         mov     fw,0x0009
         andsx   cx,fw,0x08
         cmp     cx,0x0008
         bne     TestArui_WWSErr
         mov     gw,0x0009
         orsx    dx,gw,0x08
         cmp     dx,0x0009
         bne     TestArui_WWSErr
         mov     ax,0x0009
         xorsx   ex,ax,0x08
         cmp     ex,0x0001
         bne     TestArui_WWSErr
         mov     bx,0x0009
         mulsx   fx,bx,0x08
         cmp     fx,0x0048
         bne     TestArui_WWSErr
         mov     cx,0x0009
         sdivsx  gx,cx,0x08
         cmp     gx,0x0001
         bne     TestArui_WWSErr
         mov     dx,0x0009
         sremsx  aw,dx,0x08
         cmp     aw,0x0001
         bne     TestArui_WWSErr
         mov     ex,0x0009
         addsx   bw,ex,0x09
         cmp     bw,0x0012
         bne     TestArui_WWSErr
         mov     fx,0x0009
         subsx   cw,fx,0x09
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x0009
         andsx   dw,gx,0x09
         cmp     dw,0x0009
         bne     TestArui_WWSErr
         mov     aw,0x0009
         orsx    ew,aw,0x09
         cmp     ew,0x0009
         bne     TestArui_WWSErr
         mov     bw,0x0009
         xorsx   fw,bw,0x09
         cmp     fw,0x0000
         bne     TestArui_WWSErr
         mov     cw,0x0009
         mulsx   gw,cw,0x09
         cmp     gw,0x0051
         bne     TestArui_WWSErr
         mov     dw,0x0009
         sdivsx  ax,dw,0x09
         cmp     ax,0x0001
         bne     TestArui_WWSErr
         mov     ew,0x0009
         sremsx  bx,ew,0x09
         cmp     bx,0x0000
         bne     TestArui_WWSErr
         mov     fw,0x0009
         addsx   cx,fw,0x0F
         cmp     cx,0x0018
         bne     TestArui_WWSErr
         mov     gw,0x0009
         subsx   dx,gw,0x0F
         cmp     dx,0xFFFA
         bne     TestArui_WWSErr
         mov     ax,0x0009
         andsx   ex,ax,0x0F
         cmp     ex,0x0009
         bne     TestArui_WWSErr
         mov     bx,0x0009
         orsx    fx,bx,0x0F
         cmp     fx,0x000F
         bne     TestArui_WWSErr
         mov     cx,0x0009
         xorsx   gx,cx,0x0F
         cmp     gx,0x0006
         bne     TestArui_WWSErr
         mov     dx,0x0009
         mulsx   aw,dx,0x0F
         cmp     aw,0x0087
         bne     TestArui_WWSErr
         mov     ex,0x0009
         sdivsx  bw,ex,0x0F
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x0009
         sremsx  cw,fx,0x0F
         cmp     cw,0x0009
         bne     TestArui_WWSErr
         mov     gx,0x0009
         addsx   dw,gx,0x7F
         cmp     dw,0x0088
         bne     TestArui_WWSErr
         mov     aw,0x0009
         subsx   ew,aw,0x7F
         cmp     ew,0xFF8A
         bne     TestArui_WWSErr
         mov     bw,0x0009
         andsx   fw,bw,0x7F
         cmp     fw,0x0009
         bne     TestArui_WWSErr
         mov     cw,0x0009
         orsx    gw,cw,0x7F
         cmp     gw,0x007F
         bne     TestArui_WWSErr
         mov     dw,0x0009
         xorsx   ax,dw,0x7F
         cmp     ax,0x0076
         bne     TestArui_WWSErr
         mov     ew,0x0009
         mulsx   bx,ew,0x7F
         cmp     bx,0x0477
         bne     TestArui_WWSErr
         mov     fw,0x0009
         sdivsx  cx,fw,0x7F
         cmp     cx,0x0000
         bne     TestArui_WWSErr
         mov     gw,0x0009
         sremsx  dx,gw,0x7F
         cmp     dx,0x0009
         bne     TestArui_WWSErr
         mov     ax,0x0009
         addsx   ex,ax,0x80
         cmp     ex,0xFF89
         bne     TestArui_WWSErr
         mov     bx,0x0009
         subsx   fx,bx,0x80
         cmp     fx,0x0089
         bne     TestArui_WWSErr
         mov     cx,0x0009
         andsx   gx,cx,0x80
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0009
         orsx    aw,dx,0x80
         cmp     aw,0xFF89
         bne     TestArui_WWSErr
         mov     ex,0x0009
         xorsx   bw,ex,0x80
         cmp     bw,0xFF89
         bne     TestArui_WWSErr
         mov     fx,0x0009
         mulsx   cw,fx,0x80
         cmp     cw,0xFB80
         bne     TestArui_WWSErr
         mov     gx,0x0009
         sdivsx  dw,gx,0x80
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0x0009
         sremsx  ew,aw,0x80
         cmp     ew,0x0009
         bne     TestArui_WWSErr
         mov     bw,0x0009
         addsx   fw,bw,0xFF
         cmp     fw,0x0008
         bne     TestArui_WWSErr
         mov     cw,0x0009
         subsx   gw,cw,0xFF
         cmp     gw,0x000A
         bne     TestArui_WWSErr
         mov     dw,0x0009
         andsx   ax,dw,0xFF
         cmp     ax,0x0009
         bne     TestArui_WWSErr
         mov     ew,0x0009
         orsx    bx,ew,0xFF
         cmp     bx,0xFFFF
         bne     TestArui_WWSErr
         mov     fw,0x0009
         xorsx   cx,fw,0xFF
         cmp     cx,0xFFF6
         bne     TestArui_WWSErr
         mov     gw,0x0009
         mulsx   dx,gw,0xFF
         cmp     dx,0xFFF7
         bne     TestArui_WWSErr
         mov     ax,0x0009
         sdivsx  ex,ax,0xFF
         cmp     ex,0xFFF7
         bne     TestArui_WWSErr
         mov     bx,0x0009
         sremsx  fx,bx,0xFF
         cmp     fx,0x0000
         bne     TestArui_WWSErr
         mov     cx,0x007F
         addsx   gx,cx,0x09
         cmp     gx,0x0088
         bne     TestArui_WWSErr
         mov     dx,0x007F
         subsx   aw,dx,0x09
         cmp     aw,0x0076
         bne     TestArui_WWSErr
         mov     ex,0x007F
         andsx   bw,ex,0x09
         cmp     bw,0x0009
         bne     TestArui_WWSErr
         mov     fx,0x007F
         orsx    cw,fx,0x09
         cmp     cw,0x007F
         bne     TestArui_WWSErr
         mov     gx,0x007F
         xorsx   dw,gx,0x09
         cmp     dw,0x0076
         bne     TestArui_WWSErr
         mov     aw,0x007F
         mulsx   ew,aw,0x09
         cmp     ew,0x0477
         bne     TestArui_WWSErr
         mov     bw,0x007F
         sdivsx  fw,bw,0x09
         cmp     fw,0x000E
         bne     TestArui_WWSErr
         mov     cw,0x007F
         sremsx  gw,cw,0x09
         cmp     gw,0x0001
         bne     TestArui_WWSErr
         mov     dw,0x007F
         addsx   ax,dw,0x0F
         cmp     ax,0x008E
         bne     TestArui_WWSErr
         mov     ew,0x007F
         subsx   bx,ew,0x0F
         cmp     bx,0x0070
         bne     TestArui_WWSErr
         mov     fw,0x007F
         andsx   cx,fw,0x0F
         cmp     cx,0x000F
         bne     TestArui_WWSErr
         mov     gw,0x007F
         orsx    dx,gw,0x0F
         cmp     dx,0x007F
         bne     TestArui_WWSErr
         mov     ax,0x007F
         xorsx   ex,ax,0x0F
         cmp     ex,0x0070
         bne     TestArui_WWSErr
         mov     bx,0x007F
         mulsx   fx,bx,0x0F
         cmp     fx,0x0771
         bne     TestArui_WWSErr
         mov     cx,0x007F
         sdivsx  gx,cx,0x0F
         cmp     gx,0x0008
         bne     TestArui_WWSErr
         mov     dx,0x007F
         sremsx  aw,dx,0x0F
         cmp     aw,0x0007
         bne     TestArui_WWSErr
         mov     ex,0x007F
         addsx   bw,ex,0x7F
         cmp     bw,0x00FE
         bne     TestArui_WWSErr
         mov     fx,0x007F
         subsx   cw,fx,0x7F
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x007F
         andsx   dw,gx,0x7F
         cmp     dw,0x007F
         bne     TestArui_WWSErr
         mov     aw,0x007F
         orsx    ew,aw,0x7F
         cmp     ew,0x007F
         bne     TestArui_WWSErr
         mov     bw,0x007F
         xorsx   fw,bw,0x7F
         cmp     fw,0x0000
         bne     TestArui_WWSErr
         mov     cw,0x007F
         mulsx   gw,cw,0x7F
         cmp     gw,0x3F01
         bne     TestArui_WWSErr
         mov     dw,0x007F
         sdivsx  ax,dw,0x7F
         cmp     ax,0x0001
         bne     TestArui_WWSErr
         mov     ew,0x007F
         sremsx  bx,ew,0x7F
         cmp     bx,0x0000
         bne     TestArui_WWSErr
         mov     fw,0x007F
         addsx   cx,fw,0x80
         cmp     cx,0xFFFF
         bne     TestArui_WWSErr
         mov     gw,0x007F
         subsx   dx,gw,0x80
         cmp     dx,0x00FF
         bne     TestArui_WWSErr
         mov     ax,0x007F
         andsx   ex,ax,0x80
         cmp     ex,0x0000
         bne     TestArui_WWSErr
         mov     bx,0x007F
         orsx    fx,bx,0x80
         cmp     fx,0xFFFF
         bne     TestArui_WWSErr
         mov     cx,0x007F
         xorsx   gx,cx,0x80
         cmp     gx,0xFFFF
         bne     TestArui_WWSErr
         mov     dx,0x007F
         mulsx   aw,dx,0x80
         cmp     aw,0xC080
         bne     TestArui_WWSErr
         mov     ex,0x007F
         sdivsx  bw,ex,0x80
         cmp     bw,0x0000
         bne     TestArui_WWSErr
         mov     fx,0x007F
         sremsx  cw,fx,0x80
         cmp     cw,0x007F
         bne     TestArui_WWSErr
         mov     gx,0x007F
         addsx   dw,gx,0xFF
         cmp     dw,0x007E
         bne     TestArui_WWSErr
         mov     aw,0x007F
         subsx   ew,aw,0xFF
         cmp     ew,0x0080
         bne     TestArui_WWSErr
         mov     bw,0x007F
         andsx   fw,bw,0xFF
         cmp     fw,0x007F
         bne     TestArui_WWSErr
         mov     cw,0x007F
         orsx    gw,cw,0xFF
         cmp     gw,0xFFFF
         bne     TestArui_WWSErr
         mov     dw,0x007F
         xorsx   ax,dw,0xFF
         cmp     ax,0xFF80
         bne     TestArui_WWSErr
         mov     ew,0x007F
         mulsx   bx,ew,0xFF
         cmp     bx,0xFF81
         bne     TestArui_WWSErr
         mov     fw,0x007F
         sdivsx  cx,fw,0xFF
         cmp     cx,0xFF81
         bne     TestArui_WWSErr
         mov     gw,0x007F
         sremsx  dx,gw,0xFF
         cmp     dx,0x0000
         bne     TestArui_WWSErr
         mov     ax,0x0080
         addsx   ex,ax,0x0F
         cmp     ex,0x008F
         bne     TestArui_WWSErr
         mov     bx,0x0080
         subsx   fx,bx,0x0F
         cmp     fx,0x0071
         bne     TestArui_WWSErr
         mov     cx,0x0080
         andsx   gx,cx,0x0F
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0080
         orsx    aw,dx,0x0F
         cmp     aw,0x008F
         bne     TestArui_WWSErr
         mov     ex,0x0080
         xorsx   bw,ex,0x0F
         cmp     bw,0x008F
         bne     TestArui_WWSErr
         mov     fx,0x0080
         mulsx   cw,fx,0x0F
         cmp     cw,0x0780
         bne     TestArui_WWSErr
         mov     gx,0x0080
         sdivsx  dw,gx,0x0F
         cmp     dw,0x0008
         bne     TestArui_WWSErr
         mov     aw,0x0080
         sremsx  ew,aw,0x0F
         cmp     ew,0x0008
         bne     TestArui_WWSErr
         mov     bw,0x0080
         addsx   fw,bw,0x7F
         cmp     fw,0x00FF
         bne     TestArui_WWSErr
         mov     cw,0x0080
         subsx   gw,cw,0x7F
         cmp     gw,0x0001
         bne     TestArui_WWSErr
         mov     dw,0x0080
         andsx   ax,dw,0x7F
         cmp     ax,0x0000
         bne     TestArui_WWSErr
         mov     ew,0x0080
         orsx    bx,ew,0x7F
         cmp     bx,0x00FF
         bne     TestArui_WWSErr
         mov     fw,0x0080
         xorsx   cx,fw,0x7F
         cmp     cx,0x00FF
         bne     TestArui_WWSErr
         mov     gw,0x0080
         mulsx   dx,gw,0x7F
         cmp     dx,0x3F80
         bne     TestArui_WWSErr
         mov     ax,0x0080
         sdivsx  ex,ax,0x7F
         cmp     ex,0x0001
         bne     TestArui_WWSErr
         mov     bx,0x0080
         sremsx  fx,bx,0x7F
         cmp     fx,0x0001
         bne     TestArui_WWSErr
         mov     cx,0x0080
         addsx   gx,cx,0x80
         cmp     gx,0x0000
         bne     TestArui_WWSErr
         mov     dx,0x0080
         subsx   aw,dx,0x80
         cmp     aw,0x0100
         bne     TestArui_WWSErr
         mov     ex,0x0080
         andsx   bw,ex,0x80
         cmp     bw,0x0080
         bne     TestArui_WWSErr
         mov     fx,0x0080
         orsx    cw,fx,0x80
         cmp     cw,0xFF80
         bne     TestArui_WWSErr
         mov     gx,0x0080
         xorsx   dw,gx,0x80
         cmp     dw,0xFF00
         bne     TestArui_WWSErr
         mov     aw,0x0080
         mulsx   ew,aw,0x80
         cmp     ew,0xC000
         bne     TestArui_WWSErr
         mov     bw,0x0080
         sdivsx  fw,bw,0x80
         cmp     fw,0xFFFF
         bne     TestArui_WWSErr
         mov     cw,0x0080
         sremsx  gw,cw,0x80
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         mov     dw,0x0080
         addsx   ax,dw,0xFF
         cmp     ax,0x007F
         bne     TestArui_WWSErr
         mov     ew,0x0080
         subsx   bx,ew,0xFF
         cmp     bx,0x0081
         bne     TestArui_WWSErr
         mov     fw,0x0080
         andsx   cx,fw,0xFF
         cmp     cx,0x0080
         bne     TestArui_WWSErr
         mov     gw,0x0080
         orsx    dx,gw,0xFF
         cmp     dx,0xFFFF
         bne     TestArui_WWSErr
         mov     ax,0x0080
         xorsx   ex,ax,0xFF
         cmp     ex,0xFF7F
         bne     TestArui_WWSErr
         mov     bx,0x0080
         mulsx   fx,bx,0xFF
         cmp     fx,0xFF80
         bne     TestArui_WWSErr
         mov     cx,0x0080
         sdivsx  gx,cx,0xFF
         cmp     gx,0xFF80
         bne     TestArui_WWSErr
         mov     dx,0x0080
         sremsx  aw,dx,0xFF
         cmp     aw,0x0000
         bne     TestArui_WWSErr
         mov     ex,0x7FFF
         addsx   bw,ex,0x7F
         cmp     bw,0x807E
         bne     TestArui_WWSErr
         mov     fx,0x7FFF
         subsx   cw,fx,0x7F
         cmp     cw,0x7F80
         bne     TestArui_WWSErr
         mov     gx,0x7FFF
         andsx   dw,gx,0x7F
         cmp     dw,0x007F
         bne     TestArui_WWSErr
         mov     aw,0x7FFF
         orsx    ew,aw,0x7F
         cmp     ew,0x7FFF
         bne     TestArui_WWSErr
         mov     bw,0x7FFF
         xorsx   fw,bw,0x7F
         cmp     fw,0x7F80
         bne     TestArui_WWSErr
         mov     cw,0x7FFF
         mulsx   gw,cw,0x7F
         cmp     gw,0x7F81
         bne     TestArui_WWSErr
         mov     dw,0x7FFF
         sdivsx  ax,dw,0x7F
         cmp     ax,0x0102
         bne     TestArui_WWSErr
         mov     ew,0x7FFF
         sremsx  bx,ew,0x7F
         cmp     bx,0x0001
         bne     TestArui_WWSErr
         mov     fw,0x7FFF
         addsx   cx,fw,0x80
         cmp     cx,0x7F7F
         bne     TestArui_WWSErr
         mov     gw,0x7FFF
         subsx   dx,gw,0x80
         cmp     dx,0x807F
         bne     TestArui_WWSErr
         mov     ax,0x7FFF
         andsx   ex,ax,0x80
         cmp     ex,0x7F80
         bne     TestArui_WWSErr
         mov     bx,0x7FFF
         orsx    fx,bx,0x80
         cmp     fx,0xFFFF
         bne     TestArui_WWSErr
         mov     cx,0x7FFF
         xorsx   gx,cx,0x80
         cmp     gx,0x807F
         bne     TestArui_WWSErr
         mov     dx,0x7FFF
         mulsx   aw,dx,0x80
         cmp     aw,0x0080
         bne     TestArui_WWSErr
         mov     ex,0x7FFF
         sdivsx  bw,ex,0x80
         cmp     bw,0xFF01
         bne     TestArui_WWSErr
         mov     fx,0x7FFF
         sremsx  cw,fx,0x80
         cmp     cw,0x007F
         bne     TestArui_WWSErr
         mov     gx,0x7FFF
         addsx   dw,gx,0xFF
         cmp     dw,0x7FFE
         bne     TestArui_WWSErr
         mov     aw,0x7FFF
         subsx   ew,aw,0xFF
         cmp     ew,0x8000
         bne     TestArui_WWSErr
         mov     bw,0x7FFF
         andsx   fw,bw,0xFF
         cmp     fw,0x7FFF
         bne     TestArui_WWSErr
         mov     cw,0x7FFF
         orsx    gw,cw,0xFF
         cmp     gw,0xFFFF
         bne     TestArui_WWSErr
         mov     dw,0x7FFF
         xorsx   ax,dw,0xFF
         cmp     ax,0x8000
         bne     TestArui_WWSErr
         mov     ew,0x7FFF
         mulsx   bx,ew,0xFF
         cmp     bx,0x8001
         bne     TestArui_WWSErr
         mov     fw,0x7FFF
         sdivsx  cx,fw,0xFF
         cmp     cx,0x8001
         bne     TestArui_WWSErr
         mov     gw,0x7FFF
         sremsx  dx,gw,0xFF
         cmp     dx,0x0000
         bne     TestArui_WWSErr
         mov     ax,0x8000
         addsx   ex,ax,0x80
         cmp     ex,0x7F80
         bne     TestArui_WWSErr
         mov     bx,0x8000
         subsx   fx,bx,0x80
         cmp     fx,0x8080
         bne     TestArui_WWSErr
         mov     cx,0x8000
         andsx   gx,cx,0x80
         cmp     gx,0x8000
         bne     TestArui_WWSErr
         mov     dx,0x8000
         orsx    aw,dx,0x80
         cmp     aw,0xFF80
         bne     TestArui_WWSErr
         mov     ex,0x8000
         xorsx   bw,ex,0x80
         cmp     bw,0x7F80
         bne     TestArui_WWSErr
         mov     fx,0x8000
         mulsx   cw,fx,0x80
         cmp     cw,0x0000
         bne     TestArui_WWSErr
         mov     gx,0x8000
         sdivsx  dw,gx,0x80
         cmp     dw,0x0100
         bne     TestArui_WWSErr
         mov     aw,0x8000
         sremsx  ew,aw,0x80
         cmp     ew,0x0000
         bne     TestArui_WWSErr
         mov     bw,0x8000
         addsx   fw,bw,0xFF
         cmp     fw,0x7FFF
         bne     TestArui_WWSErr
         mov     cw,0x8000
         subsx   gw,cw,0xFF
         cmp     gw,0x8001
         bne     TestArui_WWSErr
         mov     dw,0x8000
         andsx   ax,dw,0xFF
         cmp     ax,0x8000
         bne     TestArui_WWSErr
         mov     ew,0x8000
         orsx    bx,ew,0xFF
         cmp     bx,0xFFFF
         bne     TestArui_WWSErr
         mov     fw,0x8000
         xorsx   cx,fw,0xFF
         cmp     cx,0x7FFF
         bne     TestArui_WWSErr
         mov     gw,0x8000
         mulsx   dx,gw,0xFF
         cmp     dx,0x8000
         bne     TestArui_WWSErr
         mov     ax,0x8000
         sdivsx  ex,ax,0xFF
         cmp     ex,0x8000
         bne     TestArui_WWSErr
         mov     bx,0x8000
         sremsx  fx,bx,0xFF
         cmp     fx,0x0000
         bne     TestArui_WWSErr
         mov     cx,0xFFFF
         addsx   gx,cx,0xFF
         cmp     gx,0xFFFE
         bne     TestArui_WWSErr
         mov     dx,0xFFFF
         subsx   aw,dx,0xFF
         cmp     aw,0x0000
         bne     TestArui_WWSErr
         mov     ex,0xFFFF
         andsx   bw,ex,0xFF
         cmp     bw,0xFFFF
         bne     TestArui_WWSErr
         mov     fx,0xFFFF
         orsx    cw,fx,0xFF
         cmp     cw,0xFFFF
         bne     TestArui_WWSErr
         mov     gx,0xFFFF
         xorsx   dw,gx,0xFF
         cmp     dw,0x0000
         bne     TestArui_WWSErr
         mov     aw,0xFFFF
         mulsx   ew,aw,0xFF
         cmp     ew,0x0001
         bne     TestArui_WWSErr
         mov     bw,0xFFFF
         sdivsx  fw,bw,0xFF
         cmp     fw,0x0001
         bne     TestArui_WWSErr
         mov     cw,0xFFFF
         sremsx  gw,cw,0xFF
         cmp     gw,0x0000
         bne     TestArui_WWSErr
         bra     TestArui_WWSRet
TestArui_WWSErr:
         nop     
         trap    
         nop     
TestArui_WWSRet:
         leave   awx|bwx|cwx|dwx|ewx|fwx|gwx|ar|br|cr|dr|er|fr|gr,0,0
