.globl StartC
.globl StartD

.data
        .Align 8
FContextRV:
        dd 0 dup(20)


        dd 0 dup(64)
FStack:

FDataA: db 0


.text
StartC:
        lui     t0,%hi(FStack)
        addi    sp,t0,%lo(FStack)

    prvSwtTest:

        li      t0,13
    prvWait:
        addi    t0,t0,-1
        bne     t0,zero,prvWait

        #addi    sp,sp,-12
        #addi    sp,sp,12

        #call    leadAngleController

        addi    t1,t0,0x10
        addi    t1,t1,0x02

        #call    ProcessR

    prLoop:
        j       prvSwtTest


StartD:
     sdLoop:
        addi    t1,t1,1
        addi    t0,t0,2
        addi    s1,s1,1
        addi    s1,s1,3
        addi    s0,s0,3
        j       sdLoop


